Repository ampproject/amphtml, pull requests merged in 2018-08, with the labels that each got.

#17225 🔥 Call onMeasureChanged after firstAttachedCallback
  extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
Labels: cla: yes

#17037 Add amp-ad support for videointelligence
  3p/integration.js
  ads/_config.js
  ads/videointelligence.js
  ads/videointelligence.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#17226 📖 Updated information on inline styling allowed in AMP
  spec/amp-html-components.md
  spec/amp-html-format.md
Labels: cla: yes

#17231 🐛 Fix a flakiness of amp-analytics vendor request tests.
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/vendor-requests.json
Labels: cla: yes

#17229 amp-bind: scanAndApply() without DOM walking
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-list/0.1/amp-list.js
  src/purifier.js
  src/sanitizer.js
  test/functional/test-purifier.js
  test/functional/test-sanitizer.js
  tools/experiments/experiments.js
Labels: cla: yes

#17158 Revert "amp-mustache: Un-deprecate 0.1"
  extensions/amp-mustache/0.1/test/validator-amp-mustache-version.out
  extensions/amp-mustache/validator-amp-mustache.protoascii
Labels: cla: yes

#17242 Avoid unnecessary DOM serialization in amp-mustache-0.2
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-mustache/0.2/amp-mustache.js
  src/purifier.js
  test/functional/test-purifier.js
Labels: cla: yes

#17249 🚮 Remove the internalRuntimeToken
  build-system/internal-version.js
  build-system/tasks/compile.js
  gulpfile.js
Labels: cla: yes

#17253 📖Added validation section
  extensions/amp-geo/amp-geo.md
Labels: cla: yes

#17085 🐛amp-3d-gltf: add attribute clearColor
  3p/3d-gltf/viewer.js
  ads/ads.extern.js
  examples/amp-3d-gltf.amp.html
  extensions/amp-3d-gltf/0.1/amp-3d-gltf.js
  extensions/amp-3d-gltf/amp-3d-gltf.md
  extensions/amp-3d-gltf/validator-amp-3d-gltf.protoascii
Labels: cla: yes

#17187 Remove guards for launched 'inline-styles' experiment
  extensions/amp-mustache/0.1/test/test-amp-mustache.js
  src/purifier.js
  src/service/fixed-layer.js
  test/functional/test-fixed-layer.js
  test/functional/test-purifier.js
  test/functional/test-sanitizer.js
  tools/experiments/experiments.js
Labels: cla: yes

#17256 📖 Fix typo in amp-instagram docs
  extensions/amp-instagram/amp-instagram.md
Labels: cla: yes

#17206 Document-fetcher using utils functions
  ads/google/a4a/line-delimited-response-handler.js
  ads/google/a4a/utils.js
  build-system/tasks/bundle-size.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/amp-ad-type-defs.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/sra-utils.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/form-verifiers.js
  src/service/batched-xhr-impl.js
  src/service/xhr-impl.js
  src/utils/xhr-utils.js
  test/functional/test-batched-xhr.js
  test/functional/test-xhr.js
Labels: cla: yes

#17251 🐛 Sourcemap aware gulp replace
  build-system/shorten-license.js
  build-system/tasks/compile.js
  build-system/tasks/create-module-compatible-es5-bundle.js
  gulpfile.js
  package.json
  yarn.lock
Labels: cla: yes

#16643 🏗 Add support for locally serving without caching extensions.
  build-system/server.js
  build-system/tasks/serve.js
Labels: cla: yes

#17101 🏗Make codecov.io post a status on PRs instead of a comment
  .codecov.yml
  build-system/tasks/runtime-test.js
Labels: Category: Tooling, cla: yes

#17052 Adding PubMatic OpenWrap Vendor :sparkles:
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#17128 Remove isTrustedViewer hack to support missing schema
  src/service/viewer-impl.js
  test/functional/test-viewer.js
  test/functional/test-viewport.js
Labels: cla: yes

#17264 ✓ CRC32 Implementation
  extensions/amp-analytics/0.1/crc32.js
  extensions/amp-analytics/0.1/test/test-crc32.js
Labels: cla: yes

#17268 Fix lightbox-gallery starts showing blank 0x0 images after one full loop bug
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
Labels: cla: yes

#17270 Missed one gulp replace
  build-system/tasks/compile.js
Labels: cla: yes

#17237 :bug: Delay adding the ampshare fragment parameter until after the document is first visible
  src/service/viewer-impl.js
  test/functional/test-viewer.js
Labels: cla: yes

#17278 Fixing the RTL CSS selectors for the loading spinner and equalizer.
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#16710 ✨ AMP Analytics Iframe Transport Configuration for Moat
  extensions/amp-analytics/0.1/iframe-transport-vendors.js
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#17267 Fixing the progress bar "double segment" animations.
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/progress-bar.js
  extensions/amp-story/1.0/test/test-amp-story-system-layer.js
Labels: cla: yes

#17284 🏗 Run pre-push tests in headless mode
  build-system/default-pre-push
Labels: Category: Tooling, cla: yes

#17058 Enable CSS scroll snap code across more browsers
  extensions/amp-carousel/0.1/amp-carousel.css
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/0.1/test/test-slidescroll.js
  tools/experiments/experiments.js
Labels: cla: yes

#17281 Enable CSS scroll snap experiment on carousels
  build-system/global-configs/canary-config.json
Labels: cla: yes

#17265 🏗🐛 Add a more robust mechanism for dynamically skipping tests
  build-system/tasks/presubmit-checks.js
  test/_init_tests.js
  test/functional/test-fixed-layer.js
  test/functional/test-shadow-embed.js
  test/functional/test-viewport-binding.js
  test/integration/test-video-players-helper.js
Labels: Category: Tooling, Related to: Flaky Tests, cla: yes

#17262 🐛✨Work/Bug Fix on amp-image-slider
  examples/image-slider.amp.html
  extensions/amp-image-slider/0.1/amp-image-slider.css
  extensions/amp-image-slider/0.1/amp-image-slider.js
  extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
  extensions/amp-image-slider/amp-image-slider.md
  test/manual/amp-image-slider.amp.html
Labels: cla: yes

#17283 📖 Removing "optional" for creating new component example
  contributing/building-an-amp-extension.md
Labels: cla: yes

#17205 🚀♻️ Custom Elements V1 Polyfill
  build-system/dep-check-config.js
  build-system/tasks/bundle-size.js
  build-system/tasks/compile.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-form/0.1/form-proxy.js
  src/custom-element.js
  src/polyfills.js
  src/polyfills/custom-elements.js
  src/service/extensions-impl.js
  test/functional/test-base-element.js
  test/functional/test-custom-element.js
  test/functional/test-dom.js
  test/functional/test-intersection-observer.js
  testing/describes.js
  testing/iframe.js
  tools/experiments/experiments.js
Labels: cla: yes

#17287 🐛Use bytes in CRC32
  extensions/amp-analytics/0.1/crc32.js
  extensions/amp-analytics/0.1/test/test-crc32.js
Labels: cla: yes

#17286 Update user-error-reporting doc
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#17288 Don't send progress events to the progress bar for ad pages.
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#17285 Getting videos to play reliably in the first story page.
  extensions/amp-story/0.1/media-pool.js
  extensions/amp-story/1.0/media-pool.js
Labels: cla: yes

#17289 Do not duplicate the listeners when using media based advancement start/stop methods.
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
Labels: cla: yes

#17290 ♻️Single method for unicode base64Url(str)
  extensions/amp-analytics/0.1/variables.js
  src/utils/base64.js
  test/functional/utils/test-base64.js
Labels: cla: yes

#17266 Url Replacement Experiment Bump
  build-system/global-configs/prod-config.json
Labels: cla: yes

#17297 Remove 3p-use-ampcontext flag.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#17294 🐛✨First onMeasureChanged even if unchanged after build
  extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
  src/service/resource.js
  test/functional/test-resource.js
Labels: cla: yes

#17271 Introduce experiment flag to disable initialIntersection callback
  3p/3p.js
  3p/ampcontext.js
  test/functional/test-integration.js
  test/integration/test-3p-frame.js
  tools/experiments/experiments.js
Labels: cla: yes

#17191 Doubleclick SRA - move to client-side exp selection
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#17114 add babel-plugin-transform-amp-asserts
  .eslintignore
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/index.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/no-transform-dev-assert/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/no-transform-dev-assert/options.json
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/no-transform-dev-assert/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/no-transform/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/no-transform/options.json
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/no-transform/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-boolean/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-boolean/options.json
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-boolean/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-element/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-element/options.json
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-element/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-number/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-number/options.json
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-number/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-string/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-string/options.json
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-string/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert/options.json
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-user-fine/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-user-fine/options.json
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-user-fine/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/index.js
  build-system/babel-plugins/testSetupFile.js
  build-system/pr-check.js
  build-system/tasks/presubmit-checks.js
  package.json
  yarn.lock
Labels: cla: yes

#16989 fix some type issues for geo/consent that only show up on newer CC versions
  build-system/tasks/compile.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-user-notification/0.1/amp-user-notification.js
  src/services.js
Labels: cla: yes

#17310 📖 Remove origin trial link from amp-story.md
  extensions/amp-story/amp-story.md
Labels: cla: yes

#17090 🐛 Prevent double click on iframe during transition, cleanup test
  ads/inabox/frame-overlay-helper.js
  test/functional/test-friendly-iframe-embed.js
Labels: cla: yes

#16960 amp-bind: Support multiple args in Array.reduce()
  extensions/amp-bind/0.1/bind-expr-impl.jison
  extensions/amp-bind/0.1/bind-expr-impl.js
  extensions/amp-bind/0.1/bind-expression.js
  extensions/amp-bind/0.1/test/test-bind-expression.js
Labels: cla: yes

#17313 Validator Rollup
  extensions/amp-access-laterpay/0.1/test/validator-amp-access-laterpay.html
  extensions/amp-access-laterpay/0.1/test/validator-amp-access-laterpay.out
  extensions/amp-access-laterpay/0.2/test/validator-amp-access-laterpay.html
  extensions/amp-access-laterpay/0.2/test/validator-amp-access-laterpay.out
  extensions/amp-geo/0.1/test/validator-amp-geo.html
  extensions/amp-geo/0.1/test/validator-amp-geo.out
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-story-auto-ads/0.1/test/validator-amp-story-auto-ads.html
  extensions/amp-story-auto-ads/0.1/test/validator-amp-story-auto-ads.out
  extensions/amp-subscriptions/0.1/test/validator-amp-subscriptions-errors.html
  extensions/amp-subscriptions/0.1/test/validator-amp-subscriptions-errors.out
  validator/engine/parse-srcset.js
  validator/engine/validator.js
  validator/testdata/feature_tests/extensions.html
  validator/testdata/feature_tests/extensions.out
  validator/validator-main.protoascii
  validator/validator.proto
Labels: Category: Validator, cla: yes

#17311 🐛✨amp-image-slider UX updates [compressed and corrected]
  examples/image-slider.amp.html
  extensions/amp-image-slider/0.1/amp-image-slider.css
  extensions/amp-image-slider/0.1/amp-image-slider.js
  extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
  extensions/amp-image-slider/amp-image-slider.md
  test/manual/amp-image-slider.amp.html
Labels: cla: yes

#17307 ✨Enable amp-bind for amp-google-document-embed source attr
  examples/google-document-embed.amp.html
  extensions/amp-bind/0.1/bind-validator.js
  extensions/amp-google-document-embed/0.1/amp-google-document-embed.js
  extensions/amp-google-document-embed/0.1/test/validator-amp-google-document-embed.html
  extensions/amp-google-document-embed/0.1/test/validator-amp-google-document-embed.out
  extensions/amp-google-document-embed/validator-amp-google-document-embed.protoascii
Labels: cla: yes

#17316 ✅ video-player-* unit tests: don't wait for iframe to fully load
  extensions/amp-3q-player/0.1/test/test-amp-3q-player.js
  extensions/amp-brid-player/0.1/test/test-amp-brid-player.js
  extensions/amp-dailymotion/0.1/test/test-amp-dailymotion.js
  extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js
  extensions/amp-reach-player/0.1/test/test-amp-reach-player.js
  extensions/amp-springboard-player/0.1/amp-springboard-player.js
  extensions/amp-springboard-player/0.1/test/test-amp-springboard-player.js
Labels: cla: yes

#17314 Document new amp-list attributes
  extensions/amp-list/amp-list.md
Labels: cla: yes

#17320 Change animation curve in amp-carousel
  extensions/amp-carousel/0.1/slidescroll.js
Labels: cla: yes

#17272 🐛 Fix docs for amp-position-observer s/target-id/target/
  extensions/amp-position-observer/0.1/amp-position-observer.js
  extensions/amp-position-observer/amp-position-observer.md
Labels: cla: yes

#17299 📖 Updated wording to clarify user interaction and DOM updates in amp-live-list
  extensions/amp-live-list/amp-live-list.md
Labels: cla: yes

#17295 📖 Added pull request emoji key for new contributors
  CONTRIBUTING.md
Labels: cla: yes

#16967 Enforce full-width responsive for all auto ads.
  examples/auto-ads.amp.html
  extensions/amp-auto-ads/0.1/ad-network-config.js
  extensions/amp-auto-ads/0.1/ad-strategy.js
  extensions/amp-auto-ads/0.1/amp-auto-ads.js
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-auto-ads/0.1/test/test-ad-network-config.js
  extensions/amp-auto-ads/0.1/test/test-ad-strategy.js
  extensions/amp-auto-ads/0.1/test/test-placement.js
  src/layout-rect.js
  test/functional/test-layout-rect.js
  tools/experiments/experiments.js
Labels: cla: yes

#17330 Set Doubleclick SRA experiment to 1%
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#17184 Doubleclick SRA - detect if block not included
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
Labels: cla: yes

#16961 amp-bind: Array.sort() with comparator
  extensions/amp-bind/0.1/bind-expression.js
  extensions/amp-bind/0.1/test/test-bind-expression.js
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#17332 Doubleclick SRA - set doubleclickSraReportExcludedBlock to 10%
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#17324 Unlock scroll on <amp-story> when experiment is enabled.
  extensions/amp-story/1.0/amp-story-scroll.css
Labels: cla: yes

#17315 Fix amp-story tests.
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#17323 ✨amp-image-slider add ARIA
  extensions/amp-image-slider/0.1/amp-image-slider.js
Labels: cla: yes

#16471 amp-access onApplyAuthorizations callbacks.
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-access/0.1/test/test-amp-access.js
Labels: cla: yes

#17336 Doubleclick SRA - handle race condition with cancelation
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#17338 fix FetchInit annotation
  src/utils/xhr-utils.js
Labels: cla: yes

#17326 amp-carousel: Only update scroll params when CSS Scroll Snap isn't in use
  extensions/amp-carousel/0.1/slidescroll.js
Labels: cla: yes

#17327 Add firebase folder generation to gulp tasks
  .gitignore
  build-system/tasks/firebase.js
  build-system/tasks/index.js
  contributing/DEVELOPING.md
Labels: cla: yes

#17259 Add document fetcher
  src/document-fetcher.js
  test/functional/test-xhr-document-fetcher.js
Labels: cla: yes

#17248 CSS RTL improvements to amp-story 🖍
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/amp-story-consent.css
  extensions/amp-story/1.0/amp-story-consent.js
  extensions/amp-story/1.0/amp-story-hint.css
  extensions/amp-story/1.0/amp-story-hint.js
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/bookend/components/article.js
  extensions/amp-story/1.0/bookend/components/heading.js
  extensions/amp-story/1.0/test/test-amp-story-consent.js
Labels: cla: yes

#17301 Enable user-error-reporting
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#17366 Remove CSS Scroll Snap experiment from 1% Canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#17364 Validator rollup
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#17368 ✨ Launch amp-google-document-embed
  extensions/amp-google-document-embed/0.1/amp-google-document-embed.js
  extensions/amp-google-document-embed/0.1/test/test-amp-google-document-embed.js
  extensions/amp-google-document-embed/amp-google-document-embed.md
  tools/experiments/experiments.js
Labels: cla: yes

#17350 ✨amp-image-slider P0 update based on spec change
  examples/image-slider.amp.html
  extensions/amp-image-slider/0.1/amp-image-slider.css
  extensions/amp-image-slider/0.1/amp-image-slider.js
  extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
  extensions/amp-image-slider/amp-image-slider.md
  test/manual/amp-image-slider.amp.html
Labels: cla: yes

#17246 Install global submit listener only when amp-form extension is registered
  extensions/amp-form/0.1/test/integration/test-integration-form.js
  src/document-submit.js
  src/element-service.js
  test/functional/test-document-submit.js
  test/functional/test-element-service.js
Labels: cla: yes

#17377 Doc cleanup of amp-image-slider
  extensions/amp-image-slider/amp-image-slider.md
Labels: cla: yes

#17381 Added link to ABE example
  extensions/amp-3d-gltf/amp-3d-gltf.md
Labels: cla: yes

#17342 amp-lightbox: Add [open] binding
  extensions/amp-bind/0.1/bind-validator.js
  extensions/amp-bind/0.1/test/test-bind-validator.js
  extensions/amp-bind/amp-bind.md
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-lightbox/validator-amp-lightbox.protoascii
Labels: cla: yes

#17383 📖 Clean up docs for "observer" components
  extensions/amp-orientation-observer/amp-orientation-observer.md
  extensions/amp-position-observer/amp-position-observer.md
Labels: cla: yes

#17275 📖 Extracted Testing into separate guide
  contributing/DEVELOPING.md
  contributing/TESTING.md
  contributing/getting-started-e2e.md
Labels: cla: yes

#17386 📖 Add workflows & improve contributing doc
  CONTRIBUTING.md
Labels: cla: yes

#17372 🐛amp-image-slider P0 Edge/Mobile iOS glitch fix
  extensions/amp-image-slider/0.1/amp-image-slider.css
  extensions/amp-image-slider/0.1/amp-image-slider.js
Labels: cla: yes

#17003 📖 Fix typos in amp-geo docs (preset country groups) and CONTRIBUTING.md
  CONTRIBUTING.md
  extensions/amp-geo/amp-geo.md
Labels: cla: yes

#16361 🐛Fix broken test for postmessage origin in amp-brightcove
  extensions/amp-analytics/amp-video-analytics.md
  extensions/amp-brightcove/0.1/amp-brightcove.js
Labels: cla: yes

#16570 Add operand limit number in amp-bind doc
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#16700 Move AMPHTML Email's FAQ to a lower position in the spec document
  spec/amp-email-format.md
Labels: cla: yes

#16701 add consentHandlingOverride flag for Teads
  ads/_config.js
  ads/teads.md
Labels: cla: yes

#17369 Shifting live-list-manager to document-fetcher
  extensions/amp-live-list/0.1/live-list-manager.js
Labels: cla: yes

#17322 ✨amp-image-slider P0 validator rules
  extensions/amp-image-slider/validator-amp-image-slider.protoascii
  validator/testdata/feature_tests/amp-image-slider.html
  validator/testdata/feature_tests/amp-image-slider.out
Labels: cla: yes

#17388 ✨Allow static initial date attributes. Enable date offsets.
  examples/date-picker.amp.html
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/test/integration/test-integration-dates-attributes.js
  third_party/moment/moment.extern.js
Labels: cla: yes

#17343 Fix bugs in Layers
  src/service/layers-impl.js
  src/service/resource.js
  src/service/resources-impl.js
Labels: cla: yes

#17391 Fix gotoAndPlayNTimes not working due to bad eventName
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation.js
  extensions/amp-gwd-animation/0.1/test/test-amp-gwd-animation.js
Labels: cla: yes

#17400 🏗 Fix usage of `topological-sort`
  build-system/get-dep-graph.js
Labels: Category: Tooling, cla: yes

#17371 Shift amp access
  extensions/amp-access/0.1/amp-access-server-jwt.js
  extensions/amp-access/0.1/amp-access-server.js
  extensions/amp-access/0.1/test/test-amp-access-server-jwt.js
  extensions/amp-access/0.1/test/test-amp-access-server.js
Labels: cla: yes

#17402 🐛 amp-image-slider add Edge non-standard keycode
  extensions/amp-image-slider/0.1/amp-image-slider.js
Labels: cla: yes

#17392 ✅ amp-image-slider test speedup
  extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
Labels: cla: yes

#17379 🏗Change gulp firebase code to use Promises.
  build-system/tasks/firebase.js
Labels: cla: yes

#17403 🏗🐛 Increase `bundleDelay` for `karma-browserify` on Travis
  build-system/tasks/karma.conf.js
Labels: Category: Tooling, Related to: Flaky Tests, cla: yes

#17401 Add innerHTML to workaround DOMPurify bug
  build-system/tasks/bundle-size.js
  extensions/amp-mustache/0.2/amp-mustache.js
Labels: Internally Tracked, cla: yes

#17410 📖 Added info on usqp parameter
  builtins/amp-pixel.md
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#17412 📖🐛 Add warning for issues #17393
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#17424 📖 Fix issue for cors + cleanup
  extensions/amp-form/amp-form.md
Labels: cla: yes

#17341 History: Fix historyPopped, remove getHistory viewer API
  extensions/amp-bind/0.1/bind-impl.js
  src/service/history-impl.js
  test/functional/test-history.js
Labels: Internally Tracked, cla: yes

#17396 📖 Improve layout and info for building extension doc
  CONTRIBUTING.md
  contributing/building-an-amp-extension.md
Labels: cla: yes

#17365 Shifting next page manager to new document fetcher
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
Labels: cla: yes

#17428 🐛 fix margin for cta links in bookend
  extensions/amp-story/1.0/amp-story-bookend.css
Labels: Category: AMP Story, cla: yes

#16991 Disable scroll on body for <amp-sidebar>/<amp-lightbox>
  examples/sidebar.amp.html
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
  src/service/viewport/viewport-binding-ios-embed-sd.js
Labels: cla: yes

#17422 Allow style attribute on SVG tag
  validator/validator-main.protoascii
Labels: cla: yes

#17413 🐛 amp-image-slider remove webkit tap grayish color
  extensions/amp-image-slider/0.1/amp-image-slider.css
Labels: cla: yes

#17179 ✨amp-ads: Added serverName optional parameter for Giraff network
  ads/giraff.js
  ads/giraff.md
Labels: cla: yes

#17434 Allow all attrs of AMP elements in mustache-0.2
  src/purifier.js
  test/functional/test-purifier.js
  test/functional/test-sanitizer.js
Labels: cla: yes

#17439 Redisable CSS Scrol Snap for iOS 10.3
  extensions/amp-carousel/0.1/slidescroll.js
Labels: cla: yes

#17333 Create auto-started video player by Viqeo
  3p/integration.js
  3p/viqeoplayer.js
  build-system/dep-check-config.js
  bundles.config.js
  examples/viqeo.amp.html
  extensions/amp-viqeo-player/0.1/amp-viqeo-player.js
  extensions/amp-viqeo-player/0.1/test/test-amp-viqeo-player.js
  extensions/amp-viqeo-player/0.1/test/validator-amp-viqeo-player.html
  extensions/amp-viqeo-player/0.1/test/validator-amp-viqeo-player.out
  extensions/amp-viqeo-player/OWNERS.yaml
  extensions/amp-viqeo-player/amp-viqeo-player.md
  extensions/amp-viqeo-player/validator-amp-viqeo-player.protoascii
Labels: cla: yes

#17235 ✨Update Unruly loader URL
  ads/_config.js
  ads/unruly.js
  test/functional/ads/test-unruly.js
Labels: cla: yes

#15788 Add new variable to INFOnline analytics vendor configuration
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#17437 🐛 amp-image-slider hide/show hint easing/timing update
  extensions/amp-image-slider/0.1/amp-image-slider.css
Labels: cla: yes

#17438 Turn on CSS Scroll Snap experiment again.
  build-system/global-configs/canary-config.json
Labels: cla: yes

#17461 apm-video-*: Making more tests less flaky
  extensions/amp-hulu/0.1/test/test-amp-hulu.js
  extensions/amp-jwplayer/0.1/test/test-amp-jwplayer.js
  extensions/amp-ooyala-player/0.1/amp-ooyala-player.js
  extensions/amp-ooyala-player/0.1/test/test-amp-ooyala.js
  extensions/amp-viqeo-player/0.1/test/test-amp-viqeo-player.js
Labels: cla: yes

#17443 🐛Fix flash while expanding accordion with animation.
  bundles.config.js
  extensions/amp-accordion/0.1/amp-accordion.css
  extensions/amp-accordion/0.1/amp-accordion.js
Labels: cla: yes

#17450 🐛 amp-ima-video: seek should consume touch events
  ads/google/imaVideo.js
  extensions/amp-ima-video/0.1/amp-ima-video.js
  test/manual/amp-ima-video.html
Labels: cla: yes

#17466 Enable 'faster-bind-scan' in canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#17470 🐛 [amp-image-slider] Prevent Edge go back/forward in history to allow correct slider behavior on touchscreen
  extensions/amp-image-slider/0.1/amp-image-slider.js
Labels: cla: yes

#17444 ✨Add two variations for the Twitter loading state.
  extensions/amp-twitter/0.1/amp-twitter.css
  extensions/amp-twitter/0.1/amp-twitter.js
Labels: cla: yes

#17344 Add controls option to <amp-pan-zoom>
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.css
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  extensions/amp-pan-zoom/0.1/test/validator-amp-pan-zoom.html
  extensions/amp-pan-zoom/0.1/test/validator-amp-pan-zoom.out
  extensions/amp-pan-zoom/amp-pan-zoom.md
  extensions/amp-pan-zoom/validator-amp-pan-zoom.protoascii
  test/manual/amp-pan-zoom.amp.html
Labels: cla: yes

#17395 Setting AMP = 1 in UAS amp-ad tag
  ads/uas.js
Labels: cla: yes

#17291 Build all ad extensions with amp-ad
  gulpfile.js
Labels: cla: yes

#16479 ✨ Implements variable substitution macro for html element opacity.
  extensions/amp-analytics/0.1/opacity.js
  extensions/amp-analytics/0.1/test/test-opacity.js
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-analytics/0.1/visibility-manager.js
Labels: cla: yes

#17261 :bug: AppNexus: fix scope in ad available function
  ads/appnexus.js
Labels: cla: yes

#17479 Ad doc fix
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#17478 amp-bind: Check equality to depth of 10
  extensions/amp-bind/0.1/bind-impl.js
  src/json.js
  test/functional/test-json.js
Labels: cla: yes

#17451 [amp-pan-zoom] Fix bug where zoom breaks after toggling display
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  test/manual/amp-pan-zoom.amp.html
Labels: cla: yes

#17305 ✨Apester Media (extension): Added meta tags extraction
  extensions/amp-apester-media/0.1/amp-apester-media.css
  extensions/amp-apester-media/0.1/amp-apester-media.js
  extensions/amp-apester-media/0.1/test/test-amp-apester-media-utils.js
  extensions/amp-apester-media/0.1/test/test-amp-apester-media.js
  extensions/amp-apester-media/0.1/utils.js
Labels: cla: yes

#17489 Fix bug where zoom button is not initialized
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
Labels: cla: yes

#17497 Update docs on amp-access-iframe launch
  extensions/amp-access/0.1/iframe-api/README.md
  tools/experiments/experiments.js
Labels: cla: yes

#17480 Support <amp-layout> as ad container during collapse
  3p/3p.js
  builtins/amp-layout.js
  builtins/amp-layout.md
  extensions/amp-ad/0.1/amp-ad-ui.js
  extensions/amp-ad/0.1/test/test-amp-ad-ui.js
  extensions/amp-ad/amp-ad.md
  test/manual/fakead3p.amp.html
  validator/validator-main.protoascii
Labels: cla: yes

#17204 Introduce Host API for inabox.
  src/inabox/host-services.js
Labels: cla: yes

#17493 Move video prerender-able check to firstAttachedCallback
  extensions/amp-video/0.1/amp-video.js
  src/base-element.js
Labels: cla: yes

#17503 Update URL substitution doc to indicate URL host cannot be substituted
  spec/amp-var-substitutions.md
Labels: cla: yes

#17433 Imperative case, matching the example
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#17491 amp-mustache: Better version notes and quote-escaping tips
  extensions/amp-mustache/amp-mustache.md
Labels: cla: yes

#17487 AMP4EMAIL: Recommend text/html MIME part last
  spec/amp-email-format.md
Labels: cla: yes

#17500 🏗🐛 Rename `gulp changelog` flag `--version` to `--tag`, since `--version` is reserved by `gulp-cli`
  build-system/tasks/changelog.js
Labels: Category: Tooling, cla: yes

#17432 📖 amp-bind: Document necessity of default value. Complete button tag. Fix typos.
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#17477 🐛 [amp-image-slider] Conservative loading with tweak over hints
  examples/image-slider.amp.html
  extensions/amp-image-slider/0.1/amp-image-slider.js
Labels: cla: yes

#17408 🐛 Fix doc.fonts.values presence check in font-display-swap experiment
  src/font-stylesheet-timeout.js
Labels: cla: yes

#17514 🏗 Pause `yarn` install when an outdated toolchain is detected
  build-system/check-package-manager.js
Labels: Category: Tooling, cla: yes

#17430 amp-mustache: Support list tags in triple-stache
  extensions/amp-mustache/amp-mustache.md
  src/purifier.js
  test/functional/test-purifier.js
Labels: Internally Tracked, cla: yes
