Repository ampproject/amphtml, pull requests merged in 2018-09, with the labels that each got.

#17823 Inabox: Support layers
  src/inabox/inabox-viewport.js
Labels: cla: yes

#17738 📖 Update docs for amp-gist to indicate height does not have to be obtained up front
  extensions/amp-gist/amp-gist.md
Labels: cla: yes

#17697 Fix pinch zoom to corner bug
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  extensions/amp-pan-zoom/0.1/test/test-amp-pan-zoom.js
  test/manual/amp-pan-zoom-initial.amp.html
  test/manual/amp-pan-zoom.amp.html
Labels: cla: yes

#17844 Ramping up Auto Ads responsive to 1%
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#17799 🏗 Add a local-only mode for visual diff (`--percy_disabled`)
  build-system/tasks/visual-diff.js
Labels: cla: yes

#17776 🏗 Assume the loading_complete_delay_ms in visual-diffs is correct
  build-system/tasks/visual-diff.js
Labels: cla: yes

#17801 fix typedef so that JsonObject prop reads are detected by type checker
  extensions/amp-addthis/0.1/addthis-utils/lojson.js
  extensions/amp-addthis/0.1/amp-addthis.js
Labels: cla: yes

#17847 ✅♻️ : Make amp-consent test cleaner
  extensions/amp-consent/0.1/test/test-amp-consent.js
Labels: cla: yes

#17811 Strip down error data set when sent to viewer
  build-system/tasks/bundle-size.js
  src/error.js
  test/functional/test-error.js
Labels: cla: yes

#17820 ♻️amp-subscriptions: use [hidden] to toggle display
  extensions/amp-subscriptions/0.1/dialog.js
Labels: cla: yes

#17747 ✨Created the initial <amp-recaptcha-input> 3p Bootstrap Iframe
  3p/integration.js
  3p/recaptcha-bootstrap.js
  3p/recaptcha.js
  build-system/amp.extern.js
Labels: cla: yes

#17868 Add untracked files for ssr viewer example
  examples/form-proxy-template-to-viewer-host.amp.html
  examples/mustache-to-amp-view-host.amp.html
  examples/viewer.html
Labels: cla: yes

#17818 ♻️ Use toggle instead of setStyle
  css/video-autoplay.css
  extensions/amp-addthis/0.1/addthis-utils/pixel.js
  extensions/amp-analytics/0.1/iframe-transport.js
  extensions/amp-analytics/0.1/transport.js
  extensions/amp-form/0.1/amp-form.css
  extensions/amp-form/0.1/test/test-validation-bubble.js
  extensions/amp-form/0.1/validation-bubble.js
  extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-social-share/0.1/amp-social-share.js
  extensions/amp-story/0.1/amp-story-share-menu.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/1.0/amp-story-share-menu.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-web-push/0.1/iframehost.js
  src/layout.js
  src/service/fixed-layer.js
  src/service/video-manager-impl.js
Labels: cla: yes

#17864 Clean up amp-list SSR code and rework unit tests.
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#17865 ♻️Refactored & Fixed Amp Auto Ads Test
  extensions/amp-auto-ads/0.1/ad-network-config.js
  extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
Labels: cla: yes

#17886 Layers: Remove element when it detaches
  src/custom-element.js
  src/service/layers-impl.js
Labels: cla: yes

#17828 Fix and improvement to --extensions_from flag
  gulpfile.js
Labels: cla: yes

#17885 Make Transport a real class
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-transport.js
  extensions/amp-analytics/0.1/transport.js
Labels: cla: yes

#17888 getSingleChildJsonConfig helper method
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  src/json.js
  test/functional/test-json.js
Labels: cla: yes

#17656 amp-date-countdown: migrated getAttributes from constructor to buildCallback
  extensions/amp-date-countdown/0.1/amp-date-countdown.js
  extensions/amp-date-countdown/0.1/test/test-amp-date-countdown.js
Labels: cla: yes

#17890 Bypass isConnected checks when destroying FIE
  src/custom-element.js
  src/service/resource.js
  test/functional/test-resource.js
Labels: cla: yes

#17584 fix help info
  build-system/tasks/changelog.js
Labels: cla: yes

#17892 Refactor test-transport.js to use realWin
  extensions/amp-analytics/0.1/test/test-transport.js
  extensions/amp-analytics/0.1/transport.js
Labels: cla: yes

#17896 🐛Make sure template rendering works when detached.
  src/service/template-impl.js
  test/functional/test-template.js
Labels: cla: yes

#17815 add snippet about cleaning up experiment
  contributing/building-an-amp-extension.md
Labels: cla: yes

#16670 ✨Added support for iplabel RUMBI to AMP analytics
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#17902 Increase bundle size to 81.27KB
  build-system/tasks/bundle-size.js
Labels: cla: yes

#17893 [amp-carousel] Ramp up Scroll Snap experiment to 10% of prod pages
  build-system/global-configs/prod-config.json
Labels: cla: yes

#17912 📖🚮[amp-image-slider] Remove remaining experimental marks
  extensions/amp-image-slider/amp-image-slider.md
  tools/experiments/experiments.js
Labels: cla: yes

#17866 ✨ amp-consent v2: Read and merge cmp config
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  package.json
  tools/experiments/experiments.js
  yarn.lock
Labels: cla: yes

#17913 📖 Add draft specification of AMP-Cache-Transform.
  caches.json
  spec/amp-cache-modifications.md
  spec/amp-cache-transform.md
Labels: Category: AMP Caches, cla: yes

#17927 🐛 Appends toasts to the story instead of the body
  extensions/amp-story/1.0/amp-story-share.js
  extensions/amp-story/1.0/toast.js
Labels: cla: yes

#17891 🐛All macro resolution should allow falsey values.
  src/service/url-expander/expander.js
Labels: cla: yes

#17917 🐛Linker `proxyOrigin` should default to true
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
Labels: cla: yes

#17911 🐛Check hostname for default domain
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
Labels: cla: yes

#17867 ✨<amp-recaptcha-input> Created the Initial Example & Service Skeleton
  build-system/tasks/bundle-size.js
  build-system/tasks/presubmit-checks.js
  bundles.config.js
  examples/recaptcha.amp.html
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.css
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-service.js
Labels: cla: yes

#17821 Allow setting the initial display style of an element
  build-system/tasks/bundle-size.js
  extensions/amp-animation/0.1/amp-animation.js
  extensions/amp-video/0.1/amp-video.js
  src/layout.js
  src/service/fixed-layer.js
  src/service/viewport/viewport-binding-ios-embed-sd.js
  src/shadow-embed.js
  src/style.js
Labels: cla: yes

#17945 Update linker format.
  extensions/amp-analytics/0.1/linker.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker.js
Labels: cla: yes

#17947 iOS Embed SD viewport: prevent webkit-overflow-scrolling paint bug
  src/service/viewport/viewport-binding-ios-embed-sd.js
  test/functional/test-viewport-binding.js
Labels: cla: yes

#17955 amp-video: when cached, remove `src` from `amp-video` node since it gets copied back by stories `media-pool`
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-video/0.1/test/test-amp-video.js
Labels: cla: yes

#17805 Make bundle-size cap less precise
  build-system/tasks/bundle-size.js
Labels: cla: yes

#17948 ✨ Fixed amp-recaptcha-input Registration layoutCallback() Race Condition
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-input.js
Labels: cla: yes

#17956 Support default linker config.
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
Labels: cla: yes

#17965 Update ga linker config
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#17966 Update linker tests to more realistic browser info.
  extensions/amp-analytics/0.1/test/test-linker.js
Labels: cla: yes

#17822 amp-subscriptions: doc changes for subscriptions-actions sections
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#17967 AdSense/Doubleclick FF - identify token integration with amp-consent
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
  build-system/dep-check-config.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#17874 🐛Add flag to always use the closest AmpDoc
  src/service/ampdoc-impl.js
  test/functional/test-ampdoc.js
Labels: Category: PWA, cla: yes

#17978 clean up
  examples/inabox.amp.html
  extensions/amp-a4a/0.1/a4a-variable-source.js
  extensions/amp-a4a/0.1/test/test-a4a-var-source.js
  extensions/amp-ad-network-fake-impl/0.1/data/fake_amp.html
  src/service/url-replacements-impl.js
  test/functional/test-url-replacements.js
Labels: cla: yes

#17166 📖 Add documentation for amp-story image metadata
  extensions/amp-story/amp-story.md
  extensions/amp-story/img/publisher-logo-1.png
  extensions/amp-story/img/publisher-logo-2.png
  extensions/amp-story/img/publisher-logo-3.png
Labels: cla: yes

#17980 🚀 Add an experiment to remove default media
  extensions/amp-story/1.0/media-pool.js
  extensions/amp-story/1.0/sources.js
  tools/experiments/experiments.js
Labels: cla: yes

#17946 ✨ AMP consent v2: support promptUISrc
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  test/manual/amp-consent-cmp.html
Labels: cla: yes

#17920 Add desktop panning with mouse events
  extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.css
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  extensions/amp-pan-zoom/0.1/test/test-amp-pan-zoom.js
  testing/test-helper.js
Labels: cla: yes

#17992 Remove amp-img-native-srcset related configs.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#17931 ✨Add data-auto-format="mcrspv" amp tag to support Google Matched Content responsive logic
  ads/_config.js
  ads/google/adsense.js
  ads/google/utils.js
  examples/a4a-fullwidth.amp.html
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
Labels: cla: yes

#17933 Revert #12211
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
Labels: cla: yes

#17996 Validator rollup
  extensions/amp-ad/0.1/test/validator-amp-ad.html
  extensions/amp-ad/0.1/test/validator-amp-ad.out
  validator/engine/validator.js
Labels: Category: Validator, cla: yes

#17993 Remove amp-img-native-srcset from experiments.
  tools/experiments/experiments.js
Labels: cla: yes

#18002 AdSense/Doubleclick Fast Fetch - timeout on viewer get referrer
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
Labels: cla: yes

#18003 Apply a sandbox to all 3p ad iframes
  src/3p-frame.js
  test/integration/test-3p-frame.js
  tools/experiments/experiments.js
Labels: cla: yes

#18013 Turn off layers experiment in canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#18011 Update validator OWNERS
  validator/OWNERS.yaml
Labels: cla: yes

#18006 🏗 Add generated validator.pb.go.
  build-system/config.js
  validator/validator.pb.go
Labels: Category: Validator, cla: yes

#17963 Allow 'fluid' as a multi-size option
  ads/google/test/test-utils.js
  ads/google/utils.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#18024 Add krux config back
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#18026 🐛 amp-next-page: Restore functionality to drop amp-analytics configs from child pages
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
Labels: cla: yes

#17952 🐛Stops incorrect titles appearing with mouse hover on story bookend
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#17942 Refresh race condition fix
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
Labels: cla: yes

#18032 🏗🐛 Don't stop `check-package-manager` when an error is detected, merely pause execution for 5 sec
  build-system/check-package-manager.js
  build-system/tasks/update-packages.js
Labels: Category: Tooling, cla: yes

#18029 Only auto enable linker on Safari 12+
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  test/functional/test-platform.js
Labels: cla: yes

#18010 Guard access to History.p.state
  build-system/conformance-config.textproto
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/1.0/amp-story.js
  src/history.js
  src/service/history-impl.js
  src/service/viewer-impl.js
Labels: cla: yes

#17971 ✨Developed the <amp-recaptcha-input> .getValue() / .execute() flow
  3p/integration.js
  3p/recaptcha.js
  build-system/amp.extern.js
  examples/recaptcha.amp.html
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  extensions/amp-recaptcha-input/0.1/test/integration/test-amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-service.js
Labels: cla: yes

#18039 Friendly domain matching for linkers.
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  src/window-interface.js
Labels: cla: yes

#18017 Enable linker for iOS12 users on CID API enabled sites.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#18019 Attempt to fix 3p-ad-impl flaky test
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
Labels: cla: yes

#18036 🏗🐛 When a PR only changes unit test files, run just those tests that were changed
  build-system/pr-check.js
Labels: Category: Tooling, cla: yes

#18054 amp-brid-player: update owner
  extensions/amp-brid-player/OWNERS.yaml
Labels: cla: yes

#18047 Separate vendors to different files
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/acquialift.js
  extensions/amp-analytics/0.1/vendors/adobeanalytics.js
  extensions/amp-analytics/0.1/vendors/adobeanalytics_nativeConfig.js
  extensions/amp-analytics/0.1/vendors/afsanalytics.js
  extensions/amp-analytics/0.1/vendors/alexametrics.js
  extensions/amp-analytics/0.1/vendors/atinternet.js
  extensions/amp-analytics/0.1/vendors/baiduanalytics.js
  extensions/amp-analytics/0.1/vendors/bg.js
  extensions/amp-analytics/0.1/vendors/burt.js
  extensions/amp-analytics/0.1/vendors/byside.js
  extensions/amp-analytics/0.1/vendors/chartbeat.js
  extensions/amp-analytics/0.1/vendors/clicky.js
  extensions/amp-analytics/0.1/vendors/colanalytics.js
  extensions/amp-analytics/0.1/vendors/comscore.js
  extensions/amp-analytics/0.1/vendors/cxense.js
  extensions/amp-analytics/0.1/vendors/dynatrace.js
  extensions/amp-analytics/0.1/vendors/euleriananalytics.js
  extensions/amp-analytics/0.1/vendors/facebookpixel.js
  extensions/amp-analytics/0.1/vendors/gemius.js
  extensions/amp-analytics/0.1/vendors/googleadwords.js
  extensions/amp-analytics/0.1/vendors/googleanalytics.js
  extensions/amp-analytics/0.1/vendors/gtag.js
  extensions/amp-analytics/0.1/vendors/ibeatanalytics.js
  extensions/amp-analytics/0.1/vendors/infonline.js
  extensions/amp-analytics/0.1/vendors/iplabel.js
  extensions/amp-analytics/0.1/vendors/krux.js
  extensions/amp-analytics/0.1/vendors/linkpulse.js
  extensions/amp-analytics/0.1/vendors/lotame.js
  extensions/amp-analytics/0.1/vendors/marinsoftware.js
  extensions/amp-analytics/0.1/vendors/mediametrie.js
  extensions/amp-analytics/0.1/vendors/mediarithmics.js
  extensions/amp-analytics/0.1/vendors/mediator.js
  extensions/amp-analytics/0.1/vendors/metrika.js
  extensions/amp-analytics/0.1/vendors/moat.js
  extensions/amp-analytics/0.1/vendors/mobify.js
  extensions/amp-analytics/0.1/vendors/mparticle.js
  extensions/amp-analytics/0.1/vendors/mpulse.js
  extensions/amp-analytics/0.1/vendors/newrelic.js
  extensions/amp-analytics/0.1/vendors/nielsen-marketing-cloud.js
  extensions/amp-analytics/0.1/vendors/nielsen.js
  extensions/amp-analytics/0.1/vendors/oewa.js
  extensions/amp-analytics/0.1/vendors/oewadirect.js
  extensions/amp-analytics/0.1/vendors/oracleInfinityAnalytics.js
  extensions/amp-analytics/0.1/vendors/parsely.js
  extensions/amp-analytics/0.1/vendors/piStats.js
  extensions/amp-analytics/0.1/vendors/piano.js
  extensions/amp-analytics/0.1/vendors/quantcast.js
  extensions/amp-analytics/0.1/vendors/rakam.js
  extensions/amp-analytics/0.1/vendors/segment.js
  extensions/amp-analytics/0.1/vendors/shinystat.js
  extensions/amp-analytics/0.1/vendors/simplereach.js
  extensions/amp-analytics/0.1/vendors/snowplow.js
  extensions/amp-analytics/0.1/vendors/top100.js
  extensions/amp-analytics/0.1/vendors/topmailru.js
  extensions/amp-analytics/0.1/vendors/treasuredata.js
  extensions/amp-analytics/0.1/vendors/umenganalytics.js
  extensions/amp-analytics/0.1/vendors/webtrekk.js
  extensions/amp-analytics/0.1/vendors/webtrekk_v2.js
Labels: cla: yes

#18063 ✅ Skip flaky amp-story test
  extensions/amp-story/0.1/test/test-amp-story-system-layer.js
Labels: cla: yes

#17871 ✨Add a scroll vendor config option for dev mode hostname
  examples/scroll.amp.html
  extensions/amp-access-scroll/0.1/scroll-impl.js
Labels: cla: yes

#18070 🐛Ensures white colored text for audio messages
  extensions/amp-story/1.0/amp-story-system-layer.css
Labels: cla: yes

#16564 AMP List Resize: set to layout container after first render (auto-resize attribute)
  build-system/app.js
  examples/countries.json
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/validator-amp-list.html
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/validator-amp-list.protoascii
  test/manual/amp-list-resize-flex.amp.html
  test/manual/amp-list-resize.amp.html
Labels: cla: yes

#17642 Moving AMP to fetch polyfill
  ads/google/a4a/line-delimited-response-handler.js
  ads/google/a4a/utils.js
  build-system/dep-check-config.js
  build-system/tasks/bundle-size.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/amp-ad-network-base.js
  extensions/amp-a4a/0.1/amp-ad-type-defs.js
  extensions/amp-a4a/0.1/amp-ad-utils.js
  extensions/amp-a4a/0.1/signature-verifier.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/sra-utils.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/form-verifiers.js
  src/document-fetcher.js
  src/polyfills.js
  src/polyfills/fetch.js
  src/service/batched-xhr-impl.js
  src/service/xhr-impl.js
  src/utils/xhr-utils.js
  test/functional/test-batched-xhr.js
  test/functional/test-xhr.js
Labels: cla: yes

#18088 🖍 Fade between amp story backgrounds on desktop page switch
  extensions/amp-story/1.0/amp-story-desktop.css
Labels: cla: yes

#18061 SwG release 0.1.22.27
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#18093 Re-enable Layers in Canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#18116 📖 DEVELOPING: Updating repo structure
  contributing/DEVELOPING.md
Labels: cla: yes

#18114 📖 DEVELOPING: Add Pull Request section
  contributing/DEVELOPING.md
Labels: cla: yes

#18136 🏗 Bump bundle size
  build-system/tasks/bundle-size.js
Labels: cla: yes

#17881 ✨ Adds placeholder transition from blurred to amp-video posters
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-video/0.1/test/test-amp-video.js
Labels: cla: yes

#18117 📖 DEVELOPING - update browser support
  contributing/DEVELOPING.md
Labels: cla: yes

#18072 ✅ amp-next-page: Call verify on fetchDocumentMock after each test
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
Labels: cla: yes

#18051 ✨ Lotame vendor - set disableKeyAppend to true
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#18142 Instantiate the amp-story element only once per test.
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#17981 ✨ add support for multiple score factors to amp-subscriptions
  build-system/app.js
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/analytics.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/platform-store.js
  extensions/amp-subscriptions/0.1/score-factors.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-platform-store.js
  extensions/amp-subscriptions/0.1/test/test-url-builder.js
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#18005 🐛Build scrollbar URL with access source in amp-access-scroll
  extensions/amp-access-scroll/0.1/amp-access-scroll.js
  extensions/amp-access-scroll/0.1/scroll-impl.js
Labels: cla: yes

#18149 🐛 Fix path in custom eslint rule import
  build-system/eslint-rules/no-global.js
Labels: Category: Tooling, cla: yes

#18137 Doubleclick Render on Idle Interaction with 3p throttle
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#18153 Set 1% experiment for Doubleclick Idle Fix
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#18158 🏗🚀 Speed up visual tests by eliminating prod / canary config switching logic
  build-system/tasks/visual-diff.js
Labels: Category: Tooling, cla: yes

#18092 Revert back to amp-inabox.js for the local inabox example
  build-system/app.js
Labels: cla: yes

#18187 cl/213341289 Revision bump for #16564
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/validator-amp-list.protoascii
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#18128 🐛 amp-next-page: Fix cache URL rewriting
  extensions/amp-next-page/0.1/amp-next-page.js
  extensions/amp-next-page/0.1/config.js
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
  extensions/amp-next-page/0.1/test/test-config.js
Labels: cla: yes

#18015 Remove remnants of validator LIGHT mode.
  validator/engine/amp4ads-parse-css.js
  validator/engine/css-selectors.js
  validator/engine/definitions.js
  validator/engine/keyframes-parse-css.js
  validator/engine/parse-css.js
  validator/engine/parse-srcset.js
  validator/engine/tokenize-css.js
Labels: cla: yes

#17988 Switch toggle to hidden attribute
  ads/google/a4a/.eslintrc
  build-system/eslint-rules/no-style-display.js
  css/amp.css
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-animation/0.1/test/test-amp-animation.js
  extensions/amp-app-banner/0.1/test/test-amp-app-banner.js
  extensions/amp-byside-content/0.1/test/test-amp-byside-content.js
  extensions/amp-carousel/0.1/test/test-scrollable-carousel.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-form/0.1/test/test-validation-bubble.js
  extensions/amp-image-lightbox/0.1/test/integration/test-amp-image-lightbox.js
  extensions/amp-instagram/0.1/test/test-amp-instagram.js
  extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
  extensions/amp-lightbox-gallery/0.1/test/integration/test-amp-lightbox-gallery.js
  extensions/amp-playbuzz/0.1/test/test-amp-playbuzz.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-input.js
  extensions/amp-sidebar/0.1/test/integration/test-amp-sidebar.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
  extensions/amp-sidebar/0.1/test/test-toolbar.js
  extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
  extensions/amp-story/0.1/development-ui.js
  extensions/amp-story/0.1/test/test-amp-story-consent.js
  extensions/amp-story/0.1/test/test-amp-story-share-menu.js
  extensions/amp-story/1.0/development-ui.js
  extensions/amp-story/1.0/test/test-amp-story-consent.js
  extensions/amp-story/1.0/test/test-amp-story-share-menu.js
  extensions/amp-subscriptions/0.1/dialog.js
  extensions/amp-subscriptions/0.1/test/test-dialog.js
  extensions/amp-youtube/0.1/test/test-amp-youtube.js
  src/base-element.js
  src/custom-element.js
  src/service/resource.js
  src/service/standard-actions-impl.js
  src/service/video/docking.js
  src/style.js
  test/_init_tests.js
  test/functional/ads/test-csa.js
  test/functional/test-ad-helper.js
  test/functional/test-amp-pixel.js
  test/functional/test-custom-element.js
  test/functional/test-fixed-layer.js
  test/functional/test-layout.js
  test/functional/test-resource.js
  test/functional/test-shadow-embed.js
  test/functional/test-standard-actions.js
  test/functional/test-style.js
  test/integration/test-actions.js
  test/integration/test-toggle-display.js
Labels: cla: yes

#18143 Remove unneeded check on resize validation
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
Labels: cla: yes

#18167 ✨amp-timeago: Update fuzzy timestamp on viewportCallback()
  extensions/amp-timeago/0.1/amp-timeago.js
  extensions/amp-timeago/0.1/test/test-amp-timeago.js
Labels: cla: yes

#18193 Update the stylesheet URL regular expression to support old fontawesome
  validator/testdata/feature_tests/regexps.html
  validator/testdata/feature_tests/regexps.out
  validator/validator-main.protoascii
Labels: Category: Validator, P2: Soon, cla: yes

#18211 ♻️ ConsentUI class
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
Labels: cla: yes

#18196 ✨ add isReadyToPay to amp-subscriptions and amp-subscriptions-google.
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/score-factors.js
Labels: cla: yes

#17000 amp-list: 'set-dom' for DOM diffing
  build-system/tasks/compile.js
  examples/bind/list.amp.html
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-mustache/0.1/amp-mustache.js
  extensions/amp-mustache/0.2/amp-mustache.js
  package.json
  src/purifier.js
  src/sanitizer.js
  test/functional/test-purifier.js
  test/functional/test-sanitizer.js
  tools/experiments/experiments.js
  yarn.lock
Labels: cla: yes

#17964 ♻️Updated Teads Ads CDN entry point and prefetch config
  ads/_config.js
  ads/teads.js
Labels: cla: yes

#18038 :book: Nativo: Updated example HTML and config messaging.
  ads/nativo.md
Labels: cla: yes

#18224 📖 DEVELOPING: 2 days = 2 business days
  contributing/DEVELOPING.md
Labels: cla: yes

#17887 Error reporting log ssr fixes
  test/functional/test-error.js
Labels: cla: yes

#17934 Move iframe transport logic into transport.js
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-transport.js
  extensions/amp-analytics/0.1/transport.js
Labels: cla: yes

#18229 ✨ Restore ability to force SRA experiments with #exp.
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#18245 Layers: prevent multiple references to children layouts
  src/service/layers-impl.js
  src/service/resources-impl.js
Labels: cla: yes

#18148 amp-list: Attempt to resize to fit placeholder, if it exists
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#18166 Move amp-carousel tests away from the iframe framework
  test/fixtures/carousels.html
  test/integration/test-amp-carousel.js
Labels: cla: yes

#18218 Closes Issue 18111 🌐🐛
  examples/visual-tests/amp-by-example/dynamic_amp/mixing_dynamic_and_cached_data/embed/index.html
Labels: cla: yes

#18225 amp-selector: Support [disabled] binding
  examples/bind/carousels.amp.html
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-selector/0.1/test/test-amp-selector.js
Labels: cla: yes

#17929 📖Add Linker Documentation
  extensions/amp-analytics/amp-analytics.md
  extensions/amp-analytics/linker-id-forwarding.md
  extensions/amp-analytics/linker-id-receiving.md
Labels: cla: yes

#18264 🐛Use hasOwn to avoid false value
  extensions/amp-consent/0.1/amp-consent.js
Labels: cla: yes

#18263 Move sendRequest_ logic from amp-analytics.js to requests.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-requests.js
Labels: cla: yes

#18069 🐛 Input validation issue fix
  extensions/amp-form/0.1/form-validators.js
Labels: cla: yes

#18118 ♻️ Remove out of date top level structure
  build-system/tasks/presubmit-checks.js
  extensions/amp-viewer-integration/integrating-viewer-with-amp-doc-guide.md
  screenshots/test/manual/amp-anim.amp.html.png
  screenshots/test/manual/amp-carousel.amp.html.png
  screenshots/test/manual/amp-fit-text.amp.html.png
  screenshots/test/manual/amp-iframe.amp.html.png
  screenshots/test/manual/amp-image-lightbox.amp.html.png
  screenshots/test/manual/amp-img.amp.html.png
  screenshots/test/manual/amp-lightbox.amp.html.png
  viewer-api/swipe-api.js
Labels: cla: yes

#18021 ✨ Collapse ad unit (amp-brid-player) on ad end
  extensions/amp-brid-player/0.1/amp-brid-player.js
  extensions/amp-brid-player/0.1/test/test-amp-brid-player.js
Labels: cla: yes

#18267 Unify all TAG string format in amp-analytics extension.
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/events.js
  extensions/amp-analytics/0.1/iframe-transport-message-queue.js
  extensions/amp-analytics/0.1/iframe-transport.js
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/test/test-config.js
  extensions/amp-analytics/0.1/transport.js
  extensions/amp-analytics/0.1/variables.js
  extensions/amp-analytics/0.1/visibility-manager.js
Labels: cla: yes

#17628 ⏪Unskip amp-brid-player tests
  test/integration/test-video-players.js
Labels: cla: yes

#17720 Improve testing section in "getting-started-e2e.md"
  contributing/getting-started-e2e.md
Labels: cla: yes

#18289 📖 Quickstart: Improve instructions to have a necessary fetch
  contributing/getting-started-quick.md
Labels: cla: yes

#18299 fix spelling favour into favor
  extensions/amp-youtube/0.1/test/test-amp-youtube.js
Labels: cla: yes

#17987 ✨Implement Scroll App connect flow for Safari
  extensions/amp-access-scroll/0.1/scroll-impl.js
Labels: cla: yes

#18302 ♻️Fix spelling issue in product page source
  examples/visual-tests/amp-by-example/samples_templates/product_page/source/index.html
Labels: cla: yes

#18301 closes Issue #18096
  spec/amp-var-substitutions.md
Labels: cla: yes

#18304 🐛Fixes spelling of "white listed" from "whitelisted" in readme
  tools/experiments/README.md
Labels: cla: yes

#18313 📖amp-instagram.md: Spelling Correction from attept to attempt (ACS Codelab 13)
  extensions/amp-instagram/amp-instagram.md
Labels: cla: yes

#18314 📖Spelling tweaks for consistency
  examples/visual-tests/amp-by-example/components/amp-accordion/embed/index.html
Labels: cla: yes

#18320 📖amp-subscriptions: Fix spelling corrections (Codelab 12)
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#18303 Remove amp-carousel new experiment from Canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#18323 📖Fix spelling corrections for test-amp-ad-network-adsense-impl.js (Cod…
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Labels: cla: yes

#18325 🐛ACS-15: Changed all instances of whitelist[ed] to white list[ed]
  spec/amp-html-format.md
Labels: cla: yes

#18326 ♻️ change 'behaviour' to 'behavior' #18107
  examples/visual-tests/amp-by-example/components/amp-accordion/source/index.html
Labels: cla: yes

#18330 📖Update misspelling of behavior in amp-accordion example
  examples/visual-tests/amp-by-example/components/amp-accordion/index.html
Labels: cla: yes

#18333 Revert "⏪Unskip amp-brid-player tests"
  test/integration/test-video-players.js
Labels: cla: yes

#18336 📖 Correct spelling inconsistencies in spec/amp-cache-debugging.md
  spec/amp-cache-debugging.md
Labels: cla: yes

#18312 🐛 Fixes spelling of behavior
  examples/visual-tests/amp-by-example/components/amp-experiment/embed/index.html
Labels: cla: yes

#18295 Renames filterSplice to remove
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-bind/0.1/bind-evaluator.js
  extensions/amp-bind/0.1/bind-impl.js
  src/iframe-helper.js
  src/purifier.js
  src/service/layers-impl.js
  src/service/resources-impl.js
  src/utils/array.js
  test/functional/utils/test-array.js
Labels: cla: yes

#18318 Set global sandbox in _init_tests.js
  test/_init_tests.js
Labels: cla: yes
