Repository ampproject/amphtml, pull requests merged in 2018-11, with the labels that each got.

#19077 Fix docking overlay/shadow not being sized
  src/service/video/docking.js
Labels: cla: yes

#19064 📖 Update code documentation for IE11 A11Y fix
  src/service/navigation.js
Labels: cla: yes

#18961 Update addthis Example
  examples/amp-addthis.amp.html
  extensions/amp-addthis/OWNERS.yaml
Labels: cla: yes

#18820 🐛 placeholder in layout=container should not take space after hiding
  css/amp.css
  test/manual/amp-list-resize.amp.html
Labels: cla: yes

#19062 Better fixed-layer transferability comment
  src/service/fixed-layer.js
Labels: cla: yes

#18873 ✨ amp-3d-gltf: Add action to rotate model
  3p/3d-gltf/viewer.js
  ads/ads.extern.js
  examples/amp-3d-gltf.amp.html
  extensions/amp-3d-gltf/0.1/amp-3d-gltf.js
  extensions/amp-3d-gltf/amp-3d-gltf.md
Labels: cla: yes

#19086 Launch story hold to pause experiment.
  build-system/global-configs/prod-config.json
Labels: cla: yes

#19067 Introduce an experiment that requires body to have a minimum height in iOS embed mode
  css/amp.css
  src/service/viewport/viewport-binding-ios-embed-sd.js
  src/service/viewport/viewport-binding-ios-embed-wrapper.js
  test/functional/test-viewport-binding.js
  tools/experiments/experiments.js
Labels: cla: yes

#19099 Declare scroll-height-minheight at 0% in config
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#19059 📖 fix documentation mistakes of amp-fx-collection
  extensions/amp-fx-collection/amp-fx-collection.md
Labels: cla: yes

#19043 Powr player component
  build-system/dep-check-config.js
  bundles.config.js
  examples/powr-player.amp.html
  extensions/amp-powr-player/0.1/amp-powr-player.js
  extensions/amp-powr-player/0.1/test/test-amp-powr-player.js
  extensions/amp-powr-player/0.1/test/validator-amp-powr-player.html
  extensions/amp-powr-player/0.1/test/validator-amp-powr-player.out
  extensions/amp-powr-player/OWNERS.yaml
  extensions/amp-powr-player/amp-powr-player.md
  extensions/amp-powr-player/validator-amp-powr-player.protoascii
Labels: cla: yes

#18981 [amp-carousel] Add support for defined number of loops to autoplay
  extensions/amp-carousel/0.1/base-slides.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/0.1/test/test-base-slide.js
  extensions/amp-carousel/0.1/test/test-slidescroll.js
  extensions/amp-carousel/0.1/test/validator-amp-carousel.html
  extensions/amp-carousel/0.1/test/validator-amp-carousel.out
  extensions/amp-carousel/amp-carousel.md
  extensions/amp-carousel/validator-amp-carousel.protoascii
Labels: cla: yes

#19100 Explicitly document first viewport recommendation for subscriptions
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#19070 📖 Improve consistency of AMP cache FQDN patterns
  spec/amp-cors-requests.md
Labels: cla: yes

#19110 Render the bookend in its own <amp-story-bookend> tag.
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
Labels: cla: yes

#18943 ✨amp-recaptcha-input: Install recaptcha-service on the document, and use ViewerService isProxyOrigin
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-service.js
Labels: cla: yes

#18260 🏗 Update `make-extension` to use `this.element.ownerDocument`
  build-system/tasks/extension-generator/index.js
Labels: cla: yes

#19065 fixing regexp
  build-system/tasks/create-module-compatible-es5-bundle.js
  gulpfile.js
Labels: cla: yes

#18723 📖 Change the UK spelling of behaviour to US spelling behaviour
  extensions/amp-animation/0.1/css-expr-impl.js
Labels: cla: yes

#19116 typo in amp-subscriptions.md
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#19096 Do not validate for #development=1 when on AMP Caches
  build-system/tasks/presubmit-checks.js
  validator/engine/validator-in-browser.js
Labels: cla: yes

#19113 Hide navigation hint when opening the bookend.
  extensions/amp-story/1.0/amp-story-hint.js
Labels: cla: yes

#19118 Improve amp-analytics integration test coverage
  build-system/amp4test.js
  test/integration/test-amp-analytics.js
  testing/test-helper.js
Labels: cla: yes

#19119 🐛 Bug fix GTAG UA pulls data for dl parameter from the wrong variable.
  extensions/amp-analytics/0.1/vendors/gtag.js
Labels: cla: yes

#19122 Allow decoding on img tag.
  validator/testdata/feature_tests/noscript.html
  validator/testdata/feature_tests/noscript.out
  validator/validator-main.protoascii
Labels: cla: yes

#19058 [ANIMATION WORKLET] Calculate viewport-margins for scroll linked animation
  extensions/amp-animation/0.1/amp-animation.js
  extensions/amp-animation/0.1/web-animations.js
  extensions/amp-position-observer/0.1/amp-position-observer.js
  src/service/action-impl.js
Labels: cla: yes

#19120 Validator rollup
  validator/engine/validator-in-browser.js
  validator/engine/validator_test.js
  validator/testdata/amp4email_feature_tests/anchor.html
  validator/testdata/amp4email_feature_tests/anchor.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#19123 Fix amp4test request-bank
  build-system/amp4test.js
  build-system/tasks/presubmit-checks.js
  test/integration/test-amp-analytics.js
Labels: cla: yes

#19102 Support useBody config to send payload as POST body.
  build-system/amp4test.js
  build-system/app.js
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-transport-serializers.js
  extensions/amp-analytics/0.1/test/test-transport.js
  extensions/amp-analytics/0.1/test/test-vendors.js
  extensions/amp-analytics/0.1/transport-serializer.js
  extensions/amp-analytics/0.1/transport.js
  src/pixel.js
  src/window-interface.js
  test/integration/test-amp-analytics.js
  testing/test-helper.js
Labels: cla: yes

#18809 ♻️Remove non-string log messages
  extensions/amp-form/0.1/amp-form.js
Labels: cla: yes

#19140 Re-launch amp-story-responsive-units experiment
  build-system/global-configs/prod-config.json
Labels: cla: yes

#19137 📖🐛 Corrected the link to hidden global attribute
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#19131 ✨Add support for Apester's new player
  extensions/amp-apester-media/0.1/amp-apester-media.js
Labels: cla: yes

#19108 ♻️ Add internal param to embed-zen config
  ads/zen.js
Labels: cla: yes

#19141 🏗Fix p0 caused by hidden-mutation-observer experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#19104 ♻️ Fixed issue with CLIENT_ID for pressboard analytics vendor
  extensions/amp-analytics/0.1/vendors/pressboard.js
Labels: cla: yes

#16436 amp-analytics: Gemius dnt param
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/gemius.js
Labels: cla: yes

#19091 Add example for reportWhen usage
  examples/analytics-reportWhen.amp.html
Labels: Category: Analytics, cla: yes

#19151 Validator rollup
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#19128 ✨ Allow SVG 'focusable' attribute from SVG Tiny 1.2
  validator/validator-main.protoascii
Labels: cla: yes

#19129 ✨ Remove minimum-scale from required meta viewport properties
  spec/amp-html-format.md
  validator/testdata/feature_tests/bad_viewport.html
  validator/testdata/feature_tests/bad_viewport.out
  validator/testdata/feature_tests/link_meta_values.out
  validator/testdata/feature_tests/minimum_valid_amp.html
  validator/testdata/feature_tests/minimum_valid_amp.out
  validator/validator-main.protoascii
Labels: cla: yes

#19147 swg 0.1.22.37 release
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#19145 [ANIMATION WORKLET ] Support `intersection-ratios`
  extensions/amp-animation/0.1/web-animations.js
Labels: cla: yes

#19150 Ignore lightbox elements in FixedLayer
  src/service/fixed-layer.js
Labels: cla: yes

#19152 ♻️Expander: simplify arguments
  src/service/url-expander/expander.js
  src/service/url-replacements-impl.js
  test/functional/url-expander/test-expander.js
Labels: cla: yes

#19161 Don't encode `ExpandStringAsync`
  build-system/amp4test.js
  src/service/url-expander/expander.js
  src/service/url-replacements-impl.js
  test/functional/test-url-replacements.js
  test/integration/test-amp-analytics.js
  test/integration/test-amp-pixel.js
Labels: cla: yes

#19111 ensure that startDate and endDate are preserved keys. these come from react
  extensions/amp-date-picker/0.1/amp-date-picker.js
Labels: cla: yes

#19163 Re-enable 'hidden-mutation-observer'
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#19153 Delete the amp-story-scroll experiment.
  extensions/amp-story/1.0/amp-story-scroll.css
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  tools/experiments/experiments.js
Labels: cla: yes

#19006 amp-script: Worker debug hooks, use upgrade() API
  examples/amp-script/hello-world.amp.html
  examples/amp-script/hello-world.js
  extensions/amp-script/0.1/amp-script.js
  gulpfile.js
  package.json
  yarn.lock
Labels: cla: yes

#19167 allow attribution and sizes on img within noscript
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#19103 🐛Don't auto opt in linker twice
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
Labels: cla: yes

#18947 ✨amp-recaptcha-input: Added checks to make sure we only allow a single sitekey
  3p/recaptcha.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-service.js
Labels: cla: yes

#18945 ✨ Implements tooltip for amp-story
  bundles.config.js
  extensions/amp-story/1.0/amp-story-grid-layer.js
  extensions/amp-story/1.0/amp-story-hint.css
  extensions/amp-story/1.0/amp-story-hint.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-tooltip.css
  extensions/amp-story/1.0/amp-story-tooltip.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/bookend/components/article.js
  extensions/amp-story/1.0/bookend/components/bookend-component-interface.js
  extensions/amp-story/1.0/bookend/components/landscape.js
  extensions/amp-story/1.0/bookend/components/portrait.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/utils.js
Labels: Category: AMP Story, Type: Feature Request, cla: yes

#19178 Reset the UI once any action completes: delegated or non-delegated
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/dialog.js
  extensions/amp-subscriptions/0.1/local-subscription-platform-renderer.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-dialog.js
  extensions/amp-subscriptions/0.1/test/test-local-subscription-rendering.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#19173 ✨ amp-subscriptions: Add logging to analytics events
  extensions/amp-subscriptions/0.1/analytics.js
Labels: cla: yes

#18698 Add message whitelist functionality to inabox messaging host
  ads/inabox/inabox-messaging-host.js
  test/functional/inabox/test-inabox-messaging-host.js
Labels: cla: yes

#19169 Sync fixed-layer attributes with body
  src/service/fixed-layer.js
  test/functional/test-fixed-layer.js
Labels: cla: yes

#19115 ✨Implement AMP AsyncInput Base Class for amp-recaptcha-input
  src/async-input.js
  test/functional/test-async-input.js
Labels: cla: yes

#19185 Fix HTML_ATTR
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/test/test-requests.js
Labels: cla: yes

#16315 Update csa.md to remove beta language
  ads/google/csa.md
Labels: cla: yes

#19208 Remove text that is no longer needed
  extensions/amp-ad-network-fake-impl/0.1/data/fake_amp_ad_with_html_attr.html
Labels: Category: Analytics, cla: yes

#19209 🐛 Remove direct child combinator for fill layers
  extensions/amp-story/1.0/amp-story-user-overridable.css
Labels: cla: yes

#19204 amp-bind: Support alternative binding syntax with amp-list
  examples/bind/list.amp.html
  src/purifier.js
  src/sanitizer.js
  test/functional/test-purifier.js
  test/functional/test-sanitizer.js
Labels: cla: yes

#19214 Invalidate amp-script
  extensions/amp-script/0.1/test/validator-amp-script.out
  extensions/amp-script/validator-amp-script.protoascii
Labels: cla: yes

#19218 🏗✨ Configure Renovate to allow all active LTS versions of node in package.json
  renovate.json
Labels: Category: Tooling, cla: yes

#17804 🐛Allow looking up AmpDoc when it might not be available.
  src/service/ampdoc-impl.js
  src/service/vsync-impl.js
  test/functional/test-ampdoc.js
Labels: cla: yes

#19186 Introduce a method to update localstorage value
  src/service/storage-impl.js
  test/functional/test-storage.js
Labels: cla: yes

#19249 amp-script: First-pass documentation
  extensions/amp-script/amp-script.md
Labels: cla: yes

#19233 Restrict the number of global replacements variable
  test/functional/test-url-replacements.js
Labels: cla: yes

#19260 🐛Only add runtime classNames custom-elements not in templates
  src/custom-element.js
Labels: cla: yes

#19164 🐛Expander: Don't double encode nested macros
  src/service/url-expander/expander.js
  test/functional/url-expander/test-expander.js
Labels: cla: yes

#19182 Fix placeholder to display none in resizable children
  extensions/amp-list/0.1/amp-list.js
  test/manual/amp-list-with-ads.amp.html
Labels: cla: yes

#18228 🐛amp-video-iframe: add additional iframe sandbox attributes allowing video-ad clickthrough
  extensions/amp-video-iframe/0.1/amp-video-iframe.js
  src/iframe-video.js
Labels: cla: yes

#19179 Docking UX refinements
  css/video-docking.css
  examples/article-with-docked-video.html
  src/service/video/docking.js
  test/functional/test-video-docking.js
Labels: cla: yes

#19264 🏗 Update allowed nodejs versions for validator
  validator/nodejs/package.json
  validator/package.json
  validator/webui/package.json
Labels: Category: Tooling, cla: yes

#19262 SwG Release 0.1.22.38
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#18915 ✨amp-recaptcha-input: Origin Domain Verification within Bootstrap Frame
  3p/iframe-messaging-client.js
  3p/recaptcha.js
  build-system/tasks/presubmit-checks.js
  examples/recaptcha.amp.html
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  test/functional/3p/test-iframe-messaging-client.js
  test/functional/3p/test-recaptcha.js
Labels: cla: yes

#19175 ✨Support object-fit transitions for amp-lightbox-gallery
  build-system/tasks/compile.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  package.json
  test/manual/amp-lightbox-gallery.amp.html
  yarn.lock
Labels: cla: yes

#19272 add missing `-`
  extensions/amp-mowplayer/OWNERS.yaml
Labels: Category: Tooling, cla: yes

#19273 🐛 Delete validator-amp-delight.player.out
  extensions/amp-delight-player/0.1/test/validator-amp-delight.player.out
Labels: cla: yes

#19268 🐛 Fixed typo in onInfoDialogStateUpdated_ method JSDoc.
  extensions/amp-story/1.0/amp-story-info-dialog.js
Labels: cla: yes

#18401 🏗 Add .editorconfig
  .editorconfig
Labels: cla: yes

#18962 Amp byside content improvements
  extensions/amp-byside-content/0.1/amp-byside-content.js
  extensions/amp-byside-content/0.1/test/test-amp-byside-content.js
  extensions/amp-byside-content/0.1/test/validator-amp-byside-content.out
  extensions/amp-byside-content/0.1/utils.js
Labels: cla: yes

#19282 📖 Update documentation regarding publicly accessibly Percy project
  contributing/TESTING.md
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
Labels: cla: yes

#19274 🐛Fix transition playing when closing from gallery view.
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#19217 Adds unit tests for tooltip ✅
  extensions/amp-story/1.0/test/test-amp-story-tooltip.js
Labels: cla: yes

#19294 Validator rollup
  extensions/amp-script/0.1/test/validator-amp-script.out
  extensions/amp-script/validator-amp-script.protoascii
  validator/validator-main.protoascii
Labels: cla: yes

#19287 Don't display tooltip when target is under cta layer 🐛
  extensions/amp-story/1.0/page-advancement.js
Labels: cla: yes

#19300 Validator rollup
  validator/validator-main.protoascii
Labels: cla: yes

#19197 Remove vsync guards to fx presets
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js
  extensions/amp-fx-collection/0.1/providers/fx-provider.js
Labels: cla: yes

#19174 Updated AMP Story ad documentation
  extensions/amp-story/amp-story-ads.md
Labels: cla: yes

#19212 Fix gestures recognizers end up in broken state after additional unaccounted for touch
  src/gesture-recognizers.js
  src/gesture.js
  test/functional/test-gesture-recognizers.js
Labels: cla: yes

#19198 Add comments to fixed-layer synchronization
  src/service/fixed-layer.js
Labels: cla: yes

#19202 Ban DOM v4 methods
  build-system/conformance-config.textproto
  build-system/tasks/presubmit-checks.js
  extensions/amp-access-laterpay/0.1/laterpay-impl.js
  extensions/amp-access-laterpay/0.2/laterpay-impl.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-form/0.1/amp-form.js
  src/custom-element.js
Labels: cla: yes

#19283 🐛Update cookie name from segment_amp_id to _ga
  extensions/amp-analytics/0.1/vendors/segment.js
Labels: cla: yes

#19296 Render AMP fluid creatives when iframe fires load event
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js
Labels: cla: yes

#19271 Opt in into the desktop full bleed experience.
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#19303 Stories share menu redesign.
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/amp-story-share-menu.css
  extensions/amp-story/1.0/amp-story-share-menu.js
  extensions/amp-story/1.0/amp-story-share.css
  extensions/amp-story/1.0/amp-story-share.js
Labels: cla: yes

#19301 Fix <amp-fx="fly-in-{left|right}"> for IE/Edge.
  examples/test-fly-in.amp.html
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js
  extensions/amp-fx-collection/0.1/test/integration/test-amp-fx-fly-in.js
Labels: cla: yes

#19201 ✨Converted amp-recaptcha-input into an AsyncInput Element
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  src/async-input.js
  test/functional/test-async-input.js
Labels: cla: yes

#19309 ♻️Update iterateCursor
  src/dom.js
Labels: cla: yes

#19317 Stories desktop fullbleed bookend.
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
Labels: cla: yes

#19319 🐛Run an initial render in buildCallback
  extensions/amp-date-picker/0.1/amp-date-picker.js
Labels: cla: yes

#19196 Integration tests for amp-video-iframe
  extensions/amp-video-iframe/0.1/amp-video-iframe.js
  test/fixtures/video-players.html
  test/integration/test-video-players-helper.js
  test/integration/test-video-players.js
Labels: cla: yes

#19316 🏗 Add `--fortesting` to `gulp build` step in `pr-check.js`
  build-system/pr-check.js
  contributing/TESTING.md
  gulpfile.js
Labels: cla: yes

#19323 🚮 Remove ad-like assertions from amp-video-iframe
  extensions/amp-video-iframe/0.1/amp-video-iframe.js
  extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
Labels: cla: yes

#18758 🐛fix amp-ad support for Ad Generation
  ads/adgeneration.js
  ads/adgeneration.md
Labels: cla: yes

#19328 🐛 Mute/unmute only if not managed by MediaPool
  extensions/amp-video/0.1/amp-video.js
Labels: cla: yes

#19329 🏗 Silence fake XHR server logs during automated tests
  build-system/amp4test.js
  build-system/tasks/runtime-test.js
Labels: Category: Tooling, cla: yes

#19216 Various amp-selector clean up
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-selector/0.1/test/test-amp-selector.js
  extensions/amp-selector/0.1/test/test-selector-list.js
  src/types.js
  src/utils/array.js
Labels: cla: yes

#19335 🐛story-ads: prevent users getting stuck
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
Labels: cla: yes

#19299 add more owners for extensions
  extensions/OWNERS.yaml
  extensions/amp-3q-player/OWNERS.yaml
  extensions/amp-ad-custom/OWNERS.yaml
  extensions/amp-ad-exit/OWNERS.yaml
  extensions/amp-ad-network-adzerk-impl/OWNERS.yaml
  extensions/amp-anim/OWNERS.yaml
  extensions/amp-beopinion/OWNERS.yaml
  extensions/amp-consent/OWNERS.yaml
  extensions/amp-date-countdown/OWNERS.yaml
  extensions/amp-date-picker/OWNERS.yaml
  extensions/amp-delight-player/OWNERS.yaml
  extensions/amp-dynamic-css-classes/OWNERS.yaml
  extensions/amp-embedly-card/OWNERS.yaml
  extensions/amp-fit-text/OWNERS.yaml
  extensions/amp-google-document-embed/OWNERS.yaml
  extensions/amp-gwd-animation/OWNERS.yaml
  extensions/amp-ima-video/OWNERS.yaml
  extensions/amp-image-slider/OWNERS.yaml
  extensions/amp-inputmask/OWNERS.yaml
  extensions/amp-list/OWNERS.yaml
  extensions/amp-mustache/OWNERS.yaml
  extensions/amp-pan-zoom/OWNERS.yaml
  extensions/amp-riddle-quiz/OWNERS.yaml
  extensions/amp-slides/OWNERS.yaml
  extensions/amp-story-auto-ads/OWNERS.yaml
  extensions/amp-story/OWNERS
  extensions/amp-story/OWNERS.yaml
  extensions/amp-subscriptions-google/OWNERS.yaml
  extensions/amp-subscriptions/OWNERS.yaml
  extensions/amp-twitter/OWNERS.yaml
  extensions/amp-user-notification/OWNERS.yaml
  extensions/amp-video-service/OWNERS.yaml
  extensions/amp-vk/OWNERS.yaml
  extensions/amp-web-push/OWNERS.yaml
  extensions/amp-wistia-player/OWNERS.yaml
  extensions/amp-yotpo/OWNERS.yaml
Labels: cla: yes

#19325 Add minimum ratio for <amp-orientation-observer> to reduce 'jerkiness'
  examples/amp-orientation-observer-amp-3d-gltf.amp.html
  extensions/amp-orientation-observer/0.1/amp-orientation-observer.js
Labels: cla: yes

#19342 Skip amp-video-iframe integration tests
  test/integration/test-video-players.js
Labels: cla: yes

#19327 🏗 `gulp visual-diff` refactor and stability fixes
  build-system/.eslintrc
  build-system/tasks/presubmit-checks.js
  build-system/tasks/visual-diff/helpers.js
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#19305 Synchronous Custom Elements Polyfill
  src/polyfills/custom-elements.js
Labels: cla: yes

#19324 ♻️ Fix string literal warnings in UI extensions
  extensions/amp-accordion/0.1/amp-accordion.js
  extensions/amp-animation/0.1/amp-animation.js
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-date-countdown/0.1/amp-date-countdown.js
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-live-list/0.1/amp-live-list.js
  extensions/amp-live-list/0.1/live-list-manager.js
  extensions/amp-next-page/0.1/amp-next-page.js
  extensions/amp-next-page/0.1/config.js
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-next-page/0.1/test/test-config.js
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  extensions/amp-pinterest/0.1/amp-pinterest.js
  extensions/amp-pinterest/0.1/pin-widget.js
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-share-tracking/0.1/amp-share-tracking.js
  extensions/amp-video-service/0.1/amp-video-service.js
Labels: cla: yes

#19076 pass single pass type to query params if it exists
  build-system/amp.extern.js
  src/error.js
  src/mode-object.js
  src/mode.js
  test/functional/test-error.js
Labels: Category: Tooling, cla: yes

#19332 Cleanup the amp-story-hold-to-pause experiment.
  extensions/amp-story/1.0/page-advancement.js
Labels: cla: yes

#19194 🐛 Fix thirds and fill layer in Safari
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#19308 📖story-ads: update docs
  extensions/amp-story/amp-story-auto-ads.md
Labels: cla: yes

#19168 🐛Intersection Observer Polyfill Mutation Observer - Fixed Race Condition
  extensions/amp-a4a/0.1/test/test-refresh.js
  src/intersection-observer-polyfill.js
  src/service/resources-impl.js
  test/functional/test-intersection-observer-polyfill.js
  test/functional/test-resources.js
Labels: cla: yes

#19313 Exclude build-system directory from the LGTM analysis
  .lgtm.yml
Labels: cla: yes

#19275 ✨ anchor mutators on contextmenu event (navigation.js)
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-skimlinks/0.1/link-rewriter/link-rewriter-manager.js
  extensions/amp-skimlinks/0.1/test/test-link-rewriter.js
  src/service/navigation.js
Labels: cla: yes

#19336 Change the background color of highlighted texts from yellow to orange.
  extensions/amp-viewer-integration/0.1/highlight-handler.js
  extensions/amp-viewer-integration/0.1/test/test-highlight-handler.js
Labels: cla: yes

#19356 🏗 Update `third_party/closure-library/sha384-generated.js`
  third_party/closure-library/sha384-generated.js
Labels: Category: Runtime, Category: Tooling, cla: yes

#19357 add owners to third_party
  third_party/OWNERS.yaml
Labels: cla: yes

#18188 ✨ amp-next-page: Add support for type="adsense"
  extensions/amp-next-page/0.1/amp-next-page.js
  extensions/amp-next-page/0.1/config.js
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
  extensions/amp-next-page/0.1/test/test-config.js
  extensions/amp-next-page/0.1/test/validator-amp-next-page-adsense.html
  extensions/amp-next-page/0.1/test/validator-amp-next-page-adsense.out
  extensions/amp-next-page/validator-amp-next-page.protoascii
Labels: cla: yes

#19311 ♻️ AMP-Consent: Move config related code to its own file
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-config.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-config.js
Labels: cla: yes

#19250 ✅ Add visual and interactive test for amp-story-tooltip
  examples/visual-tests/amp-story/amp-story-tooltip-desktop.js
  examples/visual-tests/amp-story/amp-story-tooltip.html
  examples/visual-tests/amp-story/amp-story-tooltip.js
  extensions/amp-story/1.0/amp-story-tooltip.css
  test/visual-diff/visual-tests
Labels: cla: yes

#19365 ✅ Mark two visual diff tests as flaky
  test/visual-diff/visual-tests
Labels: cla: yes

#19355 FIE support for <amp-gwd-animation>
  examples/gwd.amp.html
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation.js
  extensions/amp-gwd-animation/0.1/test/test-amp-gwd-animation.js
Labels: cla: yes

#19315 Making pagination buttons available on panels and fullbleed desktop experience.
  extensions/amp-story/1.0/amp-story-desktop.css
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/pagination-buttons.css
Labels: cla: yes

#19340 Fix dynamic extension path
  src/service/extension-location.js
  test/functional/test-extension-location.js
Labels: cla: yes

#19367 🐛 Trick Closure compiler to preserve reflow codepath
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
Labels: cla: yes

#19341 Move Percy installation to visual-diff task
  .travis.yml
  build-system/config.js
  build-system/tasks/visual-diff/index.js
  build-system/tasks/visual-diff/package.json
  build-system/tasks/visual-diff/yarn.lock
  package.json
  yarn.lock
Labels: cla: yes

#18983 ✨ Add type adyoulike for the amp-ad tag
  3p/integration.js
  ads/_config.js
  ads/adyoulike.js
  ads/adyoulike.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#19348 Uninstall positionObserver when using WorkletAnimation
  extensions/amp-position-observer/0.1/amp-position-observer.js
Labels: cla: yes

#19373 🐛 Replace CDN URLs in video testbench
  build-system/app-utils.js
  build-system/app-video-testbench.js
  build-system/app.js
Labels: cla: yes

#19285 add amp-story-tooltip anchor tags validation ✅
  extensions/amp-story/1.0/test/validator-amp-story-tooltip-error.html
  extensions/amp-story/1.0/test/validator-amp-story-tooltip-error.out
  extensions/amp-story/1.0/test/validator-amp-story-tooltip.html
  extensions/amp-story/1.0/test/validator-amp-story-tooltip.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#19368 ♻️ Add typedefs for pool-bound and placeholder elements
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/media-pool.js
Labels: cla: yes

#19384 🐛 amp-subscriptions platform reset all platforms on reauthorise
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Labels: cla: yes

#19387 🏗🐛 Modify the error handling of visual diff tests to be more robust
  build-system/tasks/visual-diff/helpers.js
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#19190 ✨ Dynamic playlist support (amp-brid-player)
  extensions/amp-brid-player/0.1/amp-brid-player.js
Labels: cla: yes

#19363 🐛Analytics: Allow repeat hidden triggers
  extensions/amp-analytics/0.1/events.js
Labels: cla: yes

#19390 ✅ Disable flaky desktop stories test
  test/visual-diff/visual-tests
Labels: cla: yes

#18954 🐛 amp-ima-video: Show sound and fullscreen buttons during ads
  ads/ads.extern.js
  ads/google/imaVideo.js
  examples/ima-video.amp.html
  extensions/amp-ima-video/0.1/test/test-amp-ima-video.js
Labels: cla: yes

#19322 Disallow URL attribute bindings in amp4email
  extensions/amp-bind/0.1/bind-evaluator.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/bind-validator.js
  extensions/amp-bind/0.1/test/test-bind-validator.js
  src/web-worker/web-worker.js
  test/fixtures/bind-amp4email.html
  test/integration/test-amp-bind.js
Labels: cla: yes

#19344 Fix element services and AMP.setState in FIE
  src/service/extensions-impl.js
  src/service/standard-actions-impl.js
  test/functional/test-extensions.js
Labels: cla: yes
