Repository ampproject/amphtml, pull requests merged in 2018-04, with the labels that each got.

#14326 🐛Clear the hidden input elements on the clear action.
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-selector/0.1/test/test-amp-selector.js
Labels: cla: yes

#14352 Skip flaky tests
  test/functional/test-error.js
  test/functional/test-url.js
Labels: cla: yes

#14324 🔀Gate `VideoService` implementation with experiment
  build-system/tasks/compile.js
  extensions/amp-story/0.1/amp-story-page.js
  extensions/amp-video-service/0.1/amp-video-service.js
  extensions/amp-video/0.1/amp-video.js
  src/service/url-replacements-impl.js
  src/service/video-manager-impl.js
  src/service/video-service-sync-impl.js
  src/services.js
  test/functional/test-url-replacements.js
Labels: cla: yes

#14168 Add AdinCube ad network
  3p/integration.js
  ads/_config.js
  ads/adincube.js
  ads/adincube.md
  build-system/conformance-config.textproto
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#14235 ♿ Adds Alt & aria-label to Placeholder Image of amp-gfycat
  extensions/amp-gfycat/0.1/amp-gfycat.js
  extensions/amp-gfycat/0.1/test/test-amp-gfycat.js
  test/manual/amp-gfycat.amp.html
Labels: cla: yes

#14276 Rewrite amp-fx-collection code to allow new presets
  build-system/dep-check-config.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-bodymovin-animation/amp-bodymovin-animation.html
  extensions/amp-fx-collection/0.1/amp-fx-collection.js
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js
  extensions/amp-fx-collection/0.1/providers/fx-provider.js
Labels: cla: yes

#14356 SwG release 0.1.22.3
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#14374 🏗 Fix sauce platform list
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test.js
Labels: cla: yes

#14369 Support multi-doc for subscriptions
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/doc-impl.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-doc-impl.js
Labels: cla: yes

#14332 ♻️ Move sauce connect scripts to a subdirectory
  .gitignore
  .travis.yml
  build-system/pr-check.js
  build-system/sauce_connect/start_sauce_connect.sh
  build-system/sauce_connect/stop_sauce_connect.sh
Labels: Category: Tooling, cla: yes

#14306 Enable amp-consent to block components
  build-system/tasks/compile.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  src/base-element.js
  src/consent-state.js
  src/custom-element.js
  src/error.js
  src/service/resource.js
  src/service/resources-impl.js
  src/services.js
  test/functional/test-custom-element.js
  test/manual/amp-consent.html
Labels: cla: yes

#14179 🚀 Index Exchange: Change HREF macro to CANONICAL_URL in vendor call
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#14217 Fix elementHeight, elementWidth for ads
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-analytics/0.1/visibility-manager.js
Labels: Category: Ads, cla: yes

#14370 Change store service registration
  src/services.js
Labels: cla: yes

#14361 Doubleclick Fast Fetch: force safeframe support
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
Labels: cla: yes

#14373 Apply maxHeight restriction to consent UI
  extensions/amp-consent/0.1/amp-consent.css
  extensions/amp-consent/0.1/amp-consent.js
Labels: cla: yes

#14383 Whitelist origins for amp-story: week of 2018-04-03
  extensions/amp-story/0.1/origin-whitelist.js
Labels: cla: yes

#14381 ♻️ Remove duplicate shadowRoot.appendChild, which happens inside shadow-embed.js#importShadowBody
  src/runtime.js
Labels: cla: yes

#14331 Clean up lightbox docs and runtime validation
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-placeholders.js
  extensions/amp-lightbox-gallery/amp-lightbox-gallery.md
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#14390 Doubleclick Fast Fetch Auto SRA experiment
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/doubleclick-a4a-config.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-a4a-config.js
Labels: cla: yes

#14322 ♿Add more ARIA roles to emit the AMP tap event
  src/service/action-impl.js
  test/functional/test-action.js
Labels: cla: yes

#14397 Subscriptions: microdata configuration docs
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#14396 Subscriptions: raw bug fix
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-entitlement.js
Labels: cla: yes

#14389 Remove defaults for freshLifetimeSecs and validLifetimeSecs
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
Labels: cla: yes

#14144 :sparkles: Add Salesforce DMP as a vendor in DoubleClick RTC
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#14400 🐛 Install Video Service at story page level when delegating autoplay
  build-system/dep-check-config.js
  extensions/amp-story/0.1/amp-story-page.js
Labels: cla: yes

#14402 Click shield on top of story videos.
  extensions/amp-story/0.1/amp-story.css
Labels: cla: yes

#14393 Stories XHR request service.
  extensions/amp-story/0.1/amp-story-bookend.js
  extensions/amp-story/0.1/amp-story-request-service.js
  extensions/amp-story/0.1/amp-story-share.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/test/test-amp-story-request-service.js
  src/services.js
Labels: cla: yes

#14399 Allow specifying ExtensionOptions in declareExtensionVersionAlias
  gulpfile.js
Labels: cla: yes

#14096 Add kuadio ad network
  3p/integration.js
  ads/_config.js
  ads/kuadio.js
  ads/kuadio.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#14412 Make click shield more specific and important
  extensions/amp-story/0.1/amp-story.css
Labels: cla: yes

#14411 Adding experimentId for Doubleclick DF Whitelist Deprecation experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#14395 ✨ AdSense Ads: add support for specifying package code
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Labels: cla: yes

#14363 Lightbox UX Polish: clean up description animation details
  extensions/amp-image-viewer/0.1/amp-image-viewer.css
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#14404 Amp-consent enable consent dismissal
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  test/manual/amp-consent.html
Labels: cla: yes

#14434 JWT times are in seconds
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Labels: cla: yes

#14283 update docs to reflect updates in now supported css properties
  spec/amp-html-format.md
Labels: cla: yes

#14438 Add ABE example link for amp-bodymovin-animation
  extensions/amp-bodymovin-animation/amp-bodymovin-animation.md
Labels: cla: yes

#14421 ✨Adds option to suppress warning for analytics image requests
  extensions/amp-analytics/0.1/test/test-transport.js
  extensions/amp-analytics/0.1/transport.js
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#14391 ♿ Adds Alt & aria-label to Placeholder Images
  extensions/amp-brid-player/0.1/amp-brid-player.js
  extensions/amp-brid-player/0.1/test/test-amp-brid-player.js
  extensions/amp-jwplayer/0.1/amp-jwplayer.js
  extensions/amp-jwplayer/0.1/test/test-amp-jwplayer.js
  extensions/amp-kaltura-player/0.1/amp-kaltura-player.js
  extensions/amp-kaltura-player/0.1/test/test-amp-kaltura-player.js
  extensions/amp-springboard-player/0.1/amp-springboard-player.js
  extensions/amp-springboard-player/0.1/test/test-amp-springboard-player.js
  extensions/amp-youtube/0.1/amp-youtube.js
  extensions/amp-youtube/0.1/test/test-amp-youtube.js
Labels: cla: yes

#14403 🐛Don't save story ads to history
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/test/test-amp-story.js
Labels: cla: yes

#14382 Overwrite or set attr target=_blank in outlinks for amp-story
  extensions/amp-story/0.1/amp-story-cta-layer.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/test/test-amp-story-cta-layer.js
Labels: cla: yes

#14446 Fast Fetch network failure collapse slot fix
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
Labels: cla: yes

#14351 Add amp-fx="fade-in" - scroll triggered timed animation.
  examples/article-fade-in.amp.html
  extensions/amp-fx-collection/0.1/amp-fx-collection.js
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets-utils.js
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js
  extensions/amp-fx-collection/0.1/providers/fx-provider.js
  extensions/amp-fx-collection/0.1/test/validator-amp-fx-collection.html
  extensions/amp-fx-collection/0.1/test/validator-amp-fx-collection.out
  extensions/amp-fx-collection/amp-fx-collection.md
  tools/experiments/experiments.js
  validator/validator-main.protoascii
Labels: cla: yes

#13911 AMP ad tag for PubMatic UAS (:sparkles:)
  3p/integration.js
  ads/_config.js
  ads/ads.extern.js
  ads/uas.js
  ads/uas.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: no

#14405 Integrate `bundlesize` and cap main binary size
  gulpfile.js
  package.json
  yarn.lock
Labels: cla: yes

#14407 Amp consent API to get real time consent status
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  src/consent-state.js
  src/custom-element.js
Labels: cla: yes

#14453 Subscriptions: more documentation on emulating viewer behavior
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#14455 Making sure the system layer buttons touch feedback does not overlap the progress bar.
  extensions/amp-story/0.1/amp-story-system-layer.css
Labels: cla: yes

#14459 Bundlesize follow-up
  gulpfile.js
Labels: cla: yes

#14448 Subscriptions: Send auth-rejection to viewer
  build-system/tasks/presubmit-checks.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement.js
  extensions/amp-subscriptions/0.1/platform-store.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-url-builder.js
Labels: cla: yes

#14460 Sync to Github
  extensions/amp-date-picker/validator-amp-date-picker.protoascii
  validator/validator-main.protoascii
Labels: cla: yes

#14436 Clarify info for prefer-viewability-over-views
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#14463 Repair responsive tests by changing error reporting to warn
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Labels: cla: yes

#14441 🖍 Set font-display for amp-story
  extensions/amp-story/0.1/amp-story-user-overridable.css
Labels: cla: yes

#14428 Update amp-story-analytics.md
  extensions/amp-story/amp-story-analytics.md
Labels: cla: yes

#14431 ✨Add custom carousel controls for <amp-lightbox-gallery>
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#14470 <amp-facebook> Bug fix for video always showing caption
  3p/facebook.js
  extensions/amp-facebook/0.1/test/test-amp-facebook.js
  extensions/amp-facebook/amp-facebook.md
Labels: cla: yes

#14461 Subscriptions: Auth flow for viewer authentication
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Labels: cla: yes

#14430 ✨add play icon and timestamp to video thumbnails in lightbox gallery
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#14452 Story share menu.
  extensions/amp-story/0.1/amp-story-hint.js
  extensions/amp-story/0.1/amp-story-share-menu.css
  extensions/amp-story/0.1/amp-story-share-menu.js
  extensions/amp-story/0.1/amp-story-store-service.js
  extensions/amp-story/0.1/amp-story-system-layer.css
  extensions/amp-story/0.1/amp-story-system-layer.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/test/test-amp-story-share-menu.js
  extensions/amp-story/0.1/test/test-system-layer.js
  gulpfile.js
Labels: cla: yes

#14473 Subscriptions: Buildurl fix
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Labels: cla: yes

#14445 🐛fix lightbox thumbnail api bugs
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#14416 Restart failing `<amp-bodymovin-animation>` integration test
  extensions/amp-bodymovin-animation/0.1/test/integration/test-amp-bodymovin-animation.js
Labels: cla: yes

#14474 Upstream more validator changes.
  extensions/amp-bind/validator-amp-bind.protoascii
  validator/validator-main.protoascii
Labels: cla: yes

#14464 ✨ amp-geo pre-release integration
  examples/amp-geo.amp.html
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-geo/0.1/test/test-amp-geo.js
  extensions/amp-geo/OWNERS.yaml
  extensions/amp-geo/amp-geo.md
  extensions/amp-geo/validator-amp-geo.protoascii
  gulpfile.js
  src/mode.js
  src/service/url-replacements-impl.js
  src/services.js
  validator/testdata/feature_tests/amp_geo.html
  validator/testdata/feature_tests/amp_geo.out
Labels: cla: yes

#14478 amp-consent: disable multi consent with flag
  examples/amp-consent.amp.html
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
Labels: cla: yes

#14479 Upgrade Web Activities to 1.8
  package.json
  yarn.lock
Labels: cla: yes

#14489 🌐 Add new strings for amp-consent integration
  extensions/amp-story/0.1/_locales/en.js
  extensions/amp-story/0.1/localization.js
Labels: cla: yes

#14443 ♻️Move amp-story-auto-ads to its own extension
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
  extensions/amp-story/0.1/amp-story-auto-ads.js
  extensions/amp-story/0.1/amp-story.css
  extensions/amp-story/0.1/amp-story.js
  gulpfile.js
Labels: cla: yes

#14300 ✨ amp-document-recommendations: Use PositionObserver to detect when active document changes
  build-system/dep-check-config.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-document-recommendations/0.1/amp-document-recommendations.js
Labels: cla: yes

#14451 ✨✅Add support for date input. Begin tests for date-picker functionality.
  examples/date-picker.amp.html
  extensions/amp-date-picker/0.1/amp-date-picker.css
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/constants.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker.js
Labels: cla: yes

#14485 Fix amp-list dynamic CORS detection
  extensions/amp-list/0.1/amp-list.js
Labels: cla: yes

#14491 🐛 Don't require ampCors for amp-document-recommendations requests
  extensions/amp-document-recommendations/0.1/amp-document-recommendations.js
Labels: cla: yes

#14493 🐛Fix next / prev control colors on lightbox
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
Labels: cla: yes

#14500 Only preloads the share menu on mobile.
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/test/test-amp-story.js
Labels: cla: yes

#14496 Rename the test-system-layer file.
  extensions/amp-story/0.1/test/test-amp-story-system-layer.js
Labels: cla: yes

#14466 amp-consent postPromptUI
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  src/service/notification-ui-manager.js
  test/functional/test-notification-ui-manager.js
  test/manual/amp-consent.html
Labels: cla: yes

#14506 Upgrade SwG to 0.1.22.4
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#14507 amp-consent postPromptUI css change in single vsync mutate
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
Labels: cla: yes

#14495 Upgrade fetch-mock to 6.1.0
  extensions/amp-pinterest/0.1/test/test-amp-pinterest.js
  package.json
  testing/describes.js
  yarn.lock
Labels: cla: yes

#14481 ✨Disallow sync XHR in ad iframes.
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  src/3p-frame.js
  test/integration/test-3p-frame.js
  tools/experiments/experiments.js
Labels: cla: yes

#14509 Upstream more validator changes
  validator/testdata/feature_tests/amp_geo.out
  validator/validator-main.protoascii
Labels: cla: yes

#14224 ✨ Add support for custom tabs.
  gulpfile.js
  src/impression.js
  src/service/viewer-impl.js
  test/functional/test-viewer.js
Labels: cla: yes

#14511 Fix Travis 😅
  gulpfile.js
Labels: cla: yes

#14274 s/camelburrito/aghassemi
  GOVERNANCE.md
  examples/OWNERS.yaml
  extensions/amp-accordion/OWNERS.yaml
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/OWNERS.yaml
  extensions/amp-font/OWNERS.yaml
  extensions/amp-iframe/OWNERS.yaml
  extensions/amp-selector/OWNERS.yaml
  extensions/amp-sidebar/OWNERS.yaml
Labels: cla: yes

#14494 Share menu as a list.
  extensions/amp-story/0.1/amp-story-share-menu.js
  extensions/amp-story/0.1/amp-story-share.css
  extensions/amp-story/0.1/test/test-amp-story-share-menu.js
Labels: cla: yes

#14465 ✨ Document-level infinite-scroll (#12945): Adds support for a separator that is attached in-between pages.
  examples/amp-document-recommendations.amp.html
  extensions/amp-document-recommendations/0.1/amp-document-recommendations.css
  extensions/amp-document-recommendations/0.1/amp-document-recommendations.js
  extensions/amp-document-recommendations/validator-amp-document-recommendations.protoascii
Labels: cla: yes

#14523 doc cleanup for fast fetch guide
  ads/google/a4a/docs/Network-Impl-Guide.md
Labels: cla: yes

#14477 Add goToSlide to scrollable-slides
  examples/carousel.amp.html
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
Labels: cla: yes

#14526 Whitelist origins for amp-story: week of 2018-04-10
  extensions/amp-story/0.1/origin-whitelist.js
Labels: cla: yes

#14502 ✨ A4A: Add new browser capabilities (bc) parameter to ad requests
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
Labels: cla: yes

#14531 Use native system sharing when supported.
  extensions/amp-story/0.1/amp-story-share-menu.js
  extensions/amp-story/0.1/amp-story-share.js
  extensions/amp-story/0.1/test/test-amp-story-share-menu.js
Labels: cla: yes

#14515 ✨ amp-document-recommendations: Trigger analytics events when setting active document
  extensions/amp-document-recommendations/0.1/amp-document-recommendations.js
Labels: cla: yes

#14534 Rename "consentRequired"
  build-system/app.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
Labels: cla: yes

#14537 amp-carousel: Update amp-actions-and-events.md
  spec/amp-actions-and-events.md
Labels: cla: yes

#14518 Doubleclick SRA fix to handle multi-size
  ads/google/a4a/utils.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
Labels: cla: yes

#14499 Amp-Ad Fast Fetch: make nameframe default xdomain render method
  build-system/dep-check-config.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#14539 ✨ AdSense Ads: add support for specifying package code
  ads/google/adsense.js
  ads/google/test/test-adsense.js
Labels: cla: yes

#14525 Access iframe: get rid of data subfield; update examples
  examples/article-access-iframe.provider.html
  extensions/amp-access/0.1/amp-access-iframe.js
  extensions/amp-access/0.1/iframe-api/README.md
  extensions/amp-access/0.1/iframe-api/access-controller.js
  extensions/amp-access/0.1/test/test-amp-access-iframe.js
  extensions/amp-access/0.1/test/test-iframe-api.js
Labels: cla: yes

#14546 Just some doc cleanup for amp-ad integration guide
  ads/README.md
Labels: cla: yes

#14476 subscriptions: test cleanup
  extensions/amp-subscriptions/0.1/entitlement.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-dialog.js
  extensions/amp-subscriptions/0.1/test/test-entitlement.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-platform-store.js
  extensions/amp-subscriptions/0.1/test/test-url-builder.js
  extensions/amp-subscriptions/0.1/test/test-viewer-tracker.js
Labels: cla: yes

#14556 Missed closing brace
  ads/README.md
Labels: cla: yes

#14554 🐛 🏗 Intrinsic image size bug, reduce size of svg
  css/amp.css
  src/layout.js
  test/functional/test-layout.js
Labels: cla: yes

#14550 🐛 amp-consent prompt UI race condition fix
  extensions/amp-consent/0.1/amp-consent.js
Labels: cla: yes

#14557 amp-consent: Ignore user defined consent instance to retrigger prompt.
  examples/amp-consent.amp.html
  extensions/amp-consent/0.1/amp-consent.js
Labels: cla: yes

#14450 Add support for cache:getClientId
  gulpfile.js
  src/service/cache-cid-api.js
  src/service/cid-impl.js
  src/service/viewer-cid-api.js
  src/service/viewer-impl.js
  test/functional/test-cache-cid-api.js
  test/functional/test-cid.js
  test/functional/test-viewer-cid-api.js
Labels: cla: yes

#14362 Adds CryptographicValidator
  extensions/amp-a4a/0.1/amp-ad-type-defs.js
  extensions/amp-a4a/0.1/amp-ad-utils.js
  extensions/amp-a4a/0.1/cryptographic-validator.js
  extensions/amp-a4a/0.1/friendly-frame-renderer.js
  extensions/amp-a4a/0.1/test/test-amp-ad-utils.js
  extensions/amp-a4a/0.1/test/test-cryptographic-validator.js
  extensions/amp-a4a/0.1/test/testdata/valid_css_at_rules_amp.reserialized.js
Labels: cla: yes

#14522 Subscriptions: Adding analytics
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/analytics.js
  extensions/amp-subscriptions/0.1/entitlement.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-actions.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-analytics.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Labels: cla: yes

#14558 Allow pingback to return non-promise result
  extensions/amp-access/0.1/iframe-api/iframe-api.js
  extensions/amp-access/0.1/test/test-iframe-api.js
Labels: cla: yes

#14567 Validator rollup
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#14508 Consent API introduce UNKNOWN & IGNORED state
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  gulpfile.js
  src/consent-state.js
  src/custom-element.js
Labels: cla: yes

#14566 🐛update svg sizing for whatsapp and twitter icons on `<amp-social-share>`
  third_party/optimized-svg-icons/amp-social-share-svgs.css
Labels: cla: yes

#14555 Adjust lightbox arrow button sizing per UX Review
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#14196 amp-story: Metadata docs
  extensions/amp-story/amp-story.md
Labels: cla: yes

#14564 ✨ Allow updating the title of the page using amp-bind
  examples/bind/title.amp.html
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  validator/validator-main.protoascii
Labels: cla: yes

#14561 ✅ Fixes 2 unit tests
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
Labels: Category: Analytics, cla: yes

#14577 ✨ amp-geo pre-release testing
  examples/amp-geo.amp.html
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-geo/0.1/test/test-amp-geo.js
Labels: cla: yes

#14581 ✅ Skip flaky Bind tests
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
Labels: Related to: Flaky Tests, cla: yes

#14583 🏗 Print only the first line of error messages
  test/_init_tests.js
Labels: Category: Tooling, cla: yes

#14334 🐛Tweaks "ken burns" animations to check for image sizes
  examples/amp-story/animations-presets.html
  examples/amp-story/visual-effects.html
  extensions/amp-animation/0.1/web-animation-types.js
  extensions/amp-story/0.1/amp-story-grid-layer.js
  extensions/amp-story/0.1/amp-story.css
  extensions/amp-story/0.1/animation-presets-utils.js
  extensions/amp-story/0.1/animation-presets.js
  extensions/amp-story/0.1/animation.js
  extensions/amp-story/0.1/test/test-full-bleed-animations.js
Labels: cla: yes

#14576 Corrects comment text
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
Labels: cla: yes

#14586 Whitelist links in <pre> blocks
  build-system/tasks/check-links.js
Labels: cla: yes

#14589 Update lightbox placeholder icons to v3
  extensions/amp-lightbox-gallery/0.1/service/lightbox-placeholders.js
Labels: cla: yes

#14596 Toggle top bar on description overflow
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#14590 🏗 Prevent unnecessary use of allowConsoleError
  test/_init_tests.js
Labels: Category: Tooling, cla: yes

#14582 allow webcal uri scheme
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#14498 Clarify that <amp-img> should not use the `media` attribute
  builtins/amp-img.md
Labels: cla: yes

#14462 ✨Document-level infinite-scroll (#12945): Hide position fixed elements of nested pages.
  extensions/amp-document-recommendations/0.1/amp-document-recommendations.css
  extensions/amp-document-recommendations/0.1/amp-document-recommendations.js
Labels: cla: yes

#14603 Fix amp-bind tests and elementByTag()
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  gulpfile.js
  src/dom.js
Labels: cla: yes

#14565 Doc cleanup of a4a spec
  extensions/amp-a4a/amp-a4a-format.md
Labels: cla: yes

#14543 ✨ Doubleclick Fast Fetch: Add referrer macro
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-rtc.js
Labels: cla: yes

#14571 ♻️ Rename amp-document-recommendations to amp-next-page
  build-system/dep-check-config.js
  build-system/tasks/presubmit-checks.js
  examples/amp-next-page.amp.html
  extensions/amp-next-page/0.1/amp-next-page.css
  extensions/amp-next-page/0.1/amp-next-page.js
  extensions/amp-next-page/0.1/config.js
  extensions/amp-next-page/0.1/test/test-config.js
  extensions/amp-next-page/OWNERS.yaml
  extensions/amp-next-page/amp-next-page.md
  extensions/amp-next-page/validator-amp-next-page.protoascii
  gulpfile.js
  tools/experiments/experiments.js
Labels: cla: yes

#14100 Updating DoubleClick documentation
  ads/google/doubleclick.md
  extensions/amp-a4a/refresh.md
  extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
  extensions/amp-ad-network-doubleclick-impl/doubleclick-rtc.md
  extensions/amp-ad-network-doubleclick-impl/fluid.md
  extensions/amp-ad-network-doubleclick-impl/multi-size.md
  extensions/amp-ad-network-doubleclick-impl/refresh.md
  extensions/amp-ad-network-doubleclick-impl/render-on-idle.md
  extensions/amp-ad-network-doubleclick-impl/sra.md
Labels: cla: yes

#14384 ♻️✨Register common video actions and events
  extensions/amp-video-service/0.1/amp-video-service.js
  extensions/amp-video-service/0.1/test/test-amp-video-service.js
Labels: cla: yes

#14611 turn off font display swap
  build-system/global-configs/canary-config.json
Labels: cla: yes

#14501 Subscriptions: Viewer platform
  build-system/tasks/presubmit-checks.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#14588 ✅ Wrap tests in test-amp-mustache.js that expect a console error with `allowConsoleError`
  extensions/amp-mustache/0.1/test/test-amp-mustache.js
Labels: cla: yes

#14545 Add AMP loader to <amp-facebook-*>
  3p/facebook.js
  extensions/amp-facebook-comments/0.1/amp-facebook-comments.js
  extensions/amp-facebook-like/0.1/amp-facebook-like.js
  extensions/amp-facebook-page/0.1/amp-facebook-page.js
  extensions/amp-facebook/0.1/amp-facebook.js
Labels: cla: yes

#14598 Lightbox bugfixes
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#14615 🏗 On Travis, collapse the copious error logs printed after test runs
  build-system/tasks/runtime-test.js
Labels: Category: Tooling, cla: yes

#14617 📖 amp-geo documentation
  extensions/amp-geo/amp-geo.md
  spec/amp-var-substitutions.md
Labels: cla: yes

#14619 Add @jridgewell to bundlesize POC
  gulpfile.js
Labels: cla: yes

#14621 🏗 Separate error logs from different test runs on Travis
  build-system/tasks/runtime-test.js
Labels: Category: Tooling, cla: yes

#14618 Add `open` action to `<amp-lightbox-gallery>` update demo with video, youtube, and ads
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  test/manual/article-with-lightbox-2.0-gallery.amp.html
Labels: cla: yes

#14614 🚮 Remove experimental video docking
  css/amp.css
  src/service/video-manager-impl.js
  test/integration/test-video-players-helper.js
Labels: Category: Audio&Video, cla: yes

#14606 🐛 Respect CAN_SHOW_SYSTEM_LAYER_BUTTONS property on desktop
  extensions/amp-story/1.0/amp-story-desktop.css
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story-system-layer.js
Labels: cla: yes

#14424 Add code conformance rules for style property
  build-system/conformance-config.textproto
  extensions/amp-animation/0.1/web-animations.js
  extensions/amp-story/1.0/amp-story-grid-layer.js
  extensions/amp-story/1.0/page-scaling.js
  src/style.js
  test/functional/test-style.js
Labels: cla: yes

#14641 Doc update to amp-video allowing auto play video in A4A
  extensions/amp-a4a/amp-a4a-format.md
Labels: cla: yes

#14639 Fix SF bug & add feature to detect isAmp
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
Labels: cla: yes
