Repository ampproject/amphtml, pull requests merged in 2018-12, with the labels that each got.

#18910 ✨amp-consent v2: Fullscreen API Support & UX
  build-system/tasks/presubmit-checks.js
  extensions/amp-consent/0.1/amp-consent.css
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  test/manual/ampUserNotification-ampConsent.html
  test/manual/diy-consent.html
Labels: cla: yes

#19565 Unload and pagehide events come from window, not document
  examples/analytics-reportWhen.amp.html
  extensions/amp-analytics/0.1/events.js
  extensions/amp-analytics/0.1/test/test-events.js
Labels: Category: Analytics, cla: yes

#19559 🏗 Move the bundle-size check downwards
  build-system/pr-check.js
Labels: cla: yes

#19562 🏗 bundle-size requests to GitHub App should accept any 2xx status code
  build-system/tasks/bundle-size.js
Labels: cla: yes

#19577 -- videonow ad's urls fixed
  ads/videonow.js
Labels: cla: yes

#19525 amp-action-macro extension skeleton
  extensions/amp-action-macro/0.1/amp-action-macro.js
  extensions/amp-action-macro/0.1/test/test-amp-action-macro.js
  extensions/amp-action-macro/OWNERS.yaml
  extensions/amp-action-macro/amp-action-macro.md
  tools/experiments/experiments.js
Labels: cla: yes

#18680 Fix log sites
  build-system/eslint-rules/no-non-string-log-args.js
  extensions/amp-experiment/0.1/variant.js
Labels: cla: yes

#19490 Remove getServiceForDocDeprecated()
  ads/google/a4a/utils.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-animation/0.1/web-animations.js
  extensions/amp-skimlinks/0.1/link-rewriter/link-rewriter.js
  src/chunk.js
  src/impression.js
  src/inabox/inabox-viewport.js
  src/pull-to-refresh.js
  src/runtime.js
  src/service.js
  src/service/performance-impl.js
  src/services.js
  src/style-installer.js
Labels: cla: yes

#19591 fix amp-action-macro experiment name
  tools/experiments/experiments.js
Labels: cla: yes

#19496 Disallow ampdoc in Services.actionServiceForDoc()
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation.js
  extensions/amp-gwd-animation/0.1/test/test-amp-gwd-animation.js
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-story/0.1/amp-story-bookend.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-video-docking/0.1/amp-video-docking.js
  extensions/amp-video-service/0.1/amp-video-service.js
  src/service.js
  src/service/standard-actions-impl.js
  src/service/video-manager-impl.js
  src/services.js
  test/functional/test-service.js
  test/integration/test-video-manager.js
Labels: cla: yes

#19493 Remove Object.values polyfill in bind-expression.js
  extensions/amp-bind/0.1/bind-expression.js
Labels: cla: yes

#19572 📖 amp-ima-video: Add documentation for data-ad-label
  extensions/amp-ima-video/amp-ima-video.md
Labels: cla: yes

#19596 SwG release 0.1.22.40
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#19594 amp-addthis extension unit test fix
  extensions/amp-addthis/0.1/test/test-amp-addthis.js
Labels: cla: yes

#19551 [amp-list] allow templating for load-more elements load-more-button and load-more-end
  build-system/app.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/amp-list.md
  test/manual/amp-list/infinite-scroll-1.amp.html
Labels: cla: yes

#19597 build module safe scripts only when building --esm
  gulpfile.js
Labels: cla: yes

#19505 ✨ Add consentString support
  build-system/tasks/presubmit-checks.js
  examples/amp-consent-iframe.amp.html
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-info.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-info.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  test/manual/diy-consent.html
Labels: cla: yes

#19261 Amp SW prefetch outgoing links.
  extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js
  extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
Labels: cla: yes

#19608 Validator rollup
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: cla: yes

#19617 🐛🏗 Split gitBranchPoint to two function
  build-system/git.js
  build-system/tasks/bundle-size.js
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#19512 Disallow ampdoc in Services.bindForDocOrNull()
  extensions/amp-a4a/0.1/test/test-a4a-var-source.js
  src/service/url-replacements-impl.js
  src/services.js
Labels: cla: yes

#19441 Message Extraction: while removing assert methods as a preprocess step, add back in the type
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/index.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-boolean/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-boolean/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-element/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-number/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-number/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-string/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-string/output.js
  build-system/build.conf.js
  extensions/amp-pinterest/0.1/pinit-button.js
Labels: Category: Tooling, cla: yes

#19626 temporarily skip flakey amp-subscriptions test
  extensions/amp-subscriptions/0.1/test/test-dialog.js
Labels: cla: yes

#19304 ✨ analytics: Allow pings with totalVisibleTime=0 when spec has reportWhen
  examples/analytics-reportWhen.amp.html
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-analytics/0.1/test/test-visibility-model.js
  extensions/amp-analytics/0.1/visibility-manager.js
  extensions/amp-analytics/0.1/visibility-model.js
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#19621 🏗 Move the bundle-size check upwards
  build-system/pr-check.js
Labels: cla: yes

#19400 ✨Add FreeWheel ad network
  3p/integration.js
  ads/_config.js
  ads/freewheel.js
  ads/freewheel.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#19637 📖 Update amp-video-iframe docs
  extensions/amp-video-iframe/amp-video-iframe.md
Labels: cla: yes

#19506 Add new amp-analytics vendor: Permutive
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/permutive.js
Labels: cla: yes

#19632 🐛inabox: workaround to keep compiler from removing cross-domain check
  ads/inabox/inabox-messaging-host.js
Labels: cla: yes

#19643 Tweaking doc of `cookies` object
  extensions/amp-analytics/linker-id-receiving.md
Labels: cla: yes

#19663 turn off fixer for now
  .eslintrc
  build-system/eslint-rules/no-non-string-log-args.js
Labels: cla: yes

#19661 Update Sauce Connect to 4.5.2
  build-system/sauce_connect/start_sauce_connect.sh
Labels: cla: yes

#19669 Remove Mobile Safari 11 from tests
  build-system/tasks/runtime-test.js
Labels: cla: yes

#19641 Fix button positioning for load-more elements as not to partially cover last item in amp-list
  css/amp.css
  extensions/amp-list/0.1/amp-list.css
  extensions/amp-list/0.1/amp-list.js
  test/manual/amp-list/infinite-scroll-1.amp.html
Labels: cla: yes

#19581 Update no-module-exports eslint rule
  build-system/eslint-rules/no-module-exports.js
Labels: cla: yes

#19665 Skip amp video tests that are failing when running alone
  extensions/amp-video/0.1/test/test-amp-video.js
Labels: cla: yes

#18190 Allow forcing the Custom Elements V1 Polyfill
  src/polyfills.js
  src/polyfills/custom-elements.js
  src/service/extensions-impl.js
  src/web-components.js
  testing/describes.js
  testing/iframe.js
Labels: cla: yes

#19613 Teardown RequestBank after a test finish.
  build-system/amp4test.js
  test/integration/test-amp-analytics.js
  test/integration/test-amp-pixel.js
  test/integration/test-user-error-reporting.js
  testing/describes.js
  testing/test-helper.js
Labels: cla: yes

#19689 🐛 Amp subscriptions reset fixes.
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/platform-store.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-dialog.js
Labels: cla: yes

#19692 validator rollup
  extensions/amp-video-docking/0.1/test/validator-amp-video-docking-no-player.out
  extensions/amp-video-docking/validator-amp-video-docking.protoascii
  validator/engine/validator.js
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#19679 📖 Correctly format code blocks for `amp-action-macro`
  extensions/amp-action-macro/amp-action-macro.md
Labels: cla: yes

#19695 Fix test-linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
Labels: cla: yes

#19658 Disable headless mode, fix tests broken on Chrome 71
  build-system/pr-check.js
  build-system/tasks/karma.conf.js
  extensions/amp-bind/0.1/bind-events.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-list/0.1/test/integration/test-amp-list.js
  src/service/extensions-impl.js
  test/integration/test-amp-bind.js
Labels: cla: yes

#19698 Adding integration for AMPHTML ads rendered on AMP page (A4A)
  build-system/amp4test.js
  build-system/tasks/presubmit-checks.js
  test/integration/test-amp-ad-fake.js
  testing/test-helper.js
Labels: cla: yes

#19718 [amp-story] Stop stubbing querySelectorAll in tests 🐛
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: Category: AMP Story, cla: yes

#19582 Fix margins in amp-consent bookend component 🐛
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/bookend/bookend-component.js
Labels: cla: yes

#19660 Update bindings in server side rendered templates in amp-list
  examples/mustache-to-amp-view-host.amp.html
  examples/viewer.html
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#19725 [amp-story] Register localization service in system layer tests
  extensions/amp-story/1.0/test/test-amp-story-system-layer.js
Labels: Category: AMP Story, cla: yes

#19722 Skip tests failing on SL Chrome 71
  extensions/amp-form/0.1/test/integration/test-integration-form-verifiers.js
  extensions/amp-form/0.1/test/integration/test-integration-form.js
  test/integration/test-amp-bind.js
  test/integration/test-amp-pixel.js
Labels: cla: yes

#19667 ♻️Don't encode expandStringSync
  src/service/url-replacements-impl.js
  test/functional/test-url-replacements.js
Labels: cla: yes

#19709 Add integration test for CLIENT_ID in amp-analytics
  test/integration/test-amp-analytics.js
Labels: cla: yes

#19489 ✨ add ads: baidu
  3p/integration.js
  ads/_config.js
  ads/baidu.js
  ads/baidu.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
  validator/testdata/feature_tests/ads.html
  validator/testdata/feature_tests/ads.out
Labels: cla: yes

#19674 Add integration tests for <amp-analytics type=googleanalytics>
  test/integration/test-amp-analytics.js
  test/integration/test-amp-bind.js
Labels: cla: yes

#19668 Document the need for integration test for 3rd party integration
  3p/README.md
  ads/README.md
  extensions/amp-analytics/integrating-analytics.md
Labels: cla: yes

#19666 [amp-story] Add totalPages to AmpStoryStoreService
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#19545 Delay and delegate the subscriptions platform selection call.
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  src/utils/story.js
Labels: cla: yes

#19696 Fallback "Play video" message when the story video failed to play.
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/localization.js
Labels: cla: yes

#19680 🐛Allow amp-analytics to layout correctly in FIE
  css/amp.css
  extensions/amp-analytics/0.1/amp-analytics.css
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
  test/manual/amp-analytics-in-fie.amp.html
Labels: cla: yes

#19638 ✨19607 Additonal Unit Tests for amp-consent-v2 enterFullscreen()
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
Labels: cla: yes

#19681 🏗Moved 3p bootstrap frame definitions into `build-system/config.js`
  build-system/config.js
  gulpfile.js
Labels: cla: yes

#19733 Fix paywall display conditions
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/platform-store.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-platform-store.js
Labels: cla: yes

#19346 Add script tag support for enclosing a template
  examples/amp-list.amp.html
  examples/comments.example.json
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-mustache/0.1/amp-mustache.js
  extensions/amp-mustache/0.1/test/test-amp-mustache.js
  extensions/amp-mustache/0.2/amp-mustache.js
  extensions/amp-mustache/0.2/test/test-amp-mustache.js
  src/service/template-impl.js
  test/functional/test-template.js
Labels: cla: yes

#19750 ✅ Disable flaky CustomElement test
  test/functional/test-custom-element.js
Labels: cla: yes

#19630 Add more browsers to integration tests
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-bodymovin-animation/0.1/test/integration/test-amp-bodymovin-animation.js
  extensions/amp-date-picker/0.1/test/integration/test-integration-amp-date-picker-actions.js
  extensions/amp-date-picker/0.1/test/integration/test-integration-dates-attributes.js
  extensions/amp-form/0.1/test/integration/test-integration-form-verifiers.js
  extensions/amp-form/0.1/test/integration/test-integration-form.js
  extensions/amp-fx-collection/0.1/test/integration/test-amp-fx-fade-in-scroll.js
  extensions/amp-fx-collection/0.1/test/integration/test-amp-fx-fade-in.js
  extensions/amp-fx-collection/0.1/test/integration/test-amp-fx-parallax.js
  extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
  extensions/amp-inputmask/0.1/test/integration/test-integration-amp-inputmask.js
  extensions/amp-list/0.1/test/integration/test-amp-list.js
  extensions/amp-pan-zoom/0.1/test/integration/test-amp-pan-zoom.js
  extensions/amp-viewer-integration/0.1/test/integration/test-amp-viewer-integration.js
  test/_init_tests.js
  test/integration/test-3p-frame.js
  test/integration/test-amp-bind.js
  test/integration/test-amp-carousel.js
  test/integration/test-errors.js
  test/integration/test-position-observer.js
  test/integration/test-video-manager.js
  test/integration/test-video-players-helper.js
  test/integration/test-visibility-states.js
Labels: cla: yes

#19609 ✨ amp-analytics Nested Value Template Expansion
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/amp-analytics.md
  test/integration/test-amp-analytics.js
Labels: cla: yes

#19649 Keep the highlighted text color consistent with Android Chrome.
  extensions/amp-viewer-integration/0.1/highlight-handler.js
  extensions/amp-viewer-integration/0.1/test/test-highlight-handler.js
Labels: cla: yes

#19588 Remove dead links in amp-access-analytics doc
  extensions/amp-access/amp-access-analytics.md
Labels: cla: yes

#19691 Fixing method call for esm build
  build-system/single-pass.js
Labels: cla: yes

#19756 Update docs to replace doubleclick with Google Ad Manager
  ads/google/a4a/docs/Network-Impl-Guide.md
  ads/google/doubleclick.md
  extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
  extensions/amp-ad-network-doubleclick-impl/amp-consent.md
  extensions/amp-ad-network-doubleclick-impl/doubleclick-rtc.md
  extensions/amp-ad-network-doubleclick-impl/fluid.md
  extensions/amp-ad-network-doubleclick-impl/multi-size.md
  extensions/amp-ad-network-doubleclick-impl/refresh.md
  extensions/amp-ad-network-doubleclick-impl/render-on-idle.md
  extensions/amp-ad-network-doubleclick-impl/safeframe.md
  extensions/amp-ad-network-doubleclick-impl/single-page-ad.md
  extensions/amp-ad-network-doubleclick-impl/sra.md
Labels: cla: yes

#19726 🏗 Stop printing a console error summary at the end of full test runs
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test.js
Labels: Category: Tooling, cla: yes

#19445 [WIP] amp-date-display
  bundles.config.js
  examples/amp-date-display.amp.html
  extensions/amp-date-display/0.1/amp-date-display.js
  extensions/amp-date-display/0.1/test/test-amp-date-display.js
  extensions/amp-date-display/0.1/test/validator-amp-date-display.html
  extensions/amp-date-display/0.1/test/validator-amp-date-display.out
  extensions/amp-date-display/OWNERS.yaml
  extensions/amp-date-display/amp-date-display.md
  extensions/amp-date-display/validator-amp-date-display.protoascii
  tools/experiments/experiments.js
Labels: PR use: Work in Progress, cla: yes

#19760 Disable two flaky CustomElement tests
  test/functional/test-custom-element.js
Labels: cla: yes

#19746 📖 Edit embed-zen documentation
  ads/zen.md
Labels: cla: yes

#19602 Disallow passing ampdoc to Services.urlForDoc()
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-audio/0.1/amp-audio.js
  extensions/amp-dynamic-css-classes/0.1/amp-dynamic-css-classes.js
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  src/mediasession-helper.js
  src/service/navigation.js
  src/service/video-manager-impl.js
  src/services.js
  test/functional/test-mediasession-helper.js
Labels: cla: yes

#19770 Add failure demos, fix race condition for not showing load-failed element
  build-system/app.js
  extensions/amp-list/0.1/amp-list.js
  test/manual/amp-list/infinite-scroll-fail.amp.html
Labels: cla: yes

#19556 ✨Added new partner for analytics: Retargetly
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/retargetly.js
Labels: cla: yes

#19776 SwG release 0.1.22.41
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#19704 🚀 HTML Template Tag Transform to eliminate poor transpilation issues
  build-system/babel-plugins/babel-plugin-transform-html-template/index.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/direct/input.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/direct/options.json
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/direct/output.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/indirect/input.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/indirect/options.json
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/indirect/output.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/invalid/input.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/invalid/options.json
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/invalid/output.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/other-template-literals/input.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/other-template-literals/options.json
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/other-template-literals/output.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/index.js
  build-system/build.conf.js
  package.json
  test/integration/test-amp-bind.js
  yarn.lock
Labels: cla: yes

#19655 [amp-story] Refactor pagination buttons to use store ♻️
  examples/visual-tests/amp-story/amp-story-pagination-buttons.html
  examples/visual-tests/amp-story/amp-story-pagination-buttons.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/pagination-buttons.js
  test/visual-diff/visual-tests
Labels: cla: yes

#19425 🐛 [amp-analytics] Pass the canonical url on every Parse.ly Analytics pageview request
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/parsely.js
Labels: cla: yes

#19780 Add SwG team to amp-subscriptions and amp-subscriptions-google owners
  extensions/amp-subscriptions-google/OWNERS.yaml
  extensions/amp-subscriptions/OWNERS.yaml
Labels: cla: yes

#19782 ✅🏗 Reduce SauceLabs batch size and remove flaky browsers to unblock master
  build-system/tasks/runtime-test.js
  extensions/amp-form/0.1/test/integration/test-integration-form.js
  test/_init_tests.js
  test/integration/test-amp-bind.js
  test/integration/test-errors.js
  test/integration/test-toggle-display.js
  test/integration/test-user-error-reporting.js
  test/integration/test-visibility-states.js
Labels: cla: yes

#19794 Validator rollup
  extensions/amp-date-display/0.1/test/validator-amp-date-display.html
  extensions/amp-date-display/0.1/test/validator-amp-date-display.out
  extensions/amp-date-display/validator-amp-date-display.protoascii
  validator/testdata/feature_tests/ads.out
  validator/validator-main.protoascii
Labels: cla: yes

#19796 ✅ Skip mutliple flaky tests
  extensions/amp-accordion/0.1/test/integration/test-amp-accordion.js
  extensions/amp-fx-collection/0.1/test/integration/test-amp-fx-fade-in-scroll.js
  test/integration/test-amp-carousel.js
Labels: cla: yes

#19732 Adds a default title/label/assignee for the cherry pick request templates
  .github/ISSUE_TEMPLATE/cherry_pick_template.md
Labels: cla: yes

#19646 Publisher opt in into a story landscape fullbleed desktop + mobile experience.
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/amp-story-desktop-panels.css
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/amp-story-tooltip.js
  extensions/amp-story/1.0/amp-story-viewport-warning-layer.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/pagination-buttons.css
  extensions/amp-story/1.0/test/test-amp-story-store-service.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#19785 🐛 Patch web-animations-js polyfill to avoid writing to readonly property
  build-system/tasks/update-packages.js
Labels: cla: yes

#19805 🐛 Fix FixedLayer attribute sync for amp-bind
  src/service/fixed-layer.js
  test/functional/test-fixed-layer.js
Labels: cla: yes

#19784 🐛Fix bug with fading in lightbox after image transition.
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#19809 ✅ Add more tests to fixed-layer attr sync
  test/functional/test-fixed-layer.js
Labels: cla: yes

#19639 Fix amp-addthis single pass bugs
  extensions/amp-addthis/0.1/addthis-utils/lojson.js
  extensions/amp-addthis/0.1/amp-addthis.js
  extensions/amp-addthis/0.1/config-manager.js
  extensions/amp-addthis/0.1/post-message-dispatcher.js
Labels: cla: yes

#19797 Add TODOs for skipped tests
  extensions/amp-accordion/0.1/test/integration/test-amp-accordion.js
  extensions/amp-form/0.1/test/integration/test-integration-form.js
  extensions/amp-fx-collection/0.1/test/integration/test-amp-fx-fade-in-scroll.js
  test/integration/test-amp-carousel.js
  test/integration/test-errors.js
  test/integration/test-toggle-display.js
  test/integration/test-user-error-reporting.js
  test/integration/test-visibility-states.js
Labels: cla: yes

#19807 Creates separate bug/feature templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/cherry_pick_template.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes

#19824 🐛Fix amp-form caching submit service reference before it's registered
  extensions/amp-form/0.1/amp-form.js
Labels: cla: yes

#19772 [amp-list-load-more] Fix bug where existing items are getting appended again
  extensions/amp-list/0.1/amp-list.js
Labels: cla: yes

#19827 🐛 Fix non-inclusive between check for min and max
  examples/date-picker.amp.html
  extensions/amp-date-picker/0.1/date-picker-common.js
Labels: cla: yes

#19832 Replace test server port from 31862 to 8081 for better proxy support in SauceLabs
  build-system/tasks/runtime-test.js
  extensions/amp-form/0.1/test/integration/test-integration-form-verifiers.js
  extensions/amp-form/0.1/test/integration/test-integration-form.js
  extensions/amp-inputmask/0.1/test/integration/test-integration-amp-inputmask.js
  test/fixtures/bind-form.html
  test/functional/test-xhr.js
Labels: cla: yes

#19703 🖍 Added two default elements for amp-list-load-more
  extensions/amp-list/0.1/amp-list.css
  extensions/amp-list/0.1/amp-list.js
  test/manual/amp-list/infinite-scroll-1.amp.html
Labels: cla: yes

#19846 Fix off-by-one in freeze dates
  contributing/release-schedule.md
Labels: cla: yes

#19843 ✅ Restore tests disabled on SauceLabs before #19832
  extensions/amp-accordion/0.1/test/integration/test-amp-accordion.js
  extensions/amp-form/0.1/test/integration/test-integration-form.js
  extensions/amp-fx-collection/0.1/test/integration/test-amp-fx-fade-in-scroll.js
  test/integration/test-amp-bind.js
  test/integration/test-amp-carousel.js
  test/integration/test-errors.js
  test/integration/test-toggle-display.js
  test/integration/test-user-error-reporting.js
  test/integration/test-visibility-states.js
Labels: cla: yes

#19830 🐛Update fixed layer after toggle display
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
Labels: cla: yes

#19855 Update amp-consent owner
  extensions/amp-consent/OWNERS.yaml
Labels: cla: yes

#19834 🐛Fix wrong carousel slide being shown when closing lightbox.
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#19735 🚀🐛 Make video docking completely scroll-triggered
  examples/article-with-docked-video.html
  extensions/amp-video-docking/0.1/amp-video-docking.js
  extensions/amp-video-docking/0.1/controls.js
  extensions/amp-video-docking/0.1/test/test-amp-video-docking.js
Labels: cla: yes

#19854 ✨maximum-nights attribute on amp-date-picker
  examples/date-picker.amp.html
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/date-range-picker.js
  extensions/amp-date-picker/0.1/test/integration/test-integration-maximum-nights.js
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.html
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out
  extensions/amp-date-picker/0.1/wrappers/maximum-nights.js
  extensions/amp-date-picker/amp-date-picker.md
  extensions/amp-date-picker/validator-amp-date-picker.protoascii
Labels: cla: yes

#19848 Removes code that forces fixed layout on multi-size slots.
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/multi-size.md
Labels: cla: yes

#19851 ✅amp-facebook: tests for sandboxing and remove exception for `amp-embedly-card`
  extensions/amp-facebook/0.1/test/test-amp-facebook.js
  src/3p-frame.js
Labels: cla: yes

#19815 Add DOMPurify externs
  build-system/dompurify.extern.js
  build-system/tasks/compile.js
  src/purifier.js
Labels: cla: yes

#19871 add fb-me and wh protocols for anchor and social-share
  extensions/amp-social-share/validator-amp-social-share.protoascii
  validator/validator-main.protoascii
Labels: cla: yes

#18000 📖 Fixes formatting and adds links to MDN on amp-animation supported CSS properties.
  extensions/amp-animation/amp-animation.md
Labels: cla: yes

#19858 Remove i-amphtml-element class on forced disconnect
  src/custom-element.js
Labels: cla: yes

#19730 Disallow passing ampdoc to FIE service getters
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/test/test-vendors.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation.js
  extensions/amp-gwd-animation/0.1/test/test-amp-gwd-animation.js
  src/element-service.js
  src/service.js
  src/services.js
  test/functional/test-service.js
  test/functional/test-standard-actions.js
  test/functional/test-url-replacements.js
Labels: cla: yes

#19812 🚀 Hoist templates and ensure duplicates are not added to bundle
  build-system/babel-plugins/babel-plugin-transform-html-template/index.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/direct/input.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/direct/output.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/indirect/output.js
Labels: cla: yes

#19853 Fix flaky tests in test-custom-element.js
  test/functional/test-custom-element.js
Labels: cla: yes

#19877 🚮Remove `amp-story` codepath for page-scaling experiment
  extensions/amp-story/0.1/amp-story-page.js
  extensions/amp-story/0.1/page-scaling.js
Labels: cla: yes

#19889 🏗🐛 Remove `refreshKarmaWdCache`, since `karma-sauce-launcher` no longer depends on `wd`
  build-system/tasks/runtime-test.js
Labels: Category: Tooling, cla: yes

#19738 Remove wait for ini-load when layout a4a
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
Labels: cla: yes

#19860 ♻️amp-consent: Refactored consent ui api to match consent response
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  test/manual/diy-consent.html
Labels: cla: yes

#19849 Story supports-landscape attribute.
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#19872 Story supports-landscape attribute validation.
  extensions/amp-story/1.0/test/validator-amp-story-supports-landscape.html
  extensions/amp-story/1.0/test/validator-amp-story-supports-landscape.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#19894 ✨ Bindable [src] for <amp-video-iframe>
  extensions/amp-video-iframe/0.1/amp-video-iframe.js
  extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
  extensions/amp-video-iframe/validator-amp-video-iframe.protoascii
  test/fixtures/served/video-iframe-2.html
Labels: cla: yes

#18700 ✨ Implement new amp-access-poool extension
  bundles.config.js
  examples/article-access-poool.amp.html
  extensions/amp-access-poool/0.1/amp-access-poool.js
  extensions/amp-access-poool/0.1/poool-impl.js
  extensions/amp-access-poool/0.1/test/test-amp-access-poool.js
  extensions/amp-access-poool/amp-access-poool.md
  extensions/amp-access-poool/validator-amp-access-poool.protoascii
Labels: cla: yes

#19874 Run integration tests on SauceLabs with beta browser versions, and make these beta versions non-failing
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test.js
Labels: cla: yes

#19927 🐛 Avoid showing mask characters until the user reaches them
  extensions/amp-inputmask/0.1/mask-impl.js
Labels: cla: yes

#19926 Skip flaky tests on Chrome 71 + Windows 10
  extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
  src/service/platform-impl.js
  test/_init_tests.js
  test/integration/test-amp-carousel.js
  test/integration/test-errors.js
  test/integration/test-user-error-reporting.js
  test/integration/test-video-players-helper.js
  test/integration/test-visibility-states.js
Labels: cla: yes

#19920 Mark `babel-plugins` files as affecting the runtime in the `gulp pr-check` task
  build-system/pr-check.js
Labels: cla: yes

#19771 Refactor EmbeddableService
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
  src/service.js
  src/service/action-impl.js
  src/service/extensions-impl.js
  src/service/navigation.js
  src/service/standard-actions-impl.js
  src/service/timer-impl.js
  src/service/url-impl.js
  src/services.js
  test/functional/test-action.js
  test/functional/test-extensions.js
  test/functional/test-service.js
  test/functional/test-standard-actions.js
Labels: cla: yes

#19838 fix a4a intersection observer
  extensions/amp-a4a/0.1/refresh-manager.js
Labels: cla: yes

#19881 [amp-list-load-more] bugfixes, code cleanup, fix demos
  extensions/amp-list/0.1/amp-list.js
  test/manual/amp-list/infinite-scroll-1.amp.html
  test/manual/amp-list/infinite-scroll-2.amp.html
Labels: cla: yes

#19707 Add integration test for amp-analytics various triggers.
  test/integration/test-amp-analytics.js
  testing/test-helper.js
Labels: cla: yes

#19928 Fix copyright date on amp-access-poool files
  extensions/amp-access-poool/0.1/amp-access-poool.js
  extensions/amp-access-poool/0.1/test/test-amp-access-poool.js
  extensions/amp-access-poool/validator-amp-access-poool.protoascii
Labels: cla: yes

#19925 🏗 Upgrade RobinHerbots/inputmask to 4.0.4
  third_party/inputmask/README.amp
  third_party/inputmask/inputmask.dependencyLib.js
  third_party/inputmask/inputmask.js
  third_party/inputmask/patches/0000-remove-umd-wrapper.patch
  third_party/inputmask/patches/0001-window-element.patch
  third_party/inputmask/patches/0002-use-real-event.patch
  third_party/inputmask/patches/0003-fix-unpatched-unmask.patch
  third_party/inputmask/patches/0004-fix-unpatched-hover.patch
  third_party/inputmask/patches/0005-cleanup-whitespace.patch
  third_party/inputmask/patches/0006-wildcard-support.patch
Labels: cla: yes

#19946 [amp-list] resize amp-list on viewport resize experiment
  extensions/amp-list/0.1/amp-list.js
  tools/experiments/experiments.js
Labels: cla: yes

#19811 Fix CSS transitions on sidebar
  extensions/amp-sidebar/0.1/amp-sidebar.js
Labels: cla: yes

#19942 Remove all references to loadMoreLoadingOverlay
  css/amp.css
  extensions/amp-list/0.1/amp-list.js
Labels: cla: yes

#19947 Import amp-analytics css
  bundles.config.js
  extensions/amp-analytics/0.1/amp-analytics.js
Labels: cla: yes

#19885 ♻️ amp-viqeo-player: placeholder and refactoring
  3p/viqeoplayer.js
  examples/viqeo.amp.html
  extensions/amp-viqeo-player/0.1/amp-viqeo-player.js
  extensions/amp-viqeo-player/0.1/test/test-amp-viqeo-player.js
Labels: cla: yes

#19345 Add visual test for AMP Inabox with GPT
  examples/visual-tests/amp-inabox/amp-inabox-gpt.html
  test/visual-diff/visual-tests
Labels: cla: yes

#18440 ✨ Recognize details element with open/[open] attributes and summary child element
  examples/bind/details.amp.html
  extensions/amp-bind/0.1/bind-validator.js
  extensions/amp-bind/amp-bind.md
  validator/validator-main.protoascii
Labels: cla: yes

#19900 🐛Story ads: show one page sooner on desktop
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
Labels: cla: yes

#19929 📖 Update buildcop.md with beta browsers instructions
  contributing/buildcop.md
Labels: cla: yes

#19965 Validator roll up
  extensions/amp-bind/validator-amp-bind.protoascii
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out
  extensions/amp-list/validator-amp-list.protoascii
  extensions/amp-mustache/0.1/test/validator-amp-mustache.html
  extensions/amp-mustache/0.1/test/validator-amp-mustache.out
  extensions/amp-mustache/0.2/test/validator-amp-mustache.html
  extensions/amp-mustache/0.2/test/validator-amp-mustache.out
  extensions/amp-mustache/validator-amp-mustache.protoascii
  extensions/amp-video/validator-amp-video.protoascii
  extensions/amp-yotpo/validator-amp-yotpo.protoascii
  validator/engine/validator_test.js
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#19841 ✨amp-consent: Added a default loading placeholder for the consent UI
  extensions/amp-consent/0.1/amp-consent.css
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
Labels: cla: yes

#19953 📖Fix the link to the HTML attributes section
  spec/amp-var-substitutions.md
Labels: cla: yes

#19862 🐛 A4A: Improve google matched content responsive ad logic.
  ads/_config.js
  ads/google/test/test-utils.js
  ads/google/utils.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
Labels: Category: Ads, cla: yes

#19954 🏗 Refactor branch point logic and print a change summary before running PR checks
  build-system/git.js
  build-system/pr-check.js
  build-system/tasks/bundle-size.js
  build-system/tasks/visual-diff/index.js
Labels: Category: Tooling, cla: yes

#19844 ✅Enable skipped singlepass tests
  extensions/amp-analytics/0.1/transport-serializer.js
  src/service/url-replacements-impl.js
  test/integration/test-amp-ad-fake.js
  test/integration/test-amp-analytics.js
  test/integration/test-amp-pixel.js
  test/integration/test-user-error-reporting.js
Labels: cla: yes

#19943 Better A4A/FIE testing, add FIE services regression test
  build-system/amp4test.js
  test/integration/test-amp-ad-fake.js
  test/integration/test-amp-analytics.js
  test/integration/test-amp-pixel.js
  test/integration/test-user-error-reporting.js
  testing/test-helper.js
Labels: cla: yes

#19984 🏗 Limit commit log size in Travis logs and print branch point info
  build-system/git.js
  build-system/pr-check.js
Labels: Category: Tooling, cla: yes

#19628 Allow us to locally run tests on Chrome Canary.
  build-system/tasks/runtime-test.js
Labels: cla: yes
