Repository ampproject/amphtml, pull requests merged in 2018-02, with the labels that each got.

#13397 🏗️ Switch from phantomjs to (headless) chrome for visual tests
  .travis.yml
  build-system/pr-check.js
  build-system/tasks/visual-diff.js
  build-system/tasks/visual-diff.rb
  contributing/DEVELOPING.md
Labels: Category: Tooling, cla: yes

#13396 🏗️ Use (headless) chrome addon on Travis
  .travis.yml
Labels: Category: Tooling, cla: yes

#13404 🏗️✅ Re-enable old visual diff tests now that we're using chrome
  test/visual-diff/visual-tests.json
Labels: Related to: Flaky Tests, cla: yes

#13405 amp-lightbox-gallery: install component if extension is loaded
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#13305 Amp subscriptions
  build-system/app.js
  examples/amp-subscription.html
  extensions/amp-subscriptions/0.1/amp-subscriptions.css
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  gulpfile.js
Labels: cla: yes

#13400 Fixes copy link to clipboard for iOS
  extensions/amp-story/0.1/share.js
  src/clipboard.js
Labels: cla: yes

#13408 Add documentation for Percy access
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
Labels: Related to: Documentation, cla: yes

#13411 🏗️ Skip amp-by-example visual tests for PRs
  build-system/tasks/visual-diff.rb
Labels: cla: yes

#13410 🏗️ Don't pre-launch headless chrome on Travis
  .travis.yml
Labels: Category: Tooling, cla: yes

#13401 Fixes comments to point at a GH issue.
  extensions/amp-story/0.1/test/test-amp-story.js
Labels: cla: yes

#12163 Add amp-ad support for AppVador
  3p/integration.js
  ads/_config.js
  ads/appvador.js
  ads/appvador.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#13412 Spec update: Inline templates in amp-story-auto-ads
  extensions/amp-story/ad-serving-integration.md
  extensions/amp-story/amp-story-auto-ads.md
Labels: cla: yes

#13416 🏗️ Temporarily skip gulp visual-diff --verify
  build-system/pr-check.js
Labels: Related to: Flaky Tests, cla: yes

#13418 fix linter appvador.js
  ads/appvador.js
Labels: cla: yes

#13406 Allow amp-mustache in a4a
  extensions/amp-a4a/amp-a4a-format.md
  extensions/amp-mustache/validator-amp-mustache.protoascii
  validator/engine/validator_test.js
  validator/testdata/amp4ads_feature_tests/extensions.out
Labels: cla: yes

#13390 <amp-facebook-*> clean up assignment of dataLocale_ private variable
  extensions/amp-facebook-comments/0.1/amp-facebook-comments.js
  extensions/amp-facebook-like/0.1/amp-facebook-like.js
  extensions/amp-facebook/0.1/amp-facebook.js
Labels: cla: yes

#13381 <amp-ad type=custom>: allow defining template via the "template" attribute
  extensions/amp-ad/0.1/test/validator-amp-ad.html
  extensions/amp-ad/0.1/test/validator-amp-ad.out
  extensions/amp-ad/validator-amp-ad.protoascii
Labels: cla: yes

#13425 ✅ Disable visual tests for pages with dynamic content
  test/visual-diff/visual-tests.js
Labels: Related to: Flaky Tests, cla: yes

#13438 Add whitelist signup docs to amp-story.md
  extensions/amp-story/amp-story.md
Labels: cla: yes

#13440 fix amp-image-lightbox activation regression, update invocation source to caller
  extensions/amp-image-lightbox/0.1/amp-image-lightbox.js
  extensions/amp-image-lightbox/0.1/test/test-amp-image-lightbox.js
Labels: P0: Drop Everything, Type: Bug, cla: yes

#13441 :recycle: :building_construction: Move cookie/getCookie/setCookie restrictions to conformance-config.textproto
  build-system/conformance-config.textproto
  build-system/tasks/presubmit-checks.js
Labels: cla: yes

#13445 ✅ Fix desktop CSS width for visual diff tests
  build-system/tasks/visual-diff.rb
Labels: Related to: Flaky Tests, cla: yes

#12620 -- videonow ad
  3p/integration.js
  ads/_config.js
  ads/videonow.js
  ads/videonow.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#13424 fix-tests: expect is not assert
  ads/google/a4a/test/test-utils.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adzerk-impl/0.1/test/test-amp-ad-network-adzerk-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-ad/0.1/test/test-concurrent-load.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
  extensions/amp-video/0.1/test/test-amp-video.js
  test/functional/test-ads-config.js
  test/functional/test-custom-element-registry.js
  test/functional/test-custom-element.js
  test/functional/test-iframe-helper.js
  test/functional/test-json.js
  test/functional/test-xhr.js
  validator/engine/validator_test.js
Labels: cla: yes

#13426 🏗️ Add an eslint rule to prevent misuse of expect
  .eslintrc
  build-system/tasks/lint.js
  package.json
  yarn.lock
Labels: Category: Tooling, cla: yes

#13464 🏗️ Run lint checks on build-system/eslint-rules
  build-system/config.js
  build-system/eslint-rules/dict-string-keys.js
  build-system/eslint-rules/enforce-private-props.js
  build-system/eslint-rules/no-array-destructuring.js
  build-system/eslint-rules/no-es2015-number-props.js
  build-system/eslint-rules/no-export-side-effect.js
  build-system/eslint-rules/no-for-of-statement.js
  build-system/eslint-rules/no-global.js
  build-system/eslint-rules/no-spread.js
  build-system/eslint-rules/todo-format.js
Labels: Category: Tooling, cla: yes

#13459 🏗️ Don't install greenkeeper-lockfile on Travis
  .travis.yml
  package.json
  yarn.lock
Labels: Category: Tooling, cla: yes

#13460 🏗️ Add a config file for LGTM static analysis
  .lgtm.yml
Labels: Category: Tooling, cla: yes

#13453 🏗️ Remove chalk and replace it with ansi-colors
  build-system/tasks/check-links.js
  package.json
  yarn.lock
Labels: Category: Tooling, cla: yes

#13469 Doubleclick FF: launch exp for render on idle
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#13466 Add links to other story resources
  extensions/amp-story/amp-story.md
Labels: cla: yes

#13434 Change RTC macros to use AsyncResolver, add adCid macro, and count time
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-rtc.js
  extensions/amp-ad-network-doubleclick-impl/doubleclick-rtc.md
  src/ad-cid.js
  src/service/variable-source.js
Labels: cla: yes

#13368 Add test to enforce that RTC_VENDORS can not have any keys with capital letters
  extensions/amp-a4a/0.1/test/test-callout-vendors.js
Labels: cla: yes

#13449 🏗️ Scoped Query Selector: linting and audit
  .eslintrc
  ads/.eslintrc
  build-system/eslint-rules/query-selector.js
  build-system/tasks/presubmit-checks.js
  builtins/amp-img.js
  builtins/amp-pixel.js
  extensions/amp-access/0.1/amp-access-server-jwt.js
  extensions/amp-access/0.1/amp-access-server.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-story/0.1/amp-story-grid-layer.js
  extensions/amp-story/0.1/amp-story-page.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/animation.js
  extensions/amp-story/0.1/page-advancement.js
  extensions/amp-story/0.1/page-element.js
  extensions/amp-story/0.1/page-scaling.js
  extensions/amp-story/0.1/progress-bar.js
  extensions/amp-story/0.1/share.js
  extensions/amp-story/0.1/sources.js
  extensions/amp-web-push/0.1/amp-web-push-config.js
  extensions/amp-web-push/0.1/amp-web-push-permission-dialog.js
  extensions/amp-web-push/0.1/web-push-service.js
  src/dom.js
  src/font-stylesheet-timeout.js
  src/service/document-click.js
  src/service/video-manager-impl.js
  src/shadow-embed.js
  test/functional/test-dom.js
  third_party/css-escape/README.amp
  third_party/css-escape/css-escape.js
Labels: cla: yes

#13428 Amp subscriptions improvements
  examples/amp-subscription.html
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement-store.js
  extensions/amp-subscriptions/0.1/entitlements.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-entitlement-store.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Labels: cla: yes

#13151 Use valid json example in amp-story.md
  extensions/amp-story/amp-story.md
Labels: cla: yes

#13413 Make the html sanitizer allow the rel attribute on <a> tags
  src/sanitizer.js
  test/functional/test-sanitizer.js
Labels: cla: yes

#13474 🏗️ Move build-system/eslint-rules into a plugin
  .eslintrc
  ads/.eslintrc
  build-system/app.js
  build-system/eslint-rules/index.js
  build-system/eslint-rules/package.json
  build-system/tasks/lint.js
  package.json
  src/.eslintrc
  yarn.lock
Labels: Category: Tooling, cla: yes

#13483 🏗️ Enable headless mode for gulp test
  build-system/pr-check.js
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test.js
Labels: Category: Tooling, cla: yes

#13475 Validator Updates
  extensions/amp-anim/validator-amp-anim.protoascii
  extensions/amp-bind/validator-amp-bind.protoascii
  extensions/amp-image-lightbox/validator-amp-image-lightbox.protoascii
  extensions/amp-lightbox/validator-amp-lightbox.protoascii
  extensions/amp-list/validator-amp-list.protoascii
  extensions/amp-mustache/validator-amp-mustache.protoascii
  extensions/amp-selector/validator-amp-selector.protoascii
  extensions/amp-sidebar/validator-amp-sidebar.protoascii
  extensions/amp-timeago/validator-amp-timeago.protoascii
  validator/build.py
  validator/engine/json-testutil.js
  validator/engine/keyframes-parse-css.js
  validator/engine/parse-css.js
  validator/engine/parse-css_test.js
  validator/engine/tokenize-css.js
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/nodejs/index.js
  validator/testdata/amp4ads_feature_tests/extensions.out
  validator/validator-main.protoascii
  validator/validator.proto
  validator/validator_gen_js.py
Labels: cla: yes

#13501 🏗️ Fix / skip some amp-web-push tests that fail with headless chrome
  extensions/amp-web-push/0.1/test/test-web-push-permission-dialog.js
  extensions/amp-web-push/0.1/test/test-web-push-service.js
Labels: Related to: Flaky Tests, cla: yes

#13479 Subscriptions renderer
  css/amp.css
  extensions/amp-subscriptions/0.1/amp-subscriptions.css
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/renderer.js
  extensions/amp-subscriptions/0.1/test/test-renderer.js
Labels: cla: yes

#12593 Test, add example, and document referenced templates in a form's submit-[success|error]
  examples/forms.amp.html
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-form/amp-form.md
  src/service/template-impl.js
  test/functional/test-template.js
Labels: Category: Validator, cla: yes

#13355 Add Prebid-AppNexus as a vendor to RTC config
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#13495 Improving/cleaning up docs for lightbox-related components
  extensions/amp-image-lightbox/amp-image-lightbox.md
  extensions/amp-lightbox-gallery/amp-lightbox-gallery.md
  extensions/amp-lightbox/amp-lightbox.md
Labels: cla: yes

#13364 Add expand-single-section attribute to <amp-accordion>.
  examples/accordion.amp.html
  extensions/amp-accordion/0.1/amp-accordion.js
  extensions/amp-accordion/0.1/test/test-amp-accordion.js
  extensions/amp-accordion/amp-accordion.md
  extensions/amp-accordion/validator-amp-accordion.protoascii
Labels: cla: yes

#13517 Import subscriptions APIs
  build-system/app.js
  build-system/dep-check-config.js
  build-system/tasks/compile.js
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement-store.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-entitlement-store.js
  third_party/subscriptions-project/LICENSE
  third_party/subscriptions-project/README.amp
  third_party/subscriptions-project/apis.js
  third_party/subscriptions-project/config.js
Labels: cla: yes

#13099 Add Umeng+ analytics config
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#13458 Add integration test for amp-image-lightbox
  extensions/amp-image-lightbox/0.1/test/integration/test-amp-image-lightbox.js
Labels: cla: yes

#13392 Refactor amp-story progress bar to use page-ids
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/progress-bar.js
  extensions/amp-story/0.1/system-layer.js
  extensions/amp-story/0.1/test/test-system-layer.js
Labels: cla: yes

#13493 Rename AMP-to-AMP linking message from a2a to a2aNavigate
  examples/viewer-iframe-poll.html
  examples/viewer-webview.html
  examples/viewer.html
  extensions/amp-viewer-integration/0.1/test/viewer-initiated-handshake-viewer-for-testing.js
  extensions/amp-viewer-integration/0.1/test/webview-viewer-for-testing.js
  src/service/viewer-impl.js
  test/functional/test-viewer.js
Labels: cla: yes

#13489 ♻️ Migrate origin whitelist to its own file
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/origin-whitelist.js
Labels: cla: yes

#13557 Remove extra duplicated text
  spec/amp-actions-and-events.md
Labels: cla: yes

#12353 Change amp-access to support multiple sources
  examples/article-access-multiple.amp.html
  extensions/amp-access-laterpay/0.1/amp-access-laterpay.js
  extensions/amp-access-laterpay/0.1/laterpay-impl.js
  extensions/amp-access-laterpay/0.1/test/test-amp-access-laterpay.js
  extensions/amp-access-scroll/0.1/amp-access-scroll.js
  extensions/amp-access-scroll/0.1/scroll-impl.js
  extensions/amp-access/0.1/amp-access-client.js
  extensions/amp-access/0.1/amp-access-other.js
  extensions/amp-access/0.1/amp-access-server-jwt.js
  extensions/amp-access/0.1/amp-access-server.js
  extensions/amp-access/0.1/amp-access-source.js
  extensions/amp-access/0.1/amp-access-vendor.js
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-access/0.1/test/test-amp-access-source.js
  extensions/amp-access/0.1/test/test-amp-access-vendor.js
  extensions/amp-access/0.1/test/test-amp-access.js
  validator/webui/package.json
Labels: cla: yes

#13558 Doubleclick Fast Fetch: Render on Idle Launch
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
Labels: cla: yes

#13536 For the amphtml-validator NPM package, require the Node.js binary to be node.
  validator/build.py
  validator/nodejs/README.md
  validator/nodejs/index.sh
  validator/nodejs/package.json
  validator/nodejs/postinstall-windows.js
Labels: cla: yes

#13515 Clean up docs for new components
  extensions/amp-byside-content/amp-byside-content.md
  extensions/amp-facebook-page/amp-facebook-page.md
  extensions/amp-fx-collection/amp-fx-collection.md
Labels: cla: yes

#13529 Remove flashes on iOS story pages transitions.
  extensions/amp-story/0.1/amp-story.css
Labels: cla: yes

#13568 📖 Make the AMP PR template more readable
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Category: Tooling, Related to: Documentation, cla: yes

#13566 ✅ Disable flaky tests that are causing master to be red
  extensions/amp-image-lightbox/0.1/test/integration/test-amp-image-lightbox.js
  test/integration/test-video-players-helper.js
Labels: Related to: Flaky Tests, cla: yes

#13570 📖 Make emoji suggestions a list
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Related to: Documentation, cla: yes

#13561 <amp-image-viewer> move mutation out of measure into mutate
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
Labels: cla: yes

#13430 fix(playbuzz): Parent url and host which passed to the Playbuzz iframe was not correct
  extensions/amp-playbuzz/0.1/amp-playbuzz.js
Labels: cla: yes

#13564 amp-reach-player: Allow fullscreen
  extensions/amp-reach-player/0.1/amp-reach-player.js
Labels: cla: yes

#13571 Skip 3q video tests due to service instability. Unskip integration tests
  test/integration/test-video-players-helper.js
  test/integration/test-video-players.js
Labels: cla: yes

#13567 Whitelist origins for amp-story: week of 2018-02-20
  extensions/amp-story/0.1/origin-whitelist.js
Labels: cla: yes

#13574 🏗🐛 Correctly apply local dev config during visual tests
  build-system/tasks/visual-diff.rb
  test/visual-diff/visual-tests.js
Labels: Category: Tooling, cla: yes

#13563 Fix bug where lightboxed carousel images show up twice
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#13585 Ramp up 3p-use-ampcontext to 100% traffic.
  build-system/global-configs/prod-config.json
Labels: cla: yes

#13589 🏗 Disable JS during Percy rendering
  build-system/tasks/visual-diff.rb
Labels: Category: Tooling, cla: yes

#13578 Added `open` and `close` events to `amp-lightbox`
  extensions/amp-lightbox/0.1/amp-lightbox.js
  spec/amp-actions-and-events.md
Labels: cla: yes

#13580 🐛🖍 Fix form validation error default display from inline to none
  css/amp.css
Labels: cla: yes

#13598 🏗 Fix Ctrl + C handler on Windows
  build-system/ctrlcHandler.js
Labels: Category: Tooling, cla: yes

#13596 Rename document-click.js to navigation.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  src/runtime.js
  src/service/extensions-impl.js
  src/service/navigation.js
  src/service/standard-actions-impl.js
  src/services.js
  test/functional/test-navigation.js
  test/functional/test-standard-actions.js
Labels: cla: yes

#13590 Stories media pool performance improvements.
  extensions/amp-story/0.1/amp-story-page.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/media-pool.js
Labels: cla: yes

#13439 <amp-selector> Add select{Up/Down} actions
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-selector/0.1/test/test-amp-selector.js
  spec/amp-actions-and-events.md
  src/utils/math.js
  test/functional/utils/test-math.js
Labels: cla: yes

#13243 AmpGwdAnimation page change bug fixes
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation.js
  extensions/amp-gwd-animation/0.1/test/test-amp-gwd-animation.js
Labels: cla: yes

#13577 <amp-lightbox-gallery> launch-blocking manual tests
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#13509 Fixing the 'auto-advance-to' attribute.
  extensions/amp-story/0.1/amp-story.js
Labels: cla: yes

#13599 amp-form: remove for the visible-when-invalid CSS
  css/amp.css
Labels: cla: yes

#13592 Import actions code for subscriptions
  extensions/amp-subscriptions/0.1/actions.js
  extensions/amp-subscriptions/0.1/analytics.js
  extensions/amp-subscriptions/0.1/test/test-actions.js
  extensions/amp-subscriptions/0.1/test/test-analytics.js
  extensions/amp-subscriptions/0.1/test/test-url-builder.js
  extensions/amp-subscriptions/0.1/url-builder.js
Labels: cla: yes

#13594 Create Safeframe Host API for Doubleclick
  examples/doubleclick-safeframe.html
  examples/doubleclick-vanilla.amp.html
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
  tools/experiments/experiments.js
Labels: cla: yes

#13284 ✨ amp-story-auto-ads showing in the right places
  css/amp.css
  examples/amp-story-auto-ads.amp.html
  extensions/amp-story/0.1/amp-story-auto-ads.js
  extensions/amp-story/0.1/amp-story-page.js
  extensions/amp-story/0.1/amp-story.js
Labels: cla: yes

#13559 Add no positive response condition for entitlements
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement-store.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-entitlement-store.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Labels: cla: yes

#13097 Add TreasureData to amp-analytics vendor
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#12985 add imonomy network
  3p/integration.js
  ads/_config.js
  ads/ads.extern.js
  ads/imonomy.js
  ads/imonomy.md
  build-system/dep-check-config.js
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#13386 Adds support for AdPlugg ads. Implements #13345.
  3p/integration.js
  ads/_config.js
  ads/adplugg.js
  ads/adplugg.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
  test/functional/ads/test-adplugg.js
  validator/testdata/feature_tests/ads.html
  validator/testdata/feature_tests/ads.out
Labels: cla: yes

#13520 Amp-ad: add Trugaze network service
  3p/integration.js
  ads/_config.js
  ads/trugaze.js
  ads/trugaze.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#13222 Implementation of new amp-ad network: medyanet
  3p/integration.js
  ads/_config.js
  ads/medyanet.js
  ads/medyanet.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: Category: Ads, cla: no

#13610 🚀Make story-ads start loading immediately
  extensions/amp-story/0.1/amp-story-page.js
Labels: cla: yes

#12475 Broadstreet Ads AMP Ad Implementation
  3p/integration.js
  ads/_config.js
  ads/broadstreetads.js
  ads/broadstreetads.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#13604 Initial draft for lightbox CSS API
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/amp-lightbox-gallery.md
  test/manual/amp-lightbox-gallery-css.amp.html
Labels: cla: yes

#13616 ✨ Disable zoom on double tap (<amp-story>).
  extensions/amp-story/0.1/amp-story.js
  src/gesture-recognizers.js
Labels: cla: yes

#13613 Report errors from BindEvaluator.addMacros()
  extensions/amp-bind/0.1/bind-evaluator.js
  extensions/amp-bind/0.1/bind-impl.js
Labels: cla: yes

#13615 Avoid function names for IE11
  build-system/conformance-config.textproto
  extensions/amp-bind/0.1/bind-expression.js
Labels: cla: yes

#13614 Add <amp-anim> to <amp-lightbox-gallery>
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#13605 Dialog renderer implementation for subscriptions
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions/0.1/amp-subscriptions.css
  extensions/amp-subscriptions/0.1/dialog-renderer.js
  extensions/amp-subscriptions/0.1/dialog.js
  extensions/amp-subscriptions/0.1/expr.js
  extensions/amp-subscriptions/0.1/test/test-dialog-renderer.js
  extensions/amp-subscriptions/0.1/test/test-dialog.js
Labels: cla: yes

#13583 Improve custom ad to support different templateId
  examples/custom.ad.example.json
  examples/custom.ad.example.single.json
  extensions/amp-ad/0.1/amp-ad-custom.js
  extensions/amp-ad/0.1/test/test-amp-ad-custom.js
  test/fixtures/amp-ad-custom.html
  test/integration/test-amp-ad-custom.js
  test/manual/amp-ad-custom.amp.html
  test/manual/amp-ad.custom.amp.html
  testing/iframe.js
Labels: cla: yes

#13625 <amp-facebook-page> Fix typo in propagating data-show-facepile
  3p/facebook.js
  build-system/amp.extern.js
  examples/facebook.amp.html
  extensions/amp-facebook-page/0.1/test/validator-amp-facebook-page.html
  extensions/amp-facebook-page/0.1/test/validator-amp-facebook-page.out
Labels: cla: yes

#13620 amp-carousel: First phase of cleaning up snap experiment
  extensions/amp-carousel/0.1/slidescroll.js
  test/manual/amp-slidescroll.amp.html
  tools/experiments/experiments.js
Labels: cla: yes

#13192 Whitelist actions on the special AMP target
  src/service/standard-actions-impl.js
  test/functional/test-standard-actions.js
Labels: Category: Runtime, P2: Soon, Type: Feature Request, cla: yes

#13618 🚀 Make sure amp-story ad is loaded before display
  extensions/amp-story/0.1/amp-story-auto-ads.js
  extensions/amp-story/0.1/amp-story-page.js
Labels: cla: yes

#13611 Amp subscriptions: Read service config from page
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement-store.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/renderer.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-entitlement-store.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-renderer.js
Labels: cla: yes

#13624 Change thumbnail src to thumbnail id for lightbox thumbnail api
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-placeholders.js
  extensions/amp-lightbox-gallery/amp-lightbox-gallery.md
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#13639 Add <amp-ad> to <amp-lightbox-gallery> support
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  src/ad-helper.js
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#13636 Amp subs platform factory
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Labels: cla: yes

#13640 ✨Use template ads for `auto-story-ads`
  examples/amp-story-auto-ads-payload.json
  examples/amp-story-auto-ads.amp.html
  extensions/amp-story/0.1/amp-story-auto-ads.js
Labels: cla: yes

#13648 🐛 Fix progress-bar segments showing on ads in story
  extensions/amp-story/0.1/amp-story-auto-ads.js
Labels: cla: yes

#13631 Adds new "call to action" layer
  examples/amp-story/cta-layer-outlink.html
  extensions/amp-story/0.1/amp-story-cta-layer.js
  extensions/amp-story/0.1/amp-story.css
Labels: cla: yes

#13607 Reinforcing width check for full-width responsive ad units
  3p/3p.js
  ads/google/adsense.js
  ads/google/test/test-adsense.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Labels: cla: yes

#13654 Toggle next / prev buttons on <amp-lightbox-gallery>
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#13638 Rewrite `target` for <a> during [href] mutate
  extensions/amp-bind/0.1/bind-impl.js
  src/sanitizer.js
  test/functional/test-sanitizer.js
Labels: cla: yes

#13678 🐛Fix failure to reauthorize on login in amp-access
  extensions/amp-access/0.1/amp-access-source.js
  extensions/amp-access/0.1/amp-access.js
Labels: cla: yes

#13662 Pass two new RTC macros to media.net
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#13693 🏗 Remove .js extension from visual tests config file
  build-system/config.js
  build-system/tasks/visual-diff.rb
  test/visual-diff/visual-tests
Labels: Category: Tooling, cla: yes

#13691 Whitelist origins for amp-story: week of 2018-02-27
  extensions/amp-story/0.1/origin-whitelist.js
  extensions/amp-story/0.1/test/test-origin-whitelist.js
Labels: cla: yes

#13637 Add two new custom macros for RTC
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#13697 Make sure to clear iframe in SafeframeHostApi on destroy
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
Labels: cla: yes

#13649 AMP Story Ads Documentation
  extensions/amp-story/ad-serving-integration.md
  extensions/amp-story/amp-story-ads.md
  extensions/amp-story/img/consistent-ux.png
  extensions/amp-story/img/sponsored-story-ad.png
  extensions/amp-story/img/story-page-ad.png
Labels: Category: Ads, cla: yes

#13184 Minimal (experimental) document-level infinite-scroll extension
  examples/amp-document-recommendations.amp.html
  extensions/amp-document-recommendations/0.1/amp-document-recommendations.css
  extensions/amp-document-recommendations/0.1/amp-document-recommendations.js
  extensions/amp-document-recommendations/0.1/config.js
  extensions/amp-document-recommendations/OWNERS.yaml
  extensions/amp-document-recommendations/amp-document-recommendations.md
  extensions/amp-document-recommendations/validator-amp-document-recommendations.protoascii
  gulpfile.js
  src/runtime.js
  tools/experiments/experiments.js
Labels: cla: yes

#13679 First pass on optimizing lightbox performance
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#13703 🏗 Don't terminate pr-check if `gulp visual-diff` times out
  build-system/pr-check.js
Labels: Category: Tooling, P1: High Priority, cla: yes

#13694 🏗 Visual tests: Use large viewport with 1x pixel ratio
  build-system/tasks/visual-diff.rb
Labels: Category: Tooling, cla: yes

#13480 ✨ Added maps protocol to allowed AMP ones
  validator/validator-main.protoascii
Labels: cla: yes

#13704 🖍Add amp-story-grid-layer to injected ads
  examples/amp-story-auto-ads.amp.html
  extensions/amp-story/0.1/amp-story-auto-ads.js
Labels: cla: yes

#13665 Adds validation spec for the new cta-layer ✨
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#13644 Refactor lightbox launch tests
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#13687 fix(overflow): "Show More" button position should be in the bottom
  extensions/amp-playbuzz/0.1/amp-playbuzz.css
Labels: cla: yes

#13724 Doc fix clarifying sponsored story ad
  extensions/amp-story/amp-story-ads.md
Labels: cla: yes

#13705 🏗 Correctly set up Selenium options for visual tests
  build-system/tasks/visual-diff.rb
Labels: Category: Tooling, cla: yes

#13707 Fix race condition in consecutive amp-list [src] mutations
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#13726 Add AMP4EMAIL
  validator/webui/@polymer/webui-mainpage/webui-mainpage.html
  validator/webui/@polymer/webui-urlform/webui-urlform.html
Labels: Category: Validator, cla: yes
