Repository ampproject/amphtml, pull requests merged in 2018-10, with the labels that each got.

#18438 🐛✨Add behavior to prevent touch device keyboard bouncing, and opt-out
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.html
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out
  extensions/amp-date-picker/amp-date-picker.md
  extensions/amp-date-picker/validator-amp-date-picker.protoascii
Labels: cla: yes

#18450 AMP-Cache-Transform: Specify caches.json max age.
  spec/amp-cache-transform.md
Labels: cla: yes

#18434 Set display:block to sentinel element of animateScrollToTop_ explicitly
  extensions/amp-viewer-integration/0.1/highlight-handler.js
  extensions/amp-viewer-integration/0.1/test/test-highlight-handler.js
Labels: cla: yes

#18465 amp-access-laterpay: Laterpay badge changes
  extensions/amp-access-laterpay/0.2/laterpay-impl.js
Labels: cla: yes

#18447 🐛✨ Analytics: Support boolean enabled value
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
Labels: cla: yes

#18467 🐛Avoid using display: initial to fix form validation messages in IE11
  css/amp.css
  extensions/amp-form/0.1/amp-form.css
Labels: cla: yes

#18397 🏗 Fix build on Windows - Use proper shellCmd depending on platform
  build-system/exec.js
Labels: cla: yes

#18298 ♻️Remove caching of GlobalVariableSource Expr
  src/service/variable-source.js
  test/functional/test-variable-source.js
Labels: cla: yes

#18453 ✨Analytics: LINKER_PARAM binding
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/cookie-writer.js
  extensions/amp-analytics/0.1/linker-reader.js
  extensions/amp-analytics/0.1/linker.js
  extensions/amp-analytics/0.1/test/test-cookie-writer.js
  extensions/amp-analytics/0.1/test/test-linker-reader.js
  extensions/amp-analytics/0.1/test/test-linker.js
  src/url.js
  src/utils/base64.js
  test/functional/test-url.js
  test/functional/utils/test-base64.js
  test/manual/amp-analytics-cookie-writer.html
Labels: cla: yes

#18359 📖 AMP-Cache-Transform: Other content negotation
  spec/amp-cache-transform.md
Labels: cla: yes

#18217 ✨ Report amp4ads-id in getErrorReportData() for inabox
  examples/inabox.amp.html
  src/error.js
  src/inabox/amp-inabox.js
  src/inabox/utils.js
  src/mode.js
  test/functional/inabox/test-utils.js
  test/functional/test-mode.js
Labels: cla: yes

#18495 📖 AMP-Cache-Transform: explain caches registry.
  spec/amp-cache-transform.md
Labels: cla: yes

#18455 Fix vendor request tests
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/test/test-vendors.js
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/variables.js
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#18292 :book: Correcting a typo in uas.md file
  ads/uas.md
Labels: cla: yes

#18368 ✨Add form support for Linker
  examples/linkers.html
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-form/0.1/form-submit-service.js
  src/services.js
Labels: cla: yes

#18477 Fix Doubleclick SRA race condition
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#18487 🏗 Set minimum version of `yarn` to 1.10.1
  .travis.yml
  build-system/SERVING.md
  package.json
  validator/nodejs/yarn.lock
  validator/webui/yarn.lock
  validator/yarn.lock
  yarn.lock
Labels: cla: yes

#18457 ♻️ Fix LGTM alert for missing semicolon
  ads/google/imaVideo.js
Labels: cla: yes

#16495 📖Fix Typo: JSDoc typedef of ResourceSpecForHostDef
  extensions/amp-analytics/0.1/resource-timing.js
Labels: cla: yes

#18464 🐛Read attributes in buildCallback, not constructor
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker.js
Labels: cla: yes

#17751 📖 Fixing a typo in amp-var-substituions
  spec/amp-var-substitutions.md
Labels: cla: yes

#17701 ♻️ nexxtv-player minor change in building video source
  extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js
  extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js
Labels: cla: yes

#18471 Remove triggerTransformEnd from the set function
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  extensions/amp-pan-zoom/0.1/test/test-amp-pan-zoom.js
  src/gesture-recognizers.js
  testing/test-helper.js
Labels: cla: yes

#18510 🏗 Remove `--headless` mode from `gulp visual-diff` task
  build-system/pr-check.js
  build-system/tasks/visual-diff.js
  contributing/TESTING.md
Labels: cla: yes

#18503 🏗 Replace the default Percy filesystem resources loader with a custom implementation that supports multiple resource directories
  .eslintignore
  build-system/config.js
  build-system/tasks/visual-diff/index.js
  build-system/tasks/visual-diff/percy-assets-loader.js
  build-system/tasks/visual-diff/snippets/iframe-wrapper.js
  test/visual-diff/visual-tests
Labels: cla: yes

#18527 Doubleclick: Re-enable SRA 1% experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#18442 Fix typos in comments
  extensions/amp-subscriptions/0.1/platform-store.js
Labels: cla: yes

#18476 🐛Fix validation bubble polyfill in IE11
  extensions/amp-form/0.1/form-validators.js
  extensions/amp-form/0.1/test/test-form-validators.js
Labels: cla: yes

#18535 Update Google VR View to version 2.0
  extensions/amp-google-vrview-image/0.1/amp-google-vrview-image.js
  extensions/amp-google-vrview-image/0.1/test/test-amp-google-vrview-image.js
Labels: cla: yes

#18534 Force unique ID for all AMP accordions
  extensions/amp-accordion/0.1/amp-accordion.js
  extensions/amp-accordion/0.1/test/test-amp-accordion.js
Labels: cla: yes

#18537 🐛Fix transition when using amp-image-lightbox in a shadow doc.
  extensions/amp-image-lightbox/0.1/amp-image-lightbox.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#18393 allow single pass code to write out to other directories besides dist
  build-system/get-dep-graph.js
  gulpfile.js
Labels: Category: Tooling, cla: yes

#18544 SwG release 0.1.22.28
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#18547 Update amp-selector doc with support for disabled
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#18530 Change (deprecated) KeyboardEvent.keyCode -> KeyboardEvent.key
  extensions/amp-accordion/0.1/amp-accordion.js
  extensions/amp-accordion/0.1/test/test-amp-accordion.js
  extensions/amp-carousel/0.1/base-carousel.js
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-image-lightbox/0.1/amp-image-lightbox.js
  extensions/amp-image-lightbox/0.1/test/test-amp-image-lightbox.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-selector/0.1/test/test-amp-selector.js
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
  extensions/amp-social-share/0.1/amp-social-share.js
  extensions/amp-social-share/0.1/test/test-amp-social-share.js
  extensions/amp-story/0.1/amp-story-bookend.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/test/test-amp-story.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/test/test-amp-story.js
  extensions/amp-viewer-integration/0.1/touch-handler.js
  src/service/action-impl.js
  src/utils/key-codes.js
  test/functional/test-action.js
Labels: cla: yes

#18538 Break words in story navigation overlay.
  extensions/amp-story/1.0/amp-story-hint.css
Labels: cla: yes

#18494 Adding Babel filter import to remove unwanted fetch polyfill
  build-system/build.conf.js
  build-system/get-dep-graph.js
  build-system/tasks/compile.js
  gulpfile.js
  package.json
  yarn.lock
Labels: cla: yes

#18437 Add handler to forward keyboard events to viewer
  extensions/amp-viewer-integration/0.1/amp-viewer-integration.js
  extensions/amp-viewer-integration/0.1/keyboard-handler.js
  extensions/amp-viewer-integration/0.1/test/integration/test-amp-viewer-integration.js
  extensions/amp-viewer-integration/0.1/test/test-keyboard-handler.js
Labels: cla: yes

#18557 [amp-pan-zoom] should clear previous width/height on resetContentDimensions
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  extensions/amp-pan-zoom/0.1/test/test-amp-pan-zoom.js
  test/manual/amp-pan-zoom-initial.amp.html
Labels: cla: yes

#18576 Remove recently added references to `keyCodes`
  extensions/amp-viewer-integration/0.1/keyboard-handler.js
  extensions/amp-viewer-integration/0.1/test/test-keyboard-handler.js
  src/utils/key-codes.js
Labels: cla: yes

#18571 Separate login logic from subscribe and change default of supportsViewer to 0
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/platform-store.js
  extensions/amp-subscriptions/0.1/score-factors.js
  extensions/amp-subscriptions/0.1/test/test-platform-store.js
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#18588 Fix bug in regex matching in compile.js
  build-system/tasks/compile.js
Labels: cla: yes

#18283 Update de.js
  extensions/amp-story/1.0/_locales/de.js
Labels: cla: yes

#18589 Don't parse CC output for swg.js warnings -- just fix them
  build-system/tasks/compile.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#18598 remove doubleclickIdleExp experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#18597 Doubleclick render idle enable bool renderOutsideViewport
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#18572 Fixes Safari desktop background fade in.
  extensions/amp-story/1.0/amp-story-desktop.css
Labels: cla: yes

#17699 Cleanup story navigation performance experiment configuration.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#17664 Cleanup story navigation performance experiment.
  tools/experiments/experiments.js
Labels: cla: yes

#18536 Fix the audio hint text positioning when the info icon is present.
  extensions/amp-story/1.0/amp-story-system-layer.css
Labels: cla: yes

#18590 📖 Added examples to amp-image-slider.md #18058
  extensions/amp-image-slider/amp-image-slider.md
Labels: cla: yes

#18517 🐛Fix a2a for next article links in amp-next-page
  extensions/amp-next-page/0.1/next-page-service.js
Labels: cla: yes

#18475 some errors are not propagated properly from compilation step
  build-system/get-dep-graph.js
Labels: Category: Tooling, Type: Bug, cla: yes

#18553 Layers: fix Resource detection of measurement changes
  src/service/resource.js
Labels: cla: yes

#18604 SwG release 0.1.22.29
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#18043 ✨ [standard-action] Add AMP.navigateTo optional target param
  examples/standard-actions.amp.html
  spec/amp-actions-and-events.md
  src/service/navigation.js
  src/service/standard-actions-impl.js
  test/functional/test-standard-actions.js
Labels: cla: yes

#18520 Serve ampdoc-closest to 1% of traffic.
  build-system/global-configs/prod-config.json
Labels: cla: yes

#18540 Remove poster on amp-video elements when done with first layout
  extensions/amp-video/0.1/amp-video.js
Labels: cla: yes

#18521 Cookie Writer spec improvement
  extensions/amp-analytics/0.1/cookie-writer.js
  extensions/amp-analytics/0.1/test/test-cookie-writer.js
  test/manual/amp-analytics-cookie-writer.html
Labels: cla: yes

#18497 ♻️Linker: Use action-xhr when possible
  examples/linkers.html
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/form-submit-service.js
  extensions/amp-form/0.1/test/test-amp-form.js
  tools/experiments/experiments.js
Labels: cla: yes

#18580 Add a `size-changed` signal to common signals
  src/common-signals.js
  src/custom-element.js
  test/functional/test-custom-element.js
Labels: cla: yes

#18502 Linker: remove form listener in unlayout
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-form/0.1/form-submit-service.js
Labels: cla: yes

#18543 amp-list resize partial fix with signals for overflow-clicked
  css/amp.css
  extensions/amp-list/0.1/amp-list.js
  test/manual/amp-list-resize-flex.amp.html
  test/manual/amp-list-resize.amp.html
Labels: cla: yes

#18202 📖 Specifies adding env variable for java version
  contributing/getting-started-e2e.md
Labels: cla: yes

#18613 Change Addthis loading Placeholder color
  extensions/amp-addthis/0.1/amp-addthis.js
Labels: cla: yes

#18526 🐛 Do not set last page as active if bookend is open
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story-store-service.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#18623 Change GA config to read from linker_param and write to cookie
  extensions/amp-analytics/0.1/vendors/googleanalytics.js
  test/manual/amp-analytics-cookie-writer.html
Labels: cla: yes

#18541 🐛Expander: Fix handling of falsey resolvers
  extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
  src/service/url-expander/expander.js
  test/functional/url-expander/test-expander.js
Labels: cla: yes

#18451 ✨ Added a 3p frame domain key for Google's AMP Cache.
  caches.json
Labels: cla: yes

#18554 ♻️Expander: Add args to opt_collectVars
  src/service/url-expander/expander.js
  test/functional/url-expander/test-expander.js
Labels: cla: yes

#18410 Refactoring: Consolidate batch plugin logic.
  build-system/tasks/presubmit-checks.js
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/batching-plugins.js
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/test/test-requests.js
Labels: cla: yes

#18539 🐛AMP inabox : Fixed pixel imperfection by resetting position on body
  css/amp.css
  examples/ads/inabox.adchoices.html
  examples/inabox.gpt.html
  src/inabox/amp-inabox-lite.js
  src/inabox/amp-inabox.js
Labels: cla: yes

#18638 Bump up size
  build-system/tasks/bundle-size.js
Labels: cla: yes

#18611 🐛Added Mute/Unmute Controls to <amp-ima-video>
  ads/google/imaVideo.js
  examples/ima-video.amp.html
  extensions/amp-ima-video/0.1/test/test-amp-ima-video.js
Labels: cla: yes

#18642 Turn of scroll snap amp-carousel experiment in Canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#18639 Fix experiment logic in amp-carousel
  extensions/amp-carousel/0.1/slidescroll.js
  tools/experiments/experiments.js
Labels: cla: yes

#18643 Ad example page: add comment on expected error
  examples/ads.amp.html
Labels: cla: yes

#18640 🐛Lazy generate linker values.
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
Labels: cla: yes

#18641 amp-selector: Support event.selectedOptions in on="select:..."
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-selector/0.1/test/test-amp-selector.js
  extensions/amp-selector/amp-selector.md
  spec/amp-actions-and-events.md
Labels: cla: yes

#18433 added quotes to documentation
  ads/connatix.md
Labels: cla: yes

#18380 📖 Correct description for allow-blocked-ranges
  extensions/amp-date-picker/amp-date-picker.md
Labels: cla: yes

#18646 updated pinterest Pin It language to Save
  extensions/amp-pinterest/amp-pinterest.md
Labels: cla: yes

#18635 🏗 Add baseline for localhost:8000 UI
  build-system/app-index/index.js
  build-system/app-index/template.html
  build-system/app.js
  build-system/tasks/runtime-test.js
Labels: Category: Tooling, cla: yes

#18574 🏗✨ Upgrade to Babel 7
  .babelrc
  .eslintrc
  babel.config.js
  build-system/get-dep-graph.js
  build-system/tasks/compile-access-expr.js
  build-system/tasks/compile-bind-expr.js
  build-system/tasks/compile-css-expr.js
  build-system/tasks/compile-expr.js
  build-system/tasks/index.js
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test.js
  build-system/tasks/update-packages.js
  extensions/amp-access/0.1/access-expr-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-rtc.js
  extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js
  extensions/amp-animation/0.1/css-expr-impl.js
  extensions/amp-animation/0.1/test/test-amp-animation.js
  extensions/amp-app-banner/0.1/test/test-amp-app-banner.js
  extensions/amp-bind/0.1/bind-expr-impl.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
  extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
  gulpfile.js
  package.json
  src/error.js
  src/log.js
  src/shadow-embed.js
  test/_init_tests.js
  test/functional/test-history.js
  test/functional/test-layout.js
  test/functional/test-resource.js
  test/integration/test-position-observer.js
  yarn.lock
Labels: Category: Tooling, cla: yes

#18636 Add eslint no-non-string-log-args rule
  .eslintrc
  build-system/eslint-rules/no-import-rename.js
  build-system/eslint-rules/no-non-string-log-args.js
  build-system/tasks/lint.js
Labels: cla: yes

#18169 :sparkles: added pressboard as an analytics vendor
  examples/ads-legacy.amp.html
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/pressboard.js
Labels: cla: yes

#18605 🏗 Add basic manual testbench for video players
  build-system/app-video-testbench.js
  build-system/app.js
  build-system/tasks/presubmit-checks.js
  test/manual/amp-video.amp.html
Labels: cla: yes

#18569 Desktop navigation animation improvements.
  extensions/amp-story/1.0/amp-story-desktop.css
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#18633 Add the BiP Messenger scheme to anchor href attributes.
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#18675 Increase bundle size for patch canary
  build-system/tasks/bundle-size.js
Labels: cla: yes

#18666 Whitelist extra macros for anchor href substitution
  src/service/url-replacements-impl.js
  test/functional/test-url-replacements.js
Labels: cla: yes

#18674 🐛 Make `web-animations-js` compatible with strict mode and unskip failing tests
  build-system/tasks/update-packages.js
  extensions/amp-animation/0.1/test/test-amp-animation.js
Labels: Category: Tooling, cla: yes

#18505 Re-enable layers
  build-system/global-configs/canary-config.json
Labels: cla: yes

#18665 amp-script: Working skeleton
  build-system/dep-check-config.js
  build-system/tasks/compile.js
  build-system/tasks/update-packages.js
  bundles.config.js
  examples/script.amp.html
  examples/script.js
  extensions/amp-script/0.1/amp-script.js
  gulpfile.js
  package.json
  yarn.lock
Labels: cla: yes

#18686 🐛 Check if doc is RTL before instantiating page-advancement in amp-story
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#18672 🏗 Ignore errors when navigating to blank.html
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#18644 📖 AMP-Cache-Transform: specify version syntax.
  spec/amp-cache-transform.md
Labels: cla: yes

#18629 🐛 amp-next-page: Fix relative URL handling when served from the cache
  extensions/amp-next-page/0.1/amp-next-page.js
  extensions/amp-next-page/0.1/config.js
  extensions/amp-next-page/0.1/test/test-config.js
Labels: cla: yes

#18628 🐛 Tweaks to the extension generator
  build-system/tasks/extension-generator/index.js
Labels: cla: yes

#18670 Added documentation on keyboard-select-mode
  extensions/amp-selector/amp-selector.md
Labels: cla: yes

#18688 ⏪Undo updgrade of react-dates to 18.1.0
  package.json
  third_party/react-dates/_datepicker.css
  third_party/react-dates/bundle.js
  yarn.lock
Labels: cla: yes

#18186 ✨ Added embed for Yandex Zen content-recommendation platform
  3p/integration.js
  ads/_config.js
  ads/ads.extern.js
  ads/zen.js
  ads/zen.md
  build-system/conformance-config.textproto
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#18691 Fix overlay single date picker to open to selected date.
  examples/date-picker.amp.html
  examples/date-picker.json
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/date-picker-common.js
  extensions/amp-date-picker/0.1/single-date-picker.js
Labels: cla: yes

#18366 :sparkles: Add Tealium Collect for amp analytics
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/tealiumcollect.js
Labels: cla: yes

#18637 add owners list for addthis extension
  extensions/amp-addthis/OWNERS.yaml
Labels: cla: yes

#18708 Revert ":sparkles: Add Tealium Collect for amp analytics"
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/tealiumcollect.js
Labels: cla: yes

#18703 Allow Multi-line CSS styles in AMP doc
  validator/testdata/amp4ads_feature_tests/min_valid_multiline_amp4ads.html
  validator/testdata/amp4ads_feature_tests/min_valid_multiline_amp4ads.out
  validator/testdata/amp4email_feature_tests/min_valid_multiline_amp4email.html
  validator/testdata/amp4email_feature_tests/min_valid_multiline_amp4email.out
  validator/testdata/feature_tests/new_multiline_boilerplate.html
  validator/testdata/feature_tests/new_multiline_boilerplate.out
  validator/validator-main.protoascii
Labels: cla: yes

#17900 SSR refactoring
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-mustache/0.1/amp-mustache.js
  extensions/amp-mustache/0.1/test/test-amp-mustache.js
  extensions/amp-mustache/0.2/amp-mustache.js
  extensions/amp-mustache/0.2/test/test-amp-mustache.js
  src/service/template-impl.js
  test/functional/test-ssr-template-helper.js
Labels: cla: yes

#18618 🐛Removed the Extra Play event when starting ads
  ads/google/imaVideo.js
Labels: cla: yes

#18693 added sample of styling for content fetched in amp-list
  extensions/amp-list/amp-list.md
Labels: cla: yes

#18663 updated documentation to include amp-bind option for...
  extensions/amp-form/amp-form.md
Labels: cla: yes

#18722 ✅amp-brightcove: Extend test coverage
  extensions/amp-brightcove/0.1/amp-brightcove.js
  extensions/amp-brightcove/0.1/test/test-amp-brightcove.js
Labels: cla: yes

#18707 ✨ Add no-verify attribute to exclude elements from verify-xhr
  examples/forms.amp.html
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/form-verifiers.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-form/amp-form.md
  src/form-data-wrapper.js
  test/functional/test-form-data-wrapper.js
  validator/testdata/feature_tests/forms.html
  validator/testdata/feature_tests/forms.out
  validator/validator-main.protoascii
Labels: cla: yes

#18710 ♻️🐛✅Refactor FormDataWrapper and fix select[multiple] and test
  build-system/amp.extern.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  src/form-data-wrapper.js
  src/form.js
  src/service/xhr-impl.js
  src/utils/xhr-utils.js
  test/functional/test-form-data-wrapper.js
  test/functional/test-form.js
  test/functional/test-xhr-fetch-polyfill.js
  test/functional/test-xhr.js
Labels: cla: yes

#18729 Fix test failure and add tealiumcollect config back.
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/tealiumcollect.js
  test/manual/analytics-batching.amp.html
Labels: cla: yes

#18711 🏗️✨Log analytics in video testbench
  build-system/app-video-testbench.js
  test/manual/amp-video.amp.html
Labels: cla: yes

#18718 🏗✨ Use localhost:8000 template for all directory listings
  build-system/app-index/index.js
  build-system/app-index/listing-header.html
  build-system/app-index/proxy-form.html
  build-system/app-index/template.html
  build-system/app.js
Labels: cla: yes

#18751 🐛Do not submit value for empty multiselect
  src/form.js
  test/functional/test-form.js
Labels: cla: yes

#18687 🐛[amp-ad] fix errors occurring during the call of noContentAvailable in capirs
  ads/capirs.js
  examples/ads.amp.html
Labels: cla: yes

#18752 👨🏻‍🔬Turn on linker-form experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#18747 🏗✨Support entering proxy URLs without protocol prefix
  build-system/app-index/proxy-form.html
Labels: Category: Tooling, cla: yes

#18754 🏗✨Support choosing example rendering mode
  build-system/app-index/index.js
  build-system/app-index/template.html
Labels: cla: yes

#18701 amp-script: Add TodoMVC example
  build-system/config.js
  examples/amp-script/hello-world.amp.html
  examples/amp-script/hello-world.js
  examples/amp-script/todomvc.amp.html
  examples/amp-script/todomvc.es6.js
  examples/amp-script/todomvc.js
  examples/amp-script/todomvc.uglify.js
Labels: cla: yes

#18757 Revert "🐛Expander: Fix handling of falsey resolvers (#18541)"
  extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
  src/service/url-expander/expander.js
  test/functional/url-expander/test-expander.js
Labels: cla: yes

#18738 Add fie-metadata-extension experiment
  tools/experiments/experiments.js
Labels: cla: yes

#18340 🐛amp-analytics Stop adding triggers if has been detached
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
Labels: cla: yes

#18258 Apply placeholder to CMP provided iframe
  extensions/amp-consent/0.1/amp-consent.css
  extensions/amp-consent/0.1/consent-ui.js
  test/manual/diy-consent.html
Labels: cla: yes

#18777 🐛 Chrome 70 array.sort uses stable TimSort which exposed bunch of bugs
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
  extensions/amp-bind/0.1/test/test-bind-expression.js
  extensions/amp-subscriptions/0.1/platform-store.js
  src/service/fixed-layer.js
  test/functional/test-fixed-layer.js
Labels: cla: yes

#18716 Hold to pause for amp-story.
  extensions/amp-story/1.0/page-advancement.js
  tools/experiments/experiments.js
Labels: cla: yes

#18781 Launch the amp-story-hold-to-pause experiment in Canary.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#18774 📖 Fixes typo in extensions/amp-analytics/linker-id-receiving.md
  extensions/amp-analytics/linker-id-receiving.md
Labels: cla: yes

#18764 🏗🐛 Make proxy form validation less zealous
  build-system/app-index/proxy-form.html
Labels: cla: yes

#18780 Hiding the story UI on hold to pause.
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/test/test-amp-story-system-layer.js
Labels: cla: yes

#18765 🐛 Bring back `amp-youtube` listening delay
  extensions/amp-youtube/0.1/amp-youtube.js
Labels: cla: yes

#18766 🏗🐷 Piggy-back on Github's find function for finding files
  build-system/app-index/template.html
Labels: cla: yes

#18767 🖍 Compact listing view
  build-system/app-index/index.js
  build-system/app-index/listing-header.html
  build-system/app-index/template.html
Labels: cla: yes

#18790 🐛 Use win.head when checking for extensions, fix test warning
  src/element-service.js
  test/functional/test-element-service.js
Labels: cla: yes

#18791 Shadow viewport: only enable transfer under experiment to test out iOS12
  src/service/viewport/viewport-binding-ios-embed-sd.js
  test/functional/test-viewport-binding.js
  tools/experiments/experiments.js
Labels: cla: yes

#18795 Add more detailed instructions for gulp firebase
  contributing/TESTING.md
Labels: cla: yes

#18801 SwG Release 01.22.33
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg-button.css
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#18786 🏗🐛 Add `AMP_CONFIG` to shadow and ads runtime files
  build-system/tasks/runtime-test.js
  gulpfile.js
Labels: Category: Tooling, cla: yes

#18608 Clarify experiment cleanup presubmit
  build-system/pr-check.js
Labels: Category: Tooling, cla: yes

#18145 🏗 Store bundle sizes from Travis push builds in the build artifacts storage repo
  build-system/git.js
  build-system/pr-check.js
  build-system/tasks/bundle-size.js
  package.json
  yarn.lock
Labels: cla: yes

#18772 amp-list: Reset pending change-size request after render
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#18770 Allow storing non boolean value to localStorage
  build-system/tasks/presubmit-checks.js
  src/service/storage-impl.js
Labels: cla: yes

#18570 Only reports errors to StackDriver if it's not reported to viewer
  src/error.js
  test/functional/test-error.js
Labels: cla: yes

#18812 🏗 Set `target=_blank` on header links
  build-system/app-index/template.html
Labels: cla: yes

#18813 ♻️ Split CSS into its own file
  build-system/app-index/index.js
  build-system/app-index/main.css
  build-system/app-index/template.html
Labels: cla: yes

#18669 ✨ Adding Pressboard implementation of amp-ad
  3p/integration.js
  ads/_config.js
  ads/ads.extern.js
  ads/pressboard.js
  ads/pressboard.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#18821 📖 amp-3d-gltf: Document CORS requirements.
  extensions/amp-3d-gltf/amp-3d-gltf.md
Labels: cla: yes
