Repository ampproject/amphtml, pull requests merged in 2018-05, with the labels that each got.

#14963 Update autoprefixer to the latest version 🚀
  package.json
  yarn.lock
Labels: cla: yes

#14984 ✅Bump up bundle size again
  gulpfile.js
Labels: Blocked, cla: yes

#14970 AdSense Delayed Fetch amp-consent integration
  ads/google/adsense.js
  ads/google/test/test-adsense.js
Labels: cla: yes

#14986 Whitelist origins for amp-story: week of 2018-05-01
  extensions/amp-story/0.1/origin-whitelist.js
  extensions/amp-story/1.0/origin-whitelist.js
Labels: cla: yes

#14864 Anchor click interceptor and navigation service cleanup
  build-system/dep-check-config.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  src/anchor-click-interceptor.js
  src/inabox/amp-inabox.js
  src/service/navigation.js
  test/functional/test-anchor-click-interceptor.js
  test/functional/test-navigation.js
Labels: cla: yes

#14969 ✅ Add validation for rotate-to-fullscreen in amp-video
  extensions/amp-video/0.1/test/validator-amp-video.html
  extensions/amp-video/0.1/test/validator-amp-video.out
  extensions/amp-video/validator-amp-video.protoascii
Labels: cla: yes

#14982 Ensure `toggleLoading()` respects `isLoadingEnabled()`
  src/base-element.js
  test/functional/test-custom-element.js
  test/functional/test-layout.js
Labels: cla: yes

#14990 ✨ Adds an embed mode that removes sharing
  extensions/amp-story/0.1/amp-story-bookend.js
  extensions/amp-story/0.1/amp-story-share.css
  extensions/amp-story/0.1/amp-story-store-service.js
  extensions/amp-story/0.1/amp-story-system-layer.css
  extensions/amp-story/0.1/amp-story-system-layer.js
  extensions/amp-story/0.1/embed-mode.js
  extensions/amp-story/1.0/amp-story-share.css
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/embed-mode.js
Labels: cla: yes

#14983 🏗 Check for latest LTS version of `node` and stable version of `yarn` during `preinstall`
  .travis.yml
  build-system/check-package-manager.js
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
  package.json
Labels: Category: Tooling, cla: yes

#14996 Revert "Ensure `toggleLoading()` respects `isLoadingEnabled()` (#14982)"
  src/base-element.js
  test/functional/test-custom-element.js
  test/functional/test-layout.js
Labels: cla: yes

#14978 ✅Fix console errors in test-amp-sidebar
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
Labels: cla: yes

#14948 ♻️ Code cleaning for amp-story bookend
  extensions/amp-story/1.0/amp-story-share.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/bookend/bookend-component.js
  extensions/amp-story/1.0/bookend/components/article.js
  extensions/amp-story/1.0/bookend/components/bookend-component-interface.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
Labels: cla: yes

#14458 IntersectionObserverPolyfill wrapper for amp-a4a refresh.
  extensions/amp-a4a/0.1/refresh-intersection-observer-wrapper.js
  extensions/amp-a4a/0.1/refresh-manager.js
  extensions/amp-a4a/0.1/test/test-refresh-manager.js
  extensions/amp-a4a/0.1/test/test-refresh.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#14988 Delete doubleclick.js
  3p/integration.js
  ads/google/deprecated_doubleclick.js
  ads/google/doubleclick.js
  ads/google/test/test-doubleclick.js
  build-system/tasks/runtime-test.js
Labels: cla: yes

#14967 📖 Add common documentation for video interface and point to it
  extensions/amp-video/amp-video.md
  spec/amp-video-interface.md
Labels: cla: yes

#15001 🚮 Remove fullscreen from amp-gfycat
  extensions/amp-gfycat/0.1/amp-gfycat.js
Labels: cla: yes

#14987 amp-addthis: Update availability documentation since it is live
  extensions/amp-addthis/amp-addthis.md
Labels: cla: yes

#15003 ♻️ VideoInterface types cleanup
  extensions/amp-video-service/0.1/amp-video-service.js
  src/service/video-manager-impl.js
  src/video-interface.js
Labels: cla: yes

#15002 🚩 Add flag for marking rotate-to-fullscreen as pre-implemented
  extensions/amp-3q-player/0.1/amp-3q-player.js
  extensions/amp-brid-player/0.1/amp-brid-player.js
  extensions/amp-dailymotion/0.1/amp-dailymotion.js
  extensions/amp-gfycat/0.1/amp-gfycat.js
  extensions/amp-ima-video/0.1/amp-ima-video.js
  extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js
  extensions/amp-ooyala-player/0.1/amp-ooyala-player.js
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-wistia-player/0.1/amp-wistia-player.js
  extensions/amp-youtube/0.1/amp-youtube.js
  src/service/video-manager-impl.js
  src/video-interface.js
Labels: cla: yes

#15016 🚮 Remove unused private variables from amp-analytics and amp-form
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-form/0.1/amp-form.js
Labels: cla: yes

#15014 :bug: Prefer originalTitle for analytics, if set.
  src/service/url-replacements-impl.js
  test/functional/test-url-replacements.js
Labels: cla: yes

#14997 Pass along sharedData from consent response to 3p ad iframes
  3p/ampcontext.js
  ads/_ping_.js
  build-system/app.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  src/consent-state.js
Labels: cla: yes

#15019 Fixes accidentally unskipped flaky test.
  extensions/amp-a4a/0.1/test/test-refresh.js
Labels: cla: yes

#15013 ✨amp-consent: support consent policy timeout
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  test/manual/amp-consent.html
Labels: cla: yes

#15017 ♻️Add restricted and visibleForTesting annotations to private gesture methods.
  src/gesture.js
Labels: cla: yes

#15026 🐛🏗 Fix error reporting from `browserify`
  gulpfile.js
Labels: Category: Tooling, cla: yes

#15034 📖 Document amp-consent related ampcontext APIs.
  ads/README.md
Labels: cla: yes

#15032 🏗 Set minimum `yarn` version to 1.3.2
  .travis.yml
  package.json
Labels: Category: Tooling, cla: yes

#15036 📖 amp-consent: consent blocking policy
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#15024 Remove <amp-youtube> internal state tracking
  extensions/amp-youtube/0.1/amp-youtube.js
  extensions/amp-youtube/0.1/test/test-amp-youtube.js
  test/manual/amp-youtube-carousel.amp.html
Labels: cla: yes

#15022 Clarify css namespace in amp-components
  contributing/building-an-amp-extension.md
Labels: cla: yes

#15015 ✨📖✅Allow setting initial date. Document. Vsync. Test.
  examples/date-picker.amp.html
  examples/date-picker.json
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker.js
  extensions/amp-date-picker/amp-date-picker.md
Labels: cla: yes

#14939 Subscriptions: UI Decoration delegation
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/local-subscription-platform-renderer.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/platform-store.js
  extensions/amp-subscriptions/0.1/service-adapter.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-local-subscription-rendering.js
  extensions/amp-subscriptions/0.1/test/test-platform-store.js
  extensions/amp-subscriptions/0.1/test/test-service-adapter.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#15042 Updates amp-geo docs with "availability" row
  extensions/amp-geo/amp-geo.md
Labels: cla: yes

#14837 XHR fetch when view first becomes visible
  src/service/xhr-impl.js
  test/functional/test-xhr.js
Labels: cla: yes

#14956 🐛 Remove trailing comma
  ads/kuadio.md
Labels: cla: yes

#15044 Add nainar@ as OWNER of components they have worked heavily on
  extensions/amp-facebook-comments/OWNERS.yaml
  extensions/amp-facebook-like/OWNERS.yaml
  extensions/amp-facebook/OWNERS.yaml
  extensions/amp-fx-collection/OWNERS.yaml
  extensions/amp-twitter/0.1/OWNERS.yaml
Labels: cla: yes

#15043 ✅ Fail tests that call `console error` when they are run during local dev
  build-system/pr-check.js
  build-system/tasks/karma.conf.js
  test/_init_tests.js
Labels: Related to: Flaky Tests, cla: yes

#15048 consent policy timeout doc change
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#15052 🏗 Profile `browserify.transform(babelify)` operations during `gulp build`
  gulpfile.js
Labels: Category: Tooling, cla: yes

#15050 consent policy: rename fallbackState to fallbackAction
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  test/manual/amp-consent.html
Labels: cla: yes

#15008 amp-consent integrations and availability
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#15012 amp-consent: Allow 'checkConsentHref' response override 'promptIfUnknownForGeoGroup' result
  build-system/app.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  test/manual/amp-consent-geo.html
Labels: cla: yes

#15061 ✨Disable auto-fullscreen for iframe players in iOS
  src/service/video-manager-impl.js
  test/functional/test-video-rotate-to-fullscreen.js
Labels: cla: yes

#15068 🐛Prevent null reference error
  src/service/action-impl.js
Labels: cla: yes

#15046 amp-ad-exit click delay interval start based on preformance timing event
  extensions/amp-ad-exit/0.1/config.js
  extensions/amp-ad-exit/0.1/filters/click-delay.js
  extensions/amp-ad-exit/0.1/filters/factory.js
  extensions/amp-ad-exit/0.1/test/filters/test-click-delay.js
  extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
Labels: cla: yes

#14993 🐛Update Scroll amp-access extension placeholder CSS to match current UI
  extensions/amp-access-scroll/0.1/amp-access-scroll.css
Labels: cla: yes

#15090 Add amp-ad-exit to ini-load element exclusion list
  src/friendly-iframe-embed.js
  test/functional/test-friendly-iframe-embed.js
Labels: cla: yes

#15075 🏗 Ensure private fields don't use bad annotations.
  build-system/eslint-rules/unused-private-field.js
Labels: cla: yes

#15076 🐛 Make the use of `compact` mode for `babelify` consistent across all file sizes
  gulpfile.js
Labels: Type: Bug, cla: yes

#15096 SwG release 0.1.22.11
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#15069 Update FIE's unused privates
  src/friendly-iframe-embed.js
Labels: cla: yes

#15062 Story consent component.
  examples/amp-story/consent.html
  extensions/amp-story/1.0/amp-story-consent.css
  extensions/amp-story/1.0/amp-story-consent.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story-consent.js
  gulpfile.js
  src/service/action-impl.js
  test/functional/test-action.js
Labels: cla: yes

#14648 Remove timer-based delay in <amp-install-serviceworker>
  extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js
  extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
Labels: cla: yes

#15066 🏗 Add `gulp bundle-size` + assorted improvements
  build-system/pr-check.js
  build-system/tasks/bundle-size.js
  build-system/tasks/index.js
  gulpfile.js
Labels: Category: Tooling, cla: yes

#15078 📖Document promptIfUnknownForGeoGroup
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#14981 Select media through iframe boundary
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#15074 ✨ Add `firstPlay` event
  spec/amp-actions-and-events.md
  src/service/video-manager-impl.js
Labels: cla: yes

#15047 Fix todos for images and clarify date picker docs
  extensions/amp-date-picker/amp-date-picker.md
  extensions/amp-date-picker/img/amp-date-picker-lightbox-fullscreen.png
  extensions/amp-date-picker/img/amp-date-picker-range-static.png
  extensions/amp-date-picker/img/amp-date-picker-single-static.png
Labels: cla: yes

#15092 🏗 Eliminate unnecessary global tools from the AMP toolchain
  ads/README.md
  build-system/check-package-manager.js
  build-system/tasks/update-packages.js
  contributing/DEVELOPING.md
  contributing/building-an-amp-extension.md
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
  contributing/good-first-issues-template.md
Labels: Category: Tooling, cla: yes

#14975 Update srcset / sizes to match browser behavior experiment
  build-system/tasks/bundle-size.js
  builtins/amp-img.js
  test/functional/test-amp-img.js
  test/manual/amp-img.amp.html
  tools/experiments/experiments.js
Labels: cla: yes

#15081 Check if event target is an element before asserting that it is (focus-history)
  src/focus-history.js
Labels: cla: yes

#15109 🏗 More error checking, fix doc links
  build-system/check-package-manager.js
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
Labels: Category: Tooling, cla: yes

#15111 🐛 Use `compact=false` for `babelify` during `gulp dep-check` and `gulp test`
  build-system/tasks/bundle-size.js
  build-system/tasks/dep-check.js
  build-system/tasks/karma.conf.js
Labels: Category: Tooling, cla: yes

#15112 🐛🏗 Formatting fix for `bundlesize` output
  build-system/tasks/bundle-size.js
Labels: Category: Tooling, Type: Bug, cla: yes

#15120 🐛✅ Explicitly specify `browserify` module paths relative to a base directory while running tests
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test.js
Labels: Related to: Flaky Tests, Type: Bug, cla: yes

#15060 ✨ amp-ima-video: Add consent blocking.
  ads/google/imaVideo.js
  extensions/amp-ima-video/0.1/amp-ima-video.js
  extensions/amp-ima-video/0.1/test/test-amp-ima-video.js
  extensions/amp-ima-video/consent-blocking.md
Labels: cla: yes

#15107 amp-video: Make sure rejected autoplay detection promises are caught
  src/utils/video.js
Labels: cla: yes

#15105 Fix for instagram API not returning height=height+padding values anymore
  extensions/amp-instagram/0.1/amp-instagram.js
  extensions/amp-instagram/0.1/test/test-amp-instagram.js
Labels: cla: yes

#15106 🐛Add date-template and info-template to amp-date-picker validation.
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.html
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out
  extensions/amp-date-picker/validator-amp-date-picker.protoascii
  extensions/amp-mustache/validator-amp-mustache.protoascii
Labels: cla: yes

#15080 Force set amp-lightbox-gallery buttons to content-box sizing
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
Labels: cla: yes

#14816 🚮 Cleanup a4a/performance's private fields
  ads/google/a4a/performance.js
Labels: cla: yes

#15128 `console.error` cleanup: Remove unnecessary usage of `allowConsoleError`
  build-system/tasks/runtime-test.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
  extensions/amp-access/0.1/test/test-access-expr.js
  extensions/amp-access/0.1/test/test-amp-access.js
  extensions/amp-access/0.1/test/test-iframe-messenger.js
  extensions/amp-access/0.1/test/test-jwt.js
  extensions/amp-analytics/0.1/test/test-iframe-transport-client.js
  extensions/amp-analytics/0.1/test/test-instrumentation.js
  extensions/amp-animation/0.1/test/test-css-expr.js
  extensions/amp-bind/0.1/test/test-bind-expression.js
  extensions/amp-brightcove/0.1/test/test-amp-brightcove.js
  extensions/amp-experiment/0.1/test/test-amp-experiment.js
  extensions/amp-experiment/0.1/test/test-variant.js
  extensions/amp-gist/0.1/test/test-amp-gist.js
  extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
  extensions/amp-mustache/0.1/test/test-amp-mustache.js
  extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js
  extensions/amp-ooyala-player/0.1/test/test-amp-ooyala.js
  extensions/amp-reddit/0.1/test/test-amp-reddit.js
  extensions/amp-soundcloud/0.1/test/test-amp-soundcloud.js
  extensions/amp-subscriptions/0.1/test/test-actions.js
  extensions/amp-video/0.1/test/test-amp-video.js
  extensions/amp-vimeo/0.1/test/test-amp-vimeo.js
  extensions/amp-vine/0.1/test/test-amp-vine.js
  extensions/amp-web-push/0.1/test/test-web-push-config.js
  extensions/amp-wistia-player/0.1/test/test-amp-wistia-player.js
  test/functional/test-3p-environment.js
  test/functional/test-3p.js
  test/functional/test-ad-cid.js
  test/functional/test-amp-context.js
  test/functional/test-amp-pixel.js
  test/functional/test-ampdoc.js
  test/functional/test-batched-json.js
  test/functional/test-cid.js
  test/functional/test-cookies.js
  test/functional/test-custom-element.js
  test/functional/test-error.js
  test/functional/test-extensions.js
  test/functional/test-integration.js
  test/functional/test-json.js
  test/functional/test-log.js
  test/functional/test-object.js
  test/functional/test-origin-experiments.js
  test/functional/test-polyfill-object-assign.js
  test/functional/test-render-delaying-services.js
  test/functional/test-template.js
  test/functional/test-viewer-cid-api.js
  test/functional/test-viewer.js
  test/functional/utils/test-base64.js
  test/functional/utils/test-priority-queue.js
  test/functional/web-worker/test-amp-worker.js
Labels: Related to: Flaky Tests, cla: yes

#15101 Migrate amp-story-consent away from position: fixed.
  extensions/amp-story/1.0/amp-story-consent.css
  extensions/amp-story/1.0/amp-story-consent.js
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#15110 Create and lint for Promise helpers
  .eslintrc
  build-system/eslint-rules/resolve-inside-promise-resolver.js
  build-system/tasks/bundle-size.js
  src/animation.js
  src/promise.js
Labels: cla: yes

#15140 ♻️ Use tryResolve in URL Expander
  src/service/url-expander/expander.js
Labels: cla: yes

#15049 New analytics for amp-story-auto-ads
  examples/amp-story-auto-ads.amp.html
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
Labels: cla: yes

#15137 AMP Story consent i18n.
  extensions/amp-story/1.0/amp-story-consent.js
  extensions/amp-story/1.0/test/test-amp-story-consent.js
Labels: cla: yes

#15129 Subscriptions: fixing examples
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  src/sanitizer.js
  validator/validator-main.protoascii
Labels: cla: yes

#15144 🐛 update element in fixed layer when height change
  extensions/amp-consent/0.1/amp-consent.js
  test/manual/amp-consent.html
Labels: cla: yes

#14585 Protect from two errors
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
Labels: cla: yes

#14917 ✨ Add dirtyElement method to Resources
  src/service/resources-impl.js
Labels: cla: yes

#15009 Make dynamic CORS fail without opt-in
  src/batched-json.js
  src/service/url-replacements-impl.js
  test/functional/test-batched-json.js
  test/functional/test-url-replacements.js
Labels: cla: yes

#15160 Update bundle-size.js
  build-system/tasks/bundle-size.js
Labels: cla: yes

#15159 Add Layers experiment
  tools/experiments/experiments.js
Labels: cla: yes

#15156 Whitelist origins for amp-story: week of 2018-05-08.
  extensions/amp-story/0.1/origin-whitelist.js
  extensions/amp-story/1.0/origin-whitelist.js
Labels: cla: yes

#15164 Copy the amp-story-consent component from 1.0 to 0.1.
  extensions/amp-story/0.1/amp-story-consent.css
  extensions/amp-story/0.1/amp-story-consent.js
  extensions/amp-story/0.1/amp-story.css
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/test/test-amp-story-consent.js
  extensions/amp-story/0.1/test/validator-amp-story-consent.html
  extensions/amp-story/0.1/test/validator-amp-story-consent.out
  gulpfile.js
Labels: cla: yes

#15151 amp-ad-exit allow for disabling default protections
  extensions/amp-ad-exit/0.1/amp-ad-exit.js
  extensions/amp-ad-exit/0.1/config.js
  extensions/amp-ad-exit/0.1/filters/click-delay.js
  extensions/amp-ad-exit/0.1/filters/click-location.js
  extensions/amp-ad-exit/0.1/filters/filter.js
  extensions/amp-ad-exit/0.1/filters/inactive-element.js
  extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
  extensions/amp-ad-exit/amp-ad-exit.md
Labels: cla: yes

#15141 Fix carousel duplicate thumbnail bug
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#15152 Improvements to doc
  extensions/amp-date-picker/amp-date-picker.md
  extensions/amp-date-picker/img/amp-date-picker-basic.png
  extensions/amp-date-picker/img/amp-date-picker-range-static.png
  extensions/amp-date-picker/img/amp-date-picker-single-static.png
Labels: cla: yes

#15033 ♻️🚮 Upgrade amp-story-bookend to extend from BaseElement
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/bookend/bookend-element.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#15170 amp-bind: Measure impact of reducing binding limit
  extensions/amp-bind/0.1/bind-impl.js
Labels: cla: yes

#14512 ✨ New ad type: WPMedia
  3p/integration.js
  ads/_config.js
  ads/wpmedia.js
  ads/wpmedia.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: Category: Ads, cla: yes

#14186 Inline styles: Ignore fixed/sticky elements
  build-system/tasks/bundle-size.js
  src/service/fixed-layer.js
  test/functional/test-fixed-layer.js
Labels: cla: yes

#14791 Use content height for "near bottom" resize logic
  src/service/resources-impl.js
  test/functional/test-resources.js
Labels: cla: yes

#15180 bump bundle size
  build-system/tasks/bundle-size.js
Labels: cla: yes

#15175 Fast Fetch Doubleclick SRA allow fallback non-SRA on error
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
Labels: cla: yes

#15191 Whitelist amp-bind for amp4ads
  extensions/amp-bind/validator-amp-bind.protoascii
  validator/engine/validator_test.js
Labels: cla: yes

#15150 ✨ amp-next-page: Allow hiding of arbitrary elements in child pages
  examples/amp-next-page.amp.html
  extensions/amp-next-page/0.1/amp-next-page.css
  extensions/amp-next-page/0.1/config.js
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
  extensions/amp-next-page/0.1/test/test-config.js
Labels: cla: yes

#15187 ✨ amp-next-page: Relax position requirements for component
  extensions/amp-next-page/validator-amp-next-page.protoascii
Labels: cla: yes

#15196 Add amp-bind to list of amp4ads documentation of allowed extensions
  extensions/amp-a4a/amp-a4a-format.md
Labels: cla: yes

#15197 Validator Rollup
  extensions/amp-animation/0.1/test/validator-amp-animation.out
  extensions/amp-audio/0.1/test/validator-amp4ads-amp-audio.out
  extensions/amp-carousel/0.1/test/validator-amp-carousel.out
  extensions/amp-dailymotion/0.1/test/validator-amp-dailymotion.out
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out
  extensions/amp-experiment/0.1/test/validator-amp-experiment.out
  extensions/amp-izlesene/0.1/test/validator-amp-izlesene.out
  extensions/amp-lightbox-gallery/0.1/test/validator-amp-lightbox-gallery.out
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-live-list/0.1/test/validator-amp-live-list.out
  extensions/amp-mustache/0.1/test/validator-amp-mustache.out
  extensions/amp-mustache/validator-amp-mustache.protoascii
  extensions/amp-position-observer/0.1/test/validator-amp-position-observer.out
  extensions/amp-sidebar/0.1/test/validator-amp-sidebar.out
  extensions/amp-soundcloud/0.1/test/validator-amp-soundcloud.out
  extensions/amp-springboard-player/0.1/test/validator-amp-springboard-player.out
  extensions/amp-story/0.1/test/validator-amp-story-cta-layer-error.out
  extensions/amp-story/1.0/test/validator-amp-story-cta-layer-error.out
  extensions/amp-story/validator-amp-story.protoascii
  extensions/amp-timeago/0.1/test/validator-amp-timeago.out
  extensions/amp-video/0.1/test/validator-amp-video.out
  extensions/amp-vimeo/0.1/test/validator-amp-vimeo.out
  extensions/amp-youtube/0.1/test/validator-amp-youtube.out
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/testdata/amp4ads_feature_tests/extensions.out
  validator/testdata/feature_tests/custom_element_case.out
  validator/testdata/feature_tests/duplicate_attribute.out
  validator/testdata/feature_tests/mandatory_dimensions.out
  validator/testdata/feature_tests/no_custom_js.html
  validator/testdata/feature_tests/no_custom_js.out
  validator/testdata/feature_tests/regexps.out
  validator/testdata/feature_tests/several_errors.out
  validator/testdata/feature_tests/urls.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#15097 📖 Update ads doc for the context.getConsentState API.
  ads/README.md
Labels: cla: yes

#15182 ♻️ Use Deferred class in src
  build-system/tasks/bundle-size.js
  src/dom.js
  src/impression.js
  src/motion.js
  src/service.js
  src/service/ampdoc-impl.js
  src/service/extensions-impl.js
  src/service/history-impl.js
  src/service/resource.js
  src/service/template-impl.js
  src/service/viewer-impl.js
  src/service/vsync-impl.js
  src/utils/signals.js
Labels: cla: yes

#15178 Fix action whitelist error message and minor refactoring
  build-system/tasks/bundle-size.js
  src/custom-element.js
  src/service/action-impl.js
  src/service/standard-actions-impl.js
  test/functional/test-action.js
  test/functional/test-standard-actions.js
Labels: cla: yes

#14961 ✨ Implement video docking (minimize to corner)
  build-system/dep-check-config.js
  build-system/tasks/presubmit-checks.js
  css/amp.css
  css/video-autoplay.css
  css/video-docking.css
  gulpfile.js
  spec/amp-video-interface.md
  src/service/video-manager-impl.js
  src/service/video/docking.js
  src/service/video/install-autoplay-styles.js
  src/utils/video.js
  test/functional/test-video-docking.js
Labels: cla: yes

#15200 Ramp up amp-img-native-srcset experiment to 1%
  build-system/global-configs/canary-config.json
Labels: cla: yes

#15207 Add play/pause actions on <amp-audio>
  extensions/amp-audio/0.1/amp-audio.js
  extensions/amp-audio/0.1/test/test-amp-audio.js
  spec/amp-actions-and-events.md
Labels: cla: yes

#15209 Doc update to add RTC support for Fast Fetch
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#15179 🐛 Fix amp-story-bookend tests
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
Labels: cla: yes

#15221 🏗 Notify build cop when `master` goes red
  .travis.yml
Labels: cla: yes

#15208 Amp ad exit vendor dependency
  extensions/amp-ad-exit/0.1/config.js
  extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
  extensions/amp-ad-network-fake-impl/0.1/data/fake_amp_ad_with_iframe_transport.html
  extensions/amp-analytics/0.1/iframe-transport-vendors.js
  extensions/amp-analytics/0.1/test/test-vendors.js
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/integrating-analytics.md
Labels: cla: yes

#15215 🐛 amp-next-page: Fix handling of documents which are shorter than the viewport
  extensions/amp-next-page/0.1/next-page-service.js
Labels: cla: yes

#15212 🐛 amp-next-page: Fix PositionObserver error on loading failure
  extensions/amp-next-page/0.1/next-page-service.js
Labels: cla: yes

#15210 Add history to lightbox-gallery
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#15225 🏗 Make Travis email notifications less spammy
  .travis.yml
Labels: Category: Tooling, cla: yes

#15219 Using CSS Variables for the amp-story-consent component.
  examples/amp-story/consent.html
  extensions/amp-story/0.1/amp-story-consent.css
  extensions/amp-story/0.1/amp-story-consent.js
  extensions/amp-story/1.0/amp-story-consent.css
  extensions/amp-story/1.0/amp-story-consent.js
Labels: cla: yes

#15220 Remove unused OriginExperiments
  build-system/tasks/bundle-size.js
  src/experiments.js
  src/origin-experiments.js
  test/functional/test-experiments.js
  test/functional/test-origin-experiments.js
Labels: cla: yes

#15239 Fix max len lint issue for amp-next-page tes
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
Labels: cla: yes

#15223 ✅ Fail tests with unnecessary use of `allowConsoleError`
  test/_init_tests.js
Labels: cla: yes

#15205 🔥In case cache CID api is not opted in or failed, fallback to local generated CID.
  src/service/cid-impl.js
Labels: cla: yes

#15236 🏗 Notify when tests on `master` go from failing -> passing
  .travis.yml
Labels: Category: Tooling, cla: yes

#15228 🐛 Fix instances where `allowConsoleError` swallows return values
  extensions/amp-3q-player/0.1/test/test-amp-3q-player.js
  extensions/amp-app-banner/0.1/test/test-amp-app-banner.js
  extensions/amp-brid-player/0.1/test/test-amp-brid-player.js
  extensions/amp-byside-content/0.1/test/test-amp-byside-content.js
  extensions/amp-dailymotion/0.1/test/test-amp-dailymotion.js
  extensions/amp-gfycat/0.1/test/test-amp-gfycat.js
  extensions/amp-google-vrview-image/0.1/test/test-amp-google-vrview-image.js
  extensions/amp-hulu/0.1/test/test-amp-hulu.js
  extensions/amp-izlesene/0.1/test/test-amp-izlesene.js
  extensions/amp-jwplayer/0.1/test/test-amp-jwplayer.js
  extensions/amp-kaltura-player/0.1/test/test-amp-kaltura-player.js
  extensions/amp-o2-player/0.1/test/test-amp-o2-player.js
  extensions/amp-selector/0.1/test/test-amp-selector.js
  extensions/amp-social-share/0.1/test/test-amp-social-share.js
  extensions/amp-story/1.0/test/test-amp-story-cta-layer.js
  extensions/amp-vk/0.1/test/test-amp-vk.js
  extensions/amp-youtube/0.1/test/test-amp-youtube.js
  test/_init_tests.js
  test/functional/test-amp-pixel.js
Labels: Type: Bug, cla: yes

#15245 Remove unnecessary gem `rspec-retry` from visual-diff.rb
  build-system/tasks/visual-diff.rb
Labels: cla: yes

#15254 🐛 Fix `yarn.lock`
  yarn.lock
Labels: cla: yes

#15222 Clean up code for actions in <amp-audio>
  extensions/amp-audio/0.1/amp-audio.js
  extensions/amp-audio/0.1/test/test-amp-audio.js
Labels: cla: yes

#15237 clean up dep-check sanitizer usage
  build-system/dep-check-config.js
Labels: cla: yes

#15153 ✨ Added Purch as vendor in callout-vendors.js
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#15246 Minor assert fixes to amp-fx
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js
Labels: cla: yes

#15244 ✨ add amp-geo-pending support
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-geo/0.1/test/test-amp-geo.js
  extensions/amp-geo/amp-geo.md
Labels: cla: yes

#14164 amp-ad Cedato AMP Ad provider updates
  ads/cedato.md
  examples/ads.amp.html
Labels: cla: yes

#15206 Fix width auto bug in amp-image-lightbox
  extensions/amp-image-lightbox/0.1/amp-image-lightbox.js
  extensions/amp-image-lightbox/0.1/test/test-amp-image-lightbox.js
  test/manual/amp-image-lightbox.amp.html
Labels: cla: yes

#15276 SwG release 0.1.22.12
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#15184 ♻️ Update extensions to use Deferred class
  build-system/eslint-rules/resolve-inside-promise-resolver.js
  extensions/amp-3q-player/0.1/amp-3q-player.js
  extensions/amp-access/0.1/amp-access-iframe.js
  extensions/amp-access/0.1/amp-access-source.js
  extensions/amp-access/0.1/amp-access-vendor.js
  extensions/amp-access/0.1/iframe-api/iframe-api.js
  extensions/amp-access/0.1/iframe-api/messenger.js
  extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
  extensions/amp-analytics/0.1/visibility-model.js
  extensions/amp-bodymovin-animation/0.1/amp-bodymovin-animation.js
  extensions/amp-brid-player/0.1/amp-brid-player.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-dailymotion/0.1/amp-dailymotion.js
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-ima-video/0.1/amp-ima-video.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js
  extensions/amp-ooyala-player/0.1/amp-ooyala-player.js
  extensions/amp-story/0.1/amp-story-page.js
  extensions/amp-story/0.1/animation.js
  extensions/amp-story/0.1/media-tasks.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/animation.js
  extensions/amp-story/1.0/media-tasks.js
  extensions/amp-user-notification/0.1/amp-user-notification.js
  extensions/amp-wistia-player/0.1/amp-wistia-player.js
  extensions/amp-youtube/0.1/amp-youtube.js
Labels: cla: yes

#15256 🏗 During PR checks, lint only the files in the PR, and flag errors instead of warnings
  .eslintrc
  .eslintrc-strict
  build-system/tasks/lint.js
  src/.eslintrc
Labels: Category: Tooling, cla: yes

#15213 ✨ amp-next-page: Reuse amp-analytics config from parent document on all children
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
Labels: cla: yes

#15287 Whitelist origins for amp-story: week of 2018-05-14
  extensions/amp-story/0.1/origin-whitelist.js
  extensions/amp-story/1.0/origin-whitelist.js
Labels: cla: yes

#15294 🏗 Use `eslint-plugin-jsdoc` instead of the built in `valid-jsdoc`
  .eslintrc
  .eslintrc-strict
  build-system/tasks/lint.js
  package.json
  yarn.lock
Labels: cla: yes

#15289 📖 Fix incorrect JSDoc annotations in `ads/`
  ads/24smi.js
  ads/_a4a-config.js
  ads/adfox.js
  ads/adgeneration.js
  ads/adhese.js
  ads/adocean.js
Labels: Related to: Documentation, cla: yes

#15298 🏗 Refactor `lint.js` and update `jsdoc/check-tag-names` rule
  .eslintrc
  build-system/tasks/lint.js
Labels: Category: Tooling, cla: yes

#15307 Support lint on specified files: gulp lint --files=a.js,b.js,c.js
  build-system/tasks/lint.js
Labels: cla: yes

#15281 🐛amp-consent scheduleLayout for prompt UI elements
  extensions/amp-consent/0.1/amp-consent.js
Labels: cla: yes

#15174 Remove the story scrollbar on iOS iframes.
  extensions/amp-story/0.1/amp-story.css
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#15288 ✅ Allow <amp-wistia-player rotate-to-fullscreen>
  extensions/amp-wistia-player/validator-amp-wistia-player.protoascii
Labels: cla: yes

#15203 Remove amp-bind logic from actions
  build-system/tasks/bundle-size.js
  extensions/amp-animation/0.1/amp-animation.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-bodymovin-animation/0.1/amp-bodymovin-animation.js
  extensions/amp-carousel/0.1/base-slides.js
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation.js
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-live-list/0.1/amp-live-list.js
  extensions/amp-position-observer/0.1/amp-position-observer.js
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-story/0.1/amp-story-consent.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/1.0/amp-story-consent.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-video-service/0.1/amp-video-service.js
  src/action-constants.js
  src/base-element.js
  src/document-submit.js
  src/service/action-impl.js
  src/service/standard-actions-impl.js
  src/service/video-manager-impl.js
  test/functional/test-action.js
  test/functional/test-standard-actions.js
Labels: cla: yes

#15226 add mutateElement to amp-geo for layers support.
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-geo/0.1/test/test-amp-geo.js
Labels: cla: yes

#15056 Fix amp-geo docs: s/AMPBind/AmpBind
  extensions/amp-geo/amp-geo.md
Labels: cla: yes

#15277 Add basic integration tests: lightbox open and close
  extensions/amp-lightbox-gallery/0.1/test/integration/test-amp-lightbox-gallery.js
Labels: cla: yes

#15306 Skip analytics test in test-amp-next-page.js
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
Labels: cla: yes

#15316 Temporarily downgrade `jsdoc/require-param` to warning mode
  .eslintrc-strict
  build-system/tasks/lint.js
Labels: cla: yes
