Repository ampproject/amphtml, pull requests merged in 2018-06, with the labels that each got.

#15713 ♻️ Remove src/url requirement from amp-install-serviceworker
  extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js
  extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
Labels: cla: yes

#15614 ♻️ Move isSecureUrl into URL Service
  build-system/eslint-rules/vsync.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/amp-ad-utils.js
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/test-callout-vendors.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-analytics/0.1/test/test-vendors.js
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js
  extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
  src/service/resources-impl.js
  src/service/url-impl.js
  src/url.js
  test/functional/test-url.js
Labels: cla: yes

#15599 🚀 Appnexus prebid server callout respect multisize
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#15422 Allow canonical adsense to work via new frame get
  ads/google/a4a/experiment-utils.js
  ads/google/a4a/utils.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-ad-network-adsense-impl/0.1/adsense-a4a-config.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-adsense-a4a-config.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/doubleclick-a4a-config.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-a4a-config.js
  extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
Labels: cla: yes

#13738 ✨ Add Relap v7 widget support
  ads/relap.js
  ads/relap.md
Labels: cla: yes

#15726 ✨ geo service enhancement
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-geo/0.1/test/test-amp-geo.js
Labels: cla: yes

#15084 Add new AD network - Realclick
  3p/integration.js
  ads/_config.js
  ads/realclick.js
  ads/realclick.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#15604 Throw user error when promptUI and postPromptUI are not scoped
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
Labels: cla: yes

#15682 Add integration tests for <amp-fx="fly-in-{bottom,left,right}">
  extensions/amp-fx-collection/0.1/test/integration/test-amp-fx-fly-in.js
Labels: cla: yes

#15762 Skip Safari tests and use Safari 11.0 for 'latest' for now
  build-system/pr-check.js
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test.js
Labels: cla: yes

#15771 Only delegate login actions for auto servcie
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Labels: cla: yes

#15760 Allow `<amp-social-share>` to specify the target in which to open anchor
  examples/social-share.amp.html
  extensions/amp-social-share/0.1/amp-social-share.js
  extensions/amp-social-share/0.1/test/test-amp-social-share.js
  extensions/amp-social-share/amp-social-share.md
Labels: cla: yes

#15749 Fix test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-iframe-transport-message-queue.js
  extensions/amp-analytics/0.1/test/test-iframe-transport.js
Labels: cla: yes

#15777 Remove the AMP Validator release changelog
  validator/CHANGELOG.md
Labels: Category: Validator, cla: yes

#15781 Doubleclick sticky sra fix
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
Labels: cla: yes

#15714 Add integration tests for actions
  build-system/eslint-rules/no-style-property-setting.js
  test/fixtures/actions.html
  test/integration/test-actions.js
  testing/iframe.js
Labels: cla: yes

#14609 Medyanet Ad Network Update for Domain Data
  ads/medyanet.js
  ads/medyanet.md
  examples/ads.amp.html
Labels: cla: yes

#15681 Resolve url macros synchronously
  build-system/tasks/bundle-size.js
  src/service/url-expander/expander.js
  src/service/url-replacements-impl.js
  test/functional/url-expander/test-expander.js
Labels: cla: yes

#15754 Ramp up native srcset experiment to 70%
  build-system/global-configs/prod-config.json
Labels: cla: yes

#15720 ✨ adds title to portrait component in amp-story-bookend and change expected fields in articles
  examples/amp-story/bookendv1.json
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/bookend/components/article.js
  extensions/amp-story/1.0/bookend/components/landscape.js
  extensions/amp-story/1.0/bookend/components/portrait.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
Labels: cla: yes

#15784 🐛 Add micro-task delay to avoid race.
  src/element-service.js
Labels: cla: yes

#15746 Disambiguate amp-install-sw docs
  extensions/amp-install-serviceworker/amp-install-serviceworker.md
Labels: cla: yes

#15798 Attempt to enable Safari 11.0 on SL
  build-system/pr-check.js
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test.js
Labels: cla: yes

#15808 Fix master from bundle size after #15784
  build-system/tasks/bundle-size.js
Labels: cla: yes

#15337 Add TextHighlighter to amp-viewer-integration
  build-system/tasks/presubmit-checks.js
  extensions/amp-viewer-integration/0.1/amp-viewer-integration.js
  extensions/amp-viewer-integration/0.1/findtext.js
  extensions/amp-viewer-integration/0.1/highlight-handler.js
  extensions/amp-viewer-integration/0.1/test/test-findtext.js
  extensions/amp-viewer-integration/0.1/test/test-highlight-handler.js
Labels: cla: yes

#15785 📖 amp-html-components.md: Fix broken links
  spec/amp-html-components.md
Labels: cla: yes

#15694 amp-list: Measure effect of disabling pre-gesture evaluation
  examples/bind/list.amp.html
  extensions/amp-bind/0.1/bind-impl.js
Labels: cla: yes

#15817 Lower-case amp-3d-gltf attribute names.
  extensions/amp-3d-gltf/0.1/test/validator-amp-3d-gltf.html
  extensions/amp-3d-gltf/0.1/test/validator-amp-3d-gltf.out
  extensions/amp-3d-gltf/validator-amp-3d-gltf.protoascii
  validator/engine/validator_test.js
Labels: Category: Validator, cla: yes

#15815 🐛 Prevent double / async errors from being thrown during tests
  test/_init_tests.js
Labels: Category: Tooling, Related to: Flaky Tests, cla: yes

#15770 Subscriptions: propagate URL vars for ACCESS_READER_ID and AUTHDATA
  build-system/tasks/bundle-size.js
  build-system/tasks/presubmit-checks.js
  examples/amp-subscriptions.amp.html
  extensions/amp-access/0.1/access-vars.js
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-subscriptions/0.1/actions.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/analytics.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/platform-store.js
  extensions/amp-subscriptions/0.1/service-adapter.js
  extensions/amp-subscriptions/0.1/test/test-actions.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-analytics.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-platform-store.js
  extensions/amp-subscriptions/0.1/test/test-service-adapter.js
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  src/service/url-replacements-impl.js
  src/services.js
  test/_init_tests.js
  test/functional/test-url-replacements.js
Labels: cla: yes

#15804 Doubleclick remove fast fetch upgrade predicate
  ads/_a4a-config.js
  ads/_config.js
  ads/google/a4a/google-data-reporter.js
  ads/google/a4a/test/test-google-data-reporter.js
  ads/google/a4a/utils.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/doubleclick-a4a-config.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-a4a-config.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
  test/functional/3p/test-ampcontext-integration.js
Labels: cla: yes

#15829 🐛 fix alpha attribute
  extensions/amp-3d-gltf/validator-amp-3d-gltf.protoascii
Labels: cla: yes

#15836 Fix flaky performance test on Safari
  test/functional/test-performance.js
Labels: cla: yes

#15835 Fire amp-ini-load event/postMessage on inabox ini-load event
  src/inabox/amp-inabox.js
  src/inabox/utils.js
  test/functional/inabox/test-utils.js
Labels: cla: yes

#15839 Remove flaky/non-functional integration tests
  extensions/amp-3d-gltf/0.1/test/integration/test-amp-3d-gltf.js
  extensions/amp-bodymovin-animation/0.1/test/integration/test-amp-bodymovin-animation.js
Labels: cla: yes

#15747 Add sample instructions for modifying code via content-scripts
  testing/local-amp-chrome-extension/README.md
Labels: cla: yes

#15833 Add DoubleClick documentations for Single Page Ads
  extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
  extensions/amp-ad-network-doubleclick-impl/single-page-ad.md
Labels: cla: yes

#15750 🚀 Autoplay with PositionObserver
  build-system/dep-check-config.js
  build-system/tasks/presubmit-checks.js
  css/video-autoplay.css
  extensions/amp-video-service/0.1/amp-video-service.js
  src/service/position-observer/position-observer-impl.js
  src/service/video-service-interface.js
  src/service/video-service-sync-impl.js
  src/service/video/autoplay.js
  test/functional/test-video-autoplay.js
Labels: cla: yes

#13472 🐛 Fix extension generator name in validation file
  build-system/tasks/extension-generator/index.js
Labels: cla: yes

#15840 ♻️ Remove src/url requirements from amp-next-page
  extensions/amp-next-page/0.1/amp-next-page.js
  extensions/amp-next-page/0.1/config.js
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
  extensions/amp-next-page/0.1/test/test-config.js
Labels: cla: yes

#15823 Fix carousel scroll on unlayout race condition trying to access non-existant slide
  extensions/amp-carousel/0.1/slidescroll.js
  test/manual/amp-lightbox-carousel.amp.html
Labels: cla: yes

#15841 Whitelist origins for amp-story: week of 2018-06-05
  extensions/amp-story/0.1/origin-whitelist.js
  extensions/amp-story/1.0/origin-whitelist.js
Labels: cla: yes

#15842 🐛 Prevent setting min/max width/height on standalone amp-story elements
  extensions/amp-story/0.1/amp-story.css
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#15465 📖 Introduces documentation for new bookend components.
  extensions/amp-story/amp-story.md
  extensions/amp-story/img/amp-story-bookend-component-cta-links.png
  extensions/amp-story/img/amp-story-bookend-component-heading.png
  extensions/amp-story/img/amp-story-bookend-component-landscape.png
  extensions/amp-story/img/amp-story-bookend-component-portrait.png
  extensions/amp-story/img/amp-story-bookend-component-small.png
  extensions/amp-story/img/amp-story-bookend-component-textbox.png
Labels: cla: yes

#15838 SwG release 0.1.22.13
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#15303 Noddus ad-tech integration
  3p/integration.js
  ads/_config.js
  ads/noddus.js
  ads/noddus.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#15692 ♻️ Remove src/url requirement from amp-app-banner
  extensions/amp-app-banner/0.1/amp-app-banner.js
  extensions/amp-app-banner/0.1/test/test-amp-app-banner.js
Labels: cla: yes

#15855 🏗 Reinstate verification of Percy builds during PR checks
  build-system/pr-check.js
Labels: Category: Tooling, cla: yes

#15595 Refactor Real Time Config code
  build-system/amp.extern.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
Labels: cla: yes

#15761 ♻️ adds support for bookend config v1.0 in amp story v0.1.
  extensions/amp-story/0.1/amp-story-bookend.js
  extensions/amp-story/0.1/amp-story-share.js
  extensions/amp-story/0.1/related-articles.js
Labels: cla: yes

#15558 ✨Adds AMP-to-AMP linking support in amp-story bookend components
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/bookend/bookend-component.js
  extensions/amp-story/1.0/bookend/components/article.js
  extensions/amp-story/1.0/bookend/components/bookend-component-interface.js
  extensions/amp-story/1.0/bookend/components/cta-link.js
  extensions/amp-story/1.0/bookend/components/heading.js
  extensions/amp-story/1.0/bookend/components/landscape.js
  extensions/amp-story/1.0/bookend/components/portrait.js
  extensions/amp-story/1.0/bookend/components/text-box.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
Labels: cla: yes

#15832 amp-3d-gltf: fix src attribute
  3p/3d-gltf/viewer.js
  extensions/amp-3d-gltf/0.1/amp-3d-gltf.js
Labels: cla: yes

#15860 amp-3d-gltf: fix test
  extensions/amp-3d-gltf/0.1/test/integration/test-amp-3d-gltf.js
  extensions/amp-3d-gltf/0.1/test/test-amp-3d-gltf.js
Labels: cla: yes

#15861 📖Update doc to reflect Fluid status beta->launched
  extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
Labels: cla: yes

#15820 Avoid sanitizing 'on' attr with DOMPurify
  src/sanitizer.js
  test/functional/test-sanitizer.js
Labels: cla: yes

#15737 🌐 Add translations for new batch of strings
  extensions/amp-story/1.0/_locales/ar.js
  extensions/amp-story/1.0/_locales/de.js
  extensions/amp-story/1.0/_locales/default.js
  extensions/amp-story/1.0/_locales/en-GB.js
  extensions/amp-story/1.0/_locales/es-419.js
  extensions/amp-story/1.0/_locales/es.js
  extensions/amp-story/1.0/_locales/fr-CA.js
  extensions/amp-story/1.0/_locales/fr.js
  extensions/amp-story/1.0/_locales/hi.js
  extensions/amp-story/1.0/_locales/id.js
  extensions/amp-story/1.0/_locales/it.js
  extensions/amp-story/1.0/_locales/ja.js
  extensions/amp-story/1.0/_locales/ko.js
  extensions/amp-story/1.0/_locales/nl.js
  extensions/amp-story/1.0/_locales/no.js
  extensions/amp-story/1.0/_locales/pt-BR.js
  extensions/amp-story/1.0/_locales/pt.js
  extensions/amp-story/1.0/_locales/ru.js
  extensions/amp-story/1.0/_locales/tr.js
  extensions/amp-story/1.0/_locales/vi.js
  extensions/amp-story/1.0/_locales/zh-TW.js
  extensions/amp-story/1.0/_locales/zh.js
Labels: cla: yes

#15849 🚮 Gdpr Update: Removing Unnecessary GDPR Macros
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#15873 Validator rollup
  extensions/amp-3d-gltf/0.1/test/validator-amp-3d-gltf.html
  extensions/amp-3d-gltf/0.1/test/validator-amp-3d-gltf.out
  extensions/amp-animation/validator-amp-animation.protoascii
  extensions/amp-audio/validator-amp-audio.protoascii
  extensions/amp-carousel/validator-amp-carousel.protoascii
  extensions/amp-next-page/validator-amp-next-page.protoascii
  validator/validator-main.protoascii
  validator/validator_gen_js.py
Labels: Category: Validator, cla: yes

#15766 Fix test-integration.js
  test/functional/test-integration.js
Labels: cla: yes

#15869 🏗 Enable amp-story-v1 experiment in canary and production
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  build-system/tasks/bundle-size.js
Labels: cla: yes

#15872 ♻️ Port amp-story info dialog to 1.0
  extensions/amp-story/1.0/amp-story-info-dialog.css
  extensions/amp-story/1.0/amp-story-info-dialog.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story-info-dialog.js
  extensions/amp-story/1.0/test/test-amp-story-share-menu.js
  extensions/amp-story/1.0/test/test-amp-story-store-service.js
  extensions/amp-story/1.0/test/test-amp-story.js
  gulpfile.js
Labels: cla: yes

#15739 ♻️ Remove once()
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-video/0.1/test/test-amp-video.js
  test/_init_tests.js
Labels: cla: yes

#15527 ♻️ Extract common video iframe helpers
  extensions/amp-3q-player/0.1/amp-3q-player.js
  extensions/amp-brid-player/0.1/amp-brid-player.js
  extensions/amp-brid-player/0.1/test/test-amp-brid-player.js
  extensions/amp-brightcove/0.1/amp-brightcove.js
  extensions/amp-dailymotion/0.1/amp-dailymotion.js
  extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js
  extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js
  extensions/amp-ooyala-player/0.1/amp-ooyala-player.js
  extensions/amp-vimeo/0.1/amp-vimeo.js
  extensions/amp-wistia-player/0.1/amp-wistia-player.js
  extensions/amp-youtube/0.1/amp-youtube.js
  extensions/amp-youtube/0.1/test/test-amp-youtube.js
  src/iframe-video.js
  test/_init_tests.js
Labels: cla: yes

#15874 Stories paused state, and state machine.
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
Labels: cla: yes

#15676 ✨Add New Ads Network - Epeex
  3p/integration.js
  ads/_config.js
  ads/epeex.js
  ads/epeex.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#15876 Update sf docs
  extensions/amp-ad-network-doubleclick-impl/safeframe.md
Labels: cla: yes

#15881 Fixing the consent ID used by amp-story-consent.
  examples/amp-story/consent.html
  extensions/amp-story/0.1/amp-story-consent.js
  extensions/amp-story/0.1/test/test-amp-story-consent.js
  extensions/amp-story/1.0/amp-story-consent.js
  extensions/amp-story/1.0/test/test-amp-story-consent.js
Labels: cla: yes

#15890 Update path and params for wisteria ad.
  ads/wisteria.js
Labels: cla: yes

#15831 🐛 amp-next-page: Fix trying to rewrite canonical URLs to cache URLs when it shouldn't
  extensions/amp-next-page/0.1/config.js
  extensions/amp-next-page/0.1/test/test-config.js
Labels: cla: yes

#15896 Update whitelist: 2018-06-07
  extensions/amp-story/0.1/origin-whitelist.js
  extensions/amp-story/1.0/origin-whitelist.js
Labels: cla: yes

#15895 Replace A4A with AMPHTML ad
  extensions/amp-ad-exit/amp-ad-exit.md
Labels: cla: yes

#15724 Allow publisher defined consent policy
  build-system/tasks/bundle-size.js
  examples/amp-consent.amp.html
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  src/custom-element.js
  test/functional/test-custom-element.js
Labels: cla: yes

#15900 Docs - add links to ABE demos
  extensions/amp-call-tracking/amp-call-tracking.md
  extensions/amp-facebook-comments/amp-facebook-comments.md
  extensions/amp-facebook-like/amp-facebook-like.md
  extensions/amp-facebook-page/amp-facebook-page.md
  extensions/amp-google-vrview-image/amp-google-vrview-image.md
  extensions/amp-reddit/amp-reddit.md
  extensions/amp-timeago/amp-timeago.md
Labels: cla: yes

#15899 Fixing the bookend article layout.
  extensions/amp-story/1.0/bookend/components/article.js
Labels: cla: yes

#15897 Add a prompt consent button in the bookend.
  examples/amp-story/consent.html
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/amp-story-consent.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
  extensions/amp-story/1.0/test/test-amp-story-consent.js
Labels: cla: yes

#15646 Add consentHandlingOverride flag to ezoic ampad
  ads/_config.js
  ads/ezoic.md
Labels: cla: yes

#15901 Update docs for doubleclick in stamp.
  extensions/amp-ad-network-doubleclick-impl/single-page-ad.md
  extensions/amp-story/amp-story-ads.md
Labels: cla: yes

#15880 Fix getAdContainer potential crash when the body element is called <amp-body>
  src/ad-helper.js
Labels: Category: Ads, Category: PWA, P1: High Priority, cla: yes

#15905 Add a prompt consent button in the v0.1 bookend.
  extensions/amp-story/0.1/amp-story-bookend.css
  extensions/amp-story/0.1/amp-story-bookend.js
  extensions/amp-story/0.1/amp-story-consent.js
  extensions/amp-story/0.1/amp-story-store-service.js
  extensions/amp-story/0.1/test/test-amp-story-consent.js
Labels: cla: yes

#15779 Add ability to not trigger amp-position-observer after first iteration
  extensions/amp-position-observer/0.1/amp-position-observer.js
  extensions/amp-position-observer/0.1/test/test-amp-position-observer.js
  extensions/amp-position-observer/0.1/test/validator-amp-position-observer.html
  extensions/amp-position-observer/0.1/test/validator-amp-position-observer.out
  extensions/amp-position-observer/amp-position-observer.md
  extensions/amp-position-observer/validator-amp-position-observer.protoascii
Labels: cla: yes

#15910 Adding translation keys for the bookend prompt consent link.
  extensions/amp-story/0.1/_locales/default.js
  extensions/amp-story/0.1/_locales/en.js
  extensions/amp-story/0.1/amp-story-bookend.js
  extensions/amp-story/0.1/localization.js
  extensions/amp-story/1.0/_locales/default.js
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/localization.js
Labels: cla: yes

#15824 ✨Create amp-drive-viewer behind experiment
  build-system/tasks/bundle-size.js
  examples/google-document-embed.amp.html
  extensions/amp-google-document-embed/0.1/amp-google-document-embed.js
  extensions/amp-google-document-embed/0.1/test/test-amp-google-document-embed.js
  extensions/amp-google-document-embed/0.1/test/validator-amp-google-document-embed.html
  extensions/amp-google-document-embed/0.1/test/validator-amp-google-document-embed.out
  extensions/amp-google-document-embed/amp-google-document-embed.md
  extensions/amp-google-document-embed/validator-amp-google-document-embed.protoascii
  gulpfile.js
  src/layout.js
  tools/experiments/experiments.js
Labels: cla: yes

#15902 Specify error reporting url for media.net RTC
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#15908 Deprecate dismiss consent translation key.
  extensions/amp-story/0.1/_locales/en.js
  extensions/amp-story/0.1/localization.js
  extensions/amp-story/1.0/_locales/ar.js
  extensions/amp-story/1.0/_locales/de.js
  extensions/amp-story/1.0/_locales/default.js
  extensions/amp-story/1.0/_locales/en-GB.js
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/_locales/es-419.js
  extensions/amp-story/1.0/_locales/es.js
  extensions/amp-story/1.0/_locales/fr-CA.js
  extensions/amp-story/1.0/_locales/fr.js
  extensions/amp-story/1.0/_locales/hi.js
  extensions/amp-story/1.0/_locales/id.js
  extensions/amp-story/1.0/_locales/it.js
  extensions/amp-story/1.0/_locales/ja.js
  extensions/amp-story/1.0/_locales/ko.js
  extensions/amp-story/1.0/_locales/nl.js
  extensions/amp-story/1.0/_locales/no.js
  extensions/amp-story/1.0/_locales/pt-BR.js
  extensions/amp-story/1.0/_locales/pt.js
  extensions/amp-story/1.0/_locales/ru.js
  extensions/amp-story/1.0/_locales/tr.js
  extensions/amp-story/1.0/_locales/vi.js
  extensions/amp-story/1.0/_locales/zh-TW.js
  extensions/amp-story/1.0/_locales/zh.js
  extensions/amp-story/1.0/localization.js
Labels: cla: yes

#15846 Disallows `bookend-config-src` attr in `amp-story` tag
  extensions/amp-story-auto-ads/0.1/test/validator-amp-story-auto-ads.out
  extensions/amp-story/0.1/test/validator-amp-story-animations-error.out
  extensions/amp-story/0.1/test/validator-amp-story-animations.out
  extensions/amp-story/0.1/test/validator-amp-story-deprecated.out
  extensions/amp-story/0.1/test/validator-amp-story-reference-point.html
  extensions/amp-story/0.1/test/validator-amp-story-reference-point.out
  extensions/amp-story/0.1/test/validator-amp-story-video-error.html
  extensions/amp-story/0.1/test/validator-amp-story-video-error.out
  extensions/amp-story/0.1/test/validator-amp-story.html
  extensions/amp-story/0.1/test/validator-amp-story.out
  extensions/amp-story/1.0/test/validator-amp-story-animations-error.out
  extensions/amp-story/1.0/test/validator-amp-story-animations.out
  extensions/amp-story/1.0/test/validator-amp-story-bookend-error.html
  extensions/amp-story/1.0/test/validator-amp-story-bookend-error.out
  extensions/amp-story/1.0/test/validator-amp-story-deprecated.out
  extensions/amp-story/1.0/test/validator-amp-story-reference-point.html
  extensions/amp-story/1.0/test/validator-amp-story-reference-point.out
  extensions/amp-story/1.0/test/validator-amp-story-video-error.html
  extensions/amp-story/1.0/test/validator-amp-story-video-error.out
  extensions/amp-story/1.0/test/validator-amp-story.html
  extensions/amp-story/1.0/test/validator-amp-story.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#15917 amp-facebook-page resize to container width
  3p/facebook.js
Labels: cla: yes

#15929 Fixing bookend prompt consent margin when no config.
  extensions/amp-story/1.0/amp-story-bookend.css
Labels: cla: yes

#15889 ♻️Introduce more functionality to new expander.
  build-system/tasks/bundle-size.js
  src/service/url-expander/expander.js
  src/service/url-replacements-impl.js
  src/service/variable-source.js
  test/functional/test-navigation.js
  test/functional/url-expander/test-expander.js
Labels: cla: yes

#14532 AMPHTML Email Spec
  spec/amp-email-format.md
  spec/img/amp-email-mime-parts.png
Labels: cla: yes

#15903 Mute expected error: BLOCK_BY_CONSENT
  src/error.js
  test/functional/test-error.js
Labels: cla: yes

#15943 Update eslint jsdoc preference
  .eslintrc
  build-system/tasks/dep-check.js
  src/error.js
Labels: cla: yes

#15850 🐛Support fullscreening <video>s in <amp-twitter>
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-ima-video/0.1/amp-ima-video.js
  extensions/amp-reddit/0.1/amp-reddit.js
  extensions/amp-twitter/0.1/amp-twitter.js
  extensions/amp-twitter/0.1/test/test-amp-twitter.js
  src/3p-frame.js
Labels: cla: yes

#15930 ♻️ amp-carousel: obsolete flag clean up
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#15938 Deal with clashing presets in amp-fx gracefully
  examples/article-invalid-presets.amp.html
  extensions/amp-fx-collection/0.1/amp-fx-collection.js
  extensions/amp-fx-collection/amp-fx-collection.md
Labels: cla: yes

#15791 Scroll AMP doc to center highlighted elements in the viewport
  extensions/amp-viewer-integration/0.1/highlight-handler.js
  extensions/amp-viewer-integration/0.1/test/test-highlight-handler.js
  src/service/viewport/viewport-impl.js
Labels: cla: yes

#15936 🏗 Allow duplicate error messages in `expectAsyncConsoleError`
  extensions/amp-user-notification/0.1/test/test-amp-user-notification.js
  test/_init_tests.js
Labels: cla: yes

#15937 Add experiment to disable amp-story desktop UI
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/1.0/amp-story.js
  tools/experiments/experiments.js
Labels: cla: yes

#15954 Doubleclick experiment removing throttling for non-AMP creatives
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
Labels: cla: yes

#15853 🐛 Undo `hostname` change on Safari and re-enable testing on latest version
  ads/google/a4a/test/test-line-delimited-response-handler.js
  build-system/tasks/karma.conf.js
  test/functional/test-resources.js
Labels: Category: Tooling, P1: High Priority, cla: yes

#15877 🐛 make amp-geo use user().error() on bad json
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-geo/0.1/test/test-amp-geo.js
Labels: cla: yes

#15963 Fix more test-amp-analytics.js failures due to expected console errors.
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
Labels: cla: yes

#15914 📖 Create an issue template for Type: Release issues
  .github/ISSUE_TEMPLATE/release_issue_template.md
Labels: cla: yes

#15911 📖Update release process docs & create new cherry pick template
  .github/ISSUE_TEMPLATE/cherry_pick_template.md
  contributing/release-schedule.md
Labels: cla: yes

#15958 Add documentation for animate attribute on amp-accordion
  extensions/amp-accordion/amp-accordion.md
Labels: cla: yes

#15970 Remove inline installation
  validator/webui/@polymer/ampproject-toolbar/ampproject-toolbar.html
  validator/webui/app.yaml
Labels: Category: Validator, cla: yes

#15915 ✨ Add "gtag" vendor configuration.
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#15979 Start canonical adsense fast fetch experiments at 1%
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#15971 Fixes the link for the cherry pick issue template.
  contributing/release-schedule.md
Labels: cla: yes

#15952 🚀♻️Delegate autoplay using signal
  build-system/dep-check-config.js
  extensions/amp-story/0.1/amp-story-page.js
  extensions/amp-story/1.0/amp-story-page.js
  src/service/video-manager-impl.js
  src/service/video-service-interface.js
  src/service/video-service-sync-impl.js
  src/service/video/autoplay.js
Labels: cla: yes

#15981 Skip flaky tests
  extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js
Labels: cla: yes

#15985 Increment binding limit by 500 on user gesture (up to 2000)
  extensions/amp-bind/0.1/bind-impl.js
Labels: cla: yes

#15977 🏗 Require JSDoc comments for all classes, methods, and functions in AMP code
  .eslintrc
  .eslintrc-strict
  validator/.eslintrc
Labels: Category: Tooling, cla: yes

#15944 Changes amp-story-bookend config to use camelcase
  examples/amp-story/bookendv1.json
  examples/amp-story/json/bookend.json
  extensions/amp-story/1.0/amp-story-share.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/bookend/bookend-component.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
Labels: cla: yes

#15951 Allow sending RTC with consentState policy adherence
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
Labels: cla: yes

#15904 [amp-story-bookend] Replaces amp images to regular images in amp-story-bookend
  examples/amp-story/bookendv1.json
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/bookend/components/article.js
  extensions/amp-story/1.0/bookend/components/landscape.js
  extensions/amp-story/1.0/bookend/components/portrait.js
Labels: cla: yes

#15734 Add support for binding to svg image
  examples/bind/svgimage.amp.html
  extensions/amp-bind/0.1/bind-validator.js
  extensions/amp-bind/0.1/test/test-bind-validator.js
Labels: cla: yes

#15962 🏗 Add amp-story-responsive-units experiment
  tools/experiments/experiments.js
Labels: cla: yes

#15990 Sidebar should not close when toolbar is present
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.1/toolbar.js
Labels: cla: yes

#15994 🏗 Exempt `build-system/` and `test/` from JSDoc requirements
  .eslintrc
  build-system/.eslintrc
Labels: Category: Tooling, cla: yes

#15996 ✅ Add `allowConsoleError`s in test-variables.js and test-runtime.js
  extensions/amp-analytics/0.1/test/test-variables.js
  test/functional/test-runtime.js
Labels: cla: yes

#15436 Add title and amp-bind state to history events
  build-system/conformance-config.textproto
  build-system/tasks/bundle-size.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-share-tracking/0.1/test/test-amp-share-tracking.js
  src/service/history-impl.js
  test/functional/test-history.js
Labels: cla: yes

#16005 🐛✅ Make amp-iframe tests synchronous and expect known errors
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
Labels: Related to: Flaky Tests, cla: yes

#16013 Added canonical link to required markup
  extensions/amp-story/amp-story.md
Labels: cla: yes

#16016 Unbreak master
  build-system/tasks/bundle-size.js
Labels: cla: yes

#16010 🐛 Fix git pre-push message
  build-system/enable-git-pre-push.sh
Labels: Category: Tooling, cla: yes

#16007 🏗 Exempt classes from JSDoc requirements
  .eslintrc
  .eslintrc-strict
Labels: Category: Tooling, cla: yes

#15967 📊✨ Show equalizer icon in stories
  build-system/dep-check-config.js
  css/video-autoplay.css
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/media-pool.js
  src/service/video-manager-impl.js
  src/service/video-service-sync-impl.js
  src/service/video/autoplay.js
  src/video-interface.js
  test/functional/test-video-autoplay.js
Labels: cla: yes

#16008 🏗 Prevent the use of mixed operators
  .eslintrc
  .eslintrc-strict
Labels: Category: Tooling, cla: yes

#16022 Fixing the desktop system layer alignment.
  extensions/amp-story/0.1/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.css
Labels: cla: yes

#16017 Minor: Fixed code styling syntax
  spec/amp-html-layout.md
Labels: cla: yes

#15932 Add basic integration tests for button controls and text description
  extensions/amp-lightbox-gallery/0.1/test/integration/test-amp-lightbox-gallery.js
Labels: cla: yes

#16001 Fix Dev Channel link on the experiments page
  tools/experiments/experiments.js
Labels: cla: yes

#16027 Allowing multiline sharing option titles.
  extensions/amp-story/1.0/amp-story-share.css
Labels: cla: yes

#15986 Remove last amp-bind null warning
  extensions/amp-bind/0.1/bind-expression.js
Labels: cla: yes

#16041 Update amp-bind.md
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#16040 Remove old unused experiments
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#15906 🐛 fix purgeShadowRoots sometimes fails to recognize connected nodes as such
  src/runtime.js
  test/functional/test-runtime.js
Labels: cla: yes

#15916 Pause the story until the consent prompt is resolved.
  examples/amp-story/consent.html
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#15999 Fixing an error message when getting the share providers with no bookend config.
  extensions/amp-story/0.1/amp-story-share.js
  extensions/amp-story/0.1/animation.js
  extensions/amp-story/0.1/page-scaling.js
  extensions/amp-story/0.1/utils.js
  extensions/amp-story/1.0/amp-story-share.js
  extensions/amp-story/1.0/animation.js
  extensions/amp-story/1.0/page-scaling.js
  extensions/amp-story/1.0/utils.js
Labels: cla: yes

#16048 🐛 Only try to return an ampdoc shell if the ampdoc-shell experiment is on
  src/service/ampdoc-impl.js
Labels: cla: yes

#16051 submit latest size for reference
  test/size.txt
Labels: cla: yes

#15976 Add transform event and action to <amp-pan-zoom>
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  test/manual/amp-pan-zoom.amp.html
Labels: cla: yes

#15825 🐛 Extension Race episode 3, the end is in sight, nope it's a train coming the other way.
  build-system/tasks/bundle-size.js
  src/element-service.js
  src/element-stub-data.js
  src/element-stub.js
  src/service/custom-element-registry.js
  test/functional/test-custom-element-registry.js
  test/functional/test-element-service.js
Labels: cla: yes

#16045 🐛 building v0-module.js compatible for script module
  build-system/tasks/create-module-compatible-es5-bundle.js
  gulpfile.js
Labels: cla: yes

#15810 Launch amp-fx='fly-in-*'
  extensions/amp-fx-collection/0.1/amp-fx-collection.js
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js
  extensions/amp-fx-collection/0.1/test/test-amp-fx-collection.js
  tools/experiments/experiments.js
Labels: cla: yes

#16066 📖 Clarify wording for "intrinsic"
  spec/amp-html-layout.md
Labels: cla: yes

#16070 📖 Adds command to avoid "the requested upstream branch 'upstream/master…
  contributing/getting-started-e2e.md
Labels: cla: yes

#15997 Rename fake_amp.json to fake_amp.html
  examples/a4a.amp.html
  examples/fake-ad.amp.html
  extensions/amp-ad-network-fake-impl/0.1/data/fake_amp.html
Labels: cla: yes

#16063 Ramp up native srcset experiment to 100%
  build-system/global-configs/prod-config.json
Labels: cla: yes

#16077 Start sending EID on canonical doubleclick fast fetch traffic again.
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes
