Repository ampproject/amphtml, pull requests merged in 2018-07, with the labels that each got.

#16093 Update amp-story examples with v1 requirements
  examples/amp-story/ampconf.html
  examples/amp-story/analytics.html
  examples/amp-story/animations-presets.html
  examples/amp-story/bookend.html
  examples/amp-story/desktop-backgrounds.html
  examples/amp-story/helloworld-bookend.html
  examples/amp-story/progress-bar.html
  extensions/amp-story/0.1/amp-story.js
  test/manual/amp-story-doubleclick.amp.html
Labels: cla: yes

#16481 Gate resetOnResize behavior behind an attribute tag for <amp-pan-zoom>
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  extensions/amp-pan-zoom/0.1/test/validator-amp-pan-zoom.html
  extensions/amp-pan-zoom/0.1/test/validator-amp-pan-zoom.out
  extensions/amp-pan-zoom/amp-pan-zoom.md
  extensions/amp-pan-zoom/validator-amp-pan-zoom.protoascii
  test/manual/amp-pan-zoom-integration.amp.html
  test/manual/amp-pan-zoom.amp.html
Labels: cla: yes

#16492 Run integration tests on sauce labs in non coverage mode
  build-system/pr-check.js
Labels: Category: Tooling, cla: yes

#16393 For Fluid slots, resize iframe height to match amp-ad height
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js
Labels: cla: yes

#16405 📖 amp-app-banner: Warn on missing app-argument.
  extensions/amp-app-banner/0.1/amp-app-banner.js
  extensions/amp-app-banner/0.1/test/test-amp-app-banner.js
Labels: cla: yes

#16455 Disable text highlighting when <amp-access> is used.
  extensions/amp-viewer-integration/0.1/highlight-handler.js
  extensions/amp-viewer-integration/0.1/test/test-highlight-handler.js
Labels: cla: yes

#16219 ✨Support embedding a comment for <amp-facebook>.
  3p/facebook.js
  examples/facebook.amp.html
  extensions/amp-facebook/0.1/test/validator-amp-facebook.html
  extensions/amp-facebook/0.1/test/validator-amp-facebook.out
  extensions/amp-facebook/amp-facebook.md
Labels: cla: yes

#16470 Whitelisting amp-access actions from amp-story-access.
  extensions/amp-story/1.0/amp-story-access.js
  extensions/amp-story/1.0/test/test-amp-story-access.js
Labels: cla: yes

#16514 Validator rollup
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/light/validator-light_test.js
  validator/testdata/feature_tests/css_length.out
  validator/testdata/feature_tests/inline_style.html
  validator/testdata/feature_tests/inline_style.out
  validator/testdata/feature_tests/svg.html
  validator/testdata/feature_tests/svg.out
  validator/validator-main.protoascii
  validator/validator.proto
Labels: Category: Validator, cla: yes

#16511 🏗 Explicitly navigate to a blank page when running `gulp visual-diff --puppeteer --master`
  build-system/tasks/visual-diff.js
Labels: cla: yes

#16517 📖 Clarify Moments in amp-twitter documentation
  extensions/amp-twitter/amp-twitter.md
Labels: cla: yes

#16515 Validator rollup
  validator/build.py
  validator/engine/validator.js
  validator/validator-main.protoascii
  validator/validator_gen_js.py
Labels: Category: Validator, cla: yes

#16523 🚀 Turn on font display experiment in canary.
  build-system/global-configs/canary-config.json
Labels: cla: yes

#16269 🐛Add amp-access-scroll element to fixed layer
  extensions/amp-access-scroll/0.1/amp-access-scroll.css
  extensions/amp-access-scroll/0.1/scroll-impl.js
  extensions/amp-access-scroll/OWNERS.yaml
Labels: cla: yes

#16518 🏗 Add a 100 ms delay before Percy-Puppeteer snapshots to let the page load settle
  build-system/tasks/visual-diff.js
  test/visual-diff/visual-tests
Labels: cla: yes

#16541 🏗 Switch default `gulp visual-diff` mode to Puppeteer
  build-system/tasks/visual-diff.js
Labels: cla: yes

#16513 amp-list: [src] mutation must be in mutate context
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  src/custom-element.js
Labels: cla: yes

#16531 🐛 Fix a race condition that may have caused experiment variants to not be available
  extensions/amp-experiment/0.1/amp-experiment.js
  extensions/amp-experiment/0.1/test/test-amp-experiment.js
  src/service/url-replacements-impl.js
Labels: cla: yes

#16544 Enable 'inline-styles' in canary/prod
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#16088 <amp-video-iframe> ✨
  build-system/dep-check-config.js
  build-system/tasks/bundle-size.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
  extensions/amp-video-iframe/0.1/amp-video-iframe.js
  extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
  extensions/amp-video-iframe/OWNERS.yaml
  extensions/amp-video-iframe/amp-video-iframe.md
  gulpfile.js
  src/iframe-helper.js
  src/iframe-video.js
  src/service/document-info-impl.js
  src/service/url-impl.js
  src/service/video-manager-impl.js
  src/service/video/autoplay.js
  src/video-iframe-integration.js
  src/video-interface.js
  test/fixtures/served/video-iframe.html
  test/functional/test-video-iframe-integration.js
Labels: cla: yes

#16548 🐛Skip broken tests
  extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
Labels: cla: yes

#16549 🐛 Fix story video displaying the controls UI
  src/service/video-manager-impl.js
  src/service/video-service-sync-impl.js
Labels: cla: yes

#16550 ♻️✅ Test style
  extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
Labels: cla: yes

#16537 Finish cleaning up ios-embed-wrapper experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#16547 move out all extensions declaration to its own config file
  bundles.config.js
  contributing/building-an-amp-extension.md
  gulpfile.js
Labels: cla: yes

#16556 📖 Fix spec to reflect that inline styles are now allowed
  spec/amp-html-format.md
Labels: cla: yes

#16562 Fix email spec regarding allowance of inline styles
  spec/amp-email-format.md
Labels: cla: yes

#16539 ✨Apester Media (extension): Added Platform Detection
  extensions/amp-apester-media/0.1/utils.js
Labels: cla: yes

#16563 ♻️ Remove unnecessary assigments
  src/iframe-video.js
  src/video-iframe-integration.js
Labels: cla: yes

#16261 Consolidate correlator
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
  ads/google/correlator.js
Labels: cla: yes

#16528 Remove launched experiments
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#16560 🏗 Changes to `gulp visual-diff` to lower flaky visual tests
  build-system/tasks/visual-diff.js
  test/visual-diff/visual-tests
Labels: cla: yes

#16587 Amp-ad-exit / amp-analytics transport frame integration improperly referencing win.top
  extensions/amp-ad-exit/0.1/amp-ad-exit.js
  extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
Labels: cla: yes

#16494 Better debugging for amp-bind, amp-list
  build-system/tasks/bundle-size.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-list/0.1/amp-list.js
  src/log.js
  src/runtime.js
Labels: cla: yes

#16594 Doubleclick SRA ad url deferred edge case fix
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#16592 Ensure divertExperiments() is called last in buildCallback()
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Labels: cla: yes

#16306 #AJA re-PR
  3p/integration.js
  ads/_config.js
  ads/aja.js
  ads/aja.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#16618 Stop AdSense/Doubleclick delay request experiments
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#16122 Adds TemplateRenderer
  build-system/config.js
  extensions/amp-a4a/0.1/friendly-frame-renderer.js
  extensions/amp-a4a/0.1/template-renderer.js
  extensions/amp-a4a/0.1/template-validator.js
  extensions/amp-a4a/0.1/test/test-friendly-frame-renderer.js
  extensions/amp-a4a/0.1/test/test-template-renderer.js
  extensions/amp-a4a/0.1/test/testdata/valid_css_at_rules_amp.reserialized.js
Labels: cla: yes

#16630 🏗 Ignore `page.goto()` timeouts in `visual-diff.js`
  build-system/tasks/visual-diff.js
Labels: cla: yes

#16628 📈Bump url-replacement-v2 experiment
  build-system/global-configs/prod-config.json
Labels: cla: yes

#16343 Launch amp-pan-zoom and clean up experiment
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  tools/experiments/experiments.js
Labels: cla: yes

#16638 🔥🏗 Temporarily disable testing on Sauce Labs
  build-system/pr-check.js
Labels: Category: Tooling, cla: yes

#16404 Remove native srcset experiment and update fallback logic
  builtins/amp-img.js
  builtins/amp-img.md
  examples/img/hero@1x.jpg
  examples/img/hero@1x.webp
  examples/img/hero@2x.jpg
  examples/img/hero@2x.webp
  test/functional/test-amp-img.js
  test/integration/test-amp-img.js
  test/manual/amp-img-fallback.amp.html
Labels: cla: yes

#16639 ✨ Add support for NPA request for Google Analytics.
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#16627 Doubleclick SRA move block callback handler into utils
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/sra-utils.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
Labels: cla: yes

#16623 AdSense/Doubleclick remove delay request experiments
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#16646 AdSense/Doubleclick remove unlayout experiments
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#16622 Subscriptions: adding new events
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/analytics.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#16452 Build v0.js without polyfills(except webcomponents)
  build-system/tasks/compile.js
  gulpfile.js
Labels: cla: yes

#16616 Add query param to bypass validation in dev mode.
  src/mode.js
  src/validator-integration.js
  test/functional/test-validator-integration.js
Labels: cla: yes

#16543 🏗 Remove Percy-Capybara mode for visual diffing
  .travis.yml
  build-system/pr-check.js
  build-system/tasks/visual-diff.js
  build-system/tasks/visual-diff.rb
  contributing/DEVELOPING.md
Labels: cla: yes

#16255 🏗 Reenable ABE visual diffs
  build-system/tasks/visual-diff.js
  test/visual-diff/visual-tests
Labels: cla: yes

#16636 Validator Rollup
  validator/engine/validator.js
  validator/validator-main.protoascii
  validator/validator.proto
Labels: Category: Validator, cla: yes

#16580 📖 Update amp-video-iframe.md
  extensions/amp-video-iframe/amp-video-iframe.md
Labels: cla: yes

#16581 🐛 Properly getMetadata once()
  src/video-iframe-integration.js
Labels: cla: yes

#16600 Improve action trust error message
  src/service/action-impl.js
  test/functional/test-action.js
Labels: cla: yes

#16480 Fix blank pages when #webview=1 and body.height = 0
  build-system/tasks/bundle-size.js
  css/amp.css
Labels: Internally Tracked, cla: yes

#16659 📖 Fix type annotation in `gulpfile.js`
  gulpfile.js
Labels: cla: yes

#16656 🏗 Inspect status of Percy build immediately after finalizing in `gulp visual-diff`
  build-system/tasks/visual-diff.js
Labels: cla: yes

#16657 Add correct demo links for <amp-orientation-observer>
  extensions/amp-orientation-observer/amp-orientation-observer.md
Labels: cla: yes

#16542 Subscriptions fix: shifting classes to body
  build-system/app.js
  css/amp.css
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions/0.1/amp-subscriptions.css
  extensions/amp-subscriptions/0.1/renderer.js
  extensions/amp-subscriptions/0.1/test/test-dialog.js
Labels: cla: yes

#16664 🏗 Mark the <amp-date-picker> visual diff test as flaky
  test/visual-diff/visual-tests
Labels: cla: yes

#16668 Safari fix for Toast animation
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#16678 🔥 Revert "Remove launched experiments. (#16528)"
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#16654 🏗 `:%s/--verify/--verify_status/` in `gulp visual-diff`
  build-system/pr-check.js
  build-system/tasks/visual-diff.js
Labels: cla: yes

#16504 🏗 Precede `gulp visual-diff` with a build step (unless `--nobuild`)
  build-system/pr-check.js
  build-system/tasks/visual-diff.js
  contributing/DEVELOPING.md
  gulpfile.js
Labels: cla: yes

#16681 🐛 Ensure there is an active page before updating viewport styles
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#16672 :book: Fix typos in amp-img layout explanation
  builtins/amp-img.md
Labels: cla: yes

#16650 Do not XHR intercept first party (1P) CDN resources
  src/service/xhr-impl.js
  test/functional/test-xhr.js
Labels: cla: yes

#15969 get dependencies of bundles
  build-system/base.js
  build-system/get-dep-graph.js
  build-system/splittable.extern.js
  bundles.config.js
  package.json
  yarn.lock
Labels: cla: yes

#16180 🏗 Re-enable visual diff tests when running all commands in PR check
  build-system/pr-check.js
Labels: cla: yes

#16705 ✅ Disable flaky visual diff test
  test/visual-diff/visual-tests
Labels: cla: yes

#16703 Disable bundle-size on non-master pushes
  build-system/pr-check.js
Labels: cla: yes

#16688 🏗 Lint: isExperimentOn must be passed an explicit string
  .eslintrc
  ads/google/a4a/utils.js
  build-system/eslint-rules/is-experiment-on.js
  extensions/amp-access/0.1/amp-access-server-jwt.js
  extensions/amp-access/0.1/amp-access-server.js
  extensions/amp-access/0.1/signin.js
  extensions/amp-analytics/0.1/test/test-requests.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
  extensions/amp-auto-ads/0.1/amp-auto-ads.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  extensions/amp-google-document-embed/0.1/amp-google-document-embed.js
  extensions/amp-google-vrview-image/0.1/amp-google-vrview-image.js
  extensions/amp-next-page/0.1/amp-next-page.js
  extensions/amp-playbuzz/0.1/amp-playbuzz.js
  extensions/amp-share-tracking/0.1/amp-share-tracking.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-viz-vega/0.1/amp-viz-vega.js
  src/experiments.js
  src/service/url-replacements-impl.js
  src/service/viewport/viewport-impl.js
  test/functional/test-experiments.js
  tools/experiments/experiments.js
Labels: cla: yes

#16715 SwG release 0.1.22.21
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#16598 Extend RTL functionality in desktop ✨
  extensions/amp-story/1.0/amp-story-desktop.css
Labels: Category: AMP Story, cla: yes

#16687 🏗 Re-enable testing on Sauce Labs on Chrome, Firefox, and Safari (with lower concurrency)
  build-system/pr-check.js
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test.js
Labels: Category: Tooling, cla: yes

#16704 🏗 Silence subprocesses in visual diffs by default
  build-system/exec.js
  build-system/tasks/visual-diff.js
Labels: cla: yes

#16698 🐛 amp-next-page: Update URL with query string when switching documents
  extensions/amp-next-page/0.1/next-page-service.js
Labels: cla: yes

#16723 ✅ Skip `amp-bind` `in single ampdoc` tests since they cause the browser to crash
  build-system/pr-check.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
Labels: Related to: Flaky Tests, cla: yes

#16727 Fix yarn.lock
  yarn.lock
Labels: cla: yes

#16530 ✨ Implement standard action `toggleClass(...)`
  build-system/tasks/bundle-size.js
  examples/standard-actions.amp.html
  spec/amp-actions-and-events.md
  src/service/standard-actions-impl.js
  test/functional/test-standard-actions.js
Labels: cla: yes

#16736 🐛🏗 Indentation fixes based on the new (more accurate) `eslint` implementation of the `indent` rule
  3p/iframe-transport-client.js
  ads/google/a4a/experiment-utils.js
  ads/google/a4a/line-delimited-response-handler.js
  ads/google/a4a/url-builder.js
  ads/nativo.js
  build-system/config.js
  extensions/amp-a4a/0.1/template-validator.js
  extensions/amp-ad-exit/0.1/amp-ad-exit.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
  extensions/amp-analytics/0.1/iframe-transport.js
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-sidebar/0.1/test/test-toolbar.js
  extensions/amp-story/0.1/localization.js
  extensions/amp-story/1.0/amp-story-access.js
  extensions/amp-story/1.0/localization.js
  src/service/position-observer/position-observer-worker.js
  src/service/url-replacements-impl.js
  src/service/xhr-impl.js
  src/web-worker/amp-worker.js
  test/functional/test-shadow-embed.js
  validator/engine/css-selectors.js
  validator/engine/parse-css.js
  validator/engine/validator.js
Labels: Category: Tooling, cla: yes

#16477 📖External consent flow doc
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#16733 Point people with questions about using AMP to Stack Overflow instead of Slack
  CONTRIBUTING.md
Labels: cla: yes

#16667 📖amp-carousel arrow clarification: updated controls and arrows behavior content
  extensions/amp-carousel/amp-carousel.md
Labels: cla: yes

#16732 Remove references to Slack on the support page
  SUPPORT.md
Labels: cla: yes

#16649 ✨amp-sidebar: Remove 80vw restriction for amp-sidebar
  extensions/amp-sidebar/0.1/amp-sidebar.css
  extensions/amp-sidebar/amp-sidebar.md
Labels: cla: yes

#16524 Turn on the no-sync-xhr-in-ads experiment in canary.
  build-system/global-configs/canary-config.json
Labels: cla: yes

#16706 use canonical url instead of HREF 🐛
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#16746 Inform developers to run --update_tests.
  validator/engine/validator_test.js
Labels: cla: yes

#16526 ✨ Render close button for lightbox ads in FIE
  css/amp.css
  css/lightbox-ad.css
  examples/ad-lightbox.amp.html
  extensions/amp-ad/0.1/amp-ad.css
  extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
  extensions/amp-lightbox/0.1/amp-lightbox.js
  src/friendly-iframe-embed.js
  src/service/viewport/viewport-impl.js
  test/functional/test-friendly-iframe-embed.js
Labels: cla: yes

#16731 Use dev().info for prod logging
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-list/0.1/amp-list.js
  src/log.js
Labels: cla: yes

#16730 Unskip most bind-impl.js tests
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
Labels: cla: yes

#16748 🏗 Add amp-video-iframe to bundles.config.js
  bundles.config.js
Labels: cla: yes

#16725 Changes to <amp-orientation-observer> demos
  examples/amp-orientation-observer-3d-parallax.amp.html
  examples/amp-orientation-observer.amp.html
Labels: cla: yes

#16751 Fix Bind.scanAndApply() and add test
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
Labels: cla: yes

#16754 📖 amp-date-countdown: Add link to ABE sample
  extensions/amp-date-countdown/amp-date-countdown.md
Labels: cla: yes

#16758 Moves files that can be into intermediate bundles.
  .gitignore
  build-system/get-dep-graph.js
Labels: cla: yes

#16747 🐛Show equalizer icon in 3p players without `controls`
  css/video-autoplay.css
  src/service/video-manager-impl.js
  src/service/video-service-sync-impl.js
Labels: cla: yes

#16759 🏗🐛 Move negative lint globs to `.eslintignore`
  .eslintignore
  build-system/config.js
Labels: Category: Tooling, cla: yes

#16760 Validator rollup
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/testdata/feature_tests/deprecation_warnings_and_errors.out
  validator/testdata/feature_tests/new_and_old_boilerplate_mixed2.out
  validator/testdata/feature_tests/old-boilerplate.out
  validator/testdata/feature_tests/regexps.out
  validator/testdata/feature_tests/style_tag.html
  validator/testdata/feature_tests/style_tag.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#16766 ✅ Mark the <amp-jwplayer> visual diff test as flaky
  test/visual-diff/visual-tests
Labels: cla: yes

#16757 📖 Update Mediavine docs
  ads/mediavine.md
Labels: cla: yes

#16734 Support referrerPolicy:no-referrer in amp-analytics
  builtins/amp-pixel.js
  examples/analytics.amp.html
  extensions/amp-analytics/0.1/transport.js
  extensions/amp-analytics/amp-analytics.md
  src/pixel.js
  test/integration/test-amp-analytics.js
Labels: cla: yes

#16771 Allow submit-{success/error} attribute on all ancestors of form elements
  validator/testdata/feature_tests/forms.html
  validator/testdata/feature_tests/forms.out
  validator/validator-main.protoascii
Labels: cla: yes

#16770 Introduce an intermediate bundle for single-run compiler build.
  build-system/get-dep-graph.js
Labels: cla: yes

#16778 🏗🐛 Build the polyfill and non-polyfill versions of the runtime into separate files
  gulpfile.js
Labels: Category: Tooling, cla: yes

#16454 Remove the header size when we calculate the scroll position to center highlighted elements.
  extensions/amp-viewer-integration/0.1/highlight-handler.js
  extensions/amp-viewer-integration/0.1/test/test-highlight-handler.js
Labels: cla: yes

#16765 📖 Update amp-date-countdown samples
  extensions/amp-date-countdown/amp-date-countdown.md
Labels: cla: yes

#16645 📖 Update amp-next-page documentation
  extensions/amp-next-page/amp-next-page.md
Labels: cla: yes

#16776 🏗 When copying Amp-By-Examples to visual diff configs, skip components that already exist
  build-system/copy-abe-visual-test-pages.sh
Labels: cla: yes

#16772 Fix amp-state mutation bug when opening new tab
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-bind/0.1/test/test-amp-state.js
Labels: cla: yes

#16788 Clean up amp-next-page doc + fix syntax
  extensions/amp-next-page/amp-next-page.md
Labels: cla: yes

#16798 📖Move amp-audio actions from Events to Actions section in doc
  spec/amp-actions-and-events.md
Labels: cla: yes

#16787 📖 Clean up wording in doc
  extensions/amp-pan-zoom/amp-pan-zoom.md
Labels: cla: yes

#16763 🗑Remove googleanalytics-alpha
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-vendors.js
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#16799 🏗🐛 Do not generate code during `gulp check-types`
  build-system/tasks/compile.js
  gulpfile.js
Labels: Category: Tooling, cla: yes

#16804 🚮 Remove `greenkeeper-lockfile`
  package.json
  yarn.lock
Labels: Category: Tooling, Cleanup, cla: yes

#16807 amp-bind: Support object args for splice()
  extensions/amp-bind/0.1/bind-expression.js
  extensions/amp-bind/0.1/test/test-bind-expression.js
Labels: cla: yes

#16814 🏗 Add debug-assisting parameters to `gulp visual-diff`
  build-system/tasks/visual-diff.js
Labels: cla: yes

#16808 Fixing range values for scale
  extensions/amp-pan-zoom/amp-pan-zoom.md
Labels: cla: yes

#16809 Fix amp-image won't render after resize in amp-fx-flying-carpet with media attribute
  extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
  extensions/amp-fx-flying-carpet/0.1/test/test-amp-fx-flying-carpet.js
  test/manual/amp-flying-carpet-media.amp.html
Labels: cla: yes

#16790 Fix images and formatting in amp-date-countdown doc
  extensions/amp-date-countdown/amp-date-countdown.md
Labels: cla: yes

#16824 Skip amp-lightbox-gallery integration tests
  extensions/amp-lightbox-gallery/0.1/test/integration/test-amp-lightbox-gallery.js
Labels: Related to: Flaky Tests, cla: yes

#16817 Validator rollup
  extensions/amp-audio/validator-amp-audio.protoascii
  extensions/amp-bodymovin-animation/validator-amp-bodymovin-animation.protoascii
  extensions/amp-carousel/validator-amp-carousel.protoascii
  extensions/amp-dailymotion/validator-amp-dailymotion.protoascii
  extensions/amp-image-lightbox/0.1/test/validator-amp-image-lightbox.html
  extensions/amp-image-lightbox/0.1/test/validator-amp-image-lightbox.out
  extensions/amp-lightbox/0.1/test/validator-amp-lightbox.html
  extensions/amp-lightbox/0.1/test/validator-amp-lightbox.out
  extensions/amp-playbuzz/validator-amp-playbuzz.protoascii
  extensions/amp-reddit/validator-amp-reddit.protoascii
  extensions/amp-selector/validator-amp-selector.protoascii
  extensions/amp-soundcloud/validator-amp-soundcloud.protoascii
  extensions/amp-springboard-player/validator-amp-springboard-player.protoascii
  extensions/amp-youtube/validator-amp-youtube.protoascii
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/testdata/feature_tests/forms.out
  validator/validator-main.protoascii
  validator/validator.proto
  validator/validator_gen_js.py
Labels: cla: yes

#16805 Extract config logic to a separate file from amp-analytics.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-config.js
Labels: cla: yes

#16823 🐛 Fix source maps for local A4A testing.
  build-system/app.js
Labels: cla: yes

#16642 Shadow root viewport binding for iOS
  css/amp.css
  examples/everything.iframed.html
  src/service/viewport/viewport-binding-ios-embed-sd.js
  src/service/viewport/viewport-impl.js
  test/functional/test-viewport-binding.js
  test/functional/test-viewport.js
  tools/experiments/experiments.js
Labels: cla: yes

#16841 Run `gulp update-packages` just once on Travis
  build-system/pr-check.js
  build-system/tasks/check-links.js
  build-system/tasks/dep-check.js
  build-system/tasks/lint.js
  gulpfile.js
Labels: Category: Tooling, cla: yes

#16837 Clean up incosistent hack to patch document-register-element.
  build-system/get-dep-graph.js
  build-system/tasks/compile.js
  build-system/tasks/update-packages.js
  src/polyfills.js
  src/service/extensions-impl.js
  testing/describes.js
  testing/iframe.js
Labels: cla: yes

#16813 ✨Support different animation styles in `amp-lightbox`
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-lightbox/0.1/test/validator-amp-lightbox.html
  extensions/amp-lightbox/0.1/test/validator-amp-lightbox.out
  extensions/amp-lightbox/amp-lightbox.md
  extensions/amp-lightbox/validator-amp-lightbox.protoascii
Labels: cla: yes

#16806 ♻️Use built-in FIE checker
  examples/amp-story/doubleclick.html
  extensions/amp-story/1.0/amp-story-page.js
  src/friendly-iframe-embed.js
Labels: cla: yes

#16831 🐛Fix race condition when opening/closing amp-sidebar
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
Labels: cla: yes

#16842 Fix a bad merge conflict resolution
  extensions/amp-analytics/0.1/config.js
Labels: cla: yes

#16852 Revert "Code-cleanup of splittable fork."
  build-system/base.js
  build-system/config.js
  build-system/get-dep-graph.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/update-packages.js
  src/polyfills.js
  src/service/extensions-impl.js
  test/manual/amp-single-pass-compilation.html
  testing/describes.js
  testing/iframe.js
Labels: cla: yes

#16718 🐛 amp-next-page: Fix duplicate custom separators for child pages with amp-next-page
  extensions/amp-next-page/0.1/amp-next-page.js
Labels: cla: yes

#16858 update with value/value_casei change
  contributing/component-validator-rules.md
Labels: cla: yes

#16857 Code-cleanup of splittable fork.
  build-system/base.js
  build-system/config.js
  build-system/get-dep-graph.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/update-packages.js
  src/polyfills.js
  src/service/extensions-impl.js
  test/manual/amp-single-pass-compilation.html
  testing/describes.js
  testing/iframe.js
Labels: cla: yes

#16356 Add Mixi.Media AD network widgets extension
  3p/integration.js
  ads/_config.js
  ads/miximedia.js
  ads/miximedia.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#16877 📖 Update instructions for local visual diffing
  contributing/DEVELOPING.md
Labels: cla: yes

#16660 add a way to load dependencies lazily through configuration
  build-system/amp.extern.js
  build-system/tasks/bundle-size.js
  src/runtime.js
  test/functional/test-runtime.js
Labels: cla: yes

#16879 Updating with DoubleClick documentation
  extensions/amp-ad-network-doubleclick-impl/single-page-ad.md
Labels: cla: yes

#16782 Support script[type=application/json] in templates
  src/purifier.js
  src/sanitizer.js
  test/functional/test-purifier.js
Labels: cla: yes

#16898 No mixed logical operators
  .eslintrc
  3p/ampcontext-integration.js
  build-system/eslint-rules/no-mixed-operators.js
  extensions/amp-access/0.1/jwt.js
  extensions/amp-ad-network-doubleclick-impl/0.1/sra-utils.js
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-analytics/0.1/visibility-manager.js
  extensions/amp-animation/0.1/css-expr-ast.js
  extensions/amp-animation/0.1/web-animations.js
  extensions/amp-form/0.1/form-proxy.js
  src/custom-element.js
  src/gesture-recognizers.js
  src/gesture.js
  src/service/action-impl.js
  src/service/history-impl.js
  validator/engine/json-testutil.js
Labels: cla: yes

#16774 🚀sticky-ad measure background color before mutate
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
Labels: cla: yes

#16912 📖: Update maxTimerLength doc
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#16874 Fix test-requests.js error
  extensions/amp-analytics/0.1/test/test-requests.js
Labels: cla: yes

#16062 Fix a4a temps
  extensions/amp-a4a/0.1/amp-ad-type-defs.js
  extensions/amp-ad-network-adzerk-impl/0.1/amp-ad-network-adzerk-impl.js
Labels: cla: yes
