Repository ampproject/amphtml, pull requests merged in 2018-03, with the labels that each got.

#13682 Adds selectPlatform method for amp-subscriptions
  extensions/amp-subscriptions/0.1/entitlement-store.js
  extensions/amp-subscriptions/0.1/test/test-entitlement-store.js
Labels: cla: yes

#13731 🐛♻️Use a signal to know when story is loaded
  extensions/amp-story/0.1/amp-story-auto-ads.js
  extensions/amp-story/0.1/amp-story.js
Labels: cla: yes

#13723 Update docs deprecate update ping
  spec/amp-cache-debugging.md
  spec/amp-cache-guidelines.md
Labels: cla: yes

#13743 Setting a z-index to stories toast messages.
  extensions/amp-story/0.1/amp-story.css
Labels: cla: yes

#13742 Simplified media blessing.
  extensions/amp-story/0.1/media-tasks.js
Labels: cla: yes

#13722 `:book: Updated getting started docs with production release timing`
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
Labels: cla: yes

#13730 Add default placeholder icons
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-placeholders.js
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#13533 Support whitelisting of AMP variable substitutions
  extensions/amp-a4a/0.1/a4a-variable-source.js
  src/service/url-replacements-impl.js
  src/service/variable-source.js
  test/functional/test-amp-pixel.js
  test/functional/test-variable-source.js
  test/functional/url-expander/test-expander.js
Labels: cla: yes

#13756 🐛Register the actions in buildCallback so they are available before the first activation
  extensions/amp-lightbox/0.1/amp-lightbox.js
Labels: cla: yes

#13752 amp-ima-video: allow autoplay in validator
  extensions/amp-ima-video/0.1/test/validator-amp-ima-video.html
  extensions/amp-ima-video/0.1/test/validator-amp-ima-video.out
  extensions/amp-ima-video/validator-amp-ima-video.protoascii
Labels: cla: yes

#13728 🐛Refactor interaction counting for <amp-story-auto-ads>
  extensions/amp-story/0.1/amp-story-auto-ads.js
  extensions/amp-story/0.1/amp-story.js
Labels: cla: yes

#13754 Remove the Lightbox CSS API per spec
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/amp-lightbox-gallery.md
  test/manual/amp-lightbox-gallery-css.amp.html
Labels: cla: yes

#13736 CORS fixed :fire:
  ads/videonow.js
Labels: cla: yes

#13763 ♻️URL Replacements: Minifiy Date variables
  src/service/url-replacements-impl.js
Labels: cla: yes

#13759 Simplify getTimingDataAsync
  src/service/variable-source.js
  test/functional/test-variable-source.js
Labels: cla: yes

#13760 ♻️URL Replacements: Let's go golfing part 1
  src/service/url-replacements-impl.js
Labels: cla: yes

#13374 Updated copyright for taboola.js
  ads/taboola.js
Labels: cla: yes

#13727 ✨Implement story-ad outlinks
  examples/amp-story-auto-ads-payload.json
  examples/amp-story-auto-ads.amp.html
  extensions/amp-story/0.1/amp-story-ads.css
  extensions/amp-story/0.1/amp-story-auto-ads.js
  extensions/amp-story/0.1/amp-story.css
Labels: cla: yes

#12343 Added new ad network Monetizer101
  3p/integration.js
  ads/_config.js
  ads/monetizer101.js
  ads/monetizer101.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#13767 13174 ampstory desktop viewport warning
  extensions/amp-story/0.1/amp-story.css
  extensions/amp-story/0.1/amp-story.js
Labels: cla: yes

#13773 :bug: Add new Font Awseome URL format, fixes #13770 and #13685
  validator/testdata/feature_tests/regexps.html
  validator/testdata/feature_tests/regexps.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#13523 amp-ad-exit: ignore clicks on specific elements
  examples/amp-ad-exit.amp.html
  extensions/amp-ad-exit/0.1/amp-ad-exit.js
  extensions/amp-ad-exit/0.1/config.js
  extensions/amp-ad-exit/0.1/filters/factory.js
  extensions/amp-ad-exit/0.1/filters/filter.js
  extensions/amp-ad-exit/0.1/filters/inactive-element.js
  extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
  extensions/amp-ad-exit/amp-ad-exit.md
Labels: cla: yes

#12414 Implement Mobify Analytics
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#13757 🏗 Make visual tests more resilient to Selenium read timeouts
  .travis.yml
  build-system/tasks/visual-diff.rb
Labels: Category: Tooling, Related to: Flaky Tests, cla: yes

#13778 csp update for use.fontawesome.com
  build-system/app.js
  examples/csp.amp.html
Labels: cla: yes

#13787 🐛Ignore clicks on certain tags in amp-story
  extensions/amp-story/0.1/page-advancement.js
Labels: cla: yes

#13784 ✨Show/Remove ad icon for story ad
  extensions/amp-story/0.1/amp-story-ads.css
  extensions/amp-story/0.1/amp-story-auto-ads.js
  extensions/amp-story/0.1/amp-story.js
Labels: cla: yes

#13795 inabox: add window.AMP.inaboxUnregisterIframe(iframe)
  ads/inabox/inabox-host.js
  ads/inabox/inabox-messaging-host.js
  test/functional/inabox/test-inabox-messaging-host.js
Labels: cla: yes

#13801 Tracking web standards and web features proposals related to AMP.
  contributing/web-standards-related-to-amp.md
Labels: cla: yes

#13802 Update SWG to V 0.1.19
  third_party/subscriptions-project/apis.js
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#13732 Adding Experimental note
  extensions/amp-story/amp-story-ads.md
Labels: cla: yes

#13751 🐛Propagate <track> elements in amp-story
  extensions/amp-story/0.1/sources.js
Labels: cla: yes

#13790 Subscriptions: Add action execution and rendering actions
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement-store.js
  extensions/amp-subscriptions/0.1/local-subscription-platform-renderer.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/renderer.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-local-subscription-rendering.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-renderer.js
Labels: cla: yes

#13749 Remove 'alphas'
  extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
Labels: cla: yes

#13719 Update doubleclick.md
  ads/google/doubleclick.md
Labels: cla: yes

#13812 ♻️ Remove ad limit from amp-story-auto-ad
  extensions/amp-story/0.1/amp-story-auto-ads.js
Labels: cla: yes

#13807 ♻️Set up new extension for <amp-story-auto-ads>
  examples/amp-story-auto-ads.amp.html
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story/0.1/amp-story-auto-ads.js
  gulpfile.js
Labels: cla: yes

#13813 Fix vsync mutation race in lightbox open
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#13783 ✨ Add Quora AMP Ad integration
  3p/integration.js
  ads/_config.js
  ads/quoraad.js
  ads/quoraad.md
  examples/ads.amp.html
Labels: cla: yes

#13815 Correct typos in story ads docs
  extensions/amp-story/amp-story-ads.md
  extensions/amp-story/amp-story-auto-ads.md
Labels: cla: yes

#13814 🐛 Protect certain attributes in story-ads
  extensions/amp-story/0.1/amp-story-auto-ads.js
Labels: cla: yes

#13729 amp-list: Schedule pass if queue is non-empty
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#13746 Creation of base class for amp-story layers.
  extensions/amp-story/0.1/amp-story-base-layer.js
  extensions/amp-story/0.1/amp-story-cta-layer.js
  extensions/amp-story/0.1/amp-story-grid-layer.js
  extensions/amp-story/0.1/amp-story.css
Labels: cla: yes

#13826 fix links to avoid 404s
  extensions/amp-ad/amp-ad.md
  spec/amp-html-format.md
Labels: cla: yes

#13825 Inabox experiment renderOutsideViewport true
  src/base-element.js
  test/functional/test-base-element.js
  tools/experiments/experiments.js
Labels: cla: yes

#13809 Refactor measure and mutate in lightbox animations
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#13779 🐛Fixes error in document.contains polyfill in IE 10 (#13768)
  src/polyfills/document-contains.js
Labels: cla: yes

#13830 Make sure safeframe geom matches gpt
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
Labels: cla: yes

#13817 📖 Add .md for MediaPool
  extensions/amp-story/0.1/media-pool.md
  extensions/amp-story/img/media-pool-element-lifecycle.png
Labels: cla: yes

#13765 ♻️URL Replacements: minify screen variables
  src/service/url-replacements-impl.js
Labels: cla: yes

#13750 🚀♻️ Refactor Srcset
  builtins/amp-img.js
  extensions/amp-anim/0.1/amp-anim.js
  extensions/amp-bind/0.1/bind-validator.js
  extensions/amp-bind/0.1/test/test-bind-validator.js
  extensions/amp-image-lightbox/0.1/amp-image-lightbox.js
  extensions/amp-image-lightbox/0.1/test/test-amp-image-lightbox.js
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
  src/sanitizer.js
  src/srcset.js
  test/functional/test-sanitizer.js
  test/functional/test-srcset.js
Labels: cla: yes

#13845 Fix test failure due to browser behavior on getting location.hash
  test/functional/test-navigation.js
Labels: cla: yes

#13800 Fixed incorrect quotation character.
  extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
Labels: cla: yes

#13799 Fix treasuredata's cid-scope-cookie-fallback-name
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#13835 Whitelist origins
  extensions/amp-story/0.1/origin-whitelist.js
Labels: cla: yes

#13250 Mutate amp-ad inside mutation phase
  extensions/amp-ad/0.1/amp-ad-ui.js
  extensions/amp-ad/0.1/amp-ad.js
  extensions/amp-ad/0.1/test/test-amp-ad.js
Labels: cla: yes

#13834 Add amp-story embed modes
  extensions/amp-story/0.1/amp-story-auto-ads.js
  extensions/amp-story/0.1/amp-story-state-service.js
  extensions/amp-story/0.1/amp-story.css
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/embed-mode.js
  extensions/amp-story/0.1/system-layer.js
  extensions/amp-story/0.1/test/test-system-layer.js
  extensions/amp-story/embed-modes.md
Labels: cla: yes

#13842 Fix sticky-ad added to fixed layer too early
  examples/sticky.ads.amp.html
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
  extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
Labels: cla: yes

#13713 🐛 amp-ima-video: Fail gracefully to content when the IMA library fails…
  ads/google/imaVideo.js
  examples/ima-video.amp.html
  examples/img/ima-poster.png
Labels: cla: yes

#13808 Create new experiment to ignore remote.html
  extensions/amp-ad-network-doubleclick-impl/0.1/doubleclick-a4a-config.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-a4a-config.js
Labels: cla: yes

#13852 Update docs to fix all json
  extensions/amp-a4a/rtc-documentation.md
Labels: cla: yes

#13844 🐛 Sanitize CTA Urls
  extensions/amp-story/0.1/amp-story-auto-ads.js
Labels: cla: yes

#13829 🐛 Wait for story impl to resolve
  extensions/amp-story/0.1/amp-story-auto-ads.js
Labels: cla: yes

#13853 Add current macros to RTC docs.
  extensions/amp-ad-network-doubleclick-impl/doubleclick-rtc.md
Labels: cla: yes

#13831 Clean up links in docs
  extensions/amp-access/amp-access.md
  extensions/amp-ad/amp-ad.md
  extensions/amp-bind/amp-bind.md
  extensions/amp-call-tracking/amp-call-tracking.md
  extensions/amp-form/amp-form.md
  extensions/amp-iframe/amp-iframe.md
  extensions/amp-list/amp-list.md
  extensions/amp-user-notification/amp-user-notification.md
Labels: cla: yes

#13851 Add amp-layout to readme
  builtins/README.md
Labels: cla: yes

#13848 🏗Make node 8 the minimum version for AMP development
  .travis.yml
  build-system/check-package-manager.js
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
Labels: Category: Tooling, cla: yes

#13811 Allow to lint a file glob instead of all files
  build-system/tasks/lint.js
  contributing/DEVELOPING.md
Labels: cla: yes

#12869 amp-ad Cedato AMP Ad provider
  3p/integration.js
  ads/_config.js
  ads/cedato.js
  ads/cedato.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#13857 Fix amp-embed
  extensions/amp-ad/0.1/amp-ad-ui.js
Labels: cla: yes

#13858 When passing a file glob to lint, don't lose the files we're not supposed to be linting.
  build-system/tasks/lint.js
Labels: cla: yes

#13840 Subscriptions: Implement Service Adapter
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement-store.js
  extensions/amp-subscriptions/0.1/entitlement.js
  extensions/amp-subscriptions/0.1/local-subscription-platform-renderer.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/service-adapter.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-entitlements.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-service-adapter.js
Labels: cla: yes

#13409 Make <amp-install-service-worker> a low priority element, and remove timer-based delay to installation
  extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js
  extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
Labels: cla: yes

#13861 🏗 Restrict same-line logging in gulp lint to TTY terminals
  build-system/tasks/lint.js
Labels: cla: yes

#13792 Support TypeScript in extensions
  build-system/typescript.js
  gulpfile.js
  package.json
  yarn.lock
Labels: cla: yes

#13846 Add validator instructions for mac
  validator/README.md
Labels: cla: yes

#13816 <amp-lightbox-gallery> validator rules
  extensions/amp-carousel/validator-amp-carousel.protoascii
  extensions/amp-lightbox-gallery/0.1/test/validator-amp-lightbox-gallery.html
  extensions/amp-lightbox-gallery/0.1/test/validator-amp-lightbox-gallery.out
  extensions/amp-lightbox-gallery/validator-amp-lightbox-gallery.protoascii
  extensions/amp-video/validator-amp-video.protoascii
  extensions/amp-youtube/validator-amp-youtube.protoascii
  validator/validator-main.protoascii
Labels: cla: yes

#13880 ✅Add test for compounded tokens
  test/functional/url-expander/test-expander.js
Labels: cla: yes

#13875 Allow inabox-rov experiment to be enabled via metatag
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#13699 Support for background-audio on the <amp-story> tag.
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/audio.js
Labels: cla: yes

#13865 Subscriptions: reset logic after action completion
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement-store.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-entitlement-store.js
  extensions/amp-subscriptions/0.1/test/test-local-subscription-rendering.js
Labels: cla: yes

#13883 Allow referrerpolicy on anchor tags in AMP docs
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#13885 <amp-pinterest> Sanitize URLs
  extensions/amp-pinterest/0.1/pin-widget.js
Labels: cla: yes

#13836 Update to Nielsen measurement
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#13888 Validator Roll-up
  extensions/amp-lightbox-gallery/0.1/test/validator-amp-lightbox-gallery.html
  extensions/amp-lightbox-gallery/0.1/test/validator-amp-lightbox-gallery.out
  extensions/amp-lightbox-gallery/validator-amp-lightbox-gallery.protoascii
  extensions/amp-mustache/validator-amp-mustache.protoascii
  extensions/amp-story-auto-ads/0.1/test/validator-amp-story-auto-ads.html
  extensions/amp-story-auto-ads/0.1/test/validator-amp-story-auto-ads.out
  extensions/amp-story-auto-ads/validator-amp-story-auto-ads.protoascii
  extensions/amp-story/validator-amp-story.protoascii
  extensions/amp-youtube/validator-amp-youtube.protoascii
  validator/README.md
  validator/engine/validator_test.js
  validator/testdata/feature_tests/forms.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#13886 Only add http prefix to thirdPartyUrl where necessary
  build-system/tasks/prepend-global/index.js
Labels: cla: yes

#13871 Subscriptions: swg activation
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  third_party/subscriptions-project/apis.js
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#13890 🏗 Fix Ctrl + C handler on Windows (part 2)
  build-system/ctrlcHandler.js
  build-system/exec.js
Labels: Category: Tooling, cla: yes

#13860 🏗 Use latest LTS version of node for AMP development
  .travis.yml
  build-system/check-package-manager.js
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
Labels: Category: Tooling, cla: yes

#13878 ✨ Add Index Exchange as a vendor to DoubleClick RTC
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#13864 Refactors animation presets ♻️
  examples/amp-story/animations-presets.html
  extensions/amp-story/0.1/animation-presets-utils.js
  extensions/amp-story/0.1/animation-presets.js
  src/style.js
Labels: cla: yes

#13866 Remove deferMutate
  contributing/building-an-amp-extension.md
  extensions/amp-a4a/0.1/test/utils.js
  extensions/amp-ad/0.1/amp-ad-ui.js
  extensions/amp-ad/0.1/test/test-amp-ad-ui.js
  extensions/amp-carousel/0.1/base-carousel.js
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js
  extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
  extensions/amp-live-list/0.1/amp-live-list.js
  extensions/amp-live-list/0.1/test/test-amp-live-list.js
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
  extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
  src/base-element.js
  src/custom-element.js
  src/service/resources-impl.js
  src/service/standard-actions-impl.js
  test/functional/test-custom-element.js
  test/functional/test-standard-actions.js
Labels: cla: yes

#13889 Docs: data-url needs to be accessible cross-origin
  ads/custom.md
Labels: cla: yes

#13870 Update lightbox tests to prune invalid ads and add all layouts for video and social share
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#13907 sanitizer: allow aria- and role
  src/sanitizer.js
  test/functional/test-sanitizer.js
Labels: cla: yes

#13904 ♻️ Hoist const outside of function
  extensions/amp-story/0.1/page-advancement.js
Labels: cla: yes

#13915 📖Add documentation for multiple access sources
  extensions/amp-access/amp-access.md
Labels: cla: yes

#13918 Update safeframe version to 1-0-17
  extensions/amp-a4a/0.1/amp-a4a.js
Labels: cla: yes

#13905 🐛 Fix `ad` overlay for stories
  extensions/amp-story/0.1/amp-story-ads.css
Labels: cla: yes

#13847 Undo important on grid for media query
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
Labels: cla: yes

#13863 amp-consent skeleton
  build-system/app.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-consent/0.1/amp-consent.css
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  gulpfile.js
  test/manual/amp-consent.html
  tools/experiments/experiments.js
Labels: cla: yes

#12740 Remove duration and occurrences
  extensions/amp-analytics/0.1/iframe-transport.js
Labels: cla: yes

#13926 Add note about no intrinsic size for responsive elements
  spec/amp-html-layout.md
Labels: cla: yes

#13901 Subscriptions: Adding dialog renderer and actions section
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions/0.1/amp-subscriptions.css
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/dialog.js
  extensions/amp-subscriptions/0.1/local-subscription-platform-renderer.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/service-adapter.js
  extensions/amp-subscriptions/0.1/test/test-local-subscription-rendering.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-renderer.js
  extensions/amp-subscriptions/0.1/test/test-service-adapter.js
Labels: cla: yes

#13633 ♻️ Rename (get|update)Priority to (get|update)LayoutPriority
  build-system/tasks/presubmit-checks.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/utils.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-ad/0.1/amp-ad-custom.js
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
  extensions/amp-ad/0.1/test/test-amp-ad-custom.js
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-bind/0.1/amp-bind-macro.js
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
  extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js
  src/base-element.js
  src/custom-element.js
  src/element-stub.js
  src/service/resource.js
  src/service/resources-impl.js
  test/functional/test-amp-img.js
  test/functional/test-base-element.js
  test/functional/test-resource.js
  test/functional/test-resources.js
Labels: cla: yes

#13936 Update validator changelog
  validator/CHANGELOG.md
Labels: Category: Validator, cla: yes

#13933 Add Lotame as a vendor to RTC config
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#13925 Whitelist origins for amp-story: week of 2018-03-13
  extensions/amp-story/0.1/origin-whitelist.js
Labels: cla: yes

#13937 Making the unmute icon easier to target.
  extensions/amp-story/0.1/amp-story.css
Labels: cla: yes

#13941 Add new safeframe doc for Doubleclick's GPT Safeframe.
  extensions/amp-ad-network-doubleclick-impl/images/sf_example_1.png
  extensions/amp-ad-network-doubleclick-impl/images/sf_example_2.png
  extensions/amp-ad-network-doubleclick-impl/images/sf_example_3.png
  extensions/amp-ad-network-doubleclick-impl/images/sf_example_4.png
  extensions/amp-ad-network-doubleclick-impl/safeframe.md
Labels: cla: yes

#13873 bug: Fixes amp-animation not resuming correctly (#13562)
  extensions/amp-animation/0.1/test/test-web-animations.js
  extensions/amp-animation/0.1/web-animations.js
  third_party/closure-compiler/externs/web_animations.js
Labels: cla: yes

#13899 Support for standalone Media.net amp tag
  ads/medianet.js
  ads/medianet.md
Labels: cla: yes

#13142 BeOpinion: Add Extension And Ad
  3p/beopinion.js
  3p/integration.js
  ads/_config.js
  ads/ads.extern.js
  examples/ads.amp.html
  examples/beopinion.amp.html
  examples/beopinion.article.amp.html
  extensions/amp-ad/amp-ad.md
  extensions/amp-beopinion/0.1/amp-beopinion.js
  extensions/amp-beopinion/0.1/test/test-amp-beopinion.js
  extensions/amp-beopinion/0.1/test/validator-amp-beopinion.html
  extensions/amp-beopinion/0.1/test/validator-amp-beopinion.out
  extensions/amp-beopinion/amp-beopinion.md
  extensions/amp-beopinion/validator-amp-beopinion.protoascii
Labels: cla: yes

#13932 Add info for fill layout - parent needs position
  spec/amp-html-layout.md
Labels: cla: yes

#13929 Remove incorrect info on amp-img
  builtins/amp-img.md
Labels: cla: yes

#13942 Updating the WhatsApp share endpoint.
  examples/amp-story/bookend.json
  extensions/amp-social-share/0.1/amp-social-share-config.js
  extensions/amp-social-share/0.1/amp-social-share.js
Labels: cla: yes

#13798 Fix story desktop share-pill styles overriding before we use shadow DOM.
  extensions/amp-story/0.1/amp-story-desktop.css
  extensions/amp-story/0.1/amp-story.css
  extensions/amp-story/0.1/amp-story.js
Labels: cla: yes

#13931 Send an enum value of what kind of error we got for RTC
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-rtc.js
Labels: cla: yes

#13706 Add a way to insert new items at the bottom of the component
  build-system/app.js
  examples/live-list-update-reverse.amp.html
  extensions/amp-live-list/0.1/amp-live-list.js
  extensions/amp-live-list/0.1/test/test-amp-live-list.js
  tools/experiments/experiments.js
Labels: cla: yes

#13913 ♻️Change custom ad request batching
  extensions/amp-ad/0.1/amp-ad-custom.js
  extensions/amp-ad/0.1/test/test-amp-ad-custom.js
Labels: cla: yes

#13935 Add experiment to ignore USDRUD for doubleclick.
  extensions/amp-ad-network-doubleclick-impl/0.1/doubleclick-a4a-config.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-a4a-config.js
Labels: cla: yes

#13924 Fix SF config.
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
Labels: cla: yes

#13962 Fixes validation rules for amp-story-cta-layer and adds test 🐛
  extensions/amp-story/0.1/test/validator-amp-story-cta-layer-error.html
  extensions/amp-story/0.1/test/validator-amp-story-cta-layer-error.out
  extensions/amp-story/0.1/test/validator-amp-story-cta-layer.html
  extensions/amp-story/0.1/test/validator-amp-story-cta-layer.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#13963 Validator update
  extensions/amp-beopinion/0.1/test/validator-amp-beopinion.html
  extensions/amp-beopinion/0.1/test/validator-amp-beopinion.out
  extensions/amp-beopinion/validator-amp-beopinion.protoascii
  extensions/amp-subscriptions/0.1/test/validator-amp-subscriptions.html
  extensions/amp-subscriptions/0.1/test/validator-amp-subscriptions.out
  extensions/amp-subscriptions/validator-amp-subscriptions.protoascii
  validator/validator-main.protoascii
Labels: Category: Validator

#13944 Pass canonical URL on Safeframe metadata
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
Labels: cla: yes

#13909 Allow /ad/ as cache URL prefix.
  src/url.js
  test/functional/test-url.js
Labels: cla: yes

#13968 inabox: fix memory leak
  ads/inabox/position-observer.js
  examples/inabox.host.memory.html
Labels: cla: yes

#13957 change attribute sort="ascending" for live-list feature
  examples/live-list-update-reverse.amp.html
  extensions/amp-live-list/0.1/amp-live-list.js
  extensions/amp-live-list/0.1/test/test-amp-live-list.js
  extensions/amp-live-list/amp-live-list.md
  extensions/amp-live-list/validator-amp-live-list.protoascii
Labels: cla: yes

#13960 Wrap inabox binaries in function to prevent vars leaking to global window.
  gulpfile.js
Labels: cla: yes

#13943 🐛Fix two bugs in amp-access-scroll
  examples/scroll.amp.html
  extensions/amp-access-scroll/0.1/scroll-impl.js
Labels: cla: yes

#13978 <amp-accordion> Move expand-single-section attribute to correct validation section
  extensions/amp-accordion/validator-amp-accordion.protoascii
Labels: cla: yes

#13982 SauceLabs iOS 9.1 -> 9.3
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test.js
Labels: cla: yes

#13971 Upgrade to SwG 0.1.21-52536e3
  package.json
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
  yarn.lock
Labels: cla: yes

#13940 Pingback
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement-store.js
  extensions/amp-subscriptions/0.1/local-subscription-platform-renderer.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-local-subscription-rendering.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-viewer-tracker.js
  extensions/amp-subscriptions/0.1/viewer-tracker.js
Labels: cla: yes

#13839 ✨Added Rubicon as vendor in callout-vendors.js
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#13983 User abbreviated offers if access has been granted
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Labels: cla: yes

#13758 ♻️Small cleanup to SizeList
  src/size-list.js
Labels: cla: yes

#13908 Resource aware Vsync
  src/base-element.js
  src/service/layers-impl.js
  src/service/resources-impl.js
Labels: cla: yes

#13761 ♻️URL Relpacements: Simplify DocInfo Values
  src/service/url-replacements-impl.js
Labels: cla: yes

#13762 ♻️URL Replacements: Simplify AmpStoryVariables
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/test/test-variable-service.js
  extensions/amp-story/0.1/variable-service.js
  src/service/url-replacements-impl.js
  src/services.js
Labels: cla: yes

#13990 Update amp-cache-modifications
  spec/amp-cache-modifications.md
Labels: cla: yes

#13995 🚀Delay preconnects until doc is visible.
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-video/0.1/test/test-amp-video.js
  src/preconnect.js
  test/functional/test-preconnect.js
Labels: cla: yes

#13675 Introduces amp-ad-base, an abstract, lightweight, alternative to amp-a4a.
  extensions/amp-ad-network-base/0.1/amp-ad-network-base.js
  extensions/amp-ad-network-base/0.1/amp-ad-type-defs.js
  extensions/amp-ad-network-base/0.1/amp-ad-utils.js
Labels: cla: yes

#14001 Update amp-cache-modifications
  spec/amp-cache-modifications.md
Labels: cla: yes

#13996 Validator update
  extensions/amp-story/0.1/test/validator-amp-story-cta-layer-error.html
  extensions/amp-story/0.1/test/validator-amp-story-cta-layer-error.out
  extensions/amp-story/0.1/test/validator-amp-story-cta-layer.html
  extensions/amp-story/0.1/test/validator-amp-story-cta-layer.out
  validator/testdata/feature_tests/link_meta_values.html
  validator/testdata/feature_tests/link_meta_values.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#13999 Fix a dead link in integrating-analytics.md
  extensions/amp-analytics/integrating-analytics.md
Labels: cla: yes

#13970 Fix description animations
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  test/manual/amp-lightbox-gallery-launch.amp.html
Labels: cla: yes

#13994 Don't create thumbnails for <amp-ad> in <amp-lightbox-gallery>
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#14005 Allow amp-list with only [src] attribute
  extensions/amp-list/0.1/test/validator-amp-list.html
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/amp-list.md
  extensions/amp-list/validator-amp-list.protoascii
Labels: cla: yes

#13887 ✨ Handle header names in a case-insensitive manner when metadata is ret…
  ads/google/a4a/line-delimited-response-handler.js
  ads/google/a4a/test/test-line-delimited-response-handler.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes
