Repository ampproject/amphtml, pull requests merged in 2019-11, with the labels that each got.

#24866 Remove amp-youtube a4a deprecation notice
  extensions/amp-youtube/0.1/amp-youtube.js
Labels: cla: yes

#25357 Fix visibility manager resolution in shadow doc mode
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-analytics/0.1/visibility-manager.js
Labels: cla: yes

#24776 🚮 Removing mediaimpact integration
  3p/integration.js
  ads/_config.js
  ads/ads.extern.js
  ads/mediaimpact.js
  ads/mediaimpact.md
  examples/ads-legacy.amp.html
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
  validator/testdata/feature_tests/ads.html
  validator/testdata/feature_tests/ads.out
Labels: cla: yes

#25369 ✅ Skip flaky BTF integration test
  test/integration/test-amphtml-ads.js
Labels: Related to: Flaky Tests, cla: yes

#25094 shadowDoc: Return promise from close method
  spec/amp-shadow-doc.md
  src/runtime.js
  test/unit/test-runtime.js
Labels: cla: yes

#25014 amp-img: Cancel pending images on unlayout
  builtins/amp-img.js
Labels: WG: performance, cla: yes

#25376 🏗 Fix duplicate typedefs when linting
  build-system/eslint-rules/no-duplicate-name-typedef.js
Labels: cla: yes

#25380 Fix a bug that amp-carousel is not laying out children elements for inabox-lite.
  src/inabox/inabox-resources.js
Labels: cla: yes

#25373 🏗🚀 Enable concurrency for multi-pass `gulp dist` on Travis
  build-system/compile/compile.js
Labels: WG: infra, cla: yes

#25384 Remove access of ampdoc in AmpLinkRewriter's constructor.
  extensions/amp-link-rewriter/0.1/amp-link-rewriter.js
Labels: cla: yes

#25348 chromeextension: Fix regex test for amphtml
  validator/chromeextension/content_script.js
Labels: cla: yes

#25399 📖 typo
  ads/README.md
Labels: cla: yes

#24793 🐛 Recognize data-amp-bind-src as mandatory_anyof alternative to [src] in amp-list
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/validator-amp-list.protoascii
Labels: cla: yes

#25333 📖 Add Bing AMP cache to example caches
  spec/amp-cache-guidelines.md
Labels: cla: yes

#25385 ✨ SwG version 0.1.22.81
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#25295 Introduce AMP Live List Cache Busting
  build-system/test-configs/dep-check-config.js
  extensions/amp-live-list/0.1/live-list-manager.js
Labels: P1: High Priority, cla: yes

#25375 🐛 Attempt to fix LightboxGallery issue
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#25413 Fix test-resource.js. It is failing when ran alone.
  test/unit/test-resource.js
Labels: cla: yes

#25407 Add an autoplay video ad example.
  examples/amphtml-ads/many-ads.host.html
  examples/amphtml-ads/video-ad-autoplay.a4a.html
Labels: cla: yes

#25404 inabox-lite: setup input mode classes.
  src/inabox/inabox-resources.js
  src/input.js
  src/service/resources-impl.js
  test/unit/test-input.js
Labels: cla: yes

#25410 📖 Clarify readymade amp-video-iframe integration APIs
  extensions/amp-video-iframe/amp-video-iframe.md
Labels: cla: yes

#25293 Launch inabox-lite
  .eslintrc
  build-system/global-configs/canary-config.json
  build-system/global-configs/experiments-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-position-observer/0.1/test-e2e/test-amp-position-observer.js
  src/inabox/inabox-services.js
  src/inabox/inabox-viewport.js
Labels: cla: yes

#25425 Allow `<stop>` tag in SVG for stories
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#25422 Override pause/resumeCallback for Stories needs.
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#25405 🐛Escape left and right arrow keys in amp-carousel 0.1
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
Labels: cla: yes

#25424 Don't send video error metrics if autoplay was denied
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/media-performance-metrics-service.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
  extensions/amp-story/1.0/test/test-media-performance-metrics-service.js
Labels: cla: yes

#25421 SwG release 0.1.22.82
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#25445 🏗 Manually upgrade transitive validator dependencies with security vulnerabilities
  validator/package.json
  validator/yarn.lock
Labels: WG: caching, WG: infra, cla: yes

#24858 ♻️Story Ads: move page related logic to its own class
  build-system/test-configs/dep-check-config.js
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/story-ad-page.js
  extensions/amp-story-auto-ads/0.1/test/story-mock.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js
Labels: cla: yes

#25441 Narrow down script matching to avoid incorrect prefix matches
  src/service/extensions-impl.js
  test/unit/test-extensions.js
Labels: cla: yes

#25439 Validator rollup
  validator/build.py
  validator/engine/parse-css_test.js
  validator/validator-main.protoascii
Labels: cla: yes

#25372 ✅ Visual tests for <amp-mega-menu>
  examples/visual-tests/amp-mega-menu/amp-list-data.json
  examples/visual-tests/amp-mega-menu/amp-mega-menu-with-list.amp.html
  examples/visual-tests/amp-mega-menu/amp-mega-menu.amp.html
  examples/visual-tests/amp-mega-menu/amp-mega-menu.js
  examples/visual-tests/amp-mega-menu/img1.jpg
  examples/visual-tests/amp-mega-menu/img2.jpg
  test/visual-diff/visual-tests
Labels: cla: yes

#25416 Increase extension timeout to collect the failure data
  src/service/extensions-impl.js
Labels: cla: yes

#25440 Update Swg Amp extension to use new callbacks
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Labels: cla: yes

#25433 Ensure video element is upgraded to customElement before using signals.
  src/video-interface.js
Labels: cla: yes

#25355 Add sidebar 0.1 support for nested menu and guard behind experiment
  extensions/amp-nested-menu/0.1/amp-nested-menu.js
  extensions/amp-nested-menu/0.1/test/test-amp-nested-menu.js
  extensions/amp-sidebar/0.1/amp-sidebar.js
  test/manual/amp-nested-menu/amp-nested-menu-with-list.amp.html
  test/manual/amp-nested-menu/amp-nested-menu.amp.html
  tools/experiments/experiments-config.js
Labels: cla: yes

#25462 Update version notes
  validator/nodejs/README.md
Labels: cla: yes

#25471 Fix typo in filename for OWNERS file
  tools/experiments/OWNERS
Labels: cla: yes

#25470 Revert "🐛Expose amp-form response from SSR in `submit-success` and `submit-error` events."
  extensions/amp-form/0.1/amp-form.js
Labels: cla: yes

#25453 Enable layoutbox invalidate onscroll experiment in Canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#25442 Force cookies with SameSite=None to also include Secure
  src/cookies.js
  test/unit/test-cookies.js
  tools/experiments/experiments.js
Labels: cla: yes

#25477 🚀 Break infinite loop with loading container
  src/custom-element.js
  test/unit/test-custom-element.js
Labels: cla: yes

#25479 🐛 Check if any remeasures are necessary when nested scrollers scroll
  src/service/resources-impl.js
Labels: cla: yes

#21208 Make inabox iframe messenger send broadcast messages to find the window with the host script.
  3p/ampcontext.js
  3p/iframe-messaging-client.js
  3p/iframe-transport-client.js
  3p/recaptcha.js
  ads/inabox/inabox-messaging-host.js
  examples/amphtml-ads/ads-tag-integration.js
  src/inabox/inabox-iframe-messaging-client.js
  test/integration/test-amphtml-ads.js
  test/unit/3p/test-iframe-messaging-client.js
Labels: cla: yes

#25485 Fixes ampdoc related test failures.
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#25486 Update url to amp.dev
  validator/package.json
Labels: cla: yes

#24634 📈 ✨ Reintroduce storySpec with repeat option
  examples/amp-story/analytics.html
  extensions/amp-analytics/0.1/events.js
  extensions/amp-analytics/0.1/test/test-events.js
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
  extensions/amp-story/1.0/test/test-analytics.js
  test/integration/test-amp-story-analytics.js
Labels: cla: yes

#25456 Prerender amp-video poster image.
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-video/0.1/test/test-amp-video.js
Labels: cla: yes

#25414 Fire fluid delayed impression ping if creative has non-zero size.
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js
Labels: cla: yes

#24944 🐛♻️Refactor, changes to amp-base-carousel for amp-inline-gallery.
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/carousel-events.js
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-base-carousel/0.1/dimensions.js
  extensions/amp-carousel/0.2/amp-carousel.js
Labels: cla: yes

#25478 🏗 Use AES-GCM instead of AES-CTR in SwG Decryption
  extensions/amp-subscriptions/0.1/crypto-handler.js
  extensions/amp-subscriptions/0.1/test/test-crypto-handler.js
Labels: cla: yes

#25487 Remove sidebar 0.2 docs
  extensions/amp-sidebar/0.2/amp-sidebar.md.draft
Labels: cla: yes

#25503 🏗 Don't throw an error from the experiments config if an experiment is expired
  build-system/compile/build.conf.js
Labels: cla: yes

#25498 🐛 Only unlayout img if img exists
  builtins/amp-img.js
  test/unit/test-amp-img.js
Labels: cla: yes

#25497 ♻️ Tag batched JSON fetch failures as user errors
  src/batched-json.js
Labels: cla: yes

#25504 🐛 Update mowplayer version for `amp-mowplayer`
  extensions/amp-mowplayer/0.1/amp-mowplayer.js
  extensions/amp-mowplayer/0.1/test/test-amp-mowplayer.js
  extensions/amp-mowplayer/0.1/test/validator-amp-mowplayer.html
  extensions/amp-mowplayer/0.1/test/validator-amp-mowplayer.out
Labels: cla: yes

#25388 ✨Manual management of `amp-next-page` document visibility
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
  src/runtime.js
Labels: cla: yes

#25339 Add validation and documentation for <amp-nested-menu>
  examples/sidebar-nested-menu.html
  extensions/amp-nested-menu/0.1/amp-nested-menu.css
  extensions/amp-nested-menu/0.1/test/validator-amp-nested-menu-error.html
  extensions/amp-nested-menu/0.1/test/validator-amp-nested-menu-error.out
  extensions/amp-nested-menu/0.1/test/validator-amp-nested-menu.html
  extensions/amp-nested-menu/0.1/test/validator-amp-nested-menu.out
  extensions/amp-nested-menu/amp-nested-menu.md
  extensions/amp-nested-menu/validator-amp-nested-menu.protoascii
Labels: cla: yes

#25480 Launch amp-mega-menu to 100% of canary and production
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#25454 Deprecate amp-script[development] in favor of [data-ampdevmode]
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
  extensions/amp-script/amp-script.md
Labels: cla: yes

#25513 Retire ios-scrollable-iframe experiment from launch configs
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#24574 Add tests clarifying the behavior of layout intrinsic for amp-img
  test/unit/test-amp-img.js
  test/unit/test-resources.js
Labels: cla: yes

#25515 Add amp-form test for pre-existing redirection behavior
  extensions/amp-form/0.1/test/test-amp-form.js
Labels: cla: yes

#24922 fix(amp-yotpo):restore child iframe in layoutCallback
  extensions/amp-yotpo/0.1/amp-yotpo.js
Labels: cla: yes

#25327 Update amp-viewer-messaging README
  extensions/amp-viewer-integration/0.1/messaging/README.md
Labels: cla: yes

#25482 ✨ Launch the 'use responsive ads for responsive sizing in auto ads' experiment to a 5% holdback
  extensions/amp-auto-ads/0.1/amp-auto-ads.js
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
  extensions/amp-auto-ads/0.1/test/test-placement.js
Labels: cla: yes

#25540 📖Fix markup error
  extensions/amp-story/amp-story.md
Labels: cla: yes

#25507 📖 Updated to include Multi-size Ad examples
  ads/ix.md
Labels: cla: yes

#25539 ♻️Clean up amp-form test stubs handling Promises
  extensions/amp-form/0.1/test/test-amp-form.js
Labels: cla: yes

#25490 🐛 Fix transpiled detection in CEv1 polyfill
  src/polyfills/custom-elements.js
Labels: cla: yes

#25505 ♻️ Refactor `batchFetchJsonFor` by combining all options into an options bag.
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-next-page/0.1/amp-next-page.js
  extensions/amp-user-location/0.1/config-loader.js
  src/batched-json.js
  test/unit/test-batched-json.js
Labels: cla: yes

#25537 Send 'bindReady' even in dev mode
  extensions/amp-bind/0.1/bind-impl.js
Labels: cla: yes

#25541 SwG release 0.1.22.83
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#25519 Retire ios-scrollable-iframe experiment
  build-system/tasks/e2e/amp-driver.js
  examples/viewer-iframe-poll.html
  examples/viewer-webview.html
  examples/viewer.html
  extensions/amp-viewer-integration/0.1/viewer-for-testing.js
  extensions/amp-viewer-integration/0.1/viewer-initiated-handshake-viewer-for-testing.js
  extensions/amp-viewer-integration/0.1/webview-viewer-for-testing.js
  extensions/amp-viewer-integration/amp-doc-viewer-api.md
  src/service/viewport/viewport-impl.js
  test/unit/test-ampdoc.js
  test/unit/test-viewport.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#25533 Add Automatad to RTC Callout Vendors
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-a4a/rtc-documentation.md
  extensions/amp-a4a/rtc-publisher-implementation-guide.md
Labels: cla: yes

#25395 amp-ad integration - ucfunnel add new parameter
  ads/ucfunnel.js
  ads/ucfunnel.md
  examples/ads.amp.html
Labels: cla: yes

#25512 🐛 Pass through applicable AMP experiments to SwG
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Labels: cla: yes

#25552 Upgrade DOMPurify to 2.0.7
  package.json
  src/sanitation.js
  src/url-rewrite.js
  test/unit/test-purifier.js
  test/unit/test-sanitizer.js
  yarn.lock
Labels: cla: yes

#25559 Validator rollup
  extensions/amp-audio/0.1/test/validator-amp-audio.html
  extensions/amp-audio/0.1/test/validator-amp-audio.out
  validator/engine/validator.js
  validator/validator-main.protoascii
Labels: Category: Validator, WG: caching, cla: yes

#25401 Do not enforce amp-analytics 'requests' field for FIE
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
Labels: cla: yes

#25549 🐛Fix next carousel arrow showing up at the end.
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-base-carousel/0.1/test/test-carousel.js
Labels: cla: yes

#25502 ✨ Enable navigating pages through fragment params
  examples/amp-story/amp-story-branching.html
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#25501 ♻️Refactor error handling for amp-list load-more as not to throw needless errors
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list-load-more.js
  extensions/amp-list/0.1/test/test-amp-list.js
  test/manual/amp-list/infinite-scroll-fail.amp.html
Labels: cla: yes

#25557 🏗 Add a no-op experiment to investigate bias for amp-auto-ads experiment diversion
  extensions/amp-auto-ads/0.1/amp-auto-ads.js
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-auto-ads/0.1/test/test-placement.js
Labels: cla: yes

#25574 Prettifier fix
  extensions/amp-list/0.1/amp-list.js
Labels: cla: yes

#25577 Change to #contributing Slack channel for design reviews
  contributing/design-reviews.md
Labels: cla: yes

#25516 Launch amp-nested-menu to 100% of production and canary
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#25543 Handle amp-form SSR success and error responses explicitly
  extensions/amp-form/0.1/amp-form.js
Labels: cla: yes

#25066 Discontinue recursive form submissions in AMP4Email
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-accordion/0.1/amp-accordion.js
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-bind/0.1/test/test-amp-state.js
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation.js
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-truncate-text/0.1/amp-truncate-text.js
  extensions/amp-user-location/0.1/amp-user-location.js
  extensions/amp-viewer-assistance/0.1/amp-viewer-assistance.js
  src/action-constants.js
  src/base-element.js
  src/service/action-impl.js
  src/service/standard-actions-impl.js
  test/unit/test-action.js
  test/unit/test-custom-element-registry.js
Labels: cla: yes

#25580 🐛Fix initial sizing of the flying carpet area.
  extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
  extensions/amp-fx-flying-carpet/0.1/test/test-amp-fx-flying-carpet.js
Labels: cla: yes

#25250 Disable sidebar close animation on iOS back
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
Labels: cla: yes

#25130 [amp-ad] Add a4a (fast fetch) support to myTarget amp-ads
  ads/_a4a-config.js
  build-system/compile/bundles.config.js
  build-system/test-configs/dep-check-config.js
  examples/a4a.amp.html
  extensions/amp-ad-network-mytarget-impl/0.1/amp-ad-network-mytarget-impl.js
  extensions/amp-ad-network-mytarget-impl/0.1/mytarget-a4a-config.js
  extensions/amp-ad-network-mytarget-impl/0.1/test/test-amp-ad-network-mytarget-impl.js
  extensions/amp-ad-network-mytarget-impl/OWNERS
  extensions/amp-ad-network-mytarget-impl/amp-ad-network-mytarget-impl-internal.md
Labels: cla: yes

#25603 Reduce severity of shadow close timeout log
  src/runtime.js
Labels: cla: yes

#25583 🐛 amp-form test: fix test logic bug that would make it always pass
  extensions/amp-form/0.1/test/test-amp-form.js
Labels: cla: yes

#25620 Switching browser tab should not rewind story videos.
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#25461 Allow overriding the story URL info dialog.
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-utils.js
  extensions/amp-story/1.0/utils.js
Labels: cla: yes

#25565 🖍 Add shadow to loading spinner
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#25547 ✨📈 Add analytics trigger for elements that show a tooltip
  examples/amp-story/analytics.html
  extensions/amp-analytics/0.1/events.js
  extensions/amp-analytics/0.1/test/test-events.js
  extensions/amp-story/1.0/amp-story-affiliate-link.js
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-analytics.js
Labels: cla: yes

#25614 🐛 Rewrite urls for thumbnail images in bookend
  extensions/amp-story/1.0/bookend/components/article.js
  extensions/amp-story/1.0/bookend/components/landscape.js
  extensions/amp-story/1.0/bookend/components/portrait.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
  extensions/amp-story/1.0/utils.js
Labels: cla: yes

#25523 ✨Allow custom text in ASAA CTA
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/story-ad-button-text-fitter.js
  extensions/amp-story-auto-ads/0.1/story-ad-page.js
  extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js
Labels: cla: yes

#25646 SwG release 0.1.22.84
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#25648 🐛Fix attribution icon being centered incorrectly
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-attribution.css
  test/fixtures/e2e/amp-story-auto-ads/basic.html
Labels: cla: yes

#25465 🐛 inabox: support sending positions to ads with null origins
  ads/inabox/inabox-messaging-host.js
  test/unit/inabox/test-inabox-messaging-host.js
Labels: cla: yes

#25604 🐛Support amp-lightbox-gallery with amp-base-carousel
  extensions/amp-image-viewer/0.1/amp-image-viewer.css
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  test/manual/amp-base-carousel/basic.amp.html
  test/manual/amp-base-carousel/fixed-children.amp.html
  test/manual/amp-base-carousel/mixed-lengths-no-snap.amp.html
  test/manual/amp-base-carousel/mixed-lengths.amp.html
  test/manual/amp-base-carousel/vertical.amp.html
Labels: cla: yes

#25647 🏗 Use in-process `gulp` server during `visual-diff` and `e2e`
  build-system/server/app-utils.js
  build-system/tasks/build.js
  build-system/tasks/e2e/index.js
  build-system/tasks/serve.js
  build-system/tasks/visual-diff/index.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#25651 📖 Update enable-git-pre-push.sh with correct file path
  build-system/common/enable-git-pre-push.sh
Labels: cla: yes

#25622 Launch inabox-viewport-friendly
  ads/inabox/inabox-host.md
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  build-system/server/routes/a4a-envelopes.js
  src/inabox/inabox-iframe-messaging-client.js
  src/inabox/inabox-viewport.js
  test/integration/test-amphtml-ads.js
  test/unit/inabox/test-inabox-viewport.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#24547 updated carousel example to work in playground
  extensions/amp-carousel/0.1/amp-carousel.md
  extensions/amp-carousel/amp-carousel.md
Labels: cla: yes

#25654 🐛Fix weird border on some story ads
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
Labels: cla: yes

#25349 📖CORS fonts
  spec/amp-cors-requests.md
Labels: cla: yes

#25591 amp-script: Improve "state passing" and "AMP elements" docs
  extensions/amp-script/amp-script.md
Labels: cla: yes

#25672 Update OWNERS for amp-access
  extensions/amp-access/OWNERS
Labels: cla: yes

#25459 📖 updated extension generator markdown template
  build-system/tasks/extension-generator/extension-doc.template.md
Labels: cla: yes

#24671 ✨amp-form: Initialize form from URL
  examples/amp-form-initialization-test.html
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-form/amp-form.md
Labels: cla: yes

#25652 🏗 Add APPROVERS.json to enable blocking bundle-size checks for extensions
  build-system/tasks/bundle-size/APPROVERS.json
  build-system/tasks/bundle-size/README.md
  build-system/tasks/bundle-size/index.js
Labels: cla: yes

#25691 ✅ Skip ads `cross-domain rendering` test
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
Labels: Related to: Flaky Tests, WG: ads, cla: yes

#25692 Skip flaky tests
  extensions/amp-image-lightbox/0.1/test/integration/test-amp-image-lightbox.js
  test/visual-diff/visual-tests
Labels: cla: yes

#25667 🚀 update speakol amp-ad
  ads/speakol.js
Labels: cla: yes

#25649 📈✨ Add data-vars support and tests for amp-story-analytics
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
  test/integration/test-amp-story-analytics.js
Labels: cla: yes

#25698 🐛Use `env.sandbox` in `test-amp-story-embedded-component.js`
  extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
Labels: Related to: Flaky Tests, WG: stories, cla: yes

#25693 Change OWNERS of amp-consent to wg-analytics & wg-ads
  extensions/amp-consent/OWNERS
Labels: cla: yes

#25679 📖Update `gulp visual-diff` instructions in TESTING.md
  contributing/TESTING.md
Labels: cla: yes

#25704 Validator Rollup (s/GRANDFATHERED/EXEMPTED/)
  extensions/amp-access/validator-amp-access.protoascii
  extensions/amp-accordion/validator-amp-accordion.protoascii
  extensions/amp-ad/validator-amp-ad.protoascii
  extensions/amp-analytics/validator-amp-analytics.protoascii
  extensions/amp-anim/validator-amp-anim.protoascii
  extensions/amp-apester-media/validator-amp-apester-media.protoascii
  extensions/amp-audio/validator-amp-audio.protoascii
  extensions/amp-bind/validator-amp-bind.protoascii
  extensions/amp-brid-player/validator-amp-brid-player.protoascii
  extensions/amp-brightcove/validator-amp-brightcove.protoascii
  extensions/amp-call-tracking/validator-amp-call-tracking.protoascii
  extensions/amp-carousel/validator-amp-carousel.protoascii
  extensions/amp-dailymotion/validator-amp-dailymotion.protoascii
  extensions/amp-experiment/validator-amp-experiment.protoascii
  extensions/amp-facebook/validator-amp-facebook.protoascii
  extensions/amp-fit-text/validator-amp-fit-text.protoascii
  extensions/amp-font/validator-amp-font.protoascii
  extensions/amp-form/validator-amp-form.protoascii
  extensions/amp-fx-flying-carpet/validator-amp-fx-flying-carpet.protoascii
  extensions/amp-gfycat/validator-amp-gfycat.protoascii
  extensions/amp-iframe/validator-amp-iframe.protoascii
  extensions/amp-image-lightbox/validator-amp-image-lightbox.protoascii
  extensions/amp-inputmask/validator-amp-inputmask.protoascii
  extensions/amp-instagram/validator-amp-instagram.protoascii
  extensions/amp-install-serviceworker/validator-amp-install-serviceworker.protoascii
  extensions/amp-izlesene/validator-amp-izlesene.protoascii
  extensions/amp-jwplayer/validator-amp-jwplayer.protoascii
  extensions/amp-kaltura-player/validator-amp-kaltura-player.protoascii
  extensions/amp-lightbox/validator-amp-lightbox.protoascii
  extensions/amp-list/validator-amp-list.protoascii
  extensions/amp-live-list/validator-amp-live-list.protoascii
  extensions/amp-mustache/validator-amp-mustache.protoascii
  extensions/amp-o2-player/validator-amp-o2-player.protoascii
  extensions/amp-pinterest/validator-amp-pinterest.protoascii
  extensions/amp-reach-player/validator-amp-reach-player.protoascii
  extensions/amp-selector/validator-amp-selector.protoascii
  extensions/amp-sidebar/validator-amp-sidebar.protoascii
  extensions/amp-social-share/validator-amp-social-share.protoascii
  extensions/amp-soundcloud/validator-amp-soundcloud.protoascii
  extensions/amp-springboard-player/validator-amp-springboard-player.protoascii
  extensions/amp-sticky-ad/validator-amp-sticky-ad.protoascii
  extensions/amp-twitter/validator-amp-twitter.protoascii
  extensions/amp-user-notification/validator-amp-user-notification.protoascii
  extensions/amp-vimeo/validator-amp-vimeo.protoascii
  extensions/amp-vine/validator-amp-vine.protoascii
  extensions/amp-youtube/validator-amp-youtube.protoascii
  validator/engine/validator.js
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: cla: yes

#25705 Validator Rollup
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#25673 Create owners for amp-access-laterpay
  extensions/amp-access-laterpay/0.2/OWNERS
Labels: cla: yes

#25707 ✅ Moves `expect` calls to top level in test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Labels: cla: yes

#25639 🚮Remove <amp-user-location>
  build-system/compile/bundles.config.js
  build-system/server/app.js
  build-system/server/routes/user-location.js
  examples/amp-user-location.amp.html
  examples/amp-user-location.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-user-location/0.1/amp-user-location.js
  extensions/amp-user-location/0.1/config-loader.js
  extensions/amp-user-location/0.1/position-error.js
  extensions/amp-user-location/0.1/test/test-amp-user-location.js
  extensions/amp-user-location/0.1/test/test-config-loader.js
  extensions/amp-user-location/0.1/test/test-user-location-service.js
  extensions/amp-user-location/0.1/test/validator-amp-user-location.html
  extensions/amp-user-location/0.1/test/validator-amp-user-location.out
  extensions/amp-user-location/0.1/user-location-service.js
  extensions/amp-user-location/0.1/user-location.js
  extensions/amp-user-location/OWNERS
  extensions/amp-user-location/amp-user-location.md
  extensions/amp-user-location/validator-amp-user-location.protoascii
  spec/amp-var-substitutions.md
  src/mode.js
  src/service/url-replacements-impl.js
  src/services.js
  test/unit/test-url-replacements.js
Labels: cla: yes

#25666 🐛 amp-access-poool: Fix wrong usage of global document object
  extensions/amp-access-poool/0.1/poool-impl.js
Labels: cla: yes

#25718 📖Update amp-carousel 0.1 documentation for `type="slides"`
  extensions/amp-carousel/0.1/amp-carousel.md
Labels: cla: yes

#25721 Move amp-consent examples
  examples/amp-consent/amp-consent-iframe.amp.html
  examples/amp-consent/amp-consent.amp.html
  examples/amp-consent/cmp-vendors.amp.html
  examples/amphtml-ads/consent.a4a.html
  extensions/amp-consent/integrating-consent.md
Labels: cla: yes

#25676 Amp-consent CCPA feature flag
  extensions/amp-consent/0.1/amp-consent.js
  test/manual/amp-consent-geooveride.html
  tools/experiments/experiments-config.js
Labels: cla: yes

#25671 Create OWNERS for amp-access-poool
  extensions/amp-access-poool/OWNERS
Labels: cla: yes

#25689 <amp-consent> Support for consentRequired and geoOverride config fields
  build-system/test-configs/dep-check-config.js
  examples/amp-consent-geooveride.html
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-config.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-config.js
Labels: cla: yes

#25706 amp-ad integration - ucfunnel change parameter to optional
  ads/ucfunnel.js
  ads/ucfunnel.md
Labels: cla: yes

#25731 📖 Add documentation for bookend click analytics
  extensions/amp-story/amp-story-analytics.md
Labels: cla: yes

#25571 🏗Set amp-auto-ad-no-op experiment traffic fraction to 5%.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#25728 📖 Documentation for branching
  extensions/amp-story/amp-story.md
Labels: cla: yes

#25742 Allow next-page-no-ad in stories
  extensions/amp-story/1.0/test/validator-amp-story-next-page-no-ad.html
  extensions/amp-story/1.0/test/validator-amp-story-next-page-no-ad.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#25739 ✨Copy AES-GCM encryption function to AMP.
  third_party/subscriptions-project/aes_gcm.js
Labels: cla: yes

#25743 Bump Preact to v10
  package.json
  third_party/react-dates/build.sh
  third_party/react-dates/bundle.js
  third_party/react-dates/debug.sh
  yarn.lock
Labels: cla: yes

#25727 Deflake FIE and amp-iframe tests executed on the running runtime
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
  src/service/resource.js
Labels: cla: yes

#25747 🐛Allow zero vals for in validateData
  3p/3p.js
  test/unit/test-3p.js
Labels: cla: yes

#25696 <amp-consent> Support consentRequired and deprecate promptIfUnknownForGeo
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-config.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-config.js
Labels: cla: yes

#25761 🐛amp-access-poool: Fix missing usage of mutateElement
  examples/article-access-poool.amp.html
  extensions/amp-access-poool/0.1/poool-impl.js
Labels: cla: yes

#25762 🐛Turn SwG gpay 100% in canary and 10% in prod.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#25699 <amp-consent> add machtedGeoGroups to request
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-config.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
Labels: cla: yes

#25495 ✨Add amp-story-quiz component to Stories format
  build-system/compile/bundles.config.js
  examples/amp-story/quiz.html
  extensions/amp-story/1.0/amp-story-quiz.css
  extensions/amp-story/1.0/amp-story-quiz.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/test/test-amp-story-quiz.js
Labels: cla: yes

#25763 Fix reloading for 'latest' extension versions
  src/service/extension-location.js
  src/service/extensions-impl.js
  test/unit/test-extension-location.js
  test/unit/test-extensions.js
Labels: cla: yes

#25677 🐛 Improvements for embedded tweets
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#25746 ✅ Moves `expect` calls to top level in `amp-subscriptions` tests
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/test/test-actions.js
  extensions/amp-subscriptions/0.1/test/test-crypto-handler.js
  extensions/amp-subscriptions/0.1/test/test-dialog.js
  extensions/amp-subscriptions/0.1/test/test-local-subscription-rendering.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions-iframe-platform.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-platform-store.js
  extensions/amp-subscriptions/0.1/test/test-renderer.js
  extensions/amp-subscriptions/0.1/test/test-url-builder.js
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  extensions/amp-subscriptions/0.1/test/test-viewer-tracker.js
Labels: cla: yes
