Repository ampproject/amphtml, pull requests merged in 2019-06, with the labels that each got.

#22494 Move shared CSS from ampdoc.css to ampelement.css
  css/ampdoc.css
  css/ampshared.css
  src/amp.js
  src/inabox/amp-inabox-lite.js
  src/inabox/amp-inabox.js
  src/runtime.js
  src/service/extensions-impl.js
  testing/describes.js
  testing/iframe.js
Labels: cla: yes

#22633 🐛 Fix `.codecov.yaml`
  .codecov.yml
Labels: Category: Tooling, cla: yes

#22588 Add services to overridekeys for addthis
  extensions/amp-addthis/0.1/addthis-utils/get-widget-id-overloaded-with-json-for-anonymous-mode.js
Labels: cla: yes

#22635 🏗♻️ Refactor and speed up unminified builds
  build-system/tasks/helpers.js
  package.json
  yarn.lock
Labels: Category: Tooling, cla: yes

#22613 🐛amp-call-tracking: Made the 'phoneNumber' field optional
  extensions/amp-call-tracking/0.1/amp-call-tracking.js
  extensions/amp-call-tracking/0.1/test/test-amp-call-tracking.js
Labels: cla: yes

#22603 Handling the lifecycle of AMP components within an attachment.
  extensions/amp-story/1.0/amp-story-page-attachment.js
Labels: cla: yes

#22642 Replacing story attachment data-dark-mode with theme.
  extensions/amp-story/1.0/amp-story-page-attachment-header.css
  extensions/amp-story/1.0/amp-story-page-attachment.css
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/amp-story.md
Labels: cla: yes

#22580 Remove onBodyAvailable from doc-state service. Start deprecation.
  build-system/tasks/presubmit-checks.js
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
  extensions/amp-story/1.0/test/test-full-bleed-animations.js
  extensions/amp-story/1.0/test/test-live-story-manager.js
  src/dom.js
  src/runtime.js
  src/service/document-state.js
  src/service/viewer-impl.js
  src/service/vsync-impl.js
  src/services.js
  test/integration/test-visibility-states.js
  test/unit/test-activity.js
  test/unit/test-ampdoc.js
  test/unit/test-cid.js
  test/unit/test-custom-element-registry.js
  test/unit/test-document-state.js
  test/unit/test-dom.js
  test/unit/test-runtime.js
  test/unit/test-viewer.js
  test/unit/test-viewport-binding.js
  test/unit/test-viewport.js
Labels: cla: yes

#22643 Attachment theme validation.
  extensions/amp-story/1.0/test/validator-amp-story-page-attachment-error.html
  extensions/amp-story/1.0/test/validator-amp-story-page-attachment-error.out
  extensions/amp-story/1.0/test/validator-amp-story-page-attachment.html
  extensions/amp-story/1.0/test/validator-amp-story-page-attachment.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#22634 🏗 Fix code coverage logging on Travis
  build-system/tasks/codecov-upload.js
  build-system/travis.js
Labels: Category: Tooling, cla: yes

#22653 🚮Remove autosuggest examples and assets
  build-system/app.js
  build-system/routes/list.js
  examples/autosuggest.amp.html
  examples/countries.json
  extensions/amp-bind/0.1/test/validator-autosuggest.html
  extensions/amp-bind/0.1/test/validator-autosuggest.out
Labels: cla: yes

#22656 Fix typo in e2e doc
  build-system/tasks/e2e/README.md
Labels: cla: yes

#22606 🏗 Create gulp unit
  build-system/default-pre-push
  build-system/pr-check/build-targets.js
  build-system/pr-check/local-tests.js
  build-system/pr-check/remote-tests.js
  build-system/tasks/css.js
  build-system/tasks/pr-check.js
  build-system/tasks/report-test-status.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/unit.js
  gulpfile.js
Labels: cla: yes

#22659 🏗♻️ Refactor / clean up the `watch` logic used for extensions
  build-system/tasks/build.js
  build-system/tasks/css.js
  build-system/tasks/dist.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
  gulpfile.js
Labels: Category: Tooling, cla: yes

#22419 ✨amp-experiment 1.0: Allow an `#amp-x_disable_all_experiments_` to disable all experiments
  examples/experiment-1.0.amp.html
  extensions/amp-experiment/1.0/amp-experiment.js
  extensions/amp-experiment/1.0/test/test-amp-experiment.js
  extensions/amp-experiment/1.0/test/test-variant.js
  extensions/amp-experiment/1.0/variant.js
Labels: cla: yes

#22640 ✨ FEATURE: AMP form dirtiness indicator class
  extensions/amp-form/0.1/form-dirtiness.js
  extensions/amp-form/0.1/test/test-form-dirtiness.js
Labels: cla: yes

#22655 ♻️ Replace usage of pagesCount with page_ids.length
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/pagination-buttons.js
Labels: Category: AMP Story, cla: yes

#22508 🐛Fix broken args in expander.
  extensions/amp-analytics/0.1/test/test-variables.js
  src/service/url-expander/expander.js
Labels: cla: yes

#22531 📖 Splits and updates AMP for Email spec.
  spec/amp-email-format.md
  spec/email/amp-email-components.md
  spec/email/amp-email-css.md
  spec/email/amp-email-format.md
  spec/email/amp-email-html.md
  spec/email/amp-email-structure.md
Labels: Category: Email, Related to: Documentation, cla: yes

#22663 Ramp up the force prerender experiment from 1% to 10%.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#22680 🐛 Fix sauce
  build-system/tasks/karma.conf.js
Labels: cla: yes

#22664 Turn on 'inabox-remove-height-auto'
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#22510 getHighestAvailableDomain helper method
  src/cookies.js
  test/unit/test-cookies.js
  testing/fake-dom.js
Labels: cla: yes

#22528 ✨ Adds generator for JSON version of the validator spec
  .travis.yml
  validator/README.md
  validator/build.py
  validator/validator_gen_js.py
Labels: cla: yes

#22471 add browsers option to e2e task
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/index.js
Labels: cla: yes

#21508 📖 Add references to amp-twitter
  extensions/amp-story/amp-story.md
Labels: Category: AMP Story, cla: yes

#22598 ✅ Remove special casing for tests from amp-mustache extension registration
  build-system/babel-plugins/babel-plugin-transform-amp-extension-call/test/fixtures/transform-call/transform-simple-body/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-extension-call/test/fixtures/transform-call/transform-simple-body/output.js
  extensions/amp-mustache/0.1/amp-mustache.js
  extensions/amp-mustache/0.2/amp-mustache.js
  src/service/template-impl.js
Labels: cla: yes

#22483 ✨ Add custom cookie expiration
  extensions/amp-analytics/0.1/cookie-writer.js
  extensions/amp-analytics/0.1/test/test-cookie-writer.js
Labels: cla: yes

#22674 ♻️Cleanup e2e test endpoints and remove unused screenshot calls
  build-system/app-test.js
  build-system/app.js
  build-system/routes/test.js
  extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
  extensions/amp-base-carousel/0.1/test-e2e/test-non-looping.js
  extensions/amp-base-carousel/0.1/test-e2e/test-vertical.js
  extensions/amp-form/0.1/test-e2e/test-ssr.js
  extensions/amp-list/0.1/test-e2e/test-load-more-auto.js
  extensions/amp-list/0.1/test-e2e/test-load-more-manual.js
  extensions/amp-list/0.1/test-e2e/test-ssr.js
  test/fixtures/e2e/amp-bind/bind-form.html
  test/fixtures/e2e/amp-date-picker/blocked-dates.html
Labels: cla: yes

#22047 ✅ Add second visual test for amp-autocomplete
  examples/visual-tests/amp-autocomplete/amp-autocomplete.amp.html
  examples/visual-tests/amp-autocomplete/amp-autocomplete.js
Labels: cla: yes

#22684 Viewer messaging to select the next/previous document.
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/events.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#22676 📖 Adds CSS section to AMP for Email spec.
  spec/email/amp-email-css.md
  spec/email/amp-email-html.md
  spec/email/amp-email-structure.md
Labels: Category: Email, cla: yes

#22657 Override global scrollY/pageYOffset in iOS embed cases
  src/service/viewport/viewport-impl.js
  test/unit/test-viewport.js
Labels: cla: yes

#22670 ✨ amp-subscriptions-google "smartbox" support
  examples/amp-subscriptions-smartbox.amp.html
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  validator/validator-main.protoascii
Labels: cla: yes

#22669 📖 Add frontmatter key to experimental components
  extensions/amp-autocomplete/amp-autocomplete.md
  extensions/amp-base-carousel/amp-base-carousel.md
  extensions/amp-google-vrview-image/amp-google-vrview-image.md
  extensions/amp-next-page/amp-next-page.md
  extensions/amp-pan-zoom/amp-pan-zoom.md
  extensions/amp-script/amp-script.md
  extensions/amp-truncate-text/amp-truncate-text.md
  extensions/amp-user-location/amp-user-location.md
  extensions/amp-viz-vega/amp-viz-vega.md
Labels: cla: yes

#22696 🐛Fix broken cookie writer test
  build-system/pr-check/build.js
  build-system/pr-check/dist-bundle-size.js
  extensions/amp-analytics/0.1/test/test-cookie-writer.js
Labels: cla: yes

#22622 Removes uses of "AMP Project"
  GOVERNANCE.md
  SUPPORT.md
  ads/README.md
  ads/_integration-guide.md
  ads/google/a4a/docs/Network-Impl-Guide.md
  ads/google/a4a/docs/RTBExchangeGuide.md
  contributing/CODE_OWNERSHIP.md
  contributing/DEVELOPING.md
  contributing/creating-a-welcoming-community.md
  contributing/creating-good-first-issues.md
  contributing/design-reviews.md
  contributing/getting-started-e2e.md
  contributing/good-first-issues-template.md
  extensions/amp-analytics/amp-analytics.md
  extensions/amp-analytics/why-not-iframe.md
  extensions/amp-geo/amp-geo.md
  spec/amp-cache-guidelines.md
  spec/amp-versioning-policy.md
Labels: cla: yes

#22695 amp-ad doubleclick SRA - combine common key/values into single parameter
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/sra-utils.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
Labels: cla: yes

#22671 ✨ FEATURE: record form field's submitted value
  extensions/amp-form/0.1/form-dirtiness.js
  extensions/amp-form/0.1/test/test-form-dirtiness.js
Labels: cla: yes

#22646 Change Addthis teaser metadata
  extensions/amp-addthis/OWNERS.yaml
  extensions/amp-addthis/amp-addthis.md
Labels: cla: yes

#22707 ✅ Add remaining chai properties and refactor
  build-system/tasks/e2e/expect.js
Labels: cla: yes

#22630 Remove verification of the AMP-Access-Control-Allow-Source-Origin
  build-system/amp.extern.js
  extensions/amp-a4a/0.1/test/test-a4a-integration.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-access/0.1/amp-access-server-jwt.js
  extensions/amp-access/0.1/amp-access-server.js
  extensions/amp-access/0.1/test/test-amp-access-client.js
  extensions/amp-access/0.1/test/test-amp-access-server-jwt.js
  extensions/amp-access/0.1/test/test-amp-access-server.js
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-config.js
  extensions/amp-apester-media/0.1/amp-apester-media.js
  extensions/amp-app-banner/0.1/amp-app-banner.js
  extensions/amp-auto-ads/0.1/amp-auto-ads.js
  extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-live-list/0.1/live-list-manager.js
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
  extensions/amp-pinterest/0.1/pin-widget.js
  extensions/amp-pinterest/0.1/save-button.js
  extensions/amp-story/0.1/amp-story-request-service.js
  extensions/amp-story/0.1/test/test-amp-story-request-service.js
  extensions/amp-story/1.0/amp-story-request-service.js
  extensions/amp-story/1.0/test/test-amp-story-request-service.js
  extensions/amp-user-notification/0.1/amp-user-notification.js
  extensions/amp-viz-vega/0.1/amp-viz-vega.js
  src/batched-json.js
  src/document-fetcher.js
  src/impression.js
  src/service/xhr-impl.js
  src/ssr-template-helper.js
  src/utils/xhr-utils.js
  test/unit/test-batched-json.js
  test/unit/test-impression.js
  test/unit/test-ssr-template-helper.js
  test/unit/test-xhr-document-fetcher.js
  test/unit/test-xhr-fetch-polyfill.js
  test/unit/test-xhr.js
  test/unit/utils/test-xhr-utils.js
Labels: cla: yes

#22660 Move private amp-accordion CSS into the extension
  bundles.config.js
  css/ampshared.css
  extensions/amp-accordion/0.1/amp-accordion.css
  extensions/amp-accordion/0.1/amp-accordion.js
Labels: cla: yes

#22687 Validator rollup
  extensions/amp-access/validator-amp-access.protoascii
  extensions/amp-accordion/validator-amp-accordion.protoascii
  extensions/amp-ad-exit/validator-amp-ad-exit.protoascii
  extensions/amp-analytics/validator-amp-analytics.protoascii
  extensions/amp-anim/validator-amp-anim.protoascii
  extensions/amp-animation/validator-amp-animation.protoascii
  extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
  extensions/amp-bind/validator-amp-bind.protoascii
  extensions/amp-carousel/validator-amp-carousel.protoascii
  extensions/amp-consent/validator-amp-consent.protoascii
  extensions/amp-experiment/validator-amp-experiment.protoascii
  extensions/amp-geo/validator-amp-geo.protoascii
  extensions/amp-link-rewriter/validator-amp-link-rewriter.protoascii
  extensions/amp-list/validator-amp-list.protoascii
  extensions/amp-mustache/validator-amp-mustache.protoascii
  extensions/amp-payment-google-button/validator-amp-payment-google-button.protoascii
  extensions/amp-payment-google-inline-async/validator-amp-payment-google-inline-async.protoascii
  extensions/amp-payment-google-inline/validator-amp-payment-google-inline.protoascii
  extensions/amp-story-auto-ads/validator-amp-story-auto-ads.protoascii
  extensions/amp-story/1.0/test/validator-amp-story-sidebar-error.html
  extensions/amp-story/validator-amp-story.protoascii
  extensions/amp-subscriptions/validator-amp-subscriptions.protoascii
  extensions/amp-user-location/validator-amp-user-location.protoascii
  extensions/amp-viewer-assistance/validator-amp-viewer-assistance.protoascii
  validator/build.py
  validator/engine/validator_test.js
  validator/testdata/amp4email_feature_tests/amp_list.out
  validator/testdata/amp4email_feature_tests/nonce_disallowed.html
  validator/testdata/amp4email_feature_tests/nonce_disallowed.out
  validator/testdata/feature_tests/three_second_boilerplate.html
  validator/testdata/feature_tests/three_second_boilerplate.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#22712 Linker: change default behavior to decorate all subdomains (if can be found)
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
Labels: cla: yes

#22649 Make sure SR reads index of list options in amp-autocomplete
  extensions/amp-accordion/0.1/amp-accordion.js
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
Labels: cla: yes

#22710 Analytics trigger when opening/closing the story page attachment.
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/story-analytics.js
Labels: cla: yes

#22720 🐛amp-brightcove: Redispatch loadedmetadata event
  extensions/amp-brightcove/0.1/amp-brightcove.js
  extensions/amp-brightcove/0.1/test/test-amp-brightcove.js
Labels: cla: yes

#22645 Remove AMP-Access-Control-Allow-Source-Origin from test server
  build-system/amp-cors.js
  build-system/amp4test.js
  build-system/app.js
  build-system/routes/test.js
  build-system/test-server.js
  examples/amp-form.ssr.html
  examples/forms.amp.html
  examples/recaptcha.amp.html
  examples/viewer.html
Labels: cla: yes

#22604 Install Timer service directly instead of adopting
  src/service/extensions-impl.js
  src/service/timer-impl.js
  test/unit/test-extensions.js
Labels: cla: yes

#22546 🐛Make handling of history state responses more robust.
  src/service/history-impl.js
  test/unit/test-history.js
Labels: cla: yes

#22600 Bypass xhr interceptor for amp-worker invocation
  build-system/amp.extern.js
  src/utils/xhr-utils.js
  src/web-worker/amp-worker.js
  test/unit/utils/test-xhr-utils.js
  test/unit/web-worker/test-amp-worker.js
Labels: cla: yes

#22713 Use css.js for autoplay styles
  build-system/tasks/css.js
Labels: cla: yes

#22724 Making sure the consent UI AMP element is upgraded before calling whenBuilt.
  extensions/amp-consent/0.1/consent-ui.js
Labels: cla: yes

#22464 Add OT link in amp-script documentation
  extensions/amp-script/amp-script.md
Labels: cla: yes

#22731 Luanch ampdoc-closest on PROD to 100%
  build-system/global-configs/prod-config.json
Labels: cla: yes

#22730 📖amp-consent: Add Didomi CMP documentation + example (rebase)
  examples/cmp-vendors.amp.html
  extensions/amp-consent/amp-consent.md
  extensions/amp-consent/cmps/didomi.md
Labels: cla: yes

#22719 🐛Fix zucks ad return timing
  ads/zucks.js
  examples/ads.amp.html
Labels: cla: yes

#22729 ♻️ Analytics and variable service refactoring
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-analytics.js
  extensions/amp-story/1.0/variable-service.js
  src/services.js
Labels: Category: AMP Story, cla: yes

#22738 Fix amp-sidebar scrolling on open/close in UIWebView
  extensions/amp-sidebar/0.1/amp-sidebar.js
Labels: cla: yes

#22708 Cleanup `amp-autocomplete` experiment.
  examples/autocomplete.amp.html
  examples/visual-tests/amp-autocomplete/amp-autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
  extensions/amp-autocomplete/amp-autocomplete.md
  tools/experiments/experiments.js
Labels: cla: yes

#22728 Add explanatory comment
  build-system/tasks/css.js
Labels: cla: yes

#22754 Update story viewport size styles in prerender.
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#22761 Rename reported test status from `local_changes` to `local-changes`
  build-system/tasks/report-test-status.js
Labels: cla: yes

#22702 amp-list-load-more validator rules change
  extensions/amp-list/0.1/test/validator-amp-list.html
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/validator-amp-list.protoascii
  validator/validator.proto
Labels: cla: yes

#22709 ✨ Integrate `amp-form-dirty` into AMP form
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
Labels: cla: yes

#22766 Launch the force prerender experiment.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#22762 📖 Update testing documentation
  ads/README.md
  build-system/tasks/pr-check.js
  contributing/TESTING.md
  contributing/buildcop.md
  contributing/building-an-amp-extension.md
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
  contributing/good-first-issues-template.md
Labels: cla: yes

#22760 ✨ Adding 'allow-popups' to the consent prompt UI iframe
  extensions/amp-consent/0.1/consent-ui.js
Labels: cla: yes

#22615 Added Strossle to AMP solutions
  3p/integration.js
  ads/_config.js
  ads/strossle.js
  ads/strossle.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#22718 Include child margin-bottom in content height
  src/service/viewport/viewport-binding-def.js
  src/service/viewport/viewport-binding-ios-embed-sd.js
  src/service/viewport/viewport-binding-ios-embed-wrapper.js
  src/service/viewport/viewport-binding-natural.js
  tools/experiments/experiments.js
Labels: cla: yes

#22751 Enable "margin-bottom-in-content-height" in canary/prod
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#22732 Move core service installation into core-services.js for easier refactoring
  build-system/tasks/presubmit-checks.js
  src/amp-shadow.js
  src/amp.js
  src/inabox/amp-inabox-lite.js
  src/inabox/amp-inabox.js
  src/runtime.js
  src/service/core-services.js
  src/service/extensions-impl.js
  test/_init_tests.js
  test/unit/test-performance.js
  test/unit/test-runtime.js
  testing/describes.js
  testing/iframe.js
Labels: cla: yes

#22753 Linker: fix handling of fragments
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
Labels: cla: yes

#22511 Remove several getServiceForDoc() in extensions/*
  build-system/tasks/presubmit-checks.js
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/integration/test-integration-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-fx-collection/0.1/providers/fx-provider.js
  extensions/amp-inputmask/0.1/text-mask.js
  extensions/amp-live-list/0.1/amp-live-list.js
  extensions/amp-live-list/0.1/live-list-manager.js
  extensions/amp-live-list/0.1/test/test-amp-live-list.js
  extensions/amp-live-list/0.1/test/test-live-list-manager.js
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-position-observer/0.1/amp-position-observer.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  extensions/amp-user-notification/0.1/test/test-amp-user-notification.js
  extensions/amp-video-docking/0.1/amp-video-docking.js
  extensions/amp-web-push/0.1/amp-web-push-config.js
  extensions/amp-web-push/0.1/web-push-service.js
  src/services.js
Labels: cla: yes

#22788 fix type narrowing problem so that we can remove casts
  extensions/amp-experiment/0.1/amp-experiment.js
  extensions/amp-experiment/1.0/amp-experiment.js
  extensions/amp-story/1.0/amp-story-share.js
  src/log.js
Labels: cla: yes

#22797 ♻️ amp-twitter: remove old loader code in preparation for new loaders.
  bundles.config.js
  extensions/amp-twitter/0.1/amp-twitter.css
  extensions/amp-twitter/0.1/amp-twitter.js
Labels: cla: yes

#22773 ✨ Implement src attribute and script config
  examples/amp-user-location.amp.html
  examples/amp-user-location.json
  extensions/amp-user-location/0.1/amp-user-location.js
  extensions/amp-user-location/0.1/config-loader.js
  extensions/amp-user-location/0.1/test/test-amp-user-location.js
  extensions/amp-user-location/0.1/test/test-config-loader.js
  extensions/amp-user-location/0.1/test/validator-amp-user-location.html
  extensions/amp-user-location/0.1/test/validator-amp-user-location.out
  extensions/amp-user-location/0.1/user-location-service.js
  extensions/amp-user-location/amp-user-location.md
  extensions/amp-user-location/validator-amp-user-location.protoascii
Labels: cla: yes

#22798 📖 Fix table in testing documentation
  contributing/TESTING.md
Labels: cla: yes

#22700 ✨ Show label when live story is updated and user is on last page.
  extensions/amp-story/1.0/_locales/default.js
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
  src/localized-strings.js
Labels: Category: AMP Story, cla: yes

#22772 🏗 Print warning that `gulp test` will be deprecated soon
  build-system/tasks/runtime-test/index.js
Labels: cla: yes

#22803 Validator rollup
  extensions/amp-carousel/validator-amp-carousel.protoascii
  validator/testdata/amp4email_feature_tests/amp_carousel.html
  validator/testdata/amp4email_feature_tests/amp_carousel.out
  validator/testdata/feature_tests/mandatory_dimensions.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#22576 Render form state template for amp-form even with unsupported type JSON array
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
Labels: cla: yes

#22780 Ensure that fluid dummy size '320x50' is the first size included in the ad request.
  ads/google/test/test-utils.js
  ads/google/utils.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#22807 Update amp-bind docs for aria attributes.
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#22650 Documenting amp-story-page-attachment theme.
  extensions/amp-story/amp-story.md
Labels: cla: yes

#22711 Documentation for the story page attachment analytics triggers.
  extensions/amp-story/amp-story-analytics.md
Labels: cla: yes

#22786 🏗 Gulp test refactor clean up
  build-system/tasks/a4a.js
  build-system/tasks/integration.js
  build-system/tasks/runtime-test/helpers-unit.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/unit.js
Labels: cla: yes

#22764 swg 0.1.22.55
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#22799 Remove unnecessary type cast in macro resolvers
  extensions/amp-analytics/0.1/variables.js
  src/service/url-replacements-impl.js
  src/service/variable-source.js
Labels: cla: yes

#22812 Fix race condition when resolving performanceTiming.loadEventEnd
  src/service/variable-source.js
  test/integration/test-amp-analytics.js
  test/unit/test-url-replacements.js
  test/unit/test-variable-source.js
Labels: cla: yes

#22811 🐛 Fix chai assertion wrapper bug
  build-system/tasks/e2e/expect.js
Labels: cla: yes

#22813 ✅ Add visual tests for live story notification label
  examples/visual-tests/amp-story/amp-story-live-story.html
  examples/visual-tests/amp-story/amp-story-live-story.js
  test/visual-diff/visual-tests
Labels: cla: yes

#22791 :bug: Send layout jank metrics more proactively.
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#22831 Updates the JSDoc for amp-story-page overview
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#22746 Allow XHR interceptor in local development mode
  examples/viewer.html
  examples/xhr-intercept.html
  src/utils/xhr-utils.js
  test/unit/test-xhr.js
Labels: cla: yes

#22833 Change the background color of highlighted texts from orange to yellow.
  extensions/amp-viewer-integration/0.1/highlight-handler.js
  extensions/amp-viewer-integration/0.1/test/test-highlight-handler.js
Labels: cla: yes

#22818 🐛 Add a new data attribute on the created amp-ad element
  extensions/amp-auto-ads/0.1/anchor-ad-strategy.js
  extensions/amp-auto-ads/0.1/opt-in-status.js
  extensions/amp-auto-ads/0.1/test/test-anchor-ad-strategy.js
Labels: cla: yes

#22830 Use endsWith Helper
  src/cookies.js
Labels: cla: yes

#22829 Story amp-img and amp-video object-position documentation.
  extensions/amp-story/amp-story.md
  extensions/amp-story/img/amp-story-object-position.gif
Labels: cla: yes

#22631 Introduce experiments for ad CSS clean ups.
  src/inabox/amp-inabox.js
  src/service/extensions-impl.js
  tools/experiments/experiments.js
Labels: cla: yes

#22632 Ads CSS experiments config change
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#22838 🐛Fix form-validators with date picker on touch devices
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker.js
Labels: cla: yes

#22843 Story min-height fallback during prerendering.
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#22809 🚀 Layers: Fix quadratic remeasurements during initial page load
  extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
  src/custom-element.js
  src/inabox/inabox-viewport.js
  src/service/layers-impl.js
  src/service/resource.js
  test/unit/inabox/test-inabox-viewport.js
Labels: cla: yes

#22814 Landscape half half UI documentation.
  extensions/amp-story/amp-story.md
  extensions/amp-story/img/amp-story-img-video-object-fit-position.png
Labels: cla: yes

#22847 Update image src in story documentation.
  extensions/amp-story/amp-story.md
Labels: cla: yes

#22841 Remove dynamic-live-list attribute
  examples/visual-tests/amp-story/amp-story-live-story.html
  extensions/amp-live-list/0.1/live-list-manager.js
  extensions/amp-live-list/0.1/test/test-live-list-manager.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/live-story-manager.js
  extensions/amp-story/1.0/test/test-live-story-manager.js
Labels: Category: AMP Story, cla: yes

#22824 🐛 Fix sauce launcher bug
  build-system/tasks/a4a.js
  build-system/tasks/integration.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/index.js
  build-system/tasks/unit.js
  package.json
  yarn.lock
Labels: cla: yes

#22870 Update image src in story documentation.
  extensions/amp-story/amp-story.md
Labels: cla: yes

#22789 ⛏Linker fragment nits
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
Labels: cla: yes

#22875 Point people to Slack instead of buildcop when there's a test breakage
  contributing/DEVELOPING.md
  contributing/buildcop.md
Labels: cla: yes

#22872 🐛 Fix percentage-played when loadedmetadata fires before listener is added
  src/service/video-manager-impl.js
  test/unit/test-video-analytics-percentage-tracker.js
Labels: cla: yes

#22873 🐛 do not allow relative URL with https
  extensions/amp-user-location/validator-amp-user-location.protoascii
Labels: cla: yes

#22544 🚀More optimization for lightbox svgs
  extensions/amp-lightbox-gallery/0.1/lightbox-controls.css
Labels: cla: yes

#22876 🐛Remove srcset on relayout if needed
  extensions/amp-anim/0.1/amp-anim.js
  extensions/amp-anim/0.1/test/test-amp-anim.js
Labels: cla: yes

#22617 🐛Various fixes for amp-base-carousel.
  extensions/amp-base-carousel/0.1/amp-base-carousel.css
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/auto-advance.js
  extensions/amp-base-carousel/0.1/carousel.js
Labels: cla: yes

#22827 🐛 Handle case where textarea has required attr
  extensions/amp-form/0.1/form-validators.js
Labels: cla: yes

#22554 ✨ Add WebEngage as an analytics vendor
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/webengage.js
Labels: cla: yes

#22869 Inabox: remove unnecessary dependencies on various viewport bindings
  src/inabox/amp-inabox.js
  src/service/core-services.js
Labels: cla: yes

#22837 📖Typos in amp-video-iframe.md
  extensions/amp-video-iframe/amp-video-iframe.md
Labels: cla: yes

#22771 Fix typo
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#22846 ✅ Improve amp-date-picker coverage with state machine and dates-list
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/dates-list.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker-state.js
  extensions/amp-date-picker/0.1/test/test-dates-list.js
Labels: cla: yes

#22887 🐛Fix `data-slide-id` not being preserved when lightboxing a carousel.
  examples/article-with-lightbox-2.0-gallery.amp.html
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#22905 Story vertical scrolling rendering.
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-scroll.css
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#22404 ✨ #22160 Add new EQUALS macro
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
Labels: cla: yes

#22886 Inabox: remove unnecessary dependency on maybeTrackImpression
  build-system/amp4test.js
  src/inabox/amp-inabox.js
  test/integration/test-amp-inabox.js
Labels: cla: yes

#22904 marginBottomOfLastChild should only check position=static|relative
  src/service/viewport/viewport-binding-def.js
  test/unit/test-viewport.js
Labels: Externally Tracked, cla: yes

#22654 📖 Getting started: Don't suggest NVM for Windows
  contributing/getting-started-e2e.md
Labels: cla: yes

#22879 Add live-story-disabled attribute to support disabled live stories
  extensions/amp-live-list/0.1/live-list-manager.js
  extensions/amp-live-list/0.1/test/test-live-list-manager.js
Labels: Category: AMP Story, cla: yes

#22840 Dispatch VALUE_CHANGE on `amp-bind` value changes
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  src/amp-events.js
Labels: cla: yes

#22878 🐛 Do not toggle loading to same state
  src/custom-element.js
Labels: cla: yes

#22910 Improve all adp modules coverage to above 80%
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker-bind.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker-state.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker.js
  extensions/amp-date-picker/0.1/test/test-wrapper-maximum-nights.js
  extensions/amp-date-picker/0.1/wrappers/maximum-nights.js
Labels: cla: yes

#22624 ✨Add gulp task to compile analytics vendor JSON configs
  build-system/tasks/extension-helpers.js
  build-system/tasks/vendor-configs.js
  gulpfile.js
  package.json
  yarn.lock
Labels: cla: yes

#22848 Upgrade worker-dom to 0.12.3
  build-system/compile/compile.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/update-packages.js
  extensions/amp-script/0.1/amp-script.js
  package.json
  yarn.lock
Labels: cla: yes

#22913 ♻️ ESLint Rules: Allow ExportSpecifier
  build-system/eslint-rules/no-export-side-effect.js
Labels: cla: yes

#22882 🐛Fix `Ad` badge in non-chrome browsers.
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-attribution.css
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
Labels: cla: yes

#22626 🐛 Turn on the `amphtml-internal/unused-private-field` rule, fix errors
  .eslintrc
  ads/inabox/position-observer.js
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-a4a/0.1/refresh-manager.js
  extensions/amp-a4a/0.1/signature-verifier.js
  extensions/amp-access/0.1/amp-access-other.js
  extensions/amp-access/0.1/amp-access-server.js
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-animation/0.1/amp-animation.js
  extensions/amp-animation/0.1/parsers/css-expr-ast.js
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/carousel-accessibility.js
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-bind/0.1/amp-bind-macro.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/lightbox-caption.js
  extensions/amp-lightbox-gallery/0.1/lightbox-controls.js
  extensions/amp-live-list/0.1/poller.js
  extensions/amp-position-observer/0.1/amp-position-observer.js
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/story-analytics.js
  src/service/storage-impl.js
  src/service/viewport/viewport-binding-ios-embed-wrapper.js
  src/service/vsync-impl.js
Labels: Category: Runtime, cla: yes

#22912 ♻️ amp-apester-media: reduce some error noise.
  extensions/amp-apester-media/0.1/amp-apester-media.js
Labels: cla: yes

#22881 🐛 FixedLayer: Do not track children of already tracked elements
  src/service/fixed-layer.js
  test/unit/test-fixed-layer.js
Labels: cla: yes

#22874 ✨ Live story validation
  extensions/amp-story/1.0/test/validator-amp-story-live-story-error.html
  extensions/amp-story/1.0/test/validator-amp-story-live-story-error.out
  extensions/amp-story/1.0/test/validator-amp-story-live-story.html
  extensions/amp-story/1.0/test/validator-amp-story-live-story.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: Category: AMP Story, cla: yes

#22925 Validator rollup
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#22919 Fix analytics expander in singlepass
  src/service/url-expander/expander.js
  test/integration/test-amp-analytics.js
Labels: cla: yes

#22929 📈 Add last-page-visible trigger
  extensions/amp-story/1.0/navigation-state.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-analytics.js
Labels: cla: yes

#22923 Update form dirtiness on FORM_VALUE_CHANGE event
  extensions/amp-form/0.1/form-dirtiness.js
  extensions/amp-form/0.1/test/test-form-dirtiness.js
Labels: cla: yes

#22697 ✨ amp-addthis: Adding Open Graph image meta tag as fallback for media prop
  extensions/amp-addthis/0.1/addthis-utils/meta.js
  extensions/amp-addthis/0.1/amp-addthis.js
Labels: cla: yes

#22758 AdsLoom AMP Integration
  3p/integration.js
  ads/_config.js
  ads/adsloom.js
  ads/adsloom.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#22928 SwG Release 0.1.22.56
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#22815 COOKIE macro
  build-system/amp4test.js
  extensions/amp-analytics/0.1/cookie-reader.js
  extensions/amp-analytics/0.1/cookie-writer.js
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/test/test-requests.js
  extensions/amp-analytics/0.1/vendors.js
  test/integration/test-amp-analytics.js
  test/integration/test-amp-inabox.js
Labels: cla: yes

#22930 🐛Fix bottom of slides being clipped.
  extensions/amp-base-carousel/0.1/carousel.css
  extensions/amp-carousel/0.1/amp-carousel.css
Labels: cla: yes
