Repository ampproject/amphtml, pull requests merged in 2019-02, with the labels that each got.

#20629 ✅Add visual test for amp-sidebar.
  examples/visual-tests/amp-sidebar/amp-sidebar.amp.html
  examples/visual-tests/amp-sidebar/amp-sidebar.js
  test/visual-diff/visual-tests
Labels: cla: yes

#20632 ✅First few visual diff tests for amp-date-picker
  examples/visual-tests/amp-date-picker/amp-date-picker.amp.html
  examples/visual-tests/amp-date-picker/amp-date-picker.js
  test/visual-diff/visual-tests
Labels: cla: yes

#20631 Add first amp-accordion visual tests
  examples/visual-tests/amp-accordion/amp-accordion.html
  examples/visual-tests/amp-accordion/amp-accordion.js
  test/visual-diff/visual-tests
Labels: cla: yes

#20623 amp-script: Partial opacity pre-hydration
  bundles.config.js
  examples/amp-script/todomvc.amp.html
  examples/amp-script/todomvc.es6.js
  examples/amp-script/todomvc.js
  examples/amp-script/todomvc.ssr.js
  examples/amp-script/todomvc.uglify.js
  extensions/amp-script/0.1/amp-script.css
  extensions/amp-script/0.1/amp-script.js
Labels: cla: yes

#20634 Introduce a secure way to embed sandboxed AMP
  extensions/amp-viewer-integration/0.1/amp-viewer-integration.js
  extensions/amp-viewer-integration/0.1/messaging/messaging.js
  extensions/amp-viewer-integration/0.1/test/integration/test-amp-viewer-integration.js
Labels: cla: yes

#20574 Revert "temporarily disable saucelabs because of flakiness (#20566)"
  build-system/pr-check.js
  build-system/tasks/runtime-test/index.js
Labels: cla: yes

#20591 ✨Enable conversion tracking for GTAG.
  extensions/amp-analytics/0.1/vendors/gtag.js
Labels: cla: yes

#20540 ✅ amp-recaptcha-input: Added support for integration test mocking in express server
  build-system/app.js
  build-system/recaptcha-router.js
  examples/recaptcha.amp.html
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
Labels: cla: yes

#19531 initial draft amp-mraid implementation
  build-system/tasks/compile.js
  bundles.config.js
  examples/mraid/inabox-mraid.html
  examples/mraid/mraid.js
  extensions/amp-mraid/0.1/amp-mraid.js
  extensions/amp-mraid/0.1/mraid-service.js
  extensions/amp-mraid/OWNERS
  extensions/amp-mraid/amp-mraid.md
  src/inabox/host-services.js
Labels: cla: yes

#20647 Make sure that infinite scroll actually ends
  extensions/amp-list/0.1/amp-list.js
Labels: cla: yes

#20648 🐛Fix mask-output when combined with amp-list
  extensions/amp-inputmask/0.1/text-mask.js
Labels: cla: yes

#20643 launch amp-list-viewport-resize to all
  build-system/global-configs/prod-config.json
Labels: cla: yes

#20656 🐛Fix deleting from the middle of dates
  third_party/inputmask/bundle.js
  third_party/inputmask/inputmask.date.extensions.js
  third_party/inputmask/inputmask.js
  third_party/inputmask/patches/0014-delete-middle-date.patch
Labels: cla: yes

#20633 ✅ More visual diff tests for `<amp-selector>`
  examples/visual-tests/amp-selector.js
Labels: cla: yes

#20665 Skip flaky amp-list test
  extensions/amp-list/0.1/test/integration/test-amp-list.js
Labels: cla: yes

#20670 Forward touch events to the viewer when #cap=swipe.
  extensions/amp-story/1.0/amp-story-share.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#20669 🐛♻️✅ Relax document type restrictions for auto-lightbox
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
  extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
Labels: cla: yes

#20672 Remove amp-script demo link
  extensions/amp-script/amp-script.md
Labels: cla: yes

#20222 ✨Scroll extension: Add tracking of article reading progress
  examples/scroll.amp.html
  extensions/amp-access-scroll/0.1/read-depth-tracker.js
  extensions/amp-access-scroll/0.1/scroll-impl.js
  extensions/amp-access-scroll/0.1/test/read-depth-tracker.js
Labels: cla: yes

#20693 amp-sidebar autoscroll: revert validation rules for now
  extensions/amp-sidebar/0.1/test/validator-amp-sidebar-autoscroll-invalid.html
  extensions/amp-sidebar/0.1/test/validator-amp-sidebar-autoscroll-invalid.out
  extensions/amp-sidebar/0.1/test/validator-amp-sidebar-autoscroll-valid.html
  extensions/amp-sidebar/0.1/test/validator-amp-sidebar-autoscroll-valid.out
  extensions/amp-sidebar/validator-amp-sidebar.protoascii
Labels: cla: yes

#20649 📖 Remove TOC from A4A spec, as it is redundant when displayed on our site
  extensions/amp-a4a/amp-a4a-format.md
Labels: cla: yes

#20682 Skip flaky inabox tests
  test/integration/test-amp-inabox.js
Labels: cla: yes

#20635 Add visual diff test for amp-user-notification
  ads/_ping_.js
  examples/visual-tests/amp-user-notification/amp-user-notification.amp.html
  examples/visual-tests/amp-user-notification/amp-user-notification.js
  test/visual-diff/visual-tests
Labels: cla: yes

#20041 ♻️ Migrate the amp-story analytics to a service
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/media-pool.md
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/pagination-buttons.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-analytics.js
  extensions/amp-story/1.0/test/test-variable-service.js
  src/services.js
Labels: cla: yes

#20687 ✨Autofocus on `show()`
  spec/amp-actions-and-events.md
  src/service/standard-actions-impl.js
  test/manual/autofocus-on-show.html
  test/unit/test-standard-actions.js
Labels: cla: yes

#20699 Revert "Enables layers in canary"
  build-system/global-configs/canary-config.json
Labels: cla: yes

#20664 🖍 Edit sidebar animations/design
  examples/visual-tests/amp-story/amp-story-sidebar.html
  extensions/amp-story/1.0/amp-story-desktop-user-overridable.css
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#20599 Make inabox host correctly get position of a nested iframe
  ads/inabox/inabox-messaging-host.js
  ads/inabox/position-observer.js
  test/unit/inabox/test-inabox-messaging-host.js
  test/unit/inabox/test-position-observer.js
Labels: cla: yes

#20671 🏗 Execute each visual diff test in a separate subdomain
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#20662 🐛 Change a usage of ancestorElementsByTag to closestByTag.
  extensions/amp-ad/0.1/amp-ad-custom.js
Labels: cla: yes

#20701 ♻️ Remove duplicates from fullscreen API
  src/dom.js
Labels: cla: yes

#20700 🐛 Correctly scope query for multiple selectors in string
  build-system/tasks/presubmit-checks.js
  src/dom.js
  test/unit/test-dom.js
Labels: cla: yes

#20698 🐛Fix issues with animated expansion of accordion.
  extensions/amp-accordion/0.1/amp-accordion.js
  extensions/amp-accordion/0.1/test/test-amp-accordion.js
Labels: cla: yes

#20708 [amp-story] Ensure clicks on anchor tags are handled by tooltip 🐛
  extensions/amp-story/1.0/amp-story.css
Labels: Category: AMP Story, cla: yes

#20666 history: drop url fragment in the new API for the viewer as well
  src/service/history-impl.js
  test/unit/test-history.js
Labels: cla: yes

#20642 Refactor render template in amp-list
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  src/ssr-template-helper.js
  test/unit/test-ssr-template-helper.js
Labels: cla: yes

#20560 🏗 Wait an extra minute for sauce connect
  build-system/sauce_connect/start_sauce_connect.sh
Labels: Category: Tooling, cla: yes

#20604 Add test page of analytics in shadow root
  test/manual/amp-analytics/analytics-shadow-root-1.html
  test/manual/amp-analytics/analytics-shadow-root-2.html
  test/manual/amp-analytics/analytics-shadow.html
Labels: cla: yes

#20705 🐛Preserve JSON field names for Scroll extension
  extensions/amp-access-scroll/0.1/scroll-impl.js
Labels: cla: yes

#20715 Revert "🏗 Wait an extra minute for sauce connect"
  build-system/sauce_connect/start_sauce_connect.sh
Labels: Category: Tooling, cla: yes

#20716 🏗 Enable verbose logging for sauce connect
  build-system/sauce_connect/start_sauce_connect.sh
Labels: Category: Tooling, cla: yes

#20661 ✨Launch amp-inputmask
  extensions/amp-inputmask/0.1/amp-inputmask.js
  extensions/amp-inputmask/0.1/test/integration/test-integration-amp-inputmask-date.js
  extensions/amp-inputmask/0.1/test/integration/test-integration-amp-inputmask.js
  extensions/amp-inputmask/README.md
  tools/experiments/experiments.js
Labels: cla: yes

#20659 🐛 Correctly validate numeric outputs to default values in amp-bind
  examples/bind/basic.amp.html
  extensions/amp-bind/0.1/bind-impl.js
Labels: cla: yes

#20667 🐛Re-implemented "Fixed NonXHR GET on amp-form with Async Input Elements"
  build-system/app.js
  examples/forms.amp.html
  examples/recaptcha.amp.html
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
Labels: cla: yes

#20712 🐛Fixes for lightbox gallery and shadow docs.
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#20729 🏗 Capture console output and verbose logging during sauce connect failures
  build-system/sauce_connect/start_sauce_connect.sh
Labels: cla: yes

#20730 🐛Fix lightbox closing when opened from a carousel.
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#20728 Replace CommonSignal "CHANGE_SIZE_END" with a change size event
  src/amp-events.js
  src/common-signals.js
  src/custom-element.js
  test/unit/test-custom-element.js
Labels: cla: yes

#20611 ✨Amend preloading to work with branching
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#20706 🐛Modify amp-pinterest.css from displaying "Pin It" to "Save" as a button
  build-system/tasks/presubmit-checks.js
  examples/pinterest.amp.html
  extensions/amp-pinterest/0.1/amp-pinterest.css
  extensions/amp-pinterest/0.1/amp-pinterest.js
  extensions/amp-pinterest/0.1/pin-widget.js
  extensions/amp-pinterest/0.1/save-button.js
  extensions/amp-pinterest/0.1/test/validator-amp-pinterest.html
  extensions/amp-pinterest/0.1/test/validator-amp-pinterest.out
  extensions/amp-pinterest/amp-pinterest.md
Labels: cla: yes

#20710 🐛 Have purifier.js allow unknown protocols
  src/purifier.js
  test/unit/test-purifier.js
Labels: cla: yes

#20742 🏗Move `amphtml-validator` to dev dependency
  package.json
  yarn.lock
Labels: cla: yes

#20743 ✅Fix carousel e2e tests.
  build-system/tasks/e2e/index.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  extensions/amp-carousel/0.2/test-e2e/test-carousel.js
  extensions/amp-carousel/0.2/test-e2e/test-grouping.js
Labels: cla: yes

#20749 🏗 Run push builds against `revert-*` branches
  .travis.yml
Labels: Category: Tooling, cla: yes

#20771 📖 Update amp-story sidebar docs to link to stories section of amp-sidebar docs
  extensions/amp-story/amp-story.md
Labels: cla: yes

#20767 🏗🐛 Roll back sauce connect version to 4.5.1
  build-system/sauce_connect/start_sauce_connect.sh
Labels: Category: Tooling, cla: yes

#20757 📖 Document auto-lightbox treatment
  spec/auto-lightbox.md
Labels: cla: yes

#20768 Doubleclick/AdSense Fast fetch: Checksum based validation
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#20776 🏗 Remove `bundlesize` from `package.json`
  package.json
  yarn.lock
Labels: Category: Tooling, cla: yes

#20762 🚀 auto-lightbox: Slightly faster semantic type matching
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
  extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
Labels: cla: yes

#20756 ✨ Clear Google viewer URL prefix from proxy URL
  build-system/app.js
Labels: cla: yes

#20753 🖍 lightbox-gallery: Override author-defined carousel background
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
Labels: cla: yes

#20761 🔧♻️ auto-lightbox: No nesting, use array for selector
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
  extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
Labels: cla: yes

#20760 ✨ Support <amp-ima-video dock>
  extensions/amp-ima-video/0.1/test/validator-amp-ima-video-dock-no-extension.html
  extensions/amp-ima-video/0.1/test/validator-amp-ima-video-dock-no-extension.out
  extensions/amp-ima-video/validator-amp-ima-video.protoascii
  extensions/amp-video-docking/0.1/amp-video-docking.js
  extensions/amp-video-docking/0.1/test/test-amp-video-docking.js
  extensions/amp-video-docking/0.1/test/validator-amp-video-docking-amp-ima-video.html
  extensions/amp-video-docking/0.1/test/validator-amp-video-docking-amp-ima-video.out
Labels: cla: yes

#20755 🐦 Activate `amp-auto-lightbox` in canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#20751 🐛 auto-lightbox: Accept all viewers per proxy origin check
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
  extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
Labels: cla: yes

#18256 📖 Add documentation for new code ownership model
  contributing/CODE_OWNERSHIP.md
  contributing/DEVELOPING.md
Labels: Related to: Documentation, cla: yes

#20769 📖 Documentation improvements for amp-access-laterpay
  extensions/amp-access-laterpay/amp-access-laterpay.md
Labels: cla: yes

#20797 Skip integration test in firefox
  test/integration/test-amp-skimlinks.js
Labels: cla: yes

#18456 🐛🌐 amp-story: Added missing localization strings in es and es-419
  extensions/amp-story/1.0/_locales/es-419.js
  extensions/amp-story/1.0/_locales/es.js
Labels: cla: yes

#20784 🖍Clean up amp-pinterest button styling
  extensions/amp-pinterest/0.1/save-button.js
Labels: cla: yes

#20788 📖 Restructure docs for amp-video-docking, inform attribute in player docs
  extensions/amp-brightcove/amp-brightcove.md
  extensions/amp-ima-video/amp-ima-video.md
  extensions/amp-video-docking/amp-video-docking.md
  extensions/amp-video-iframe/amp-video-iframe.md
  extensions/amp-video/amp-video.md
  extensions/amp-youtube/amp-youtube.md
  spec/amp-video-interface.md
Labels: cla: yes

#20754 🖍 Stack `amp-lightbox-gallery` at the very top
  css/Z_INDEX.md
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
Labels: cla: yes

#20766 📖 Documentation(unruly): update README and test page with correct integration instructions
  ads/unruly.md
  examples/ads.amp.html
Labels: cla: yes

#20807 🐛 Fix subscriptions dialog stacking order.
  extensions/amp-subscriptions/0.1/amp-subscriptions.css
Labels: cla: yes

#20717 ♻️ Refactor dom.js to have similar functions be close to each other and have more accurate names.
  build-system/conformance-config.textproto
  extensions/amp-ad/0.1/amp-ad-custom.js
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-animation/0.1/web-animations.js
  extensions/amp-audio/0.1/amp-audio.js
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-image-lightbox/0.1/amp-image-lightbox.js
  extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-story/0.1/amp-story-consent.js
  extensions/amp-story/0.1/amp-story-page.js
  extensions/amp-story/0.1/utils.js
  extensions/amp-story/1.0/amp-story-access.js
  extensions/amp-story/1.0/amp-story-consent.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/utils.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-video-docking/0.1/controls.js
  src/custom-element.js
  src/dom.js
  src/friendly-iframe-embed.js
  src/iframe-helper.js
  src/service/navigation.js
  src/service/viewport/viewport-impl.js
  src/utils/story.js
  test/unit/test-dom.js
Labels: cla: yes

#20711 amp-story: add/remove visible attr for ads
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
Labels: cla: yes

#20802 🏗🚮 Remove --verify_status step from `gulp visual-diff` task
  build-system/pr-check.js
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#20440 amp-action-macro implementation
  build-system/dep-check-config.js
  bundles.config.js
  extensions/amp-action-macro/0.1/amp-action-macro.js
  extensions/amp-action-macro/0.1/test/test-amp-action-macro.js
  extensions/amp-action-macro/amp-action-macro.md
  src/service/action-impl.js
  test/unit/test-action.js
Labels: cla: yes

#20792 🏗🗑 Remove asynchronous amp-video-service experiment
  build-system/tasks/runtime-test/helpers.js
  bundles.config.js
  extensions/amp-story/0.1/amp-story-page.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/media-pool.js
  extensions/amp-video-service/0.1/amp-video-service.js
  extensions/amp-video-service/0.1/test/test-amp-video-service.js
  extensions/amp-video-service/OWNERS.yaml
  gulpfile.js
  src/service/video-manager-impl.js
  src/service/video-service-interface.js
  src/service/video-service-sync-impl.js
  src/service/video/autoplay.js
  src/services.js
  src/video-interface.js
  test/unit/test-video-autoplay.js
  tools/experiments/experiments.js
Labels: cla: yes

#20109 jubna amp ads
  3p/integration.js
  ads/_config.js
  ads/jubna.js
  ads/jubna.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#20803 Validator Roll-up
  extensions/amp-access/validator-amp-access.protoascii
  extensions/amp-ad-exit/validator-amp-ad-exit.protoascii
  extensions/amp-analytics/validator-amp-analytics.protoascii
  extensions/amp-animation/validator-amp-animation.protoascii
  extensions/amp-bind/validator-amp-bind.protoascii
  extensions/amp-consent/validator-amp-consent.protoascii
  extensions/amp-experiment/validator-amp-experiment.protoascii
  extensions/amp-geo/validator-amp-geo.protoascii
  extensions/amp-mustache/validator-amp-mustache.protoascii
  extensions/amp-payment-google-button/validator-amp-payment-google-button.protoascii
  extensions/amp-payment-google-inline-async/validator-amp-payment-google-inline-async.protoascii
  extensions/amp-payment-google-inline/validator-amp-payment-google-inline.protoascii
  extensions/amp-sidebar/0.1/test/validator-amp-sidebar-autoscroll-invalid.html
  extensions/amp-sidebar/0.1/test/validator-amp-sidebar-autoscroll-invalid.out
  extensions/amp-sidebar/0.1/test/validator-amp-sidebar-autoscroll-valid.html
  extensions/amp-sidebar/0.1/test/validator-amp-sidebar-autoscroll-valid.out
  extensions/amp-sidebar/validator-amp-sidebar.protoascii
  extensions/amp-story-auto-ads/validator-amp-story-auto-ads.protoascii
  extensions/amp-story/validator-amp-story.protoascii
  extensions/amp-subscriptions/validator-amp-subscriptions.protoascii
  extensions/amp-viewer-assistance/validator-amp-viewer-assistance.protoascii
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/testdata/transformed_feature_tests/nonce_attribute_error.html
  validator/testdata/transformed_feature_tests/nonce_attribute_error.out
  validator/testdata/transformed_feature_tests/server_side_rendering.html
  validator/testdata/transformed_feature_tests/server_side_rendering.out
  validator/testdata/transformed_feature_tests/transformed_but_not_identified_transformed.html
  validator/testdata/transformed_feature_tests/transformed_but_not_identified_transformed.out
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: Category: Validator, cla: yes

#20746 🏗 Consolidate all Travis-related state in `build-system/travis.js`
  babel.config.js
  build-system/ctrlcHandler.js
  build-system/git.js
  build-system/pr-check.js
  build-system/single-pass.js
  build-system/tasks/ava.js
  build-system/tasks/bundle-size.js
  build-system/tasks/check-links.js
  build-system/tasks/compile.js
  build-system/tasks/dep-check.js
  build-system/tasks/karma.conf.js
  build-system/tasks/lint.js
  build-system/tasks/prepend-global/index.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/index.js
  build-system/tasks/update-packages.js
  build-system/tasks/visual-diff/helpers.js
  build-system/tasks/visual-diff/index.js
  build-system/travis.js
  gulpfile.js
Labels: Category: Tooling, cla: yes

#20818 📖amp story ads RTC & Targeting docs
  extensions/amp-story-auto-ads/amp-story-auto-ads.md
Labels: cla: yes

#20817 🐛Reset min dimensions on undock
  extensions/amp-video-docking/0.1/amp-video-docking.js
Labels: cla: yes

#20819 Optimize scopeSelector
  src/dom.js
Labels: cla: yes

#20823 ✨ Set amp=1 fragment in amp-video-iframe src
  extensions/amp-video-iframe/0.1/amp-video-iframe.js
  extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
Labels: cla: yes

#20821 ✅ amp-youtube: add amp=1 to the url
  extensions/amp-youtube/0.1/amp-youtube.js
  extensions/amp-youtube/0.1/test/test-amp-youtube.js
Labels: cla: yes

#20826 🛑 <amp-video-iframe> integration safeguards
  src/video-iframe-integration.js
Labels: cla: yes

#20779 Clean up 'user-error-reporting'
  extensions/amp-analytics/amp-analytics.md
  src/error.js
  tools/experiments/experiments.js
Labels: cla: yes

#20809 ✅Skip date picker visual diff tests for flakes
  test/visual-diff/visual-tests
Labels: cla: yes

#20514 Make test-resource.js not flaky
  test/unit/test-resources.js
Labels: cla: yes

#20794 ✅ Resolve some flakiness in e2e tests
  build-system/tasks/e2e/DEBUGGING.md
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/expect.js
  build-system/tasks/e2e/functional-test-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  extensions/amp-carousel/0.2/test-e2e/test-autoadvance.js
  extensions/amp-carousel/0.2/test-e2e/test-carousel.js
  extensions/amp-carousel/0.2/test-e2e/test-grouping.js
  extensions/amp-carousel/0.2/test-e2e/test-max-swipe.js
  extensions/amp-carousel/0.2/test-e2e/test-mixed-lengths.js
  extensions/amp-carousel/0.2/test-e2e/test-non-looping.js
  extensions/amp-carousel/0.2/test-e2e/test-vertical.js
Labels: cla: yes

#20822 Don't send amp-bind state to untrusted viewers
  build-system/tasks/presubmit-checks.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
Labels: cla: yes

#20774 🚮 Cleanup adsense amp-auto-ads holdout experiment. Close #9247.
  ads/google/adsense-amp-auto-ads.js
  ads/google/test/test-adsense-amp-auto-ads.js
  build-system/dep-check-config.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-auto-ads/0.1/ad-network-config.js
  extensions/amp-auto-ads/0.1/test/test-ad-network-config.js
  tools/experiments/experiments.js
Labels: cla: yes

#20833 AdSense Fast Fetch experiment - delay request by fixed 3 viewport range
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Labels: cla: yes

#20837 AdSense Fast Fetch 1% experiment delay requested based on fixed viewport offset
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#20624 ✨ Improve Google matched content logic to reflect adsbygoogle.js.
  ads/google/a4a/shared/content-recommendation.js
  ads/google/a4a/shared/test/test-content-recommendation.js
  ads/google/test/test-utils.js
  ads/google/utils.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
Labels: cla: yes

#20789 ✨auto-lightbox: Discard tap actions with invalid references
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
  extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  src/service/action-impl.js
  test/unit/test-action.js
Labels: cla: yes

#20857 Make is-my-pr-in-production-yet more prominent in our docs
  README.md
Labels: cla: yes

#20357 amp-ad-exit: use HostService if exists.
  examples/mraid/inabox-mraid.html
  extensions/amp-ad-exit/0.1/amp-ad-exit.js
  extensions/amp-mraid/0.1/amp-mraid.js
  src/inabox/host-services.js
Labels: cla: yes

#20865 AmpAd Fast Fetch Launch layoutcallback immediate resolve for FIE
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
Labels: cla: yes

#20835 Displaying more specific messages when users have to resize their window.
  extensions/amp-story/1.0/_locales/default.js
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-viewport-warning-layer.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/localization.js
  extensions/amp-story/1.0/test/test-amp-story-store-service.js
Labels: cla: yes

#20772 ✨Implement autoexpand for amp-form textarea element
  extensions/amp-form/0.1/amp-form-textarea.js
  extensions/amp-form/0.1/amp-form.css
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form-textarea.js
  extensions/amp-form/amp-form.md
  src/purifier.js
  test/manual/amp-form-textarea-added.amp.html
  test/manual/amp-form-textarea.amp.html
  validator/testdata/feature_tests/forms.html
  validator/testdata/feature_tests/forms.out
  validator/validator-main.protoascii
Labels: cla: yes

#20866 AdSense Fast Fetch delay 3 viewport experiment - respect loading strategy
  build-system/dep-check-config.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Labels: cla: yes

#20724 🐛Do not perform static layout for cloned nodes with static layout.
  extensions/amp-a4a/0.1/test/test-template-renderer.js
  src/layout.js
  test/unit/test-layout.js
Labels: cla: yes

#20854 ♻️ Export few data types from content-recommendation.js
  ads/google/a4a/shared/content-recommendation.js
Labels: cla: yes

#20856 Undo space reservation after successful height change
  extensions/amp-list/0.1/amp-list.js
Labels: cla: yes

#20731 🐛 Guard against getBoundingClientRect to prevent unspecified errors in IE.
  src/get-bounding-client-rect.js
  src/polyfills.js
Labels: cla: yes

#20834 SwG Release 0.1.22.44
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#20836 🐛 Assert that values are never returned from vsync callbacks
  extensions/amp-embedly-card/0.1/amp-embedly-card-impl.js
  extensions/amp-subscriptions/0.1/dialog.js
  src/service/vsync-impl.js
Labels: cla: yes

#20778 [amp-story] Allow more parameters for pan/zoom animations ✨
  examples/amp-story/animations-presets.html
  examples/amp-story/visual-effects.html
  extensions/amp-story/1.0/animation-presets.js
  extensions/amp-story/1.0/animation.js
  extensions/amp-story/1.0/test/test-full-bleed-animations.js
Labels: cla: yes

#20668 🐛Return 400 when recaptcha example fails
  build-system/recaptcha-router.js
  examples/recaptcha.amp.html
Labels: Category: User Input, cla: yes

#20810 📖 video-docking: Target types and events
  extensions/amp-video-docking/amp-video-docking.md
Labels: cla: yes

#20873 Use const in validator code
  validator/engine/validator.js
Labels: cla: yes

#20814 🚀 Wait for mutate phase before layoutCallback
  src/service/resource.js
  test/integration/test-amp-carousel.js
  test/integration/test-visibility-states.js
  test/unit/test-resource.js
Labels: cla: yes

#20820 ✨Add support for setting the slide via an attribute.
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-carousel/0.2/carousel.js
  extensions/amp-carousel/0.2/responsive-attributes.js
  extensions/amp-carousel/0.2/test-e2e/test-initial-slide.js
  test/manual/amp-carousel-0-2/bind-slide.amp.html
  test/manual/amp-carousel-0-2/initial-slide.amp.html
Labels: cla: yes

#20876 Revert "Force the subscriptions dialog into the fixed layer to avoid collisions with border"
  extensions/amp-subscriptions/0.1/dialog.js
  extensions/amp-subscriptions/0.1/test/test-dialog.js
Labels: cla: yes

#20748 ✨Add support for contextual article matching
  examples/jwplayer.amp.html
  extensions/amp-jwplayer/0.1/amp-jwplayer.js
  extensions/amp-jwplayer/0.1/test/test-amp-jwplayer.js
  extensions/amp-jwplayer/0.1/test/validator-amp-jwplayer.html
  extensions/amp-jwplayer/0.1/test/validator-amp-jwplayer.out
  extensions/amp-jwplayer/amp-jwplayer.md
Labels: cla: yes

#20795 🐛 Prevent toggle() from throwing error when no elements are selected.
  examples/selector.amp.html
  extensions/amp-selector/0.1/amp-selector.js
Labels: cla: yes

#20494 ✨Create new extension - AMP-smartlinks
  build-system/dep-check-config.js
  bundles.config.js
  examples/amp-smartlinks.html
  extensions/amp-smartlinks/0.1/OWNERS.yaml
  extensions/amp-smartlinks/0.1/amp-smartlinks.js
  extensions/amp-smartlinks/0.1/constants.js
  extensions/amp-smartlinks/0.1/linkmate-options.js
  extensions/amp-smartlinks/0.1/linkmate.js
  extensions/amp-smartlinks/0.1/test/test-amp-smartlinks.js
  extensions/amp-smartlinks/0.1/test/test-linkmate.js
  extensions/amp-smartlinks/0.1/test/validator-amp-smartlinks.html
  extensions/amp-smartlinks/0.1/test/validator-amp-smartlinks.out
  extensions/amp-smartlinks/amp-smartlinks.md
  extensions/amp-smartlinks/validator-amp-smartlinks.protoascii
  src/extension-analytics.js
  test/unit/test-extension-analytics.js
Labels: cla: yes

#20872 [carousel v2] Support a maximum number of auto advance loops.
  extensions/amp-bind/0.1/bind-validator.js
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-carousel/0.2/auto-advance.js
  extensions/amp-carousel/0.2/carousel.js
Labels: cla: yes

#20886 Removing myself as owner
  extensions/amp-access-laterpay/OWNERS.yaml
Labels: cla: yes

#20811 🏗 New Travis Build Matrix
  .travis.yml
  build-system/pr-check/build-targets.js
  build-system/pr-check/build.js
  build-system/pr-check/checks.js
  build-system/pr-check/dist-tests.js
  build-system/pr-check/local-tests.js
  build-system/pr-check/remote-tests.js
  build-system/pr-check/utils.js
  build-system/pr-check/validator-tests.js
  build-system/pr-check/visual-diff-tests.js
  build-system/tasks/presubmit-checks.js
  build-system/travis.js
Labels: cla: yes

#20799 📖 Fix validity of amp-list[load-more] examples
  extensions/amp-list/amp-list.md
Labels: Category: Presentation, cla: yes

#20891 Revert "✨Create new extension - AMP-smartlinks"
  build-system/dep-check-config.js
  bundles.config.js
  examples/amp-smartlinks.html
  extensions/amp-smartlinks/0.1/OWNERS.yaml
  extensions/amp-smartlinks/0.1/amp-smartlinks.js
  extensions/amp-smartlinks/0.1/constants.js
  extensions/amp-smartlinks/0.1/linkmate-options.js
  extensions/amp-smartlinks/0.1/linkmate.js
  extensions/amp-smartlinks/0.1/test/test-amp-smartlinks.js
  extensions/amp-smartlinks/0.1/test/test-linkmate.js
  extensions/amp-smartlinks/0.1/test/validator-amp-smartlinks.html
  extensions/amp-smartlinks/0.1/test/validator-amp-smartlinks.out
  extensions/amp-smartlinks/amp-smartlinks.md
  extensions/amp-smartlinks/validator-amp-smartlinks.protoascii
  src/extension-analytics.js
  test/unit/test-extension-analytics.js
Labels: cla: yes

#20871 amp-list-load-more bugfixes
  extensions/amp-list/0.1/amp-list.js
  test/manual/amp-list/infinite-scroll-1.amp.html
Labels: cla: yes

#20893 🏗 Print git change summary only for non-push builds
  build-system/pr-check/build.js
  build-system/pr-check/checks.js
  build-system/pr-check/dist-tests.js
  build-system/pr-check/local-tests.js
  build-system/pr-check/remote-tests.js
  build-system/pr-check/validator-tests.js
  build-system/pr-check/visual-diff-tests.js
Labels: Category: Tooling, cla: yes

#20863 ✨ Adding 'allow-same-origin' to the consent prompt UI iframe
  extensions/amp-consent/0.1/consent-ui.js
Labels: cla: yes

#20901 🏗 Fix Travis when build job is skipped
  build-system/pr-check/local-tests.js
  build-system/pr-check/remote-tests.js
  build-system/pr-check/visual-diff-tests.js
Labels: cla: yes

#20895 ♻️ carousel v2: Simplify CSS
  extensions/amp-carousel/0.2/carousel.css
Labels: cla: yes

#20894 ✅Carousel v2 manual test cleanup.
  test/manual/amp-carousel-0-2/autoadvance.amp.html
  test/manual/amp-carousel-0-2/basic.amp.html
  test/manual/amp-carousel-0-2/cross-fader-max-swipe-one.amp.html
  test/manual/amp-carousel-0-2/cross-fader.amp.html
  test/manual/amp-carousel-0-2/custom-arrows.amp.html
  test/manual/amp-carousel-0-2/grouping-autoadvance.amp.html
  test/manual/amp-carousel-0-2/grouping-looping.amp.html
  test/manual/amp-carousel-0-2/grouping-move-by-2.amp.html
  test/manual/amp-carousel-0-2/grouping.amp.html
  test/manual/amp-carousel-0-2/max-swipe-one-no-loop.amp.html
  test/manual/amp-carousel-0-2/max-swipe-one.amp.html
  test/manual/amp-carousel-0-2/mixed-lengths-no-snap.amp.html
  test/manual/amp-carousel-0-2/mixed-lengths.amp.html
  test/manual/amp-carousel-0-2/non-looping.amp.html
  test/manual/amp-carousel-0-2/peeking-sides-centered.amp.html
  test/manual/amp-carousel-0-2/peeking-sides-start-aligned.amp.html
  test/manual/amp-carousel-0-2/related-items.amp.html
  test/manual/amp-carousel-0-2/responsive.amp.html
  test/manual/amp-carousel-0-2/three-slides.amp.html
  test/manual/amp-carousel-0-2/tweets.amp.html
  test/manual/amp-carousel-0-2/two-slides.amp.html
  test/manual/amp-carousel-0-2/vertical.amp.html
Labels: cla: yes

#20877 ✨amp-recaptcha-input: Added Origin Trial Support for the experiment
  build-system/dep-check-config.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-input.js
Labels: cla: yes

#20831 ♻️ 🐛: amp-animation: animationWorklet: Only create one module + organizational refactoring
  .eslintignore
  build-system/tasks/compile-expr.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-animation/0.1/amp-animation.js
  extensions/amp-animation/0.1/parsers/css-expr-ast.js
  extensions/amp-animation/0.1/parsers/css-expr-impl.jison
  extensions/amp-animation/0.1/parsers/css-expr-impl.js
  extensions/amp-animation/0.1/parsers/css-expr.js
  extensions/amp-animation/0.1/parsers/keyframes-extractor.js
  extensions/amp-animation/0.1/runners/animation-runner.js
  extensions/amp-animation/0.1/runners/native-web-animation-runner.js
  extensions/amp-animation/0.1/runners/scrolltimeline-worklet-runner.js
  extensions/amp-animation/0.1/test/test-amp-animation.js
  extensions/amp-animation/0.1/test/test-css-expr.js
  extensions/amp-animation/0.1/test/test-keyframes-extractor.js
  extensions/amp-animation/0.1/test/test-web-animations.js
  extensions/amp-animation/0.1/web-animation-types.js
  extensions/amp-animation/0.1/web-animations.js
  extensions/amp-story/0.1/animation.js
  extensions/amp-story/1.0/animation.js
  test/manual/amp-animation/embeds/scrollbound/clock.a4a.html
Labels: cla: yes

#20902 ✨ Enable layers in canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#20859 Reject host service on failures.
  extensions/amp-ad-exit/0.1/amp-ad-exit.js
  extensions/amp-mraid/0.1/amp-mraid.js
  src/inabox/host-services.js
  src/service.js
  test/unit/test-service.js
Labels: cla: yes

#20849 Avoid bundling DOMPurify into amp-bind, amp-mustache-0.1
  build-system/dep-check-config.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-script/0.1/amp-script.js
  src/purifier.js
  src/sanitation.js
  src/sanitizer.js
  src/url-rewrite.js
  test/unit/test-purifier.js
  test/unit/test-url-rewrite.js
Labels: cla: yes

#20874 Keep same macro for A4A and inabox
  build-system/amp4test.js
  extensions/amp-a4a/0.1/a4a-variable-source.js
  extensions/amp-a4a/0.1/test/test-a4a-var-source.js
  test/integration/test-amp-ad-fake.js
Labels: cla: yes

#20909 🖍🐛 Undo stacking lightbox on top
  css/Z_INDEX.md
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
Labels: cla: yes

#20899 Fix regex to detect ad type
  build-system/app.js
Labels: cla: yes

#20644 clean up amp-list-viewport-resize experiment
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  tools/experiments/experiments.js
Labels: cla: yes

#20921 🏗 Clean up pr-check task
  build-system/config.js
  build-system/pr-check.js
  build-system/pr-check/build-targets.js
  build-system/pr-check/build.js
  build-system/pr-check/utils.js
  build-system/pr-check/yarn-checks.js
  build-system/tasks/presubmit-checks.js
Labels: cla: yes

#20940 🐛 Fix optional check
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#20943 🐛 Wait for element to be upgraded before mutate
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
Labels: cla: yes

#20947 🖍✨ Display loaders on all video player components
  src/layout.js
  test/unit/test-layout.js
Labels: cla: yes

#20912 🐛 Do not reset component element on undock
  extensions/amp-video-docking/0.1/amp-video-docking.js
Labels: cla: yes

#20911 ✨Support <amp-dailymotion dock>
  extensions/amp-dailymotion/0.1/test/validator-amp-dailymotion.html
  extensions/amp-dailymotion/0.1/test/validator-amp-dailymotion.out
  extensions/amp-dailymotion/amp-dailymotion.md
  extensions/amp-dailymotion/validator-amp-dailymotion.protoascii
  extensions/amp-video-docking/0.1/test/validator-amp-video-docking-amp-dailymotion.html
  extensions/amp-video-docking/0.1/test/validator-amp-video-docking-amp-dailymotion.out
  extensions/amp-video-docking/amp-video-docking.md
  spec/amp-video-interface.md
Labels: cla: yes

#20534 amd-ad: add type=sas network implementation
  3p/integration.js
  ads/_config.js
  ads/sas.js
  ads/sas.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#20906 ✨Flick to dismiss docked video
  extensions/amp-video-docking/0.1/amp-video-docking.js
  extensions/amp-video-docking/amp-video-docking.md
Labels: cla: yes

#20900 📖 amp-add-this: fix video in documentation
  extensions/amp-addthis/amp-addthis.md
Labels: cla: yes
