Repository ampproject/amphtml, pull requests merged in 2019-03, with the labels that each got.

#20968 Automatically generate sizes attribute for amp-img
  builtins/amp-img.js
  test/manual/amp-img-sizes.amp.html
  test/unit/test-amp-img.js
  test/unit/test-custom-element.js
  tools/experiments/experiments.js
Labels: cla: yes

#21190 🏗 Lock all `amp-foo-latest.js` extensions to their current latest version
  bundles.config.js
  contributing/building-an-amp-extension.md
  gulpfile.js
Labels: Category: Tooling, cla: yes

#21199 🏗 Add a prefix to incoming Renovate PR titles
  renovate.json
Labels: Category: Tooling, cla: yes

#21094 📖 Add docs for inline bookend config
  extensions/amp-story/amp-story.md
Labels: cla: yes

#21211 📖 Update firebase init documentation
  contributing/TESTING.md
Labels: cla: yes

#20683 [amp-story] Animation for expandable components
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.css
Labels: Category: AMP Story, cla: yes

#21205 🏗 Use service account with limited permissions to upload/download build artifacts
  .travis.yml
  build-system/pr-check/utils.js
  build-system/sa-travis-key.json.enc
Labels: cla: yes

#21048 🐛 Amp-viqeo-player: fixing placeholder url
  extensions/amp-viqeo-player/0.1/amp-viqeo-player.js
  extensions/amp-viqeo-player/0.1/test/test-amp-viqeo-player.js
Labels: cla: yes

#21215 🐛 Fix layers dirtying after resize
  src/service/resources-impl.js
Labels: cla: yes

#21173 Adjust `amp-list` container height for both load-end and load-failed elements
  extensions/amp-list/0.1/amp-list.js
  test/manual/amp-list/infinite-scroll-1.amp.html
Labels: cla: yes

#21202 Launch amp-img-auto-sizes to 100% of canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#21083 ✨Support amp-fx=float-in-* in viewer
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets-utils.js
  extensions/amp-fx-collection/0.1/providers/fx-provider.js
  extensions/amp-fx-collection/0.1/scroll-toggle.js
  src/custom-element.js
  src/layout.js
  src/preconnect.js
  src/service/fixed-layer.js
  src/service/jank-meter.js
  src/service/resources-impl.js
  src/service/standard-actions-impl.js
  src/service/url-replacements-impl.js
  src/service/viewport/viewport-binding-ios-embed-sd.js
  src/service/viewport/viewport-impl.js
  test/unit/test-layout.js
Labels: cla: yes

#21232 🐛Fix call on undefined property forEach
  extensions/amp-form/0.1/form-validators.js
Labels: cla: yes

#21158 📖Add documentation for amp-base-carousel.
  extensions/amp-base-carousel/amp-base-carousel.md
  tools/experiments/experiments.js
Labels: cla: yes

#21233 🏗 Reflect new extension docs format in generator
  build-system/tasks/extension-generator/index.js
Labels: cla: yes

#21213 🏗 Copy form values from the browser to the HTML snapshot that gets uploaded to Percy for visual-diff tests
  build-system/tasks/visual-diff/index.js
  build-system/tasks/visual-diff/snippets/freeze-form-values.js
  examples/visual-tests/amp-form/amp-form.amp.html
  examples/visual-tests/amp-form/amp-form.js
  test/visual-diff/visual-tests
Labels: cla: yes

#21165 🏗🐛 Use Octokit's new authentication API
  build-system/tasks/bundle-size.js
Labels: Category: Tooling, cla: yes

#21237 🐛 Fix race condition for `signals`
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
Labels: cla: yes

#21236 ✨Integrate all e2e tests with viewer environment
  build-system/tasks/e2e/amp-driver.js
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/functional-test-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  examples/viewer.html
  extensions/amp-base-carousel/0.1/test-e2e/helpers.js
  extensions/amp-base-carousel/0.1/test-e2e/test-arrows.js
  extensions/amp-base-carousel/0.1/test-e2e/test-autoadvance.js
  extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
  extensions/amp-base-carousel/0.1/test-e2e/test-grouping.js
  extensions/amp-base-carousel/0.1/test-e2e/test-initial-slide.js
  extensions/amp-base-carousel/0.1/test-e2e/test-max-swipe.js
  extensions/amp-base-carousel/0.1/test-e2e/test-mixed-lengths.js
  extensions/amp-base-carousel/0.1/test-e2e/test-non-looping.js
  extensions/amp-base-carousel/0.1/test-e2e/test-responsive.js
  extensions/amp-base-carousel/0.1/test-e2e/test-vertical.js
  extensions/amp-list/0.1/test-e2e/test-load-more-auto.js
  extensions/amp-list/0.1/test-e2e/test-load-more-manual.js
  test/e2e/test-github.js
Labels: cla: yes

#21235 🏗 Add OWNERS.yaml for visual diffs
  examples/visual-tests/OWNERS.yaml
  test/visual-diff/OWNERS.yaml
Labels: cla: yes

#21238 🏗✅ Add a blocking check for invalid extension definitions
  bundles.config.js
  gulpfile.js
Labels: Category: Tooling, cla: yes

#20750 ✨amp-consent: Added a11y focusing for consent UI
  examples/amp-consent-iframe.amp.html
  extensions/amp-consent/0.1/consent-ui.js
  test/manual/amp-consent-cmp-overlay.html
  test/manual/amp-consent-cmp.html
  test/manual/amp-consent-geo.html
  test/manual/diy-consent.html
Labels: cla: yes

#21231 🏗 Install openssl on Travis VMs
  .travis.yml
  build-system/pr-check/utils.js
Labels: cla: yes

#21249 🐛Video: temp workaround for Chrome 72-74 breakage
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
  extensions/amp-ima-video/0.1/amp-ima-video.js
  extensions/amp-youtube/0.1/amp-youtube.js
  src/iframe-video.js
Labels: cla: yes

#21063 ✨ Change lightbox gallery swipe to dismiss UX
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  src/gesture-recognizers.js
Labels: cla: yes

#21272 🏗🐛 Fix two bugs in PR check
  build-system/pr-check/dist-tests.js
  build-system/pr-check/utils.js
Labels: Category: Tooling, cla: yes

#21194 Make changes to support `<amp-inline-gallery>`.
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/carousel.css
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-base-carousel/0.1/dimensions.js
Labels: cla: yes

#21266 🏗 Use gcloud auth for build artifacts
  .travis.yml
  build-system/pr-check/utils.js
Labels: cla: yes

#20805 Inabox: Change use of includes within whitelist checking to indexOf.
  ads/inabox/inabox-messaging-host.js
Labels: cla: yes

#21276 Undo bad code size wins
  src/service/resources-impl.js
  src/service/url-replacements-impl.js
Labels: cla: yes

#21214 Take amp-list routes out of app.js into its own routing file
  build-system/amp-cors.js
  build-system/amp4test.js
  build-system/app.js
  build-system/recaptcha-router.js
  build-system/routes/list.js
  test/manual/amp-list-load-more.amp.html
  test/manual/amp-list/amp-list-data.json
  test/manual/amp-list/amp-list-resize-flex.amp.html
  test/manual/amp-list/amp-list-resize.amp.html
  test/manual/amp-list/amp-list-with-ads.amp.html
  test/manual/amp-list/amp-list.amp.html
  test/manual/amp-list/infinite-scroll-2.amp.html
Labels: cla: yes

#21154 ADJS-443 update refs to js.gumgum
  ads/_config.js
  ads/gumgum.js
Labels: cla: yes

#21270 ✅ Address amp-list-load-more e2e tests
  extensions/amp-list/0.1/test-e2e/test-load-more-auto.js
  extensions/amp-list/0.1/test-e2e/test-load-more-manual.js
Labels: cla: yes

#21271 Implement more of the functional-test-controller API
  build-system/tasks/e2e/functional-test-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
Labels: cla: yes

#21283 🐛 Improve AMP state URL replacement compatibility with PWA (#20853)
  src/service/url-replacements-impl.js
Labels: cla: yes

#21282 🐛 amp-geo: Target AMP body with class changes (#20946)
  extensions/amp-geo/0.1/amp-geo.js
Labels: cla: yes

#21277 Fix [amp-list-load-more] doesn't work with [amp-state] bug
  build-system/routes/list.js
  extensions/amp-list/0.1/amp-list.js
  test/manual/amp-list/load-more-state.amp.html
Labels: cla: yes

#20972 Fix various issues with the inabox integration tests
  build-system/amp4test.js
  test/fixtures/amp-cupcake-ad.html
  test/fixtures/served/iframe-safeframe.html
  test/integration/test-amp-inabox.js
  testing/iframe.js
Labels: cla: yes

#21230 Update amp-story-auto-ads.md
  extensions/amp-story-auto-ads/amp-story-auto-ads.md
Labels: cla: yes

#21293 amp-geo: Fix inconsistent geoState parent
  extensions/amp-geo/0.1/amp-geo.js
Labels: cla: yes

#21300 Fix amp-base-carousel bind validation.
  extensions/amp-bind/0.1/bind-validator.js
Labels: cla: yes

#21289 🚮🖍🚀 Remove amp-story backgrounds
  css/amp.css
  extensions/amp-story/1.0/amp-story-desktop-panels.css
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/pagination-buttons.css
  tools/experiments/experiments.js
Labels: cla: yes

#21159 Enables 'msz' and 'psz' parameters on doubleclick ad requests.
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
  build-system/dep-check-config.js
  examples/fluid.amp.html
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: Category: Ads, cla: yes

#21299 ✅ Use non-default slow threshold for e2e tests
  build-system/tasks/e2e/index.js
Labels: cla: yes

#21307 correct linker document
  extensions/amp-analytics/linker-id-receiving.md
Labels: cla: yes

#21304 Fix the load-more-button does not display bug
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test-e2e/test-load-more-manual.js
  test/manual/amp-list/infinite-scroll-1.amp.html
  test/manual/amp-list/load-more-auto.amp.html
  test/manual/amp-list/load-more-manual.amp.html
Labels: cla: yes

#21298 ✨Enable shadow-demo environment for e2e tests for documents inside PWAs
  build-system/tasks/e2e/amp-driver.js
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/driver/query-xpath.js
  build-system/tasks/e2e/functional-test-controller.js
  build-system/tasks/e2e/index.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  third_party/wgxpath/LICENSE
  third_party/wgxpath/README.amp
  third_party/wgxpath/wgxpath.js
Labels: cla: yes

#21305 Validator rollup
  extensions/amp-story/validator-amp-story.protoascii
  validator/engine/css-selectors.js
  validator/engine/htmlparser.js
  validator/engine/parse-css.js
  validator/engine/validator.js
  validator/testdata/feature_tests/comment_tags.html
  validator/testdata/feature_tests/comment_tags.out
  validator/testdata/transformed_feature_tests/amp-story-cta-layer.html
  validator/testdata/transformed_feature_tests/amp-story-cta-layer.out
  validator/testdata/transformed_feature_tests/server_side_rendering.html
  validator/testdata/transformed_feature_tests/server_side_rendering.out
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: Category: Validator, cla: yes

#21294 Add a method to enable REPL-like debugging on e2e tests
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/repl.js
Labels: cla: yes

#21295 🐛Pause embeds on page change
  extensions/amp-story/1.0/amp-story-embedded-component.js
Labels: Category: AMP Story, cla: yes

#21306 🖍 amp-consent-ui: Removed iframe border-radius on consent fullscreen and width fix
  extensions/amp-consent/0.1/amp-consent.css
Labels: cla: yes

#21320 Add amp-img-auto-sizes to doc-level-optin
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21257 🐛 Move Signals to AmpElement
  build-system/amp.extern.js
Labels: cla: yes

#21319 Performance service can't get other services too early
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#21315 🐛 Fix owners file for `contributing/`
  contributing/OWNERS.yaml
Labels: Related to: Documentation, cla: yes

#21129 🏗 Re-added simple Visual Diff Tests for amp-consent
  build-system/amp-cors.js
  build-system/tasks/visual-diff/helpers.js
  examples/visual-tests/amp-consent/amp-consent.amp.html
  examples/visual-tests/amp-consent/amp-consent.js
  test/visual-diff/visual-tests
Labels: cla: yes

#21321 🚮Remove side-slide-count functionality from amp-base-carousel.
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/array-util.js
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-base-carousel/0.1/test-e2e/test-max-swipe.js
  test/manual/amp-base-carousel/max-swipe-one-no-loop.amp.html
  test/manual/amp-base-carousel/max-swipe-one.amp.html
Labels: cla: yes

#21336 🐛 Fix bad translate from refactor
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js
Labels: cla: yes

#21338 Validator rollup
  validator/testdata/amp4email_feature_tests/amp_form.html
  validator/testdata/amp4email_feature_tests/amp_form.out
  validator/testdata/feature_tests/incorrect_custom_style.html
  validator/testdata/feature_tests/incorrect_custom_style.out
  validator/testdata/feature_tests/inline_style.html
  validator/testdata/feature_tests/inline_style.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#21341 amp-base-carousel: fix the result of some cleanup.
  extensions/amp-base-carousel/0.1/array-util.js
  extensions/amp-base-carousel/0.1/carousel.js
Labels: cla: yes

#21344 🖍 Increase base font-size of amp-story
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#21193 🐛Fix AMP Experiment Render Block with API Changes, and Removed Bad AMP Story definition
  extensions/amp-dynamic-css-classes/0.1/amp-dynamic-css-classes.js
  extensions/amp-experiment/0.1/variant.js
  src/render-delaying-services.js
  test/unit/test-render-delaying-services.js
Labels: cla: yes

#21342 🐛For 32-bit hashes (i.e., non-cryptographic), the value is no longer b…
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#21343 🐛 Update paddingTop after measure cycle
  src/service/viewport/viewport-impl.js
  test/unit/test-viewport.js
Labels: cla: yes

#21210 📖 Add docs for new parameters in zoom/pan animations
  extensions/amp-story/amp-story.md
Labels: cla: yes

#21334 📖Document common questions about writing E2E tests
  build-system/tasks/e2e/README.md
  build-system/tasks/e2e/describes-e2e.js
  contributing/TESTING.md
Labels: cla: yes

#21355 Launch amp-list-load-more to 100% of canary and production
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21153 SSR rendering fix for amp-list
  examples/amp-form.ssr.html
  examples/amp-list.ssr.html
  examples/mustache-to-amp-view-host.amp.html
  examples/viewer.html
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#21323 User activation tracker for gesture control
  extensions/amp-script/0.1/test/unit/test-user-activation-tracker.js
  extensions/amp-script/0.1/user-activation-tracker.js
Labels: cla: yes

#21316 ✅ Re-enable tooltip interactive tests
  examples/visual-tests/amp-story/amp-story-tooltip-desktop.js
  examples/visual-tests/amp-story/amp-story-tooltip.html
  examples/visual-tests/amp-story/amp-story-tooltip.js
  test/visual-diff/visual-tests
Labels: cla: yes

#20497 Enable validation for amp-twitter
  extensions/amp-story/1.0/test/validator-amp-story-amp-twitter-error.html
  extensions/amp-story/1.0/test/validator-amp-story-amp-twitter-error.out
  extensions/amp-story/1.0/test/validator-amp-story-amp-twitter.html
  extensions/amp-story/1.0/test/validator-amp-story-amp-twitter.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: Category: AMP Story, cla: yes

#21370 📖 Add note about `Vary: Accept`.
  build-system/tasks/check-links.js
  spec/amp-cache-transform.md
Labels: Category: Validator, cla: yes

#21358 AdSense Fast Fetch
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Labels: cla: yes

#21375 Clean up adsense-ff-number-delay experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21368 Updating the fullbleed desktop navigation icons.
  extensions/amp-story/1.0/pagination-buttons.css
Labels: cla: yes

#21356 always execute yarn with --production=false flag
  build-system/tasks/update-packages.js
Labels: Category: Tooling, cla: yes

#21369 Story share menu margins and background color.
  extensions/amp-story/1.0/amp-story-share-menu.css
  extensions/amp-story/1.0/amp-story-share.css
Labels: cla: yes

#21372 🐛 Fix minimum swipe distance
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#21378 Validator rollup
  extensions/amp-payment-google-inline-async/0.1/test/validator-actions-amp-payment-google-inline-async.html
  extensions/amp-payment-google-inline-async/0.1/test/validator-actions-amp-payment-google-inline-async.out
  validator/engine/validator.js
  validator/testdata/actions_feature_tests/type_identifier_missing.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#21291 ✨amp-autocomplete: mvp features
  css/amp.css
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.css
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
  extensions/amp-autocomplete/amp-autocomplete.md
  src/string.js
  test/unit/test-string.js
Labels: cla: yes

#21379 ⬆️ ramp up `amp-auto-lightbox` to 50%
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21366 Fix load-more e2e tests
  extensions/amp-list/0.1/test-e2e/test-load-more-auto.js
  test/manual/amp-list/load-more-auto.amp.html
  test/manual/amp-list/load-more-manual.amp.html
Labels: cla: yes

#21383 🐛 Experiment guard dirtyElement call in collapseElement
  src/service/resources-impl.js
Labels: cla: yes

#21174 ✨🐛RE_3:Add support for CAaja ads network
  3p/integration.js
  ads/_config.js
  ads/aja.js
  ads/aja.md
  examples/ads.amp.html
Labels: cla: yes

#21385 ⏪ Revert Support amp-fx=float-in-* in viewer
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets-utils.js
  extensions/amp-fx-collection/0.1/providers/fx-provider.js
  extensions/amp-fx-collection/0.1/scroll-toggle.js
  src/custom-element.js
  src/layout.js
  src/preconnect.js
  src/service/fixed-layer.js
  src/service/jank-meter.js
  src/service/standard-actions-impl.js
  src/service/url-replacements-impl.js
  src/service/viewport/viewport-binding-ios-embed-sd.js
  src/service/viewport/viewport-impl.js
  test/unit/test-layout.js
  test/unit/test-viewport.js
Labels: cla: yes

#21335 Add missing xhr-utils test
  src/utils/xhr-utils.js
  test/unit/utils/test-xhr-utils.js
Labels: cla: yes

#21388 ✅ Add support for Chai true, false and ok expectations
  build-system/tasks/e2e/expect.js
Labels: cla: yes

#21264 Dynamic playlist tag support (amp-brid-player)
  extensions/amp-brid-player/0.1/test/validator-amp-brid-player.html
  extensions/amp-brid-player/0.1/test/validator-amp-brid-player.out
  extensions/amp-brid-player/amp-brid-player.md
  extensions/amp-brid-player/validator-amp-brid-player.protoascii
Labels: cla: yes

#21392 Scrub <script> tags from <head> of ad responses if offsets are missing
  extensions/amp-a4a/0.1/amp-ad-utils.js
  extensions/amp-a4a/0.1/test/test-amp-ad-utils.js
  extensions/amp-a4a/0.1/test/testdata/valid_css_at_rules_amp.reserialized.js
Labels: cla: yes

#21107 ✨ Add "crossorigin" attribute to remote xhr elements to attach id token.
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-bind/0.1/test/test-amp-state.js
  extensions/amp-bind/validator-amp-bind.protoascii
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-list/validator-amp-list.protoascii
  extensions/amp-viewer-assistance/amp-viewer-assistance.md
  src/batched-json.js
  src/services.js
  src/utils/xhr-utils.js
  test/unit/test-batched-json.js
  validator/testdata/actions_feature_tests/amp_bind.html
  validator/testdata/actions_feature_tests/amp_bind.out
  validator/testdata/actions_feature_tests/amp_form.html
  validator/testdata/actions_feature_tests/amp_form.out
  validator/testdata/actions_feature_tests/amp_list.html
  validator/testdata/actions_feature_tests/amp_list.out
  validator/validator-main.protoascii
Labels: cla: yes

#21413 Fix typo in the sidebar documentation.
  extensions/amp-sidebar/amp-sidebar.md
Labels: cla: yes

#21408 🏗🚮 Remove unused webhook notification from .travis.yml
  .travis.yml
Labels: cla: yes

#21401 ✨Read data from `src` attribute on amp-autocomplete.
  examples/autocomplete-cities.example.json
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Labels: cla: yes

#21390 [amp-list] Fix race condition on access to this.loadMoreService_
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list-load-more.js
  test/manual/amp-list/infinite-scroll-1.amp.html
Labels: cla: yes

#21364 Remove adNavTiming, adNavType, and adRedirectCount
  extensions/amp-a4a/0.1/a4a-variable-source.js
  extensions/amp-a4a/0.1/test/test-a4a-var-source.js
  extensions/amp-analytics/0.1/vendors.js
Labels: Category: Ads, Category: Analytics, cla: yes

#21096 🐛✅Fix tickevent tests for Safari
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#21435 🏗 Add test name to error messages in visual-diff
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#21436 AdSense/Doubleclick Fast Fetch adxy experiment
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#21439 Set AdSense/Doubleclick Fast Fetch adxy experiment fraction at 1%
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21448 🐛Make click event available to ancestors of image viewer.
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
Labels: cla: yes

#21445 ♻️ Disable layers prioritization code in extensions
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-image-slider/0.1/amp-image-slider.js
Labels: cla: yes

#21350 🐛Close opacity layer when sidebar for stories closed via action
  examples/visual-tests/amp-story/amp-story-sidebar.html
  examples/visual-tests/amp-story/amp-story-sidebar.js
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#21447 WorkerDOM: upgrade to 0.3.0
  package.json
  yarn.lock
Labels: cla: yes

#21389 WorkerDOM: Require user gesture active for all mutations and start the e2e tests
  build-system/app.js
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test-e2e/test-amp-script.js
  extensions/amp-script/0.1/test/integration/test-amp-script.js
  extensions/amp-script/0.1/user-activation-tracker.js
  test/manual/amp-script/test1.amp.html
  test/manual/amp-script/test1.js
Labels: cla: yes

#21402 ✨ Support dead embeds
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
Labels: Category: AMP Story, cla: yes

#21446 Stories default animations curves and duration.
  extensions/amp-story/1.0/animation-presets.js
  extensions/amp-story/1.0/animation.js
Labels: cla: yes

#21437 🐛 Fix bad calc()
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js
Labels: cla: yes

#21404 WorkerDOM: allow unlimited mutations w/o gesture for size-defined small embeds
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/integration/test-amp-script.js
  extensions/amp-script/amp-script.md
Labels: cla: yes

#21459 Stories animate-in-timing-function parameter validation.
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#21284 ✨ Add CA ProFit-X's new ad serving method
  ads/caprofitx.js
  ads/caprofitx.md
  examples/ads.amp.html
Labels: cla: yes

#21317 ✅ Embedded-components visual tests
  examples/visual-tests/amp-story/amp-story-tooltip-desktop.js
  examples/visual-tests/amp-story/amp-story-tooltip.html
  examples/visual-tests/amp-story/amp-story-tooltip.js
Labels: cla: yes

#21405 WorkerDOM: support long tasks
  examples/amp-script/hello-world-data.json
  examples/amp-script/hello-world.amp.html
  examples/amp-script/hello-world.js
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/integration/test-amp-script.js
  extensions/amp-script/0.1/test/unit/test-user-activation-tracker.js
  extensions/amp-script/0.1/user-activation-tracker.js
Labels: cla: yes

#21442 🚀 Story assets preloading improvements.
  css/amp.css
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#21406 ✨Support rich content on amp-autocomplete.
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
  extensions/amp-autocomplete/amp-autocomplete.md
Labels: cla: yes

#21463 ✨ Validation for new interactive attribute
  extensions/amp-story/1.0/test/validator-amp-story-amp-twitter.html
  extensions/amp-story/1.0/test/validator-amp-story-amp-twitter.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: Category: AMP Story, cla: yes

#21477 Skip flaky test in `test-resources.js`
  test/unit/test-resources.js
Labels: cla: yes

#21427 🐛 Ensure body is available
  src/dom.js
  test/unit/test-dom.js
Labels: cla: yes

#21471 ✅ Add visual diff tests for dead embeds
  examples/visual-tests/amp-story/amp-story-tooltip-desktop.js
  examples/visual-tests/amp-story/amp-story-tooltip.html
  examples/visual-tests/amp-story/amp-story-tooltip.js
  extensions/amp-story/1.0/amp-story-embedded-component.js
Labels: Category: AMP Story, cla: yes

#21415 SSR viewer integration test
  build-system/app.js
  build-system/tasks/presubmit-checks.js
  examples/viewer.html
  extensions/amp-form/0.1/test-e2e/test-ssr.js
  extensions/amp-list/0.1/test-e2e/test-ssr.js
  test/fixtures/e2e/amp-form/amp-form.html
  test/fixtures/e2e/amp-list/amp-list.html
  test/fixtures/e2e/amp-list/amp-list.ssr.html
  test/fixtures/e2e/amp-list/list-data.json
Labels: cla: yes

#21450 ✨Added support for "config" parameter in purch amp-ad adapter.
  ads/purch.js
  ads/purch.md
Labels: cla: yes

#21441 ✨ Implement FunctionalTestController with puppeteer and refactor
  build-system/tasks/e2e/amp-driver.js
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/functional-test-controller.js
  build-system/tasks/e2e/helper.js
  build-system/tasks/e2e/index.js
  build-system/tasks/e2e/package.json
  build-system/tasks/e2e/puppeteer-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  build-system/tasks/e2e/yarn.lock
  contributing/TESTING.md
  extensions/amp-base-carousel/0.1/test-e2e/test-non-looping.js
  extensions/amp-list/0.1/test-e2e/test-load-more-auto.js
  extensions/amp-list/0.1/test-e2e/test-load-more-manual.js
Labels: cla: yes

#21164 ✨ Version bumped amp-experiment to 1.0
  build-system/tasks/presubmit-checks.js
  bundles.config.js
  examples/experiment-1.0.amp.html
  extensions/amp-experiment/1.0/amp-experiment.js
  extensions/amp-experiment/1.0/test/test-amp-experiment.js
  extensions/amp-experiment/1.0/test/test-variant.js
  extensions/amp-experiment/1.0/variant.js
Labels: cla: yes

#21474 ♻️Refactor amp-autocomplete to save the partial user input locally
  extensions/amp-autocomplete/0.1/amp-autocomplete.css
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Labels: cla: yes

#21490 🚮Cleanup amp-list-resizable-children experiment
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/integration/test-amp-list.js
  extensions/amp-list/amp-list.md
  test/manual/amp-list/infinite-scroll-fail.amp.html
Labels: cla: yes

#21475 Fix duplicate items in load-more when scrolling fast
  build-system/routes/list.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list-load-more.js
  test/manual/amp-list/infinite-scroll-1.amp.html
  testing/test-helper.js
Labels: cla: yes

#21483 🐛Change check to see if amp-img has completed layout.
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
Labels: cla: yes

#21493 swg-release 0.1.22.47
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#21472 ✨Support submit-on-enter attribute on amp-autocomplete.
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Labels: cla: yes

#21521 🐛Fix lightbox shim appearing on top of the captions.
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
Labels: cla: yes

#21520 ✨ Add a marker to floodlight request to indicate dynamic tags.
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/gtag.js
Labels: cla: yes

#21519 Whitelist <hr> tag for triple mustache.
  extensions/amp-mustache/0.1/test/test-amp-mustache.js
  extensions/amp-mustache/0.2/test/test-amp-mustache.js
  src/sanitation.js
  test/unit/test-purifier.js
Labels: cla: yes

#21535 📖 Add missing AMP lightning bolts to amp-story spec
  extensions/amp-story/amp-story.md
Labels: cla: yes

#20745 📖 Add docs for clickable elements
  extensions/amp-story/amp-story.md
  extensions/amp-story/img/amp-story-tooltip.gif
Labels: Category: AMP Story, cla: yes

#21495 ✨ Display bound [src] data with amp-bind in amp-autocomplete.
  examples/autocomplete-countries.example.json
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
  extensions/amp-bind/0.1/bind-validator.js
Labels: cla: yes

#21531 Launch amp-img-auto-sizes to 10% of production
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21502 ♻️ Improve tooltip icons logic
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-tooltip.css
  extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
  third_party/optimized-svg-icons/amp-social-share-svgs.css
Labels: Category: AMP Story, cla: yes

#21503 🐛amp-smartlinks fix bug in mapLinks_ function and attribute behavior
  extensions/amp-smartlinks/0.1/linkmate.js
  extensions/amp-smartlinks/0.1/test/test-linkmate.js
Labels: cla: yes

#21518 🐛Include the submit button clicked in POST responses
  extensions/amp-form/0.1/test/test-amp-form.js
  src/form-data-wrapper.js
  src/form.js
  test/unit/test-form-data-wrapper.js
  test/unit/test-form.js
Labels: cla: yes

#21541 🏗 Fix launching IE when running integration tests locally
  build-system/tasks/runtime-test/index.js
Labels: cla: yes

#21538 ✔️ Disable two flaky tests
  test/integration/test-amp-inabox.js
  test/unit/test-resources.js
Labels: cla: yes

#21548 🖍 Enable blurry-image placeholder transition experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21554 📖 Document q-values / media type params alternative.
  spec/amp-cache-transform.md
Labels: cla: yes

#21553 Delegate trust check to action handler
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-viewer-assistance/0.1/amp-viewer-assistance.js
  src/service/action-impl.js
  test/unit/test-action.js
Labels: cla: yes

#21409 ✨Allow LINKER_PARAM macro use more broadly
  examples/linkers.html
  extensions/amp-analytics/0.1/cookie-writer.js
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/linker-reader.js
  extensions/amp-analytics/0.1/test/test-cookie-writer.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-reader.js
  extensions/amp-analytics/0.1/test/test-requests.js
  extensions/amp-analytics/0.1/test/test-resource-timing.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
Labels: cla: yes

#21504 Start flexible ad slot experiment at 1%.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21571 ⬆️ramp up auto-lightbox to 100% for April 2nd prod.
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21563 Revert "Delegate trust check to action handler (#21553)"
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-viewer-assistance/0.1/amp-viewer-assistance.js
  src/service/action-impl.js
  test/unit/test-action.js
Labels: Category: Access, P1: High Priority, Type: Bug, cla: yes

#21564 🐛Move `ad` badge to shadow DOM
  build-system/dep-check-config.js
  bundles.config.js
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-attribution.css
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
Labels: cla: yes

#21562 ✨Allow amp-live-list to fetch from CDN if transformed
  extensions/amp-live-list/0.1/live-list-manager.js
  extensions/amp-live-list/0.1/test/test-live-list-manager.js
  src/service/url-impl.js
Labels: cla: yes

#21565 amp-subscriptions doc: update entitlement response guidance
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes
