Repository ampproject/amphtml, pull requests merged in 2019-07, with the labels that each got.

#23113 🐛 Make sure `rrule` code is included in `amp-date-picker`
  build-system/compile/compile.js
  extensions/amp-date-picker/0.1/dates-list.js
  extensions/amp-date-picker/0.1/test/test-dates-list.js
Labels: Category: Tooling, cla: yes

#23135 Allowing the position attribute on amp-story-grid-layer.
  extensions/amp-story/1.0/test/validator-amp-story-templates.html
  extensions/amp-story/1.0/test/validator-amp-story-templates.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#23026 ✨ New loaders: MVP implementation covering default case
  css/ampshared.css
  src/custom-element.js
  src/loader.js
  src/static-template.js
  test/manual/loaders-new.amp.html
  tools/experiments/experiments.js
Labels: cla: yes

#23111 Remove fallbackToTopWin option for FIE service getter
  src/service.js
  test/unit/test-service.js
Labels: cla: yes

#23138 📖 Documentation for requestOrigin
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#23132 🏗 Remove all single-pass sourcemaps
  build-system/compile/single-pass.js
Labels: cla: yes

#23147 Temporarily disable amp-script until interaction of amp-script and si…
  extensions/amp-script/0.1/test/validator-amp-script-not-origin-trial.out
  extensions/amp-script/0.1/test/validator-amp-script.out
  extensions/amp-script/validator-amp-script.protoascii
Labels: Category: Validator, cla: yes

#23105 correctly pingback multiple entitlements
  extensions/amp-subscriptions/0.1/local-subscription-platform-remote.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Labels: cla: yes

#23106 🏗🚮 Remove workaround to transform Common JS modules to ESM
  build-system/build.conf.js
  build-system/compile/compile.js
  build-system/compile/single-pass.js
  extensions/amp-list/0.1/amp-list.js
  package.json
  src/polyfills/promise.js
  yarn.lock
Labels: Category: Tooling, cla: yes

#23137 Update amp-twitter validation for moments and timelines
  extensions/amp-twitter/0.1/test/validator-amp-twitter.html
  extensions/amp-twitter/0.1/test/validator-amp-twitter.out
  extensions/amp-twitter/validator-amp-twitter.protoascii
  test/manual/amp-twitter.amp.html
Labels: cla: yes

#23136 SwG 0.1.22.59
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#23114 Remove flag ad-type-custom
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#23158 Validator rollup
  extensions/amp-carousel/0.1/test/validator-amp-carousel-error-msg.html
  extensions/amp-carousel/0.1/test/validator-amp-carousel-error-msg.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#23143 amp-script: Add sandbox attr and "allow-forms"
  examples/amp-script/hello-world.amp.html
  extensions/amp-form/amp-form.md
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
  extensions/amp-script/0.1/test/validator-amp-script.html
  extensions/amp-script/0.1/test/validator-amp-script.out
  extensions/amp-script/amp-script.md
  extensions/amp-script/validator-amp-script.protoascii
Labels: cla: yes

#22917 New validation rule for A4A meta tags.
  validator/testdata/amp4ads_feature_tests/amp_story_ad.html
  validator/testdata/amp4ads_feature_tests/amp_story_ad.out
  validator/testdata/amp4ads_feature_tests/amp_story_ad_errors.html
  validator/testdata/amp4ads_feature_tests/amp_story_ad_errors.out
  validator/validator-main.protoascii
Labels: cla: yes

#23180 📖 Document validator JSON endpoint
  validator/README.md
Labels: Category: Validator, Related to: Documentation, cla: yes

#23173 🐛 AMP4Email: Deprecate amp-lightbox and amp-image-lightbox
  extensions/amp-image-lightbox/validator-amp-image-lightbox.protoascii
  extensions/amp-lightbox/validator-amp-lightbox.protoascii
Labels: cla: yes

#23139 Allow Adsense to request single page story ads by implementing spsa request param.
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Labels: cla: yes

#23162 🏗 Apply lint rules and transforms to svg templates
  build-system/babel-plugins/babel-plugin-transform-html-template/index.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/direct/input.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/direct/output.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/indirect/input.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/indirect/output.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/invalid/input.js
  build-system/babel-plugins/babel-plugin-transform-html-template/test/fixtures/transform-assertions/invalid/output.js
  build-system/eslint-rules/html-template.js
  build-system/static-template-metadata.js
Labels: cla: yes

#23149 Fix video autoplay ad start/end masks
  src/service/video-manager-impl.js
  test/integration/test-video-manager.js
Labels: cla: yes

#23163 ♻️🐛 Refactors `getViewerInterceptResponse` and improves tests
  src/utils/xhr-utils.js
  test/unit/utils/test-xhr-utils.js
Labels: cla: yes

#23197 Ramp adsense canonical
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#23199 ♻️ Remove auto-lightbox experiments
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
  extensions/amp-auto-lightbox/0.1/carousel-criteria.js
  extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
  extensions/amp-auto-lightbox/0.1/test/test-carousel-criteria.js
  src/auto-lightbox.js
  tools/experiments/experiments.js
Labels: cla: yes

#23202 Fix devAssert(0) console error.
  extensions/amp-story/1.0/pagination-buttons.js
Labels: cla: yes

#23152 revcontent amp-ad loadscript option
  ads/revcontent.js
  ads/revcontent.md
Labels: cla: yes

#23207 COOKIE macro support in linker
  extensions/amp-analytics/0.1/linker-manager.js
Labels: cla: yes

#23031 Allow in-viewport width-expansion when reflow is not possible
  src/service/resources-impl.js
  test/unit/test-resources.js
Labels: cla: yes

#23110 🚮 Remove navigation state
  build-system/dep-check-config.js
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/navigation-state.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-amp-story.js
  extensions/amp-story/1.0/test/test-analytics.js
  extensions/amp-story/1.0/test/test-navigation-state.js
  extensions/amp-story/1.0/test/test-variable-service.js
  extensions/amp-story/1.0/variable-service.js
Labels: cla: yes

#23204 Rewrite negative responsive units.
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#23130 Update adsense example AMPHTML doc to make example snippet responsive and update supported tags
  ads/google/adsense.md
Labels: cla: yes

#23205 📖 Update amp-truncate-text documentation
  extensions/amp-truncate-text/amp-truncate-text.md
Labels: cla: yes

#23210 Vertical rendering mode triggers all publishers custom CSS animations with no delay.
  extensions/amp-story/1.0/amp-story-vertical.css
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#23212 ✨ SWG: Adds attribute for SmartButton's message text color
  examples/amp-subscriptions-smartbox.amp.html
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Labels: cla: yes

#22902 [Ads] Invibes ad integration
  3p/integration.js
  ads/_config.js
  ads/invibes.js
  ads/invibes.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#23229 📖 Remove experimental note about auto-lightbox
  spec/auto-lightbox.md
Labels: cla: yes

#23153 Extension installation for FIE ampdocs
  extensions/amp-a4a/0.1/a4a-variable-source.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/friendly-frame-util.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
  src/service.js
  src/service/action-impl.js
  src/service/ampdoc-impl.js
  src/service/core-services.js
  src/service/extensions-impl.js
  src/service/hidden-observer-impl.js
  src/service/navigation.js
  src/service/standard-actions-impl.js
  src/service/url-impl.js
  src/style-installer.js
  test/unit/test-extensions.js
  test/unit/test-service.js
Labels: cla: yes

#23227 Validator rollup
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#23041 📖 Add docs for live stories
  extensions/amp-story/amp-story.md
  extensions/amp-story/img/live-stories-gif.gif
Labels: WG: stories, cla: yes

#23234 Remove launched auto-sizes experiment from tests
  test/unit/test-amp-img.js
Labels: cla: yes

#23233 Remove launched auto-sizes experiments from configs
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#22566 ✨ SWG Encryption Client Implementation Change
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions/0.1/test/test-crypto-handler.js
Labels: cla: yes

#23100 ✨ Add MATCH macro
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
Labels: cla: yes

#23246 🐛 Fix async completion bug in `gulp ava`
  build-system/tasks/ava.js
Labels: WG: infra, cla: yes

#23221 amp-script: Polish docs, add tutorials links
  extensions/amp-script/amp-script.md
Labels: cla: yes

#23242 🏗 Silence / fix known warnings that appear when `gulp check-types` detects an error
  build-system/amp.extern.js
  build-system/compile/compile.js
Labels: WG: infra, cla: yes

#23236 📖 Move example animation to be below main heading
  extensions/amp-story/amp-story.md
Labels: cla: yes

#23237 Remove Heroku
  build-system/amp-cors.js
  build-system/tasks/check-links.js
  contributing/TESTING.md
  examples/ads.amp.html
  validator/testdata/feature_tests/ads.html
  validator/testdata/feature_tests/ads.out
Labels: cla: yes

#23253 📖 Re-add support file
  SUPPORT.md
Labels: cla: yes

#23080 Adds 'fws' request parameter for flexible ad slots.
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/flexible-ad-slot-utils.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-flexible-ad-slot-utils.js
  src/utils/dom-ancestor-visitor.js
  test/unit/utils/test-dom-ancestor-visitor.js
Labels: cla: yes

#23243 Cleanup amp-story-desktop-background experiment.
  extensions/amp-story/1.0/amp-story-desktop-panels.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/background.js
  tools/experiments/experiments.js
Labels: cla: yes

#23240 Story desktop GPU memory optimization so videos play smoothly.
  extensions/amp-story/1.0/amp-story-desktop-panels.css
Labels: cla: yes

#22796 Refactor experiments to use localStorage
  build-system/tasks/presubmit-checks.js
  src/experiments.js
  test/unit/test-cid.js
  test/unit/test-experiments.js
  tools/experiments/README.md
  tools/experiments/experiments.html
  tools/experiments/experiments.js
Labels: cla: yes

#23256 🚀 FetchInitDef prerenderSafe param
  build-system/amp.extern.js
  build-system/tasks/presubmit-checks.js
  src/utils/xhr-utils.js
  test/unit/utils/test-xhr-utils.js
Labels: cla: yes

#23241 Remove the auto-sizes experiment entirely
  tools/experiments/experiments.js
Labels: cla: yes

#23267 Upgrade dompurify to 1.0.11 and remove hack
  package.json
  src/purifier.js
  src/sanitation.js
  yarn.lock
Labels: cla: yes

#23268 Only install FIE services on ampdoc in the ampdoc-fie mode
  src/service.js
  test/unit/test-service.js
Labels: cla: yes

#23239 Report iframe activation mismatches for resize
  extensions/amp-ad/0.1/amp-ad-ui.js
  extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
  extensions/amp-ad/0.1/test/test-amp-ad-ui.js
  src/iframe-helper.js
Labels: cla: yes

#22969 ✨ amp-ad type=dynad
  3p/integration.js
  ads/_config.js
  ads/dynad.js
  ads/dynad.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#23282 🏗 Increase parallelism for single pass unless `--pseudo_names` is used
  build-system/compile/compile.js
  build-system/pr-check/single-pass-tests.js
Labels: WG: infra, cla: yes

#23250 🐛♿Restrict focus / screenreaders to sidebar when it is open.
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
  src/modal.js
  src/service/action-impl.js
  test/unit/test-modal.js
  testing/test-helper.js
Labels: cla: yes

#23285 Do not add nameless submit buttons to form data
  src/form-data-wrapper.js
  test/unit/test-form-data-wrapper.js
Labels: cla: yes

#23263 Add a promo to README for AMPCS2019
  README.md
Labels: cla: yes

#22974 📖 Convert ampbyexample iframes to inline preview
  builtins/amp-img.md
  extensions/amp-accordion/amp-accordion.md
  extensions/amp-ad/amp-ad.md
  extensions/amp-carousel/amp-carousel.md
  extensions/amp-fit-text/amp-fit-text.md
  extensions/amp-form/amp-form.md
  extensions/amp-list/amp-list.md
  extensions/amp-twitter/amp-twitter.md
  extensions/amp-video/amp-video.md
Labels: cla: yes

#23290 🏗 Force exact versions during `yarn add`
  .yarnrc
Labels: WG: infra, cla: yes

#23288 Fix 3 viewports down bug
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list-load-more.js
  test/manual/amp-list/infinite-scroll-1.amp.html
Labels: cla: yes

#23141 Fix a11y on amp-pinterest
  extensions/amp-pinterest/0.1/pin-widget.js
  test/manual/amp-pinterest.amp.html
Labels: cla: yes

#23280 🏗 Separate closure warning levels for compile vs. type check
  build-system/compile/compile.js
Labels: WG: infra, cla: yes

#23272 Add SDK integration doc for inabox.
  ads/inabox/inabox-host.md
Labels: cla: yes

#22907 ✨Idealmedia new improvements
  3p/integration.js
  ads/_config.js
  ads/idealmedia.js
  ads/idealmedia.md
  ads/mgid.md
Labels: cla: yes

#23309 Change unselectText() to private method.
  src/service/resources-impl.js
  test/integration/test-visibility-states.js
Labels: cla: yes

#23312 Change resources-impl/rebuildDomWhenReady() to private method.
  src/service/resources-impl.js
  test/unit/test-resource.js
Labels: cla: yes

#23262 AMP viewer and document API
  extensions/amp-viewer-integration/amp-doc-viewer-api.md
Labels: cla: yes

#23122 🐛 Avoid redirects inside amp-access-poool iframe on click events
  extensions/amp-access-poool/0.1/poool-impl.js
  extensions/amp-access-poool/0.1/test/validator-amp-access-poool.html
  extensions/amp-access-poool/0.1/test/validator-amp-access-poool.out
  validator/engine/validator_test.js
  validator/validator-main.protoascii
Labels: cla: yes

#23279 Dispatch a custom event when form dirtiness changes
  extensions/amp-form/0.1/form-dirtiness.js
  extensions/amp-form/0.1/test/test-form-dirtiness.js
  src/amp-events.js
Labels: cla: yes

#23320 Viewer API doc link
  extensions/amp-viewer-integration/amp-doc-viewer-api.md
  extensions/amp-viewer-integration/integrating-viewer-with-amp-doc-guide.md
Labels: cla: yes

#23321 Replace deprecated method call `.createFile` with `.createOrUpdateFile` in bundle-size.js
  build-system/tasks/bundle-size.js
Labels: cla: yes

#23328 Fix IE11 syntax error with attributeFilter without attributes
  extensions/amp-accordion/0.1/amp-accordion.js
Labels: cla: yes

#23310 Remove unused method getMaxDpr().
  src/base-element.js
  src/service/resources-impl.js
Labels: cla: yes

#23308 🏗 Enforce exact versions in `package.json` files
  build-system/git.js
  build-system/pr-check/checks.js
  build-system/tasks/check-exact-versions.js
  build-system/tasks/pr-check.js
  build-system/tasks/presubmit-checks.js
  gulpfile.js
  package.json
  renovate.json
  yarn.lock
Labels: WG: infra, cla: yes

#22895 ✨MGID new improvements
  3p/integration.js
  ads/_config.js
  ads/mgid.js
Labels: cla: yes

#23322 🐛 Animation improvements
  extensions/amp-story/1.0/animation.js
Labels: WG: stories, cla: yes

#23331 Remove getDpr() from resources-impl.js
  src/base-element.js
  src/service/resources-impl.js
Labels: cla: yes

#23297 📖 Update README badges and add badges for project metrics
  README.md
Labels: cla: yes

#23301 🏗 Enable `e2e`, `integration`, and `visual-diff` tests to be run using the `canary` AMP config
  build-system/tasks/e2e/index.js
  build-system/tasks/helpers.js
  build-system/tasks/integration.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/visual-diff/index.js
  contributing/TESTING.md
Labels: WG: infra, cla: yes

#23333 amp-bind: Don't get stuck on sibling-less amp-list
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
Labels: cla: yes

#23306 Add deprecation error when amp-youtube is used in AMPHTML ads.
  extensions/amp-youtube/0.1/amp-youtube.js
  src/custom-element.js
  test/unit/test-custom-element.js
Labels: cla: yes

#23335 Remove isRuntimeOn() from resources-impl.js
  src/service/resources-impl.js
Labels: cla: yes

#23261 amp-script: Use minified amp/worker/worker.js binary
  build-system/tasks/extension-helpers.js
  package.json
  yarn.lock
Labels: cla: yes

#22614 ✨ Adding Kargo RTC Vendor
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-a4a/rtc-documentation.md
  extensions/amp-a4a/rtc-publisher-implementation-guide.md
Labels: cla: yes

#22932 📖 Adds docs for last page visible
  extensions/amp-story/amp-story-analytics.md
Labels: cla: yes

#23035 Create ORIGIN_TRIALS.md to document Trials process
  contributing/ORIGIN_TRIALS.md
Labels: cla: yes

#23284 Pass correct event target from the bookend to the AMP linker
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  src/service/navigation.js
  test/unit/test-navigation.js
Labels: cla: yes

#23327 🏗 Fix sourcemaps in single-pass
  build-system/compile/single-pass.js
  package.json
  yarn.lock
Labels: cla: yes

#23349 🐛 Add validation for allow-blocked-end-date
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.html
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out
  extensions/amp-date-picker/validator-amp-date-picker.protoascii
Labels: cla: yes

#23298 Fix tests for ampdoc-fie mode
  src/service.js
  src/service/navigation.js
  test/unit/test-document-info.js
  test/unit/test-document-submit.js
  test/unit/test-element-service.js
  test/unit/test-friendly-iframe-embed.js
  test/unit/test-intersection-observer-polyfill.js
  test/unit/test-navigation.js
  test/unit/test-resource.js
  test/unit/test-standard-actions.js
  test/unit/test-template.js
  test/unit/test-url-replacements.js
  test/unit/test-viewer.js
Labels: cla: yes

#23351 Story attachment spec update to be consistent with ads CTAs.
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#23200 ✨ Introduce new tick event `cls` (Cumulative Layout Shift).
  build-system/compile/compile.js
  build-system/performance-observer.extern.js
  extensions/amp-viewer-integration/TICKEVENTS.md
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#23355 📖 amp-access-poool: Update documentation & example
  examples/article-access-poool.amp.html
  extensions/amp-access-poool/amp-access-poool.md
Labels: cla: yes

#22641 ✨Add Consent State Macro into Comscore's Vendor Script
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/comscore.js
Labels: cla: yes

#23330 ✨ Es 2015 code generation
  babel.config.js
  build-system/compile/compile.js
  build-system/tasks/helpers.js
Labels: cla: yes

#23085 📖 SwG: Add code highlighting
  extensions/amp-subscriptions-google/amp-subscriptions-google.md
Labels: cla: yes

#23359 Update to reflect potential areas to think about in Design Reviews
  contributing/design-reviews.md
Labels: cla: yes

#23175 ✨ Add support for minify-replace babel plugin
  build-system/build.conf.js
  build-system/global-configs/README.md
  build-system/global-configs/experiments-config.json
  build-system/tasks/helpers.js
  package.json
  yarn.lock
Labels: cla: yes

#23350 ✅ Improve Puppeteer support.
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/puppeteer-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  extensions/amp-base-carousel/0.1/test-e2e/test-arrows.js
  extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
  extensions/amp-base-carousel/0.1/test-e2e/test-non-looping.js
  extensions/amp-base-carousel/0.1/test-e2e/test-responsive.js
  extensions/amp-base-carousel/0.1/test-e2e/test-vertical.js
Labels: cla: yes

#23361 Fix rotation overlay font size.
  extensions/amp-story/1.0/amp-story-viewport-warning-layer.css
Labels: cla: yes

#23215 ✨Added region support in webengage analytics.
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/webengage.js
Labels: cla: yes

#23345 Remove grantBuildPermission() from resources-impl.js
  src/service/resource.js
  src/service/resources-impl.js
  test/unit/test-resource.js
  test/unit/test-resources.js
Labels: cla: yes

#23374 🏗 Reduce closure concurrency during slower compilation operations
  build-system/compile/compile.js
Labels: WG: infra, cla: yes

#23375 🐛 Firefox mobile progress bar glitch fix
  extensions/amp-story/1.0/amp-story-system-layer.css
Labels: cla: yes

#23381 Experiment to support natural viewport binding on iOS
  src/service/viewport/viewport-impl.js
  test/unit/test-viewport.js
  tools/experiments/experiments.js
Labels: cla: yes

#23383 Configure ios-scrollable-iframe experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#23385 Catch all async errors in onerror
  src/error.js
Labels: cla: yes

#23343 Move out renderStarted() from resources-impl.js
  src/service/resources-impl.js
  src/style-installer.js
  test/unit/test-style-installer.js
Labels: cla: yes

#23058 ✨amp-experiment-1.0: Refactor, Select multiple Elements (querySelectorAll)
  examples/experiment-1.0.amp.html
  extensions/amp-experiment/1.0/amp-experiment.js
  extensions/amp-experiment/1.0/apply-experiment.js
  extensions/amp-experiment/1.0/attribute-allow-list/allowed-attribute-mutation-entry.js
  extensions/amp-experiment/1.0/attribute-allow-list/attribute-allow-list.js
  extensions/amp-experiment/1.0/mutation-parser.js
  extensions/amp-experiment/1.0/mutation-record.js
  extensions/amp-experiment/1.0/mutation/attribute-mutation-default-class.js
  extensions/amp-experiment/1.0/mutation/attribute-mutation-default-style.js
  extensions/amp-experiment/1.0/mutation/attribute-mutation-default-url.js
  extensions/amp-experiment/1.0/mutation/character-data-mutation.js
  extensions/amp-experiment/1.0/mutation/mutation.js
  extensions/amp-experiment/1.0/test/test-amp-experiment.js
  extensions/amp-experiment/1.0/test/test-apply-experiment.js
  extensions/amp-experiment/1.0/test/test-attribute-allow-list.js
  extensions/amp-experiment/1.0/test/test-attribute-mutation.js
  extensions/amp-experiment/1.0/test/test-character-data-mutation.js
  extensions/amp-experiment/1.0/test/test-mutation-parser.js
  extensions/amp-experiment/1.0/test/test-mutation-record.js
  extensions/amp-experiment/1.0/test/test-mutation.js
Labels: cla: yes

#23382 🏗 [pr-deploy-bot] Add html files to dist package that Travis uploads
  build-system/pr-check/utils.js
  build-system/tasks/pr-deploy-bot-utils.js
Labels: cla: yes

#22024 ✨Add RnetPlus ad exchange support to amp-ad
  3p/integration.js
  ads/_config.js
  ads/rnetplus.js
  ads/rnetplus.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#23245 amp-script: Allow removal of attributes
  extensions/amp-script/0.1/amp-script.js
  src/purifier.js
  test/unit/test-purifier.js
Labels: cla: yes

#23313 Remove resources-impl.getViewport()
  extensions/amp-auto-ads/0.1/placement.js
  src/service/resource.js
  src/service/resources-impl.js
  test/unit/test-resource.js
  test/unit/test-resources.js
Labels: cla: yes

#23067 Cleanup amp-force-prerender-visible-elements configuration files.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  tools/experiments/experiments.js
Labels: cla: yes

#23401 🖍 AMP FIE CSS cleanup Doubleclick/Adsense experiment
  ads/google/a4a/utils.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#23424 📖 Update AMP for Email CSS docs
  spec/email/amp-email-css.md
Labels: Related to: Documentation, WG: amp4email, cla: yes

#23414 Clean up "margin-bottom-in-content-height" experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  src/service/viewport/viewport-binding-def.js
  test/unit/test-viewport.js
  tools/experiments/experiments.js
Labels: cla: yes

#23030 📈 Initial StorySpec Implementation
  examples/amp-story/analytics.html
  examples/analytics.amp.html
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-analytics/0.1/events.js
  extensions/amp-analytics/0.1/test/test-events.js
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-analytics.js
  src/analytics.js
Labels: WG: stories, cla: yes

#23339 📖 Add README badge for release-cherrypick-count metric
  README.md
Labels: cla: yes

#23418 Move getElementLayoutBox
  extensions/amp-auto-ads/0.1/ad-tracker.js
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-auto-ads/0.1/test/test-ad-tracker.js
  extensions/amp-auto-ads/0.1/test/test-placement.js
  extensions/amp-auto-ads/0.1/test/test-utils.js
  extensions/amp-auto-ads/0.1/utils.js
  src/service/resource.js
  src/service/resources-impl.js
  test/unit/test-resource.js
  test/unit/test-resources.js
Labels: cla: yes

#23380 🐛 Mark collapse attempt denied as an expected error
  src/service/resources-impl.js
Labels: cla: yes

#23255 🚮 a4a: remove obsolete experiments
  ads/google/a4a/traffic-experiments.js
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#23387 🐛 Fix ooyala when event data is null
  extensions/amp-ooyala-player/0.1/amp-ooyala-player.js
Labels: cla: yes

#23438 Add integration test for FIE rendering.
  build-system/amp4test.js
  test/integration/test-amphtml-ads.js
Labels: cla: yes

#23269 ✨ Updates SWG to use prerenderSafe fetch param
  build-system/tasks/presubmit-checks.js
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Labels: cla: yes

#23293 Adding ads network Nativeroll
  3p/integration.js
  ads/_config.js
  ads/nativeroll.js
  ads/nativeroll.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#23201 Various optimizations to AMP inabox friendly iframe position observer.
  ads/inabox/inabox-messaging-host.js
  ads/inabox/position-observer.js
  build-system/amp.extern.js
  src/inabox/inabox-viewport.js
  test/unit/inabox/test-position-observer.js
Labels: cla: yes

#23395 ✨ RevContent new ad code support
  ads/revcontent.js
  ads/revcontent.md
Labels: cla: yes

#23423 ✨ opinary amp detection
  ads/opinary.js
Labels: cla: yes

#23427 🏗 Enable package updates for E2E and visual diff tests
  build-system/tasks/e2e/index.js
  build-system/tasks/e2e/package.json
  build-system/tasks/visual-diff/package.json
Labels: WG: infra, cla: yes

#23386 🐛 Enforce amp-ad type=custom has an HTTPS data-url
  extensions/amp-ad/0.1/amp-ad-custom.js
  extensions/amp-ad/0.1/test/validator-amp-ad.html
  extensions/amp-ad/0.1/test/validator-amp-ad.out
  extensions/amp-ad/validator-amp-ad.protoascii
Labels: cla: yes

#23431 🐛 Catch invalid json responses in amp-addthis
  extensions/amp-addthis/0.1/addthis-utils/pixel.js
Labels: cla: yes

#23439 🐛Remove string.trimStart() from expander
  src/service/url-expander/expander.js
  src/string.js
Labels: cla: yes

#23442 🐛 Cleanup detached layers periodically
  src/service/layers-impl.js
Labels: cla: yes

#23435 🏗️ Ban new prototype APIs
  build-system/conformance-config.textproto
Labels: cla: yes

#23388 ✨ Add babel replace plugin to unit gulp task
  build-system/tasks/helpers.js
  build-system/tasks/karma.conf.js
Labels: cla: yes

#22911 Render page descriptions for bot user agents
  examples/amp-story/ampconf.html
  examples/visual-tests/amp-story/amp-story-bot-rendering.html
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-vertical.css
  test/visual-diff/visual-tests
Labels: cla: yes

#23413 Reorg analytics instrumentation/roots/visibility to support FIE ampdocs
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-analytics/0.1/instrumentation.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-analytics-root.js
  extensions/amp-analytics/0.1/test/test-instrumentation.js
  extensions/amp-analytics/0.1/visibility-manager.js
  src/friendly-iframe-embed.js
  src/service.js
  src/service/ampdoc-impl.js
  src/services.js
  test/unit/test-ampdoc.js
  test/unit/test-friendly-iframe-embed.js
Labels: cla: yes

#23458 SwG 0.1.22.61 release
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#23466 🧪Add integration test for nested macro with leading space.
  test/integration/test-amp-pixel.js
Labels: cla: yes

#23472 Add no-duplicate-name-typedefs eslint rule
  .eslintrc
  build-system/eslint-rules/no-duplicate-name-typedef.js
  extensions/amp-access-laterpay/0.1/laterpay-impl.js
  extensions/amp-access-laterpay/0.2/laterpay-impl.js
  extensions/amp-story/0.1/logging.js
  extensions/amp-story/0.1/media-pool.js
  extensions/amp-story/0.1/pagination-buttons.js
  extensions/amp-story/1.0/logging.js
  extensions/amp-story/1.0/media-pool.js
  extensions/amp-story/1.0/pagination-buttons.js
Labels: cla: yes

#23410 ✨ Add expiration time to experiments
  build-system/build.conf.js
  build-system/global-configs/README.md
  build-system/global-configs/experiments-config.json
  build-system/tasks/presubmit-checks.js
Labels: cla: yes

#23471 Add some missing visibleForTesting annotations.
  src/friendly-iframe-embed.js
  src/service/resources-impl.js
Labels: cla: yes

#23366 ✨ Fork media amp-ad support
  3p/integration.js
  ads/_config.js
  ads/forkmedia.js
  ads/forkmedia.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#23469 📖 Add plots of historical metric values
  METRICS.md
Labels: cla: yes
