Repository ampproject/amphtml, pull requests merged in 2019-05, with the labels that each got.

#22085 Revert "📦 Update dependency google-closure-compiler to v20190415"
  package.json
  yarn.lock
Labels: cla: yes

#22077 🏗🚮 Remove blank lines from copyright licenses in `v0.js` without breaking sourcemaps
  build-system/compile/compile.js
  build-system/compile/shorten-license.js
  build-system/compile/single-pass.js
Labels: Category: Tooling, cla: yes

#22066 🐛 Fix autoexpand text areas with relative widths
  extensions/amp-form/0.1/amp-form-textarea.js
  extensions/amp-form/0.1/test/test-amp-form-textarea.js
  test/manual/amp-form-textarea-table.amp.html
Labels: cla: yes

#21972 Better support for HTMLMediaElement in the loadPromise helper.
  extensions/amp-audio/0.1/amp-audio.js
  extensions/amp-audio/0.1/test/test-amp-audio.js
  extensions/amp-video/0.1/amp-video.js
  src/event-helper.js
Labels: cla: yes

#22081 ✅ Fix carousel arrows non looping e2e test
  extensions/amp-base-carousel/0.1/test-e2e/test-arrows-non-looping.js
  extensions/amp-base-carousel/0.1/test-e2e/test-non-looping.js
  test/manual/amp-base-carousel/non-looping.amp.html
Labels: cla: yes

#22011 Web validator publisher checklist message on success
  validator/webui/@polymer/webui-statusbar/webui-statusbar.html
Labels: cla: yes

#22096 Update publisher checklist links
  validator/engine/validator.js
  validator/gulpjs/index.js
Labels: cla: yes

#22053 Cleanup amp-img-auto-sizes experiment
  builtins/amp-img.js
  builtins/amp-img.md
Labels: cla: yes

#22107 Math Functions: Sqrt and Log function added ✨
  extensions/amp-bind/0.1/bind-expression.js
  extensions/amp-bind/0.1/test/test-bind-expression.js
Labels: cla: yes

#22093 🏗 Use scrollTo instead of scrollBy in some E2E tests
  build-system/pr-check/local-tests.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  extensions/amp-base-carousel/0.1/test-e2e/test-arrows-non-looping.js
  extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
  extensions/amp-base-carousel/0.1/test-e2e/test-grouping.js
Labels: cla: yes

#22109 🏗♻️ Split `gulpfile.js` into separate files
  build-system/compile/closure-compile.js
  build-system/tasks/build.js
  build-system/tasks/check-types.js
  build-system/tasks/css.js
  build-system/tasks/dist.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
  build-system/tasks/index.js
  build-system/tasks/nailgun.js
  build-system/tasks/presubmit-checks.js
  gulpfile.js
Labels: Category: Tooling, cla: yes

#22115 Add a template for release tracking issues
  .github/ISSUE_TEMPLATE/release-tracking-issue.md
Labels: cla: yes

#21905 ✨ Added connatix player extension
  bundles.config.js
  examples/connatix-player.amp.html
  extensions/amp-connatix-player/0.1/amp-connatix-player.js
  extensions/amp-connatix-player/0.1/test/test-amp-connatix-player.js
  extensions/amp-connatix-player/0.1/test/validator-amp-connatix-player.html
  extensions/amp-connatix-player/0.1/test/validator-amp-connatix-player.out
  extensions/amp-connatix-player/amp-connatix-player.md
  extensions/amp-connatix-player/validator-amp-connatix-player.protoascii
Labels: cla: yes

#22111 Update end-to-end guide for new governance/process
  contributing/getting-started-e2e.md
Labels: cla: yes

#22078 📖 amp-subscriptions iframe local platform doc
  extensions/amp-access/0.1/iframe-api/README.md
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#22110 Point Code of Conduct to meta
  CODE_OF_CONDUCT.md
Labels: cla: yes

#22119 Update the select event on amp-autocomplete
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
  extensions/amp-autocomplete/amp-autocomplete.md
  src/utils/key-codes.js
Labels: cla: yes

#22095 amp-list script template integration test
  extensions/amp-list/0.1/test/integration/test-amp-list.js
Labels: cla: yes

#22125 🏗✨Upgrade to `gulp` v4 and migrate all tasks to the new API
  build-system/check-package-manager.js
  build-system/compile/closure-compile.js
  build-system/compile/compile.js
  build-system/compile/single-pass.js
  build-system/pr-check.js
  build-system/server.js
  build-system/tasks/ava.js
  build-system/tasks/build.js
  build-system/tasks/bundle-size.js
  build-system/tasks/changelog.js
  build-system/tasks/check-links.js
  build-system/tasks/check-types.js
  build-system/tasks/clean.js
  build-system/tasks/compile-expr.js
  build-system/tasks/create-golden-css/index.js
  build-system/tasks/create-module-compatible-es5-bundle.js
  build-system/tasks/css.js
  build-system/tasks/csvify-size/index.js
  build-system/tasks/dep-check.js
  build-system/tasks/dev-dashboard-tests.js
  build-system/tasks/dist.js
  build-system/tasks/e2e/index.js
  build-system/tasks/extension-generator/index.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/firebase.js
  build-system/tasks/get-zindex/index.js
  build-system/tasks/get-zindex/test.js
  build-system/tasks/helpers.js
  build-system/tasks/index.js
  build-system/tasks/jsify-css.js
  build-system/tasks/json-check.js
  build-system/tasks/lint.js
  build-system/tasks/nailgun.js
  build-system/tasks/pr-check.js
  build-system/tasks/prepend-global/index.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/process-3p-github-pr.js
  build-system/tasks/process-github-issues.js
  build-system/tasks/release-tagging.js
  build-system/tasks/runtime-test/index.js
  build-system/tasks/runtime-test/status-report.js
  build-system/tasks/serve.js
  build-system/tasks/size.js
  build-system/tasks/todos.js
  build-system/tasks/update-packages.js
  build-system/tasks/validator.js
  build-system/tasks/visual-diff/index.js
  build-system/tasks/visual-diff/percy-assets-loader.js
  gulpfile.js
  package.json
  yarn.lock
Labels: Category: Tooling, cla: yes

#22134 🏗🐛 Make `validator` functions `async` so that their `gulp` tasks complete
  build-system/tasks/validator.js
Labels: Category: Tooling, cla: yes

#22132 🏗🐛 Fix flaky Karma startup by refreshing the `wd` cache (again)
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/index.js
Labels: Category: Tooling, cla: yes

#22135 🏗🚮🐛 Assorted `gulp` compilation fixes
  build-system/tasks/css.js
  build-system/tasks/dist.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/firebase.js
  build-system/tasks/helpers.js
  build-system/tasks/prepend-global/index.js
  build-system/tasks/runtime-test/index.js
Labels: Category: Tooling, cla: yes

#21980 🏗 Stability and developer-experience changes for visual diffs testing platform
  build-system/tasks/visual-diff/helpers.js
  build-system/tasks/visual-diff/index.js
  build-system/tasks/visual-diff/snippets/snapshot-error.html
Labels: cla: yes

#21988 Optional story page attachment title.
  extensions/amp-story/1.0/amp-story-page-attachment-header.css
  extensions/amp-story/1.0/amp-story-page-attachment.js
Labels: cla: yes

#22094 ✨ Support ability to 'disable' an item on amp-autocomplete.
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.css
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
Labels: cla: yes

#22131 amp-script: Allow attribute mutations on built-ins
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
  src/purifier.js
  test/unit/test-purifier.js
Labels: cla: yes

#22091 Add --custom_version_mark to build jobs to set a custom last digit to the RTV number
  build-system/git.js
  build-system/internal-version.js
  build-system/tasks/helpers.js
Labels: cla: yes

#22137 ♻️Move VariableService to doc level
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/cookie-writer.js
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/resource-timing.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-cookie-writer.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-analytics/0.1/test/test-requests.js
  extensions/amp-analytics/0.1/test/test-resource-timing.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
Labels: cla: yes

#22153 Revert "✅ Make visual tests non-blocking"
  .travis.yml
Labels: Category: Tooling, Related to: Flaky Tests, cla: yes

#22161 Disable flaky visual diff test "amp-accordion: page loads"
  test/visual-diff/visual-tests
Labels: cla: yes

#22155 update extension generator to amp.dev
  build-system/tasks/extension-generator/index.js
Labels: Category: Tooling, Category: Validator, cla: yes

#22163 ✅ Skip timing out tests.
  test/integration/test-amp-skimlinks.js
Labels: cla: yes

#22129 Prevent default action only on elements that invoke an AMP action.
  src/service/action-impl.js
  test/unit/test-action.js
Labels: cla: yes

#21884 Set auto ads responsive holdback to 0 traffic
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21885 Clean up responsive experiment for auto ads
  ads/google/adsense-amp-auto-ads-responsive.js
  ads/google/test/test-adsense-amp-auto-ads-responsive.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-auto-ads/0.1/ad-network-config.js
  extensions/amp-auto-ads/0.1/amp-auto-ads.js
  extensions/amp-auto-ads/0.1/test/test-ad-network-config.js
Labels: cla: yes

#22084 🐛 amp inabox: Removed height: auto !important for the amp4ads use case
  css/amp.css
  examples/ads/inabox.adchoices.creative.html
  examples/ads/inabox.adchoices.html
  examples/inabox.gpt.html
  src/service/viewport/viewport-impl.js
  test/unit/test-viewport.js
  tools/experiments/experiments.js
Labels: cla: yes

#22118 🐛 amp inabox: Added the inabox `height: auto !important` experiment to the prod config
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21834 📖 amp-recaptcha-input: Added amp.dev example
  extensions/amp-recaptcha-input/amp-recaptcha-input.md
Labels: cla: yes

#22092 🐛Propagate data-ad-host attribute to ad url param for amp-auto-ads
  extensions/amp-auto-ads/0.1/ad-network-config.js
  extensions/amp-auto-ads/0.1/test/test-ad-network-config.js
Labels: cla: yes

#21716 For AdSense, expect checksum to be a 32-bit integer that is not base-…
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Labels: cla: yes

#21943 Docs: remove "experimental" (overloaded term)
  extensions/amp-story/amp-story.md
Labels: cla: yes

#21671 🖍🚀🐛support for CAaja ads network
  ads/_config.js
  ads/aja.js
  ads/aja.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: Category: Ads, cla: yes

#22181 ✅ Skip all amp-skimlinks integration tests.
  test/integration/test-amp-skimlinks.js
Labels: cla: yes

#22187 Allow SVG elements in Stories.
  extensions/amp-story/1.0/test/validator-amp-story-svg-error.html
  extensions/amp-story/1.0/test/validator-amp-story-svg-error.out
  extensions/amp-story/1.0/test/validator-amp-story-svg.html
  extensions/amp-story/1.0/test/validator-amp-story-svg.out
  extensions/amp-story/amp-story.md
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#22196 Update validator output due to changed message.
  extensions/amp-story/1.0/test/validator-amp-story-svg-error.out
Labels: cla: yes

#22175 ✨Add support for mask-trim-zeros attribute on amp-inputmask.
  examples/masking-trim.amp.html
  extensions/amp-inputmask/0.1/inputmask-custom-alias.js
  extensions/amp-inputmask/0.1/mask-impl.js
  extensions/amp-inputmask/0.1/test/test-inputmask-custom-alias.js
  extensions/amp-inputmask/0.1/test/test-mask-impl.js
  extensions/amp-inputmask/0.1/test/validator-amp-inputmask.html
  extensions/amp-inputmask/0.1/test/validator-amp-inputmask.out
  extensions/amp-inputmask/amp-inputmask.md
  extensions/amp-inputmask/validator-amp-inputmask.protoascii
Labels: cla: yes

#22186 Added note about ads and flying carpets
  extensions/amp-fx-flying-carpet/amp-fx-flying-carpet.md
Labels: cla: yes

#22128 🌐 Support RTL inputs and datasets on amp-autocomplete
  examples/autocomplete.amp.html
  examples/visual-tests/amp-autocomplete/amp-autocomplete.amp.html
  examples/visual-tests/amp-autocomplete/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
Labels: cla: yes

#22199 🍎 🐛 amp-lightbox: prevent iOS scroll freeze in both directions.
  extensions/amp-lightbox/0.1/amp-lightbox.js
Labels: cla: yes

#22166 updated documentation on sizes attribute behavior on amp-img
  builtins/amp-img.md
Labels: cla: yes

#22083 amp-script: Share size limit across elements
  extensions/amp-script/0.1/amp-script.js
Labels: cla: yes

#22207 🐞Fix dev server shadow mode.
  build-system/shadow-viewer.js
Labels: cla: yes

#22147 🏗♻️Refactor `compileJs` into smaller functions
  build-system/tasks/helpers.js
  build-system/typescript.js
Labels: Category: Tooling, cla: yes

#21647 ✨amp-consent: consent-ui Allow passing in the reason for prompt in the iframe name attribute
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
Labels: cla: yes

#22165 Skip flaky A4A test
  test/integration/test-amp-ad-fake.js
Labels: cla: yes

#22191 🚮 Delete auto ads responsive experiment from experiments.js
  tools/experiments/experiments.js
Labels: cla: yes

#22202 toggleAutoplay is an action, not an event
  spec/amp-actions-and-events.md
Labels: cla: yes

#22205 amp-bind: Update textarea initial value via [defaultText]
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/bind-validator.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-bind/0.1/test/validator-amp-bind.html
  extensions/amp-bind/0.1/test/validator-amp-bind.out
  extensions/amp-bind/amp-bind.md
  validator/validator-main.protoascii
Labels: cla: yes

#22218 Revert "♻️Move VariableService to doc level"
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/cookie-writer.js
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/resource-timing.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-cookie-writer.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-analytics/0.1/test/test-requests.js
  extensions/amp-analytics/0.1/test/test-resource-timing.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
Labels: cla: yes

#22058 ✨ Implementing subscriptions encryption to work with the Viewer
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#21667 🏗 Enable local testing on IE11
  build-system/tasks/runtime-test/index.js
  src/mode.js
  src/polyfills.js
Labels: cla: yes

#22210 🏗 Retry tests before failing them on Travis
  build-system/tasks/karma.conf.js
Labels: Category: Tooling, cla: yes

#22029 ✨Add allow-blocked-end-date flag and e2e test
  build-system/app-test.js
  build-system/tasks/e2e/functional-test-controller.js
  build-system/tasks/e2e/puppeteer-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/date-picker-common.js
  extensions/amp-date-picker/0.1/dates-list.js
  extensions/amp-date-picker/0.1/test-e2e/test-blocked-dates.js
  extensions/amp-date-picker/amp-date-picker.md
  test/fixtures/e2e/amp-date-picker/blocked-dates.html
Labels: cla: yes

#22226 SwG Release 0.1.22.50
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#22223 Experiment to disable transfer layer in 12.2 and above
  src/service/viewport/viewport-binding-ios-embed-sd.js
  src/service/viewport/viewport-binding-ios-embed-wrapper.js
  src/service/viewport/viewport-impl.js
  test/unit/test-viewport-binding.js
  test/unit/test-viewport.js
  tools/experiments/experiments.js
Labels: cla: yes

#22224 Config for ios-fixed-no-transfer experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#22189 ✨🖍🐛 Lightbox captions changes.
  css/Z_INDEX.md
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/lightbox-caption.css
  extensions/amp-lightbox-gallery/0.1/lightbox-caption.js
  test/manual/amp-lightbox-gallery-launch-captions.amp.html
Labels: cla: yes

#22231 validator.amp.dev is live, update links
  extensions/amp-viewer-integration/integrating-viewer-with-amp-doc-guide.md
  validator/chromeextension/popup-validator.html
  validator/engine/validator.js
  validator/webui/README.md
  validator/webui/index.html
  validator/webui/serve-standalone.go
  validator/webui/serve.go
Labels: Category: Validator, cla: yes

#22236 Validator rollup
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#22206 🏗 Clean up describes-e2e
  build-system/tasks/e2e/describes-e2e.js
Labels: cla: yes

#22100 Support for MGID
  3p/integration.js
  ads/_config.js
  ads/mgid.js
  ads/mgid.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#22101 Support for Lentainform
  3p/integration.js
  ads/_config.js
  ads/lentainform.js
  ads/lentainform.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#22248 🏗 Re add IE11 to our CI in blocking mode
  build-system/config.js
  build-system/tasks/runtime-test/index.js
  test/integration/test-configuration.js
Labels: cla: yes

#21752 ✨amp-consent: Added support for allowing CMPs to add their own documentation and examples for amp-consent
  build-system/app.js
  examples/cmp-vendors.amp.html
  extensions/amp-consent/amp-consent.md
  extensions/amp-consent/cmps/_ping_.md
  extensions/amp-consent/integrating-consent.md
Labels: cla: yes

#22250 🐛✅Update failing autocomplete e2e test
  extensions/amp-autocomplete/0.1/test-e2e/test-amp-autocomplete.js
Labels: cla: yes

#22102 Support for Idealmedia
  3p/integration.js
  ads/_config.js
  ads/idealmedia.js
  ads/idealmedia.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#21778 ✨ Support dynamically added lists and add configuration options
  extensions/amp-live-list/0.1/amp-live-list.js
  extensions/amp-live-list/0.1/live-list-manager.js
  extensions/amp-live-list/0.1/test/test-amp-live-list.js
  extensions/amp-live-list/0.1/test/test-live-list-manager.js
Labels: cla: yes

#21855 🐛 web-worker: Set error reporter
  src/dom.js
  src/error.js
  src/get-bounding-client-rect.js
  src/polyfills.js
  src/polyfills/custom-elements.js
  src/polyfills/document-contains.js
  src/web-worker/web-worker.js
Labels: cla: yes

#22254 🏗♻️🚮🐛 Refactor `compile()` in `build-system/tasks/helpers.js`
  build-system/compile/compile.js
  build-system/tasks/build.js
  build-system/tasks/check-types.js
  build-system/tasks/dist.js
  build-system/tasks/helpers.js
Labels: Category: Tooling, cla: yes

#21781 🚀 Use a multislot request for pubmine ads
  ads/_config.js
  ads/pubmine.js
  examples/ads.amp.html
Labels: cla: yes

#21909 🚮 Remove support for xhr identity attribute "cross-origin".
  extensions/amp-bind/validator-amp-bind.protoascii
  extensions/amp-list/validator-amp-list.protoascii
  src/utils/xhr-utils.js
  validator/testdata/actions_feature_tests/amp_bind.html
  validator/testdata/actions_feature_tests/amp_bind.out
  validator/testdata/actions_feature_tests/amp_form.html
  validator/testdata/actions_feature_tests/amp_form.out
  validator/testdata/actions_feature_tests/amp_list.html
  validator/testdata/actions_feature_tests/amp_list.out
  validator/validator-main.protoascii
Labels: cla: yes

#22244 Override global scrollTo in iOS embed cases
  src/inabox/inabox-viewport.js
  src/service/viewport/viewport-binding-def.js
  src/service/viewport/viewport-binding-ios-embed-sd.js
  src/service/viewport/viewport-binding-ios-embed-wrapper.js
  src/service/viewport/viewport-binding-natural.js
  src/service/viewport/viewport-impl.js
  test/unit/test-viewport-binding.js
  test/unit/test-viewport.js
Labels: cla: yes

#22256 🏗♻️ Refactor post-compilation config writes
  build-system/tasks/dist.js
  build-system/tasks/helpers.js
  build-system/tasks/prepend-global/index.js
Labels: Category: Tooling, cla: yes

#22269 🐛 Store the native getBoundingClientRect before patching
  src/get-bounding-client-rect.js
Labels: cla: yes

#22242 Remove position: absolute when measuring fluid creative height.
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js
Labels: cla: yes

#22263 🏗✨🐛 Run tests against minified code during PR checks
  .travis.yml
  build-system/pr-check/build.js
  build-system/pr-check/dist-bundle-size.js
  build-system/pr-check/remote-tests.js
  build-system/pr-check/single-pass-tests.js
  build-system/pr-check/validator-tests.js
  build-system/pr-check/yarn-checks.js
  build-system/tasks/presubmit-checks.js
Labels: Category: Tooling, cla: yes

#22255 Write cookies to eTLD+1
  extensions/amp-analytics/0.1/cookie-writer.js
  extensions/amp-analytics/0.1/test/test-cookie-writer.js
  testing/fake-dom.js
Labels: cla: yes

#22257 Add dirtyBit support to stored consent value
  build-system/app.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-info.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  test/manual/amp-consent-cmp.html
Labels: cla: yes

#20860 Rename Chargeads to Newsroom AI
  3p/integration.js
  ads/_config.js
  ads/nws.js
  ads/nws.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#22272 ♻️ SwG Crypto naming change: "keys" -> "cryptokeys"
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions/0.1/crypto-handler.js
  extensions/amp-subscriptions/0.1/test/test-crypto-handler.js
Labels: cla: yes

#22274 🐛 amp inabox: Removed margin: auto !important for the amp4ads use case
  css/amp.css
Labels: cla: yes

#22164 🏗 End e2e task with grace
  build-system/tasks/e2e/index.js
Labels: cla: yes

#22221 amp form submit-error action fix
  extensions/amp-form/0.1/amp-form.js
Labels: cla: yes

#22283 Add Intent-to-Deprecate and Intent-to-Remove templates
  .github/ISSUE_TEMPLATE/intent-to-deprecate--i2d-.md
  .github/ISSUE_TEMPLATE/intent-to-remove--i2r-.md
Labels: cla: yes

#22252 ✨Add shadow integration test for amp analytics
  build-system/amp4test.js
  build-system/app.js
  build-system/shadow-viewer.js
  test/integration/test-amp-analytics.js
  testing/describes.js
Labels: cla: yes

#22284 🐛 Fix lint error in 3p/integration.js
  3p/integration.js
Labels: cla: yes

#22044 📖 Fix broken links in AMP4Email spec.
  spec/amp-email-format.md
Labels: cla: yes

#22290 🐛Fix usage of `getElementsByTagName` on ShadowRoot.
  extensions/amp-auto-ads/0.1/ad-tracker.js
  extensions/amp-auto-ads/0.1/anchor-ad-strategy.js
Labels: cla: yes

#22286 Validator Rollup
  validator/testdata/actions_feature_tests/amp_list.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#22195 amp-embed support for opinary
  3p/integration.js
  ads/_config.js
  ads/opinary.js
  ads/opinary.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#22289 Add validation rules for <amp-ad-custom>
  extensions/amp-ad-custom/0.1/test/validator-amp-ad-custom.html
  extensions/amp-ad-custom/0.1/test/validator-amp-ad-custom.out
  extensions/amp-ad-custom/validator-amp-ad-custom.protoascii
Labels: cla: yes

#22294 🏗🚮 Simplify the way `gulp lint` works on Travis
  .eslintrc
  build-system/tasks/lint.js
  validator/.eslintrc
Labels: Category: Tooling, cla: yes

#22307 🐛amp-recaptcha-input: Removed the experimental blurb in the recaptcha reference docs
  extensions/amp-recaptcha-input/amp-recaptcha-input.md
Labels: cla: yes

#22301 SwG release 0.1.22.51
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg-button.css
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#20245 🐛 Web push: service worker messenger command typo
  extensions/amp-web-push/0.1/amp-web-push.service-worker.js
Labels: cla: yes

#22298 amp-form: Reduce typecasts, clean up
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
Labels: cla: yes

#21138 🏗 Altered Safari Preconnect Polyfill Endpoint
  src/preconnect.js
  test/unit/test-preconnect.js
Labels: cla: yes

#22320 🏗 Don't run unit tests on local changes for large refactors
  build-system/pr-check/local-tests.js
Labels: Category: Tooling, cla: yes

#22319 🏗♻️🚮🐛 Refactor `gulp pr-check`
  build-system/pr-check.js
  build-system/pr-check/checks.js
  build-system/pr-check/utils.js
  build-system/tasks/dep-check.js
  build-system/tasks/pr-check.js
  build-system/tasks/presubmit-checks.js
  contributing/TESTING.md
Labels: Category: Tooling, cla: yes

#22321 Remove doc opt-in for 'ampdoc-shell' experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#20884 New amp-ad for aniview
  3p/integration.js
  ads/_config.js
  ads/aniview.js
  ads/aniview.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#22311 📖 Connatix Player extension: fix broken documentation page
  extensions/amp-connatix-player/amp-connatix-player.md
Labels: cla: yes

#22299 ✨amp-consent: Allowed passing the consent string through a macro
  examples/a4a-consent.amp.html
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
Labels: Category: Ads, cla: yes

#22323 🏗🐛 Mark `--local-changes` test status as skipped for large refactors
  build-system/pr-check/local-tests.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/index.js
Labels: Category: Tooling, cla: yes

#22293 amp-next-page: Fetch failure should be a user error
  extensions/amp-next-page/0.1/next-page-service.js
Labels: cla: yes

#22140 Handling video visibility updates.
  extensions/amp-story/1.0/amp-story-desktop-panels.css
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
  extensions/amp-story/1.0/utils.js
Labels: cla: yes

#22308 Rename consentState to consentStateValue
  extensions/amp-consent/integrating-consent.md
Labels: cla: yes

#22306 Remove amp-consent experimental flag
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  tools/experiments/experiments.js
Labels: cla: yes

#22309 Remove 'amp-consent' experiment flag pr2
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#22317 🏗Enable passing viewer caps as hashparam
  build-system/tasks/e2e/amp-driver.js
  examples/viewer.html
Labels: cla: yes

#22330 📖 Add email to amp-lightbox supported formats
  extensions/amp-lightbox/amp-lightbox.md
Labels: Category: Email, Related to: Documentation, cla: yes

#22114 Update feature deprecation/removal process
  spec/amp-versioning-policy.md
Labels: cla: yes

#22332 🏗Switch to .prettierrc to avoid breaking IDE extensions
  .eslintrc
  .prettierrc
Labels: cla: yes

#22338 📖 AMP analytics docs: Correct format support (-email, +stories)
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#21989 Documentation for story page attachments CTA label and title.
  extensions/amp-story/amp-story.md
Labels: cla: yes

#22334 🐛 Add max width to amp-twitter
  extensions/amp-story/1.0/amp-story.css
Labels: Category: AMP Story, cla: yes

#22138 Create custom attribute for text background color on stories
  examples/amp-story/text-background-color.html
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/utils.js
Labels: cla: yes

#22326 Force build additional components during prerendering if needed.
  css/amp.css
  src/service/resource.js
  src/service/resources-impl.js
  test/unit/test-resources.js
  tools/experiments/experiments.js
Labels: cla: yes

#22232 ♻️Lightbox refactoring.
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/swipe-to-dismiss.js
  extensions/amp-lightbox-gallery/0.1/utils.js
Labels: cla: yes

#22344 Use DOMReady (bodyComplete) signal where necessary
  extensions/amp-experiment/1.0/amp-experiment.js
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
  extensions/amp-link-rewriter/0.1/amp-link-rewriter.js
  extensions/amp-smartlinks/0.1/amp-smartlinks.js
  extensions/amp-story/1.0/amp-story-render-service.js
Labels: cla: yes

#22227 [AoG] Fix two race conditions in amp-bind/amp-list when backgrounded
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  src/common-signals.js
  src/custom-element.js
Labels: cla: yes

#22273 ✨ Introduce LiveStoryManager
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/live-story-manager.js
  extensions/amp-story/1.0/test/test-live-story-manager.js
Labels: Category: AMP Story, cla: yes

#22356 Remove unnecessary service stubs in linker-manager-test
  extensions/amp-analytics/0.1/test/test-linker-manager.js
Labels: cla: yes

#22335 Points to deprecation process from contribution doc & fixes typo
  contributing/contributing-code.md
  spec/amp-versioning-policy.md
Labels: cla: yes

#22116 🐛 Add safe zone in screen edges to prevent blocking navigation
  extensions/amp-story/1.0/page-advancement.js
Labels: cla: yes

#22347 Rename waitForBody to waitForBodyOpen
  extensions/amp-dynamic-css-classes/0.1/amp-dynamic-css-classes.js
  extensions/amp-experiment/0.1/amp-experiment.js
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-gwd-animation/0.1/test/test-amp-gwd-animation.js
  extensions/amp-skimlinks/0.1/amp-skimlinks.js
  extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
  src/dom.js
  src/element-service.js
  src/runtime.js
  src/service/ampdoc-impl.js
  src/service/resources-impl.js
  src/service/viewport/viewport-binding-ios-embed-sd.js
  src/service/viewport/viewport-binding-ios-embed-wrapper.js
  src/service/viewport/viewport-impl.js
  src/style-installer.js
  src/utils/story.js
  test/unit/test-ampdoc.js
  test/unit/test-document-submit.js
  test/unit/test-dom.js
  test/unit/test-runtime.js
Labels: cla: yes

#21994 🐛 Support RTL for base carousel
  build-system/tasks/e2e/functional-test-controller.js
  build-system/tasks/e2e/puppeteer-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  extensions/amp-base-carousel/0.1/amp-base-carousel.css
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-base-carousel/0.1/dimensions.js
  extensions/amp-base-carousel/0.1/test-e2e/test-rtl.js
  extensions/amp-base-carousel/amp-base-carousel.md
  test/manual/amp-base-carousel/autoadvance-rtl.amp.html
  test/manual/amp-base-carousel/basic-rtl.amp.html
  test/manual/amp-base-carousel/non-looping-rtl.amp.html
  test/manual/amp-base-carousel/three-slides-rtl.amp.html
Labels: cla: yes

#22359 Updates the components doc for current processes
  spec/amp-html-components.md
Labels: cla: yes

#22358 Removes references to core committers and help find reviewers
  contributing/getting-started-quick.md
Labels: cla: yes

#22364 🏗🐛 Fixes for `gulp pr-check`
  build-system/tasks/pr-check.js
Labels: Category: Tooling, cla: yes

#22343 Ensure that the waitForBody yields at the earliest possible time when body is opened
  src/dom.js
  test/unit/test-dom.js
  test/unit/test-element-service.js
Labels: cla: yes

#22363 Fixes typo in amp-access and amp-subscriptions docs
  extensions/amp-access/amp-access.md
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#22360 Launch the force prerender experiment for canary and 1% of prod traffic.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#22366 🏗 Appropriately handle async E2E test error
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
Labels: cla: yes

#22362 🏗♻️ Move test configuration out of `package json`
  build-system/pr-check/checks.js
  build-system/tasks/ava.js
  build-system/tasks/babel-plugin-tests.js
  build-system/tasks/pr-check.js
  gulpfile.js
  package.json
  yarn.lock
Labels: Category: Tooling, cla: yes

#22361 Enable linker for AMP.navigateTo
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  src/service/navigation.js
  test/manual/amp-linker-simple.amp.html
Labels: cla: yes

#22300 ♻️Move VariableService to doc level #2
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/cookie-writer.js
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/resource-timing.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-cookie-writer.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-analytics/0.1/test/test-requests.js
  extensions/amp-analytics/0.1/test/test-resource-timing.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
Labels: cla: yes

#22296 Add separate iframe transport URLs for Canary
  extensions/amp-analytics/0.1/iframe-transport-vendors.js
  extensions/amp-analytics/0.1/vendors.js
Labels: cla: yes

#22348 🏗 Update the build target logic used during PR checks
  build-system/pr-check/build-targets.js
  build-system/pr-check/build.js
  build-system/pr-check/checks.js
  build-system/pr-check/dist-bundle-size.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/local-tests.js
  build-system/pr-check/remote-tests.js
  build-system/pr-check/single-pass-tests.js
  build-system/pr-check/validator-tests.js
  build-system/pr-check/visual-diff-tests.js
  build-system/tasks/pr-check.js
  build-system/tasks/runtime-test/status-report.js
Labels: Category: Tooling, cla: yes

#22386 🐛 Don't overwrite browserify transform config
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test/index.js
Labels: cla: yes
