Repository ampproject/amphtml, pull requests merged in 2019-01, with the labels that each got.

#19424 removed authentication section
  spec/amp-email-format.md
Labels: cla: yes

#20048 Click through the system layer when hidden.
  extensions/amp-story/1.0/amp-story-system-layer.css
Labels: cla: yes

#19491 Save bookend state in window history
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#19936 ✨Adding PUB_UUID publisher defined macro to aps callout vendor URL
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#20058 🐛 Prevent context menu in stories
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#20069 🐛: Adding UpScore to Vendor.js
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/upscore.js
Labels: cla: yes

#20119 Update presubmit check to require copyright for 2019
  build-system/tasks/presubmit-checks.js
Labels: cla: yes

#19888 🚮Cleanup `amp-story-scaling` experiment
  tools/experiments/experiments.js
Labels: cla: yes

#19932 Update mparticle.js to allow custom page names
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/mparticle.js
Labels: cla: yes

#20051 Introduce cta-landing-page-type for story ads
  validator/testdata/amp4ads_feature_tests/amp_story_ad.html
  validator/testdata/amp4ads_feature_tests/amp_story_ad.out
  validator/testdata/amp4ads_feature_tests/amp_story_ad_errors.html
  validator/testdata/amp4ads_feature_tests/amp_story_ad_errors.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#20124 Minor fix to analytics vendor example page
  examples/analytics-vendors.amp.html
Labels: cla: yes

#19334 ✨Amp Form - Async Input / amp-recaptcha-input Support
  examples/recaptcha.amp.html
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-input.js
  src/async-input.js
Labels: cla: yes

#20067 ✨amp-brightcove: extend analytics support
  extensions/amp-analytics/amp-video-analytics.md
  extensions/amp-brightcove/0.1/amp-brightcove.js
Labels: cla: yes

#20129 Stop amp-sidebar from forwarding hotkeys to viewer
  extensions/amp-sidebar/0.1/amp-sidebar.js
Labels: cla: yes

#20117 Tidy up the test gulp task
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/index.js
Labels: cla: yes

#20110 Move amp-date-picker node modules from devDependencies to dependencies
  package.json
Labels: cla: yes

#20030 Fix changelog baseline
  build-system/tasks/changelog.js
Labels: Category: Tooling, cla: yes

#20131 ✨/ ♻️amp-recaptcha-input: Added Validation tests / Updated Validation Documentation
  contributing/component-validator-rules.md
  extensions/amp-recaptcha-input/0.1/test/validator-amp-recaptcha-input.html
  extensions/amp-recaptcha-input/0.1/test/validator-amp-recaptcha-input.out
  extensions/amp-recaptcha-input/validator-amp-recaptcha-input.protoascii
  validator/README.md
Labels: cla: yes

#19893 🏗✨ Add boilerplate for video `seekTo`, implement for `amp-video`
  extensions/amp-3q-player/0.1/amp-3q-player.js
  extensions/amp-brid-player/0.1/amp-brid-player.js
  extensions/amp-brightcove/0.1/amp-brightcove.js
  extensions/amp-dailymotion/0.1/amp-dailymotion.js
  extensions/amp-delight-player/0.1/amp-delight-player.js
  extensions/amp-gfycat/0.1/amp-gfycat.js
  extensions/amp-ima-video/0.1/amp-ima-video.js
  extensions/amp-mowplayer/0.1/amp-mowplayer.js
  extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js
  extensions/amp-ooyala-player/0.1/amp-ooyala-player.js
  extensions/amp-powr-player/0.1/amp-powr-player.js
  extensions/amp-video-iframe/0.1/amp-video-iframe.js
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-video/0.1/test/test-amp-video.js
  extensions/amp-vimeo/0.1/amp-vimeo.js
  extensions/amp-viqeo-player/0.1/amp-viqeo-player.js
  extensions/amp-wistia-player/0.1/amp-wistia-player.js
  extensions/amp-youtube/0.1/amp-youtube.js
  src/video-interface.js
Labels: cla: yes

#20101 Remove multi consent prompt support
  examples/amp-consent.amp.html
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-config.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-config.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
Labels: cla: yes

#20145 🐛amp-recaptcha-input: Fixed Copyright year on Validator HTML Test
  extensions/amp-recaptcha-input/0.1/test/validator-amp-recaptcha-input.html
  extensions/amp-recaptcha-input/0.1/test/validator-amp-recaptcha-input.out
Labels: cla: yes

#20151 🏗 Refactor git merge base functions
  build-system/git.js
  build-system/pr-check.js
  build-system/tasks/bundle-size.js
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#20149 📖 Fix link to image lightbox
  extensions/amp-lightbox/amp-lightbox.md
Labels: cla: yes

#20139 ✨ amp-animation: Added length() function.
  extensions/amp-animation/0.1/css-expr-ast.js
  extensions/amp-animation/0.1/css-expr-impl.jison
  extensions/amp-animation/0.1/css-expr-impl.js
  extensions/amp-animation/0.1/test/test-css-expr.js
  extensions/amp-animation/0.1/test/test-web-animations.js
  extensions/amp-animation/0.1/web-animations.js
  extensions/amp-animation/amp-animation.md
Labels: cla: yes

#20153 Report the SHA of the base (merged `master`) commit in bundle-size checks
  build-system/tasks/bundle-size.js
Labels: cla: yes

#20155 ♻️Reference the Event object from the gesture.event property
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
Labels: cla: yes

#20174 Documents iframe transport response
  extensions/amp-analytics/amp-analytics.md
Labels: Category: Analytics, cla: yes

#20084 ✨Add a go to page action
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
  tools/experiments/experiments.js
Labels: cla: yes

#18402 ✨ Add Navegg as A4A vendor
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#20144 amp-form mustache template rendering doc height update
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
Labels: cla: yes

#20188 Fix flaky ordering in test-performance
  test/functional/test-performance.js
Labels: cla: yes

#20191 Validator rollup
  validator/validator-main.protoascii
Labels: cla: yes

#19614 ♻️use writeScript instead of loadScript
  ads/adgeneration.js
Labels: cla: yes

#18956 ✨Apester Media (extension): Embed 3rd party pixel #18858
  extensions/amp-apester-media/0.1/amp-apester-media.js
  extensions/amp-apester-media/0.1/utils.js
Labels: cla: yes

#20172 Extern list for 3p ad context attributes
  build-system/amp.extern.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  src/iframe-attributes.js
Labels: cla: yes

#18281 🌐 suggested i18n update for nl.js
  extensions/amp-story/1.0/_locales/nl.js
Labels: cla: yes

#20098 ✨ amp-skimlinks: Remove non-affiliated links from links impressions analytics.
  extensions/amp-skimlinks/0.1/constants.js
  extensions/amp-skimlinks/0.1/test/test-tracking.js
  extensions/amp-skimlinks/0.1/tracking.js
Labels: cla: yes

#17999 🐛AMP STORY : Fixed localization for simplified Chinese
  extensions/amp-story/1.0/_locales/zh.js
Labels: cla: yes

#20158 Enable consent setting and pass setting to iframe
  examples/amp-consent.amp.html
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-config.js
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-config.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  test/manual/amp-consent-cmp.html
Labels: cla: yes

#20195 Rename test/functional dir to test/unit in ads/README.md
  ads/README.md
Labels: cla: yes

#20200 Preemptive null check in fixed-layer.js
  src/service/fixed-layer.js
Labels: cla: yes

#20116 Make advance-to public
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#20192 🏗 Fix baseline selection for bundle-size and visual-diff checks
  build-system/git.js
  build-system/tasks/bundle-size.js
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#20076 Add mox.tv ad network integration for amp-ad
  3p/integration.js
  ads/_config.js
  ads/mox.js
  ads/mox.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: Category: Ads, Type: Ads Vendor PR, cla: yes

#20130 ✨amp-ima-video: Show Controls on Hover
  ads/google/imaVideo.js
  build-system/dep-check-config.js
  extensions/amp-ima-video/0.1/test/test-amp-ima-video.js
Labels: cla: yes

#20031 Disallow passing ampdoc to all element service getters
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-experiment/0.1/test/test-variant.js
  extensions/amp-experiment/0.1/variant.js
  extensions/amp-ima-video/0.1/amp-ima-video.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-next-page/0.1/amp-next-page.js
  extensions/amp-story/0.1/animation.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/animation.js
  extensions/amp-user-notification/0.1/amp-user-notification.js
  src/consent.js
  src/element-service.js
  src/service/url-replacements-impl.js
  src/service/video-service-sync-impl.js
  src/services.js
  test/unit/test-url-replacements.js
Labels: cla: yes

#20182 Made changes to navigation to support branching
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#20201 🐛 Video docking bugfix pass
  extensions/amp-video-docking/0.1/amp-video-docking.js
  extensions/amp-video-docking/0.1/controls.js
  extensions/amp-video-docking/0.1/events.js
Labels: cla: yes

#20223 🏗 Add an `rc-channel` experiment ID to allow opt-in to the RC build of AMP
  contributing/release-schedule.md
  tools/experiments/experiments.js
Labels: Category: Tooling, cla: yes

#20216 More fixes for git baseline selection in pr-check
  build-system/git.js
  build-system/pr-check.js
Labels: cla: yes

#20055 Add test for, and logging of, unpatched amp-geo,
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-geo/0.1/test/test-amp-geo.js
Labels: cla: yes

#19540 Add validation for <amp-sidebar> within <amp-story>✨
  extensions/amp-sidebar/validator-amp-sidebar.protoascii
  extensions/amp-story/0.1/test/validator-amp-story-cta-layer-error.out
  extensions/amp-story/1.0/test/validator-amp-story-cta-layer-error.out
  extensions/amp-story/1.0/test/validator-amp-story-sidebar-error.html
  extensions/amp-story/1.0/test/validator-amp-story-sidebar-error.out
  extensions/amp-story/1.0/test/validator-amp-story-sidebar.html
  extensions/amp-story/1.0/test/validator-amp-story-sidebar.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#20229 Fix types for straggler callers of element service getters
  extensions/amp-access-laterpay/0.1/amp-access-laterpay.js
  extensions/amp-access-laterpay/0.2/amp-access-laterpay.js
  extensions/amp-access-poool/0.1/amp-access-poool.js
  extensions/amp-access-scroll/0.1/amp-access-scroll.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  src/custom-element.js
  test/unit/test-activity.js
Labels: cla: yes

#20239 amp-bind: Always set value for [text] in textarea
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-list/0.1/test/integration/test-amp-list.js
Labels: cla: yes

#20254 🏗 Fix error message when failing to report the bundle size of a pull request
  build-system/tasks/bundle-size.js
Labels: cla: yes

#20255 ✅ Mark two amp-story visual diff tests as flaky
  test/visual-diff/visual-tests
Labels: cla: yes

#20228 ✨Initial skeleton of amp-carousel v2.
  bundles.config.js
  extensions/amp-carousel/0.2/amp-carousel.css
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-carousel/0.2/auto-advance.js
  extensions/amp-carousel/0.2/carousel.js
  extensions/amp-carousel/0.2/dimensions.js
Labels: cla: yes

#20157 Fix overflow problem with failed resize on amp-list load-more
  build-system/app.js
  extensions/amp-list/0.1/amp-list.css
  extensions/amp-list/0.1/amp-list.js
  test/manual/amp-list/infinite-scroll-1.amp.html
  test/manual/amp-list/infinite-scroll-2.amp.html
Labels: cla: yes

#20256 🏗 Print short SHAs in pr-check for readability
  build-system/git.js
  build-system/pr-check.js
  build-system/tasks/bundle-size.js
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#20258 Mark one amp-story visual diff tests as flaky
  test/visual-diff/visual-tests
Labels: cla: yes

#20257 Subscriptions: add additional events for SwG
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/actions.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/analytics.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/service-adapter.js
  extensions/amp-subscriptions/0.1/test/test-actions.js
  extensions/amp-subscriptions/0.1/test/test-analytics.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#20210 AMP Story page attachment component.
  extensions/amp-story/1.0/amp-story-page-attachment.css
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
Labels: cla: yes

#20261 Moving the amp-story-bookend documentation to after the amp-story-page doc.
  extensions/amp-story/amp-story.md
Labels: cla: yes

#20250 ✨🏗 Use the `AMP_CANARY` cookie to determine canary / RC opt-in state
  src/experiments.js
  test/unit/test-experiments.js
  tools/experiments/experiments.js
Labels: Category: Runtime, Category: Tooling, cla: yes

#20015 Refactor amp-geo to use externs,
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-geo/OWNERS.yaml
  extensions/amp-user-notification/0.1/amp-user-notification.js
  extensions/amp-user-notification/0.1/test/test-amp-user-notification.js
  src/service/url-replacements-impl.js
Labels: cla: yes

#20263 Pause the story when the attachment is open.
  extensions/amp-story/1.0/amp-story-page-attachment.js
Labels: cla: yes

#20265 Don't apply the click shield to videos that are in amp-story-page-attachment.
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#20100 🐛amp-consent: Fixed URL Bar resizing for CMP Iframe modal
  extensions/amp-consent/0.1/amp-consent.css
  test/manual/amp-consent-cmp.html
  test/manual/diy-consent.html
Labels: cla: yes

#20248 Restore OriginExperiments
  src/service/origin-experiments-impl.js
  test/unit/test-origin-experiments.js
Labels: cla: yes

#20266 Prevent contextmenu on iOS.
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#20221 Fix amp-experiment instantiation for shadow mode
  build-system/tasks/compile.js
  extensions/amp-experiment/0.1/amp-experiment.js
  extensions/amp-experiment/0.1/test/test-amp-experiment.js
  extensions/amp-experiment/0.1/variant.js
  src/error.js
  src/service/url-replacements-impl.js
  src/services.js
  test/unit/test-url-replacements.js
Labels: cla: yes

#20264 Exclude the attachment media from the page media playback.
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
Labels: cla: yes

#20277 Creates I2I template
  .github/ISSUE_TEMPLATE/intent-to-implement--i2i-.md
Labels: cla: yes

#20251 ✅Integration test for configRewriter
  build-system/amp4test.js
  build-system/app.js
  build-system/routes/analytics.js
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/_fake_.js
  test/integration/test-amp-analytics.js
Labels: cla: yes

#20242 ✨ Pass previous stored consent info to CMP iframe
  extensions/amp-consent/0.1/consent-info.js
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  test/manual/amp-consent-cmp.html
  test/manual/diy-consent.html
Labels: cla: yes

#20276 Increase the height of the fullbleed desktop progress bar.
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
Labels: cla: yes

#20282 🏗 Only print TRAVIS_PULL_REQUEST_SHA in `pr-check` on Travis
  build-system/pr-check.js
Labels: cla: yes

#20283 add intent-to-ship template
  .github/ISSUE_TEMPLATE/intent-to-ship--i2s-.md
Labels: cla: yes

#20274 Validator roll-up
  extensions/amp-accordion/validator-amp-accordion.protoascii
  extensions/amp-analytics/validator-amp-analytics.protoascii
  extensions/amp-anim/validator-amp-anim.protoascii
  extensions/amp-animation/validator-amp-animation.protoascii
  extensions/amp-bind/validator-amp-bind.protoascii
  extensions/amp-carousel/validator-amp-carousel.protoascii
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out
  extensions/amp-experiment/validator-amp-experiment.protoascii
  extensions/amp-fit-text/validator-amp-fit-text.protoascii
  extensions/amp-font/validator-amp-font.protoascii
  extensions/amp-form/validator-amp-form.protoascii
  extensions/amp-fx-collection/validator-amp-fx-collection.protoascii
  extensions/amp-image-lightbox/validator-amp-image-lightbox.protoascii
  extensions/amp-image-slider/validator-amp-image-slider.protoascii
  extensions/amp-lightbox/validator-amp-lightbox.protoascii
  extensions/amp-list/validator-amp-list.protoascii
  extensions/amp-live-list/validator-amp-live-list.protoascii
  extensions/amp-mustache/validator-amp-mustache.protoascii
  extensions/amp-orientation-observer/validator-amp-orientation-observer.protoascii
  extensions/amp-pan-zoom/validator-amp-pan-zoom.protoascii
  extensions/amp-payment-google-button/0.1/test/validator-actions-amp-payment-google-button.html
  extensions/amp-payment-google-button/0.1/test/validator-actions-amp-payment-google-button.out
  extensions/amp-payment-google-button/validator-amp-payment-google-button.protoascii
  extensions/amp-payment-google-inline/0.1/test/validator-actions-amp-payment-google-inline.html
  extensions/amp-payment-google-inline/0.1/test/validator-actions-amp-payment-google-inline.out
  extensions/amp-payment-google-inline/validator-amp-payment-google-inline.protoascii
  extensions/amp-position-observer/validator-amp-position-observer.protoascii
  extensions/amp-selector/validator-amp-selector.protoascii
  extensions/amp-sidebar/validator-amp-sidebar.protoascii
  extensions/amp-timeago/validator-amp-timeago.protoascii
  extensions/amp-video/validator-amp-video.protoascii
  extensions/amp-viewer-assistance/0.1/test/validator-actions-amp-viewer-assistance.html
  extensions/amp-viewer-assistance/0.1/test/validator-actions-amp-viewer-assistance.out
  extensions/amp-viewer-assistance/validator-amp-viewer-assistance.protoascii
  extensions/amp-yotpo/validator-amp-yotpo.protoascii
  extensions/amp-youtube/validator-amp-youtube.protoascii
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/nodejs/index.js
  validator/testdata/actions_feature_tests/minimum_valid.html
  validator/testdata/actions_feature_tests/minimum_valid.out
  validator/testdata/actions_feature_tests/type_identifier_missing.html
  validator/testdata/actions_feature_tests/type_identifier_missing.out
  validator/testdata/amp4ads_feature_tests/amp_actions.html
  validator/testdata/amp4ads_feature_tests/amp_actions.out
  validator/testdata/amp4email_feature_tests/amp_actions.html
  validator/testdata/amp4email_feature_tests/amp_actions.out
  validator/testdata/feature_tests/amp_actions.html
  validator/testdata/feature_tests/amp_actions.out
  validator/testdata/feature_tests/empty.out
  validator/testdata/feature_tests/multiple_body_tags_3.out
  validator/testdata/feature_tests/new_and_old_boilerplate_mixed.out
  validator/testdata/feature_tests/new_and_old_boilerplate_mixed2.out
  validator/testdata/feature_tests/regexps.out
  validator/testdata/feature_tests/unprintable_chars.out
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: cla: yes

#20268 Add NaN check to amp-pan-zoom maxScale
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
Labels: cla: yes

#20230 Fix amp-list-load-more doesn't shrink issue.
  extensions/amp-list/0.1/amp-list.js
  test/manual/amp-list/infinite-scroll-1.amp.html
Labels: cla: yes

#20249 Property check for getDefaultActionAlias on node
  src/service/action-impl.js
Labels: cla: yes

#19852 Clarify contribution docs and add I2I/I2S process requiring approval from Approvers WG
  CONTRIBUTING.md
  contributing/contributing-code.md
Labels: cla: yes

#20290 Add Actions to Validator WebUI
  validator/webui/@polymer/webui-mainpage/webui-mainpage.html
  validator/webui/@polymer/webui-urlform/webui-urlform.html
Labels: cla: yes

#20287 ✨amp-recaptcha-input: Added Reference Documentation.
  extensions/amp-recaptcha-input/amp-recaptcha-input.md
Labels: Related to: Documentation, cla: yes

#20035 🐛 Update contentHeight algorithms
  src/service/viewport/viewport-binding-ios-embed-sd.js
  src/service/viewport/viewport-binding-ios-embed-wrapper.js
  src/service/viewport/viewport-binding-natural.js
Labels: cla: yes

#20294 Moving the page attachment header into shadow DOM.
  bundles.config.js
  extensions/amp-story/1.0/amp-story-page-attachment-header.css
  extensions/amp-story/1.0/amp-story-page-attachment.css
  extensions/amp-story/1.0/amp-story-page-attachment.js
Labels: cla: yes

#19948 [amp-story] Extend interactivity support for iframe-based elements ✨
  examples/visual-tests/amp-story/amp-story-tooltip-desktop.js
  examples/visual-tests/amp-story/amp-story-tooltip.js
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-hint.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-tooltip.css
  extensions/amp-story/1.0/amp-story-tooltip.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/test/test-amp-story-tooltip.js
  extensions/amp-story/1.0/test/validator-amp-story-embedded-component-error.html
  extensions/amp-story/1.0/test/validator-amp-story-embedded-component-error.out
  extensions/amp-story/1.0/test/validator-amp-story-embedded-component.html
  extensions/amp-story/1.0/test/validator-amp-story-embedded-component.out
  test/visual-diff/visual-tests
Labels: cla: yes

#20154 Add integration test for various AMP Inabox flows.
  build-system/app.js
  test/fixtures/amp-cupcake-ad.html
  test/fixtures/served/cupcake.jpg
  test/integration/test-amp-inabox.js
Labels: cla: yes

#20094 amp-list load-more validation
  extensions/amp-list/0.1/test/validator-amp-list.html
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/validator-amp-list.protoascii
Labels: cla: yes

#20273 🖍 Add sidebar transitions/ styling
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#20292 Reopen page attachment from browser history.
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/utils.js
Labels: cla: yes

#20310 Launch amp-list-viewport-resize to 10%
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#20311 🏗 Elevate the various states of the `AMP_CANARY` cookie to constants
  tools/experiments/experiments.js
Labels: Category: Tooling, cla: yes

#20317 Fix [amp-lightbox-gallery] panning results in carousel swipe
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
Labels: cla: yes

#20316 First dummy e2e test with ChromeDriver
  package.json
  test/e2e/test-github.js
  testing/e2e/describes-e2e.js
  testing/e2e/expect.js
  testing/e2e/functional-test-controller.js
  testing/e2e/selenium-webdriver-controller.js
  yarn.lock
Labels: cla: yes

#20322 Add validation for [is-layout-container]
  extensions/amp-list/0.1/test/validator-amp-list.html
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/validator-amp-list.protoascii
Labels: cla: yes

#20318 Disable the inabox tests on Safari.
  test/integration/test-amp-inabox.js
Labels: cla: yes

#20325 Removes references to pre-governance change working groups
  contributing/working-groups.md
Labels: cla: yes

#20321 Removed misleading statement on amp-animation conditions 📖
  extensions/amp-animation/amp-animation.md
Labels: cla: yes

#20327 🖍 Animate and style placeholder icon for right-to-left transition
  extensions/amp-video-docking/0.1/amp-video-docking.css
  extensions/amp-video-docking/0.1/amp-video-docking.js
  extensions/amp-video-docking/0.1/math.js
Labels: cla: yes

#20059 ✨amp-consent: UI Mask Overlay
  extensions/amp-consent/0.1/amp-consent.css
  extensions/amp-consent/0.1/consent-config.js
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-config.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  test/manual/amp-consent-cmp-overlay.html
  test/manual/amp-consent.html
Labels: cla: yes

#20331 📖 Add copyright header
  extensions/amp-video-iframe/amp-video-iframe.md
Labels: cla: yes

#20190 ✨Introduce `varGroups` for configRewriter.
  build-system/routes/analytics.js
  build-system/tasks/presubmit-checks.js
  examples/analytics-varGroups.amp.html
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/test/test-config.js
  extensions/amp-analytics/0.1/vendors/_fake_.js
  test/integration/test-amp-analytics.js
Labels: cla: yes

#20038 Fix cloudflare cacheDomain in caches.json
  caches.json
Labels: cla: yes

#20329 🐛 Reapply docking target on resize if changed
  extensions/amp-video-docking/0.1/amp-video-docking.js
  extensions/amp-video-docking/0.1/controls.js
Labels: cla: yes

#20323 🐛Quick-fix safari paste behavior with inputmask
  third_party/inputmask/inputmask.js
  third_party/inputmask/patches/0007-safari-paste-fix.patch
Labels: cla: yes

#20328 🐛Fix copy-pastes into fields with masks that have literal prefixes
  extensions/amp-inputmask/0.1/inputmask-custom-alias.js
  extensions/amp-inputmask/0.1/mask-impl.js
Labels: cla: yes

#20335 🚮 Remove flick-to-dismiss from amp-video-docking
  extensions/amp-video-docking/0.1/amp-video-docking.js
Labels: cla: yes

#20284 ✨Consent: Allow using metaTag to block AMP components by tagName
  examples/amp-consent.amp.html
  src/consent.js
  src/custom-element.js
  test/manual/amp-consent-cmp.html
  test/unit/test-consent.js
  test/unit/test-custom-element.js
Labels: cla: yes

#20334 🐛 Update placeholder icon direction while dragging
  extensions/amp-video-docking/0.1/amp-video-docking.css
  extensions/amp-video-docking/0.1/amp-video-docking.js
Labels: cla: yes

#20336 🐛amp-carousel: move mutate from onLayoutMeasure to layoutCallback.
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/0.1/test/test-slidescroll.js
Labels: cla: yes

#20351 Add xpath support to e2e test controllers
  testing/e2e/functional-test-controller.js
  testing/e2e/selenium-webdriver-controller.js
Labels: cla: yes

#20354 [amp-story] Fix progress bar issue🐛
  extensions/amp-story/1.0/amp-story-system-layer.css
Labels: cla: yes

#20333 Fix load-more button extra height issue
  extensions/amp-list/0.1/amp-list.js
Labels: cla: yes

#19446 ✨ [amp-analytics] AT Internet - add default vars + new var pixelPath
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/atinternet.js
Labels: cla: yes

#20350 Update amp-carousel.md to be reflective of layouts supported
  extensions/amp-carousel/amp-carousel.md
Labels: cla: yes

#20006 Adpon amp-ad support.
  3p/integration.js
  ads/_config.js
  ads/adpon.js
  ads/adpon.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#20353 Don't force collapse on fluid slots if resize fails, as they are initiated in a collapsed state
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
Labels: cla: yes

#20355 Rename embedded component tests ♻️
  extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
Labels: cla: yes

#19451 Update docs for script tag templating support
  extensions/amp-form/amp-form.md
  extensions/amp-list/amp-list.md
  extensions/amp-mustache/amp-mustache.md
  spec/amp-html-format.md
  spec/amp-html-templates.md
Labels: cla: yes

#20372 update broken bookmarks in contribution doc
  CONTRIBUTING.md
Labels: cla: yes

#20347 ✨Add support for credit card field named mask
  examples/masking.amp.html
  extensions/amp-inputmask/0.1/constants.js
  extensions/amp-inputmask/0.1/inputmask-payment-card-alias.js
  extensions/amp-inputmask/0.1/mask-impl.js
  extensions/amp-inputmask/0.1/test/validator-amp-inputmask.html
  extensions/amp-inputmask/0.1/test/validator-amp-inputmask.out
  extensions/amp-inputmask/README.md
  extensions/amp-inputmask/validator-amp-inputmask.protoascii
  third_party/inputmask/inputmask.js
  third_party/inputmask/patches/0009-support-cardinality.patch
Labels: cla: yes

#20360 Validator rollup
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/testdata/transformed_feature_tests/minimum_valid_amp.html
  validator/testdata/transformed_feature_tests/minimum_valid_amp.out
  validator/testdata/transformed_feature_tests/transformed_attribute_value_malformed.html
  validator/testdata/transformed_feature_tests/transformed_attribute_value_malformed.out
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: cla: yes

#20370 Create gulp e2e task
  .eslintrc
  build-system/tasks/e2e/index.js
  build-system/tasks/index.js
  package.json
  test/e2e/test-github.js
  testing/e2e/test-module.js
  yarn.lock
Labels: cla: yes

#20356 Close the story page attachment on browser back.
  extensions/amp-story/1.0/amp-story-page-attachment.js
Labels: cla: yes

#20376 update amp-bodymovin-animation extension options
  bundles.config.js
Labels: cla: yes

#20382 🐛 amp-bind: close amp-bind-macro tag in example
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#19835 📖 Add docs for XML-compatible AMP bind attribute syntax
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#20339 [amp-story] Add support for different kinds of action icons inside the tooltip
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-tooltip.css
  extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
Labels: cla: yes

#20293 Carousel v2: add logic for spacers for looping.
  extensions/amp-carousel/0.2/array-util.js
  extensions/amp-carousel/0.2/carousel.js
  extensions/amp-carousel/0.2/dimensions.js
Labels: cla: yes

#20384 🏗 Update Sauce Connect Proxy to version 4.5.3
  build-system/sauce_connect/start_sauce_connect.sh
Labels: cla: yes

#20364 Erase consentStr on undefined value
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  test/manual/diy-consent.html
Labels: cla: yes

#20383 ✨ Support input masking four date formats
  build-system/dep-check-config.js
  examples/masking.amp.html
  extensions/amp-inputmask/0.1/constants.js
  extensions/amp-inputmask/0.1/mask-impl.js
  extensions/amp-inputmask/0.1/test/validator-amp-inputmask.html
  extensions/amp-inputmask/0.1/test/validator-amp-inputmask.out
  extensions/amp-inputmask/validator-amp-inputmask.protoascii
  third_party/inputmask/inputmask.date.extensions.js
  third_party/inputmask/inputmask.js
  third_party/inputmask/patches/0010-date-extension-umd.patch
  third_party/inputmask/patches/0011-add-date-separators.patch
Labels: cla: yes

#20402 Tweak closing tooltip animation
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-tooltip.css
Labels: Category: AMP Story, cla: yes

#20379 Hide pagination buttons when toggling the hide system UI state.
  extensions/amp-story/1.0/pagination-buttons.css
  extensions/amp-story/1.0/pagination-buttons.js
Labels: cla: yes

#20403 Update rtc-documentation.md
  extensions/amp-a4a/rtc-documentation.md
Labels: cla: yes

#20386 Update gulp e2e
  .eslintrc
  build-system/config.js
  build-system/tasks/e2e/index.js
Labels: cla: yes

#20380 Tiny fix to display the share menu on top of the pagination buttons.
  extensions/amp-story/1.0/amp-story-share-menu.css
Labels: cla: yes

#20388 Story page attachment visual tests.
  examples/visual-tests/amp-story/amp-story-page-attachment-desktop.js
  examples/visual-tests/amp-story/amp-story-page-attachment.html
  examples/visual-tests/amp-story/amp-story-page-attachment.js
  test/visual-diff/visual-tests
Labels: cla: yes

#20407 amp-mustache: Don't log user error for binding attributes
  src/purifier.js
Labels: cla: yes

#20288 Implement Safari workaround for option[selected] and <select>
  extensions/amp-bind/0.1/bind-impl.js
Labels: cla: yes

#20409 🐛Fix pasted and initial values and escape characters
  examples/masking.amp.html
  extensions/amp-inputmask/0.1/inputmask-custom-alias.js
  extensions/amp-inputmask/0.1/mask-impl.js
Labels: cla: yes

#20363 Add a simple initial functional test for carousel-v2.
  extensions/amp-carousel/0.2/test-e2e/test-carousel.js
  test/manual/amp-carousel-0-2/basic.amp.html
  test/manual/amp-carousel-0-2/disable-layers.html
  test/manual/amp-carousel-0-2/enable-experiment.html
  testing/e2e/selenium-webdriver-controller.js
Labels: cla: yes

#20414 📖 Remove experimental status from `amp-video-iframe` docs
  extensions/amp-video-iframe/amp-video-iframe.md
Labels: cla: yes

#20418 📖Create examples for country phone number formats
  examples/masking.amp.html
Labels: cla: yes

#20406 ♻️ Scoped query selector fallback method
  src/dom.js
Labels: cla: yes

#20417 ♻️amp-inputmask validator refactor to avoid complicated regex
  extensions/amp-inputmask/0.1/test/validator-amp-inputmask.html
  extensions/amp-inputmask/0.1/test/validator-amp-inputmask.out
  extensions/amp-inputmask/validator-amp-inputmask.protoascii
  validator/testdata/feature_tests/forms.out
Labels: cla: yes

#20342 🐛 amp-ad: fixed URL handling on uzou.js
  ads/uzou.js
Labels: cla: yes

#20411 🐛Move GEO_IN_GROUP types to pure file
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-geo/0.1/amp-geo-in-group.js
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-geo/0.1/test/test-amp-geo.js
  extensions/amp-user-notification/0.1/amp-user-notification.js
  extensions/amp-user-notification/0.1/test/test-amp-user-notification.js
Labels: cla: yes
