Repository ampproject/amphtml, pull requests merged in 2019-10, with the labels that each got.

#24741 ✨Callout vendor update: added consent_string macros to aps prebid url
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#24833 amp-bind: Increase equality check depth to 20
  extensions/amp-bind/0.1/bind-impl.js
Labels: cla: yes

#24810 Launch <amp-action-macro>
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-action-macro/amp-action-macro.md
Labels: cla: yes

#24683 🐛 amp-ad type blade - fix bladeOnLoad callback
  ads/blade.js
Labels: cla: yes

#24690 Remove code for inabox chunking experiments
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  examples/amphtml-ads/many-ads.host.html
  src/inabox/amp-inabox.js
  tools/experiments/experiments.js
Labels: cla: yes

#24839 Enable amp-list[diffable] in other AMP specs
  extensions/amp-list/validator-amp-list.protoascii
Labels: cla: yes

#24830 gulp integration build command consistency
  build-system/tasks/integration.js
Labels: cla: yes

#24375 ✨ Implement ad size optimization for AdSense.
  build-system/tasks/presubmit-checks.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
  spec/amp-localstorage.md
Labels: cla: yes

#24835 Cleanup stale owners file entries
  extensions/amp-consent/OWNERS.yaml
  extensions/amp-instagram/OWNERS.yaml
  extensions/amp-subscriptions-google/OWNERS.yaml
  extensions/amp-subscriptions/OWNERS.yaml
Labels: cla: yes

#24730 Fix reloadExtension for amp-viewer-integration
  src/element-service.js
  src/runtime.js
  src/service/extensions-impl.js
  test/unit/test-custom-element-registry.js
  test/unit/test-extensions.js
  test/unit/test-runtime.js
Labels: cla: yes

#24825 ♿Add alert role to toast for screen reader support
  extensions/amp-story/1.0/toast.js
Labels: cla: yes

#24831 Story Ads: propagate visible attr to transformed body.
  examples/amp-story/ads/app-install.html
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads.js
  test/fixtures/e2e/amp-story-auto-ads/dv3-request.html
  test/fixtures/e2e/amp-story-auto-ads/dv3-transformed-creative.html
Labels: cla: yes

#24845 babel-preset-modules should be a devDependency
  package.json
Labels: Type: Bug, WG: infra, WG: performance, cla: yes

#24819 Ramp up inconsistent responsive height selection fix experiment to 5%.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#24427 ✨ noContent on destroy Nativeroll player
  ads/nativeroll.js
Labels: cla: yes

#23942 ✨ Lentainform. this change is very important
  ads/lentainform.js
Labels: cla: yes

#24546 🐛Fix subdomain handling in lentainform widgets
  ads/lentainform.js
Labels: cla: yes

#24738 🐛Update Ooyala player version from Sandbox to Prod
  extensions/amp-ooyala-player/0.1/amp-ooyala-player.js
  extensions/amp-ooyala-player/0.1/test/test-amp-ooyala.js
  extensions/amp-ooyala-player/0.1/test/validator-amp-ooyala.html
  extensions/amp-ooyala-player/0.1/test/validator-amp-ooyala.out
Labels: cla: yes

#24624 Document setState/getState in amp-script
  extensions/amp-script/amp-script.md
Labels: cla: yes

#24840 ♿Add alert role to sound announcements for screen reader support
  extensions/amp-story/1.0/amp-story-system-layer.js
Labels: cla: yes

#24823 🐛Adds true parallax to the `amp-orientation-observer` example
  examples/amp-orientation-observer-3d-parallax.amp.html
Labels: cla: yes

#24857 Validator rollup 401@960
  extensions/amp-script/0.1/test/validator-amp-script.out
  validator/engine/validator_test.js
  validator/validator-main.protoascii
  validator/validator.pb.go
Labels: cla: yes

#24859 📖Fix broken link to LocalizedStringId in _locales/ README
  extensions/amp-story/1.0/_locales/README.md
Labels: cla: yes

#24795 Add SeedingAlliance support to amp-ad
  3p/integration.js
  ads/_config.js
  ads/seedingalliance.js
  ads/seedingalliance.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#24820 Ramp up experiment for using responsive amp-ad in amp-auto-ads to 5%.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#24846 🐛 Update WorkerDOM to 0.21.0
  package.json
  yarn.lock
Labels: cla: yes

#24777 ✨ 📖 Vendor config warning message
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/test/test-config.js
  extensions/amp-analytics/amp-analytics.md
  extensions/amp-analytics/integrating-analytics.md
Labels: cla: yes

#23958 🐛 Add trailing slash to event endpoint to return gif in response to GET request
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/tealiumcollect.js
Labels: cla: yes

#24865 Correct wg-analytics reference in owners file
  extensions/amp-analytics/OWNERS.yaml
Labels: cla: yes

#24853 Make wg-approvers owner of experiments
  build-system/OWNERS.yaml
  build-system/global-configs/OWNERS.yaml
Labels: cla: yes

#24662 🏗 Reduce `gulp dist` parallelism on Travis, add some logging
  build-system/compile/compile.js
  build-system/compile/single-pass.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
Labels: WG: infra, cla: yes

#24863 ⚡️Add all WGs as owners for common folders
  examples/OWNERS.yaml
  test/OWNERS.yaml
Labels: cla: yes

#24418 🏗 Stop reporting gzipped compressed size in the bundle-size task
  build-system/tasks/bundle-size.js
Labels: cla: yes

#24413 Ramp up experiment for AdSense ad size optimization to 1% of AMP traffic
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#24870 Fix wildcard owners in `test` and `examples`
  examples/OWNERS.yaml
  test/OWNERS.yaml
Labels: cla: yes

#24882 Revert "🏗 Stop reporting gzipped compressed size in the bundle-size task"
  build-system/tasks/bundle-size.js
Labels: cla: yes

#24884 🏗 Regenerate `yarn.lock`
  yarn.lock
Labels: WG: infra, cla: yes

#24864 Disallow amp-youtube in amp4ads
  extensions/amp-youtube/validator-amp-youtube.protoascii
  validator/engine/validator_test.js
  validator/testdata/amp4ads_feature_tests/extensions.html
  validator/testdata/amp4ads_feature_tests/extensions.out
Labels: cla: yes

#24888 Revert "Revert "Stop reporting gzipped compressed size in the bundle-size task (#24418)" (#24882)"
  build-system/tasks/bundle-size.js
Labels: cla: yes

#24887 ♿Expand tap target size for page attachment close button
  extensions/amp-story/1.0/amp-story-draggable-drawer-header.css
Labels: cla: yes

#24891 🏗🐛 Resolve paths in `window-property-name` custom `eslint` rule
  build-system/eslint-rules/window-property-name.js
Labels: WG: infra, cla: yes

#24892 📖 Remove confusing emoji codes from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Related to: Documentation, cla: yes

#24886 🐛Fixes accidental ownership swap
  extensions/amp-fx-flying-carpet/OWNERS.yaml
  extensions/amp-viqeo-player/OWNERS.yaml
Labels: cla: yes

#24842 ♿Add aria-labels to story system-layer buttons
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/simple-template.js
  src/localized-strings.js
Labels: cla: yes

#24812 ♻️Minor refactor for `amp-orientation-observer`
  extensions/amp-orientation-observer/0.1/amp-orientation-observer.js
Labels: cla: yes

#24813 📖clone documentation for sidebar v2
  extensions/amp-sidebar/0.1/amp-sidebar.md
  extensions/amp-sidebar/1.0/amp-sidebar.md
Labels: cla: yes

#24896 🏗♻️ Reorganize files in the `amphtml` root directory
  .eslintrc
  .renovaterc.json
  OWNERS.yaml
  Procfile
  build-system/common/LICENSE-TEMPLATE.txt
  build-system/compile/bundles.config.js
  build-system/compile/single-pass.js
  build-system/global-configs/caches.json
  build-system/pr-check/build-targets.js
  build-system/server/lazy-build.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
  build-system/tasks/json-check.js
  contributing/building-an-amp-extension.md
  default.profraw
  extensions/amp-geo/amp-geo.md
  spec/amp-cache-guidelines.md
  spec/amp-cache-transform.md
  system.properties
Labels: WG: infra, cla: yes

#24626 url: Recognize + as %20 when parsing query string
  src/url-parse-query-string.js
Labels: cla: yes

#24877 AdGlare Ad Server: Added a cache buster to the URL.
  ads/adglare.js
  ads/adglare.md
Labels: cla: yes

#24913 Restore visibility methods as restricted in the viewer for viewer-integration fixes
  src/service/viewer-impl.js
Labels: cla: yes

#24860 Remove resize logs and enable activation for resize decisions
  extensions/amp-ad/0.1/amp-ad-ui.js
  src/service/resources-impl.js
  test/unit/test-resources.js
Labels: cla: yes

#24854 AMP4Email: Disallow "latest" extension scripts
  extensions/amp-accordion/validator-amp-accordion.protoascii
  extensions/amp-anim/validator-amp-anim.protoascii
  extensions/amp-bind/validator-amp-bind.protoascii
  extensions/amp-carousel/validator-amp-carousel.protoascii
  extensions/amp-fit-text/validator-amp-fit-text.protoascii
  extensions/amp-form/validator-amp-form.protoascii
  extensions/amp-list/validator-amp-list.protoascii
  extensions/amp-mustache/validator-amp-mustache.protoascii
  extensions/amp-selector/validator-amp-selector.protoascii
  extensions/amp-sidebar/validator-amp-sidebar.protoascii
  extensions/amp-timeago/validator-amp-timeago.protoascii
  validator/engine/validator_test.js
  validator/testdata/amp4email_feature_tests/no_latest_extensions.html
  validator/testdata/amp4email_feature_tests/no_latest_extensions.out
Labels: cla: yes

#24943 🏗 Lint `OWNERS` files with `gulp lint`
  build-system/tasks/lint.js
Labels: WG: infra, cla: yes

#24946 🏗 Use `config.lintGlobs` instead of a hard-coded list of globs
  build-system/tasks/lint.js
Labels: WG: infra, cla: yes

#24937 🏗 Change Attribute Name in SwG Encrypted Scripts
  extensions/amp-subscriptions/0.1/crypto-handler.js
  extensions/amp-subscriptions/0.1/test/test-crypto-handler.js
Labels: cla: yes

#24945 🏗 Add `OWNERS` files for all `build-system/` sub-directories
  build-system/babel-plugins/OWNERS
  build-system/common/OWNERS
  build-system/compile/OWNERS
  build-system/eslint-rules/OWNERS
  build-system/externs/OWNERS
  build-system/pr-check/OWNERS
  build-system/runner/OWNERS
  build-system/sauce_connect/OWNERS
  build-system/server/OWNERS
  build-system/server/app-index/OWNERS
  build-system/tasks/OWNERS
  build-system/tasks/e2e/OWNERS
  build-system/tasks/runtime-test/OWNERS
  build-system/tasks/visual-diff/OWNERS
  build-system/test-configs/OWNERS
Labels: WG: infra, cla: yes

#24951 Extend experiments A and B by 1 month
  build-system/global-configs/experiments-config.json
Labels: cla: yes

#24955 🏗 Switch bundle-size store function to the JSON API endpoint
  build-system/tasks/bundle-size.js
Labels: cla: yes

#23124 :sparkles: Add tracdelight AMP ad integration
  3p/integration.js
  ads/_config.js
  ads/tracdelight.js
  ads/tracdelight.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#24958 🏗 Remove unnecessary .json from bundle-size /store URL
  build-system/tasks/bundle-size.js
Labels: cla: yes

#24959 ⏪Remove Error Reporting From karmaBrowserComplete_ When Zero Tests Found
  build-system/tasks/runtime-test/helpers.js
Labels: cla: yes

#24948 🏗 Remove `--eager_build` flag from `gulp`
  build-system/tasks/build.js
  build-system/tasks/serve.js
Labels: WG: infra, cla: yes

#24962 📖 Formats amp-story attributes section as a table.
  extensions/amp-story/amp-story.md
Labels: cla: yes

#24939 🐛loader: Disable caching of LoaderService Promise
  src/loader.js
Labels: cla: yes

#24709 📖 Remove duplicate sections from amp-story.md
  extensions/amp-story/amp-story.md
Labels: cla: yes

#24976 Revert "📦 Update dependency selenium-webdriver to v4.0.0-alpha.5"
  build-system/tasks/e2e/package.json
  build-system/tasks/e2e/yarn.lock
Labels: cla: yes

#24732 Remove extra css for amp-ad-exit e2e test
  test/fixtures/e2e/amphtml-ads/amp-ad-exit.amp.html
Labels: cla: yes

#24941 ✨ SWG release 0.1.22.74
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#24986 Validator rollup
  validator/engine/validator.js
  validator/testdata/amp4ads_feature_tests/extensions.html
  validator/testdata/amp4ads_feature_tests/extensions.out
  validator/validator-main.protoascii
Labels: cla: yes

#24966 📖 Make PR template text invisible even when it is inadvertently included in a PR description
  .github/OWNERS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Related to: Documentation, cla: yes

#24971 🏗 A few minor `OWNERS` fixes
  .eslintignore
  .prettierrc
  OWNERS
  css/OWNERS
  examples/OWNERS
  extensions/OWNERS
  tools/OWNERS
  validator/OWNERS
Labels: WG: infra, cla: yes

#23928 [DRAFT] <amp-embed type="insticator">
  3p/integration.js
  ads/_config.js
  ads/insticator.js
  ads/insticator.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#24979 Story branching navigation path fixes.
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#24981 Remove story multiple advancement config.
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
Labels: cla: yes

#24980 Remove the branching share page checkbox.
  extensions/amp-story/1.0/amp-story-share.css
  extensions/amp-story/1.0/amp-story-share.js
Labels: cla: yes

#24993 🏗 Don't use `eslint` to check `OWNERS` files
  .eslintignore
  .eslintrc
  .prettierrc
  build-system/tasks/lint.js
  build-system/test-configs/config.js
Labels: WG: infra, cla: yes

#24988 Add reviewers team to root OWNERS file
  OWNERS
Labels: cla: yes

#24963 ✨amp-bind: Allow String.replace()
  extensions/amp-bind/0.1/bind-expression.js
  extensions/amp-bind/0.1/test/test-bind-expression.js
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#24977 Better inabox console message when message.source is null
  ads/inabox/inabox-host.js
Labels: cla: yes

#24909 🐛Fix script tag validation issues with amp-experiment usage on amp-story
  extensions/amp-story/1.0/test/validator-amp-story-amp-experiment-error.html
  extensions/amp-story/1.0/test/validator-amp-story-amp-experiment-error.out
  extensions/amp-story/1.0/test/validator-amp-story-amp-experiment.html
  extensions/amp-story/1.0/test/validator-amp-story-amp-experiment.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#25003 Media Pool: generate HTMLSourceElement from the src attribute.
  extensions/amp-story/1.0/media-pool.js
  extensions/amp-story/1.0/media-tasks.js
  extensions/amp-story/1.0/sources.js
  extensions/amp-story/1.0/test/test-media-tasks.js
Labels: cla: yes

#25010 🐛Hide type="carousel" arrows after swiping to a new slide.
  extensions/amp-carousel/0.2/amp-carousel.js
Labels: cla: yes

#25018 Fix bad script in amp story auto ads docs
  extensions/amp-story-auto-ads/amp-story-auto-ads.md
Labels: cla: yes

#24048 Fix typo
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#24985 🏗 Add `danielrozenberg` as OWNER of sauce_connect
  build-system/sauce_connect/OWNERS
Labels: cla: yes

#24836 🏗 Lando: Install dependencies needed for building validator
  .lando.yml
Labels: cla: yes

#24747 Amp animation e2e test
  extensions/amp-animation/0.1/test-e2e/test-amp-animation.js
  test/e2e/test-adchoices.js
  test/fixtures/e2e/amp-animation/simple.html
  test/fixtures/e2e/amphtml-ads/text.html
Labels: cla: yes

#25027 🐛Consider *.gmail.com trusted viewer domains
  src/config.js
Labels: cla: yes

#25042 🏗 Report and store the bundle size of alternate runtime and extension files
  build-system/tasks/bundle-size.js
Labels: cla: yes

#25044 Update amp-analytics owner file
  extensions/amp-analytics/OWNERS
Labels: cla: yes

#25043 SwG Release 0.1.22.75
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#25056 Disable amp-animation for shadow for flakiness
  extensions/amp-animation/0.1/test-e2e/test-amp-animation.js
Labels: cla: yes

#25059 Skip flaky subscriptions e2e test
  extensions/amp-subscriptions-google/0.1/test-e2e/test-amp-subscriptions-google.js
Labels: Related to: Flaky Tests, cla: yes

#25053 ✨ Update INFOnline analytics vendor configuration
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/infonline.js
Labels: cla: yes

#24895 🐛Add CSS rule to hide amp-loaders from stories
  css/ampdoc.css
Labels: cla: yes

#25000 🐛Restrict checking cached ampDoc reference to AMP elements.
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
  extensions/amp-sidebar/1.0/amp-sidebar.js
  extensions/amp-sidebar/1.0/test/test-amp-sidebar.js
  src/service/ampdoc-impl.js
  test/unit/test-ampdoc.js
Labels: cla: yes

#25011 ✨PWA: Expose amp-bind getState and setState
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  spec/amp-shadow-doc.md
  src/runtime.js
Labels: cla: yes

#25038 ✨Add "conative" ad network support to amp-ad
  3p/integration.js
  ads/_config.js
  ads/conative.js
  ads/conative.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#24822 Implement an amp-mega-menu component
  build-system/compile/bundles.config.js
  build-system/server/routes/list.js
  extensions/amp-mega-menu/0.1/amp-mega-menu.css
  extensions/amp-mega-menu/0.1/amp-mega-menu.js
  extensions/amp-mega-menu/0.1/test/test-amp-mega-menu.js
  extensions/amp-mega-menu/OWNERS
  test/manual/amp-mega-menu.amp.html
  tools/experiments/experiments.js
Labels: cla: yes

#24949 ✨ Add Empower to amp-ad networks
  3p/integration.js
  ads/_config.js
  ads/ads.extern.js
  ads/empower.js
  ads/empower.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
  validator/testdata/feature_tests/ads.html
  validator/testdata/feature_tests/ads.out
Labels: cla: yes

#25072 Validator roll up
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#24947 🐛Fix progress bar bug with more comprehensive advancement checks
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
Labels: cla: yes

#25075 🏗 Update all markdown files to be owned by wg-outreach
  OWNERS
Labels: cla: yes

#25057 🏗✨ Check non-JS files for formatting errors using `prettier` during local and Travis PR checks
  .prettierrc
  build-system/common/utils.js
  build-system/pr-check/build-targets.js
  build-system/pr-check/checks.js
  build-system/tasks/caches-json.js
  build-system/tasks/check-owners.js
  build-system/tasks/lint.js
  build-system/tasks/pr-check.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/prettify.js
  build-system/test-configs/config.js
  extensions/amp-mega-menu/OWNERS
  gulpfile.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#24818 📖Fix typo in AMP Variable Substitutions documentation
  spec/amp-var-substitutions.md
Labels: cla: yes

#24735 🏗 Upgrade the browsers we use on Sauce Labs
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test/runtime-test-base.js
Labels: cla: yes

#25063 📖 Update contributing docs to reflect non-YAML OWNERS files
  contributing/CODE_OWNERSHIP.md
  contributing/building-an-amp-extension.md
  contributing/contributing-code.md
  contributing/creating-a-welcoming-community.md
Labels: cla: yes

#25093 🏗 Add a `--local_changes` mode to `gulp prettify`
  build-system/common/default-pre-push
  build-system/common/utils.js
  build-system/tasks/lint.js
  build-system/tasks/pr-check.js
  build-system/tasks/prettify.js
  contributing/TESTING.md
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#25079 Fix minor URL typo for Collaborators team
  contributing/contributing-code.md
Labels: cla: yes

#25101 Fixing typo
  extensions/amp-ad-custom/amp-ad-custom.md
Labels: cla: yes

#25097 🏗 Replace `globs-to-files` with `globby`
  build-system/common/utils.js
  build-system/tasks/bundle-size.js
  build-system/tasks/check-owners.js
  build-system/tasks/dev-dashboard-tests.js
  build-system/tasks/dist.js
  build-system/tasks/lint.js
  build-system/tasks/prettify.js
  build-system/tasks/runtime-test/helpers-unit.js
  build-system/tasks/serve.js
  build-system/tasks/vendor-configs.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#24579 🐛Fix subdomain handling in idealmedia widgets
  ads/idealmedia.js
Labels: cla: yes

#25065 ✅ Deflakes SwG E2E Test
  extensions/amp-subscriptions-google/0.1/test-e2e/test-amp-subscriptions-google.js
Labels: cla: yes

#25087 🏗 Makes Yuan an owner of SwG extension
  extensions/amp-subscriptions-google/OWNERS
Labels: cla: yes

#25062 Add wg-amp4email as OWNERS for spec/email
  spec/email/OWNERS
Labels: cla: yes

#25096 🏗 Fix team names in OWNERS of `tools`
  tools/OWNERS
Labels: cla: yes

#25114 Fix syntax for spec/email/OWNERS
  spec/email/OWNERS
Labels: cla: yes

#24908 Set @alanorozco and @wassgha as owners of video service
  src/service/video/OWNERS
Labels: cla: yes

#25073 remove sp path from extension location
  src/service/extension-location.js
  test/unit/test-extension-location.js
Labels: cla: yes

#23853 Improve text-matching algorithm of amp-viewer-integration/findtext.js.
  extensions/amp-viewer-integration/0.1/findtext.js
  extensions/amp-viewer-integration/0.1/test/test-findtext.js
Labels: cla: yes

#25103 Updates to the .md read me file for <amp-embed type="insticator">
  ads/insticator.md
Labels: cla: yes

#24965 ✨ Add Comscore Translated Consent Parameter
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/comscore.js
Labels: cla: yes

#24900 🐛Fixes ima-video race condition and percentage played
  extensions/amp-ima-video/0.1/amp-ima-video.js
  src/service/video-manager-impl.js
Labels: cla: yes

#25088 SwG release 0.1.22.76
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#24902 Allow parentPostMessage for FIE for amp-analytics
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
Labels: cla: yes

#25135 SwG Release 0.1.22.77
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#24968 Story branching support for sidebar links.
  examples/visual-tests/amp-story/amp-story-sidebar.html
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#25109 Formatting a code-block
  extensions/amp-ad-custom/amp-ad-custom.md
Labels: cla: yes

#25136 🏗 Fix watch mode on e2e tests
  build-system/tasks/e2e/index.js
Labels: cla: yes

#25131 🐛 fix getPreviousPageId
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#25139 Avoid swipe to dismiss errors being logged.
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: cla: yes

#25140 🏗🚀 Significantly speed up `gulp prettify`
  build-system/tasks/prettify.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#25145 🐛✅ <header> -> <head> to fix test flake
  test/fixtures/e2e/amp-subscriptions-google/swg.amp.html
Labels: cla: yes

#25092 allow firebase for 3p frames
  build-system/tasks/firebase.js
  contributing/TESTING.md
Labels: cla: yes

#25152 🏗 Fix `gulp prettify` when there's nothing to check
  build-system/tasks/prettify.js
Labels: WG: infra, cla: yes

#25151 Adds some more people to collaboration OWNERS
  contributing/OWNERS
Labels: cla: yes

#25153 remove preinstall script for node.js
  validator/nodejs/package.json
Labels: cla: yes

#25141 ✨ Launch Custom Elements v1 Polyfill
  build-system/compile/compile.js
  build-system/compile/shorten-license.js
  build-system/compile/sources.js
  build-system/global-configs/experiments-config.json
  build-system/tasks/presubmit-checks.js
  build-system/tasks/update-packages.js
  package.json
  src/friendly-iframe-embed.js
  src/polyfills.js
  src/polyfills/custom-elements.js
  src/service/custom-element-registry.js
  test/unit/test-custom-element-registry.js
  yarn.lock
Labels: cla: yes

#25156 🐛 Fix escaping of backticks in json configuration
  build-system/babel-plugins/babel-plugin-transform-json-configuration/index.js
  build-system/babel-plugins/babel-plugin-transform-json-configuration/test/fixtures/transform/escapes/input.js
  build-system/babel-plugins/babel-plugin-transform-json-configuration/test/fixtures/transform/escapes/output.js
Labels: cla: yes

#25155 🏗 Pre-build JS files and extensions loaded by core runtime during `gulp` startup
  build-system/server/lazy-build.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
  build-system/tasks/serve.js
Labels: WG: infra, cla: yes

#25095 amp-sidebar: Propagate trust from action->event
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
  extensions/amp-sidebar/1.0/amp-sidebar.js
  extensions/amp-sidebar/1.0/test/test-amp-sidebar.js
Labels: cla: yes

#25161 Upgrade node from ^10.0.0 to ^12.0.0
  package.json
  validator/nodejs/package.json
  validator/package.json
  validator/webui/package.json
  yarn.lock
Labels: cla: yes

#25162 Upgrade amphtml-validator version to 1.0.26
  validator/nodejs/package.json
Labels: cla: yes

#25110 amp-accordion: Propagate trust from action->event
  extensions/amp-accordion/0.1/amp-accordion.js
  extensions/amp-accordion/0.1/test/test-amp-accordion.js
Labels: cla: yes

#25133 🐛Transition to submit-error on SSR error responses
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
Labels: cla: yes

#25167 🚮 Delete testIE mode because Custom Elements v1 Polyfill was launched
  build-system/tasks/runtime-test/runtime-test-base.js
  src/mode.js
Labels: cla: yes

#25170 Ramp up experiment for sidebar swipe-to-dismiss
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#25177 Navigation: Fix IE a11y patch & clean up
  src/service/navigation.js
  test/unit/test-navigation.js
Labels: cla: yes

#25169 Separate experiments object block from experiment.js code
  tools/experiments/OWNERS
  tools/experiments/experiments-config.js
  tools/experiments/experiments.js
Labels: cla: yes

#25204 Publish amphtml-validator version 1.0.27
  validator/nodejs/package.json
Labels: cla: yes
