Repository ampproject/amphtml, pull requests merged in 2019-12, with the labels that each got.

#25796 ✅Add end-to-end tests for <amp-autocomplete inline>
  extensions/amp-autocomplete/0.1/test-e2e/test-amp-autocomplete-inline.js
  test/manual/amp-autocomplete/amp-autocomplete-inline.amp.html
Labels: cla: yes

#25668 Correct sandbox attribute browser support
  extensions/amp-iframe/amp-iframe.md
Labels: cla: yes

#25260 ✨ amp-autocomplete: Support SSR templating
  examples/amp-autocomplete.ssr.html
  examples/viewer.html
  examples/visual-tests/amp-autocomplete/amp-autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
  src/service/template-impl.js
Labels: cla: yes

#25816 📖 Update project metrics in readme and metrics page
  METRICS.md
  README.md
Labels: cla: yes

#25767 added action for amp-lightbox-gallery
  spec/amp-actions-and-events.md
Labels: cla: yes

#25801 🐛 CEv1: Support IE10
  src/polyfills/custom-elements.js
Labels: cla: yes

#25749 🚀Use standard decryption method in crypto-handler.
  build-system/test-configs/dep-check-config.js
  extensions/amp-subscriptions/0.1/crypto-handler.js
  extensions/amp-subscriptions/0.1/test/test-crypto-handler.js
Labels: cla: yes

#25638 Viewer must be trusted for ssr templates to be supported
  build-system/tasks/presubmit-checks.js
  extensions/amp-form/0.1/test/test-amp-form.js
  src/ssr-template-helper.js
  test/unit/test-ssr-template-helper.js
Labels: cla: yes

#25771 🐛 Remove splice Infinity
  src/service/resources-impl.js
Labels: cla: yes

#25757 Adding Deep.BI analytics to AMP
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/deepbi.js
Labels: cla: yes

#25797 🚀 Make macro-after-long-task the default for chunk.js
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  src/chunk.js
  test/unit/test-chunk.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#25818 🐛 amp-consent accept enum response
  examples/amp-consent-geooveride.html
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-info.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
Labels: cla: yes

#25823 🐛Remove `postEvent` allowlist from video iframe integration
  src/video-iframe-integration.js
  test/unit/test-video-iframe-integration.js
Labels: cla: yes

#25799 📖 Clarify `AMP.push` for default experiment toggles
  tools/experiments/README.md
Labels: cla: yes

#25832 🐛 CEv1: copy properties from prototype chain in IE10
  src/polyfills/custom-elements.js
  test/unit/test-polyfill-custom-elements.js
Labels: cla: yes

#25752 ✨🐛 Scroll return button on docked video ad
  extensions/amp-video-docking/0.1/amp-video-docking.css
  extensions/amp-video-docking/0.1/amp-video-docking.js
  extensions/amp-video-docking/0.1/controls.js
  extensions/amp-video-docking/0.1/events.js
  extensions/amp-video-docking/0.1/test/test-amp-video-docking.js
  extensions/amp-video-docking/amp-video-docking.md
Labels: cla: yes

#25817 🚮 Clean up use-responsive-ads-for-responsive-sizing-in-auto-ads holdback experiment
  extensions/amp-auto-ads/0.1/amp-auto-ads.js
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
  extensions/amp-auto-ads/0.1/test/test-placement.js
Labels: cla: yes

#25847 Disabling amp-gfycat support within amp-story-grid-layer.
  extensions/amp-story/amp-story-grid-layer.md
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#25853 amp-consent geo examples iframe auto accept
  examples/amp-consent/geooverride-iframe.amp.html
  examples/amp-consent/geooverride.amp.html
  examples/amp-consent/prompt.html
Labels: cla: yes

#25846 Validator rollup
  extensions/amp-list/0.1/test/validator-amp-list.html
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/validator-amp-list.protoascii
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#25843 Turn on amp-consent-geo-override in canary and prod
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-consent/0.1/amp-consent.js
Labels: cla: yes

#24307 ✨🐛UpScore Analytics: Changed ampURL to canonical URL and added 2 custom params
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/upscore.js
Labels: cla: yes

#25197 ✨ Red Bull video player
  build-system/compile/bundles.config.js
  build-system/test-configs/dep-check-config.js
  examples/amp-redbull-player.amp.html
  extensions/amp-redbull-player/0.1/amp-redbull-player.js
  extensions/amp-redbull-player/0.1/test/test-amp-redbull.js
  extensions/amp-redbull-player/0.1/test/validator-amp-redbull.html
  extensions/amp-redbull-player/0.1/test/validator-amp-redbull.out
  extensions/amp-redbull-player/OWNERS
  extensions/amp-redbull-player/amp-redbull-player.md
  extensions/amp-redbull-player/validator-amp-redbull-player.protoascii
Labels: Validator: Approved, cla: yes

#25822 🏗🚮 Replace `bluebird` promises with node's native promises
  build-system/compile/single-pass.js
  build-system/server/app-index/index.js
  build-system/server/app-index/test/test-self.js
  build-system/server/app-index/util/listing.js
  build-system/server/app-video-testbench.js
  build-system/server/app.js
  build-system/server/recaptcha-router.js
  build-system/server/routes/a4a-envelopes.js
  build-system/tasks/bundle-size/index.js
  build-system/tasks/changelog.js
  build-system/tasks/check-owners.js
  build-system/tasks/csvify-size/index.js
  build-system/tasks/dep-check.js
  build-system/tasks/e2e/puppeteer-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  build-system/tasks/prepend-global/index.js
  build-system/tasks/process-3p-github-pr.js
  build-system/tasks/process-github-issues.js
  build-system/tasks/release-tagging.js
  build-system/tasks/todos.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#25839 Fix error, remove BaseElement.layoutWidth_
  build-system/externs/amp.multipass.extern.js
  builtins/amp-img.js
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/0.1/test/test-slidescroll.js
  extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
  extensions/amp-fx-flying-carpet/0.1/test/test-amp-fx-flying-carpet.js
  extensions/amp-vk/0.1/test/test-amp-vk.js
  src/base-element.js
  src/custom-element.js
  src/service/resources-impl.js
  test/unit/test-amp-img.js
  test/unit/test-custom-element.js
  test/unit/test-resources.js
Labels: cla: yes

#25635 Correct type for position observer `relativePos`
  src/service/position-observer/position-observer-worker.js
Labels: cla: yes

#25862 Fix extension URL parsing for optional ".max"
  src/service/extension-location.js
  test/unit/test-extension-location.js
Labels: cla: yes

#24716 Add request assertion to amp-ad-exit e2e test
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/request-bank.js
  extensions/amp-ad-exit/0.1/test-e2e/test-amp-ad-exit.js
  test/fixtures/e2e/amphtml-ads/amp-ad-exit.amp.html
Labels: cla: yes

#25702 🐛 Pressing esc or back key to close expanded component
  extensions/amp-story/1.0/amp-story-embedded-component.js
Labels: cla: yes

#25877 🐛Avoid fractional scroll position impacting current index.
  extensions/amp-carousel/0.2/amp-carousel.js
Labels: cla: yes

#25876 🐛Fix amp-carousel 0.2 bound slide change to slide zero.
  extensions/amp-carousel/0.2/amp-carousel.js
Labels: cla: yes

#25875 Revert "Launch inabox-viewport-friendly (#25622)"
  ads/inabox/inabox-host.md
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  build-system/server/routes/a4a-envelopes.js
  src/inabox/inabox-iframe-messaging-client.js
  src/inabox/inabox-viewport.js
  test/integration/test-amphtml-ads.js
  test/unit/inabox/test-inabox-viewport.js
  tools/experiments/experiments-config.js
Labels: P0: Drop Everything, cla: yes

#25619 ✨ Copy data attrs from amp-img to inner img (fixes #24787)
  builtins/amp-img.js
  builtins/amp-img.md
  src/base-element.js
  test/unit/test-amp-img.js
  test/unit/test-base-element.js
Labels: cla: yes

#25882 Fix single page story prerendering.
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#25857 🐛 Expire cache fix for server-side decisions
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
Labels: cla: yes

#25863 Improve amp-consent examples
  examples/amp-consent/amp-consent-client.html
  examples/amp-consent/amp-consent-cmp.html
  examples/amp-consent/amp-consent-geo.html
  examples/amp-consent/amp-consent-server.html
  examples/amp-consent/diy-consent.html
  examples/amp-consent/prompt.html
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/0.1/test/test-consent-config.js
  test/manual/amp-consent/amp-consent-cmp-overlay.html
  test/manual/amp-consent/legacy_config_support/amp-consent-geo.html
  test/manual/amp-consent/legacy_config_support/amp-consent-iframe.amp.html
  test/manual/amp-consent/legacy_config_support/amp-consent.amp.html
Labels: cla: yes

#25890 ✅ Visual tests for amp-video-docking
  examples/visual-tests/amp-video-docking/amp-video-docking.html
  examples/visual-tests/amp-video-docking/amp-video-docking.js
  examples/visual-tests/amp-video-docking/video-iframe-inner.html
  test/visual-diff/visual-tests
Labels: cla: yes

#25787 📈 ✨ Add analytics for openable and closeable things
  examples/amp-story/amp-story-branching.html
  examples/amp-story/analytics.html
  examples/visual-tests/amp-story/info-dialog.html
  extensions/amp-story/1.0/amp-story-info-dialog.js
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story-share-menu.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/story-analytics.js
Labels: cla: yes

#25896 🐛Correctly handle file read errors in gulp test server
  build-system/server/app-video-testbench.js
  build-system/server/app.js
Labels: WG: infra, cla: yes

#25792 ✅Add visual test for <amp-autocomplete inline>
  examples/visual-tests/amp-autocomplete/amp-autocomplete.amp.html
  examples/visual-tests/amp-autocomplete/amp-autocomplete.js
Labels: cla: yes

#25683 Changes for amp-base-carousel to support amp-inline-gallery.
  extensions/amp-base-carousel/0.1/amp-base-carousel.css
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/auto-advance.js
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-base-carousel/0.1/test-e2e/test-rtl.js
Labels: cla: yes

#25899 📖Update amp-autocomplete documentation to include "inline" and "query" attributes
  extensions/amp-autocomplete/amp-autocomplete.md
Labels: cla: yes

#25870 ✅Add validation rules for amp-autocomplete[inline] and amp-autocomplete[query]
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
  extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
Labels: Validator: Approved, WG: caching, cla: yes

#25287 📖 3p video player guide and explainer
  spec/amp-3p-video.md
  src/video-interface.js
Labels: cla: yes

#25903 🐛 fix incirrict fint fimily
  examples/amp-story/ampconf.html
  examples/amp-story/rtl.html
Labels: cla: yes

#25860 clarified visibility trigger behavior
  extensions/amp-animation/amp-animation.md
Labels: cla: yes

#25891 🐛Make amp-carousel 0.1 focusable
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
Labels: cla: yes

#25841 📖 Update PR template with link to contribution process
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#25758 ✨amp-viqeo-player: full support analytics
  3p/viqeoplayer.js
  extensions/amp-analytics/amp-video-analytics.md
  extensions/amp-viqeo-player/0.1/amp-viqeo-player.js
  extensions/amp-viqeo-player/0.1/test/test-amp-viqeo-player.js
Labels: cla: yes

#25898 Revert "Introduce AMP Live List Cache Busting"
  build-system/test-configs/dep-check-config.js
  extensions/amp-live-list/0.1/live-list-manager.js
Labels: cla: yes

#25688 🐛 Possible fix for resizing amp-ad beop
  3p/beopinion.js
Labels: cla: yes

#25917 Fixes amp-analytics iframeTransport regression.
  examples/amphtml-ads/botguard.a4a.html
  extensions/amp-analytics/0.1/amp-analytics.js
Labels: cla: yes

#25889 ✨Allow amp-selector in AMP4ADS
  extensions/amp-selector/validator-amp-selector.protoascii
  validator/engine/validator_test.js
  validator/testdata/amp4ads_feature_tests/amp_selector.html
  validator/testdata/amp4ads_feature_tests/amp_selector.out
  validator/testdata/amp4ads_feature_tests/extensions.html
  validator/testdata/amp4ads_feature_tests/extensions.out
Labels: Validator: Approved, WG: caching, cla: yes

#25581 📖 Adapt misleading comment in validateLayout()
  validator/engine/validator.js
Labels: cla: yes

#25840 📖amp-list: documentation for using the new strip-prefix attribute
  extensions/amp-list/amp-list.md
Labels: cla: yes

#25921 Add e2e tests for amp-analytics iframe transport
  extensions/amp-analytics/0.1/test-e2e/test-iframe-transport.js
  test/fixtures/e2e/amphtml-ads/botguard.a4a.html
Labels: cla: yes

#25916 Move consent.a4a.html to /examples/amp-consent/
  examples/amp-consent/amp-consent-amp-ad.amp.html
Labels: cla: yes

#25611 Update `amp-consent` spec for the `geoOverride` support
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#25925 Inject transport iframe to top window
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/iframe-transport.js
  extensions/amp-analytics/0.1/test/test-iframe-transport.js
  extensions/amp-analytics/0.1/test/test-transport.js
  extensions/amp-analytics/0.1/transport.js
Labels: cla: yes

#25854 🐛Check resolved URL for google.com during getEncryptedDocumentKey
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#25585 🐛 Changes analytics notification example in amp.dev because the current example gives error when run locally
  examples/analytics-notification.amp.html
Labels: cla: yes

#25905 amp-consent: support unknown state from response
  examples/amp-consent/amp-consent-geo.html
  examples/amp-consent/amp-consent-server.html
  extensions/amp-consent/0.1/consent-info.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-consent-info.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
Labels: cla: yes

#25929 amp-consent geoOverride: should NOT override instanceId
  extensions/amp-consent/0.1/consent-config.js
  extensions/amp-consent/0.1/test/test-consent-config.js
Labels: cla: yes

#25930 Update amp-consent.md
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#25842 Consolidate forcePromptOnNext into expireCache
  extensions/amp-consent/0.1/amp-consent.js
Labels: cla: yes

#25575 📖 Added description and css for it in analytics-notification to solve #24905
  examples/analytics-notification.amp.html
Labels: cla: yes

#25915 📖 Add wg-ui-and-a11y to 3p OWNERS set
  3p/OWNERS
Labels: cla: yes

#25808 📖 Update rule for mutation / user-gesture
  extensions/amp-script/amp-script.md
Labels: cla: yes

#25901 🐛 amp-subscriptions: Fixes click event delegation for iOS 13.2
  extensions/amp-subscriptions/0.1/local-subscription-platform-base.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions-iframe-platform.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Labels: cla: yes

#25941 ✅ Unflake video docking visual tests
  examples/visual-tests/amp-video-docking/amp-video-docking.js
  examples/visual-tests/amp-video-docking/video-iframe-inner.html
Labels: cla: yes

#25928 🐛 Fixes amp-mega-menu flaky diff test
  examples/visual-tests/amp-mega-menu/amp-mega-menu.js
Labels: cla: yes

#25914 🐛 Fix binary type map in a4a
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
  test/unit/test-error.js
  test/unit/test-experiments.js
Labels: cla: yes

#25944 ✅ Visual test docking controls activated by tap
  examples/visual-tests/amp-video-docking/amp-video-docking.js
Labels: cla: yes

#25947 ✅ Visual test video docking: RTL and dock into slot element
  examples/visual-tests/amp-video-docking/ltr.html
  examples/visual-tests/amp-video-docking/rtl.html
  examples/visual-tests/amp-video-docking/slot.html
  test/visual-diff/visual-tests
Labels: cla: yes

#25952 📖 Specify how amp-video-iframe can be used by video vendors
  extensions/amp-video-iframe/amp-video-iframe.md
Labels: cla: yes

#25784 🐛 Propagate nonce to generated script tags.
  src/service/extensions-impl.js
  src/validator-integration.js
  test/unit/test-validator-integration.js
Labels: cla: yes

#25956 🐛Protect against video freezing in stories
  src/service/video-manager-impl.js
  test/unit/test-video-analytics-percentage-tracker.js
Labels: cla: yes

#25629 🏗Multi-doc manager refactor
  build-system/tasks/presubmit-checks.js
  extensions/amp-next-page/0.1/next-page-service.js
  src/amp.js
  src/multidoc-manager.js
  src/runtime.js
  test/_init_tests.js
Labels: UI: Component: amp-next-page, cla: yes

#25636 ✨ Initial implementation of amp-next-page v2
  build-system/compile/bundles.config.js
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-next-page/0.2/amp-next-page.css
  extensions/amp-next-page/0.2/amp-next-page.js
  extensions/amp-next-page/0.2/page.js
  extensions/amp-next-page/0.2/service.js
  extensions/amp-next-page/0.2/utils.js
  src/services.js
  test/manual/amp-next-page/0.2/amp-next-page.amp.html
  tools/experiments/experiments-config.js
Labels: cla: yes

#25951 🐛♻️ Docking: pageLayoutBox and position RTL controls
  extensions/amp-video-docking/0.1/amp-video-docking.css
  extensions/amp-video-docking/0.1/amp-video-docking.js
  extensions/amp-video-docking/0.1/test/test-amp-video-docking.js
Labels: cla: yes

#25821 Clean up 'remove-viewer-query-params-on-navigate' experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  src/service/navigation.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#25953 Swg release 0.1.22.85
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#25946 ♻️ Refactor: Rename strip-prefix to xssi-prefix
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/validator-amp-list.html
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/amp-list.md
  extensions/amp-list/validator-amp-list.protoascii
  src/batched-json.js
Labels: cla: yes

#25963 Fix 3p/ OWNERS files
  3p/OWNERS
Labels: cla: yes

#25958 Ramp layoutbox-invalidate-on-scroll to 10%
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#25788 ✅ Moves `expect` calls to top level in `amp-subscriptions-google` tests
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Labels: cla: yes

#25959 🐛 amp-next-page fix interaction with styles
  extensions/amp-next-page/0.1/next-page-service.js
Labels: cla: yes

#25948 ♻️ Refactor template helper: Rename isSupported() to isEnabled()
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  src/ssr-template-helper.js
  test/unit/test-ssr-template-helper.js
Labels: cla: yes

#25970 propagate nonce: update to only document.head
  src/service/extensions-impl.js
  src/validator-integration.js
Labels: cla: yes

#25904 Move calls to mutator interface into a dedicated service
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-access/0.1/test/test-amp-access.js
  extensions/amp-ad/0.1/amp-ad-ui.js
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-auto-ads/0.1/test/test-placement.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-form/0.1/amp-form-textarea.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/form-validators.js
  extensions/amp-form/0.1/test/test-amp-form-textarea.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-form/0.1/test/test-form-validators.js
  extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js
  extensions/amp-fx-collection/0.1/providers/fx-provider.js
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-mathml/0.1/amp-mathml.js
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-next-page/0.1/test/test-amp-next-page.js
  extensions/amp-story/0.1/amp-story-consent.js
  extensions/amp-story/0.1/amp-story-info-dialog.js
  extensions/amp-story/0.1/test/test-amp-story-info-dialog.js
  extensions/amp-story/1.0/amp-story-affiliate-link.js
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-info-dialog.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/progress-bar.js
  extensions/amp-story/1.0/test/test-amp-story-access.js
  extensions/amp-story/1.0/test/test-amp-story-consent.js
  extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
  extensions/amp-story/1.0/test/test-amp-story-info-dialog.js
  extensions/amp-subscriptions/0.1/renderer.js
  extensions/amp-subscriptions/0.1/test/test-renderer.js
  src/base-element.js
  src/custom-element.js
  src/friendly-iframe-embed.js
  src/service/standard-actions-impl.js
  src/services.js
  test/unit/test-custom-element.js
  test/unit/test-friendly-iframe-embed.js
  test/unit/test-standard-actions.js
Labels: cla: yes

#25868 ✨ Add xssiPrefix to amp-consent
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#25973 Validator rollup
  extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
  extensions/amp-lightbox/validator-amp-lightbox.protoascii
  extensions/amp-sidebar/validator-amp-sidebar.protoascii
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/testdata/amp4ads_feature_tests/extensions.out
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: cla: yes

#25849 🐛Add warning about using GET to send cryptokey
  extensions/amp-subscriptions/0.1/local-subscription-platform-remote.js
Labels: cla: yes

#25617 Initial implementation of amp-inline-gallery
  build-system/compile/bundles.config.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-inline-gallery/0.1/amp-inline-gallery-pagination.css
  extensions/amp-inline-gallery/0.1/amp-inline-gallery-pagination.js
  extensions/amp-inline-gallery/0.1/amp-inline-gallery.css
  extensions/amp-inline-gallery/0.1/amp-inline-gallery.js
  extensions/amp-inline-gallery/0.1/inline-gallery-events.js
  test/manual/amp-base-carousel/basic.amp.html
  test/manual/amp-inline-gallery/fixed-height.amp.html
  test/manual/amp-inline-gallery/img/alan-jones-OQsxdghBKrU-unsplash-small.jpg
  test/manual/amp-inline-gallery/img/ivars-krutainis-jTJ9-4ESzU4-unsplash-small.jpg
  test/manual/amp-inline-gallery/img/ola-gronlund--MuvLw5G6x8-unsplash-small.jpg
  test/manual/amp-inline-gallery/img/sander-dewerte--jcP3xbN88w-unsplash-small.jpg
  test/manual/amp-inline-gallery/pagination-only-autoplay.amp.html
  test/manual/amp-inline-gallery/pagination-only-many-slides.amp.html
  test/manual/amp-inline-gallery/pagination-only-outset.amp.html
  test/manual/amp-inline-gallery/pagination-only-remote-images.amp.html
  test/manual/amp-inline-gallery/pagination-only-responsive.amp.html
  test/manual/amp-inline-gallery/pagination-only.amp.html
  test/manual/amp-inline-gallery/rtl.amp.html
Labels: cla: yes

#25950 ✨Add "sulvo" adserver support to amp-ad
  3p/integration.js
  ads/_config.js
  ads/sulvo.js
  ads/sulvo.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#25340 ⏪📖 JW Player: Update documentation and remove configuration options
  examples/jwplayer.amp.html
  extensions/amp-jwplayer/0.1/amp-jwplayer.js
  extensions/amp-jwplayer/0.1/test/test-amp-jwplayer.js
  extensions/amp-jwplayer/0.1/test/validator-amp-jwplayer.html
  extensions/amp-jwplayer/0.1/test/validator-amp-jwplayer.out
  extensions/amp-jwplayer/amp-jwplayer.md
Labels: Validator: Approved, cla: yes

#25809 Intent to implement: `amp-ad` type for AdServSolutions #25806
  3p/integration.js
  ads/_config.js
  ads/adservsolutions.js
  ads/adservsolutions.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#25927 xssi-prefix support to amp-form
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-form/amp-form.md
Labels: cla: yes

#26002 🏗 Don't cache for Travis experiment jobs
  .travis.yml
Labels: cla: yes

#25986 🐛 Append url parameters correct in viewer-demo
  build-system/tasks/e2e/amp-driver.js
Labels: cla: yes

#25993 ID disallowed names
  spec/amp-html-format.md
Labels: cla: yes

#25488 Cleanup amp-mega-menu experiment
  extensions/amp-mega-menu/0.1/amp-mega-menu.js
  extensions/amp-mega-menu/0.1/test/test-amp-mega-menu.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#26017 📖Fix component link s/youtube/story/
  spec/amp-3p-video.md
Labels: cla: yes

#25798 🐛amp-autocomplete: Require "filter" attribute in validations
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
  extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
  validator/testdata/feature_tests/no_dev_mode.html
  validator/testdata/feature_tests/no_dev_mode.out
Labels: Validator: Approved, WG: caching, cla: yes

#26000 ✨ Implementing analytics vendor support for Memo (memo.co)
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/memo.js
Labels: cla: yes

#25965 Updates Design Review guidelines (explainers, deadlines and public requirement)
  contributing/design-reviews.md
Labels: cla: yes

#26021 ✨ SwG: Promote native buyflow to 100% for SwG in AMP
  build-system/global-configs/prod-config.json
Labels: cla: yes

#26008 📖Documents existing analytics triggers on `amp-next-page`
  extensions/amp-next-page/amp-next-page.md
Labels: cla: yes

#25637 Add support for Sklik SSP amp-ad
  3p/integration.js
  ads/_config.js
  ads/ssp.js
  ads/ssp.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
  test/unit/ads/test-ssp.js
Labels: cla: yes

#25207 Added new ad network: Nativery
  3p/integration.js
  ads/_config.js
  ads/nativery.js
  ads/nativery.md
  build-system/test-configs/conformance-config.textproto
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#26001 Treat amp-script AMP.setState as high trust
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
  extensions/amp-script/amp-script.md
  test/unit/test-validator-integration.js
Labels: cla: yes

#25943 🚮 Remove unnecessary lpdid script loading
  ads/capirs.js
Labels: cla: yes

#25971 ✨amp-next-page v2 history manipulation
  extensions/amp-next-page/0.2/page.js
  extensions/amp-next-page/0.2/service.js
Labels: cla: yes

#25955 🐛Fix next/prev arrows being clickable with hidden controls for amp-base-carousel
  extensions/amp-base-carousel/0.1/amp-base-carousel.css
  extensions/amp-base-carousel/0.1/test-e2e/test-hidden-controls.js
  test/manual/amp-base-carousel/hidden-controls.amp.html
Labels: cla: yes

#25259 🐛 Fixed first contentful paint race condition
  extensions/amp-access/0.1/test/test-amp-access-source.js
  extensions/amp-access/0.1/test/test-amp-access.js
  src/amp.js
  src/inabox/amp-inabox.js
  src/service/performance-impl.js
  src/service/url-replacements-impl.js
  test/integration/test-amp-analytics.js
  test/manual/amp-analytics/analytics-fcp.html
  test/unit/test-layout-delay-meter.js
  test/unit/test-performance.js
  test/unit/test-style-installer.js
Labels: cla: yes

#24119 ✨ Validator support for transformed intrinsic layout
  validator/engine/validator.js
  validator/testdata/transformed_feature_tests/server_side_rendering.html
  validator/testdata/transformed_feature_tests/server_side_rendering.out
  validator/testdata/transformed_feature_tests/transformed_but_not_identified_transformed.out
  validator/validator-main.protoascii
Labels: Validator: Approved, cla: yes

#24346 Introduce Largest Contentful Paint tick event
  extensions/amp-viewer-integration/TICKEVENTS.md
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#25931 Report dev error at viewer channel timeout
  src/log.js
  src/service/viewer-impl.js
Labels: cla: yes

#26068 🐛 Fix `gulp changelog`
  build-system/tasks/changelog.js
Labels: Type: Bug, WG: infra, cla: yes

#26062 SwG Release 0.1.22.87
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#26011 ✨Add inline-gallery thumbnails element.
  build-system/compile/bundles.config.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/carousel.css
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-inline-gallery/0.1/amp-inline-gallery-thumbnails.css
  extensions/amp-inline-gallery/0.1/amp-inline-gallery-thumbnails.js
  extensions/amp-inline-gallery/0.1/amp-inline-gallery.js
  test/manual/amp-inline-gallery/pagination-and-thumbnails.amp.html
Labels: cla: yes

#26073 🐛Fix test failure
  test/unit/test-performance.js
Labels: cla: yes

#26007 ✨ amp-story: Add support for a viewer to tell the AMP story to switch pages
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/story-analytics.js
Labels: cla: yes

#26013 Amp consent e2e
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-client-side.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side-expire-cache.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js
  test/manual/amp-consent/amp-consent-basic-uses.amp.html
Labels: cla: yes

#23247 🐛 load script inside #c container for Zucks ad
  ads/zucks.js
Labels: cla: yes

#26083 cl/285484769 Revision bump for #25798
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
  validator/validator-main.protoascii
Labels: Validator: Approved, cla: yes

#26054 Allow setting RTV experiment flag to custom value
  build-system/compile/build.conf.js
Labels: cla: yes

#26084 Validator 20191218
  build-system/tasks/presubmit-checks.js
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/testdata/amp4email_feature_tests/nonce_disallowed.out
  validator/testdata/feature_tests/empty.out
  validator/testdata/feature_tests/lts_extension_without_lts_runtime.html
  validator/testdata/feature_tests/lts_extension_without_lts_runtime.out
  validator/testdata/feature_tests/lts_runtime_after_extension.html
  validator/testdata/feature_tests/lts_runtime_after_extension.out
  validator/testdata/feature_tests/lts_runtime_and_extensions.html
  validator/testdata/feature_tests/lts_runtime_and_extensions.out
  validator/testdata/feature_tests/not_amp.out
  validator/testdata/feature_tests/several_errors.out
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: WG: caching, cla: yes

#25829 🏗 Handle missing decrypted document key correctly
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/crypto-handler.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Labels: cla: yes

#26075 Generate analytics vendor configs in singlepass
  build-system/tasks/extension-helpers.js
Labels: cla: yes

#24663 a4a envelopes: (mock) mraid envelope, and no host script if friendly
  build-system/server/app-index/document-modes.js
  build-system/server/app.js
  build-system/server/routes/a4a-envelopes.js
  build-system/server/server-inabox-template.html
Labels: cla: yes

#26088 Adding size check to amp-analytics code
  build-system/tasks/bundle-size/APPROVERS.json
Labels: cla: yes

#26059 Snowplow v2
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/snowplow.js
  extensions/amp-analytics/0.1/vendors/snowplow_v2.js
  extensions/amp-analytics/0.1/vendors/snowplow_v2.json
Labels: cla: yes

#26094 cl/286269591 AMP respect different varieties of lightning bolt.
  validator/engine/validator.js
Labels: WG: caching, cla: yes

#26065 Remove 'canary' perf experiment
  src/service/performance-impl.js
Labels: cla: yes

#26089 Skip flakey amp-consent e2e
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side-expire-cache.js
Labels: cla: yes

#26086 ♻️ amp-story-quiz: fix small gcc type warning
  extensions/amp-story/1.0/amp-story-quiz.js
Labels: cla: yes

#26071 Add FIE visual tests for amp-ad
  examples/visual-tests/amphtml-ads/amp-fie-static.html
  test/visual-diff/visual-tests
Labels: cla: yes

#26069 ♿Replace `i-amphtml-screen-reader` usage on amp-carousel 0.1
  extensions/amp-carousel/0.1/amp-carousel.css
  extensions/amp-carousel/0.1/base-carousel.js
  extensions/amp-carousel/0.1/test-e2e/test-hidden-controls.js
  test/manual/amp-carousel/0.1/hidden-controls.amp.html
Labels: cla: yes

#26092 updated macro code sample to inline executable
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#26063 🚮Remove amp-autocomplete `inline` and `query` experiments
  examples/visual-tests/amp-autocomplete/amp-autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/autocomplete-binding-inline.js
  extensions/amp-autocomplete/0.1/test-e2e/test-amp-autocomplete-inline.js
  extensions/amp-autocomplete/0.1/test-e2e/test-amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-bindings.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/amp-autocomplete.md
Labels: cla: yes

#26032 ♻️ Refactors visibility observing in amp-next-page v2
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-next-page/0.2/page.js
  extensions/amp-next-page/0.2/service.js
  extensions/amp-next-page/0.2/visibility-observer.js
Labels: cla: yes

#26096 🐛Don't request story ad in short stories.
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
Labels: cla: yes

#26110 🐛 Metering viewer fix
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#26116 Modifying AMP Auto Ads to run strategies even if noConfigReason present
  extensions/amp-auto-ads/0.1/amp-auto-ads.js
  extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
Labels: cla: yes

#25002 Add an exceptional case for the deprecation process
  spec/amp-versioning-policy.md
Labels: cla: yes

#26108 Disallow redirect on amp-form submission in AMP4Email
  extensions/amp-form/0.1/amp-form.js
  spec/email/amp-email-components.md
  spec/email/amp-email-format.md
Labels: cla: yes

#26066 amp-script: Remove height constraint for mutation
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/integration/test-amp-script.js
  extensions/amp-script/amp-script.md
Labels: cla: yes

#26112 Improve amp-consent e2e
  extensions/amp-consent/0.1/test-e2e/common.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-client-side.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side-expire-cache.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js
Labels: cla: yes

#26028 🏗 Add a `--coverage` flag to `gulp build` to instrument the unminified runtime
  build-system/tasks/build.js
  build-system/tasks/helpers.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes
