Repository ampproject/amphtml, pull requests merged in 2019-09, with the labels that each got.

#24325 🏗 Re-implement `gulp serve` as an in-process server
  build-system/app.js
  build-system/recaptcha-router.js
  build-system/server.js
  build-system/tasks/build.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/serve.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#23944 Follow changes in the Event Timing API in Chrome 77.
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#24322 🖍Progressbar overflow tweaks
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/progress-bar.js
Labels: cla: yes

#24340 📖 Update amp-carousel 0.2 doc formats
  extensions/amp-carousel/amp-carousel.md
Labels: cla: yes

#24315 Revert "amp-bind: Rate-limit history operations"
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
Labels: cla: yes

#24341 Validator rollup
  extensions/amp-carousel/validator-amp-carousel.protoascii
  validator/engine/validator_test.js
  validator/testdata/amp4email_feature_tests/anchor.out
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#24321 🐛Fix facebook loader for comments, page.
  build-system/dep-check-config.js
  build-system/sources.js
Labels: cla: yes

#23980 ✨ Create a library to embed AMP stories
  build-system/tasks/helpers.js
  bundles.config.js
  examples/amp-story/embed.html
  src/amp-story-embed.js
Labels: cla: yes

#24343 🐛 Fix regression for analytics with custom event name
  extensions/amp-analytics/0.1/events.js
  extensions/amp-video-iframe/0.1/amp-video-iframe.js
  extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
  src/service/video-manager-impl.js
  src/video-interface.js
  test/manual/amp-video.amp.html
Labels: cla: yes

#24316 History: Defend against bad "historyPopped" data
  extensions/amp-bind/0.1/amp-state.js
  src/service/history-impl.js
  test/unit/test-history.js
Labels: cla: yes

#24350 Document that amp-carousel autoplay stops on interaction
  extensions/amp-carousel/0.1/amp-carousel.md
  extensions/amp-carousel/amp-carousel.md
Labels: cla: yes

#24342 Ramp up new loaders to 100%
  build-system/global-configs/prod-config.json
  test/visual-diff/visual-tests
Labels: cla: yes

#24336 🏗 Move all dev / test server files to `build-system/server/`
  .eslintignore
  build-system/config.js
  build-system/pr-check/build-targets.js
  build-system/server/amp-cors.js
  build-system/server/amp4test.js
  build-system/server/app-index/amphtml-helpers.js
  build-system/server/app-index/api/api.js
  build-system/server/app-index/basepath-mappings.js
  build-system/server/app-index/boilerplate.js
  build-system/server/app-index/components/main.js
  build-system/server/app-index/document-modes.js
  build-system/server/app-index/file-list.js
  build-system/server/app-index/form.js
  build-system/server/app-index/header-links.js
  build-system/server/app-index/html.js
  build-system/server/app-index/index.js
  build-system/server/app-index/main.css
  build-system/server/app-index/proxy-form.js
  build-system/server/app-index/regex.js
  build-system/server/app-index/settings.js
  build-system/server/app-index/template.js
  build-system/server/app-index/test/helpers.js
  build-system/server/app-index/test/test-amphtml-helpers.js
  build-system/server/app-index/test/test-file-list.js
  build-system/server/app-index/test/test-html.js
  build-system/server/app-index/test/test-self.js
  build-system/server/app-index/test/test-template.js
  build-system/server/app-index/test/test.js
  build-system/server/app-index/url.js
  build-system/server/app-index/util/listing.js
  build-system/server/app-utils.js
  build-system/server/app-video-testbench.js
  build-system/server/app.js
  build-system/server/lazy-build.js
  build-system/server/recaptcha-router.js
  build-system/server/routes/a4a-envelopes.js
  build-system/server/routes/analytics.js
  build-system/server/routes/list.js
  build-system/server/routes/test.js
  build-system/server/routes/user-location.js
  build-system/server/server-a4a-template.html
  build-system/server/server-inabox-template.html
  build-system/server/shadow-viewer.js
  build-system/server/test-server.js
  build-system/tasks/karma.conf.js
  build-system/tasks/pr-deploy-bot-utils.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/serve.js
Labels: WG: infra, cla: yes

#24348 Fix return of non-granting entitlements
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Labels: cla: yes

#24355 Add a link to analytics blogpost on amp.dev
  extensions/amp-story/amp-story-analytics.md
Labels: cla: yes

#24356 🚮 Stop including eid that had been used to force enabling of fast-fetch…
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#24351 Skip failing tests.
  extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js
Labels: cla: yes

#24301 🐛Avoid carousel flickering on iOS.
  extensions/amp-base-carousel/0.1/child-layout-manager.js
  extensions/amp-base-carousel/0.1/test/test-child-layout-manager.js
  extensions/amp-carousel/0.2/amp-carousel.js
Labels: cla: yes

#24271 🎇Story Ads: Development mode
  build-system/dep-check-config.js
  examples/amp-story/ad-development.html
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test/story-mock.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
  src/utils/array.js
Labels: cla: yes

#24370 🚮 Delete two unused methods from BaseElement
  src/base-element.js
Labels: cla: yes

#24365 Revert "🐛Prevent automatic sizing for amp-imgs with intrinsic layout"
  builtins/amp-img.js
  test/unit/test-amp-img.js
Labels: cla: yes

#24362 📖 Add link to amp-autocomplete example
  extensions/amp-autocomplete/amp-autocomplete.md
Labels: cla: yes

#24363 📖 Fix rendering of amp-autocomplete docs
  extensions/amp-autocomplete/amp-autocomplete.md
Labels: cla: yes

#24290 📖 Clarify autoexpansion of amp-lists overflow element
  extensions/amp-list/amp-list.md
Labels: cla: yes

#24330 🔥🐛update yahoonativeads script and example [amp-embed type=yahoonativeads]
  ads/yahoonativeads.js
  ads/yahoonativeads.md
  examples/ads.amp.html
Labels: cla: yes

#23632 Introduce an alternative implementation of resources service for inabox
  ads/google/a4a/utils.js
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  build-system/server/app.js
  src/friendly-iframe-embed.js
  src/inabox/inabox-mutator.js
  src/inabox/inabox-resources.js
  src/inabox/inabox-services.js
  src/service/performance-impl.js
  src/service/resources-impl.js
  test/unit/inabox/test-inabox-mutator.js
  test/unit/inabox/test-inabox-resources.js
Labels: cla: yes

#24327 🔥🐛update readmo script and example [amp-embed type=readmo]
  ads/readmo.js
  ads/readmo.md
  examples/ads.amp.html
Labels: cla: yes

#24280 ♻️ Move layoutScheduleTime to CustomElement class
  src/base-element.js
  src/custom-element.js
Labels: cla: yes

#24369 Add environment variable to RTV experiment
  build-system/global-configs/experiments-config.json
Labels: cla: yes

#24381 🏗 Increase duration for which Sauce VMs are allowed to run tests
  build-system/tasks/karma.conf.js
Labels: WG: infra, cla: yes

#24384 🏗 Remove unnecessary `process.env` references in `build-system/`
  build-system/amp.extern.js
  build-system/server/amp4test.js
  build-system/server/app-index/index.js
  build-system/server/app-utils.js
  build-system/server/app-video-testbench.js
  build-system/server/app.js
  build-system/server/routes/a4a-envelopes.js
  build-system/tasks/lint.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/serve.js
  build-system/tasks/visual-diff/index.js
Labels: WG: infra, cla: yes

#24379 Pure renaming. Create resources-interface.js, owners-interface.js, mu…
  ads/google/a4a/utils.js
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-animation/0.1/web-animations.js
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/form-validators.js
  extensions/amp-fx-collection/0.1/providers/fx-provider.js
  extensions/amp-next-page/0.1/next-page-service.js
  extensions/amp-story/0.1/amp-story-info-dialog.js
  extensions/amp-story/1.0/amp-story-affiliate-link.js
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-info-dialog.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/progress-bar.js
  extensions/amp-subscriptions/0.1/renderer.js
  src/custom-element.js
  src/friendly-iframe-embed.js
  src/inabox/inabox-mutator.js
  src/inabox/inabox-resources.js
  src/service/mutator-interface.js
  src/service/owners-impl.js
  src/service/owners-interface.js
  src/service/performance-impl.js
  src/service/resource.js
  src/service/resources-impl.js
  src/service/resources-interface.js
  src/service/standard-actions-impl.js
  src/services.js
  test/unit/test-resource.js
  test/unit/test-resources.js
Labels: cla: yes

#23588 🚮 Remove XML self-closing slash from rel=canonical link tags in validator example pages
  validator/webui/@polymer/webui-mainpage/webui-mainpage.html
Labels: cla: yes

#24394 🚮 Remove debugging statement from amp-consent visual-diff test
  examples/visual-tests/amp-consent/amp-consent.js
Labels: cla: yes

#24383 Re-enable amp-story-consent percy tests.
  examples/visual-tests/amp-story/amp-story-consent.html
  examples/visual-tests/amp-story/amp-story-consent.rtl.html
  test/visual-diff/visual-tests
Labels: cla: yes

#24174 🐛 Experiment for fixing height inconsistency between 3p and a4a paths for AdSense ads
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Labels: cla: yes

#24292 🐛Set up experiment for delegating responsive sizing from amp-auto-ads to network specific amp-ad implementation
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-auto-ads/0.1/amp-auto-ads.js
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
  extensions/amp-auto-ads/0.1/test/test-placement.js
Labels: cla: yes

#24401 clarified AMP applies CSS to overflow attribute
  extensions/amp-list/amp-list.md
Labels: cla: yes

#24331 🏗 build: Include file listing with dist
  build-system/tasks/dist.js
Labels: cla: yes

#24396 Story consent interactive tests.
  examples/visual-tests/amp-story/amp-story-consent.js
  test/visual-diff/visual-tests
Labels: cla: yes

#24347 [amp-story] Fix share link bug
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/functional-test-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  extensions/amp-story/1.0/test-e2e/test-amp-story-bookend.js
  extensions/amp-story/1.0/test-e2e/test-amp-story-share-menu.js
  src/clipboard.js
  test/manual/amp-story/amp-story.amp.html
  test/manual/amp-story/input-form.html
Labels: cla: yes

#24402 🐛 Ensure amp-mustache is version locked to v0.js
  src/runtime.js
  src/service/extensions-impl.js
Labels: cla: yes

#24373 Add environment type to experiment config
  build-system/global-configs/README.md
  build-system/global-configs/experiments-config.json
Labels: cla: yes

#23917 amp-consent :sparkles: :book: Add SourcePoint to CMPs list
  examples/cmp-vendors.amp.html
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/amp-consent.md
  extensions/amp-consent/cmps/sourcepoint.md
Labels: cla: yes

#24368 📈 Add custom analytics event for bookend clicks
  examples/amp-story/analytics.html
  examples/amp-story/bookendv1.json
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/bookend/bookend-component.js
  extensions/amp-story/1.0/bookend/components/article.js
  extensions/amp-story/1.0/bookend/components/bookend-component-interface.js
  extensions/amp-story/1.0/bookend/components/cta-link.js
  extensions/amp-story/1.0/bookend/components/heading.js
  extensions/amp-story/1.0/bookend/components/landscape.js
  extensions/amp-story/1.0/bookend/components/portrait.js
  extensions/amp-story/1.0/bookend/components/text-box.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
  extensions/amp-story/1.0/variable-service.js
Labels: cla: yes

#24406 🐛🔥📖make url required; update docs
  ads/readmo.js
  ads/readmo.md
  examples/ads.amp.html
Labels: cla: yes

#24415 Move ANALYTICS_VENDOR_SPLIT expiry back one month
  build-system/global-configs/experiments-config.json
Labels: cla: yes

#23344 Move out removeForChildWindow() from resources-impl.js
  src/friendly-iframe-embed.js
  src/service/resources-impl.js
  test/unit/test-friendly-iframe-embed.js
  test/unit/test-resources.js
Labels: cla: yes

#24380 Enable RTV experiment for inabox-resources-lite
  src/inabox/inabox-services.js
Labels: cla: yes

#22903 MPlayer AMP Extension
  build-system/dep-check-config.js
  bundles.config.js
  examples/amp-minute-media-player.amp.html
  extensions/amp-minute-media-player/0.1/amp-minute-media-player.js
  extensions/amp-minute-media-player/0.1/test/test-amp-minute-media-player.js
  extensions/amp-minute-media-player/0.1/test/validator-amp-minute-media-player.html
  extensions/amp-minute-media-player/0.1/test/validator-amp-minute-media-player.out
  extensions/amp-minute-media-player/OWNERS.yaml
  extensions/amp-minute-media-player/amp-minute-media-player.md
  extensions/amp-minute-media-player/validator-amp-minute-media-player.protoascii
Labels: cla: yes

#24389 🐛 ✅ 🚮fixed build errors in amp-nexxtv-player and added additional test
  extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js
Labels: cla: yes

#24420 Remove conflicting experiments-config
  build-system/global-configs/experiments-config.json
Labels: cla: yes

#24386 🏗 Lazy build by default during `gulp` and replace `--lazy_build` with `--eager_build`
  build-system/server/lazy-build.js
  build-system/tasks/build.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/serve.js
  contributing/getting-started-e2e.md
Labels: WG: infra, cla: yes

#24422 Skip flaky a4a integration test
  test/integration/test-amphtml-ads.js
Labels: cla: yes

#24123 Clean up uses of `aria-hidden` in amp-sidebar.
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
Labels: cla: yes

#24435 Fix test-amp-ad-3p.js in Chrome 77
  test/integration/test-amp-ad-3p.js
Labels: cla: yes

#24445 📖added information on overflow behavior
  extensions/amp-list/amp-list.md
Labels: cla: yes

#24452 Fix Document.referrer tests in Chrome 77
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  test/unit/test-url-replacements.js
Labels: cla: yes

#24439 Ensures story video has sources before playing to avoid early error.
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#24440 SwG Release 0.1.22.67
  extensions/amp-subscriptions/0.1/dialog.js
  extensions/amp-subscriptions/0.1/doc-impl.js
  extensions/amp-subscriptions/0.1/test/test-dialog.js
  src/service/fixed-layer.js
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#24463 cl/268074143 Revision bump for #22903
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#24450 📖Update documentation on layout intrinsic
  builtins/amp-img.md
  spec/amp-html-layout.md
Labels: cla: yes

#24458 📖 Fix typo
  extensions/amp-carousel/amp-carousel.md
Labels: cla: yes

#24434 🏗 Add a `--on_local_build` mode for `gulp bundle-size`
  build-system/tasks/bundle-size.js
Labels: WG: infra, cla: yes

#24472 🏗 Normalize RTV number before determining Brotli compressed size
  build-system/tasks/bundle-size.js
Labels: cla: yes

#24467 Make amp-list[diffable] valid
  extensions/amp-list/0.1/test/validator-amp-list.html
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/validator-amp-list.protoascii
Labels: cla: yes

#24482 🐛 SwG Release 0.1.22.68
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#24451 🐛Work around a Chrome layout bug introduced in Chrome 77.
  extensions/amp-loader/0.1/amp-loader.css
  extensions/amp-loader/0.1/spinner.js
Labels: cla: yes

#24471 Keep AMP_CONFIG writing in sync with production release script.
  build-system/tasks/helpers.js
Labels: cla: yes

#24466 🐛 exclude amp- prefixes from reserved class
  src/service/standard-actions-impl.js
  test/unit/test-standard-actions.js
Labels: cla: yes

#24478 🐛 amp-list[diffable]: Fit to initial content on layout
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#24465 🐛Fixes bug with Safari/Edge animations not resuming
  extensions/amp-animation/0.1/runners/native-web-animation-runner.js
Labels: cla: yes

#24498 🏗 Use the bundle-size app to store new sizes
  build-system/tasks/bundle-size.js
  package.json
  yarn.lock
Labels: cla: yes

#24468 🐛 CEv1: Only upgrade nodes if ownerDocument matches registry doc
  src/polyfills/custom-elements.js
Labels: cla: yes

#24511 🏗🐛 Use correct endpoint to store bundle-sizes
  build-system/tasks/bundle-size.js
Labels: cla: yes

#24513 Turn custom-elements-v1 experiment off in canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#24514 🏗🐛 Fix wrong type for bundle-size storage
  build-system/tasks/bundle-size.js
Labels: cla: yes

#24515 🐛 Fix existing syntax errors in OWNERS.yaml files
  OWNERS.yaml
  css/OWNERS.yaml
  extensions/amp-access-laterpay/OWNERS.yaml
  test/OWNERS.yaml
Labels: cla: yes

#24447 Move out ini-load related logic to separate file.
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
  build-system/dep-check-config.js
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-analytics/0.1/test/test-analytics-root.js
  src/friendly-iframe-embed.js
  src/inabox/utils.js
  src/ini-load.js
  src/service/performance-impl.js
  src/service/resources-impl.js
  test/integration/test-amphtml-ads.js
  test/unit/inabox/test-utils.js
  test/unit/test-friendly-iframe-embed.js
  test/unit/test-ini-load.js
  test/unit/test-performance.js
  test/unit/test-resources.js
Labels: cla: yes

#23447 ✨ SmileWanted new ad code support
  3p/integration.js
  ads/_config.js
  ads/smilewanted.js
  ads/smilewanted.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#24461 🐛Remove erroneous timeout warning
  extensions/amp-a4a/0.1/real-time-config-manager.js
Labels: cla: yes

#24304 ♻️ Update targeted domain for AdYouLike AMP entry point
  ads/_config.js
  ads/adyoulike.js
Labels: cla: yes

#24517 🏗 Update ownership rules for extensions/**/*-player.js
  extensions/OWNERS.yaml
  extensions/amp-3q-player/OWNERS.yaml
  extensions/amp-brid-player/OWNERS.yaml
  extensions/amp-delight-player/OWNERS.yaml
  extensions/amp-kaltura-player/OWNERS.yaml
  extensions/amp-minute-media-player/OWNERS.yaml
  extensions/amp-nexxtv-player/OWNERS.yaml
  extensions/amp-o2-player/OWNERS.yaml
  extensions/amp-ooyala-player/OWNERS.yaml
  extensions/amp-reach-player/OWNERS.yaml
  extensions/amp-springboard-player/OWNERS.yaml
  extensions/amp-wistia-player/OWNERS.yaml
Labels: cla: yes

#24518 🏗 Update ownership rules for validator files
  OWNERS.yaml
  validator/OWNERS.yaml
Labels: cla: yes

#24509 New Ad Server to join AMP: AdGlare
  3p/integration.js
  ads/_config.js
  ads/adglare.js
  ads/adglare.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#24529 Temporary fix: Disable custom element experiment check because it happens too early
  src/polyfills.js
Labels: cla: yes

#24473 ✨amp-autocomplete: Add "item" attribute to specify the relevant property of a datasource
  examples/autocomplete-states.example.json
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
  extensions/amp-autocomplete/amp-autocomplete.md
  extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
Labels: cla: yes

#24544 🏗 Prevent corrupt Travis caches
  .travis.yml
Labels: cla: yes

#24523 Add OWNERS.yaml for subscriptions project
  third_party/subscriptions-project/OWNERS.yaml
Labels: cla: yes

#24527 Soft DNS rewrite for various dev envelops
  build-system/server/app.js
  package.json
  yarn.lock
Labels: cla: yes

#24500 🐛 Message extraction: Fallback on unserialize objects
  src/log.js
Labels: cla: yes

#24501 Change how carousel queuing of layout visibility works for iOS.
  build-system/dep-check-config.js
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/carousel-accessibility.js
  extensions/amp-base-carousel/0.1/carousel-events.js
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-base-carousel/0.1/child-layout-manager.js
  extensions/amp-base-carousel/0.1/test/test-child-layout-manager.js
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-carousel/0.2/test/test-type-slides.js
Labels: cla: yes

#24005 🐛✨Snowplow Analytics: Fix timezone/timestamp issue and add document size field
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/snowplow.js
Labels: cla: yes

#24549 🐛 Logging message toString() blunder fix
  src/log.js
Labels: cla: yes

#24561 Revert "Soft DNS rewrite for various dev envelops"
  build-system/server/app.js
  package.json
  yarn.lock
Labels: cla: yes

#24551 ♻️ Redefine custom-elements-v1 as an RTV experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/experiments-config.json
  src/friendly-iframe-embed.js
  src/polyfills.js
  tools/experiments/experiments.js
Labels: cla: yes

#24552 Remove BaseElement.getDpr API
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-image-lightbox/0.1/amp-image-lightbox.js
  extensions/amp-image-lightbox/0.1/test/test-amp-image-lightbox.js
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
  src/base-element.js
  src/window-interface.js
Labels: cla: yes

#24448 amp-script: Support setState/getState in worker
  examples/amp-script/example.amp.html
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
  package.json
  yarn.lock
Labels: cla: yes

#24545 Use tagname for creating story embeds
  examples/amp-story/embed.html
  src/amp-story-embed.js
Labels: cla: yes

#24563 🏗✨ Add Mac OS support for the Sauce Labs Proxy launcher script
  .gitignore
  build-system/sauce_connect/start_sauce_connect.sh
  contributing/TESTING.md
Labels: WG: infra, cla: yes

#24562 Skip flaky "more real ads" test in test-amphtml-ads.js
  test/integration/test-amphtml-ads.js
Labels: cla: yes

#24573 Update amp-script owners
  extensions/amp-script/OWNERS.yaml
Labels: cla: yes

#24586 Make JS URLs more robust in local testing
  build-system/server/app.js
Labels: cla: yes

#24587 Change experiment environment
  build-system/global-configs/experiments-config.json
Labels: cla: yes

#24584 📖added src info for emails
  builtins/amp-img.md
  extensions/amp-anim/amp-anim.md
Labels: cla: yes

#24595 🏗 Only store new bundle-size on `master` branch
  build-system/tasks/bundle-size.js
  build-system/travis.js
Labels: cla: yes

#24596 Validator Rollup
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
  validator/validator-main.protoascii
Labels: Category: Validator, WG: caching, cla: yes

#24535 🐛 Added missing URL to 'Analytics Vendors' link
  extensions/amp-analytics/amp-analytics.md
Labels: Component: amp-analytics, Related to: Documentation, WG: analytics, cla: yes

#24597 🏗 Reorganize `dist()`
  build-system/tasks/dist.js
  build-system/tasks/helpers.js
Labels: WG: infra, cla: yes

#24426 📖 Use inline examples for amp-facebook docs
  extensions/amp-facebook/amp-facebook.md
Labels: cla: yes

#24614 ✨ SwG release 0.1.22.69
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#24604 Better amp-script docs
  extensions/amp-script/amp-script.md
Labels: cla: yes

#24598 Add validator test files to wg-caching owners
  OWNERS.yaml
Labels: WG: caching, cla: yes

#24613 🏗 Run Travis integration tests on Sauce Labs with 2 different commands
  build-system/pr-check/remote-tests.js
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/runtime-test-base.js
Labels: cla: yes

#24616 Introduce a new experiment constant list
  build-system/build.conf.js
  build-system/global-configs/experiments-const.json
Labels: cla: yes

#24548 📈 AmpStoryEventTracker & Integration tests
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-analytics/0.1/events.js
  extensions/amp-analytics/0.1/instrumentation.js
  extensions/amp-analytics/0.1/test/test-events.js
  test/integration/test-amp-story-analytics.js
Labels: cla: yes

#24619 🏗 Specify owners for files in the repo's root directory
  OWNERS.yaml
Labels: cla: yes

#24459 Update ix.md
  ads/ix.md
Labels: cla: no

#24494 Set flexible ad slot z-index to 11.
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#24603 Fix INABOX_LITE resources ready-scan signal.
  src/inabox/inabox-resources.js
  src/ini-load.js
  src/service/resources-impl.js
  src/service/resources-interface.js
  test/integration/test-amphtml-ads.js
Labels: cla: yes

#24528 Add e2e test for amp-ad-exit
  build-system/tasks/e2e/functional-test-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  extensions/amp-ad-exit/0.1/test-e2e/test-amp-ad-exit.js
  test/fixtures/e2e/amphtml-ads/amp-ad-exit.amp.html
Labels: cla: yes

#24638 Skip flaky story analytics integration tests
  test/integration/test-amp-story-analytics.js
Labels: cla: yes

#24602 ✨ Add support for the SHE Media ad network.
  3p/integration.js
  ads/_config.js
  ads/shemedia.js
  ads/shemedia.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#24642 📖 Rephrase how lightbox-gallery disables auto-lightbox
  spec/auto-lightbox.md
Labels: cla: yes

#24623 🏗 Follow up changes to integration tests on sauce labs
  build-system/pr-check/remote-tests.js
  build-system/tasks/report-test-status.js
  build-system/tasks/runtime-test/helpers.js
Labels: Type: Bug, WG: infra, cla: yes

#24641 Fixed unused-private-field lint rule to avoid breaking it on additional assignments
  build-system/eslint-rules/unused-private-field.js
Labels: cla: yes

#24648 🏗 Make `nailgun` server stoppage a time-bound operation and log errors if any
  build-system/tasks/nailgun.js
Labels: WG: infra, cla: yes

#24526 Handling a4a envelop crash
  build-system/server/routes/a4a-envelopes.js
Labels: cla: yes

#24622 `doPass` is an overloaded method name in resources-impl.js. Rename one of them to `doWork`
  src/service/resources-impl.js
Labels: cla: yes

#24656 Remove globalDocumentState from vsync
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  src/service/vsync-impl.js
  test/unit/test-vsync.js
Labels: cla: yes

#24644 ✅ Try unflaking amp-story-analytics integration test
  test/integration/test-amp-story-analytics.js
Labels: cla: yes

#24636 🐛Fix loader failing to render logo / color for amp-pinterest.
  extensions/amp-pinterest/0.1/amp-pinterest.js
Labels: cla: yes

#24658 ✅ Skip BTF integration tests
  test/integration/test-amphtml-ads.js
Labels: cla: yes

#24681 Upgrade DOMPurify to 2.0.2
  package.json
  yarn.lock
Labels: cla: yes

#24660 Remove globalDocumentState service
  build-system/tasks/presubmit-checks.js
  src/service/core-services.js
  src/service/document-state.js
  src/services.js
  test/unit/test-activity.js
  test/unit/test-cid.js
  test/unit/test-custom-element-registry.js
  test/unit/test-document-state.js
  test/unit/test-runtime.js
  test/unit/test-viewer.js
  test/unit/test-viewport-binding.js
  test/unit/test-viewport.js
Labels: cla: yes

#24599 🏗 Updates existing OWNERS.yaml files with brace-set and modifier syntax1
  OWNERS.yaml
  extensions/OWNERS.yaml
Labels: cla: yes

#24324 🐛Experiment flag to use amp-carousel 0.2 in amp-lightbox-gallery
  examples/article-with-lightbox-2.0-gallery.amp.html
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-carousel/0.2/amp-carousel.css
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
  tools/experiments/experiments.js
Labels: cla: yes

#24645 🐛 amp-autocomplete: Fetch remote data after first user interaction
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Labels: cla: yes

#24686 🏗 Allow retries for e2e test setup and set retries to 1
  build-system/tasks/e2e/describes-e2e.js
Labels: cla: yes

#24689 📖 Update amp-autocomplete documentation
  extensions/amp-autocomplete/amp-autocomplete.md
Labels: cla: yes

#24688 Updating the amp-story owners file.
  extensions/amp-story/OWNERS.yaml
Labels: cla: yes

#24695 ✨ SwG release 0.1.22.70
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#24698 Add OWNERS file to /src/inabox/ folder
  src/inabox/OWNERS.yaml
Labels: cla: yes

#24102 Adding support for amp_ad puffnetwork
  3p/integration.js
  ads/_config.js
  ads/puffnetwork.js
  ads/puffnetwork.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#24700 Fix inabox viewport
  src/inabox/inabox-viewport.js
Labels: cla: yes

#24635 🐛Story Ads: Don't require outlink meta tag
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
Labels: cla: yes

#24670 Use SameSite=None for canary cookie.
  src/cookies.js
  tools/experiments/experiments.js
Labels: cla: yes

#24571 🚮Cleanup for the new loaders.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  css/ampshared.css
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-ad/0.1/amp-ad-custom.js
  extensions/amp-ad/0.1/amp-ad-ui.js
  src/custom-element.js
  src/loader.js
  test/manual/loaders.amp.html
  test/unit/test-custom-element.js
  tools/experiments/experiments.js
Labels: cla: yes

#24620 ✨Callout vendor update: adding gdpr_consent and account to Prebid Server urls
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#24717 Do not trigger slideChange on the initial render.
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-carousel/0.2/test/test-type-slides.js
Labels: cla: yes
