Repository ampproject/amphtml, pull requests merged in 2019-08, with the labels that each got.

#23589 localStorage usage Guideline
  build-system/tasks/presubmit-checks.js
  spec/amp-localstorage.md
Labels: cla: yes

#23620 Launch AdSense Canonical Impl Support
  3p/integration.js
  ads/_a4a-config.js
  ads/_config.js
  ads/google/adsense.js
  ads/google/test/test-adsense.js
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  build-system/tasks/runtime-test/helpers.js
  extensions/amp-ad-network-adsense-impl/0.1/adsense-a4a-config.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-adsense-a4a-config.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
  extensions/amp-auto-ads/0.1/test/test-ad-strategy.js
  extensions/amp-auto-ads/0.1/test/test-placement.js
  test/unit/3p/test-ampcontext-integration.js
Labels: cla: yes

#23592 delete ad server in the preconnect list
  ads/_config.js
Labels: cla: yes

#23626 🏗 Fix e2e headless mode and make e2e job blocking again
  .travis.yml
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/yarn.lock
Labels: cla: yes

#23289 ✨ Add experiment param in GA pageview request
  extensions/amp-analytics/0.1/config.js
Labels: cla: yes

#23613 ✨ Dont compile test vendor JSONs
  build-system/tasks/vendor-configs.js
Labels: cla: yes

#23631 🐛 Correctly interpolate expanded log messages
  src/log.js
  test/unit/test-log.js
Labels: cla: yes

#23558 🏗 Add lint rule for unload listener
  .eslintrc
  build-system/eslint-rules/no-unload-listener.js
  extensions/amp-analytics/0.1/events.js
  extensions/amp-viewer-integration/0.1/amp-viewer-integration.js
  src/service/performance-impl.js
Labels: cla: yes

#23633 More refactoring of resources-impl to owners-impl
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/0.1/test/test-scrollable-carousel.js
  extensions/amp-carousel/0.1/test/test-slidescroll.js
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
  extensions/amp-fx-flying-carpet/0.1/test/test-amp-fx-flying-carpet.js
  extensions/amp-image-slider/0.1/amp-image-slider.js
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  extensions/amp-pan-zoom/0.1/test/test-amp-pan-zoom.js
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
  extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
  extensions/amp-story/0.1/test/test-amp-story.js
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-page-attachment.js
  src/base-element.js
  src/custom-element.js
  src/service/owners-impl.js
  src/service/resources-impl.js
  test/unit/test-custom-element.js
Labels: cla: yes

#23628 Add an AMPHTML ad example that uses amp-bind.
  examples/amphtml-ads/many-ads.host.html
  examples/amphtml-ads/video-ad.a4a.html
Labels: cla: yes

#23652 Sever remaining owners service method from resources
  contributing/building-an-amp-extension.md
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
  extensions/amp-image-slider/0.1/amp-image-slider.js
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
  extensions/amp-story/1.0/amp-story-page-attachment.js
  src/base-element.js
  src/service/owners-impl.js
  src/service/resources-impl.js
Labels: cla: yes

#23627 ♻️Refactor new loaders code.
  extensions/amp-facebook/facebook-loader.js
  extensions/amp-loader/0.1/amp-loader.css
  extensions/amp-loader/0.1/amp-loader.js
  extensions/amp-pinterest/0.1/amp-pinterest.js
  extensions/amp-twitter/0.1/amp-twitter.js
  src/base-element.js
  src/custom-element.js
Labels: cla: yes

#23667 Change the new loaders spinner implementation.
  extensions/amp-loader/0.1/amp-loader.css
  extensions/amp-loader/0.1/amp-loader.js
  extensions/amp-loader/0.1/spinner.js
  src/utils/math.js
Labels: cla: yes

#23666 More ad examples, covering amp-fit-text, amp-animation, amp-social-sh…
  build-system/app.js
  examples/amphtml-ads/animation-ad.a4a.html
  examples/amphtml-ads/fake-memory.host.html
  examples/amphtml-ads/gif-ad.a4a.html
  examples/amphtml-ads/many-ads.host.html
  examples/amphtml-ads/slides-ad.a4a.html
  examples/amphtml-ads/text-ad.a4a.html
  examples/amphtml-ads/visibility-ad.a4a.html
  examples/amphtml-ads/visibility.host.html
Labels: cla: yes

#23684 🐛Gulp watch: watch all sub folders
  build-system/tasks/extension-helpers.js
Labels: cla: yes

#23681 Turn the share button into a self-link for each STAMP
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/test/test-amp-story-system-layer.js
Labels: cla: yes

#23700 Remove reference to inabox lite
  build-system/app-utils.js
Labels: cla: yes

#23703 Fix a test isolation problem caused by the use of Object.defineProperty w/o restore.
  test/unit/test-viewport.js
  testing/describes.js
Labels: cla: yes

#23690 Synchronize calls to reportAllExpectedTests()
  build-system/pr-check/checks.js
Labels: cla: yes

#23473 Actual amp-ad functionality in amp-ad-network-fake-impl
  extensions/amp-ad-network-cloudflare-impl/0.1/data/fake_a4a.json
  extensions/amp-ad-network-fake-impl/0.1/amp-ad-metadata-transformer.js
  extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
  extensions/amp-ad-network-fake-impl/0.1/external-reorder-head-transformer.js
  extensions/amp-ad-network-fake-impl/0.1/test/test-amp-ad-metadata-transformer.js
  extensions/amp-ad-network-fake-impl/0.1/test/test-amp-ad-network-fake-impl.js
  extensions/amp-ad-network-fake-impl/0.1/test/test-external-reorder-head-transformer.js
Labels: cla: yes

#23695 🐛 Fix race condition when opening/closing sidebar.
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
  src/modal.js
Labels: cla: yes

#23362 ✨ Dynamically load vendor configs
  build-system/app.js
  build-system/dep-check-config.js
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/vendors.js
  src/service/extension-location.js
Labels: cla: yes

#23598 Support amp-list > [fetch-error]
  build-system/tasks/create-golden-css/css/main.css
  css/ampshared.css
  extensions/amp-list/0.1/amp-list.css
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/validator-amp-list.protoascii
Labels: cla: yes

#23714 Skip flaky xhr test
  test/unit/test-xhr.js
Labels: cla: yes

#23692 Update amp-instagram to new embed version and remove certain classes of jank
  css/ampdoc.css
  extensions/amp-instagram/0.1/amp-instagram.js
  extensions/amp-instagram/0.1/test/test-amp-instagram.js
  test/integration/test-released.js
Labels: cla: yes

#23682 Mark gplus share button as obsolete and don't render it.
  extensions/amp-social-share/0.1/amp-social-share-config.js
  extensions/amp-social-share/0.1/amp-social-share.js
  extensions/amp-social-share/0.1/test/test-amp-social-share.js
  extensions/amp-social-share/amp-social-share.md
Labels: cla: yes

#23715 Change all usages of Object.defineProperty to sandbox.defineProperty in tests
  extensions/amp-access/0.1/test/test-amp-access-iframe.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-rtc.js
  extensions/amp-form/0.1/test/test-amp-form-textarea.js
  extensions/amp-form/0.1/test/test-form-validators.js
  extensions/amp-form/0.1/test/test-form-verifiers.js
  extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
  extensions/amp-web-push/0.1/test/test-web-push-permission-dialog.js
  extensions/amp-web-push/0.1/test/test-web-push-service.js
  extensions/amp-youtube/0.1/test/test-amp-youtube.js
  test/unit/inabox/test-inabox-messaging-host.js
  test/unit/test-chunk.js
  test/unit/test-custom-element.js
  test/unit/test-font-stylesheet-timeout.js
  test/unit/test-form.js
  test/unit/test-resource.js
  test/unit/test-runtime.js
  test/unit/test-viewport.js
  testing/describes.js
Labels: cla: yes

#23683 Validator rollup
  build-system/tasks/presubmit-checks.js
  validator/engine/validator-in-browser.js
  validator/engine/validator.js
  validator/engine/validator_test.js
Labels: cla: yes

#23717 🐛 Fix unit test paths
  build-system/config.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
Labels: WG: infra, cla: yes

#23722 Introduce sandbox.deleteProperty
  test/unit/test-dom.js
  testing/describes.js
Labels: cla: yes

#23721 🐛 Do not use `origin/master` during Travis builds
  build-system/git.js
  build-system/pr-check/utils.js
Labels: WG: infra, cla: yes

#23707 Re-enable skipped test in test-friendly-iframe-embed
  test/unit/test-friendly-iframe-embed.js
Labels: cla: yes

#23698 🐛 Use source relative URLs in navigateTo
  src/service/navigation.js
  src/service/url-impl.js
  test/unit/test-navigation.js
  testing/fake-dom.js
Labels: cla: yes

#23705 Fix PWA example script
  examples/pwa/pwa.js
Labels: cla: yes

#23697 🖍 Make both bottom corners of info dialog rounded
  extensions/amp-story/1.0/amp-story-info-dialog.css
Labels: cla: yes

#23693 🏗📖 Delete SERVING.md
  build-system/SERVING.md
Labels: cla: yes

#23730 📖 Updates AmpStoryBaseLayer description
  extensions/amp-story/0.1/amp-story-base-layer.js
Labels: cla: yes

#23739 🐛 Clean up `$weak$` files after single pass compilation
  build-system/compile/single-pass.js
Labels: WG: infra, cla: yes

#23733 Introduce video-ad-start/end event
  extensions/amp-analytics/amp-video-analytics.md
  src/service/video-manager-impl.js
  src/video-interface.js
  test/manual/amp-ima-video.html
Labels: cla: yes

#23691 amp-script: Script gadget mitigation
  build-system/amp.extern.js
  examples/amp-script/hello-world.amp.html
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
  extensions/amp-script/amp-script.md
  src/polyfills/fetch.js
  src/service/xhr-impl.js
  test/manual/amp-script/test1.amp.html
  test/unit/test-xhr-fetch-polyfill.js
  validator/testdata/feature_tests/amp_meta_tags.html
  validator/testdata/feature_tests/amp_meta_tags.out
  validator/validator-main.protoascii
Labels: WG: runtime, cla: yes

#23611 ✨ Add RTV serve_mode
  build-system/app-utils.js
  build-system/app.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/serve.js
  contributing/TESTING.md
  contributing/getting-started-e2e.md
Labels: cla: yes

#23470 amp-list: [diffable]
  examples/amp-list.amp.html
  examples/bind/list.amp.html
  examples/list.example.json
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-mustache/0.1/amp-mustache.js
  extensions/amp-mustache/0.2/amp-mustache.js
  package.json
  src/purifier.js
  src/sanitation.js
  src/sanitizer.js
  test/unit/test-purifier.js
  test/unit/test-sanitizer.js
  tools/experiments/experiments.js
  yarn.lock
Labels: cla: yes

#23736 Don't ignore falsy values in amp-state
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-bind/0.1/bind-impl.js
Labels: WG: runtime, cla: yes

#23741 🏗🚮 Delete `gulp test`
  build-system/tasks/runtime-test/index.js
  gulpfile.js
Labels: WG: infra, cla: yes

#23743 🏗🚮 Delete deprecation warning for `gulp lint --local-changes`
  build-system/tasks/lint.js
Labels: WG: infra, cla: yes

#23696 Abstract draggable drawer component.
  bundles.config.js
  extensions/amp-story/1.0/amp-story-draggable-drawer-header.css
  extensions/amp-story/1.0/amp-story-draggable-drawer.css
  extensions/amp-story/1.0/amp-story-draggable-drawer.js
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story-vertical.css
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#21540 Clean up test-amp-state.js
  extensions/amp-bind/0.1/test/test-amp-state.js
Labels: WG: runtime, cla: yes

#23723 🚀 Clean up video manager listeners on dispose
  src/service/video-manager-impl.js
Labels: cla: yes

#23687 Implement new loader for ads
  extensions/amp-ad/0.1/amp-ad-ui.js
  extensions/amp-loader/0.1/amp-loader.css
  extensions/amp-loader/0.1/amp-loader.js
  src/loader.js
  test/manual/loaders-new.amp.html
Labels: cla: yes

#23658 Add canvas support in amp-script
  examples/amp-script/amp-script-demo.js
  examples/amp-script/canvas.js
  examples/amp-script/example.amp.html
  extensions/amp-script/0.1/test/integration/test-amp-script.js
  extensions/amp-script/0.1/test/validator-amp-script.html
  extensions/amp-script/0.1/test/validator-amp-script.out
  extensions/amp-script/validator-amp-script.protoascii
  validator/validator-main.protoascii
Labels: cla: yes

#23749 🏗 Add missing return types in `build-system/`
  build-system/amp4test.js
  build-system/app-utils.js
  build-system/app.js
  build-system/babel-plugins/babel-plugin-is_dev-constant-transformer/index.js
  build-system/babel-plugins/babel-plugin-is_minified-constant-transformer/index.js
  build-system/compile/closure-compile.js
  build-system/compile/shorten-license.js
  build-system/ctrlcHandler.js
  build-system/eslint-rules/await-expect.js
  build-system/eslint-rules/no-deep-destructuring.js
  build-system/eslint-rules/private-prop-names.js
  build-system/exec.js
  build-system/tasks/ava.js
  build-system/tasks/babel-plugin-tests.js
  build-system/tasks/check-exact-versions.js
  build-system/tasks/clean.js
  build-system/tasks/css.js
  build-system/tasks/dep-check.js
  build-system/tasks/dev-dashboard-tests.js
  build-system/tasks/dist.js
  build-system/tasks/e2e/controller-promise.js
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/repl.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/generate-runner.js
  build-system/tasks/helpers.js
  build-system/tasks/json-check.js
  build-system/tasks/nailgun.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/process-3p-github-pr.js
  build-system/tasks/process-github-issues.js
  build-system/tasks/todos.js
  build-system/tasks/visual-diff/helpers.js
  build-system/tasks/visual-diff/index.js
Labels: WG: infra, cla: yes

#23754 Story video failure play vs error message.
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.css
  src/localized-strings.js
Labels: cla: yes

#23750 Overhaul Chunks implementation and avoid macro tasks before body is visible.
  src/amp.js
  src/chunk.js
  src/inabox/amp-inabox.js
  test/unit/test-chunk.js
Labels: cla: yes

#23762 amp-bind: Don't validate non-primitive expression results
  extensions/amp-bind/0.1/bind-evaluator.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-bind/0.1/test/test-bind-evaluator.js
  extensions/amp-bind/0.1/test/test-bind-expression.js
Labels: WG: runtime, cla: yes

#23766 🏗 Synchronize exit and fix logging on Travis for dev dashboard tests
  build-system/tasks/dev-dashboard-tests.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#23768 🏗 Speed up `browserify` while building the runtime and running tests
  build-system/compile/single-pass.js
  build-system/tasks/dep-check.js
  build-system/tasks/helpers.js
  build-system/tasks/karma.conf.js
Labels: WG: infra, cla: yes

#23752 Relaxes requirement that amp-sidebar be a direct child of body
  extensions/amp-sidebar/amp-sidebar.md
  extensions/amp-sidebar/validator-amp-sidebar.protoascii
Labels: cla: yes

#23764 Update visual-diff doc wrong link
  contributing/TESTING.md
Labels: cla: yes

#23748 Fix e2e doc command line example.
  build-system/tasks/e2e/README.md
Labels: cla: yes

#23727 🐛 Allow "binding" attribute in amp-list for emails
  extensions/amp-list/validator-amp-list.protoascii
Labels: Category: Validator, WG: amp4email, cla: yes

#23712 ♻️ Cid-impl test improvement
  test/unit/test-cid.js
Labels: cla: yes

#23706 🏗 Report brotli bundle-size
  build-system/tasks/bundle-size.js
  package.json
  yarn.lock
Labels: cla: yes

#23777 🏗✨ Add a `Version` section to the experiments page that links to the GitHub release
  build-system/tasks/dist.js
  tools/experiments/experiments.html
Labels: WG: infra, cla: yes

#23773 Updating default story sidebar width.
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#23751 ✅Repurpose test-3p-frame.js as a unit test
  3p/integration.js
  test/unit/3p/test-3p-frame.js
Labels: cla: yes

#23779 amp-img: Remove [srcset] when [src] is mutated
  builtins/amp-img.js
  extensions/amp-bind/amp-bind.md
  test/unit/test-amp-img.js
Labels: cla: yes

#23728 📖 Update email CSS spec to document filter and transition
  spec/email/amp-email-css.md
  spec/email/amp-email-format.md
Labels: Related to: Documentation, WG: amp4email, cla: yes

#23735 🐛Do not select hidden elements in amp-selector
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-selector/0.1/test/test-amp-selector.js
Labels: cla: yes

#23720 Add user warning to prevent tap actions registered on amp-accordion headers
  extensions/amp-accordion/0.1/amp-accordion.js
Labels: cla: yes

#23782 Re-enable amp-ad-custom test and isolate it
  test/integration/test-amp-ad-custom.js
Labels: cla: yes

#23789 🏗🐛Manually update `build-system/tasks/visual-diff/yarn.lock` to address security vulnerabilities
  build-system/tasks/visual-diff/yarn.lock
Labels: WG: infra, cla: yes

#23783 🏗🐛 Disable `no-duplicate-name-typedef` rule during on-the-fly IDE linting
  build-system/eslint-rules/no-duplicate-name-typedef.js
Labels: WG: infra, cla: yes

#23774 Remove built event and replace usage in flying carpet.
  extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
  src/amp-events.js
  src/service/resource.js
Labels: cla: yes

#23767 Various micro optimizations of the component boot flow.
  build-system/build.conf.js
  build-system/dep-check-config.js
  examples/lots-of-images.amp.html
  src/base-element.js
  src/friendly-iframe-embed.js
  src/polyfills.js
  src/polyfills/domtokenlist.js
  src/service.js
  src/service/ampdoc-impl.js
  test/unit/test-polyfill-domtokenlist-toggle.js
Labels: cla: yes

#23678 🐛: fix container bug & support white-label & rename streamrail to blade
  3p/integration.js
  ads/_config.js
  ads/blade.js
  ads/blade.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#23796 amp-bind: Add "global" reference
  extensions/amp-bind/0.1/bind-evaluator.js
  extensions/amp-bind/0.1/bind-expression.js
  extensions/amp-bind/0.1/bind-macro.js
  extensions/amp-bind/0.1/test/test-bind-evaluator.js
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#23780 Set the new loaders experiment to 1% of traffic.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#23761 Swipe down to close the bookend.
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/amp-story-draggable-drawer-header.css
  extensions/amp-story/1.0/amp-story-draggable-drawer.css
  extensions/amp-story/1.0/amp-story-draggable-drawer.js
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-vertical.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#23797 🐛 Disable closure compiler parallelism during local development
  build-system/compile/compile.js
Labels: WG: infra, cla: yes

#23746 Allow <use> with relative href in amp-mustache-0.2
  src/purifier.js
  test/unit/test-purifier.js
Labels: WG: runtime, cla: yes

#23393 Create amp-carousel 0.2 based on amp-base-carousel
  build-system/dep-check-config.js
  bundles.config.js
  extensions/amp-base-carousel/0.1/amp-base-carousel.css
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/carousel.css
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-base-carousel/0.1/child-layout-manager.js
  extensions/amp-base-carousel/0.1/test-e2e/helpers.js
  extensions/amp-base-carousel/0.1/test/test-child-layout-manager.js
  extensions/amp-carousel/0.2/amp-carousel.css
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-carousel/0.2/test/test-type-slides.js
  extensions/amp-carousel/validator-amp-carousel.protoascii
Labels: cla: yes

#23809 Move expiration date back to 2020
  build-system/build.conf.js
  build-system/global-configs/experiments-config.json
Labels: cla: yes

#23803 Change test-amp-ad-custom to use describes.integration
  build-system/amp4test.js
  test/fixtures/amp-ad-custom.html
  test/integration/test-amp-ad-custom.js
  test/integration/test-amp-ad-type-custom.js
Labels: cla: yes

#23656 fixed nativeroll's player collapse & resize bug
  ads/nativeroll.js
  examples/ads.amp.html
Labels: cla: yes

#23808 🏗 Add a way to opt out of Nailgun during `dist` and `check-types`
  build-system/compile/closure-compile.js
  build-system/tasks/check-types.js
  build-system/tasks/dist.js
  build-system/tasks/nailgun.js
Labels: WG: infra, cla: yes

#23525 📖 Remove duplicate <strong>
  extensions/amp-accordion/amp-accordion.md
Labels: cla: yes

#23770 Fix format identifier
  extensions/amp-fit-text/amp-fit-text.md
Labels: cla: yes

#23524 📖 Remove `expand` event from actions table
  extensions/amp-accordion/amp-accordion.md
Labels: cla: yes

#23701 📖 Split amp-story.md into multiple documents
  extensions/amp-story/amp-story-bookend.md
  extensions/amp-story/amp-story-cta-layer.md
  extensions/amp-story/amp-story-grid-layer.md
  extensions/amp-story/amp-story-page-attachment.md
  extensions/amp-story/amp-story-page.md
Labels: cla: yes

#22691 updated beta to launched
  extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
Labels: cla: yes

#23823 Fix linker-forwarding examples.
  extensions/amp-analytics/linker-id-forwarding.md
Labels: cla: yes

#22706 🐛 Fix link to the amp-iframe origin policy
  extensions/amp-analytics/0.1/transport.js
Labels: cla: yes

#22743 fixed links
  spec/amp-html-format.md
Labels: cla: yes

#22998 📖Fix invalid and unnecessary code block quotes in docs
  extensions/amp-mustache/amp-mustache.md
Labels: cla: yes

#23274 📖 Fix typos on linkers for analytics extension.
  extensions/amp-analytics/amp-analytics.md
  extensions/amp-analytics/linker-id-forwarding.md
Labels: cla: yes

#23294 Link to supported values for layout
  extensions/amp-script/amp-script.md
Labels: cla: yes

#23819 Fully launch inabox-css-cleanup
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  src/inabox/amp-inabox.js
  tools/experiments/experiments.js
Labels: cla: yes

#23456 amp-sidebar is supported in stories
  extensions/amp-sidebar/amp-sidebar.md
Labels: cla: yes

#23591 🧹 Badges
  README.md
Labels: cla: yes

#23806 Fix amp-date-picker closure compiler warnings
  build-system/compile/compile.js
  build-system/conformance-config.textproto
  extensions/amp-date-picker/0.1/date-picker-common.js
  extensions/amp-date-picker/0.1/react-utils.js
  extensions/amp-date-picker/0.1/single-date-picker.js
  extensions/amp-date-picker/0.1/wrappers/maximum-nights.js
Labels: cla: yes

#23807 🏗 Send the Travis job URL to the test status bot
  build-system/tasks/report-test-status.js
  build-system/travis.js
Labels: cla: yes

#23800 ✨Do not require amp-autocomplete to be a child of a form
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
  extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
Labels: cla: yes

#23826 Allow input[type] binding in AMP format
  extensions/amp-bind/0.1/test/validator-amp-bind.html
  extensions/amp-bind/0.1/test/validator-amp-bind.out
  validator/testdata/amp4email_feature_tests/amp_form.out
  validator/validator-main.protoascii
Labels: cla: yes

#23781 Increase play & error message font size.
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#23508 Add additional parameters for Gemius amp-analytics
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/gemius.js
Labels: cla: yes

#23792 🐛 Do not apply anchor mutator for internal navigation
  src/service/navigation.js
Labels: cla: yes

#23832 Add VARIANT doc to the variables list
  spec/amp-var-substitutions.md
Labels: cla: yes

#23821 🐛✨`<amp-carousel>` 0.2 minor fixes
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-carousel/validator-amp-carousel.protoascii
Labels: cla: yes

#23829 🐛Fixes `amp-imgur` issue with new id format
  examples/amp-imgur.amp.html
  extensions/amp-imgur/0.1/amp-imgur.js
  extensions/amp-imgur/0.1/test/test-amp-imgur.js
  extensions/amp-imgur/OWNERS.yaml
Labels: cla: yes

#23835 Validator rollup
  validator/build.py
  validator/engine/validator.js
  validator/testdata/feature_tests/dev_mode.html
  validator/testdata/feature_tests/dev_mode.out
  validator/testdata/feature_tests/no_dev_mode.html
  validator/testdata/feature_tests/no_dev_mode.out
  validator/validator-main.protoascii
Labels: Category: Validator, WG: caching, cla: yes

#23688 🐛 Fixes rendering children when using `amp-selector` 's toggle action
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-selector/0.1/test/test-amp-selector.js
Labels: cla: yes

#23818 Remove duplicated test in test-amp-ad-fake.js
  test/integration/test-amp-ad-fake.js
Labels: cla: yes

#23841 🏗 Report brotli bundle-size on pull requests
  build-system/tasks/bundle-size.js
Labels: cla: yes

#23699 Add inabox envelopes for friendly and safeframe.
  build-system/app-index/document-modes.js
  build-system/app-utils.js
  build-system/routes/a4a-envelopes.js
  build-system/server-inabox-template.html
Labels: cla: yes

#23671 Viewport refactoring preparation: remove unused methods and moved some public methods out.
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  src/dom.js
  src/service/viewport/viewport-impl.js
  test/unit/test-viewport.js
Labels: cla: yes

#23825 [amp-story] Hides tool tip next arrow overlay when you're on the last page
  examples/visual-tests/amp-story/amp-story-tooltip.html
  extensions/amp-story/1.0/amp-story-embedded-component.js
Labels: cla: yes

#23849 🏗Increase Karma timeout for Sauce Labs tests
  build-system/tasks/karma.conf.js
Labels: WG: infra, cla: yes

#23846 ✅Reorganize AMPHTML visual tests
  examples/visual-tests/amp-ad/amp-ad.html
  examples/visual-tests/amp-ad/amp-fie-text.html
  examples/visual-tests/amp-ad/amp-inabox-creative.html
  examples/visual-tests/amp-ad/amp-inabox-image.html
  examples/visual-tests/amp-ad/amp-inabox-text.html
  examples/visual-tests/amphtml-ads/adchoices.js
  examples/visual-tests/amphtml-ads/amp-fie-adchoices.html
  examples/visual-tests/amphtml-ads/amp-inabox-adchoices.html
  examples/visual-tests/amphtml-ads/amp-inabox-static.html
  examples/visual-tests/amphtml-ads/helpers.js
  examples/visual-tests/amphtml-ads/resource/amp-creative.html
  examples/visual-tests/amphtml-ads/resource/en.png
  examples/visual-tests/amphtml-ads/resource/icon.png
  examples/visual-tests/amphtml-ads/resource/image.html
  examples/visual-tests/amphtml-ads/resource/text.html
  examples/visual-tests/amphtml-ads/static.js
  test/visual-diff/visual-tests
Labels: cla: yes

#23830 Allow [itemprop] in amp-mustache-0.2
  src/sanitation.js
  test/unit/test-purifier.js
Labels: cla: yes

#23654 ♻️ Unify order of component's formats, correct spelling and add format
  extensions/amp-accordion/amp-accordion.md
  extensions/amp-analytics/amp-analytics.md
  extensions/amp-anim/amp-anim.md
  extensions/amp-audio/amp-audio.md
  extensions/amp-bind/amp-bind.md
  extensions/amp-carousel/amp-carousel.md
  extensions/amp-consent/amp-consent.md
  extensions/amp-fit-text/amp-fit-text.md
  extensions/amp-font/amp-font.md
  extensions/amp-form/amp-form.md
  extensions/amp-list/amp-list.md
  extensions/amp-mustache/amp-mustache.md
  extensions/amp-sidebar/amp-sidebar.md
  extensions/amp-twitter/amp-twitter.md
  extensions/amp-user-location/amp-user-location.md
  extensions/amp-video/amp-video.md
Labels: cla: yes

#23852 📖 Add missing quote to opening tip tag
  extensions/amp-next-page/amp-next-page.md
Labels: cla: yes

#23844 Fix navigation in PWAs / webpages saved to homescreen
  bundles.config.js
  examples/standalone.amp.html
  extensions/amp-standalone/0.1/amp-standalone.js
  extensions/amp-standalone/0.1/test/test-amp-standalone.js
  extensions/amp-standalone/README.md
  src/amp.js
  src/service/platform-impl.js
  src/services.js
  src/standalone.js
  test/unit/test-platform.js
Labels: cla: yes

#23744 🐛Adds capability for closing story share menu on escape key press.
  extensions/amp-story/1.0/amp-story-share-menu.js
  extensions/amp-story/1.0/test/test-amp-story-share-menu.js
Labels: cla: yes

#23831 ✨Make "layout=intrinsic" compatible with SSR
  src/custom-element.js
  test/unit/test-custom-element.js
Labels: cla: yes

#23843 🏗 Update brotli-size to v4.0.0 and fix breaking change to bundle-size.js
  build-system/tasks/bundle-size.js
  package.json
  yarn.lock
Labels: cla: yes

#23827 🧪Add Story Ads e2e testing
  build-system/tasks/e2e/functional-test-controller.js
  build-system/tasks/e2e/puppeteer-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads.js
  test/fixtures/e2e/amp-story-auto-ads/basic.html
Labels: cla: yes

#23208 📖Update navegg.md
  ads/navegg.md
Labels: cla: yes

#23811 amp-bind: Support special chars in strings
  build-system/conformance-config.textproto
  build-system/tasks/compile-expr.js
  extensions/amp-bind/0.1/bind-expr-impl.jison
  extensions/amp-bind/0.1/bind-expr-impl.js
  extensions/amp-bind/0.1/test/test-bind-expression.js
Labels: cla: yes

#23765 Support some new img attributes for those within noscript.
  validator/validator-main.protoascii
Labels: cla: yes

#23860 [amp-story] Fix copy-link-to-clipboard bug in Firefox
  src/clipboard.js
Labels: cla: yes

#23650 ♿ Prevent `amp-list` from losing focus when using keyboard controls
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list-load-more.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-list/amp-list.md
Labels: cla: yes

#23836 Revert the analytics linker hack to check href
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  test/manual/amp-analytics/analytics-linker.html
Labels: cla: yes

#23857 📖 Clean up outdated documentation in amp-story.md
  extensions/amp-story/amp-story.md
Labels: cla: yes

#23845 Correctness fixes for chunk queue
  src/chunk.js
  test/unit/test-chunk.js
Labels: cla: yes

#23870 🏗 Add check for python v2.7
  build-system/check-package-manager.js
Labels: WG: infra, cla: yes

#23861 Fix first page hint layer for RTL
  extensions/amp-story/1.0/amp-story-hint.css
Labels: cla: yes

#23044 Modifying AMP Form to include extended timeout for async UI input
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  src/async-input.js
Labels: cla: yes

#23399 🐛 Follow type changes from `layoutShift` to `layout-shift`.
  build-system/compile/compile.js
  build-system/layout-shift.extern.js
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#23775 Launch amp-script
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/validator-amp-script-not-origin-trial.html
  extensions/amp-script/0.1/test/validator-amp-script-not-origin-trial.out
  extensions/amp-script/0.1/test/validator-amp-script.html
  extensions/amp-script/0.1/test/validator-amp-script.out
  extensions/amp-script/validator-amp-script.protoascii
  validator/validator-main.protoascii
Labels: WG: runtime, cla: yes

#23868 Fix the regression caused by resources->owners refactoring
  src/custom-element.js
  test/unit/test-custom-element.js
Labels: cla: yes

#23665 ✅ Add an e2e test for amp-subscriptions-google.
  extensions/amp-subscriptions-google/0.1/test-e2e/test-amp-subscriptions-google.js
  test/fixtures/e2e/amp-subscriptions-google/swg.amp.html
  test/manual/amp-subscriptions-google/swg.amp.html
Labels: cla: yes

#22370 📖 Add tip to AMPHTML layout page that leads to a quick demonstration (and remove unneeded TOC)
  spec/amp-html-layout.md
Labels: cla: yes

#23805 Anti-test flakiness: Always cancel all timers between test runs
  src/service/timer-impl.js
  test/_init_tests.js
Labels: cla: yes

#23876 CSS reset for shadow trees.
  extensions/amp-story/1.0/amp-story-bookend.css
  extensions/amp-story/1.0/amp-story-consent.css
  extensions/amp-story/1.0/amp-story-draggable-drawer-header.css
  extensions/amp-story/1.0/amp-story-info-dialog.css
  extensions/amp-story/1.0/amp-story-shadow-reset.css
  extensions/amp-story/1.0/amp-story-share-menu.css
  extensions/amp-story/1.0/amp-story-viewport-warning-layer.css
Labels: cla: yes

#23873 Allow regular AMPHTML validation rules on amp-video within page-attachments.
  extensions/amp-story/1.0/test/validator-amp-story-video-controls.html
  extensions/amp-story/1.0/test/validator-amp-story-video-controls.out
  extensions/amp-video/validator-amp-video.protoascii
Labels: cla: yes

#23557 Optimize preconnect callbacks
  build-system/tasks/presubmit-checks.js
  src/custom-element.js
  test/unit/test-custom-element.js
Labels: cla: yes

#23874 Make cache cid timeout an expected error
  src/service/cache-cid-api.js
  src/service/viewer-impl.js
Labels: cla: yes

#23866 Update amp-date-display validation to allow template attribute
  extensions/amp-date-display/0.1/test/validator-amp-date-display.html
  extensions/amp-date-display/0.1/test/validator-amp-date-display.out
  extensions/amp-date-display/validator-amp-date-display.protoascii
Labels: cla: yes

#23897 🐛 Move `facebook-loader.js` into its component directory
  build-system/dep-check-config.js
  extensions/amp-facebook-comments/0.1/amp-facebook-comments.js
  extensions/amp-facebook-page/0.1/amp-facebook-page.js
  extensions/amp-facebook/0.1/amp-facebook.js
  extensions/amp-facebook/0.1/facebook-loader.js
Labels: WG: infra, WG: ui-and-a11y, cla: yes

#23883 Fix illegal invocation
  src/service/platform-impl.js
Labels: cla: yes
