Repository ampproject/amphtml, pull requests merged in 2019-04, with the labels that each got.

#21574 Reverse behavior of responsive auto ads experiment to ramp up to 95%
  extensions/amp-auto-ads/0.1/ad-network-config.js
  extensions/amp-auto-ads/0.1/test/test-ad-network-config.js
Labels: cla: yes

#21632 Lightbox enter/exit improvements
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  src/service/viewport/viewport-impl.js
Labels: cla: yes

#21523 ✨Started a config parser for the amp-experiment 1.0 format
  examples/experiment-1.0.amp.html
  extensions/amp-experiment/1.0/amp-experiment.js
  extensions/amp-experiment/1.0/test/test-amp-experiment.js
  extensions/amp-experiment/1.0/test/test-variant.js
  extensions/amp-experiment/1.0/variant.js
Labels: cla: yes

#21627 Launch auto-sizes to 50% of production
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21561 ✨ Removing prerender check to include SXG performance marks
  src/service/performance-impl.js
Labels: cla: yes

#21578 🏗 Workaround attempt for Sauce Labs timeout issues
  build-system/tasks/karma.conf.js
  package.json
  yarn.lock
Labels: cla: yes

#21645 Branching sharing option alignment.
  extensions/amp-story/1.0/amp-story-share.css
  extensions/amp-story/1.0/amp-story-share.js
Labels: cla: yes

#21301 Add orientation and device attributes on the amp-story element.
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#21533 🐛 Post-based identity bug fix
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-list/0.1/amp-list.js
  src/batched-json.js
  src/utils/xhr-utils.js
  test/unit/test-batched-json.js
  test/unit/utils/test-xhr-utils.js
Labels: cla: yes

#21539 Fix broken amp-mustache docs on ampproject.org
  extensions/amp-mustache/amp-mustache.md
Labels: cla: yes

#21655 Add mini-postmortem to cherry-pick template
  .github/ISSUE_TEMPLATE/cherry_pick_template.md
Labels: cla: yes

#21666 Disable embedded component desktop visual diff tests.
  test/visual-diff/visual-tests
Labels: cla: yes

#21591 🐛 amp-ima-video: Allow other kinds of `track` than just `subtitle` and also support `crossorigin`
  ads/google/imaVideo.js
  examples/ima-video.amp.html
  extensions/amp-ima-video/0.1/test/validator-amp-ima-video.html
  extensions/amp-ima-video/0.1/test/validator-amp-ima-video.out
  extensions/amp-ima-video/amp-ima-video.md
  validator/validator-main.protoascii
Labels: cla: yes

#21677 🏗 Fix test local changes bug
  build-system/tasks/runtime-test/helpers.js
Labels: cla: yes

#21362 ✨ Add additional analytics opt out mechanism. (#21163)
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/vendors/googleanalytics.js
Labels: cla: yes

#21669 📖 Small word fix for amp-var-substitutions.md
  spec/amp-var-substitutions.md
Labels: cla: yes

#21592 📖 Update Google Maps API Key
  extensions/amp-iframe/amp-iframe.md
Labels: cla: yes

#21664 ✨amp-recaptcha-input: Removed experiment from amp-recaptcha-input
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-input.js
Labels: cla: yes

#21663 ✨amp-experiment-v1: Created experiment for amp-experiment-v1
  build-system/dep-check-config.js
  extensions/amp-experiment/1.0/amp-experiment.js
  extensions/amp-experiment/1.0/test/test-amp-experiment.js
Labels: cla: yes

#21630 ✨ Create whitelist for amp-viewer-assistance.updateActionState actionStatus
  extensions/amp-viewer-assistance/0.1/amp-viewer-assistance.js
  extensions/amp-viewer-assistance/0.1/test/test-amp-viewer-assistance.js
  extensions/amp-viewer-assistance/amp-viewer-assistance.md
Labels: cla: yes

#21653 Roll forward "Delegate trust check... (#21553)"
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-access/0.1/test/test-amp-access.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-viewer-assistance/0.1/amp-viewer-assistance.js
  src/service/action-impl.js
  test/unit/test-action.js
Labels: cla: yes

#21569 Experiment flag for using amp-base-carousel from amp-lightbox-gallery.
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/carousel.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  tools/experiments/experiments.js
Labels: cla: yes

#21689 Use `scroll-snap-stop` for amp-base-carousel
  extensions/amp-base-carousel/0.1/carousel.css
Labels: cla: yes

#21512 Add "fetch-error" event for amp-list/amp-state
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-bind/0.1/test/test-amp-state.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-list/amp-list.md
  extensions/amp-viewer-assistance/0.1/amp-viewer-assistance.js
  extensions/amp-viewer-assistance/0.1/test/test-amp-viewer-assistance.js
  extensions/amp-viewer-assistance/amp-viewer-assistance.md
  spec/amp-actions-and-events.md
Labels: cla: yes

#21685 ✅validator tests: enable extension spec testing
  validator/engine/validator_test.js
Labels: cla: yes

#21643 🚀 amp-subscriptions prerender
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#21662 Pre templated stories API, and landscape half half template.
  examples/visual-tests/amp-story/amp-story-landscape-templates.html
  examples/visual-tests/amp-story/amp-story-landscape-templates.js
  examples/visual-tests/amp-story/img/cat1.jpg
  examples/visual-tests/amp-story/img/cat2.jpg
  extensions/amp-story/1.0/amp-story-templates.css
  extensions/amp-story/1.0/amp-story.css
  test/visual-diff/visual-tests
Labels: cla: yes

#21710 ✅ Re-enable embedded component desktop tests
  examples/visual-tests/amp-story/amp-story-tooltip-desktop.js
  test/visual-diff/visual-tests
Labels: Category: AMP Story, cla: yes

#21717 🐛 Update frontmatter for amp-story documentation.
  extensions/amp-story/amp-story.md
Labels: cla: yes

#21580 🏗 Add non blocking E2E tests to CI build
  .travis.yml
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/utils.js
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/index.js
  build-system/tasks/presubmit-checks.js
Labels: cla: yes

#21711 🚀 Watch devdash modules for server reload
  build-system/tasks/serve.js
Labels: cla: yes

#21679 data-credentials support for amp-story bookend
  extensions/amp-story/1.0/amp-story-request-service.js
  extensions/amp-story/1.0/test/test-amp-story-request-service.js
Labels: cla: yes

#21255 🐛 amp-recaptcha-input: Fixed single pass tests
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  test/integration/test-amp-recaptcha-input.js
Labels: cla: yes

#21683 ✨amp-experiment: Mutation Parser for 1.0 format
  examples/experiment-1.0.amp.html
  extensions/amp-experiment/1.0/amp-experiment.js
  extensions/amp-experiment/1.0/mutation-parser.js
  extensions/amp-experiment/1.0/test/test-amp-experiment.js
  extensions/amp-experiment/1.0/test/test-mutation-parser.js
Labels: cla: yes

#21285 ✨ add amp-link-rewriter extension
  build-system/dep-check-config.js
  bundles.config.js
  examples/amp-link-rewriter.html
  extensions/amp-link-rewriter/0.1/amp-link-rewriter.js
  extensions/amp-link-rewriter/0.1/config-options.js
  extensions/amp-link-rewriter/0.1/link-rewriter.js
  extensions/amp-link-rewriter/0.1/scope.js
  extensions/amp-link-rewriter/0.1/test/test-amp-link-rewriter.js
  extensions/amp-link-rewriter/0.1/test/test-helpers.js
  extensions/amp-link-rewriter/0.1/test/validator-amp-link-rewriter-no-script.html
  extensions/amp-link-rewriter/0.1/test/validator-amp-link-rewriter-no-script.out
  extensions/amp-link-rewriter/0.1/test/validator-amp-link-rewriter.html
  extensions/amp-link-rewriter/0.1/test/validator-amp-link-rewriter.out
  extensions/amp-link-rewriter/amp-link-rewriter.md
  extensions/amp-link-rewriter/validator-amp-link-rewriter.protoascii
Labels: cla: yes

#20096 Add isd, msd to visibility tracker
  examples/analytics-scrollDepth.amp.html
  extensions/amp-analytics/0.1/test/test-events.js
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-analytics/0.1/test/test-visibility-model.js
  extensions/amp-analytics/0.1/visibility-manager.js
  extensions/amp-analytics/0.1/visibility-model.js
  spec/amp-var-substitutions.md
  src/layout-rect.js
Labels: Category: Ads, Category: Analytics, cla: yes

#21735 📖 Update links to amp.dev
  SUPPORT.md
Labels: cla: yes

#21479 🖍 Add preliminary styles for amp-autocomplete
  css/Z_INDEX.md
  css/amp.css
  extensions/amp-autocomplete/0.1/amp-autocomplete.css
Labels: cla: yes

#21697 📖Document how to rerun Percy on a PR
  contributing/TESTING.md
Labels: cla: yes

#21734 ✨amp-experiment: Base functionality for Demo
  examples/experiment-1.0.amp.html
  extensions/amp-experiment/1.0/mutation-parser.js
  extensions/amp-experiment/1.0/test/test-mutation-parser.js
Labels: cla: yes

#21720 ✨ add ability for viewer to notify subscriptions that the state has changed
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#21745 Adds a suggestion to I2I template to sign CLA as soon as possible
  .github/ISSUE_TEMPLATE/intent-to-implement--i2i-.md
Labels: cla: yes

#21744 Emphasize signing CLA as soon as possible in contribution docs
  contributing/contributing-code.md
Labels: cla: yes

#21025 ✨Allow `fake` ads in amp stories
  examples/amp-story/ads/app-install.html
  examples/amp-story/fake-ad.html
  examples/amp-story/img/app-install-hero.jpg
  examples/amp-story/img/app-install-logo.jpg
  extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
  extensions/amp-ad-network-fake-impl/0.1/test/test-amp-ad-network-fake-impl.js
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
Labels: cla: yes

#21757 🐛 Implemented secure url exception for http://127.0.0.1
  src/url.js
Labels: cla: yes

#21748 🐛 Layers: Bust Resource's measurements when dirtying
  src/service/resources-impl.js
Labels: cla: yes

#21761 Validator rollup
  extensions/amp-ima-video/0.1/test/validator-amp-ima-video.out
  validator/validator-main.protoascii
Labels: cla: yes

#21726 WorkerDOM: upgrade to 0.6.0
  examples/amp-script/hello-world.js
  extensions/amp-script/0.1/amp-script.js
  package.json
  yarn.lock
Labels: cla: yes

#21750 Disable flaky visual diff tests
  test/visual-diff/visual-tests
Labels: Category: AMP Story, cla: yes

#21732 Remove scroll-height-bounce and scroll-height-minheight from config
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21731 Remove scroll-height-bounce and scroll-height-minheight experiments
  css/amp.css
  src/service/viewport/viewport-binding-ios-embed-sd.js
  src/service/viewport/viewport-binding-ios-embed-wrapper.js
  test/unit/test-viewport-binding.js
  tools/experiments/experiments.js
Labels: cla: yes

#21693 ✨Add Didomi to the CMPs list in the amp-consent extension
  extensions/amp-consent/0.1/cmps.js
Labels: cla: yes

#21764 ✨amp-experiment: 1.0 Validation, and Regex Updates
  extensions/amp-experiment/1.0/mutation-parser.js
  extensions/amp-experiment/1.0/test/validator-amp-experiment.html
  extensions/amp-experiment/1.0/test/validator-amp-experiment.out
  extensions/amp-experiment/validator-amp-experiment.protoascii
Labels: cla: yes

#21702 ✨ Allowing custom scope for SW in <amp-web-push>
  extensions/amp-web-push/0.1/amp-web-push-config.js
  extensions/amp-web-push/0.1/test/test-web-push-config.js
  extensions/amp-web-push/0.1/test/test-web-push-service.js
  extensions/amp-web-push/0.1/web-push-service.js
  extensions/amp-web-push/amp-web-push.md
Labels: cla: yes

#21313 Additional message in validation pass to follow up with CORS testing
  validator/engine/validator-in-browser.js
  validator/engine/validator.js
  validator/gulpjs/index.js
Labels: cla: yes

#21789 ✅ Convert skipped amp-bind integration tests to e2e tests
  build-system/app-test.js
  build-system/app.js
  build-system/tasks/e2e/expect.js
  build-system/tasks/e2e/puppeteer-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  test/e2e/test-amp-bind-brightcove.js
  test/e2e/test-amp-bind-email.js
  test/e2e/test-amp-bind-form.js
  test/e2e/test-amp-bind-iframe.js
  test/e2e/test-amp-bind-live-list.js
  test/e2e/test-amp-bind-state.js
  test/e2e/test-amp-bind-video.js
  test/e2e/test-amp-bind-youtube.js
  test/fixtures/e2e/amp-bind/bind-amp4email.html
  test/fixtures/e2e/amp-bind/bind-basic.html
  test/fixtures/e2e/amp-bind/bind-brightcove.html
  test/fixtures/e2e/amp-bind/bind-form.html
  test/fixtures/e2e/amp-bind/bind-iframe.html
  test/fixtures/e2e/amp-bind/bind-live-list.html
  test/fixtures/e2e/amp-bind/bind-video.html
  test/fixtures/e2e/amp-bind/bind-youtube.html
  test/integration/test-amp-bind.js
Labels: cla: yes

#21796 🏗 Reenable Edge and Chrome on Remote Tests (Sauce Labs) job
  build-system/tasks/runtime-test/index.js
Labels: cla: yes

#21775 Skip AMP Video failing HTTP test.
  extensions/amp-video/0.1/test/test-amp-video.js
Labels: cla: yes

#21747 object-fit and object-position attributes for amp-img, amp-video, and amp-anim.
  builtins/amp-img.js
  extensions/amp-anim/0.1/amp-anim.js
  extensions/amp-anim/0.1/test/test-amp-anim.js
  extensions/amp-anim/0.1/test/validator-amp-anim.html
  extensions/amp-anim/0.1/test/validator-amp-anim.out
  extensions/amp-anim/validator-amp-anim.protoascii
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-video/0.1/test/test-amp-video.js
  extensions/amp-video/0.1/test/validator-amp-video.html
  extensions/amp-video/0.1/test/validator-amp-video.out
  extensions/amp-video/validator-amp-video.protoascii
  src/style.js
  test/unit/test-amp-img.js
  validator/validator-main.protoascii
Labels: cla: yes

#21798 ✅ Skip amp-list e2e tests for now
  extensions/amp-list/0.1/test-e2e/test-load-more-auto.js
  extensions/amp-list/0.1/test-e2e/test-load-more-manual.js
Labels: cla: yes

#21801 🏗 Add lint rule to enforce that e2e test `expects` are `await`ed
  .eslintignore
  .eslintrc
  build-system/eslint-rules/await-expect.js
Labels: cla: yes

#21742 Launch amp-img-auto-sizes to 100% of production
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21713 ✨ SVK-Native Ads. Network integration
  3p/integration.js
  ads/_config.js
  ads/svknative.js
  ads/svknative.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#21812 ✅ Skip some tests that fail on Edge now that we're running tests on the browser
  test/integration/test-amp-inabox.js
  test/integration/test-amp-recaptcha-input.js
Labels: Related to: Flaky Tests, cla: yes

#21813 ✅ Skip `amp-script` tests on Windows (Edge, Firefox, and Chrome)
  extensions/amp-script/0.1/test/integration/test-amp-script.js
Labels: Category: Tooling, Related to: Flaky Tests, cla: yes

#21814 ✅ Skip `inabox` tests on Windows, not just Edge
  test/integration/test-amp-inabox.js
Labels: Related to: Flaky Tests, cla: yes

#21770 ✨Avoid rewriting href with multiple extensions
  extensions/amp-link-rewriter/0.1/test/validator-amp-link-rewriter-exclude.html
  extensions/amp-link-rewriter/0.1/test/validator-amp-link-rewriter-exclude.out
  extensions/amp-link-rewriter/validator-amp-link-rewriter.protoascii
  extensions/amp-skimlinks/validator-amp-skimlinks.protoascii
  extensions/amp-smartlinks/validator-amp-smartlinks.protoascii
Labels: cla: yes

#21779 🏗 Clear node require cache when running E2E tests
  build-system/tasks/e2e/index.js
Labels: cla: yes

#21793 📖 Fix sidebar for stories side documentation
  extensions/amp-sidebar/amp-sidebar.md
Labels: cla: yes

#21810 Validator Rollup
  validator/validator-main.protoascii
Labels: Category: Validator, cla: yes

#21822 🏗 Change disconnect / no activity timeouts for Sauce Labs
  build-system/tasks/karma.conf.js
Labels: Category: Tooling, Related to: Flaky Tests, cla: yes

#21823 Validator Rollup
  validator/validator-main.protoascii
Labels: cla: yes

#21827 Revert third_party/subscriptions-project/ files for Closure upgrade
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#21818 🐛 Fix Source maps
  3p/integration.js
  ads/google/a4a/utils.js
  build-system/dep-check-config.js
  build-system/shorten-license.js
  extensions/amp-analytics/0.1/iframe-transport.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  src/3p-frame.js
  src/amp-shadow.js
  src/amp.js
  src/iframe-attributes.js
  src/inabox/amp-inabox-lite.js
  src/inabox/amp-inabox.js
  src/internal-version.js
  src/mode.js
  src/runtime.js
  src/service/url-replacements-impl.js
Labels: cla: yes

#21825 SwG Release 0.1.22.49
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#21831 Update flaky integration test on amp-list
  extensions/amp-list/0.1/test/integration/test-amp-list.js
Labels: cla: yes

#21824 add single pass experiment IDs when needed.
  ads/google/a4a/traffic-experiments.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#21851 Add explicity `--unit` to automated tests that run on `--local-changes`
  build-system/default-pre-push
  build-system/pr-check.js
  build-system/pr-check/local-tests.js
Labels: cla: yes

#21864 Sort experiment.json files
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21805 ✨ Add support for "error" param for amp-viewer-assistance.updateActionState
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-viewer-assistance/0.1/amp-viewer-assistance.js
  extensions/amp-viewer-assistance/0.1/test/test-amp-viewer-assistance.js
  extensions/amp-viewer-assistance/amp-viewer-assistance.md
Labels: cla: yes

#21842 Update docs for amp-list to indicate that load-more is out of experimental
  extensions/amp-list/amp-list.md
Labels: cla: yes

#21868 🏗 Replace `gulp-closure-compiler` with `google-closure-compiler`
  build-system/single-pass.js
  build-system/tasks/compile.js
  package.json
  yarn.lock
Labels: Category: Tooling, cla: yes

#21843 Cleanup amp-list-resizable-children experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#21877 Remove resizable children experiment
  tools/experiments/experiments.js
Labels: cla: yes

#21879 Revert "🏗 Replace `gulp-closure-compiler` with `google-closure-compiler` (#21868)
  build-system/single-pass.js
  build-system/tasks/compile.js
  package.json
  yarn.lock
Labels: cla: yes

#21863 🏗 Report queued/skipped tests to the test status app
  build-system/pr-check/checks.js
  build-system/tasks/runtime-test/index.js
  build-system/tasks/runtime-test/status-report.js
Labels: cla: yes

#21852 Add error logging for page navigation errors in visual diff tests
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#21687 ✨ Create a hidden attribute mutation observer service
  extensions/amp-a4a/0.1/test/test-refresh.js
  extensions/amp-story/1.0/amp-story.js
  src/inabox/amp-inabox-lite.js
  src/intersection-observer-polyfill.js
  src/runtime.js
  src/service/fixed-layer.js
  src/service/hidden-observer-impl.js
  src/services.js
  test/unit/test-fixed-layer.js
  test/unit/test-hidden-observer.js
  test/unit/test-intersection-observer-polyfill.js
Labels: cla: yes

#21701 amp-script: Add Vue.js TodoMVC example
  examples/amp-script/vue-todomvc.amp.html
  examples/amp-script/vue-todomvc.js
Labels: cla: yes

#21866 DOMPurify: Remove special-case for "on" attribute
  src/purifier.js
Labels: cla: yes

#21782 amp-script: Refactor and improve sanitization coverage
  examples/amp-script/hello-world.js
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/integration/test-amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
  package.json
  src/purifier.js
  test/unit/test-purifier.js
  yarn.lock
Labels: cla: yes

#17597 Update amp-form.md for user-invalid polyfill on fieldset
  extensions/amp-form/amp-form.md
Labels: cla: yes

#21676 cors docs: caches.json is now the canonical source of cache info
  spec/amp-cors-requests.md
Labels: cla: yes

#21903 🐛 don't auto lightbox elements with subscriptions-action attribute
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
  extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
Labels: cla: yes

#21730 using global.context.sourceUrl in PubMatic UAS ad tag
  ads/uas.js
Labels: cla: yes

#21552 ✨add wp anonymous mode
  extensions/amp-addthis/0.1/addthis-utils/get-widget-id-overloaded-with-json-for-anonymous-mode.js
  extensions/amp-addthis/0.1/addthis-utils/mode.js
  extensions/amp-addthis/0.1/addthis-utils/string.js
  extensions/amp-addthis/0.1/amp-addthis.js
  extensions/amp-addthis/0.1/config-manager.js
  extensions/amp-addthis/0.1/test/test-amp-addthis.js
  extensions/amp-addthis/0.1/test/validator-amp-addthis.html
  extensions/amp-addthis/0.1/test/validator-amp-addthis.out
  extensions/amp-addthis/validator-amp-addthis.protoascii
Labels: cla: yes

#21900 🏗 Replace `gulp-closure-compiler` with `google-closure-compiler` (reprise)
  build-system/single-pass.js
  build-system/tasks/compile.js
  package.json
  yarn.lock
Labels: Category: Tooling, cla: yes

#21917 🐛 Update amp-geo country code hotpatch detection
  extensions/amp-geo/0.1/amp-geo.js
Labels: cla: yes

#21811 amp-form-textarea text area drag fix.
  extensions/amp-form/0.1/amp-form-textarea.js
  extensions/amp-form/0.1/test/test-amp-form-textarea.js
Labels: cla: yes

#21932 🏗🐛 Fix closure compiler error logging
  build-system/tasks/compile.js
Labels: Category: Tooling, Type: Bug, cla: yes

#21872 small fix for amp auto anchor ads
  extensions/amp-auto-ads/0.1/anchor-ad-strategy.js
Labels: cla: yes

#21670 Subscriptions encryption part 1
  build-system/app.js
  examples/amp-subscriptions.amp.html
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/crypto-handler.js
  extensions/amp-subscriptions/0.1/entitlement.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/service-adapter.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-crypto-handler.js
  extensions/amp-subscriptions/0.1/test/test-entitlement.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-service-adapter.js
Labels: cla: yes

#21800 🐛amp-autocomplete: Fix submit-on-enter bug
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
  extensions/amp-autocomplete/amp-autocomplete.md
Labels: cla: yes

#21889 📖 amp-video-docking: Correct the URL of amp-video-iframe
  extensions/amp-video-docking/amp-video-docking.md
Labels: cla: yes

#21947 🏗 Fold visual diff test errors and warning on Travis
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#21946 🏗 Create a snapshot with the error message for failing visual diff tests
  build-system/tasks/visual-diff/index.js
  build-system/tasks/visual-diff/snippets/snapshot-error.html
Labels: cla: yes

#21951 🏗✨ Add `--full_sourcemaps`, a `gulp dist` flag to include source code in sourcemaps
  build-system/tasks/compile.js
  gulpfile.js
Labels: Category: Tooling, cla: yes

#21762 Inabox host script disallows write action (expanding iframe, etc.) by default.
  ads/inabox/inabox-messaging-host.js
  test/unit/inabox/test-inabox-messaging-host.js
Labels: cla: yes

#21964 Changes README references from ampproject.org to amp.dev
  README.md
Labels: cla: yes

#21963 ✅ Skip flaky tests
  extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
Labels: cla: yes

#21950 🏗 Retry failed page navigation in visual diff tests
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#21962 🏗 Add the text `[non-blocking]` to the Remote and e2e Travis stages
  .travis.yml
Labels: cla: yes

#21882 🏗 Increase page navigation timeout in visual diff tests from 3s to 7s and switch to `networkidle2` strategy
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#21802 Re-enable amp-video HTTP test.
  extensions/amp-video/0.1/test/test-amp-video.js
Labels: cla: yes

#21966 Remove extra dependencies for iframe-api package
  extensions/amp-access/0.1/iframe-api/DEVELOPING.md
  extensions/amp-access/0.1/iframe-api/iframe-api.js
  extensions/amp-access/0.1/iframe-api/messenger.js
  gulpfile.js
Labels: cla: yes

#21728 🐛amp-mraid: handle non-inabox better
  extensions/amp-mraid/0.1/amp-mraid.js
Labels: cla: yes

#21707 🐛Restore width on section content.
  extensions/amp-accordion/0.1/amp-accordion.js
  extensions/amp-accordion/0.1/test/test-amp-accordion.js
Labels: cla: yes

#21738 ✨ mraid: change default for fallback, and simplify configuration
  examples/mraid/inabox-mraid.html
  extensions/amp-mraid/0.1/amp-mraid.js
Labels: cla: yes

#21938 using global.context.sourceUrl in PubMatic SSP ad tag
  ads/pubmatic.js
Labels: cla: yes

#21844 Remove references to amp-list-load-more experiment now that the feature has launched
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list-load-more.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#21957 Updates contributing docs to simplify small change section and change "reviewer" to "guide"
  contributing/contributing-code.md
Labels: cla: yes

#21978 Amp form textarea comment
  extensions/amp-form/0.1/amp-form-textarea.js
Labels: cla: yes

#21956 🐛Use current ChromeDriver version
  build-system/tasks/e2e/package.json
  build-system/tasks/e2e/yarn.lock
  renovate.json
Labels: cla: yes

#21846 🐛 Disable and re-enable browser autofilling on amp-autocomplete.
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Labels: cla: yes

#21766 Stories media queries service.
  extensions/amp-story/1.0/amp-story-desktop-panels.css
  extensions/amp-story/1.0/amp-story-media-query-service.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story-media-query-service.js
  src/services.js
Labels: cla: yes

#21948 🐛 Expand token-prefix meaning on amp-autocomplete
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Labels: cla: yes

#21968 ✅ amp-iframe: fix test flake
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
Labels: cla: yes

#21911 📖 Update Sample document of AMP HTML Format needs amp-ad script
  spec/amp-html-format.md
Labels: cla: yes

#21312 Skip the failing inabox BTF test on Safari.
  test/integration/test-amp-inabox.js
Labels: cla: yes

#21983 ✅ Make Sauce labs integration tests green
  extensions/amp-script/0.1/test/integration/test-amp-script.js
Labels: Related to: Flaky Tests, cla: yes

#21967 ♿amp-base-carousel a11y fixes
  extensions/amp-base-carousel/0.1/amp-base-carousel.css
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-base-carousel/0.1/auto-advance.js
  extensions/amp-base-carousel/0.1/carousel-accessibility.js
  extensions/amp-base-carousel/0.1/carousel.js
  src/dom.js
  test/unit/test-dom.js
Labels: cla: yes

#21837 ✨ Add Vpon Analytics to AMP analytics vendors #21769
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/vponanalytics.js
Labels: cla: yes

#21829 ✅ Skip flaky amp-base-carousel e2e tests
  build-system/tasks/e2e/describes-e2e.js
  extensions/amp-base-carousel/0.1/test-e2e/test-arrows-non-looping.js
  extensions/amp-base-carousel/0.1/test-e2e/test-arrows.js
  extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
  extensions/amp-base-carousel/0.1/test-e2e/test-grouping.js
  extensions/amp-base-carousel/0.1/test-e2e/test-initial-slide.js
  extensions/amp-base-carousel/0.1/test-e2e/test-mixed-lengths-no-snap.js
  extensions/amp-base-carousel/0.1/test-e2e/test-mixed-lengths.js
  extensions/amp-base-carousel/0.1/test-e2e/test-non-looping.js
  extensions/amp-base-carousel/0.1/test-e2e/test-responsive.js
  extensions/amp-base-carousel/0.1/test-e2e/test-vertical.js
Labels: cla: yes

#21990 🏗 Make remote (sauce labs) tests blocking on Travis now that they're green
  .travis.yml
Labels: Category: Tooling, Related to: Flaky Tests, cla: yes

#21992 ✅ Make visual tests non-blocking
  .travis.yml
Labels: Related to: Flaky Tests, cla: yes

#21977 🏗✨Create a `gulp` task for the `nailgun` compiler
  build-system/tasks/compile.js
  build-system/tasks/index.js
  build-system/tasks/nailgun-compile
  build-system/tasks/nailgun.js
  gulpfile.js
Labels: Category: Tooling, cla: yes

#21985 Custom CTA label for story page attachments.
  examples/visual-tests/amp-story/amp-story-page-attachment-desktop.js
  examples/visual-tests/amp-story/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/test/test-amp-story-page.js
Labels: cla: yes

#21976 🐛 fixed-layer: Fix hidden observer init in PWA
  src/service/fixed-layer.js
  src/service/hidden-observer-impl.js
Labels: cla: yes

#21526 ✅ Add validation rules for amp-autocomplete.
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
  extensions/amp-autocomplete/amp-autocomplete.md
  extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
Labels: cla: yes

#21996 [amp-pan-zoom] to scheduleLayout for its children
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  extensions/amp-pan-zoom/0.1/test/test-amp-pan-zoom.js
  test/manual/amp-pan-zoom/amp-pan-zoom-carousel.amp.html
  test/manual/amp-pan-zoom/amp-pan-zoom-initial.amp.html
  test/manual/amp-pan-zoom/amp-pan-zoom-integration.amp.html
  test/manual/amp-pan-zoom/amp-pan-zoom-positioning.amp.html
  test/manual/amp-pan-zoom/amp-pan-zoom.amp.html
Labels: cla: yes

#21845 ✅ Add end-to-end tests for amp-autocomplete.
  extensions/amp-autocomplete/0.1/test-e2e/test-amp-autocomplete.js
  test/manual/amp-autocomplete/amp-autocomplete.amp.html
Labels: cla: yes

#21991 🏗 Remove parallelization from visual diff to avoid flakiness
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#21995 Fix the copy to clipboard sharing option on Stories.
  extensions/amp-story/1.0/amp-story-share.js
Labels: cla: yes

#22020 ✅ Fix AMPHTML document for <amp-sidebar> visual diff tests
  examples/visual-tests/amp-sidebar/amp-sidebar-toolbar-ol.amp.html
  examples/visual-tests/amp-sidebar/amp-sidebar-toolbar-ul.amp.html
Labels: cla: yes

#22023 Issue 22022 fix
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Labels: cla: yes

#21807 🐛 load mraid.js from a url that won't normally resolve.
  extensions/amp-mraid/0.1/amp-mraid.js
Labels: cla: yes

#22032 Validator 20190426
  extensions/amp-image-slider/validator-amp-image-slider.protoascii
  extensions/amp-video-iframe/validator-amp-video-iframe.protoascii
  validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.html
  validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.out
  validator/validator-main.protoascii
Labels: cla: yes

#22028 ✅ Allowing service-worker-scope attribute in amp-web-push for AMP validator
  extensions/amp-web-push/0.1/test/validator-amp-web-push.html
  extensions/amp-web-push/0.1/test/validator-amp-web-push.out
  extensions/amp-web-push/validator-amp-web-push.protoascii
Labels: cla: yes

#22033 ✅ amp-sidebar and amp-image-lightbox tests in FF
  extensions/amp-image-lightbox/0.1/test/integration/test-amp-image-lightbox.js
  extensions/amp-sidebar/0.1/test/integration/test-amp-sidebar.js
Labels: cla: yes

#22017 Deletes outdated references to core committers
  contributing/CODE_OWNERSHIP.md
  contributing/DEVELOPING.md
  contributing/building-an-amp-extension.md
  contributing/creating-a-welcoming-community.md
  contributing/owners-and-committers.md
Labels: cla: yes
