Repository ampproject/amphtml, pull requests merged in 2020-10, with the labels that each got.

#30459 🏗 Migrate from deprecated `opn` to `open`
  build-system/tasks/e2e/index.js
  build-system/tasks/helpers.js
  build-system/tasks/runtime-test/helpers.js
  package.json
  yarn.lock
Labels: cla: yes

#30462 Fixes generated protoascii. Tested scripts/validator_example compiles
  extensions/BUILD
  validator/BUILD
  validator/WORKSPACE
  validator/cpp/engine/WORKSPACE
Labels: cla: yes

#30439 Clarify layoutSizeDefined and provide default isLayoutSupported
  extensions/amp-base-carousel/1.0/amp-base-carousel.js
  extensions/amp-date-display/1.0/amp-date-display.js
  extensions/amp-fit-text/1.0/amp-fit-text.js
  extensions/amp-timeago/1.0/amp-timeago.js
  src/preact/base-element.js
Labels: cla: yes

#30478 🏗 Pin yarn to 1.22.5 temporarily
  build-system/common/check-package-manager.js
Labels: cla: yes

#30476 📖 No longer an open proposal
  extensions/amp-mustache/amp-mustache.md
Labels: cla: yes

#30467 🏗 Consolidate `gulp storybook` command
  build-system/tasks/storybook/index.js
  gulpfile.js
Labels: cla: yes

#30464 📖 Document metatag consent blocking
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#30477 Delete duplicate file
  validator/testdata/feature_tests/.cpponly
Labels: WG: caching, cla: yes

#30433 🐛 [amp-story-player] Adds intermediate element and removes default size
  css/amp-story-player-iframe.css
  css/amp-story-player.css
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#30479 🐛 Activate button above content.
  extensions/amp-story-360/0.1/amp-story-360.css
  extensions/amp-story-360/0.1/amp-story-360.js
Labels: cla: yes

#30466 🐛 Catch rejected promise in getConsentRemote
  extensions/amp-consent/0.1/amp-consent.js
Labels: cla: yes

#30483 SwG 0.1.22.123 Release
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#30485 Fix typos and types in url class.
  validator/cpp/htmlparser/url.h
Labels: cla: yes

#30480 Fix validator_test partially
  extensions/BUILD
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out.cpponly
  extensions/amp-geo/0.1/test/validator-amp-geo.cpponly
  extensions/amp-geo/0.1/test/validator-amp-geo.out.cpponly
  extensions/amp-mustache/0.1/test/validator-amp-mustache.out.cpponly
  extensions/amp-mustache/0.2/test/validator-amp-mustache.out.cpponly
  extensions/amp-mustache/0.2/test/validator-json-not-in-template.out.cpponly
  validator/BUILD
  validator/cpp/engine/BUILD
  validator/cpp/engine/WORKSPACE
  validator/cpp/engine/scripts/BUILD
  validator/cpp/engine/testing-utils.cc
Labels: cla: yes

#30489 Fix validator_test
  extensions/amp-story/1.0/test/validator-amp-story-sidebar-error.out
  validator/cpp/engine/validator-internal.cc
Labels: cla: yes

#30497 Validator rollup
  validator/js/engine/parse-srcset.js
Labels: cla: yes

#30494 Remove dependency on the global window for impression tracking
  testing/describes.js
Labels: cla: yes

#30482 amp-accordion: Enable display locking based on `beforematch`
  extensions/amp-accordion/0.1/amp-accordion.js
Labels: cla: yes

#30118 🏗 Report test results when test task fails
  build-system/common/exec.js
  build-system/pr-check/dist-tests.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/local-tests.js
  build-system/pr-check/utils.js
  build-system/tasks/e2e/mocha-custom-json-reporter.js
  build-system/tasks/test-report-upload.js
Labels: cla: yes

#30468 ampdoc-fie cleanup: remove legacy FIE installer
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/test-friendly-frame-renderer.js
  extensions/amp-a4a/0.1/test/test-friendly-frame-util.js
  extensions/amp-a4a/0.1/test/test-template-renderer.js
  extensions/amp-ad-custom/0.1/test/test-amp-ad-custom.js
  extensions/amp-analytics/0.1/test/test-analytics-root.js
  extensions/amp-analytics/0.1/test/test-instrumentation.js
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-animation/0.1/test/test-amp-animation.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
  extensions/amp-gwd-animation/0.1/test/test-amp-gwd-animation.js
  src/element-service.js
  src/friendly-iframe-embed-legacy.js
  src/friendly-iframe-embed.js
  src/service.js
  src/service/action-impl.js
  src/service/core-services.js
  src/service/hidden-observer-impl.js
  src/service/navigation.js
  src/service/standard-actions-impl.js
  src/service/url-impl.js
  test/unit/test-action.js
  test/unit/test-element-service.js
  test/unit/test-friendly-iframe-embed.js
  test/unit/test-navigation.js
  test/unit/test-service.js
  test/unit/test-standard-actions.js
  testing/describes.js
Labels: cla: yes

#30496 360 Feature discovery
  css/Z_INDEX.md
  extensions/amp-story-360/0.1/amp-story-360.css
  extensions/amp-story-360/0.1/amp-story-360.js
Labels: cla: yes

#30499 custom-element: remove attached/detached callbacks
  src/custom-element.js
Labels: cla: yes

#30492 ♻️ Remove firstAttachedCallback and createdCallback
  builtins/amp-img.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-vendors.js
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-story/1.0/amp-story-grid-layer.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-truncate-text/0.1/amp-truncate-text.js
  extensions/amp-video/0.1/amp-video.js
  src/base-element.js
  src/custom-element.js
  test/unit/test-amp-img.js
  test/unit/test-custom-element.js
Labels: WG: runtime, cla: yes

#30434 [amp-story-player] Update validation
  extensions/amp-story-player/validator-amp-story-player.protoascii
Labels: WG: caching, cla: yes

#30469 ampdoc-fie cleanup: remove legacy style installer
  src/style-installer.js
  test/unit/test-style-installer.js
  testing/iframe.js
Labels: cla: yes

#30519 🏗Fix test-report-upload in push builds
  build-system/pr-check/dist-tests.js
  build-system/pr-check/e2e-tests.js
  build-system/tasks/test-report-upload.js
Labels: cla: yes

#30509 🚮 Remove unused eslint-disable
  build-system/babel-plugins/babel-plugin-transform-jss/test/index.js
  build-system/server/app-index/boilerplate.js
  build-system/server/app-index/file-list.js
  build-system/server/app-index/settings.js
  build-system/server/app-index/template.js
  build-system/server/shadow-viewer.js
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/helpers.js
  build-system/tasks/storybook/amp-env/main.js
  build-system/tasks/storybook/preact-env/main.js
  extensions/amp-addthis/0.1/addthis-utils/classify.js
  extensions/amp-animation/0.1/web-animations.js
  extensions/amp-apester-media/0.1/monetization/companion/video.js
  extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
  extensions/amp-geo/0.1/test/test-amp-geo.js
  extensions/amp-script/0.1/test/integration/test-amp-script.js
  extensions/amp-story/1.0/_locales/km.js
  extensions/amp-subscriptions/0.1/test/test-crypto-handler.js
  src/amp-shadow.js
  src/amp.js
  src/iframe-helper.js
  src/service/origin-experiments-impl.js
  src/service/position-observer/position-observer-impl.js
  src/service/video-manager-impl.js
  src/service/viewport/viewport-binding-ios-embed-wrapper.js
  src/service/viewport/viewport-binding-natural.js
  test/integration/test-amp-bind.js
  test/integration/test-amp-recaptcha-input.js
  test/unit/test-origin-experiments.js
  testing/yield.js
Labels: cla: yes

#30507 Remove a few eslint disable rules as unnecessary
  3p/ampcontext-lib.js
  3p/iframe-transport-client-lib.js
  3p/integration.js
  3p/recaptcha.js
  ads/google/imaVideo.js
  ads/speakol.js
  ads/uas.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  test/unit/ads/test-aduptech.js
Labels: cla: yes

#30446 Accordion bento component outline
  build-system/compile/bundles.config.js
  extensions/amp-accordion/1.0/accordion.js
  extensions/amp-accordion/1.0/accordion.type.js
  extensions/amp-accordion/1.0/amp-accordion.css
  extensions/amp-accordion/1.0/amp-accordion.js
  extensions/amp-accordion/1.0/storybook/Basic.amp.js
  extensions/amp-accordion/1.0/storybook/Basic.js
  extensions/amp-accordion/1.0/test/test-accordion.js
  extensions/amp-accordion/1.0/test/test-amp-accordion.js
  src/preact/base-element.js
  src/utils/id-generator.js
  src/utils/object.js
  test/unit/test-object.js
Labels: cla: yes

#30463 🏗 Add `gulp serve --coverage=live` to auto-report coverage while browsing
  build-system/server/app.js
  build-system/tasks/serve.js
Labels: cla: yes

#30521 Add gmajoulet to amp-video OWNERS.
  extensions/amp-video/OWNERS
Labels: cla: yes

#30533 🏗 Use `yarn` v1.22.5 on Travis
  .travis.yml
Labels: WG: infra, cla: yes

#30503 🐛 [amp-story] Build pagination buttons for pre-rendered stories
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/pagination-buttons.css
Labels: cla: yes

#30536 add a try catch for navigation performanceobserver
  src/service/performance-impl.js
Labels: cla: yes

#30386 ✨ [bento][amp-date-countdown] Bento version of AMP component
  build-system/compile/bundles.config.js
  extensions/amp-date-countdown/1.0/amp-date-countdown.js
  extensions/amp-date-countdown/1.0/date-countdown.js
  extensions/amp-date-countdown/1.0/date-countdown.type.js
  extensions/amp-date-countdown/1.0/test/test-amp-date-countdown.js
  extensions/amp-date-countdown/1.0/test/test-date-countdown.js
Labels: cla: yes

#30511 Cleanup ampdoc-fie in AmpDoc service
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/test-name-frame-renderer.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-apester-media/0.1/test/test-amp-apester-media-utils.js
  src/ampdoc-fie.js
  src/impression.js
  src/service/ampdoc-impl.js
  test/unit/3p/test-3p-frame.js
  test/unit/test-ampdoc.js
  test/unit/test-element-service.js
  test/unit/test-friendly-iframe-embed.js
  test/unit/test-impression.js
  test/unit/test-service.js
  testing/describes.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#30504 CSI: Report SSR experiments via the USQP meta
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#30539 🏗 Report Travis job/build URLs to test case reporting
  build-system/common/travis.js
  build-system/tasks/test-report-upload.js
Labels: cla: yes

#30563 ❄️ Skip Flaky Carousel Tests
  extensions/amp-base-carousel/0.1/test/test-carousel.js
Labels: cla: yes

#30545 ✂️ ampdoc-fie cleanup: remove unused constructor args for doc/fie services
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
  src/dom.js
  src/service/hidden-observer-impl.js
  src/service/navigation.js
  src/service/standard-actions-impl.js
  src/service/url-impl.js
  src/shadow-embed.js
  test/unit/test-shadow-embed.js
Labels: cla: yes

#30530 Bento Carousel: `controls` prop
  extensions/amp-base-carousel/1.0/amp-base-carousel.js
  extensions/amp-base-carousel/1.0/base-carousel.js
  extensions/amp-base-carousel/1.0/base-carousel.type.js
  extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
  extensions/amp-base-carousel/1.0/storybook/Basic.js
  extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
  extensions/amp-base-carousel/1.0/test/test-base-carousel.js
Labels: cla: yes

#30556 📖 Add @function JSDoc annotation to wrapped helpers
  build-system/common/travis.js
  build-system/pr-check/utils.js
Labels: cla: yes

#30552 🏗 Use status instead of stderr to detect failure in execOrThrow
  build-system/common/check-package-manager.js
  build-system/common/exec.js
  build-system/common/process.js
  build-system/pr-check/dist-tests.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/local-tests.js
  build-system/pr-check/utils.js
  build-system/tasks/cherry-pick.js
Labels: cla: yes

#30561 📖 [bento][amp-date-countdown] Add and update existing storybook for amp-date-countdown
  extensions/amp-date-countdown/1.0/storybook/Basic.amp.js
  extensions/amp-date-countdown/1.0/storybook/Basic.js
Labels: cla: yes

#30559 📖 Update validator install instructions
  validator/README.md
Labels: WG: caching, cla: yes

#30558 Sync from Google
  validator/cpp/htmlparser/url.cc
  validator/cpp/htmlparser/url.h
  validator/cpp/htmlparser/url_test.cc
Labels: WG: caching, cla: yes

#30520 Add new AMPDOC_META analytics var and macro
  extensions/amp-analytics/0.1/default-config.js
  extensions/amp-analytics/0.1/sandbox-vars-allowlist.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
Labels: cla: yes

#30537 🐛 Correct scene-heading value in euler_ method
  third_party/zuho/zuho.js
Labels: cla: yes

#30144 🐛Update amp-playbuzz internal iframe url
  extensions/amp-playbuzz/0.1/test/test-amp-playbuzz.js
  extensions/amp-playbuzz/0.1/utils.js
  extensions/amp-playbuzz/OWNERS
Labels: cla: yes

#30569 🏗 Only measure CWV metrics for CI performance benchmark
  build-system/tasks/performance/README.md
  build-system/tasks/performance/measure-documents.js
Labels: WG: infra, WG: performance, cla: yes

#30543 Bento Accordion: animations
  css/ampshared.css
  extensions/amp-accordion/0.1/amp-accordion.css
  extensions/amp-accordion/1.0/accordion.js
  extensions/amp-accordion/1.0/accordion.type.js
  extensions/amp-accordion/1.0/amp-accordion.js
  extensions/amp-accordion/1.0/animations.js
  extensions/amp-accordion/1.0/storybook/Basic.amp.js
  extensions/amp-accordion/1.0/storybook/Basic.js
  extensions/amp-accordion/1.0/test/test-accordion.js
  extensions/amp-accordion/1.0/test/test-amp-accordion.js
  src/custom-element.js
  test/unit/test-custom-element.js
  test/unit/test-dom.js
Labels: cla: yes

#30540 unit tests: remove canary sentinel
  test/_init_tests.js
  test/unit/3p/test-3p-frame.js
Labels: cla: yes

#30505 Refactor onResizeSuccess/onResizeFailure to requestResize
  3p/ampcontext.js
  ads/google/csa.js
  build-system/tasks/presubmit-checks.js
  test/unit/ads/test-adplugg.js
  test/unit/ads/test-aduptech.js
  test/unit/ads/test-csa.js
Labels: cla: yes

#30577 📖 Update instructions to install openjdk on macOS
  validator/README.md
Labels: cla: yes

#30575 🐛 Fix interactive prompt not centering when CSS variable is center
  extensions/amp-story-interactive/0.1/amp-story-interactive.css
Labels: cla: yes

#30570 ♻️ [amp-story-player] Migrate this.stories_ to new StoryDef
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#30583 🐛 [amp-story-player] Only add amp_js_v when amp cache
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#30498 🐛 amp-access-scroll: Reset iframe container padding and margin
  extensions/amp-access-scroll/0.1/amp-access-scroll.css
Labels: cla: yes

#30405 📖 Fix typo
  extensions/amp-ad-network-doubleclick-impl/multi-size.md
Labels: cla: yes

#30580 ♻️ Move beopinion to use requestResize promise
  3p/beopinion.js
Labels: cla: yes

#30419 ✅ Modernize test-actions, test-toggle-display, and integration test infra
  test/integration/test-actions.js
  test/integration/test-amp-img.js
  test/integration/test-toggle-display.js
  testing/describes.js
  testing/test-helper.js
Labels: cla: yes

#29102 🔥 amp-connatix-player: Handle amp-consent for our existing amp-connatix-player.js
  extensions/amp-connatix-player/0.1/amp-connatix-player.js
Labels: cla: yes

#30624 🔥 Include AbortController in ESM polyfills
  build-system/compile/compile.js
Labels: cla: yes

#30598 🐛 Fix .getImpl race condition on Android
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/test/test-amp-story-grid-layer.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
Labels: cla: yes

#30595 🐛 Interactives only should show confetti on user selection
  extensions/amp-story-interactive/0.1/amp-story-interactive-abstract.js
Labels: cla: yes

#30604 ✨ Hide video eq when no-audio embedMode
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#30549 Bento Carousel: `snap` prop
  extensions/amp-base-carousel/1.0/amp-base-carousel.js
  extensions/amp-base-carousel/1.0/base-carousel.js
  extensions/amp-base-carousel/1.0/base-carousel.jss.js
  extensions/amp-base-carousel/1.0/base-carousel.type.js
  extensions/amp-base-carousel/1.0/scroller.js
  extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
  extensions/amp-base-carousel/1.0/storybook/Basic.js
  extensions/amp-base-carousel/1.0/test-e2e/helpers.js
  extensions/amp-base-carousel/1.0/test-e2e/test-carousel.js
  extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
  extensions/amp-base-carousel/1.0/test/test-base-carousel.js
  test/manual/amp-base-carousel/1.0/basic.amp.html
  test/manual/amp-base-carousel/1.0/img/bluegradient.png
  test/manual/amp-base-carousel/1.0/img/greengradient.png
  test/manual/amp-base-carousel/1.0/img/lemonyellowgradient.png
  test/manual/amp-base-carousel/1.0/img/lilacgradient.png
  test/manual/amp-base-carousel/1.0/img/orangegradient.png
  test/manual/amp-base-carousel/1.0/img/redgradient.png
  test/manual/amp-base-carousel/1.0/img/tealgradient.png
Labels: cla: yes

#30481 🐛Video analytics bug
  extensions/amp-video/0.1/amp-video.js
  src/service/video-manager-impl.js
Labels: cla: yes

#30576 ✅ Validator rules for <amp-onetap-google>
  extensions/amp-onetap-google/0.1/test/validator-amp-onetap-google.html
  extensions/amp-onetap-google/0.1/test/validator-amp-onetap-google.out
  extensions/amp-onetap-google/validator-amp-onetap-google.protoascii
Labels: WG: caching, cla: yes

#30630 🏗 Remove includeOnlyESMLevelPolyfills
  build-system/compile/bundles.config.js
  build-system/compile/compile.js
Labels: cla: yes

#30554 add try/catch to calls to PerformanceObserver.prototype.observe and add tests
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#30628 Update validator owners
  validator/OWNERS
Labels: WG: caching, cla: yes

#30629 ✅ Aggregate coverage during testing and report after
  build-system/tasks/e2e/describes-e2e.js
Labels: cla: yes

#30643 🏗 Remove fullscreenEnter wrapper check from denylist
  build-system/tasks/presubmit-checks.js
Labels: cla: yes

#30633 🐛 Story pages when removed makes navigation crash (WIP)
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#30500 ✨ [amp-story-player] Consume JSON configuration from the player
  css/amp-story-player-iframe.css
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#30578 amp-img: do not propagate data-amp-bind*
  builtins/amp-img.js
  src/base-element.js
  test/unit/test-amp-img.js
  test/unit/test-base-element.js
Labels: cla: yes

#30632 📖 Update Cherry-pick template with QA section
  .github/ISSUE_TEMPLATE/cherry_pick_template.md
  .github/ISSUE_TEMPLATE/page-experience.md
  .github/ISSUE_TEMPLATE/release-tracking-issue.md
Labels: cla: yes

#30658 🏗 Pin `yarn` stable version to v1.22.4
  .travis.yml
  build-system/common/check-package-manager.js
Labels: WG: infra, cla: yes

#30635 Refactor button rendering for story ads (pt 1)
  build-system/test-configs/dep-check-config.js
  extensions/amp-story-auto-ads/0.1/story-ad-page.js
  extensions/amp-story-auto-ads/0.1/story-ad-ui.js
  extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js
  extensions/amp-story-auto-ads/0.1/test/test-story-ad-ui.js
  extensions/amp-story-auto-ads/0.1/utils.js
Labels: cla: yes

#30656 [amp-story-player] Pass object with controls key
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#30501 ✨ [amp-story-player] Send custom UI config from player to story
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js
Labels: cla: yes

#30668 🏗 Upload e2e coverage reports to codecov if present
  build-system/tasks/codecov-upload.js
Labels: cla: yes

#30634 Reimplement loading indicator via IntersectionObserver
  extensions/amp-animation/0.1/test/test-amp-animation.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-twitter/0.1/amp-twitter.js
  src/base-element.js
  src/custom-element.js
  src/service.js
  src/service/core-services.js
  src/service/loader-element.js
  src/service/loading-indicator.js
  src/services.js
  test/unit/test-amp-inabox.js
  test/unit/test-custom-element.js
  test/unit/test-loader.js
  test/unit/test-loading-indicator.js
Labels: cla: yes

#30665 🐛Fix binary poll not clamping more than two lines
  extensions/amp-story-interactive/0.1/amp-story-interactive-binary-poll.css
Labels: cla: yes

#30678 📖 Fix dead links in analytics vendors
  extensions/amp-analytics/analytics-vendors-list.md
Labels: cla: yes

#30648 Bento Carousel: `outsetArrows` prop
  extensions/amp-base-carousel/1.0/amp-base-carousel.js
  extensions/amp-base-carousel/1.0/arrow.js
  extensions/amp-base-carousel/1.0/base-carousel.js
  extensions/amp-base-carousel/1.0/base-carousel.jss.js
  extensions/amp-base-carousel/1.0/base-carousel.type.js
  extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
  extensions/amp-base-carousel/1.0/storybook/Basic.js
  extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
  extensions/amp-base-carousel/1.0/test/test-base-carousel.js
Labels: cla: yes

#30682 🐛 Align 'activate 360' button with header UI
  extensions/amp-story-360/0.1/amp-story-360.css
Labels: P2: Soon, Type: Bug, WG: stories, cla: yes

#30655 ✨ Lotame: Change to allow limiting the maximum number of audiences.
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-analytics/analytics-vendors-list.md
Labels: cla: yes

#30662 Remove TODO for closed issue
  test/integration/test-amp-carousel.js
Labels: cla: yes

#30567 ✨ Set default orientation in gyroscope mode
  extensions/amp-story-360/0.1/amp-story-360.js
Labels: cla: yes

#30524 Add SSR experiments to a4a eid
  ads/google/a4a/test/test-traffic-experiments.js
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/traffic-experiments.js
  ads/google/a4a/utils.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  src/string.js
Labels: cla: yes

#30652 Fix story stretched poster images by removing media pool default sources.
  extensions/amp-story/1.0/default-media.js
  extensions/amp-story/1.0/media-pool.js
  extensions/amp-story/1.0/media-tasks.js
Labels: cla: yes

#30572 ✨ Remixd AMP ad-tag implementation #30030
  3p/integration.js
  ads/_config.js
  ads/remixd.js
  ads/remixd.md
  examples/ads.amp.esm.html
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
  validator/testdata/feature_tests/ads.html
  validator/testdata/feature_tests/ads.out
Labels: WG: caching, cla: yes

#30683 ♻️ onPageNavigation_ method in 360 component
  extensions/amp-story-360/0.1/amp-story-360.js
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#30684 Change storage impl OWNERS to wg-components
  src/OWNERS
Labels: cla: yes

#30685 🏗 Bento owners
  css/OWNERS
  extensions/OWNERS
Labels: cla: yes

#30688 Send document canonicalUrl with sendCsi viewer events.
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#30698 🏗 Fix errors in new server transforms and make logs less noisy
  build-system/server/new-server/transforms/tsconfig.json
  build-system/server/new-server/transforms/utilities/script.ts
Labels: WG: infra, cla: yes

#30644 ✨ [bento][amp-accordion] Adding a11y to bento accordion
  extensions/amp-accordion/1.0/accordion.js
  extensions/amp-accordion/1.0/amp-accordion.js
  extensions/amp-accordion/1.0/test/test-accordion.js
  extensions/amp-accordion/1.0/test/test-amp-accordion.js
  src/utils/id-generator.js
Labels: cla: yes

#30627 resources-impl: fix alwayFixed
  src/service/resource.js
  test/unit/test-resource.js
Labels: P1: High Priority, Type: Bug, cla: yes

#30152 ✨ Consent Metadata macros in ads RTC and amp-analytics
  build-system/server/app.js
  examples/amp-consent/amp-consent-amp-ad.amp.html
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-analytics/0.1/test/test-requests.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/test/test-vendors.js
  extensions/amp-analytics/0.1/variables.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-client-side.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side-expire-cache.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js
  src/consent.js
  test/fixtures/e2e/amp-consent/amp-consent-basic-uses.amp.html
Labels: cla: yes

#30465 Remove consent string restriction on metadata
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
Labels: cla: yes

#30706 Amp-ad Doubleclick: Remove frc parameter
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#30689 Refactor button rendering for story ads (pt 2)
  extensions/amp-story-auto-ads/0.1/story-ad-page.js
  extensions/amp-story-auto-ads/0.1/story-ad-ui.js
  extensions/amp-story-auto-ads/0.1/test/test-story-ad-ui.js
Labels: cla: yes

#30700 🏗 Pre-emptive lint fixes + clean up
  .prettierrc
  build-system/tasks/lint.js
  contributing/TESTING.md
  yarn.lock
Labels: WG: infra, cla: yes

#30676 [amp-story-player] Fetch more stories from endpoint
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#30732 📖 Fix dead link in AMP dev docs
  contributing/DEVELOPING.md
  contributing/component-validator-rules.md
  contributing/contributing-code.md
  contributing/getting-started-e2e.md
Labels: Related to: Documentation, WG: components

#30694 🏗 Migrate `amphtml` package management from `yarn` to `npm`
  .eslintignore
  .github/workflows/continuous-integration-workflow.yml
  .gitignore
  .lando.yml
  .npmrc
  .yarnrc
  OWNERS
  build-system/common/check-package-manager.js
  build-system/common/process.js
  build-system/common/utils.js
  build-system/pr-check/build-targets.js
  build-system/pr-check/build.js
  build-system/pr-check/checks.js
  build-system/pr-check/dist-bundle-size.js
  build-system/pr-check/module-dist-bundle-size.js
  build-system/pr-check/npm-checks.js
  build-system/pr-check/validator-tests.js
  build-system/tasks/coverage-map/package-lock.json
  build-system/tasks/coverage-map/yarn.lock
  build-system/tasks/e2e/package-lock.json
  build-system/tasks/e2e/yarn.lock
  build-system/tasks/karma.conf.js
  build-system/tasks/performance/package-lock.json
  build-system/tasks/performance/yarn.lock
  build-system/tasks/pr-check.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/storybook/.gitignore
  build-system/tasks/storybook/package-lock.json
  build-system/tasks/update-packages.js
  build-system/tasks/visual-diff/index.js
  build-system/tasks/visual-diff/package-lock.json
  build-system/tasks/visual-diff/yarn.lock
  contributing/TESTING.md
  contributing/buildcop.md
  contributing/contributing-code.md
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
  package-lock.json
  package.json
  third_party/react-dates/debug.sh
  validator/build.py
  validator/js/nodejs/package-lock.json
  validator/js/nodejs/yarn.lock
  validator/js/webui/build.py
  validator/js/webui/package-lock.json
  validator/js/webui/yarn.lock
  validator/package-lock.json
  validator/yarn.lock
  yarn.lock
Labels: WG: infra, cla: yes

#30502 ✨ [amp-story-player] Initial code for reacting to custom UI API from the system layer
  examples/amp-story/cta-layer-outlink.html
  examples/visual-tests/amp-story/amp-story-cta-layer.html
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/test/test-amp-story-system-layer.js
  src/localized-strings.js
Labels: cla: yes

#30746 🏗 Add `OWNERS` files to simplify package updates in `amphtml` subdirs
  extensions/amp-access/0.1/iframe-api/OWNERS
  src/purifier/OWNERS
  third_party/amp-toolbox-cache-url/OWNERS
Labels: WG: infra

#30673 revert the `showStack` change
  build-system/server/typescript-compile.js
Labels: cla: yes

#30681 pass fixture files through the postHTML transformer code
  build-system/tasks/integration.js
  build-system/tasks/vendor-configs.js
  test/fixtures/3p-ad.html
  test/fixtures/actions.html
  test/fixtures/amp-cupcake-ad.html
  test/fixtures/amp-pan-zoom.html
  test/fixtures/boilerplate-new-visibility.html
  test/fixtures/boilerplate-old-opacity.html
  test/fixtures/configuration.html
  test/fixtures/doubleclick.html
  test/fixtures/errors.html
  test/fixtures/images-ie.html
  test/fixtures/images.html
  test/fixtures/overflow.html
  test/fixtures/released.html
  test/fixtures/script-load-extension-footer-v0-footer.html
  test/fixtures/script-load-extension-head-v0-head.html
  test/fixtures/script-load-extensions.html
  test/fixtures/script-load-v0-footer-extension-footer.html
  test/fixtures/script-load-v0-head-extension-footer.html
  test/fixtures/script-load-v0-head-extension-head.html
  test/fixtures/video-players.html
  test/fixtures/visibility-state.html
  test/integration/test-extensions-loading.js
Labels: cla: yes

#30744 use fancy-log.info()
  validator/js/gulpjs/index.js
Labels: WG: caching

#30760 Release gulp-amphtml-validator @1.0.6
  validator/js/gulpjs/README.md
  validator/js/gulpjs/package.json
Labels: WG: caching

#30622 ✨ [bento][amp-accordion] CSS Port draft for amp accordion (PR #2)
  extensions/amp-accordion/1.0/accordion.js
  extensions/amp-accordion/1.0/accordion.jss.js
  extensions/amp-accordion/1.0/accordion.type.js
  extensions/amp-accordion/1.0/amp-accordion.css
  extensions/amp-accordion/1.0/amp-accordion.js
  extensions/amp-accordion/1.0/test/test-accordion.js
  extensions/amp-accordion/1.0/test/test-amp-accordion.js
Labels: cla: yes

#30773 Validator rollup for 20201020
  extensions/amp-onetap-google/validator-amp-onetap-google.protoascii
  validator/testdata/transformed_feature_tests/amp-img.html
  validator/testdata/transformed_feature_tests/amp-img.out
  validator/validator-main.protoascii
Labels: WG: caching

#30646 Bento Carousel: `advanceCount` and `visibleCount` props
  extensions/amp-base-carousel/1.0/amp-base-carousel.js
  extensions/amp-base-carousel/1.0/arrow.js
  extensions/amp-base-carousel/1.0/base-carousel.js
  extensions/amp-base-carousel/1.0/base-carousel.jss.js
  extensions/amp-base-carousel/1.0/base-carousel.type.js
  extensions/amp-base-carousel/1.0/scroller.js
  extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
  extensions/amp-base-carousel/1.0/storybook/Basic.js
  extensions/amp-base-carousel/1.0/test-e2e/helpers.js
  extensions/amp-base-carousel/1.0/test-e2e/test-carousel.js
  extensions/amp-base-carousel/1.0/test-e2e/test-grouping.js
  extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
  extensions/amp-base-carousel/1.0/test/test-base-carousel.js
  extensions/amp-inline-gallery/1.0/test/test-amp-inline-gallery.js
  test/manual/amp-base-carousel/1.0/grouping-move-by-2.amp.html
Labels: cla: yes

#30639 ✨ Added support for attribute prefixes in PreactBaseElement
  src/preact/base-element.js
  test/unit/preact/test-base-element-mapping.js
Labels: cla: yes

#30535 unit tests: align with prod-config
  src/service/resources-impl.js
  test/_init_tests.js
Labels: WG: infra, cla: yes

#30618 carousel: remove onViewportCallback
  extensions/amp-carousel/0.1/base-carousel.js
  extensions/amp-carousel/0.1/base-slides.js
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/0.1/test/test-base-slide.js
Labels: cla: yes

#30516 ✨ Freestar Callout Vendors GDPR Consent Update
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#30797 Sync for validator/cpp/engine
  validator/cpp/engine/BUILD
  validator/cpp/engine/WORKSPACE
  validator/cpp/engine/parse-srcset.cc
  validator/cpp/engine/scripts/BUILD
  validator/cpp/engine/testing-utils.cc
Labels: WG: caching

#30375 Backup CID in Storage for non-proxy origin
  build-system/tasks/presubmit-checks.js
  spec/amp-var-substitutions.md
  src/service/cid-impl.js
  src/service/storage-impl.js
  src/service/url-replacements-impl.js
  test/unit/test-cid.js
  test/unit/test-storage.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#30832 🐛 Add "controls" to amp-story-360 validator
  extensions/amp-story-360/0.1/test/validator-amp-story-360.html
  extensions/amp-story-360/0.1/test/validator-amp-story-360.out
  extensions/amp-story-360/validator-amp-story-360.protoascii
Labels: WG: caching

#30637 ♻️ springAds: refactoring computeInMasterFrame
  ads/springAds.js
Labels: cla: yes

#30846 📖 Update Travis URLs from `.org` to `.com`
  README.md
  build-system/server/app-index/header-links.js
  contributing/DEVELOPING.md
  contributing/buildcop.md
  contributing/getting-started-e2e.md
  contributing/release-schedule.md
  extensions/amp-iframe/0.1/amp-iframe.js
Labels: Related to: Documentation, WG: infra

#30670 🐛 Ads was missing 'height' attribute
  extensions/amp-auto-ads/0.1/alright-network-config.js
  extensions/amp-auto-ads/0.1/attributes.js
  extensions/amp-auto-ads/0.1/test/test-alright-network-config.js
  extensions/amp-auto-ads/0.1/test/test-attributes.js
Labels: cla: yes

#30677 ✨ amp-autocomplete: Add support for making object items available in autocomplete select events
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
  extensions/amp-autocomplete/amp-autocomplete.md
Labels: WG: caching, cla: yes

#30847 remove unnecessary spec_name from script tagspecs
  extensions/amp-ad-custom/validator-amp-ad-custom.protoascii
  extensions/amp-video-docking/validator-amp-video-docking.protoascii
Labels: WG: caching

#30827 amp-list: single-item a11y warning.
  extensions/amp-list/0.1/amp-list.js
Labels: Component: amp-list, P3: When Possible

#30647 AMP Video Players: use IntersectionObserver instead of viewportCallback + scroll detection.
  extensions/amp-3q-player/0.1/amp-3q-player.js
  extensions/amp-brightcove/0.1/amp-brightcove.js
  extensions/amp-dailymotion/0.1/amp-dailymotion.js
  extensions/amp-ima-video/0.1/amp-ima-video.js
  extensions/amp-mowplayer/0.1/amp-mowplayer.js
  extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js
  extensions/amp-ooyala-player/0.1/amp-ooyala-player.js
  extensions/amp-ooyala-player/0.1/test/test-amp-ooyala.js
  extensions/amp-powr-player/0.1/amp-powr-player.js
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-wistia-player/0.1/amp-wistia-player.js
  extensions/amp-youtube/0.1/amp-youtube.js
  extensions/amp-youtube/0.1/test/test-amp-youtube.js
  src/service/video-manager-impl.js
  src/viewport-observer.js
  test/integration/test-video-manager.js
  test/integration/test-video-players-helper.js
  testing/fake-dom.js
Labels: Component: amp-video & interface, WG: components, cla: yes

#30667 Bento Carousel: `mixedLength` prop
  extensions/amp-base-carousel/1.0/amp-base-carousel.js
  extensions/amp-base-carousel/1.0/base-carousel.js
  extensions/amp-base-carousel/1.0/base-carousel.type.js
  extensions/amp-base-carousel/1.0/scroller.js
  extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
  extensions/amp-base-carousel/1.0/storybook/Basic.js
Labels: cla: yes

#30597 StreamGallery: Initial implementation
  build-system/compile/bundles.config.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-base-carousel/1.0/base-carousel.js
  extensions/amp-base-carousel/1.0/scroller.js
  extensions/amp-stream-gallery/1.0/amp-stream-gallery.js
  extensions/amp-stream-gallery/1.0/storybook/Basic.amp.js
  extensions/amp-stream-gallery/1.0/storybook/Basic.js
  extensions/amp-stream-gallery/1.0/stream-gallery.js
  extensions/amp-stream-gallery/1.0/stream-gallery.jss.js
  extensions/amp-stream-gallery/1.0/stream-gallery.type.js
  extensions/amp-stream-gallery/1.0/test/test-amp-stream-gallery.js
  extensions/amp-stream-gallery/1.0/test/test-stream-gallery.js
Labels: cla: yes

#30230 ✨ Bento port of amp-instagram
  build-system/compile/bundles.config.js
  extensions/amp-instagram/1.0/amp-instagram.js
  extensions/amp-instagram/1.0/instagram.js
  extensions/amp-instagram/1.0/instagram.type.js
  extensions/amp-instagram/1.0/storybook/Basic.amp.js
  extensions/amp-instagram/1.0/storybook/Basic.js
  extensions/amp-instagram/1.0/test/test-amp-instagram.js
  extensions/amp-instagram/1.0/test/test-instagram.js
Labels: cla: yes
