Repository ampproject/amphtml, pull requests merged in 2020-09, with the labels that each got.

#30070 Remove use of clamp due to dependency on getMode
  extensions/amp-base-carousel/1.0/base-carousel.js
Labels: cla: yes

#30072 📖 Update AMP4Email documentation on markup size limit
  spec/email/amp-email-format.md
Labels: cla: yes

#30053 🐛 Fix RTL display of mobile screen reader back button
  extensions/amp-story/1.0/amp-story.css
Labels: WG: stories, cla: yes

#29703 🚀 [amp-story-player] Wait for first story to load before loading next ones
  extensions/amp-story/1.0/amp-story.js
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#30081 Cleanup AdSense/Doubleclick round adx/ady
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#30078 Context: rename needsParent to recursive
  src/context/prop.js
  src/context/prop.type.js
  src/context/values.js
  test/unit/context/test-node-components.js
  test/unit/context/test-node-values.js
Labels: cla: yes

#30080 ♻️ Change amp-story-interactive version to 0.1
  build-system/compile/bundles.config.js
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/dep-check-config.js
  examples/amp-story/interactive_polls.html
  examples/amp-story/interactive_quizzes.html
  examples/amp-story/interactive_results.html
  examples/amp-story/interactives.html
  examples/amp-story/quiz.html
  examples/visual-tests/amp-story/amp-story-interactive-quiz-sizing-positioning.html
  extensions/amp-story-interactive/0.1/amp-story-interactive-abstract.js
  extensions/amp-story-interactive/0.1/amp-story-interactive-binary-poll.css
  extensions/amp-story-interactive/0.1/amp-story-interactive-binary-poll.js
  extensions/amp-story-interactive/0.1/amp-story-interactive-poll.css
  extensions/amp-story-interactive/0.1/amp-story-interactive-poll.js
  extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.css
  extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.js
  extensions/amp-story-interactive/0.1/amp-story-interactive-results.css
  extensions/amp-story-interactive/0.1/amp-story-interactive-results.js
  extensions/amp-story-interactive/0.1/amp-story-interactive.css
  extensions/amp-story-interactive/0.1/amp-story-interactive.js
  extensions/amp-story-interactive/0.1/interactive-confetti.js
  extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-binary-poll.js
  extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-quiz.js
  extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-results.js
  extensions/amp-story-interactive/0.1/test/test-amp-story-interactive.js
  extensions/amp-story-interactive/0.1/test/validator-amp-story-interactive-poll.html
  extensions/amp-story-interactive/0.1/test/validator-amp-story-interactive-poll.out
  extensions/amp-story-interactive/0.1/test/validator-amp-story-interactive-quiz.html
  extensions/amp-story-interactive/0.1/test/validator-amp-story-interactive-quiz.out
  extensions/amp-story-interactive/0.1/test/validator-amp-story-interactive-results.html
  extensions/amp-story-interactive/0.1/test/validator-amp-story-interactive-results.out
  extensions/amp-story-interactive/0.1/test/validator-amp-story-interactive-valid.html
  extensions/amp-story-interactive/0.1/test/validator-amp-story-interactive-valid.out
  extensions/amp-story-interactive/0.1/utils.js
  extensions/amp-story-interactive/README.md
  extensions/amp-story-interactive/validator-amp-story-interactive.protoascii
  extensions/amp-story/1.0/amp-story-store-service.js
Labels: P1: High Priority, Type: Bug, WG: stories, cla: yes

#30013 SwG Release 0.1.22.119
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#30073 fixed code sample
  extensions/amp-action-macro/amp-action-macro.md
Labels: cla: yes

#30027 Support server-side-rendered shadow roots
  src/css.js
  src/dom.js
  src/preact/base-element.js
  src/preact/index.js
  test/unit/preact/test-base-element.js
Labels: cla: yes

#30069 🐛 [amp-story-player] Fix fragment param issue
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#30065 jss: make classname deterministic
  build-system/babel-plugins/babel-plugin-transform-jss/index.js
  build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-jss-var/output.mjs
  build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/input.js
  build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/output.mjs
  build-system/babel-plugins/babel-plugin-transform-jss/test/index.js
  extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
Labels: cla: yes

#29823 🖍 [amp-story] Fix vertical margins for tweets
  examples/visual-tests/amp-story/amp-story-tooltip.html
  examples/visual-tests/amp-story/amp-story-tooltip.js
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#30094 🏗 Catch errors during post-closure babel transforms
  build-system/compile/post-closure-babel.js
Labels: cla: yes

#30004 🏗 Add babel-plugin-istanbul to pre-closure steps with `gulp dist --coverage`
  build-system/babel-config/pre-closure-config.js
  build-system/babel-config/unminified-config.js
  build-system/tasks/dist.js
  build-system/tasks/helpers.js
  package.json
  yarn.lock
Labels: cla: yes

#30087 updated to match template
  extensions/amp-beopinion/amp-beopinion.md
  extensions/amp-bodymovin-animation/amp-bodymovin-animation.md
  extensions/amp-brid-player/amp-brid-player.md
  extensions/amp-brightcove/amp-brightcove.md
  extensions/amp-byside-content/amp-byside-content.md
Labels: cla: yes

#30088 Updated format to match template
  extensions/amp-connatix-player/amp-connatix-player.md
  extensions/amp-dailymotion/amp-dailymotion.md
  extensions/amp-delight-player/amp-delight-player.md
  extensions/amp-embedly-card/amp-embedly-card.md
  extensions/amp-gfycat/amp-gfycat.md
Labels: cla: yes

#30089 updated to match template
  extensions/amp-facebook-comments/amp-facebook-comments.md
  extensions/amp-facebook-like/amp-facebook-like.md
  extensions/amp-facebook-page/amp-facebook-page.md
  extensions/amp-facebook/amp-facebook.md
  extensions/amp-gist/amp-gist.md
Labels: cla: yes

#30098 ✨ [amp-story-player] adds `noNextStory` event
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#30077 Inline gallery: AMP components with context propagation
  build-system/compile/bundles.config.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-base-carousel/1.0/amp-base-carousel.js
  extensions/amp-base-carousel/1.0/base-carousel.js
  extensions/amp-base-carousel/1.0/carousel-props.js
  extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
  extensions/amp-inline-gallery/1.0/amp-inline-gallery-pagination.js
  extensions/amp-inline-gallery/1.0/amp-inline-gallery.js
  extensions/amp-inline-gallery/1.0/pagination.js
  extensions/amp-inline-gallery/1.0/storybook/Basic.amp.js
  extensions/amp-inline-gallery/1.0/test/test-amp-inline-gallery.js
  extensions/amp-story/1.0/test/test-amp-story.js
  src/preact/base-element.js
  test/unit/preact/test-base-element.js
  testing/test-helper.js
Labels: cla: yes

#30104 Updated format to match template
  extensions/amp-google-document-embed/amp-google-document-embed.md
  extensions/amp-google-vrview-image/amp-google-vrview-image.md
  extensions/amp-hulu/amp-hulu.md
  extensions/amp-ima-video/amp-ima-video.md
  extensions/amp-imgur/amp-imgur.md
Labels: cla: yes

#30103 ✨ [amp-story-player] adds `noPreviousStory` event
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#30106 ♻️ amp-subscriptions-google: Renames glaa_ params to gaa_
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Labels: cla: yes

#30100 ♻️ amp-subscriptions-google: Starts using new encryption param
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
Labels: cla: yes

#29931 ✨Interactive size adapts to screen size with ems
  examples/amp-story/interactive_results.html
  examples/amp-story/interactive_size.html
  examples/visual-tests/amp-story/amp-story-interactive-quiz-sizing-positioning.html
  extensions/amp-story-interactive/0.1/amp-story-interactive-binary-poll.css
  extensions/amp-story-interactive/0.1/amp-story-interactive-binary-poll.js
  extensions/amp-story-interactive/0.1/amp-story-interactive-poll.css
  extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.css
  extensions/amp-story-interactive/0.1/amp-story-interactive-results.css
  extensions/amp-story-interactive/0.1/amp-story-interactive.css
  extensions/amp-story-interactive/README.md
  extensions/amp-story/1.0/amp-story.css
Labels: WG: stories, cla: yes

#30102 Declare types for AmpContext
  src/preact/base-element.js
  src/preact/context.js
  src/preact/context.type.js
  src/preact/slot.js
  src/preact/utils.js
Labels: cla: yes

#30018 ♿ TetraLogical: Accessibility notes for the documentation
  contributing/DESIGN_PRINCIPLES.md
  contributing/contributing-code.md
  contributing/getting-started-e2e.md
Labels: cla: yes

#30111 🏗Add `gulp browse` task to open browser to URL
  build-system/tasks/browse.js
  gulpfile.js
Labels: cla: yes

#30123 SwG Release 0.1.22.120
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#30105 🐛 Report zero visibility for zero size element
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-analytics/0.1/visibility-manager.js
Labels: cla: yes

#29800 🏗 Added support for ESM and SxG environment in `coverage-map`
  build-system/tasks/coverage-map/index.js
Labels: cla: yes

#29696 Add error message for unparseable checkConsentHref response
  extensions/amp-consent/0.1/amp-consent.js
Labels: cla: yes

#30079 ✨ Restrict amp-ad sticky ad size to 20% viewport size and 50% height
  extensions/amp-ad/0.1/amp-ad-ui.js
Labels: cla: yes

#30116 📖 Improved readme for sizing interactive components
  extensions/amp-story-interactive/README.md
Labels: cla: yes

#30127 🐛 Mgid fix validation error
  ads/idealmedia.js
  ads/lentainform.js
  ads/mgid.js
Labels: cla: yes

#29863 ✨Add better validation to interactive components
  extensions/amp-story-interactive/0.1/test/validator-amp-story-interactive-results.html
  extensions/amp-story-interactive/0.1/test/validator-amp-story-interactive-results.out
  extensions/amp-story-interactive/validator-amp-story-interactive.protoascii
Labels: WG: caching, cla: yes

#30154 Remove survey
  README.md
Labels: cla: yes

#29869 ✨ Remove consent info size restriction for docs served from origin
  examples/amp-consent/diy-consent.html
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  extensions/amp-consent/integrating-consent.md
  src/service/storage-impl.js
Labels: cla: yes

#30115 🐛 jss transform: support watch mode by allowing dupes if same file
  build-system/babel-plugins/babel-plugin-transform-jss/create-hash.js
  build-system/babel-plugins/babel-plugin-transform-jss/index.js
  build-system/babel-plugins/babel-plugin-transform-jss/test/index.js
Labels: cla: yes

#29172 Visibility Trigger for Non AMP Elements
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-analytics/0.1/events.js
  extensions/amp-analytics/0.1/test/test-analytics-root.js
  extensions/amp-analytics/0.1/test/test-events.js
  extensions/amp-analytics/amp-analytics.md
  test/manual/amp-analytics/amp-analytics-multi-selector.html
Labels: cla: yes

#30163 ♿ Edit tip wordage
  extensions/amp-story/1.0/_locales/default.js
  extensions/amp-story/1.0/_locales/en.js
Labels: cla: yes

#30153 ✨ Interactive poll can have options with two lines
  examples/amp-story/interactive_polls.html
  extensions/amp-story-interactive/0.1/amp-story-interactive-poll.css
  extensions/amp-story-interactive/0.1/amp-story-interactive-poll.js
  extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-poll.js
Labels: cla: yes

#29636 ✨ Consent: Pass consent string and metadata to amp-iframe
  examples/amp-consent/amp-consent-iframe.amp.html
  examples/amp-consent/amp-consent-iframe.embed.html
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
  extensions/amp-iframe/amp-iframe.md
  src/3p-frame-messaging.js
  test/fixtures/served/iframe.html
Labels: cla: yes

#30151 Make ads/ui wg 3p iframe related code owner
  src/OWNERS
Labels: cla: yes

#30119 Enable `amp-accordion-display-locking` experiment on 1% traffic
  build-system/global-configs/prod-config.json
Labels: cla: yes

#30166 📖 Update gdprApplies Comment
  extensions/amp-consent/0.1/consent-info.js
Labels: cla: yes

#30170 [amp-story-player] Add allow=autoplay to iframes
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#30125 Migrate pagination styles to JSS
  extensions/amp-base-carousel/1.0/base-carousel.jss.js
  extensions/amp-inline-gallery/1.0/amp-inline-gallery-pagination.js
  extensions/amp-inline-gallery/1.0/pagination.js
  extensions/amp-inline-gallery/1.0/pagination.jss.js
  extensions/amp-inline-gallery/1.0/storybook/Basic.amp.js
  src/preact/component/component.type.js
  src/preact/component/contain.js
  src/preact/component/index.js
  src/preact/component/wrapper.js
Labels: cla: yes

#30101 amp-list: support amp-state and amp-script for load-more
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test-e2e/test-function-src.js
  extensions/amp-list/0.1/test/test-amp-list.js
  test/fixtures/e2e/amp-list/amp-list-function-load-more.html
Labels: cla: yes

#30141 copy worker-dom files from the new amp-production directory when it exists
  build-system/compile/sources.js
  build-system/tasks/extension-helpers.js
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
  package.json
  yarn.lock
Labels: cla: yes

#30168 🐛 Let buttons flow RTL naturally
  extensions/amp-story/1.0/amp-story-system-layer.css
Labels: WG: stories, cla: yes

#30130 🐛 [amp-base-carousel] fix for next arrow not hidden properly when visible-count > 1
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
Labels: cla: yes

#30173 ✨ Adding translation support for score
  extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.js
  extensions/amp-story/1.0/_locales/default.js
  extensions/amp-story/1.0/_locales/en.js
  src/localized-strings.js
Labels: cla: yes

#30181 ❄️ [bento][amp-time-ago] Skip flaky tests in amp-timeago for now
  extensions/amp-timeago/1.0/test/test-amp-timeago.js
Labels: cla: yes

#30148 Validator rollup
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#30149 Sync from Google
  validator/cpp/htmlparser/strings.cc
Labels: WG: caching, cla: yes

#29619 ✅ [bento][amp-social-share] First draft test amp-social-share
  extensions/amp-social-share/1.0/test/test-amp-social-share.js
  extensions/amp-social-share/1.0/test/test-social-share.js
Labels: cla: yes

#30010 📖 Add interactive results animation to examples
  examples/amp-story/interactive_quizzes.html
  examples/amp-story/interactive_results.html
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#30188 intersection-observer: don't use premeasure if there is a more recent measure
  src/service/resource.js
Labels: cla: yes

#29848 ✨Adding ConsentManager CMP to amp-consent
  examples/amp-consent/cmp-vendors.amp.html
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/amp-consent.md
  extensions/amp-consent/cmps/consentmanager.md
Labels: cla: yes

#30186 Unblock Preact tests that are executed against fake clock
  extensions/amp-date-display/1.0/test/test-amp-date-display.js
  extensions/amp-date-display/1.0/test/test-date-display.js
  extensions/amp-social-share/1.0/test/test-social-share.js
  extensions/amp-timeago/1.0/test/test-amp-timeago.js
Labels: cla: yes

#29876 ✨Consent: Pass consent string and metadata to amp-delight-player
  extensions/amp-delight-player/0.1/amp-delight-player.js
Labels: cla: yes

#30174 🐛 Fixing window reference for amp-ad type kargo
  ads/kargo.js
Labels: cla: yes

#29661 🚮 Remove RENDLE_ON_IDLE experiment logic
  ads/google/a4a/utils.js
  build-system/global-configs/prod-config.json
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  src/service/resources-impl.js
Labels: cla: yes

#30187 Timeago: fix placeholder and wrapper
  extensions/amp-timeago/1.0/amp-timeago.js
  extensions/amp-timeago/1.0/storybook/Basic.amp.js
  extensions/amp-timeago/1.0/storybook/Basic.js
  extensions/amp-timeago/1.0/test/test-amp-timeago.js
  extensions/amp-timeago/1.0/timeago.js
  extensions/amp-timeago/1.0/timeago.type.js
  src/preact/base-element.js
Labels: cla: yes

#29770 ♻️ Moved animateFixedLayer_ into fixed layer code, and added SxG modes for animateScrollIntoView.
  build-system/tasks/presubmit-checks.js
  src/service/fixed-layer.js
  src/service/viewport/viewport-impl.js
  test/unit/test-viewport.js
Labels: cla: yes

#30198 🧪 Turn off no signing in canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#29912 Add page-experience.md
  .github/ISSUE_TEMPLATE/page-experience.md
Labels: cla: yes

#30117 🐛 Pagination button mobile screen reader support
  css/Z_INDEX.md
  extensions/amp-story/1.0/amp-story-desktop-panels.css
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/pagination-buttons.css
  extensions/amp-story/1.0/pagination-buttons.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: WG: stories, cla: yes

#30192 ♻️ Move tests and reference implementation to use promise on context.requestResize API
  ads/_ping_.js
  examples/ac-creative.js
  examples/ampcontext-creative-json.html
  examples/ampcontext-creative.html
  test/integration/test-amp-ad-3p.js
Labels: cla: yes

#30201 Move no-signing to RTV exp
  build-system/global-configs/experiments-config.json
  build-system/tasks/e2e/amp-driver.js
  build-system/tasks/e2e/describes-e2e.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#30169 🧪 Remove and launch sticky ad safety area css experiment
  ads/google/a4a/utils.js
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.css
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#30092 ✨ [bento][amp-date-countdown] Initial Preact component for amp-date-countdown
  extensions/amp-date-countdown/1.0/date-countdown.js
  extensions/amp-date-countdown/1.0/date-countdown.type.js
  extensions/amp-date-countdown/1.0/messages.js
Labels: cla: yes

#30161 Update callout-vendors.js
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-a4a/rtc-documentation.md
  extensions/amp-a4a/rtc-publisher-implementation-guide.md
Labels: cla: yes

#30191 📖 [bento][amp-social-share] Clean up storybooks for social share
  extensions/amp-social-share/0.1/storybook/Basic.amp.js
  extensions/amp-social-share/1.0/storybook/Basic.amp.js
  extensions/amp-social-share/1.0/storybook/Basic.js
Labels: cla: yes

#30205 ✨ Added new ad network vlyby
  3p/integration.js
  ads/_config.js
  ads/vlyby.js
  ads/vlyby.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#30202 Validator rollup
  extensions/amp-story-interactive/validator-amp-story-interactive.protoascii
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#30093 Ensure auto-injected script tags are parsed as modules in ESM mode
  src/service/extensions-impl.js
Labels: cla: yes

#30224 🐛 Fix story ads in no signing exp
  extensions/amp-story-auto-ads/0.1/story-ad-page.js
  extensions/amp-story-auto-ads/0.1/utils.js
Labels: cla: yes

#30124 Extend timeout for flakey test
  extensions/amp-viewer-integration/0.1/test/integration/test-messaging-handshake.js
Labels: Related to: Flaky Tests, cla: yes

#29743 ✨Add new owners file for NWS fast fetch
  extensions/amp-ad-network-nws-impl/OWNERS
Labels: cla: yes

#30222 --files flag windows support
  build-system/common/utils.js
Labels: cla: yes

#29831 🧪Fully launch json targeting expansion experiment.
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#30220 Drop keyframes based on physics
  extensions/amp-story/1.0/animation-presets.js
Labels: cla: yes

#30227 📖 [bento][amp-date-countdown] Preact storybook for amp-date-countdown
  extensions/amp-date-countdown/1.0/storybook/Basic.js
Labels: cla: yes

#30235 Fix yield pro use of implicit this
  ads/yieldpro.js
Labels: cla: yes

#30237 🐛[amp-story-player] Fix CSS bug
  css/amp-story-player-iframe.css
Labels: cla: yes

#30228 Multi-attribute prop bindings for date components
  build-system/tasks/presubmit-checks.js
  extensions/amp-date-display/1.0/amp-date-display.js
  extensions/amp-date-display/1.0/date-display.js
  extensions/amp-date-display/1.0/date-display.type.js
  extensions/amp-date-display/1.0/storybook/Basic.js
  extensions/amp-date-display/1.0/test/test-amp-date-display.js
  extensions/amp-date-display/1.0/test/test-date-display.js
  extensions/amp-timeago/1.0/amp-timeago.js
  extensions/amp-timeago/1.0/storybook/Basic.js
  extensions/amp-timeago/1.0/test/test-amp-timeago.js
  extensions/amp-timeago/1.0/timeago.js
  extensions/amp-timeago/1.0/timeago.type.js
  src/preact/base-element.js
  src/preact/component/contain.js
  src/preact/component/wrapper.js
  src/utils/date.js
  test/unit/preact/test-base-element.js
  test/unit/utils/test-date.js
Labels: cla: yes

#30226 amp-date-display: render via __html string
  build-system/externs/preact.extern.js
  examples/amp-date-display.amp.html
  extensions/amp-date-display/1.0/amp-date-display.js
  extensions/amp-date-display/1.0/async-render.js
  extensions/amp-date-display/1.0/date-display.js
  extensions/amp-date-display/1.0/date-display.type.js
  extensions/amp-date-display/1.0/render-dom-tree.js
  extensions/amp-date-display/1.0/storybook/Basic.amp.js
  extensions/amp-date-display/1.0/storybook/Basic.js
  extensions/amp-date-display/1.0/test/test-amp-date-display.js
  extensions/amp-date-display/1.0/test/test-date-display.js
  extensions/amp-mustache/0.1/amp-mustache.js
  extensions/amp-mustache/0.1/test/test-amp-mustache.js
  extensions/amp-mustache/0.2/amp-mustache.js
  extensions/amp-mustache/0.2/test/test-amp-mustache.js
  src/preact/base-element.js
  src/preact/component/component.type.js
  src/preact/component/index.js
  src/preact/component/renderer.js
  src/service/template-impl.js
  test/unit/preact/component/test-renderer.js
  test/unit/preact/test-base-element.js
  test/unit/test-template.js
Labels: cla: yes

#30233 ♻️ Reduce size of interactive extension
  extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.css
  extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.js
Labels: WG: stories, cla: yes

#30206 jss transform: transform via postcss
  build-system/babel-plugins/babel-plugin-transform-jss/index.js
  build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-jss-var/output.mjs
  build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/input.js
  build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/output.mjs
  build-system/tasks/create-golden-css/index.js
  build-system/tasks/jsify-css.js
Labels: cla: yes

#30232 ✨ Add prebidappnexuspsp as a vendor to RTC config
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-a4a/rtc-documentation.md
  extensions/amp-a4a/rtc-publisher-implementation-guide.md
Labels: cla: yes

#29985 ✨ amp-a4a: declare Future Plc as a new vendor
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-a4a/rtc-documentation.md
  extensions/amp-a4a/rtc-publisher-implementation-guide.md
Labels: cla: yes

#30138 ✨ [amp-story-360] Add scene orientation support (fixes #29514)
  examples/amp-story-360.amp.html
  extensions/amp-story-360/0.1/amp-story-360.js
  extensions/amp-story-360/0.1/test/validator-amp-story-360.html
  extensions/amp-story-360/0.1/test/validator-amp-story-360.out
  extensions/amp-story-360/validator-amp-story-360.protoascii
  third_party/zuho/README.amp
  third_party/zuho/zuho.js
Labels: cla: yes

#29486 ✨ VideoWrapper Preact component with autoplay and mediasession
  css/video-autoplay.css
  extensions/amp-audio/0.1/amp-audio.js
  extensions/amp-video/1.0/storybook/Basic.js
  extensions/amp-video/1.0/test/test-video-wrapper.js
  extensions/amp-video/1.0/video-wrapper.css.js
  extensions/amp-video/1.0/video-wrapper.js
  extensions/amp-video/1.0/video-wrapper.type.js
  src/mediasession-helper.js
  src/service/video-manager-impl.js
  test/unit/test-mediasession-helper.js
Labels: cla: yes

#30249 🐛 Fix ad index value in IMA video
  ads/ads.extern.js
  ads/google/imaVideo.js
  extensions/amp-ima-video/0.1/test/test-amp-ima-video.js
Labels: cla: yes

#30114 amp-iframe: Hide overflow element on resize
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
Labels: cla: yes

#30247 ❄️ Attempt to deflake messaging-handshake test
  extensions/amp-viewer-integration/0.1/test/integration/test-messaging-handshake.js
Labels: cla: yes

#30262 🏗 Increment cherry pick branch version by number of commits
  build-system/tasks/cherry-pick.js
Labels: cla: yes

#30264 🐛 Fix `Animation.animate` breakage caused by missing import.
  .eslintrc.js
  src/service/fixed-layer.js
  test/unit/test-fixed-layer.js
Labels: cla: yes

#30284 Revert "🐛 Report zero visibility for zero size element"
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-analytics/0.1/visibility-manager.js
Labels: cla: yes

#30277 🧪 Experimental code: Dial up the Adsense ad size optimization experiment to 10%.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#30287 ✨ Clone children as VNodes into component call
  src/preact/base-element.js
  test/unit/preact/test-base-element.js
Labels: cla: yes

#30279 🖍 System UI updates
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#30248 🐛 Also look at the content of the response when detecting Scroll
  extensions/amp-access-scroll/0.1/scroll-impl.js
Labels: cla: yes

#30099 🏗 Add support for `gulp serve --coverage` coverage collection endpoint
  build-system/server/app.js
  build-system/tasks/serve.js
  package.json
  yarn.lock
Labels: cla: yes

#30305 dependencies: bump worker-dom
  package.json
  yarn.lock
Labels: cla: yes

#30295 Support aspect-ratio CSS for layout=responsive
  build-system/tasks/storybook/amp-env/main.js
  builtins/storybook/amp-layout-with-aspect-ratio-css.amp.js
  builtins/storybook/amp-layout.amp.js
  css/ampshared.css
  src/layout.js
  test/unit/test-layout.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#30090 ✨ Update checkConsentHref for the iubenda <amp-consent> integration
  extensions/amp-consent/0.1/cmps.js
Labels: cla: yes

#30208 🚀 Separating BaseTemplate from template-impl.
  build-system/externs/amp.extern.js
  extensions/amp-mustache/0.1/amp-mustache.js
  extensions/amp-mustache/0.2/amp-mustache.js
  src/base-template.js
  src/runtime.js
  src/service/template-impl.js
  test/unit/test-runtime.js
  test/unit/test-template.js
Labels: cla: yes

#30306 Wait for scrolling before loading sticky ad
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
Labels: cla: yes

#30297 🏗 Lint for $ in animation-name
  .eslintrc.js
  build-system/eslint-rules/jss-animation-name.js
Labels: cla: yes

#30313 🐛 amp-auto-ads: Fix a typo in firstimpression.io network config
  extensions/amp-auto-ads/0.1/firstimpression.io-network-config.js
Labels: cla: yes

#30270 Added Adpushup callout_vendors.js
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-a4a/rtc-documentation.md
  extensions/amp-a4a/rtc-publisher-implementation-guide.md
Labels: cla: yes

#30185 amp-ad type broadstreetads: Support renderStart()
  ads/_config.js
  ads/broadstreetads.js
Labels: cla: yes

#29688 🚮 amp-list: remove experiment 'protocol-adapters'
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test-e2e/test-function-src.js
  extensions/amp-list/0.1/test/test-amp-list.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#30257 when in ESM mode, copy the the parent runtime CSS into the friendly iframe
  src/friendly-iframe-embed.js
Labels: cla: yes

#30299 🚀 Safari 14 Fixed the Web Animations API implementation
  extensions/amp-animation/0.1/install-polyfill.js
Labels: cla: yes

#30276 ♿ Added accessibility name to play pause button
  extensions/amp-story/1.0/_locales/default.js
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/amp-story-system-layer.js
  src/localized-strings.js
Labels: cla: yes

#30298 ♻️ Use JSS for video
  extensions/amp-video/1.0/autoplay.jss.js
  extensions/amp-video/1.0/test/test-video-wrapper.js
  extensions/amp-video/1.0/video-wrapper.js
Labels: cla: yes

#30316 ✨ Add amp-ad support for myoffrz
  3p/integration.js
  ads/_config.js
  ads/myoffrz.js
  ads/myoffrz.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#30296 Remove pause-iframe expriment
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
  extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
  src/iframe-helper.js
  test/unit/test-iframe-helper.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#30267 🐛 Inabox visibility reporting: listen to window resize event
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-analytics/0.1/visibility-manager.js
Labels: cla: yes

#30263 Remove cache and origin separation
  .github/ISSUE_TEMPLATE/page-experience.md
Labels: cla: yes

#30301 🧪 Enable build-in-chunks experiment in canary-config.json
  build-system/global-configs/canary-config.json
Labels: WG: performance, cla: yes

#30326 Social Share: update wrapper and propagate size from the AMP element
  extensions/amp-social-share/1.0/amp-social-share.js
  extensions/amp-social-share/1.0/social-share.js
Labels: cla: yes

#30329 ♻️ Storybook in Component Story Format
  extensions/amp-animation/0.1/storybook/Basic.amp.js
  extensions/amp-animation/0.1/storybook/Random.amp.js
  extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
  extensions/amp-date-display/1.0/storybook/Basic.amp.js
  extensions/amp-fit-text/1.0/storybook/Basic.amp.js
  extensions/amp-image-slider/0.1/storybook/Basic.amp.js
  extensions/amp-inline-gallery/1.0/storybook/Basic.amp.js
  extensions/amp-selector/1.0/storybook/Basic.amp.js
  extensions/amp-sidebar/0.1/storybook/Basic.amp.js
  extensions/amp-social-share/0.1/storybook/Basic.amp.js
  extensions/amp-social-share/1.0/storybook/Basic.amp.js
  extensions/amp-timeago/1.0/storybook/Basic.amp.js
  extensions/amp-youtube/0.1/storybook/Basic.amp.js
Labels: cla: yes

#30343 Upgrade @ampproject/storybook-addon to 1.1.2
  build-system/tasks/storybook/package.json
Labels: cla: yes

#30321 ContextNode: automatically re-discover changes in the shadow DOM on slotchange event
  src/context/node.js
  test/unit/context/test-node-discover.js
Labels: cla: yes

#30340 Validator Rollup
  validator/validator-main.protoascii
Labels: cla: yes

#30351 🖍 Cleanup autoplay JSS/fix :before, :after
  extensions/amp-video/1.0/autoplay.jss.js
Labels: cla: yes

#30332 ✨ Add a delay fetched fake vendor for test purposes
  3p/integration.js
  ads/_config.js
  ads/_fakedelayed_.js
  ads/_fakedelayed_.md
  examples/amp-ad/sticky-creative.html
  examples/amp-ad/sticky.html
  examples/amp-ad/sticky.js
Labels: cla: yes

#30347 ContextNode: groups API
  src/context/index.js
  src/context/node.js
  test/unit/context/test-node-discover.js
Labels: cla: yes

#29979 📖 Added note about data-colorscheme to amp-facebook-comments docs
  extensions/amp-facebook-comments/amp-facebook-comments.md
Labels: cla: yes

#29867 🖍 [bento][social-share] Update outdated social icons and colors
  build-system/compile/sources.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-social-share/1.0/amp-social-share.css
  extensions/amp-social-share/1.0/social-share-config.js
  extensions/amp-social-share/1.0/social-share-svgs.js
  extensions/amp-social-share/1.0/social-share.js
  third_party/optimized-svg-icons/social-share-svgs.js
Labels: cla: yes

#30200 🐛 [bento][amp-social-share] Preact component should not throw error
  extensions/amp-social-share/1.0/social-share.js
  extensions/amp-social-share/1.0/social-share.type.js
  extensions/amp-social-share/1.0/test/test-social-share.js
Labels: cla: yes

#30300 🚀 FID improvement use isInputPending if available for chunk.
  src/chunk.js
  test/unit/test-chunk.js
Labels: WG: performance, WG: runtime, cla: yes

#30339 Add OneTrust CMP
  examples/amp-consent/cmp-vendors.amp.html
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/amp-consent.md
  extensions/amp-consent/cmps/onetrust.md
Labels: cla: yes

#30282 Implement context props and integrate with Preact context
  build-system/tasks/storybook/preact-env/main.js
  extensions/amp-base-carousel/1.0/base-carousel.js
  extensions/amp-base-carousel/1.0/scroller.js
  extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
  extensions/amp-base-carousel/1.0/test/test-base-carousel.js
  src/context/index.js
  src/context/node.js
  src/contextprops/index.js
  src/loading.js
  src/preact/base-element.js
  src/preact/context.js
  src/preact/context.type.js
  src/preact/slot.js
  src/preact/storybook/Context.js
  src/preact/storybook/Wrappers.js
  test/unit/contextprops/test-contextprops.js
  test/unit/preact/test-base-element-mapping.js
  test/unit/preact/test-base-element-runtime.js
  test/unit/preact/test-context.js
  test/unit/preact/test-slot.js
Labels: cla: yes

#30369 🐛[amp-story] Only close expanded element when appropriate
  extensions/amp-story/1.0/amp-story-embedded-component.js
Labels: cla: yes

#30254 [amp-story-player] Add ShadowDOM fallback for edge
  css/amp-story-player-iframe.css
  css/amp-story-player.css
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#30373 🏗 Clean up duplicate logging in `gulp dist` during `worker-dom` resource copying
  build-system/tasks/extension-helpers.js
Labels: WG: infra, cla: yes

#29896 🔥 Disable linker by default
  extensions/amp-analytics/0.1/vendors/deepbi.json
Labels: cla: yes

#30085 🚀 🐛 [amp-story-player] show() improvements
  src/amp-story-player/amp-story-player-iframe-pool.js
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#30323 ✨Add a close button to amp-ad stick type
  examples/amp-ad/sticky.html
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
  extensions/amp-ad/0.1/amp-ad.css
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
  extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js
Labels: cla: yes

#30304 jss transform: use @enum instead of json.parse
  build-system/babel-plugins/babel-plugin-transform-jss/index.js
  build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-jss-var/output.mjs
  build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/output.mjs
  extensions/amp-base-carousel/1.0/amp-base-carousel.js
  extensions/amp-inline-gallery/1.0/amp-inline-gallery-pagination.js
Labels: cla: yes

#30381 🐛 "activate 360" button always above content
  css/Z_INDEX.md
  extensions/amp-story-360/0.1/amp-story-360.css
Labels: WG: stories, cla: yes

#30389 ✅ Fix amp-ad-3p sourceUrl assertion for IE11
  test/integration/test-amp-ad-3p.js
Labels: cla: yes

#30393 ✅ Configure CSS integration tests to skip IE11
  test/integration/test-css.js
Labels: cla: yes

#30382 ✅ Fix 5 failing IE11 tests because of missing argument
  test/integration/test-extensions-loading.js
Labels: cla: yes
