Repository ampproject/amphtml, pull requests merged in 2020-03, with the labels that each got.

#27035 Launch `amp-next-page` v2 & clean up experiment
  build-system/compile/bundles.config.js
  extensions/amp-next-page/1.0/amp-next-page.js
  extensions/amp-next-page/1.0/test/test-amp-next-page.js
  extensions/amp-next-page/amp-next-page.md
  test/manual/amp-next-page/1.0/amp-next-page.amp.html
  test/manual/amp-next-page/1.0/amp-next-page.element-visibility.html
  test/manual/amp-next-page/1.0/amp-next-page.script-templated-separator.amp.html
  tools/experiments/experiments-config.js
Labels: cla: yes

#26294 ssr intrinsic layout: support svg using apostroph
  validator/testdata/transformed_feature_tests/server_side_rendering.html
  validator/testdata/transformed_feature_tests/server_side_rendering.out
  validator/validator-main.protoascii
Labels: Validator: Approved, WG: caching, cla: yes

#27034 🐛 only log first error for ignored embed-size in amp-iframe
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
Labels: cla: yes

#26631 ✨amp-delight-player: Additional analytics support
  extensions/amp-delight-player/0.1/amp-delight-player.js
  extensions/amp-delight-player/0.1/test/test-amp-delight-player.js
Labels: cla: yes

#27056 specified use of markdown in teaser
  build-system/tasks/extension-generator/extension-doc.template.md
Labels: cla: yes

#27055 Adds new touch capability to viewer integration
  extensions/amp-viewer-integration/0.1/amp-viewer-integration.js
Labels: cla: yes

#27006 🐛 Maintain ad-rolling state, use to init dock controls
  extensions/amp-video-docking/0.1/controls.js
  extensions/amp-viqeo-player/0.1/test/test-amp-viqeo-player.js
  src/service/video-manager-impl.js
  src/video-interface.js
  test/integration/test-video-manager.js
Labels: cla: yes

#27045 fix single-pass to use `transferSrcsToTempDir`
  build-system/compile/compile.js
  build-system/compile/single-pass.js
  build-system/tasks/dist.js
Labels: cla: yes

#27054 ✨ SwG version 0.1.22.95
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#27067 Validator rollup
  validator/testdata/feature_tests/json-parsing-invalid.html
  validator/testdata/feature_tests/json-parsing-invalid.out
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#27030 gulp performance: emit status updates
  build-system/tasks/performance/measure-documents.js
Labels: cla: yes

#27057 🚮 Remove TransferLayerShadow
  src/service/fixed-layer.js
  test/unit/test-fixed-layer.js
Labels: cla: yes

#27063 Fire low trust events when relevant in amp-carousel v1
  examples/carousel-v1.amp.html
  extensions/amp-carousel/0.1/base-slides.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/0.1/test/test-slidescroll.js
Labels: cla: yes

#26950 Update link to Mustache spec and not JS implementation
  extensions/amp-mustache/amp-mustache.md
Labels: cla: yes

#26794 ✨ Update Pubmine amp-ad to support amp-consent states
  ads/pubmine.js
  ads/pubmine.md
  test/unit/ads/test-pubmine.js
Labels: cla: yes

#27084 Sync from Google
  validator/htmlparser/BUILD
  validator/htmlparser/bin/BUILD
  validator/htmlparser/data/BUILD
  validator/htmlparser/data/CaseFolding.txt
  validator/htmlparser/data/jsongrammar.txt
  validator/htmlparser/grammar/BUILD
  validator/htmlparser/grammar/tablebuilder.cc
  validator/htmlparser/htmldataset_test.cc
  validator/htmlparser/json/BUILD
  validator/htmlparser/json/jsondataset_test.cc
  validator/htmlparser/json/parser.cc
  validator/htmlparser/json/states.h
  validator/htmlparser/json/types.cc
  validator/htmlparser/json/types.h
  validator/htmlparser/json/types_test.cc
  validator/htmlparser/node.cc
  validator/htmlparser/parser.cc
  validator/htmlparser/testdata/go/template.dat
  validator/htmlparser/testdata/tree-construction/tests11.dat
  validator/htmlparser/testdata/tree-construction/tests25.dat
  validator/htmlparser/tokenizer.cc
  validator/htmlparser/url.cc
  validator/htmlparser/url.h
  validator/htmlparser/url_test.cc
Labels: WG: caching, cla: yes

#27085 Sync from Google
  validator/htmlparser/json/types.cc
  validator/htmlparser/json/types_test.cc
  validator/htmlparser/url_test.cc
Labels: WG: caching, cla: yes

#27022 📖 Fix validation errors in amp-web-push example
  extensions/amp-web-push/amp-web-push.md
Labels: cla: yes

#27047 ✨amp-access-scroll: Update the activate bar to properly set up relay for resizing
  extensions/amp-access-scroll/0.1/scroll-bar.js
  extensions/amp-access-scroll/0.1/scroll-impl.js
Labels: cla: yes

#26172 Avoid encoding data-amp-addparams
  src/service/url-replacements-impl.js
  test/unit/test-url-replacements.js
Labels: cla: yes

#27087 📖Fix one more referecnes to Mustache.js
  extensions/amp-mustache/amp-mustache.md
Labels: cla: yes

#27088 ✨amp-access-scroll Bump protocol version
  extensions/amp-access-scroll/0.1/scroll-protocol.js
Labels: cla: yes

#27078 ✨AmpAnalytics: Add linker to ADOBEANALYTICS_CONFIG (#26289)
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/adobeanalytics.json
Labels: cla: yes

#27089 New onDocumentState viewer messaging.
  extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js
  extensions/amp-story/1.0/test/test-amp-story-viewer-messaging-handler.js
Labels: cla: yes

#26507 ✨ Initial amp-timeago Bento component
  build-system/compile/bundles.config.js
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/dep-check-config.js
  examples/amp-timeago.amp.html
  extensions/amp-timeago/0.2/amp-timeago.js
  extensions/amp-timeago/0.2/timeago.js
Labels: cla: yes

#26991 amp-carousel expose `ampTrust` in `slideChange` event
  examples/carousel-v1.amp.html
  extensions/amp-carousel/0.1/slidescroll.js
Labels: cla: yes

#27113 🐛 Fix Timeago Preact Type
  extensions/amp-timeago/0.2/timeago.js
Labels: cla: yes

#26876 🚀Use { passive: true } on gesture.js to improve touch event performance
  src/event-helper-listen.js
  src/gesture.js
  test/unit/test-event-helper.js
Labels: WG: ui-and-a11y, cla: yes

#27116 Fixes various review comments on JSX PR
  babel.config.js
  build-system/babel-plugins/babel-plugin-transform-fix-leading-comments/test/fixtures/transform/basic/input.js
  build-system/babel-plugins/babel-plugin-transform-fix-leading-comments/test/fixtures/transform/basic/output.js
  build-system/babel-plugins/babel-plugin-transform-fix-leading-comments/test/index.js
  build-system/compile/build.conf.js
  build-system/compile/compile.js
  build-system/eslint-rules/preact.js
Labels: cla: yes

#26972 📖Update amp-ad-exit docs
  extensions/amp-ad-exit/amp-ad-exit.md
Labels: cla: yes

#27129 🐛 Fix format for story-components
  extensions/amp-story-auto-ads/amp-story-auto-ads.md
  extensions/amp-story/amp-story.md
Labels: cla: yes

#27037 🐛 propagate title attribute in amp-iframe
  extensions/amp-bind/0.1/bind-validator.js
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
Labels: WG: Caching: Triaged, WG: caching, WG: ui-and-a11y, cla: yes

#27103 ✨The Ozone Project: Update RTC endpoint macro in callout-vendors.js
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#27074 🐛Remove Google Safeframe origin check
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
Labels: cla: yes

#27098 amp-story-education extension boilerplate.
  build-system/compile/bundles.config.js
  extensions/amp-story-education/0.1/amp-story-education.css
  extensions/amp-story-education/0.1/amp-story-education.js
  extensions/amp-story-education/0.1/test/test-amp-story-education.js
  extensions/amp-story-education/OWNERS
  extensions/amp-story-education/amp-story-education.md
  extensions/amp-story-education/validator-amp-story-education.protoascii
Labels: cla: yes

#27013 ✨ Add support for tracking sub ids for revcontent amp ads
  ads/revcontent.js
  ads/revcontent.md
Labels: cla: yes

#27132 🐛Allow nonce in inline bookend
  extensions/amp-story/1.0/test/validator-amp-story-bookend-inline.html
  extensions/amp-story/1.0/test/validator-amp-story-bookend-inline.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#27136 📖 Allow `text/javascript` for amp-script
  extensions/amp-script/amp-script.md
Labels: cla: yes

#27115 ♻️ alphabetize propagated attrs in amp-img
  builtins/amp-img.js
Labels: cla: yes

#27106 🐛 Snowplow Extension: Patch Page Pings
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/snowplow.json
  extensions/amp-analytics/0.1/vendors/snowplow_v2.json
Labels: cla: yes

#27027 Aspect ratio format for amp-story-grid-layer
  examples/amp-story/helloworld.html
  extensions/amp-story/1.0/amp-story-grid-layer.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/test/test-amp-story-grid-layer.js
  extensions/amp-story/1.0/test/validator-amp-story-grid-layer-error.html
  extensions/amp-story/1.0/test/validator-amp-story-grid-layer-error.out
  extensions/amp-story/1.0/test/validator-amp-story-grid-layer.html
  extensions/amp-story/1.0/test/validator-amp-story-grid-layer.out
  extensions/amp-story/amp-story-grid-layer.md
  extensions/amp-story/validator-amp-story.protoascii
  src/style.js
  test/unit/test-style.js
Labels: WG: caching, cla: yes

#27143 Fix filters in amp-bind reference
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#27142 🏗 Add React Hooks linter
  .eslintrc
  package.json
  yarn.lock
Labels: cla: yes

#27144 🚀 Disable ampCors for analytics vendors requests
  extensions/amp-analytics/0.1/config.js
Labels: cla: yes

#27102 📖 Fix typo in amp-ad.md
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#27154 Revert "Fix filters in amp-bind reference (#27143)"
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#27141 🏗 Standardize on-demand package installation for `gulp` tasks
  build-system/common/utils.js
  build-system/tasks/e2e/index.js
  build-system/tasks/performance/index.js
  build-system/tasks/visual-diff/index.js
Labels: WG: infra, cla: yes

#26236 First pass at IntersectionObserver in Resources
  src/inabox/inabox-resources.js
  src/ini-load.js
  src/layout-rect.js
  src/service/mutator-impl.js
  src/service/position-observer/position-observer-worker.js
  src/service/resource.js
  src/service/resources-impl.js
  src/service/resources-interface.js
  src/service/viewport/viewport-binding-def.js
  src/service/viewport/viewport-binding-ios-embed-wrapper.js
  src/service/viewport/viewport-binding-natural.js
  src/service/viewport/viewport-impl.js
  src/service/viewport/viewport-interface.js
  test/unit/test-layout-rect.js
  test/unit/test-viewport.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#27135 🏗 ads owners: don't send reviews to jeffkaufman
  ads/OWNERS
Labels: cla: yes

#27158 🏗 Log dist error on Travis
  build-system/pr-check/dist-bundle-size.js
  package.json
  yarn.lock
Labels: cla: yes

#27096 🐛 Bug fix
  validator/java/pom.xml
  validator/java/src/main/java/dev/amp/validator/AMPHtmlHandler.java
  validator/java/src/main/java/dev/amp/validator/Context.java
  validator/java/src/main/java/dev/amp/validator/ExtensionsContext.java
  validator/java/src/main/java/dev/amp/validator/ParsedValidatorRules.java
  validator/java/src/main/java/dev/amp/validator/TagStack.java
  validator/java/src/main/java/dev/amp/validator/utils/AttributeSpecUtils.java
  validator/java/src/main/java/dev/amp/validator/utils/ExtensionsUtils.java
  validator/java/src/main/java/dev/amp/validator/utils/TagSpecUtils.java
  validator/java/src/main/java/dev/amp/validator/utils/UrlUtils.java
  validator/java/src/main/proto/validator.proto
  validator/java/src/test/java/dev/amp/validator/ExtensionsContextTest.java
Labels: WG: caching, cla: yes

#27156 Sync from Google
  validator/htmlparser/json/types.h
  validator/htmlparser/json/types_test.cc
Labels: WG: caching, cla: yes

#27140 Story navigation education.
  build-system/test-configs/dep-check-config.js
  extensions/amp-story-education/0.1/amp-story-education.css
  extensions/amp-story-education/0.1/amp-story-education.js
  extensions/amp-story-education/0.1/test/test-amp-story-education.js
  extensions/amp-story/1.0/_locales/default.js
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/amp-story.js
  src/localized-strings.js
Labels: cla: yes

#26945 ♻️Introduce new detached dom writing logic.
  src/utils/detached-dom-stream.js
  src/utils/dom-tranform-stream.js
  src/utils/dom-writer.js
  test/unit/utils/test-detached-dom-stream.js
  test/unit/utils/test-dom-transform-stream.js
Labels: cla: yes

#26992 bind-impl: introduce getStateAsync
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#27134 ✨ amp-bind: allow facetime protocol for links
  extensions/amp-bind/0.1/bind-validator.js
  validator/validator-main.protoascii
Labels: Validator: Approved, WG: caching, cla: yes

#27166 🐛 [amp-story-player] Install viewer integration script on buildCallback
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#27076 amp-script: decouple dev modes
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
  extensions/amp-script/0.1/test/validator-amp-script.html
  extensions/amp-script/0.1/test/validator-amp-script.out
  extensions/amp-script/amp-script.md
  extensions/amp-script/validator-amp-script.protoascii
Labels: Validator: Approved, WG: caching, cla: yes

#26912 Remove deprecated Cloudflare AMP Cache and A4A support.
  3p/README.md
  ads/_a4a-config.js
  ads/dianomi.md
  build-system/compile/bundles.config.js
  build-system/global-configs/caches.json
  build-system/tasks/caches-json.js
  build-system/test-configs/dep-check-config.js
  examples/a4a.amp.html
  extensions/amp-ad-network-cloudflare-impl/0.1/amp-ad-network-cloudflare-impl.js
  extensions/amp-ad-network-cloudflare-impl/0.1/cloudflare-a4a-config.js
  extensions/amp-ad-network-cloudflare-impl/0.1/data/fake_a4a.html
  extensions/amp-ad-network-cloudflare-impl/0.1/data/fake_a4a.json
  extensions/amp-ad-network-cloudflare-impl/0.1/test/test-amp-ad-network-cloudflare-impl.js
  extensions/amp-ad-network-cloudflare-impl/0.1/vendors.js
  extensions/amp-ad-network-cloudflare-impl/OWNERS
  extensions/amp-ad-network-cloudflare-impl/amp-ad-network-cloudflare-impl-internal.md
  extensions/amp-ad-network-gmossp-impl/0.1/amp-ad-network-gmossp-impl.js
  extensions/amp-ad-network-gmossp-impl/0.1/gmossp-a4a-config.js
  extensions/amp-ad-network-gmossp-impl/0.1/test/test-amp-ad-network-gmossp-impl.js
  extensions/amp-ad-network-gmossp-impl/OWNERS
  extensions/amp-ad-network-gmossp-impl/amp-ad-network-gmossp-impl-internal.md
  extensions/amp-ad-network-mytarget-impl/0.1/amp-ad-network-mytarget-impl.js
  extensions/amp-ad-network-mytarget-impl/0.1/mytarget-a4a-config.js
  extensions/amp-ad-network-mytarget-impl/0.1/test/test-amp-ad-network-mytarget-impl.js
  extensions/amp-ad-network-mytarget-impl/OWNERS
  extensions/amp-ad-network-mytarget-impl/amp-ad-network-mytarget-impl-internal.md
  extensions/amp-ad-network-triplelift-impl/0.1/amp-ad-network-triplelift-impl.js
  extensions/amp-ad-network-triplelift-impl/0.1/test/test-amp-ad-network-triplelift-impl.js
  extensions/amp-ad-network-triplelift-impl/0.1/triplelift-a4a-config.js
  extensions/amp-ad-network-triplelift-impl/OWNERS
  spec/amp-cache-guidelines.md
  spec/amp-cors-requests.md
  test/size.txt
  validator/engine/validator-in-browser.js
Labels: WG: caching, cla: yes

#27163 🐛Delete setting of incorrect field "iframe_"
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
Labels: cla: yes

#27179 ✨[amp-story-player] Sandbox iframes
  src/amp-story-player.js
Labels: cla: yes

#27186 Change OWNER wg-ads to wg-ads-reviewers
  3p/OWNERS
  ads/OWNERS
  ads/google/OWNERS
  extensions/amp-a4a/OWNERS
  extensions/amp-ad-custom/OWNERS
  extensions/amp-ad-exit/OWNERS
  extensions/amp-ad-network-adsense-impl/OWNERS
  extensions/amp-ad-network-adzerk-impl/OWNERS
  extensions/amp-ad-network-doubleclick-impl/OWNERS
  extensions/amp-ad-network-fake-impl/OWNERS
  extensions/amp-ad/OWNERS
  extensions/amp-beopinion/OWNERS
  extensions/amp-consent/OWNERS
  extensions/amp-mraid/OWNERS
  src/OWNERS
  src/inabox/OWNERS
Labels: cla: yes

#27051 🏗️ enable 3-at-a-time batching for all sauce labs tests
  build-system/tasks/runtime-test/helpers.js
Labels: cla: yes

#27165 Story navigation education animations.
  extensions/amp-story-education/0.1/amp-story-education.css
Labels: cla: yes

#27077 testing: enable chai-as-promised for integ tests
  build-system/tasks/helpers.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/test-configs/config.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  test/_init_tests.js
  test/chai-as-promised/.eslintrc
  test/chai-as-promised/chai-as-promised.js
Labels: WG: infra, cla: yes

#27196 🏗 Apply `rtv_version` flag to dist and build tasks
  build-system/compile/internal-version.js
  build-system/tasks/build.js
  build-system/tasks/dist.js
  contributing/TESTING.md
Labels: cla: yes

#27201 Validator rollup
  validator/engine/validator.js
  validator/testdata/amp4email_feature_tests/anchor.html
  validator/testdata/amp4email_feature_tests/anchor.out
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#27203 Sync from Google
  validator/htmlparser/strings.h
  validator/htmlparser/strings_test.cc
Labels: WG: caching, cla: yes

#27197 🐛 [check-links] Don't reassign const
  build-system/tasks/check-links.js
Labels: cla: yes

#27191 ♻️readmo: add support for custom configs via json attribute
  ads/readmo.js
  ads/readmo.md
Labels: cla: yes

#27204 🐛 Create image pixel in onload event handler of iframe
  src/pixel.js
Labels: cla: yes

#27208 🐛 Don't try to assign deferred before checking null
  extensions/amp-video-iframe/0.1/amp-video-iframe.js
Labels: cla: yes

#27210 🏗 Run yarn via npx, in the `gulp validator` task.
  validator/build.py
Labels: WG: caching, cla: yes

#27202 Reconstruct safeframe API upon refreshing.
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#27173 ✨[amp-story-player] Adds swipe-to-next/previous story
  css/amp-story-player-iframe.css
  src/amp-story-player.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#27137 Make the mini-postmortem template more mini
  .github/ISSUE_TEMPLATE/cherry_pick_template.md
Labels: cla: yes

#26758 Add support for multirequest Ads in Sklik SSP amp-ad
  ads/ssp.js
  ads/ssp.md
  examples/ads.amp.html
  test/unit/ads/test-ssp.js
Labels: cla: yes

#25837 ✨Mgid uniq ad
  ads/mgid.js
Labels: cla: yes

#27225 Sync from Google
  validator/htmlparser/README.md
Labels: cla: yes

#27232 ✅ SwG: Updates E2E expectations to match new values
  extensions/amp-subscriptions-google/0.1/test-e2e/test-amp-subscriptions-google.js
Labels: cla: yes

#27212 🐛 Use quoted properties to prevent Closure's DCE
  extensions/amp-date-display/0.2/amp-date-display.js
  extensions/amp-timeago/0.2/amp-timeago.js
  src/preact/base-element.js
Labels: cla: yes

#27226 Exclude /validator/htmlparser
  build-system/test-configs/config.js
Labels: WG: caching, cla: yes

#27122 ✨🚀Widget Optimized [TE Medya]
  ads/_config.js
  ads/temedya.js
  ads/temedya.md
  examples/ads.amp.html
Labels: cla: yes

#27083 Support `disable-inline-width` attribute when applying layout sizes
  spec/amp-html-layout.md
  src/custom-element.js
  test/unit/test-amp-img.js
  test/unit/test-custom-element.js
  validator/validator-main.protoascii
Labels: Validator: Approved, WG: caching, cla: yes

#27233 🐛Fix missing iframe error in safeframe
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
Labels: cla: yes

#27218 🐛 amp-access: Keeps trying to close window for a minute
  extensions/amp-access/0.1/amp-login-done-dialog.js
  extensions/amp-access/0.1/test/test-amp-login-done-dialog.js
Labels: cla: yes

#26826 amp-autocomplete: Revise order of selection events
  examples/amp-autocomplete-bind.html
  examples/amp-autocomplete-testing.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Labels: cla: yes

#27241 🐛 Remove markdown from component teaser text
  extensions/amp-access-laterpay/amp-access-laterpay.md
  extensions/amp-ad-exit/amp-ad-exit.md
  extensions/amp-addthis/amp-addthis.md
  extensions/amp-apester-media/amp-apester-media.md
  extensions/amp-audio/amp-audio.md
  extensions/amp-beopinion/amp-beopinion.md
  extensions/amp-bodymovin-animation/amp-bodymovin-animation.md
  extensions/amp-brid-player/amp-brid-player.md
  extensions/amp-brightcove/amp-brightcove.md
  extensions/amp-connatix-player/amp-connatix-player.md
  extensions/amp-dailymotion/amp-dailymotion.md
  extensions/amp-delight-player/amp-delight-player.md
  extensions/amp-gfycat/amp-gfycat.md
  extensions/amp-gist/amp-gist.md
  extensions/amp-hulu/amp-hulu.md
  extensions/amp-ima-video/amp-ima-video.md
  extensions/amp-install-serviceworker/amp-install-serviceworker.md
  extensions/amp-izlesene/amp-izlesene.md
  extensions/amp-jwplayer/amp-jwplayer.md
  extensions/amp-kaltura-player/amp-kaltura-player.md
  extensions/amp-mathml/amp-mathml.md
  extensions/amp-megaphone/amp-megaphone.md
  extensions/amp-mowplayer/amp-mowplayer.md
  extensions/amp-mustache/amp-mustache.md
  extensions/amp-ooyala-player/amp-ooyala-player.md
  extensions/amp-powr-player/amp-powr-player.md
  extensions/amp-recaptcha-input/amp-recaptcha-input.md
  extensions/amp-redbull-player/amp-redbull-player.md
  extensions/amp-share-tracking/amp-share-tracking.md
  extensions/amp-soundcloud/amp-soundcloud.md
  extensions/amp-springboard-player/amp-springboard-player.md
  extensions/amp-timeago/amp-timeago.md
  extensions/amp-video-iframe/amp-video-iframe.md
  extensions/amp-vimeo/amp-vimeo.md
  extensions/amp-viqeo-player/amp-viqeo-player.md
  extensions/amp-viz-vega/amp-viz-vega.md
  extensions/amp-vk/amp-vk.md
  extensions/amp-web-push/amp-web-push.md
  extensions/amp-wistia-player/amp-wistia-player.md
  extensions/amp-yotpo/amp-yotpo.md
  extensions/amp-youtube/amp-youtube.md
Labels: cla: yes

#27224 Add expected error for prerenderSize deprecation
  src/service/viewer-impl.js
Labels: cla: yes

#27248 0.1.22.96
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#27257 Revert "📦 Update dependency jest-cli to v25"
  package.json
  yarn.lock
Labels: cla: yes

#27180 initialize amp-list from amp-state, finishing touches
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  examples/amp-list.state.html
  extensions/amp-list/0.1/test/validator-amp-list.html
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/amp-list.md
  extensions/amp-list/validator-amp-list.protoascii
Labels: UI: Component: amp-list, Validator: Approved, WG: caching, WG: runtime, cla: yes

#27247 🐛 Mark initMessagingChannel timeout as an expected error
  src/service/viewer-impl.js
Labels: cla: yes

#27265 🐛 Always unlock pages that have unlocked config
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Labels: cla: yes

#27194 Story education viewer messaging.
  build-system/tasks/presubmit-checks.js
  extensions/amp-story-education/0.1/amp-story-education.js
  extensions/amp-story-education/0.1/test/test-amp-story-education.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#27256 use symbol replacement IS_ESM instead of relying on AMP_CONFIG.esm
  src/mode-object.js
  src/mode.js
  test/unit/3p/test-3p-frame.js
Labels: cla: yes

#27261 🐛 Mark viewer storage failure as an expected error
  src/service/storage-impl.js
Labels: cla: yes

#27253 Enable stale bot
  .github/stale.yml
Labels: cla: yes

#27183 🏗🚮 Remove deprecated AMP_CANARY cookie name from experiments.js
  tools/experiments/experiments.js
Labels: cla: yes

#27264 Remove unused experiment config
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#27215 Rename changeSize APIs to be grep-able (noop)
  build-system/tasks/presubmit-checks.js
  contributing/building-an-amp-extension.md
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
  extensions/amp-apester-media/0.1/amp-apester-media.js
  extensions/amp-apester-media/0.1/monetization/companion/display.js
  extensions/amp-apester-media/0.1/monetization/companion/video.js
  extensions/amp-apester-media/0.1/test/test-amp-apester-media.js
  extensions/amp-apester-media/0.1/test/test-amp-apester-monetization.js
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-auto-ads/0.1/test/test-placement.js
  extensions/amp-beopinion/0.1/amp-beopinion.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-embedly-card/0.1/amp-embedly-card-impl.js
  extensions/amp-facebook-comments/0.1/amp-facebook-comments.js
  extensions/amp-facebook/0.1/amp-facebook.js
  extensions/amp-facebook/0.1/test/test-amp-facebook.js
  extensions/amp-gist/0.1/amp-gist.js
  extensions/amp-instagram/0.1/amp-instagram.js
  extensions/amp-instagram/0.1/test/test-amp-instagram.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list-container.js
  extensions/amp-list/0.1/test/test-amp-list-load-more.js
  extensions/amp-mathml/0.1/amp-mathml.js
  extensions/amp-reddit/0.1/amp-reddit.js
  extensions/amp-twitter/0.1/amp-twitter.js
  extensions/amp-vk/0.1/amp-vk.js
  extensions/amp-vk/0.1/test/test-amp-vk.js
  src/base-element.js
  src/custom-element.js
  src/inabox/inabox-mutator.js
  src/service/mutator-impl.js
  src/service/mutator-interface.js
  src/service/resource.js
  src/service/resources-impl.js
  test/unit/inabox/test-inabox-mutator.js
  test/unit/test-custom-element.js
  test/unit/test-mutator.js
  test/unit/test-resource.js
Labels: cla: yes

#27279 Validator rollup at 450/1022
  extensions/amp-list/0.1/test/validator-amp-list.out
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#27255 🐛Swap columns on performance report
  build-system/tasks/performance/print-report.js
Labels: cla: yes

#27293 ✨ amp-subscriptions: In viewer platform, throw error if one is included with entitlements object
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#27292 🏗 add .percy.yaml config file for visual diff tests
  build-system/tasks/visual-diff/.percy.yaml
  build-system/tasks/visual-diff/index.js
  test/visual-diff/visual-tests
Labels: cla: yes

#27242 📖 Add missing amp-lightbox-gallery import
  extensions/amp-inline-gallery/amp-inline-gallery.md
Labels: cla: yes

#27269 🏗 Add test runner to gulp performance
  build-system/tasks/performance/index.js
  build-system/tasks/performance/load-config.js
  build-system/tasks/performance/package.json
  build-system/tasks/performance/print-report.js
  build-system/tasks/performance/run-tests.js
  build-system/tasks/performance/test-suite.js
  build-system/tasks/performance/yarn.lock
Labels: cla: yes

#27295 ♻️[amp-story-player] Player file restructure
  build-system/tasks/presubmit-checks.js
  src/amp-story-player-impl.js
  src/amp-story-player-manager.js
  src/amp-story-player.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#27209 🐛 Validate presence of contentWindow after promise resolves
  extensions/amp-ima-video/0.1/amp-ima-video.js
Labels: cla: yes

#27199 ♻️ Refactor dist --fortesting into commons/utils
  build-system/common/utils.js
  build-system/tasks/e2e/index.js
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#27280 🐛Change validator to let amp-access and amp-subscriptions coexist
  extensions/amp-access/validator-amp-access.protoascii
  extensions/amp-subscriptions/0.1/test/validator-amp-subscriptions-errors.out
  extensions/amp-subscriptions/validator-amp-subscriptions.protoascii
Labels: cla: yes

#27309 🐛 amp-subscriptions: In viewer platform, throw error if entitlements request times out
  build-system/test-configs/dep-check-config.js
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/constants.js
  extensions/amp-subscriptions/0.1/platform-store.js
  extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#27289 ♻️ amp-subscriptions: Moving public methods before private methods, and alphabetizing getter methods
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/service-adapter.js
Labels: cla: yes

#27213 🐛 Wait for document body to exist before testing rtl/ltr
  extensions/amp-video-docking/0.1/amp-video-docking.js
Labels: cla: yes

#27313 🏗 Make `yarn.lock` change detection more resilient
  build-system/common/git.js
  build-system/pr-check/yarn-checks.js
Labels: WG: infra, cla: yes

#27325 📖Remove irrelevant amp-bind doc for email
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#27159 Support layout=container in amp-list
  examples/amp-list-container.amp.html
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list-load-more.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-list/0.1/test/validator-amp-list.html
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/amp-list.md
  extensions/amp-list/validator-amp-list.protoascii
  validator/testdata/amp4email_feature_tests/amp_list.html
  validator/testdata/amp4email_feature_tests/amp_list.out
Labels: Validator: Approved, WG: caching, cla: yes

#27297 🏗 Run all PR checks during package upgrades
  build-system/pr-check/build-targets.js
Labels: WG: infra, cla: yes

#27326 🐛 amp-consent getRemoteConsent null
  extensions/amp-consent/0.1/amp-consent.js
Labels: cla: yes

#27328 🐛 amp-subscriptions: Resolves authdata on unlocked pages
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/entitlement.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Labels: cla: yes

#27302 amp-sidebar: Fix async throw in toolbar
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.1/toolbar.js
  extensions/amp-sidebar/0.2/amp-sidebar.js
  extensions/amp-sidebar/0.2/toolbar.js
Labels: cla: yes

#27324 Add class plugin with loose:false
  babel.config.js
Labels: cla: yes

#27002 🐛 Fix Relap widget URL
  ads/relap.js
Labels: cla: yes

#26862 ✨ Array multi-selector visibility trigger
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-analytics/0.1/events.js
  extensions/amp-analytics/0.1/test/test-events.js
  test/manual/amp-analytics/amp-analytics-multi-selector.html
  tools/experiments/experiments-config.js
Labels: cla: yes

#26387 Adding Oblivki network
  build-system/test-configs/dep-check-config.js
  extensions/amp-ad-network-oblivki-impl/0.1/amp-ad-network-oblivki-impl.js
  extensions/amp-ad-network-oblivki-impl/0.1/oblivki-a4a-config.js
  extensions/amp-ad-network-oblivki-impl/0.1/test/test-amp-ad-network-oblivki-impl.js
  extensions/amp-ad-network-oblivki-impl/OWNERS
  extensions/amp-ad-network-oblivki-impl/amp-ad-network-oblivki-impl.md
Labels: cla: yes

#27237 build: Update version flags
  build-system/compile/internal-version.js
  build-system/tasks/build.js
  build-system/tasks/dist.js
  contributing/TESTING.md
Labels: cla: yes

#26840 a4a: RefreshManager: Support amp-ad-enable-refresh lookup in AmpDocShadow
  extensions/amp-a4a/0.1/refresh-manager.js
  extensions/amp-a4a/0.1/test/test-refresh.js
Labels: cla: yes

#26678 amp-ad-network-doubleclick: Respect meta['referrer'] in AmpDocShadow
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
Labels: cla: yes

#26682 amp-ad: Support amp-3p-iframe-src lookup in AmpDocShadow
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-ad/0.1/amp-ad.js
  src/3p-frame.js
  test/unit/3p/test-3p-frame.js
Labels: cla: yes

#27341 🏗🐛 Upgrade module `find-imports` to 1.3.2
  build-system/tasks/runtime-test/helpers-unit.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#27319 Disable x-scrolling on iOS when iframed
  css/ampdoc.css
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
  extensions/amp-sidebar/0.1/test/integration/test-amp-sidebar.js
  extensions/amp-sidebar/0.2/test/integration/test-amp-sidebar.js
  src/service/viewport/viewport-binding-natural.js
  test/unit/test-viewport-binding.js
Labels: cla: yes

#26543 ✨Initial amp-social-share Bento component
  build-system/compile/bundles.config.js
  build-system/compile/sources.js
  build-system/tasks/helpers.js
  build-system/test-configs/dep-check-config.js
  examples/social-share.amp.html
  extensions/amp-social-share/0.2/amp-social-share-config.js
  extensions/amp-social-share/0.2/amp-social-share.js
  extensions/amp-social-share/0.2/social-share.css.js
  extensions/amp-social-share/0.2/social-share.js
  src/preact/base-element.js
  third_party/optimized-svg-icons/README.amp
  third_party/optimized-svg-icons/social-share-svgs.js
Labels: cla: yes

#26835 ✨ Adding "Browsi" amp-analytics & RTC vendors
  examples/analytics-vendors.amp.html
  examples/browsi-analytics.amp.html
  examples/browsi-prediction.amp.html
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-a4a/rtc-documentation.md
  extensions/amp-a4a/rtc-publisher-implementation-guide.md
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/browsi.json
Labels: cla: yes

#27260 DOMPurify: convert to a service
  extensions/amp-mustache/0.2/amp-mustache.js
  extensions/amp-mustache/0.2/test/test-amp-mustache.js
  extensions/amp-script/0.1/amp-script.js
Labels: cla: yes

#27363 🐛Fix the documentation link to the experiment list
  tools/experiments/README.md
Labels: cla: yes

#27270 Bind expressions: allow escaped quotes in strings
  extensions/amp-bind/0.1/bind-expr-impl.jison
  extensions/amp-bind/0.1/test/test-bind-expression.js
Labels: cla: yes

#27368 Skip flaky test
  extensions/amp-story/1.0/test-e2e/test-amp-story-share-menu.js
Labels: cla: yes

#27276 Avoid expanding selector
  extensions/amp-analytics/0.1/amp-analytics.js
Labels: cla: yes

#27374 🚀Ensure Classes are not Transpiled for Module Build
  babel.config.js
  package.json
  yarn.lock
Labels: cla: yes

#27371 SwG release 0.1.22.97
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#27355 [amp-social-share v2] Remove SOCIAL_SHARE_ prefixes from assets
  extensions/amp-social-share/0.2/social-share.css.js
  extensions/amp-social-share/0.2/social-share.js
  third_party/optimized-svg-icons/social-share-svgs.js
Labels: cla: yes

#27354 Simplify mutateProps in PreactBaseElement
  src/preact/base-element.js
Labels: cla: yes

#27369 Restrict amp-story-education to the mobile UI.
  extensions/amp-story-education/0.1/amp-story-education.js
Labels: cla: yes

#27361 Fix progress bar synchronization with amp-audio.
  extensions/amp-story/1.0/page-advancement.js
Labels: cla: yes

#27377 🐛 Properly invalidate `serve` require cache when watching
  build-system/tasks/serve.js
Labels: cla: yes

#27323 🐛 Values returned by setInterval must be greater than 0.
  3p/environment.js
Labels: cla: yes

#27277 📖 Add frontmatter to amp-layout reference
  builtins/amp-layout.md
Labels: cla: yes

#27278 🐛 Make amp-carousel.css use .i-amphtml-carousel-has-controls instead of [controls]
  extensions/amp-carousel/0.1/amp-carousel.css
  test/integration/test-amp-carousel.js
Labels: cla: yes

#27367 Experimental flag for preview
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/embed-mode.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
  extensions/amp-story/1.0/test/test-full-bleed-animations.js
  extensions/amp-story/1.0/test/test-live-story-manager.js
Labels: cla: yes

#27412 Validator Roll Up
  extensions/amp-subscriptions/0.1/test/validator-amp-subscriptions-errors.out
  extensions/amp-subscriptions/validator-amp-subscriptions.protoascii
  validator/build.py
  validator/engine/parse-css.js
  validator/engine/parse-css_test.js
  validator/engine/validator.js
  validator/testdata/feature_tests/empty.out
  validator/testdata/feature_tests/incorrect_custom_style.html
  validator/testdata/feature_tests/incorrect_custom_style.out
  validator/testdata/feature_tests/multiple_body_tags_3.out
  validator/testdata/feature_tests/not_amp.out
  validator/testdata/feature_tests/unprintable_chars.out
  validator/testdata/transformed_feature_tests/transformed_but_not_identified_transformed.out
  validator/validator-css.protoascii
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: WG: caching, cla: yes
