Repository ampproject/amphtml, pull requests merged in 2020-04, with the labels that each got.

#27475 Add support for amp_ad rakutenunifiedads
  3p/integration.js
  ads/_config.js
  ads/rakutenunifiedads.js
  ads/rakutenunifiedads.md
  examples/ads.amp.esm.html
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#27451 📖 amp-subscriptions: Marks `error` field in entitlements object as deprecated
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#27314 ♿ Remove 'role' attribute on amp-list when 'single-item' is specified.
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#27517 Update document for amp_ad rakutenunifiedads
  ads/rakutenunifiedads.md
Labels: cla: yes

#27514 🐛 Mark initMessagingChannel timeout as expected error
  src/service/viewer-impl.js
Labels: cla: yes

#27501 add new error reporting url experiment
  src/error.js
Labels: cla: yes

#27519 🐛 nit: fix logic for `deep-parsing` on `amp-next-page`
  extensions/amp-next-page/1.0/service.js
Labels: cla: yes

#27529 amp-timeago: Fix weird HTML formatting in doc
  extensions/amp-timeago/amp-timeago.md
Labels: cla: yes

#27521 [amp-list]: make layout=container and load-more mutually exclusive
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list-load-more.js
Labels: cla: yes

#27522 [dom.js] Fix fullscreen util issue 🐛
  src/dom.js
Labels: cla: yes

#27532 Adds a link to the AMP DevX survey to the amphtml README
  README.md
Labels: cla: yes

#27515 🏗🐛 Assorted fixes for `gulp --compiled`
  build-system/server/lazy-build.js
  build-system/tasks/build.js
  build-system/tasks/default-task.js
  build-system/tasks/dist.js
  build-system/tasks/presubmit-checks.js
  gulpfile.js
Labels: WG: infra, cla: yes

#27411 ✨ Added My6sense adapter to amp project
  3p/integration.js
  ads/_config.js
  ads/my6sense.js
  ads/my6sense.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#27533 [amp-social-share]: Allow component to prerender
  extensions/amp-social-share/0.1/amp-social-share.js
Labels: cla: yes

#27539 🏗Performance test bug fix
  build-system/tasks/performance/stats.js
Labels: cla: yes

#27544 🐛 Validator: support decimals for intrisic sizer dimensions
  validator/testdata/transformed_feature_tests/server_side_rendering.html
  validator/testdata/transformed_feature_tests/server_side_rendering.out
  validator/validator-main.protoascii
Labels: cla: yes

#27311 🏗Add navigation ticks to CSI
  extensions/amp-viewer-integration/TICKEVENTS.md
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#27497 intersect-resources: Refactor to a lower risk integration
  src/service/mutator-impl.js
  src/service/owners-impl.js
  src/service/resource.js
  src/service/resources-impl.js
  test/unit/test-resource.js
Labels: cla: yes

#27487 Fix unsupported browser font sizing, and reenable tests.
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  test/visual-diff/visual-tests
Labels: cla: yes

#27504 removed amp-analytics from valid child list of amp-story-grid-layer
  extensions/amp-story/amp-story-grid-layer.md
Labels: cla: yes

#27482 🚀 Optimize toggleLoading by letting the mutator skip measuring in specific cases.
  src/custom-element.js
  src/layout.js
  src/service/mutator-impl.js
  src/service/mutator-interface.js
Labels: Related to: Performance, WG: runtime, cla: yes

#27535 🏗♻️ More fixes for `gulp --compiled`
  babel.config.js
  build-system/tasks/build.js
  build-system/tasks/default-task.js
  build-system/tasks/dist.js
  build-system/tasks/serve.js
  gulpfile.js
Labels: WG: infra, cla: yes

#27450 ✨ Add global support for amp-recaptcha-input component.
  3p/recaptcha.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-input.js
  extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-service.js
  extensions/amp-recaptcha-input/amp-recaptcha-input.md
  test/integration/test-amp-recaptcha-input.js
  test/unit/3p/test-recaptcha.js
Labels: cla: yes

#27345 amp-apester: Support keyword lookup in AmpDocShadow
  extensions/amp-apester-media/0.1/amp-apester-media.js
  extensions/amp-apester-media/0.1/test/test-amp-apester-media-utils.js
  extensions/amp-apester-media/0.1/utils.js
Labels: cla: yes

#27338 Open remote story page attachments.
  extensions/amp-story/1.0/amp-story-draggable-drawer-header.css
  extensions/amp-story/1.0/amp-story-draggable-drawer.css
  extensions/amp-story/1.0/amp-story-draggable-drawer.js
  extensions/amp-story/1.0/amp-story-page-attachment.css
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#27512 🚀 Function expression rewriting during post closure transforms
  build-system/babel-plugins/babel-plugin-transform-function-declarations/index.js
  build-system/babel-plugins/babel-plugin-transform-function-declarations/test/fixtures/transform-assertions/function-expression/input.js
  build-system/babel-plugins/babel-plugin-transform-function-declarations/test/fixtures/transform-assertions/function-expression/options.json
  build-system/babel-plugins/babel-plugin-transform-function-declarations/test/fixtures/transform-assertions/function-expression/output.js
  extensions/amp-story/1.0/amp-story-page-attachment.js
Labels: cla: yes

#27516 🚀 Flatten Literals in TemplateLiterals
  build-system/babel-plugins/babel-plugin-transform-function-declarations/index.js
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/index.js
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/test/fixtures/transform/binary-expression/input.js
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/test/fixtures/transform/binary-expression/options.json
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/test/fixtures/transform/binary-expression/output.js
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/test/fixtures/transform/literals/input.js
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/test/fixtures/transform/literals/options.json
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/test/fixtures/transform/literals/output.js
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/test/index.js
  build-system/compile/build.conf.js
  yarn.lock
Labels: cla: yes

#27531 🐛resolve build errors in testing due to new css.protoascii
  validator/java/src/main/bin/fetchAMPResources.sh
  validator/java/src/test/java/dev/amp/validator/parser/AMPHtmlParserTest.java
Labels: cla: yes

#27520 🐛 Remove the erroneous, trailing space in filename
  build-system/babel-plugins/babel-plugin-transform-function-declarations/test/fixtures/transform-assertions/arguments-identifier/options.json
Labels: cla: yes

#27446 Fix race condition on vendor request test
  extensions/amp-analytics/0.1/test/test-vendors-new.js
  testing/test-helper.js
Labels: cla: yes

#27284 ✨ Isolated component development and testing for Bento and AMP
  .renovaterc.json
  build-system/server/new-server/transforms/tsconfig.json
  build-system/tasks/check-exact-versions.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/storybook/OWNERS
  build-system/tasks/storybook/amp-env/decorator.js
  build-system/tasks/storybook/amp-env/main.js
  build-system/tasks/storybook/amp-env/register.js
  build-system/tasks/storybook/amp-env/webpack.config.js
  build-system/tasks/storybook/index.js
  build-system/tasks/storybook/package.json
  build-system/tasks/storybook/preact-env/main.js
  build-system/tasks/storybook/preact-env/webpack.config.js
  build-system/tasks/storybook/yarn.lock
  contributing/TESTING.md
  extensions/amp-date-display/0.2/date-display.js
  extensions/amp-date-display/0.2/storybook/Basic.js
  extensions/amp-timeago/0.2/storybook/Basic.js
  extensions/amp-youtube/0.1/storybook/Basic.amp.js
  gulpfile.js
Labels: cla: yes

#27565 Split 'on tap' and 'on tap and swipe' education messages.
  extensions/amp-story-education/0.1/amp-story-education.js
  extensions/amp-story-education/0.1/test/test-amp-story-education.js
Labels: cla: yes

#27582 Skip amp-consent flaky e2e test
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js
Labels: cla: yes

#27556 🐛 amp-subscriptions: Allow platforms to register but don't fetch entitlements on free pages
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Labels: Component: amp-subscriptions, WG: access-subscriptions, cla: yes

#27569 🚀 Merging TemplateLiterals can result in StringLiterals
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/index.js
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/test/fixtures/transform/binary-expression/input.js
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/test/fixtures/transform/binary-expression/output.js
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/test/fixtures/transform/literals/input.js
  build-system/babel-plugins/babel-plugin-transform-stringish-literals/test/fixtures/transform/literals/output.js
Labels: cla: yes

#27589 🏗 [amp-story-player] Adds toolbox-cache-url as a dependency
  build-system/compile/sources.js
  build-system/tasks/presubmit-checks.js
  package.json
  yarn.lock
Labels: cla: yes

#27562 Track whether media are served from the cache.
  extensions/amp-story/1.0/media-performance-metrics-service.js
  extensions/amp-story/1.0/test/test-media-performance-metrics-service.js
Labels: cla: yes

#27574 Validate auto-advance-after element.
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/test/test-page-advancement.js
Labels: cla: yes

#27586 Validator rollup
  validator/testdata/amp4email_feature_tests/css_declarations.html
  validator/testdata/amp4email_feature_tests/css_declarations.out
  validator/testdata/feature_tests/css_declarations.html
  validator/testdata/feature_tests/css_declarations.out
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#27188 🏗 Add opt-in option to nightly release channel
  tools/experiments/experiments.js
Labels: cla: yes

#27320 ✨[amp-story-player] Upgrading amp-story-player to CE
  examples/amp-story/player.html
  src/amp-story-player-impl.js
  src/amp-story-player-manager.js
  src/amp-story-player.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#27596 swg release 100
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#27587 📖 Document the `?optin=<channel>` feature
  contributing/release-schedule.md
Labels: cla: yes

#27271 🏗 Run Java validator tests on Travis jobs
  .travis.yml
  build-system/pr-check/build-targets.js
  build-system/pr-check/validator-tests.js
  build-system/tasks/clean.js
  build-system/tasks/validator.js
  gulpfile.js
  validator/java/.gitignore
  validator/java/OWNERS
  validator/java/build.sh
  validator/java/build_and_test.sh
  validator/java/install_bazel.sh
Labels: WG: caching, WG: infra, cla: yes

#27613 🚀 Remove 'use strict' directives in post compilation transform for modu…
  build-system/babel-plugins/babel-plugin-transform-remove-directives/index.js
  build-system/babel-plugins/babel-plugin-transform-remove-directives/test/fixtures/transform/directives/input.js
  build-system/babel-plugins/babel-plugin-transform-remove-directives/test/fixtures/transform/directives/options.json
  build-system/babel-plugins/babel-plugin-transform-remove-directives/test/fixtures/transform/directives/output.js
  build-system/babel-plugins/babel-plugin-transform-remove-directives/test/index.js
  build-system/compile/build.conf.js
Labels: cla: yes

#27527 custom-element.updateLayoutBox: remove automatic toggleLoading
  src/custom-element.js
  src/loader.js
  test/unit/test-custom-element.js
Labels: WG: runtime, cla: yes

#27622 🐛 Catch on navigator.share
  extensions/amp-social-share/0.1/amp-social-share.js
  extensions/amp-social-share/0.1/test/test-amp-social-share.js
  extensions/amp-social-share/0.2/social-share.js
Labels: cla: yes

#27466 🐛Don't expand in array if not string
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
Labels: cla: yes

#27591 🏗 Clean up error reporting Beta diversions & divert all Nightly
  build-system/externs/amp.extern.js
  src/config.js
  src/error.js
Labels: cla: yes

#27442 🚮 amp-access-scroll: remove holdback
  extensions/amp-access-scroll/0.1/amp-access-scroll.css
  extensions/amp-access-scroll/0.1/scroll-bar.js
  extensions/amp-access-scroll/0.1/scroll-component.js
  extensions/amp-access-scroll/0.1/scroll-impl.js
  extensions/amp-access-scroll/0.1/scroll-protocol.js
  extensions/amp-access-scroll/0.1/scroll-sheet.js
Labels: cla: yes

#27626 🐛Fixed quiz icon not showing on sharp chip
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#27629 🚀 Remove IE specific references for ESM path
  build-system/compile/build.conf.js
  src/service/platform-impl.js
Labels: cla: yes

#27624 🐛Require src attribute in amp-ad-custom
  extensions/amp-ad-custom/validator-amp-ad-custom.protoascii
Labels: cla: yes

#27619 🏗 Add new issue template for error reports
  .github/ISSUE_TEMPLATE/error-report.md
Labels: cla: yes

#27633 Skip failing consent test
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-client-side.js
Labels: cla: yes

#27611 Show amp-geo as usable in stories on amp.dev.
  extensions/amp-geo/amp-geo.md
Labels: cla: yes

#27651 Ramp up Display Locking experiment on amp-accordion to 1%
  build-system/global-configs/prod-config.json
Labels: cla: yes

#27652 🏗 Added --host option to gulp's default task
  build-system/tasks/default-task.js
Labels: cla: yes

#27655 🚀 Add const-let transform to post closure transforms
  build-system/babel-plugins/babel-plugin-const-transformer/index.js
  build-system/compile/build.conf.js
Labels: cla: yes

#27571 Add preset-us-ca set to amp-geo
  extensions/amp-geo/0.1/amp-geo-presets.js
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-geo/0.1/test/test-amp-geo.js
Labels: cla: yes

#27627 Allow one tracking iframe in each amp doc
  extensions/amp-iframe/0.1/amp-iframe.js
  src/service/ampdoc-impl.js
  test/manual/amp-next-page/1.0/articles/article-short.html
  test/manual/amp-next-page/1.0/articles/article-with-fixed.html
Labels: cla: yes

#27609 ✨ Invibes ads: new ad parameter
  ads/invibes.js
  ads/invibes.md
  examples/ads.amp.esm.html
  examples/ads.amp.html
Labels: cla: yes

#27576 🏗♻️ Consolidate all `babel` configs into `babel.config.js`
  .eslintrc
  OWNERS
  babel.config.js
  build-system/babel-config/.eslintrc
  build-system/babel-config/OWNERS
  build-system/babel-config/dep-check-config.js
  build-system/babel-config/dev-dependencies.js
  build-system/babel-config/index.js
  build-system/babel-config/post-closure-config.js
  build-system/babel-config/pre-closure-config.js
  build-system/babel-config/replace-plugin.js
  build-system/babel-config/single-pass-config.js
  build-system/babel-config/test-config.js
  build-system/babel-config/unminified-config.js
  build-system/compile/OWNERS
  build-system/compile/build.conf.js
  build-system/compile/compile.js
  build-system/compile/post-closure-babel.js
  build-system/compile/pre-closure-babel.js
  build-system/compile/single-pass.js
  build-system/tasks/dep-check.js
  build-system/tasks/e2e/index.js
  build-system/tasks/helpers.js
  build-system/tasks/karma.conf.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/runtime-test/runtime-test-base.js
Labels: WG: infra, cla: yes

#27664 🏗🐛 Fix babel plugin tests and run them for babel config changes
  babel.config.js
  build-system/pr-check/build-targets.js
Labels: WG: infra, cla: yes

#27549 Adds has-tooltip="auto" support for links
  examples/amp-story/has-tooltip.html
  extensions/amp-story/1.0/page-advancement.js
Labels: cla: yes

#27598 🚀 Defer viewport getSize in performance-impl
  src/service/performance-impl.js
Labels: cla: yes

#27657 intersect-resources: Always schedule pass after build
  src/service/mutator-impl.js
  src/service/resources-impl.js
  test/unit/test-resources.js
Labels: cla: yes

#27671 Trigger user rather than dev errors for amp-story-consent misconfiguration.
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#26778 ♻️ `amp-next-page` v2 host page visibility + minor refactor
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-next-page/1.0/page.js
  extensions/amp-next-page/1.0/service.js
  extensions/amp-next-page/1.0/test/test-amp-next-page.js
  extensions/amp-next-page/1.0/visibility-observer.js
  src/dom.js
Labels: cla: yes

#27678 Revert babel changes to babel.config.js
  .eslintrc
  OWNERS
  babel.config.js
  build-system/babel-config/.eslintrc
  build-system/babel-config/OWNERS
  build-system/babel-config/dep-check-config.js
  build-system/babel-config/dev-dependencies.js
  build-system/babel-config/index.js
  build-system/babel-config/post-closure-config.js
  build-system/babel-config/pre-closure-config.js
  build-system/babel-config/replace-plugin.js
  build-system/babel-config/single-pass-config.js
  build-system/babel-config/test-config.js
  build-system/babel-config/unminified-config.js
  build-system/compile/OWNERS
  build-system/compile/build.conf.js
  build-system/compile/compile.js
  build-system/compile/post-closure-babel.js
  build-system/compile/pre-closure-babel.js
  build-system/compile/single-pass.js
  build-system/pr-check/build-targets.js
  build-system/tasks/dep-check.js
  build-system/tasks/e2e/index.js
  build-system/tasks/helpers.js
  build-system/tasks/karma.conf.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/runtime-test/runtime-test-base.js
Labels: cla: yes

#27631 ♻️ amp-subscriptions: Creates entitlement for free pages
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/crypto-handler.js
  extensions/amp-subscriptions/0.1/platform-store.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Labels: Component: amp-subscriptions, WG: access-subscriptions, cla: yes

#27682 🏗 Ramp new error reporting endpoint to 100%
  src/config.js
  src/error.js
Labels: cla: yes

#27683 🏗♻️ Consolidate all `babel` configs into `babel.config.js` (with `--esm` fixes)
  .eslintrc
  OWNERS
  babel.config.js
  build-system/babel-config/.eslintrc
  build-system/babel-config/OWNERS
  build-system/babel-config/dep-check-config.js
  build-system/babel-config/dev-dependencies.js
  build-system/babel-config/index.js
  build-system/babel-config/post-closure-config.js
  build-system/babel-config/pre-closure-config.js
  build-system/babel-config/replace-plugin.js
  build-system/babel-config/single-pass-config.js
  build-system/babel-config/test-config.js
  build-system/babel-config/unminified-config.js
  build-system/compile/OWNERS
  build-system/compile/build.conf.js
  build-system/compile/bundles.config.js
  build-system/compile/compile.js
  build-system/compile/post-closure-babel.js
  build-system/compile/pre-closure-babel.js
  build-system/compile/single-pass.js
  build-system/pr-check/build-targets.js
  build-system/tasks/dep-check.js
  build-system/tasks/e2e/index.js
  build-system/tasks/helpers.js
  build-system/tasks/karma.conf.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/runtime-test/runtime-test-base.js
Labels: WG: infra, WG: performance, cla: yes

#27685 🏗 Build ESM output on travis
  .travis.yml
  build-system/pr-check/module-build.js
Labels: cla: yes

#27697 🏗 ESM Build exclude language fix
  build-system/pr-check/module-build.js
Labels: cla: yes

#27687 build-system: Restrict allowed version_override
  build-system/compile/internal-version.js
Labels: WG: infra, cla: yes

#27644 ✨ [amp-form] Allow user to specify enctype=application/x-www-form-urlencoded for form submission
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-form/amp-form.md
Labels: cla: yes

#27674 🏗 Added --port option to gulp's default task
  build-system/tasks/default-task.js
Labels: cla: yes

#27688 Use a real anchor for remote page attachments
  examples/visual-tests/amp-story/amp-story-bot-rendering.html
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story-share-menu.css
  extensions/amp-story/1.0/amp-story-vertical.css
  test/visual-diff/visual-tests
Labels: cla: yes

#27701 ❄️ Skip amp-base-carousel flaky e2e test
  extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
Labels: cla: yes

#27656 📖 Development, Nightly, and Release schedule documentation updates
  contributing/DEVELOPING.md
  contributing/contributing-code.md
  contributing/release-schedule.md
Labels: cla: yes

#27700 🏗 Debug Compilation Lifecycles via gulp dist --debug
  build-system/compile/debug-compilation-lifecycle.js
  build-system/compile/post-closure-babel.js
  build-system/compile/pre-closure-babel.js
  build-system/tasks/dist.js
Labels: cla: yes

#27663 intersect-resources: Apply sizes/media queries on Resources.add
  src/custom-element.js
  src/service/resources-impl.js
  src/service/resources-interface.js
  test/unit/test-resources.js
Labels: cla: yes

#27702 🐛performance-impl: timeOrigin should be a value instead of delta
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: WG: runtime, cla: yes

#27661 build-system: Support alternate sourcemap URLs
  build-system/compile/compile.js
  build-system/tasks/dist.js
Labels: cla: yes

#27705 🏗Lay groundwork for testing ESM code during CI
  .travis.yml
  build-system/pr-check/dist-bundle-size.js
  build-system/pr-check/module-dist-bundle-size.js
  build-system/pr-check/utils.js
  build-system/tasks/presubmit-checks.js
Labels: WG: infra, cla: yes

#27706 🏗 Validator Java test updates
  build-system/pr-check/build-targets.js
  build-system/pr-check/validator-tests.js
  validator/java/.bazelrc
  validator/java/BUILD
  validator/java/build.sh
  validator/java/build_and_test.sh
  validator/java/install_bazel.sh
  validator/java/src/main/bin/copyValidatorJavaSource.sh
  validator/java/src/main/bin/fetchAMPResources.sh
Labels: WG: caching, WG: infra, cla: yes

#27704 Small fixes for vertical rendering
  examples/visual-tests/amp-story/amp-story-bot-rendering.html
  extensions/amp-story/1.0/amp-story-page-attachment.css
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story-vertical.css
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#27684 intersect-resources: Fix incorrect pre-layout assumption
  src/service/resource.js
  src/service/resources-impl.js
  test/unit/test-resources.js
Labels: cla: yes

#27723 Add period at end of a comment.
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#27713 ♻️✅ amp-story animations: test, refactor presets
  extensions/amp-story/1.0/animation-presets.js
  extensions/amp-story/1.0/animation-types.js
  extensions/amp-story/1.0/animation.js
  extensions/amp-story/1.0/test/test-animation.js
  extensions/amp-story/1.0/test/test-full-bleed-animations.js
Labels: cla: yes

#27654 🚀 amp-actions hide() can skipRemeasure
  src/service/standard-actions-impl.js
Labels: cla: yes

#27709 Ship remote page attachments
  examples/amp-story/attachment.html
  extensions/amp-story/1.0/amp-story-page-attachment.css
  extensions/amp-story/1.0/test/validator-amp-story-page-attachment-error.html
  extensions/amp-story/1.0/test/validator-amp-story-page-attachment-error.out
  extensions/amp-story/1.0/test/validator-amp-story-page-attachment.html
  extensions/amp-story/1.0/test/validator-amp-story-page-attachment.out
  extensions/amp-story/amp-story-page-attachment.md
  extensions/amp-story/validator-amp-story.protoascii
Labels: Validator: Approved, WG: caching, cla: yes

#27727 ✨ SwG Release 0.1.22.101
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#27665 🏗 Fix sourcemap sources paths
  build-system/compile/closure-compile.js
  build-system/compile/compile.js
  build-system/compile/helpers.js
  build-system/compile/post-closure-babel.js
  build-system/compile/single-pass.js
  build-system/tasks/create-module-compatible-es5-bundle.js
  build-system/tasks/dist.js
  package.json
  yarn.lock
Labels: cla: yes

#27733 Revert "✨[amp-story-player] Upgrading amp-story-player to CE"
  examples/amp-story/player.html
  src/amp-story-player-impl.js
  src/amp-story-player-manager.js
  src/amp-story-player.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#27728 🐛 Always lowercase amp-geo hotpatch matches
  extensions/amp-geo/0.1/amp-geo.js
Labels: cla: yes

#27449 🐛 amp-delight-player: Guard against missing DeviceMotionEvent info on iOS
  extensions/amp-delight-player/0.1/amp-delight-player.js
Labels: cla: yes

#27751 🐛 Local dev listing: fix search
  build-system/server/app-index/api/api.js
Labels: cla: yes

#27753 📖 Remove unreachable google-internal link from method comment
  extensions/amp-ad-network-fake-impl/0.1/amp-ad-metadata-transformer.js
Labels: cla: yes

#27752 Change name to show-tooltip
  examples/amp-story/show-tooltip.html
  extensions/amp-story/1.0/page-advancement.js
Labels: cla: yes

#27737 intersect-resources: Fix bad devAssert
  src/service/resource.js
  src/service/resources-impl.js
Labels: cla: yes

#27768 Revert #27159 and #27521
  examples/amp-list-container.amp.html
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list-load-more.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-list/0.1/test/validator-amp-list.html
  extensions/amp-list/0.1/test/validator-amp-list.out
  extensions/amp-list/amp-list.md
  extensions/amp-list/validator-amp-list.protoascii
  validator/testdata/amp4email_feature_tests/amp_list.html
  validator/testdata/amp4email_feature_tests/amp_list.out
Labels: WG: caching, cla: yes

#27738 🏗 Debounce all `watch` operations in the AMP dev toolchain
  build-system/tasks/css.js
  build-system/tasks/dist.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
  build-system/tasks/lint.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/serve.js
  build-system/tasks/vendor-configs.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#27730 amp-video-manager: always skip remeasurements
  src/base-element.js
  src/service/video-manager-impl.js
Labels: WG: runtime, cla: yes

#27761 🏗 Do not write sourcesContent in sourcemaps unless requested
  build-system/compile/debug-compilation-lifecycle.js
  build-system/compile/helpers.js
  build-system/compile/post-closure-babel.js
  build-system/compile/pre-closure-babel.js
Labels: cla: yes

#27735 Enable "intersect-resources" on canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#27756 [amp-story-player] 🐛 Fixes firefox bug
  build-system/tasks/presubmit-checks.js
  src/amp-story-player-impl.js
  src/amp-story-player-manager.js
Labels: cla: yes

#27774 Added comma to a comment as a trivial tweak
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#27773 🐛 Force Web Animations polyfill on Safari
  extensions/amp-animation/0.1/web-animations-polyfill.js
Labels: cla: yes

#27763 Drive by PR: Allow new enterkeyhint attribute on input
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#27772 🏗Don't throw an error when an unrecognized `babel` caller is encountered
  babel.config.js
Labels: WG: infra, cla: yes

#27783 🐛 Fix Custom Element instance creation in IE11, redo
  src/polyfills/custom-elements.js
Labels: cla: yes

#27785 ✅ Enable simple integration test in IE11
  test/integration/test-amp-img.js
Labels: cla: yes

#27740 Fix nasty race condition in AMP video
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-video/0.1/test/test-amp-video.js
  src/preconnect.js
Labels: cla: yes

#27508 toggleLoading: remove force paramater
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-twitter/0.1/amp-twitter.js
  src/base-element.js
  src/custom-element.js
Labels: cla: yes

#27788 🏗Java Validator testing changes
  build-system/pr-check/build-targets.js
  build-system/pr-check/build.js
  build-system/pr-check/checks.js
  build-system/pr-check/dist-bundle-size.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/experiment-tests.js
  build-system/pr-check/local-tests.js
  build-system/pr-check/module-dist-bundle-size.js
  build-system/pr-check/single-pass-tests.js
  build-system/pr-check/validator-tests.js
  build-system/pr-check/visual-diff-tests.js
  build-system/tasks/pr-check.js
Labels: WG: caching, WG: infra, cla: yes

#27597 ✨ <amp-story-animation>
  build-system/test-configs/dep-check-config.js
  examples/amp-story/amp-story-animation.html
  extensions/amp-animation/0.1/amp-animation.js
  extensions/amp-animation/0.1/test/test-amp-animation.js
  extensions/amp-story/1.0/animation-presets-utils.js
  extensions/amp-story/1.0/animation-types.js
  extensions/amp-story/1.0/animation.js
  extensions/amp-story/1.0/test/test-animation.js
Labels: cla: yes

#27489 🏗 Make wg-caching a required reviewer for validator changes
  OWNERS
Labels: cla: yes

#27736 🐛 Avoid [overflow] layout shift after buildCallback
  css/ampshared.css
  test/fixtures/overflow.html
  test/integration/test-css.js
Labels: cla: yes

#27789 Enable overflow for amp-story-grid-layer
  extensions/amp-story/1.0/amp-story-user-overridable.css
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#27755 Disable AdSense ad size optimization for users with wide viewport
  extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
Labels: cla: yes

#27811 Updates Homebrew Cask install command.
  validator/README.md
Labels: cla: yes

#27809 🏗 Temporarily disable function transform due to Services implementation
  build-system/babel-config/post-closure-config.js
Labels: WG: performance, cla: yes

#27782 Register story page level background-audio.
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
Labels: cla: yes

#27787 amp-twitter: validator should support [data-tweetid]
  examples/twitter.amp.html
  extensions/amp-story/1.0/test/validator-amp-story-amp-twitter.out
  extensions/amp-twitter/0.1/test/validator-amp-twitter.html
  extensions/amp-twitter/0.1/test/validator-amp-twitter.out
  extensions/amp-twitter/validator-amp-twitter.protoascii
  validator/testdata/feature_tests/everything.out
  validator/testdata/feature_tests/mandatory_dimensions.out
Labels: Type: Bug, Validator: Approved, WG: caching, cla: yes

#27729 🐛 .show() for iOS and autofocus must always remeasure
  src/service/standard-actions-impl.js
  test/unit/test-standard-actions.js
Labels: Type: Bug, UI: Component: Standard Actions, cla: yes

#27796 🏗✅ Fix IE11 Integration Test Support
  build-system/babel-config/dep-check-config.js
  build-system/babel-config/dev-dependencies.js
  build-system/babel-config/pre-closure-config.js
  build-system/babel-config/test-config.js
  build-system/babel-config/unminified-config.js
  test/integration/test-amp-img.js
Labels: cla: yes

#27812 Remote attachment dark mode support.
  extensions/amp-story/1.0/amp-story-page-attachment.css
Labels: cla: yes

#27814 Add --define_experiment_constant as valid flag
  build-system/babel-config/replace-plugin.js
  build-system/tasks/build.js
  build-system/tasks/default-task.js
  build-system/tasks/dist.js
Labels: cla: yes

#27837 Revert "[amp-social-share]: Allow component to prerender (#27533)"
  extensions/amp-social-share/0.1/amp-social-share.js
  extensions/amp-social-share/0.1/test/test-amp-social-share.js
Labels: cla: yes

#27692 🏗📦 Switch renovate updates for `amphtml` from opt-in to opt-out
  .renovaterc.json
Labels: WG: caching, WG: infra, cla: yes

#27836 Remove linker initialization promise
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/linker-manager.js
Labels: cla: yes

#27662 Unskip amp-consent e2e test
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-client-side.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js
Labels: cla: yes

#27847 🏗Don't run `VALIDATOR_JAVA` tests for `amphtml` package updates
  build-system/pr-check/build-targets.js
Labels: WG: caching, WG: infra, cla: yes

#27841 📖 Updates to the release issue template
  .github/ISSUE_TEMPLATE/release-tracking-issue.md
Labels: cla: yes

#27875 Make media pool assert HTTPs-ness of URLs to align with amp-video
  extensions/amp-story/1.0/sources.js
  extensions/amp-story/1.0/test/test-media-pool.js
  extensions/amp-story/1.0/test/test-media-tasks.js
Labels: cla: yes

#27806 🐛 Different method to bail out of native Animation on Safari
  extensions/amp-animation/0.1/web-animations-polyfill.js
Labels: cla: yes

#27659 ✅ Bootstrap unit tests for both loader.js and amp-loader.js
  extensions/amp-loader/0.1/test/test-amp-loader.js
  src/loader.js
  test/unit/test-loader.js
Labels: cla: yes

#26886 ✨ Visibility trigger support for querySelectorAll
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-analytics/0.1/events.js
  extensions/amp-analytics/0.1/test/test-analytics-root.js
  extensions/amp-analytics/0.1/test/test-events.js
  test/manual/amp-analytics/amp-analytics-multi-selector.html
Labels: cla: yes

#27605 Introduce analytics-chunks experiment
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/analytics-group.js
  extensions/amp-analytics/0.1/cookie-writer.js
  extensions/amp-analytics/0.1/test/test-analytics-group.js
  test/integration/test-amp-analytics.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#27760 mutator: skip an extra measure
  src/service/mutator-impl.js
Labels: cla: yes

#27594 ♻️ ExpandTemplate consolidation
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
Labels: cla: yes

#27843 🏗Update code coverage status configuration for `amphtml`
  .codecov.yml
Labels: WG: infra, cla: yes

#27800 ✨ CSS support in Storybook and `amp-image-slider` example
  build-system/tasks/storybook/amp-env/decorator.js
  build-system/tasks/storybook/package.json
  build-system/tasks/storybook/yarn.lock
  extensions/amp-image-slider/0.1/storybook/Basic.amp.js
Labels: cla: yes

#27893 SwG Release 0.1.22.102
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#27854 🚀allowlist adsense type for story ads
  extensions/amp-story-auto-ads/0.1/story-ad-config.js
  extensions/amp-story-auto-ads/0.1/test/test-story-ad-config.js
Labels: cla: yes

#27820 A11Y changes for Stories
  extensions/amp-story/1.0/amp-story-draggable-drawer.js
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-share-menu.js
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/pagination-buttons.css
  extensions/amp-story/1.0/pagination-buttons.js
  extensions/amp-story/1.0/progress-bar.js
  extensions/amp-story/1.0/semantic-render.js
Labels: cla: yes

#27896 Move the old IntersectionObserver polyfills out of src/.
  extensions/amp-a4a/0.1/refresh-intersection-observer-polyfill-wrapper.js
  extensions/amp-a4a/0.1/refresh-manager.js
  extensions/amp-a4a/0.1/test/test-refresh.js
  extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
  extensions/amp-ad/0.1/intersection-observer-host.js
  extensions/amp-ad/0.1/test/test-intersection-observer-host.js
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-analytics/0.1/visibility-manager.js
  extensions/amp-apester-media/0.1/amp-apester-media.js
  extensions/amp-iframe/0.1/amp-iframe.js
  src/custom-element.js
  src/utils/intersection-observer-polyfill.js
  test/unit/test-intersection-observer-polyfill.js
Labels: cla: yes

#27222 ✨ New feature: Adding our platform MoEngage as an amp-analytics plugin.
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/moengage.js
  extensions/amp-analytics/0.1/vendors/moengage.json
Labels: cla: yes
