Repository ampproject/amphtml, pull requests merged in 2020-02, with the labels that each got.

#26573 🐛 amp-auto-lightbox: Ignore unlaid out elements
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
  extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
Labels: cla: yes

#26554 🏗 Apply `AMP_CONFIG` to runtime files during `gulp dist`
  build-system/tasks/dist.js
  build-system/tasks/firebase.js
  build-system/tasks/helpers.js
  contributing/TESTING.md
Labels: WG: infra, cla: yes

#26470 ✨ Remote loading of pages for <amp-next-page> v2
  extensions/amp-next-page/1.0/page.js
  extensions/amp-next-page/1.0/service.js
  extensions/amp-next-page/1.0/test/test-amp-next-page.js
  extensions/amp-next-page/1.0/utils.js
Labels: cla: yes

#24424 Adding support for time/duration (amp-brid-player extension)
  extensions/amp-brid-player/0.1/amp-brid-player.js
Labels: cla: yes

#26527 Set owners for js in src/ for wg-ads and wg-analytics
  src/OWNERS
Labels: cla: yes

#26547 ♻️Resource=>Mutator refactor for access-poool
  extensions/amp-access-poool/0.1/poool-impl.js
Labels: cla: yes

#26557 🖍 [amp-story-player] Adds css for pre-fetch experience
  build-system/tasks/css.js
  css/amp-story-player.css
  examples/amp-story/player.html
  src/amp-story-player.js
Labels: cla: yes

#25879 🐛Prevent extend String object by the "colors" library.
  validator/nodejs/index.js
Labels: WG: caching, cla: yes

#26565 Remove expected error
  src/service/url-replacements-impl.js
Labels: cla: yes

#26588 🐛Force scrollTop to be remeasured on shadow doc visibility change
  src/service/viewport/viewport-impl.js
  test/unit/test-viewport.js
Labels: cla: yes

#26401 amp-script: Filter user-visible mutations during hydration
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test-e2e/test-amp-script.js
  package.json
  test/fixtures/e2e/amp-script/basic.amp.html
  test/fixtures/e2e/amp-script/basic.js
  yarn.lock
Labels: cla: yes

#26598 Update validator-amp-mega-menu.protoascii
  extensions/amp-mega-menu/validator-amp-mega-menu.protoascii
Labels: WG: caching, cla: yes

#26567 ♻️ peformance-impl: simplify tick()
  src/service/performance-impl.js
Labels: cla: yes

#26566 📖 Download the JDK not JRE
  contributing/getting-started-e2e.md
Labels: WG: infra, WG: outreach, cla: yes

#26605 Fix sharing layout when the label is two lines long.
  extensions/amp-story/1.0/amp-story-share-menu.css
  extensions/amp-story/1.0/amp-story-share.css
Labels: cla: yes

#26604 🚫 [amp-story-player] Temporarily disable messaging
  examples/amp-story/player.html
  src/amp-story-player.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#26583 🐛 batched-xhr-impl: use absolute url as key for batchFetch
  src/service/batched-xhr-impl.js
  test/unit/test-batched-xhr.js
Labels: cla: yes

#26613 🖍 [amp-story-player] Extract iframe css to different file
  build-system/tasks/css.js
  css/OWNERS
  css/amp-story-player-iframe.css
  css/amp-story-player.css
  src/amp-story-player.js
Labels: cla: yes

#26616 🐛 Fix typos for amp-story.md
  extensions/amp-story/amp-story.md
Labels: cla: yes

#26482 ✨Add percentage display to <amp-story-quiz>
  extensions/amp-story/1.0/amp-story-quiz.css
  extensions/amp-story/1.0/amp-story-quiz.js
  extensions/amp-story/1.0/test/test-amp-story-quiz.js
Labels: cla: yes

#26493 amp-list: Add user warning to use binding=refresh
  extensions/amp-list/0.1/amp-list.js
Labels: cla: yes

#26460 Updating path to Yahoo ad script
  ads/_config.js
  ads/yahoo.js
Labels: cla: yes

#26600 🏗 SwG Release 0.1.22.92
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#26587 ♻️ Use new mutator API in auto-lightbox
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
  extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
Labels: cla: yes

#26504 📖 Update list of video players
  spec/amp-video-interface.md
Labels: cla: yes

#26596 Ibeat Analytics tracking method changed
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/ibeatanalytics.js
  extensions/amp-analytics/0.1/vendors/ibeatanalytics.json
Labels: cla: yes

#26621 Validator rollup
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#26607 Fix shadow test state pollution
  test/unit/test-shadow-embed.js
Labels: cla: yes

#26546 ♻️ Resource=>Mutator refactor for apester-media
  extensions/amp-apester-media/0.1/monetization/companion/display.js
  extensions/amp-apester-media/0.1/monetization/companion/video.js
  extensions/amp-apester-media/0.1/test/test-amp-apester-monetization.js
Labels: cla: yes

#24917 ✨Add amp-iframe support for Pym.js width and height resize messages
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
  test/fixtures/served/iframe.html
Labels: cla: yes

#26456 amp-consent a11y improvement
  examples/amp-consent/diy-consent.html
  extensions/amp-consent/0.1/amp-consent.css
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  test/manual/amp-consent/amp-consent-cmp-overlay.html
Labels: cla: yes

#26532 Remove visual diff test for amp-consent
  examples/visual-tests/amp-consent/amp-consent.amp.html
  examples/visual-tests/amp-consent/amp-consent.js
  test/visual-diff/visual-tests
Labels: cla: yes

#26636 ✨ Support data-param-* in amp-video-iframe
  extensions/amp-video-iframe/0.1/amp-video-iframe.js
  extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
  extensions/amp-video-iframe/amp-video-iframe.md
Labels: cla: yes

#26609 ampdoc: Add get/setMetaByName methods
  src/multidoc-manager.js
  src/service/ampdoc-impl.js
  test/unit/test-ampdoc.js
  test/unit/test-runtime.js
Labels: cla: yes

#26271 Resolve macros before encoding for analytics variables
  build-system/tasks/presubmit-checks.js
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/resource-timing.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-analytics/0.1/test/test-resource-timing.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
  extensions/amp-analytics/analytics-vars.md
  src/string.js
  test/manual/amp-analytics/analytics-nested.html
  test/unit/test-string.js
Labels: cla: yes

#26635 🌐Add i18n for <amp-story-quiz> answer choice options
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/amp-story-quiz.js
  extensions/amp-story/1.0/test/test-amp-story-quiz.js
  src/localized-strings.js
Labels: cla: yes

#26539 ✨amp-consent: Add Chandago's AppConsent to CMPs list (#25834)
  examples/amp-consent/cmp-vendors.amp.html
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/amp-consent.md
  extensions/amp-consent/cmps/appconsent.md
Labels: cla: yes

#26618 ♻️ performance-impl: delete unused code
  src/service/performance-impl.js
Labels: cla: yes

#26659 Skip ads test breaking master
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
Labels: cla: yes

#26650 quick fix and update to amp-timeago
  extensions/amp-timeago/amp-timeago.md
Labels: cla: yes

#26624 🐛 amp-story: Remove duplicate replaceState on navigation
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
  extensions/amp-story/1.0/utils.js
Labels: cla: yes

#26658 🐛 amp-subscriptions: Fixes click event delegation for iOS 12 and lower
  extensions/amp-subscriptions/0.1/local-subscription-platform-base.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Labels: cla: yes

#26581 Fix advancementMode variables for time based advancements.
  extensions/amp-story/1.0/page-advancement.js
Labels: cla: yes

#26447 ♻️Rename ShadowDomWriter* => DomWriter*
  src/shadow-embed.js
  src/utils/dom-writer.js
  test/unit/test-shadow-embed.js
  test/unit/utils/test-dom-writer.js
Labels: cla: yes

#26670 ✅ Set amp-ad unit test to use unreachable domain
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
Labels: cla: yes

#26668 📖 Migrate mediapool overview doc to 1.0
  extensions/amp-story/1.0/media-pool.md
Labels: cla: yes

#26672 ✅ Fix shadow tests broken due to deprecated createShadowRoot API
  test/unit/test-ampdoc.js
Labels: cla: yes

#26475 🖍 Increase CSS byte limit from 50000 bytes to 75000 bytes
  spec/amp-html-format.md
  validator/engine/validator_test.js
  validator/java/src/main/proto/validator.proto
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: Validator: Approved, WG: amp4email, WG: caching, WG: outreach, WG: performance, cla: yes

#26517 ✨Implement amp-ad-exit indirect targets
  examples/amp-ad-exit.amp.html
  extensions/amp-ad-exit/0.1/amp-ad-exit.js
  extensions/amp-ad-exit/0.1/test-e2e/test-amp-ad-exit.js
  extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
  test/fixtures/e2e/amphtml-ads/amp-ad-exit.amp.html
Labels: cla: yes

#26674 ✅Change domains on tests for ads/analytics
  ads/google/a4a/shared/test/test-url-builder.js
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
  extensions/amp-ad/0.1/test/test-amp-ad-custom.js
  extensions/amp-ad/0.1/test/test-amp-ad.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  extensions/amp-analytics/0.1/test/test-config-new.js
  extensions/amp-analytics/0.1/test/test-config.js
  extensions/amp-analytics/0.1/test/test-cookie-writer.js
  extensions/amp-analytics/0.1/test/test-linker-manager.js
  extensions/amp-analytics/0.1/test/test-requests.js
Labels: cla: yes

#26340 make extensions end in mjs file extension type
  build-system/compile/compile.js
  build-system/tasks/dist.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
  examples/everything.amp.esm.html
  package.json
  yarn.lock
Labels: Related to: Performance, Type: Feature Request, cla: yes

#26648 Nested macros adding caveat documentation
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/analytics-vars.md
Labels: cla: yes

#26564 TE Medya (Vidyome) Native Ads Integration
  3p/integration.js
  ads/_config.js
  ads/temedya.js
  ads/temedya.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#23933 Enable a4a friendly iframe css splitting for prod
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  src/friendly-iframe-embed.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#26663 🖍 Remove placeholder on amp-access-scroll
  extensions/amp-access-scroll/0.1/amp-access-scroll.css
  extensions/amp-access-scroll/0.1/scroll-bar.js
Labels: cla: yes

#26679 amp-access: Support i-amphtml-access-state lookup in AmpDocShadow
  extensions/amp-access/0.1/amp-access-server-jwt.js
  extensions/amp-access/0.1/amp-access-server.js
Labels: cla: yes

#26706 SwG Release 0.1.22.93
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#26707 🐛📖 Fix amp-consent.md url
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#26708 ✨amp-inline-gallery docs and validation rules
  extensions/amp-inline-gallery/0.1/amp-inline-gallery.js
  extensions/amp-inline-gallery/0.1/test/validator-amp-inline-gallery-pagination.html
  extensions/amp-inline-gallery/0.1/test/validator-amp-inline-gallery-pagination.out
  extensions/amp-inline-gallery/0.1/test/validator-amp-inline-gallery-thumbnails.html
  extensions/amp-inline-gallery/0.1/test/validator-amp-inline-gallery-thumbnails.out
  extensions/amp-inline-gallery/amp-inline-gallery.md
  extensions/amp-inline-gallery/validator-amp-inline-gallery.protoascii
Labels: Validator: Approved, cla: yes

#26640 📖 Cleanup amp-list documentation indentations
  extensions/amp-list/amp-list.md
Labels: cla: yes

#26721 🏗 Watch and rebuild `amp-a4a` when an ad network extension is being watched
  build-system/tasks/extension-helpers.js
Labels: WG: ads, WG: infra, cla: yes

#26535 amp-script: Use updated method to get meta hashes
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
Labels: Component: amp-script, WG: performance, cla: yes

#26720 🚀 Remove amp-truncate-text experiment check
  extensions/amp-truncate-text/0.1/amp-truncate-text.js
  extensions/amp-truncate-text/0.1/test/test-amp-truncate-text.js
Labels: cla: yes

#26710 ✨Implement amp-stream-gallery
  build-system/compile/bundles.config.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-stream-gallery/0.1/amp-stream-gallery.css
  extensions/amp-stream-gallery/0.1/amp-stream-gallery.js
  extensions/amp-stream-gallery/0.1/arrows.css
  extensions/amp-stream-gallery/0.1/inset-arrows.css
  extensions/amp-stream-gallery/0.1/outset-arrows.css
  extensions/amp-stream-gallery/0.1/test/test-amp-stream-gallery.js
  extensions/amp-stream-gallery/OWNERS
  test/manual/amp-stream-gallery/basic.amp.html
  test/manual/amp-stream-gallery/custom-arrows.amp.html
  test/manual/amp-stream-gallery/enable-experiment.html
  test/manual/amp-stream-gallery/outset-arrows-partial-count-approximate.amp.html
  test/manual/amp-stream-gallery/outset-arrows-partial-count.amp.html
  test/manual/amp-stream-gallery/outset-arrows.amp.html
  test/manual/amp-stream-gallery/responsive.amp.html
  test/manual/amp-stream-gallery/rtl.amp.html
  test/manual/amp-stream-gallery/spacing.amp.html
  tools/experiments/experiments-config.js
Labels: cla: yes

#26422 Added pauseCallback in amp-ima-video
  extensions/amp-ima-video/0.1/amp-ima-video.js
Labels: cla: yes

#23660 🐛amp-ima-video: show play/pause button in ad controls
  ads/google/imaVideo.js
  extensions/amp-ima-video/0.1/test/test-amp-ima-video.js
Labels: cla: yes

#26683 amp-analytics: Support amp-google-client-id-api lookup in AmpDocShadow
  extensions/amp-analytics/0.1/linker-manager.js
  src/service/cid-impl.js
Labels: cla: yes

#26727 🚀 Change `const` to `let` VariableDeclarations for ESM Output
  build-system/babel-plugins/babel-plugin-const-transformer/index.js
  build-system/babel-plugins/babel-plugin-const-transformer/test/fixtures/transform-assertions/ignored-let/input.js
  build-system/babel-plugins/babel-plugin-const-transformer/test/fixtures/transform-assertions/ignored-let/options.json
  build-system/babel-plugins/babel-plugin-const-transformer/test/fixtures/transform-assertions/ignored-let/output.js
  build-system/babel-plugins/babel-plugin-const-transformer/test/fixtures/transform-assertions/ignored-var/input.js
  build-system/babel-plugins/babel-plugin-const-transformer/test/fixtures/transform-assertions/ignored-var/options.json
  build-system/babel-plugins/babel-plugin-const-transformer/test/fixtures/transform-assertions/ignored-var/output.js
  build-system/babel-plugins/babel-plugin-const-transformer/test/fixtures/transform-assertions/should-transform/input.js
  build-system/babel-plugins/babel-plugin-const-transformer/test/fixtures/transform-assertions/should-transform/options.json
  build-system/babel-plugins/babel-plugin-const-transformer/test/fixtures/transform-assertions/should-transform/output.js
  build-system/babel-plugins/babel-plugin-const-transformer/test/index.js
Labels: cla: yes

#26056 Update Analytics integration doc
  extensions/amp-analytics/integrating-analytics.md
Labels: cla: yes

#26722 amp-consent uiConfig and captions documentation
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#26733 Fork media amp-ad update
  ads/_config.js
  ads/forkmedia.js
Labels: cla: yes

#26736 🐛 Fix validation error
  extensions/amp-story/amp-story-page-attachment.md
Labels: cla: yes

#26744 Fix amp-video layoutCallback on first story page.
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#26702 🐛 Subscriptions: Stops stopping propagation of click events
  extensions/amp-subscriptions/0.1/local-subscription-platform-base.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Labels: cla: yes

#26610 ✨<amp-next-page> v2 default and templated footers (more articles box)
  extensions/amp-next-page/1.0/amp-next-page.css
  extensions/amp-next-page/1.0/page.js
  extensions/amp-next-page/1.0/service.js
  extensions/amp-next-page/1.0/test/test-amp-next-page.js
  extensions/amp-next-page/1.0/visibility-observer.js
  test/manual/amp-next-page/1.0/amp-next-page.amp.html
Labels: cla: yes

#26705 Remove amp-autocomplete form ancestor requirement
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/autocomplete-binding-def.js
  extensions/amp-autocomplete/0.1/autocomplete-binding-inline.js
  extensions/amp-autocomplete/0.1/autocomplete-binding-single.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-bindings.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Labels: cla: yes

#26719 ✨[amp-story-player] Install viewer integration script when inside the player
  extensions/amp-story/1.0/amp-story.js
  src/amp-story-player.js
Labels: cla: yes

#26743 Add notify:true for amphtml/validator/...
  validator/OWNERS
Labels: WG: caching, cla: yes

#26724 Remove geooverride flag
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-client-side.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side-expire-cache.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#26747 🐛 Allow <script> templates to be referenced by id.
  extensions/amp-mustache/validator-amp-mustache.protoascii
  extensions/amp-script/validator-amp-script.protoascii
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#26711 🚀 Remove older performance info
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes

#26638 ♻️ Remerge: Resources/Mutator service refactor
  build-system/tasks/presubmit-checks.js
  src/inabox/inabox-mutator.js
  src/inabox/inabox-resources.js
  src/inabox/inabox-services.js
  src/service/core-services.js
  src/service/mutator-impl.js
  src/service/resources-impl.js
  src/service/resources-interface.js
  src/services.js
  test/unit/test-mutator.js
  test/unit/test-resources.js
Labels: cla: yes

#26757 🐛✅TE Medya Ad Type
  ads/_config.js
Labels: cla: yes

#26732 🐛 Fix validator Chrome extension for Chrome 80+
  validator/chromeextension/bower.json
  validator/chromeextension/popup-validator.html
Labels: WG: caching, cla: yes

#26487 📖 amp-consent fullscreen restriction documentation
  extensions/amp-consent/integrating-consent.md
Labels: cla: yes

#26344 ✅ Add integration for shadow AMP v0.js
  build-system/externs/amp.extern.js
  test/fixtures/served/shadow.html
  test/integration/test-shadow-amp.js
  testing/test-helper.js
Labels: Category: PWA, WG: performance, cla: yes

#26761 🐛 Force bust cached document for amp-addthis
  extensions/amp-addthis/0.1/amp-addthis.js
  extensions/amp-addthis/0.1/test/test-amp-addthis.js
Labels: cla: yes

#26748 🚮 Delete gulp changelog
  build-system/tasks/changelog.js
  gulpfile.js
  package.json
  yarn.lock
Labels: cla: yes

#26745 📖 Analytics var documentation format
  extensions/amp-analytics/analytics-vars.md
Labels: cla: yes

#26767 Bump version number, remove key
  validator/chromeextension/manifest.json
Labels: WG: caching, cla: yes

#26399 ✨ Allow a[type=application/rss+xml] in validator spec
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#26403 ✨ Allow pubdate attribute on time element
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#26362 ✨ Add 'feed' to allowed protocols for links
  validator/validator-main.protoascii
Labels: Validator: Approved, WG: caching, cla: yes

#25975 📖 amp-consent: Add Ogury CMP doc + example
  examples/amp-consent/cmp-vendors.amp.html
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/amp-consent.md
  extensions/amp-consent/cmps/ogury.md
Labels: cla: yes

#22725 📖 Update allowed form input elements
  spec/amp-html-format.md
Labels: cla: yes

#26769 🏗🐛 Wait for Percy agent to start before performing visual diff tests
  build-system/tasks/visual-diff/index.js
  package.json
  yarn.lock
Labels: cla: yes

#26771 Validator rollup
  validator/nodejs/README.md
  validator/validator-main.protoascii
Labels: cla: yes

#26774 Update nodejs and gulpjs versions and README
  validator/gulpjs/README.md
  validator/nodejs/README.md
  validator/nodejs/package.json
Labels: cla: yes

#26768 Update chrome extension icon
  validator/chromeextension/amp-icon-128.png
Labels: WG: caching, cla: yes

#26776 Do not allow arrow functions as the "factory" function for registerServiceDorDoc
  .eslintrc
  build-system/eslint-rules/no-arrow-on-register-functions.js
  extensions/amp-geo/0.1/amp-geo.js
  extensions/amp-next-page/0.1/amp-next-page.js
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
Labels: cla: yes

#26775 Update validator version & fix tests
  validator/gulpjs/package.json
  validator/gulpjs/test/validate.js
Labels: cla: yes

#26465 Enable text/javascript header type.
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
Labels: cla: yes

#26784 Make image responsive
  extensions/amp-story/amp-story.md
Labels: cla: yes

#26589 🐛amp-autocomplete: preserve existing query parameters. Fixes #26522
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Labels: cla: yes

#26580 Updated amp-accordion and amp-bind documentation
  extensions/amp-accordion/amp-accordion.md
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#26780 Fix script calculations
  examples/ads.amp.esm.html
  src/service/extension-location.js
  src/service/extensions-impl.js
  test/unit/test-extension-location.js
Labels: cla: yes

#26787 update gulpjs README.md version notes
  validator/gulpjs/README.md
Labels: WG: caching, cla: yes

#26752 ♻️Move new methods in resources service to package visibility
  src/service/resources-interface.js
Labels: cla: yes

#26788 🐛Fixes swipe to dismiss badly ordered swipes on `amp-lightbox-gallery`
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/swipe-to-dismiss.js
Labels: cla: yes

#26737 trying to update Sauce timeouts
  build-system/tasks/karma.conf.js
Labels: cla: yes

#26749 🐛Check for window null before creating tracking pixel
  builtins/amp-pixel.js
  extensions/amp-analytics/0.1/transport.js
  src/pixel.js
Labels: cla: yes

#26680 Add PWA multidoc loader to examples
  examples/pwa-multidoc-loader.html
Labels: cla: yes

#26753 ✅Another set of example.com change
  ads/google/a4a/test/test-utils.js
  build-system/server/amp4test.js
  build-system/server/app.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-ad-network-fake-impl/0.1/test/test-amp-ad-network-fake-impl.js
  extensions/amp-ad-network-fake-impl/0.1/test/test-external-reorder-head-transformer.js
  extensions/amp-analytics/0.1/test/test-iframe-transport-message-queue.js
  extensions/amp-analytics/0.1/test/test-iframe-transport.js
  extensions/amp-analytics/0.1/test/test-resource-timing.js
  extensions/amp-analytics/0.1/test/test-transport.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-consent/0.1/test/test-consent-config.js
  test/unit/test-extension-analytics.js
  test/unit/test-friendly-iframe-embed.js
Labels: cla: yes

#26798 Sync from Google
  validator/htmlparser/strings.cc
  validator/htmlparser/strings.h
  validator/htmlparser/tokenizer.cc
Labels: WG: caching, cla: yes

#26800 Sync from Google
  validator/htmlparser/atom.h
  validator/htmlparser/bin/atomgen.cc
  validator/htmlparser/bin/casetablegen.cc
  validator/htmlparser/bin/entitytablegen.cc
  validator/htmlparser/casetable.h
  validator/htmlparser/entity.h
Labels: WG: caching, cla: yes

#25113 🚀 Move ads variables to amp-analytics
  extensions/amp-a4a/0.1/a4a-variable-source.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
  src/service/url-replacements-impl.js
  test/integration/test-amp-analytics.js
  test/manual/amp-analytics/analytics-fcp.html
  test/unit/test-url-replacements.js
Labels: cla: yes

#26212 Move video_state macro
  src/service/url-replacements-impl.js
  src/service/video-manager-impl.js
  test/manual/amp-video.amp.html
  test/unit/test-url-replacements.js
Labels: cla: yes

#26803 Sync from Google
  validator/htmlparser/atom.h
  validator/htmlparser/bin/casetablegen.cc
  validator/htmlparser/data/CaseFolding.txt
  validator/htmlparser/data/SpecialCasing.txt
  validator/htmlparser/data/UnicodeData.txt
  validator/htmlparser/data/extras.txt
  validator/htmlparser/data/ucs2.txt
  validator/htmlparser/defer.h
  validator/htmlparser/foreign.cc
  validator/htmlparser/foreign.h
  validator/htmlparser/htmldataset_test.cc
  validator/htmlparser/navigator_test.cc
  validator/htmlparser/node_test.cc
  validator/htmlparser/parser.cc
  validator/htmlparser/parser.h
  validator/htmlparser/renderer.cc
  validator/htmlparser/renderer_test.cc
  validator/htmlparser/testconstants.h
  validator/htmlparser/tokenizer.cc
  validator/htmlparser/tokenizer.h
  validator/htmlparser/tokenizer_test.cc
Labels: WG: caching, cla: yes

#26300 Mock variableService getMacros
  extensions/amp-analytics/0.1/test/test-vendors-new.js
  extensions/amp-analytics/0.1/test/test-vendors.js
  extensions/amp-analytics/0.1/test/vendor-requests.json
Labels: cla: yes

#26766 Turn on restrict fullscreen flag canary
  build-system/global-configs/canary-config.json
Labels: cla: yes

#26695 Variable substitution tester
  build-system/server/app.js
  build-system/server/variable-substitution.js
  build-system/tasks/presubmit-checks.js
  test/manual/amp-analytics/variable-request-examples.html
  test/manual/amp-analytics/variable-request-tester.html
Labels: cla: yes

#26795 Fix more arrow functions that are passed in as "constructors"
  build-system/compile/compile.js
  build-system/eslint-rules/no-arrow-on-register-functions.js
  extensions/amp-apester-media/0.1/test/test-amp-apester-monetization.js
  extensions/amp-crypto-polyfill/0.1/amp-crypto-polyfill.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/test/test-amp-story-consent.js
  extensions/amp-story/0.1/test/test-amp-story-hint.js
  extensions/amp-story/0.1/test/test-amp-story-info-dialog.js
  extensions/amp-story/0.1/test/test-amp-story-share-menu.js
  extensions/amp-story/0.1/test/test-amp-story-system-layer.js
  extensions/amp-story/0.1/test/test-amp-story.js
  extensions/amp-story/0.1/test/test-full-bleed-animations.js
  extensions/amp-story/0.1/test/test-navigation-state.js
  extensions/amp-story/1.0/amp-story-media-query-service.js
  extensions/amp-story/1.0/amp-story-request-service.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/media-performance-metrics-service.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-amp-story-access.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
  extensions/amp-story/1.0/test/test-amp-story-consent.js
  extensions/amp-story/1.0/test/test-amp-story-cta-layer.js
  extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
  extensions/amp-story/1.0/test/test-amp-story-hint.js
  extensions/amp-story/1.0/test/test-amp-story-info-dialog.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
  extensions/amp-story/1.0/test/test-amp-story-quiz.js
  extensions/amp-story/1.0/test/test-amp-story-share-menu.js
  extensions/amp-story/1.0/test/test-amp-story-system-layer.js
  extensions/amp-story/1.0/test/test-amp-story.js
  extensions/amp-story/1.0/test/test-full-bleed-animations.js
  extensions/amp-story/1.0/test/test-live-story-manager.js
  extensions/amp-story/1.0/variable-service.js
  extensions/amp-user-notification/0.1/test/test-amp-user-notification.js
  src/service.js
  test/unit/test-element-service.js
  testing/test-helper.js
Labels: cla: yes

#26162 🚮 Removing amp-consent-v2 experiment logic
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  examples/amp-consent/cmp-vendors.amp.html
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-config.js
  extensions/amp-consent/0.1/consent-info.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-config.js
  extensions/amp-consent/0.1/test/test-consent-info.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#26815 application/json is ab allowed type for <script>
  spec/amp-html-format.md
Labels: cla: yes

#26824 build-system: Fix autocomplete error response
  build-system/server/app.js
Labels: cla: yes

#26814 🏗 Ensure valid flag usage for `gulp` tasks
  build-system/tasks/build.js
  build-system/tasks/integration.js
  build-system/tasks/process-3p-github-pr.js
  gulpfile.js
Labels: cla: yes

#26842 🐛 Add gulp dist flags
  build-system/tasks/dist.js
Labels: cla: yes

#25836 ✨Lentainform uniq ad
  ads/lentainform.js
Labels: cla: yes

#26845 Validator rollup
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
  validator/testdata/amp4ads_feature_tests/amp_form.html
  validator/testdata/amp4ads_feature_tests/amp_form.out
  validator/testdata/amp4email_feature_tests/amp_form.html
  validator/testdata/amp4email_feature_tests/amp_form.out
  validator/testdata/feature_tests/forms.html
  validator/testdata/feature_tests/forms.out
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#26851 Do not append `sourceMappingURL` to map files
  build-system/compile/compile.js
Labels: cla: yes

#26793 Fix story page sizing variables.
  extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads-fullbleed.js
  extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads.js
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#26751 ✨[amp-story-player] Adds navigation logic
  src/OWNERS
  src/amp-story-player-iframe-pool.js
  src/amp-story-player.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#26849 ✨Render captions in the vertical render mode of stories
  examples/visual-tests/amp-story/amp-story-bot-rendering.html
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-vertical.css
  extensions/amp-story/1.0/semantic-render.js
  extensions/amp-story/1.0/test/test-semantic-render.js
Labels: cla: yes

#26857 amp-bind: getStateValue: Return nullable string
  extensions/amp-bind/0.1/bind-impl.js
  src/service/url-replacements-impl.js
Labels: cla: yes

#26864 ✅ Skip flaky shadow integration test on Safari
  test/integration/test-shadow-amp.js
Labels: Related to: Flaky Tests, WG: performance, cla: yes

#26831 ampdoc: Fix params unit test
  test/unit/test-ampdoc.js
Labels: cla: yes

#26856 Sync from Google
  validator/htmlparser/BUILD
  validator/htmlparser/README.md
  validator/htmlparser/WORKSPACE
  validator/htmlparser/bin/jsongrammargen.cc
  validator/htmlparser/data/jsongrammar.txt
  validator/htmlparser/fileutil.cc
  validator/htmlparser/fileutil.h
  validator/htmlparser/fileutil_test.cc
  validator/htmlparser/grammar/tablebuilder.cc
  validator/htmlparser/grammar/tablebuilder.h
  validator/htmlparser/json/jsondataset_test.cc
  validator/htmlparser/json/parser.cc
  validator/htmlparser/json/parser.h
  validator/htmlparser/json/parser_test.cc
  validator/htmlparser/json/states.h
  validator/htmlparser/json/testdata/1.json
  validator/htmlparser/json/testdata/10.json
  validator/htmlparser/json/testdata/2.json
  validator/htmlparser/json/testdata/3.json
  validator/htmlparser/json/testdata/4.json
  validator/htmlparser/json/testdata/5.json
  validator/htmlparser/json/testdata/6.json
  validator/htmlparser/json/testdata/7.json
  validator/htmlparser/json/testdata/8.json
  validator/htmlparser/json/testdata/9.json
  validator/htmlparser/json/testdata/README
  validator/htmlparser/logging.h
  validator/htmlparser/node.cc
  validator/htmlparser/parser.cc
  validator/htmlparser/parser_test.cc
  validator/htmlparser/renderer.cc
  validator/htmlparser/strings.cc
  validator/htmlparser/strings.h
  validator/htmlparser/strings_test.cc
  validator/htmlparser/whitespacetable.h
Labels: WG: caching, cla: yes

#26870 Different typo fix
  build-system/tasks/extension-generator/extension-doc.template.md
Labels: cla: yes

#26869 Removed entire table!!!
  build-system/tasks/extension-generator/extension-doc.template.md
Labels: cla: yes

#26867 Removed examples from table
  build-system/tasks/extension-generator/extension-doc.template.md
Labels: cla: yes

#26871 Replacing onMeasuredChange with onLayoutCallback.
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#26875 ✅ Skip another flaky shadow integration test on Safari
  test/integration/test-shadow-amp.js
Labels: Related to: Flaky Tests, WG: performance, cla: yes

#25838 ✨Idealmedia uniq ad
  ads/idealmedia.js
  examples/ads.amp.html
Labels: cla: yes

#26739 🐛 Bug fix: check links test
  build-system/tasks/check-links.js
Labels: cla: yes

#26891 Add performance metrics to README
  build-system/tasks/performance/README.md
Labels: cla: yes

#26855 amp-sticky-ad: Fix unit test
  extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
Labels: cla: yes

#26899 🐛 Update owners file to correct syntax
  css/OWNERS
  src/OWNERS
Labels: cla: yes

#26865 ✨[amp-story-player] Adds tap-to-next/previous story
  css/amp-story-player-iframe.css
  examples/amp-story/player.html
  src/amp-story-player.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#26741 Update consent string maximum size to 200 bytes
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  extensions/amp-consent/integrating-consent.md
Labels: cla: yes

#25594 🚀 Move scroll left and top macros out of url-replacement-impl
  extensions/amp-a4a/0.1/a4a-variable-source.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
  src/service/url-replacements-impl.js
  test/unit/test-url-replacements.js
  test/unit/test-viewport-binding.js
  testing/fake-dom.js
Labels: cla: yes
