Repository ampproject/amphtml, pull requests merged in 2020-07, with the labels that each got.

#28887 amp-date-picker: restore rrule support
  build-system/compile/sources.js
  build-system/externs/amp.extern.js
  build-system/tasks/update-packages.js
  examples/date-picker.amp.html
  extensions/amp-date-picker/0.1/dates-list.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker.js
  extensions/amp-date-picker/0.1/test/test-dates-list.js
  extensions/amp-date-picker/amp-date-picker.md
  package.json
  test/fixtures/e2e/amp-date-picker/blocked-dates.html
  yarn.lock
Labels: cla: yes

#29038 🏗🚮 Stop testing on Sauce Labs and delete all related infrastructure
  .gitignore
  build-system/pr-check/remote-tests.js
  build-system/pr-check/utils.js
  build-system/sauce_connect/OWNERS
  build-system/sauce_connect/start_sauce_connect.sh
  build-system/sauce_connect/stop_sauce_connect.sh
  build-system/tasks/a4a.js
  build-system/tasks/integration.js
  build-system/tasks/karma.conf.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/unit.js
  contributing/TESTING.md
  contributing/buildcop.md
  contributing/getting-started-e2e.md
  extensions/amp-image-lightbox/0.1/test/integration/test-amp-image-lightbox.js
  extensions/amp-inputmask/0.1/test/integration/test-integration-amp-inputmask-date.js
  extensions/amp-inputmask/0.1/test/integration/test-integration-amp-inputmask.js
  extensions/amp-viewer-integration/0.1/test/integration/test-amp-viewer-integration.js
  package.json
  test/_init_tests.js
  test/integration/test-actions.js
  test/integration/test-amp-ad-3p.js
  test/integration/test-amp-ad-doubleclick.js
  test/integration/test-amp-analytics.js
  test/integration/test-amp-img.js
  test/integration/test-amp-pixel.js
  test/integration/test-amp-recaptcha-input.js
  test/integration/test-boilerplates.js
  test/integration/test-configuration.js
  test/integration/test-css.js
  test/integration/test-errors.js
  test/integration/test-extensions-loading.js
  test/integration/test-released.js
  test/integration/test-toggle-display.js
  test/integration/test-video-players.js
  test/unit/test-cache-cid-api.js
  test/unit/test-cid.js
  test/unit/test-crypto.js
  test/unit/test-error.js
  test/unit/test-origin-experiments.js
  test/unit/test-storage.js
  test/unit/test-url-replacements.js
  test/unit/test-url.js
  test/unit/utils/test-base64.js
  test/unit/utils/test-pem.js
  testing/describes.js
  testing/test-helper.js
  yarn.lock
Labels: WG: infra, cla: yes

#29060 🖍 Transforms only fix to display small percentages in binary polls.
  extensions/amp-story/1.0/amp-story-interactive-binary-poll.css
  extensions/amp-story/1.0/amp-story-interactive-binary-poll.js
  extensions/amp-story/1.0/test/test-amp-story-interactive-binary-poll.js
Labels: cla: yes

#29091 Add asterisk to comments that were meant to be jsdocs in amp.extern
  build-system/externs/amp.extern.js
Labels: cla: yes

#29099 🏗 Use native closure compiler with pre-compiled AMP runner
  .gitignore
  build-system/compile/closure-compile.js
  build-system/compile/compile.js
  build-system/runner/OWNERS
  build-system/runner/build.xml
  build-system/runner/src/org/ampproject/AmpCodingConvention.java
  build-system/runner/src/org/ampproject/AmpCommandLineRunner.java
  build-system/tasks/check-types.js
  build-system/tasks/clean.js
  build-system/tasks/default-task.js
  build-system/tasks/dist.js
  build-system/tasks/generate-runner.js
  build-system/tasks/helpers.js
  build-system/tasks/nailgun-compile
  build-system/tasks/nailgun.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/serve.js
  gulpfile.js
  package.json
  third_party/nailgun/README.amp
  third_party/nailgun/nailgun-runner
  third_party/nailgun/nailgun-server.jar
  yarn.lock
Labels: cla: yes

#29107 🏗 Add a `--flavor` flag to `gulp release`
  build-system/tasks/release/index.js
Labels: cla: yes

#29112 ❄️ Skip tests that are known to fail on GH Actions
  build-system/pr-check/cross-browser-tests.js
  test/integration/test-amp-recaptcha-input.js
  test/integration/test-amphtml-ads.js
  test/integration/test-user-error-reporting.js
Labels: Related to: Flaky Tests, cla: yes

#29023 ✨ amp-story-360 extension (base functionality)
  build-system/compile/bundles.config.js
  build-system/compile/sources.js
  build-system/test-configs/dep-check-config.js
  examples/amp-story-360.amp.html
  extensions/amp-story-360/0.1/amp-story-360.css
  extensions/amp-story-360/0.1/amp-story-360.js
  extensions/amp-story-360/0.1/test/test-amp-story-360.js
  extensions/amp-story-360/OWNERS
  third_party/zuho/README.amp
  third_party/zuho/zuho.js
Labels: cla: yes

#29120 🏗 Delete legacy validator generator
  validator/validator_gen.py
Labels: cla: yes

#29104 Propagate amp-img crossorigin attribute.
  builtins/amp-img.js
  test/unit/test-amp-img.js
  validator/validator-main.protoascii
Labels: cla: yes

#27216 added blurb about font-display and cleaned up language format
  extensions/amp-font/amp-font.md
Labels: cla: yes

#28972 write transformer tests for css insertion
  build-system/server/new-server/transforms/css/css-transform.ts
  build-system/server/new-server/transforms/css/test/css.txt
  build-system/server/new-server/transforms/css/test/esm-env-input.html
  build-system/server/new-server/transforms/css/test/esm-env-output.html
  build-system/server/new-server/transforms/css/test/version.txt
  build-system/server/new-server/transforms/transform.ts
Labels: cla: yes

#29147 📦 Update linting devDependencies (minor)
  build-system/server/lazy-build.js
  build-system/tasks/performance/rewrite-script-tags.js
  package.json
  third_party/amp-toolbox-cache-url/package.json
  yarn.lock
Labels: cla: yes

#29079 ✨ Implement story Interactive poll
  build-system/compile/bundles.config.js
  examples/amp-story/interactives.html
  extensions/amp-story/1.0/amp-story-interactive-binary-poll.css
  extensions/amp-story/1.0/amp-story-interactive-poll.css
  extensions/amp-story/1.0/amp-story-interactive-poll.js
  extensions/amp-story/1.0/amp-story-interactive-quiz.css
  extensions/amp-story/1.0/amp-story-interactive.css
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
Labels: WG: stories, cla: yes

#29095 🐛 amp-autocomplete: Set default filter to "none"
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
Labels: cla: yes

#29132 🐛 third_party/zuho - fix closure compile, update README.amp
  third_party/zuho/README.amp
  third_party/zuho/zuho.js
Labels: cla: yes

#29083 📖 Document amp-consent TCF support
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#29122 📖 Fix typo in amp-img documentation
  builtins/amp-img.md
Labels: cla: yes

#29156 🏗 Reduce JSON.stringify cost during Closure Compilation
  package.json
  yarn.lock
Labels: cla: yes

#29153 Removes Collab Summit banner from README, adds Q3 survey link
  README.md
Labels: cla: yes

#29004 📖 Remove documentation for overflow
  spec/amp-html-format.md
Labels: cla: yes

#29133 Extension docs updated to match template
  builtins/amp-layout.md
  extensions/amp-inputmask/amp-inputmask.md
  extensions/amp-install-serviceworker/amp-install-serviceworker.md
  extensions/amp-list/amp-list.md
  extensions/amp-live-list/amp-live-list.md
Labels: WG: ui-and-a11y, cla: yes

#29116 Fix 'render on idle fix' experiment logic
  src/service/resources-impl.js
Labels: cla: yes

#29108 ✨ Add class i-amphtml-story-interactive-active when current page is active to interactives
  examples/amp-story/interactives.html
  extensions/amp-story/1.0/amp-story-interactive.js
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#29113 🐛 Fix broken ads client side experiments
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
  src/ampdoc-fie.js
Labels: cla: yes

#29160 🏗 Cache Babel Results with a Map per `gulp dist`
  build-system/babel-config/pre-closure-config.js
  build-system/compile/pre-closure-babel.js
  contributing/TESTING.md
  package.json
  yarn.lock
Labels: cla: yes

#29123 🐛 Replace sourceMappingURL URL with absolute URL
  src/web-worker/amp-worker.js
  test/unit/web-worker/test-amp-worker.js
Labels: cla: yes

#29165 [amp-story-player] Set title to iframe for a11y
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#29181 Launch InOb polyfill for inabox
  build-system/global-configs/experiments-config.json
  build-system/global-configs/experiments-const.json
Labels: cla: yes

#29178 Pause/play Story level background audio on viewer/tab visibility change.
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#29175 ✨ [amp-social-share][bento] Update default background color
  extensions/amp-social-share/1.0/social-share.css.js
  extensions/amp-social-share/1.0/social-share.js
Labels: cla: yes

#29174 ✨ [amp-social-share][bento] Update experiment version
  examples/social-share.amp.html
  extensions/amp-social-share/1.0/amp-social-share.js
Labels: cla: yes

#28665 ContextNode: types and discovery phase
  src/context/index.js
  src/context/node.js
  src/context/scan.js
  src/context/scheduler.js
  src/utils/array.js
  test/unit/context/test-node-discover.js
Labels: cla: yes

#29155 ✨Add base for amp-story-interactive-results
  examples/amp-story/interactives.html
  extensions/amp-story/1.0/amp-story-interactive.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/test/test-amp-story-interactive.js
  extensions/amp-story/1.0/test/test-amp-story-store-service.js
Labels: WG: stories, cla: yes

#29163 📖 clarify isAdPositionAllowed
  extensions/amp-a4a/0.1/amp-a4a.js
Labels: cla: yes

#29198 🚮 Removed duplicate tests
  extensions/amp-story/1.0/test/test-amp-story-interactive.js
Labels: cla: yes

#29183 amp-autocomplete: Selection `change` event should bubble
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  src/service/action-impl.js
Labels: cla: yes

#29130 ✨ New feature: new supported type alright for amp-auto-ads
  extensions/amp-auto-ads/0.1/ad-network-config.js
  extensions/amp-auto-ads/0.1/alright-network-config.js
  extensions/amp-auto-ads/0.1/test/test-alright-network-config.js
  extensions/amp-auto-ads/amp-auto-ads.md
Labels: cla: yes

#29096 New Story embed mode to hide system layer icons.
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
  extensions/amp-story/1.0/embed-mode.js
Labels: cla: yes

#29205 Add player sample with local stories
  examples/amp-story/player-local-stories.html
Labels: cla: yes

#29210 🐛 Fix `gulp presubmit`
  build-system/test-configs/config.js
Labels: cla: yes

#26223 ✨ amp-subscriptions-google real time config
  build-system/server/app.js
  build-system/test-configs/dep-check-config.js
  examples/amp-subscriptions.rtc.amp.html
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.css
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions-google/amp-subscriptions-google.md
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/local-subscription-platform-base.js
  extensions/amp-subscriptions/0.1/service-adapter.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
  src/purifier/sanitation.js
  validator/validator-main.protoascii
Labels: WG: access-subscriptions, WG: caching, cla: yes

#29209 🏗🐛 Fix AMP version logic on Windows
  build-system/common/git.js
Labels: WG: infra, cla: yes

#29195 🐛 Fallback on invalid story animation attributes
  extensions/amp-story/1.0/animation.js
  extensions/amp-story/1.0/test/test-animation.js
  extensions/amp-story/1.0/test/test-utils.js
  extensions/amp-story/1.0/utils.js
Labels: cla: yes

#29218 Only play/pause background audio on visibilitystate change if story is unmuted.
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#29109 🐛 #28698: Fix for bug that was incorrectly transforming anonymous function to arrow function.
  build-system/babel-plugins/babel-plugin-transform-function-declarations/index.js
  build-system/babel-plugins/babel-plugin-transform-function-declarations/test/fixtures/transform-assertions/argument-function/input.js
  build-system/babel-plugins/babel-plugin-transform-function-declarations/test/fixtures/transform-assertions/argument-function/output.js
Labels: cla: yes

#29179 🐛📖 Update postPromptUI bug fix & doc update
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/amp-consent.md
  test/manual/amp-consent/amp-consent-inline-postPromptUI.html
Labels: cla: yes

#29226 intersect-resources: Add missing 25% loadRect expansion to rootMargin
  src/service/resources-impl.js
Labels: cla: yes

#29170 fix typo in `running-server-side-experiment.md`
  contributing/running-server-side-experiment.md
Labels: cla: yes

#29225 Revert "Enable 'intersect-resources' in 100% of prod"
  build-system/global-configs/prod-config.json
Labels: cla: yes

#29180 🐛 Prevent screen reader from announcing img src if alt tag is not specified.
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#29187 Change experiment setting to arrays
  ads/google/a4a/experiment-utils.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
  src/ampdoc-fie.js
  src/experiments.js
  src/service/resources-impl.js
  test/unit/test-experiments.js
Labels: cla: yes

#29167 ✨A4A: introduce head validation
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/head-validation.js
  extensions/amp-a4a/0.1/test/test-head-validation.js
Labels: cla: yes

#29229 ✨Introduce `srcdoc` feature to fake ad network
  examples/fake-ad.amp.html
  extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
  extensions/amp-ad-network-fake-impl/0.1/test/test-amp-ad-network-fake-impl.js
  extensions/amp-ad-network-fake-impl/amp-ad-network-fake-impl-internal.md
Labels: cla: yes

#29242 Fixed Link anchor don't jump to the right heading ampproject/amp.dev#4167
  extensions/amp-story/amp-story.md
Labels: cla: yes

#29233 Fix and improve Story first page videos.
  examples/visual-tests/amp-story/basic.html
  examples/visual-tests/amp-story/basic.rtl.html
  examples/visual-tests/amp-story/embed-mode-1.html
  examples/visual-tests/amp-story/embed-mode-2.html
  examples/visual-tests/amp-story/info-dialog.rtl.html
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
  extensions/amp-story/1.0/test/test-full-bleed-animations.js
  extensions/amp-story/1.0/utils.js
  extensions/amp-video/0.1/amp-video.js
Labels: cla: yes

#29230 🏗 Refactor `gulp clean` and add logging
  build-system/tasks/clean.js
Labels: WG: infra, cla: yes

#29248 AdSense/Doubleclick Ad - Round Positions Experiment
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#29162 ✨ Implements <amp-ad type="sona" ...>
  3p/integration.js
  ads/_config.js
  ads/sona.js
  ads/sona.md
  examples/ads.amp.html
Labels: cla: yes

#29259 📖 Fix bad quotes in amp-subscriptions-google.md
  extensions/amp-subscriptions-google/amp-subscriptions-google.md
Labels: cla: yes

#29244 ✨ Add linker to deepbi
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/deepbi.json
Labels: cla: yes

#29269 🐛 Fix gulp clean refactor bug
  build-system/tasks/clean.js
Labels: cla: yes

#28793 run v0 and extensions in strict mode
  build-system/compile/compile.js
  build-system/global-configs/experiments-config.json
  build-system/global-configs/experiments-const.json
  src/error.js
  src/service/video-manager-impl.js
  src/video-iframe-integration.js
Labels: WG: runtime, cla: yes

#28453 Resources: remove task timeouts under an experiment
  build-system/global-configs/canary-config.json
  src/service/resources-impl.js
Labels: WG: runtime, cla: yes

#29271 🐛 Make duration and easing consistent for percent bar animation.
  extensions/amp-story/1.0/amp-story-interactive-quiz.css
Labels: cla: yes

#29270 🐛 Use correct css variables on binary poll percent bars.
  extensions/amp-story/1.0/amp-story-interactive-binary-poll.css
Labels: cla: yes

#29224 POC: using externs for component props
  .eslintrc.js
  extensions/amp-fit-text/1.0/fit-text.js
  extensions/amp-fit-text/1.0/fit-text.type.js
Labels: cla: yes

#29255 🐛 Transforming stream race condition
  src/utils/dom-tranform-stream.js
  test/unit/utils/test-dom-transform-stream.js
Labels: cla: yes

#29273 🐛 [amp-story-player] Fix player tests
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29211 🐛 [amp-story-player] Fixes keyboard navigation
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#29287 🐛 amp-autocomplete `query` should respect [src] mutations
  examples/autocomplete.amp.html
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Labels: cla: yes

#26585 ✨ Amp Actions: AMP.goBack action should call history.back
  src/service/history-impl.js
  src/service/standard-actions-impl.js
  test/unit/test-history.js
  test/unit/test-standard-actions.js
Labels: WG: runtime, cla: yes

#29275 🏗 Sort z-index table differently, add instructions
  build-system/tasks/get-zindex/index.js
  build-system/tasks/get-zindex/test.js
  css/Z_INDEX.md
Labels: cla: yes

#28704 [Carousel]: Initial Preact Component
  extensions/amp-base-carousel/1.0/arrow.js
  extensions/amp-base-carousel/1.0/base-carousel.css.js
  extensions/amp-base-carousel/1.0/base-carousel.js
  extensions/amp-base-carousel/1.0/scroller.js
  extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
  extensions/amp-base-carousel/1.0/storybook/Basic.js
  extensions/amp-base-carousel/1.0/test/test-base-carousel.js
  src/preact/index.js
Labels: cla: yes

#29106 🖍✅✨ [amp-story-player] Implement back and close buttons
  css/amp-story-player-iframe.css
  examples/amp-story/player-with-button.html
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29251 ✨ [amp-story-player] Add mute and unmute methods
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29176 ✨ [amp-social-share][bento] Duplicate target logic from amp component to bento
  extensions/amp-social-share/1.0/amp-social-share.js
  extensions/amp-social-share/1.0/social-share.js
Labels: cla: yes

#29292 🐛 [amp-story-store-service] add state propery comparison for pageSize
  extensions/amp-story/1.0/amp-story-store-service.js
Labels: cla: yes

#29294 🚮 Binary Polls: Removes dead flex styling.
  extensions/amp-story/1.0/amp-story-interactive-binary-poll.css
Labels: cla: yes

#29266 🚮 Cleanup amp-consent restrict fullscreen opt in
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  examples/amp-consent/amp-consent-cmp.html
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  test/manual/amp-consent/amp-consent-cmp-overlay.html
  test/manual/amp-consent/legacy_config_support/amp-consent-cmp.html
  tools/experiments/experiments-config.js
Labels: cla: yes

#29295 ✨ yahoofedads: Change the mock js to real js lib.
  ads/yahoofedads.js
Labels: cla: yes

#29097 [amp-story-player] Implement `go` method
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29186 ✨ amp-story-player: Add play, pause and togglePaused methods to player
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29308 Copy data-bitrate attribute to origin sources
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-video/0.1/test/test-amp-video.js
Labels: cla: yes

#29297 🏗 Introducing `IS_SXG` in Babel transformers.
  build-system/babel-config/helpers.js
Labels: cla: yes

#29323 🐛 Use correct path for Yahoo Federation AD library
  ads/yahoofedads.js
  ads/yahoofedads.md
Labels: cla: yes

#29298 Reimplement amp-animation visibility trigger via IntersectionObserver
  extensions/amp-animation/0.1/amp-animation.js
  extensions/amp-animation/0.1/test/test-amp-animation.js
  extensions/amp-animation/amp-animation.md
Labels: cla: yes

#29207 [amp-story-player] Implement `navigation` event
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29328 🐛 Fix renovate bot
  .renovaterc.json
  package.json
  yarn.lock
Labels: cla: yes

#29235 ✅ amp-story-360 validator config and tests
  build-system/test-configs/dep-check-config.js
  extensions/amp-story-360/0.1/amp-story-360.js
  extensions/amp-story-360/0.1/test/test-amp-story-360.js
  extensions/amp-story-360/0.1/test/validator-amp-story-360.html
  extensions/amp-story-360/0.1/test/validator-amp-story-360.out
  extensions/amp-story-360/validator-amp-story-360.protoascii
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/test/validator-amp-story-360.html
  extensions/amp-story/1.0/test/validator-amp-story-360.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: cla: yes

#29232 📖 Recommend promptUiSrc instead of amp-iframe
  extensions/amp-consent/amp-consent.md
Labels: cla: yes

#29228 Documentation for amp-consent consentMetadata
  extensions/amp-consent/customizing-extension-behaviors-on-consent.md
  extensions/amp-consent/integrating-consent.md
Labels: cla: yes

#29334 Remove ambiguous FIE.isVisible() API
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/friendly-frame-util.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-animation/0.1/test/test-amp-animation.js
  src/friendly-iframe-embed.js
  test/unit/test-friendly-iframe-embed.js
Labels: cla: yes

#29343 update amp-story-360-regex
  extensions/amp-story-360/validator-amp-story-360.protoascii
Labels: WG: caching, cla: yes

#29336 🚮 [amp-list] cleanup experiment 'amp-list-init-from-state'
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#29340 [amp-story-player] Use onDocumentReady instead of window.onload
  src/amp-story-player/amp-story-player.js
Labels: cla: yes

#29344 Preact: change the Context and useContext typing to support any type
  build-system/externs/preact.extern.js
  src/preact/index.js
Labels: cla: yes

#29354 Ramp "intersect-resources" to 100% (second try)
  build-system/global-configs/prod-config.json
Labels: cla: yes

#29362 📖 Fix corrupt tip in amp-access-laterpay
  extensions/amp-access-laterpay/amp-access-laterpay.md
Labels: cla: yes

#29365 Fix `tip` markup
  extensions/amp-app-banner/amp-app-banner.md
Labels: cla: yes

#29325 [amp-social-share][bento] Remove endpoint check from amp component
  extensions/amp-social-share/1.0/amp-social-share.js
Labels: cla: yes

#29339 [amp-story-player] Implement `navigation` event for `go` method
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29249 ✨ Polls confetti mode
  examples/amp-story/interactives.html
  extensions/amp-story/1.0/amp-story-interactive.css
  extensions/amp-story/1.0/amp-story-interactive.js
  extensions/amp-story/1.0/interactive-confetti.js
Labels: cla: yes

#29337 [amp-story] Add attachmentPageId to the store
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js
  extensions/amp-story/1.0/test/test-amp-story-viewer-messaging-handler.js
Labels: cla: yes

#29381 Remove error report for startLayout flow
  src/service/resource.js
Labels: cla: yes

#29135 updated to match template
  extensions/amp-call-tracking/amp-call-tracking.md
  extensions/amp-experiment/amp-experiment.md
  extensions/amp-fit-text/amp-fit-text.md
  extensions/amp-form/amp-form.md
Labels: WG: analytics, WG: ui-and-a11y, cla: yes

#29064 Updated documentation to explain component
  extensions/amp-mowplayer/amp-mowplayer.md
Labels: WG: ui-and-a11y, cla: yes

#29327 [amp-story-player] AMP extension for the amp-story-player
  build-system/compile/bundles.config.js
  examples/amp-story/player-amp.html
  extensions/amp-story-player/0.1/amp-story-player.css
  extensions/amp-story-player/0.1/amp-story-player.js
  extensions/amp-story-player/0.1/test/validator-amp-story-player.html
  extensions/amp-story-player/0.1/test/validator-amp-story-player.out
  extensions/amp-story-player/OWNERS
  extensions/amp-story-player/validator-amp-story-player.protoascii
  src/amp-story-player/amp-story-player-iframe-pool.js
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#29375 🐛🌐 amp-consent: fix rtl support caused by alertDialog
  extensions/amp-consent/0.1/amp-consent.css
Labels: cla: yes

#29358 FIE: ensure that custom-element-registry is only used via extensions service
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/dep-check-config.js
  examples/analytics-visibility.amp.html
  src/friendly-iframe-embed-legacy.js
  src/friendly-iframe-embed.js
  src/service/extensions-impl.js
  test/unit/test-friendly-iframe-embed.js
Labels: cla: yes

#29166 ✨ Launch the random subdomain for SafeFrame experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#29331 🏗 Addition of `--sxg` flag in `dist`.
  build-system/tasks/dist.js
Labels: cla: yes

#29332 ✨Introduce rendering for unsigned creatives
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/secure-frame.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  src/friendly-iframe-embed.js
Labels: cla: yes

#29386 📖 Document `promptIfUnknownForGeoGroup` as legacy
  extensions/amp-consent/0.1/consent-config.js
Labels: cla: yes

#29382 Update more extension documentation to match template
  extensions/amp-base-carousel/amp-base-carousel.md
  extensions/amp-carousel/amp-carousel.md
  extensions/amp-date-countdown/amp-date-countdown.md
  extensions/amp-date-display/amp-date-display.md
  extensions/amp-date-picker/amp-date-picker.md
Labels: WG: ui-and-a11y, cla: yes

#29389 Resources: Don't become ready for layout if already scheduled
  src/service/resource.js
  test/unit/test-resource.js
Labels: cla: yes

#29267 Block promptUISrc from loading iframe with amp-story-consent
  extensions/amp-consent/0.1/consent-config.js
  extensions/amp-consent/0.1/test/test-consent-config.js
Labels: cla: yes

#29370 🏗 [test-case-reporting] Add report flag to gulp tasks of tests
  build-system/tasks/integration.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/unit.js
Labels: cla: yes

#29367 ✨ [bento] Add passthroughNonEmpty mode for handling children in Bento
  src/preact/base-element.js
Labels: cla: yes

#29285 ✨ [amp-social-share][bento] Allow easy styling of Social Share icons
  build-system/compile/bundles.config.js
  extensions/amp-social-share/1.0/amp-social-share.css
  extensions/amp-social-share/1.0/amp-social-share.js
  extensions/amp-social-share/1.0/social-share.css.js
  extensions/amp-social-share/1.0/social-share.js
  third_party/optimized-svg-icons/social-share-svgs.js
Labels: cla: yes

#29380 🏗 Move breaking changes instructions to all Renovate PRs
  .renovaterc.json
Labels: cla: yes

#29396 🐛 Geo location was not set to the blueconic-analytics-vendor
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/blueconic.json
Labels: cla: yes

#29197 ContextNode: value propagation
  src/context/index.js
  src/context/node.js
  src/context/prop.js
  src/context/prop.type.js
  src/context/scan.js
  src/context/values.js
  test/unit/context/test-node-values.js
Labels: cla: yes

#29408 Validator Roll up
  validator/engine/parse-css.js
  validator/engine/parse-css_test.js
  validator/engine/validator.js
  validator/testdata/feature_tests/regexps.out
  validator/testdata/transformed_feature_tests/amp-img.html
  validator/testdata/transformed_feature_tests/amp-img.out
  validator/testdata/transformed_feature_tests/nonce_attribute_error.html
  validator/testdata/transformed_feature_tests/nonce_attribute_error.out
  validator/testdata/transformed_feature_tests/server_side_rendering.html
  validator/testdata/transformed_feature_tests/server_side_rendering.out
  validator/testdata/transformed_feature_tests/transformed_but_not_identified_transformed.out
  validator/validator-css.protoascii
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#29387 Remove an already launched and cleaned up ampdoc-closest
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#29356 ✨ Add Yektanet ad platform support to amp-ad.
  3p/integration.js
  ads/_config.js
  ads/yektanet.js
  ads/yektanet.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#29415 🐛 [amp-story-360] Fix Safari rendering issue where the canvas has no height
  extensions/amp-story-360/0.1/amp-story-360.css
Labels: cla: yes

#29392 🐛A4A: add more functionality to secure frame
  extensions/amp-a4a/0.1/secure-frame.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
Labels: cla: yes

#29412 Sync from Google
  validator/htmlparser/css/parse-css.cc
  validator/htmlparser/css/parse-css_test.cc
  validator/htmlparser/json/types.h
Labels: WG: caching, cla: yes

#29250 ✨ [amp-social-share][bento] Handle children for social-share
  extensions/amp-social-share/1.0/amp-social-share.js
  extensions/amp-social-share/1.0/social-share-config.js
  extensions/amp-social-share/1.0/social-share.css.js
  extensions/amp-social-share/1.0/social-share.js
Labels: cla: yes

#29379 🐛 Mark user action in non-visible doc as expected error
  src/service/viewer-impl.js
Labels: cla: yes

#29426 🏗 Remove outdated `process-github-issues` gulp task
  build-system/tasks/process-github-issues.js
  gulpfile.js
Labels: cla: yes

#29417 🐛amp-experiment: Do not throw dev error when experiment is not turned on
  extensions/amp-experiment/1.0/amp-experiment.js
  extensions/amp-experiment/1.0/test/test-amp-experiment.js
Labels: cla: yes

#29114 🐛 Don't throw errors for unsupported metrics APIs in amp-analytics
  src/service/performance-impl.js
  src/utils/signals.js
  test/unit/test-performance.js
Labels: Component: amp-analytics, Type: Bug, cla: yes

#29416 Enable ampdoc-fie in canary.
  build-system/global-configs/canary-config.json
  src/ampdoc-fie.js
Labels: cla: yes

#29276 ✨ amp-story-player: Add "addStories" method to player
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29393 🧪Enable A4A integration test for no-signing exp
  extensions/amp-a4a/0.1/head-validation.js
  extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
  test/integration/test-amphtml-ads.js
Labels: cla: yes

#29430 ✨Creating an interactive-results-category component
  build-system/compile/bundles.config.js
  examples/amp-story/interactive_results.html
  examples/amp-story/interactives.html
  extensions/amp-story/1.0/amp-story-interactive-binary-poll.css
  extensions/amp-story/1.0/amp-story-interactive-poll.css
  extensions/amp-story/1.0/amp-story-interactive-quiz.css
  extensions/amp-story/1.0/amp-story-interactive-results.css
  extensions/amp-story/1.0/amp-story-interactive-results.js
  extensions/amp-story/1.0/amp-story-interactive.css
  extensions/amp-story/1.0/amp-story-interactive.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-amp-story-interactive-results.js
Labels: cla: yes

#29436 ✨ [bento] Add mutation observer to 'passthroughNonEmpty' children mode in base-element
  extensions/amp-social-share/1.0/amp-social-share.js
  src/preact/base-element.js
Labels: cla: yes

#29427 ✨ Add Hubvisor to RTC callout-vendors for amp-ad
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#29445 amp-list: email should support xssi-prefix
  extensions/amp-list/validator-amp-list.protoascii
Labels: UI: Component: amp-list, WG: caching, WG: runtime, cla: yes

#29463 Revert "🧪Enable A4A integration test for no-signing exp"
  extensions/amp-a4a/0.1/head-validation.js
  extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
  test/integration/test-amphtml-ads.js
Labels: cla: yes

#29450 added new parameters for ibeat analytics
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/ibeatanalytics.json
Labels: cla: yes

#29459 🚮 Removes unnecessary pseudo element on pagination buttons.
  extensions/amp-story/1.0/pagination-buttons.css
Labels: cla: yes

#29444 Move ads placement into layoutCallback of amp-auto-ads
  css/ampshared.css
  examples/auto-ads.amp.html
  extensions/amp-auto-ads/0.1/amp-auto-ads.js
  extensions/amp-auto-ads/0.1/anchor-ad-strategy.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#29481 [amp-story-player] Don't drag when only one story is present
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#29441 [amp-story-player] Suppress expected element errors in iframe focus
  src/focus-history.js
Labels: cla: yes

#29446 🐛 Fix case where ads iframe is measured before resize
  src/friendly-iframe-embed.js
  test/unit/test-friendly-iframe-embed.js
Labels: cla: yes

#29483 Revert "Ramp "intersect-resources" to 100% (second try)"
  build-system/global-configs/prod-config.json
Labels: cla: yes

#29480 amp-form: allow xssi-prefix in email
  validator/validator-main.protoascii
Labels: Validator: Approved, WG: caching, cla: yes
