Repository ampproject/amphtml, pull requests merged in 2020-05, with the labels that each got.

#28156 Add sanitize_vars_for_diff option to diff
  build-system/compile/bundles.config.js
  build-system/compile/compile.js
  build-system/compile/sanitize.js
  build-system/tasks/dist.js
Labels: cla: yes

#28092 ✨TCF integration: pass gdprApplies to amp-ad-network-*
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  extensions/amp-consent/0.1/consent-policy-manager.js
Labels: cla: yes

#26902 ✨ Require visibility trigger selector's to have data-vars-*
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-analytics/0.1/test/test-analytics-root.js
  extensions/amp-analytics/0.1/test/test-events.js
  test/manual/amp-analytics/amp-analytics-multi-selector.html
Labels: cla: yes

#28157 🏗✅ Add persistent browserify caching
  .gitignore
  .travis.yml
  build-system/tasks/clean.js
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test/runtime-test-base.js
  package.json
  yarn.lock
Labels: cla: yes

#28118 🏗 performance-urls task
  build-system/pr-check/checks.js
  build-system/tasks/performance-urls.js
  gulpfile.js
Labels: cla: yes

#28167 🏗 Tag release on-duty team in issue templates
  .github/ISSUE_TEMPLATE/cherry_pick_template.md
  .github/ISSUE_TEMPLATE/error-report.md
  .github/ISSUE_TEMPLATE/release-tracking-issue.md
Labels: cla: yes

#28170 🏗 Ignore `.karma-cache` during lint / prettier checks
  build-system/test-configs/config.js
Labels: WG: infra, cla: yes

#24047 🏗🚮 Remove `AmpPass.java`
  3p/ampcontext.js
  build-system/babel-config/pre-closure-config.js
  build-system/compile/closure-compile.js
  build-system/compile/compile.js
  build-system/runner/src/org/ampproject/AmpCodingConvention.java
  build-system/runner/src/org/ampproject/AmpCommandLineRunner.java
  build-system/runner/src/org/ampproject/AmpPass.java
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-video/0.1/amp-video.js
  src/log.js
  src/preact/slot.js
  src/service/ampdoc-impl.js
Labels: WG: infra, cla: yes

#28164 🏗 Skip `gulp unit --local_changes` on Travis if too many tests were affected
  build-system/tasks/runtime-test/helpers-unit.js
Labels: WG: infra, cla: yes

#28128 ✅🏗 Ensure we always call Chai method assertions
  .eslintrc
  build-system/eslint-rules/always-call-chai-methods.js
  build-system/eslint-rules/prefer-spread-props.js
  extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-form/0.1/test/test-form-submit-service.js
  extensions/amp-fx-flying-carpet/0.1/test/test-amp-fx-flying-carpet.js
  extensions/amp-skimlinks/0.1/test/test-tracking.js
  extensions/amp-story/1.0/test/integration/test-amp-story-affiliate-link.js
  extensions/amp-story/1.0/test/test-animation.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
  extensions/amp-user-notification/0.1/test/test-amp-user-notification.js
  test/integration/test-video-manager.js
  test/unit/test-ampdoc.js
  test/unit/test-cid.js
  test/unit/test-document-submit.js
  test/unit/test-dom.js
  test/unit/test-json.js
  test/unit/test-object.js
  test/unit/test-polyfill-object-values.js
  test/unit/test-service.js
  test/unit/test-url.js
  test/unit/test-video-iframe-integration.js
Labels: cla: yes

#28166 📖 Update spec/amp-errors.md with new reporting URL
  spec/amp-errors.md
  src/error.js
Labels: cla: yes

#27990 ♻️ Refactor localization service
  build-system/test-configs/dep-check-config.js
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/story-ad-localization.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/test/test-story-ad-localization.js
  extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js
  extensions/amp-story-education/0.1/amp-story-education.js
  extensions/amp-story-education/0.1/test/test-amp-story-education.js
  extensions/amp-story/0.1/amp-story-bookend.js
  extensions/amp-story/0.1/amp-story-info-dialog.js
  extensions/amp-story/0.1/amp-story-share-menu.js
  extensions/amp-story/0.1/amp-story-share.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/simple-template.js
  extensions/amp-story/0.1/test/test-amp-story-consent.js
  extensions/amp-story/0.1/test/test-amp-story-info-dialog.js
  extensions/amp-story/0.1/test/test-amp-story-share-menu.js
  extensions/amp-story/0.1/test/test-amp-story.js
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-info-dialog.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-reaction-quiz.js
  extensions/amp-story/1.0/amp-story-share.js
  extensions/amp-story/1.0/amp-story-viewport-warning-layer.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/simple-template.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
  extensions/amp-story/1.0/test/test-amp-story-consent.js
  extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
  extensions/amp-story/1.0/test/test-amp-story-grid-layer.js
  extensions/amp-story/1.0/test/test-amp-story-hint.js
  extensions/amp-story/1.0/test/test-amp-story-info-dialog.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
  extensions/amp-story/1.0/test/test-amp-story-reaction-quiz.js
  extensions/amp-story/1.0/test/test-amp-story-share-menu.js
  extensions/amp-story/1.0/test/test-amp-story-system-layer.js
  extensions/amp-story/1.0/test/test-amp-story.js
  extensions/amp-story/1.0/test/test-full-bleed-animations.js
  extensions/amp-story/1.0/test/test-live-story-manager.js
  src/service/localization.js
  src/services.js
  test/unit/test-amp-inabox.js
  test/unit/test-localization.js
Labels: cla: yes

#28124 ♻️Move Two SwG AMP examples and update CSS on the example
  examples/amp-subscriptions-google/amp-subscriptions-contribution.amp.html
  examples/amp-subscriptions-google/amp-subscriptions.amp.html
Labels: cla: yes

#28174 Expand analytics variables in remote config url
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/test/test-config-new.js
Labels: cla: yes

#28181 Pre-throttle error reports from Stable client
  src/error.js
Labels: cla: yes

#28188 Set aside 10% of canary traffic for fie-init-chunking experiment
  build-system/global-configs/canary-config.json
Labels: cla: yes

#28115 🖍 Cleanup several unresolved amp-layout CSS states
  css/ampshared.css
Labels: cla: yes

#28148 🏗 Add gulp performance to Travis
  .travis.yml
  build-system/pr-check/performance-tests.js
  build-system/tasks/performance/cache-documents.js
  build-system/tasks/performance/config.json
  build-system/tasks/performance/index.js
  build-system/tasks/performance/measure-documents.js
  build-system/tasks/performance/print-report.js
  build-system/tasks/performance/run-tests.js
  build-system/tasks/presubmit-checks.js
Labels: cla: yes

#27499 🚀 Move FixedLayer to amp-viewer-integration extension
  .eslintrc
  build-system/babel-config/helpers.js
  build-system/babel-config/pre-closure-config.js
  build-system/babel-config/test-config.js
  build-system/babel-config/unminified-config.js
  build-system/global-configs/README.md
  build-system/global-configs/experiments-config.json
  build-system/global-configs/experiments-const.json
  build-system/pr-check/experiment-tests.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-viewer-integration/0.1/amp-viewer-integration.js
  src/inabox/inabox-viewport.js
  src/service/viewport/viewport-impl.js
  src/service/viewport/viewport-interface.js
  test/unit/test-viewport.js
Labels: cla: yes

#28197 Trim bounce values
  extensions/amp-story/1.0/amp-story-reaction-quiz.css
Labels: cla: yes

#28204 🏗 Add missing `await` to `stopServer()` invocations
  build-system/tasks/e2e/index.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/visual-diff/index.js
Labels: WG: infra, cla: yes

#28210 Fix Node API on Node >12
  validator/build.py
  validator/nodejs/cli.js
  validator/nodejs/index.js
  validator/nodejs/index_test.js
  validator/nodejs/package.json
Labels: cla: yes

#28191 Fix userAssert's type annotation
  build-system/compile/compile.js
  extensions/amp-analytics/0.1/events.js
  src/log.js
Labels: cla: yes

#28186 added blurb explaining web stories and AMP stories
  extensions/amp-story/amp-story.md
Labels: cla: yes

#28214 Validator rollup
  validator/testdata/amp4email_feature_tests/css_declarations.html
  validator/testdata/amp4email_feature_tests/css_declarations.out
  validator/testdata/feature_tests/css_declarations.html
  validator/testdata/feature_tests/css_declarations.out
  validator/testdata/feature_tests/regexps.html
  validator/testdata/feature_tests/regexps.out
  validator/validator-css.protoascii
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#28218 Add manufactured comments token metadata for parser.
  validator/htmlparser/parser.cc
  validator/htmlparser/token.h
  validator/htmlparser/tokenizer.cc
  validator/htmlparser/tokenizer.h
Labels: WG: caching, cla: yes

#28185 🐛 Add error messages to thrown bare Error()s in `amp-script`
  extensions/amp-script/0.1/amp-script.js
Labels: cla: yes

#28207 amp-script: catch user errors in worker scripts
  extensions/amp-script/0.1/amp-script.js
Labels: WG: runtime, cla: yes

#28216 amp-script: add wg-runtime to OWNERS
  extensions/amp-script/OWNERS
Labels: Component: amp-script, WG: performance, WG: runtime, cla: yes

#28190 Add implicit layout comments
  css/ampshared.css
Labels: cla: yes

#27100 spec: Add AMP framework hosting guide
  spec/amp-framework-hosting.md
Labels: cla: yes

#28215 🏗 Reduce coverage threshold for `codecov` check
  .codecov.yml
Labels: WG: infra, cla: yes

#28228 ⏪ Remove experiment for FixedLayer due to failing sidebar test
  build-system/global-configs/experiments-config.json
Labels: cla: yes

#28226 📖 Exclude `amp-state:` documentation for email
  extensions/amp-list/amp-list.md
Labels: cla: yes

#28213 Add subscriptions-message-number to SwG smartbox button
  examples/amp-subscriptions-google/amp-subscriptions-smartbox.amp.html
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Labels: cla: yes

#28240 🏗 Configure Closure Compile to use ECMASCRIPT_2020
  build-system/compile/compile.js
  build-system/compile/single-pass.js
Labels: cla: yes

#27913 amp-rdu round 1 documentation update for amp-3d-gltf
  extensions/amp-3d-gltf/amp-3d-gltf.md
Labels: WG: ui-and-a11y, cla: yes

#28203 🚀 Allow prerendering of more elements
  extensions/amp-accordion/0.1/amp-accordion.js
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-inline-gallery/0.1/amp-inline-gallery-pagination.js
  extensions/amp-inline-gallery/0.1/amp-inline-gallery-thumbnails.js
  extensions/amp-inline-gallery/0.1/amp-inline-gallery.js
  extensions/amp-mega-menu/0.1/amp-mega-menu.js
  extensions/amp-nested-menu/0.1/amp-nested-menu.js
  extensions/amp-selector/0.1/amp-selector.js
  extensions/amp-sidebar/0.2/amp-sidebar.js
  extensions/amp-stream-gallery/0.1/amp-stream-gallery.js
Labels: cla: yes

#28242 🚮 Remove skipped old tests
  extensions/amp-analytics/0.1/test/test-config.js
  extensions/amp-analytics/0.1/test/test-vendors.js
Labels: cla: yes

#28241 Temporarily remove ads from performance test pages
  test/manual/amp-analytics/performanceTestPages/visible-multiple.html
Labels: cla: yes

#28246 ♻️rename test file
  extensions/amp-analytics/0.1/test/test-vendors.js
Labels: cla: yes

#28202 fixed bracket
  extensions/amp-access/amp-access.md
Labels: cla: yes

#28146 ✨ amp-animation: add x(), y(), rescale by scope element's transform
  examples/amp-story/amp-story-animation.html
  extensions/amp-animation/0.1/parsers/css-expr-ast.js
  extensions/amp-animation/0.1/parsers/css-expr-impl.jison
  extensions/amp-animation/0.1/test/test-css-expr-parser.js
  extensions/amp-animation/0.1/test/test-css-expr-resolve-calc.js
  extensions/amp-animation/0.1/test/test-css-expr-resolve.js
  extensions/amp-animation/0.1/test/test-web-animations.js
  extensions/amp-animation/0.1/web-animation-types.js
  extensions/amp-animation/0.1/web-animations.js
  extensions/amp-animation/amp-animation.md
  extensions/amp-story/1.0/animation.js
  extensions/amp-story/1.0/test/test-animation.js
Labels: cla: yes

#28249 Ramp up no center css experiment to 5% prod
  build-system/global-configs/prod-config.json
Labels: cla: yes

#28265 Delete validator/AUTHORS.
  validator/AUTHORS
Labels: WG: caching, cla: yes

#28250 Add support for module/nomodule script pairs
  src/multidoc-manager.js
  src/service/extensions-impl.js
  test/unit/test-extensions.js
  test/unit/test-runtime.js
Labels: cla: yes

#28263 📖 Fixes a typo
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#28277 e2e tests: support building specific extensions instead of everything.
  build-system/common/utils.js
  build-system/tasks/e2e/index.js
Labels: WG: infra, cla: yes

#27892 Launch inabox-viewport-friendly.
  ads/inabox/inabox-host.md
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  build-system/server/routes/a4a-envelopes.js
  src/inabox/inabox-iframe-messaging-client.js
  src/inabox/inabox-viewport.js
  test/integration/test-amphtml-ads.js
  test/unit/inabox/test-inabox-viewport.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#28276 Make timeout configurable for `findElement` in e2e tests
  build-system/tasks/e2e/functional-test-controller.js
  build-system/tasks/e2e/puppeteer-controller.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
Labels: cla: yes

#28256 Check for CSS variable support
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#28285 amp-social-share should not layout without a share endpoint
  extensions/amp-social-share/0.1/amp-social-share.js
Labels: cla: yes

#28261 ♻️Change ANALYTICS_CONFIG to DEFAULT_CONFIG to better reflect its usage
  extensions/amp-ad-exit/0.1/amp-ad-exit.js
  extensions/amp-analytics/0.1/config.js
  extensions/amp-analytics/0.1/default-config.js
  extensions/amp-analytics/0.1/transport.js
Labels: cla: yes

#28291 Validator rollup 465@1045
  validator/nodejs/index.js
Labels: cla: yes

#28268 🐛 Register `LINKER_CREATED` on ampdoc instead of attribute
  extensions/amp-analytics/0.1/linker-manager.js
  extensions/amp-iframe/0.1/amp-iframe.js
  src/enums.js
  src/service/ampdoc-impl.js
Labels: cla: yes

#28297 Fix race condition that fails to hide video loading indicator
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#28306 Revert "🚮 Remove idleRenderOutsideViewport"
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  src/base-element.js
  src/custom-element.js
  src/service/resource.js
  src/service/resources-impl.js
  test/unit/test-resource.js
  test/unit/test-resources.js
Labels: cla: yes

#28272 ✨amp-consent: Add Usercentrics CMP
  examples/amp-consent/cmp-vendors.amp.html
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/amp-consent.md
  extensions/amp-consent/cmps/usercentrics.md
Labels: cla: yes

#27008 ✨ Galaxie Media RTC adapter added
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-a4a/rtc-documentation.md
Labels: cla: yes

#28084 ♻️Test page folder refactor
  build-system/tasks/performance/config.json
  test/manual/amp-analytics/performance-test-pages/visible-basic.html
  test/manual/amp-analytics/performance-test-pages/visible-multiple.html
Labels: cla: yes

#28290 amp-consent iframe ui 100% height
  extensions/amp-consent/0.1/amp-consent.css
Labels: cla: yes

#28257 ♻️ Require trigger="visibility" to run an <amp-story-animation> effect
  examples/amp-story/amp-story-animation.html
  extensions/amp-story/1.0/animation.js
  extensions/amp-story/1.0/test/test-animation.js
Labels: cla: yes

#28102 ✨Add analytics vendor BlueConic
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/blueconic.json
Labels: cla: yes

#28296 updated amp-action-macro and flagged as experimental
  extensions/amp-action-macro/amp-action-macro.md
Labels: cla: yes

#28316 🐛Fix `check-types` failure due to new closure version
  3p/twitter.js
  build-system/tasks/presubmit-checks.js
Labels: cla: yes

#28320 ♻️Refactor amp-subscriptions-iframe example
  examples/amp-subscriptions-google/amp-subscriptions-iframe.amp.html
  examples/amp-subscriptions-google/amp-subscriptions-iframe.provider.html
Labels: cla: yes

#28224 Register localization from amp-story
  build-system/test-configs/dep-check-config.js
  extensions/amp-story-auto-ads/0.1/story-ad-localization.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
  extensions/amp-story-education/0.1/amp-story-education.js
  extensions/amp-story-education/0.1/test/test-amp-story-education.js
  extensions/amp-story/0.1/amp-story-info-dialog.js
  extensions/amp-story/0.1/amp-story-localization-service.js
  extensions/amp-story/0.1/amp-story-share.js
  extensions/amp-story/0.1/amp-story.js
  extensions/amp-story/0.1/simple-template.js
  extensions/amp-story/0.1/test/test-amp-story-info-dialog.js
  extensions/amp-story/0.1/test/test-amp-story.js
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-info-dialog.js
  extensions/amp-story/1.0/amp-story-localization-service.js
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story-reaction-quiz.js
  extensions/amp-story/1.0/amp-story-share.js
  extensions/amp-story/1.0/amp-story-viewport-warning-layer.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/bookend/amp-story-bookend.js
  extensions/amp-story/1.0/simple-template.js
  extensions/amp-story/1.0/test/test-amp-story-bookend.js
  extensions/amp-story/1.0/test/test-amp-story-consent.js
  extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
  extensions/amp-story/1.0/test/test-amp-story-hint.js
  extensions/amp-story/1.0/test/test-amp-story-info-dialog.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
  extensions/amp-story/1.0/test/test-amp-story-reaction-quiz.js
  extensions/amp-story/1.0/test/test-amp-story-system-layer.js
  extensions/amp-story/1.0/test/test-amp-story.js
  extensions/amp-story/1.0/test/test-full-bleed-animations.js
  extensions/amp-story/1.0/test/test-live-story-manager.js
  src/service/localization.js
  src/services.js
  test/unit/test-localization.js
Labels: cla: yes

#28319 🐛 Fix a bug with the Random Experiment setup
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#28182 🌐 Allow language override from viewer context
  src/service/localization.js
  test/unit/test-localization.js
Labels: cla: yes

#28317 🏗🐛 Fix build target logic by adding an explicit `RUNTIME` target
  build-system/pr-check/build-targets.js
Labels: WG: infra, cla: yes

#28305 🚀 e2e tests: support fast (unminified) mode.
  build-system/common/utils.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/experiment-tests.js
  build-system/tasks/e2e/index.js
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#28323 Turn on analytics-chunks in prod
  build-system/global-configs/prod-config.json
Labels: cla: yes

#28347 🐛 [TAG-6201] use p in the amp request to avoid errors with response sizes
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/comscore.json
Labels: cla: yes

#28346 🐛 Use binaryType instead of runtime for pre-throttling
  src/error.js
Labels: cla: yes

#28335 Slot: `ref` should not be an element
  src/preact/slot.js
Labels: cla: yes

#28209 ♻️Reaction API change
  examples/amp-story/reactions.html
  extensions/amp-story/1.0/_locales/default.js
  extensions/amp-story/1.0/amp-story-reaction-quiz.css
  extensions/amp-story/1.0/amp-story-reaction-quiz.js
  extensions/amp-story/1.0/amp-story-reaction.js
  extensions/amp-story/1.0/test/test-amp-story-reaction-quiz.js
  extensions/amp-story/1.0/test/test-amp-story-reaction.js
  src/url.js
  test/unit/test-url.js
Labels: cla: yes

#28352 Update my notifications
  build-system/pr-check/OWNERS
  build-system/tasks/runtime-test/OWNERS
Labels: cla: yes

#28326 🏗Allow `gulp` tasks to programmatically build the runtime
  build-system/babel-config/pre-closure-config.js
  build-system/common/utils.js
  build-system/compile/compile.js
  build-system/compile/helpers.js
  build-system/compile/single-pass.js
  build-system/pr-check/visual-diff-tests.js
  build-system/tasks/build.js
  build-system/tasks/css.js
  build-system/tasks/dist.js
  build-system/tasks/e2e/index.js
  build-system/tasks/firebase.js
  build-system/tasks/helpers.js
  build-system/tasks/integration.js
  build-system/tasks/performance/compile-scripts.js
  build-system/tasks/vendor-configs.js
  build-system/tasks/visual-diff/index.js
  contributing/TESTING.md
Labels: WG: infra, cla: yes

#28358 Oblivki config
  ads/_config.js
Labels: cla: yes

#28357 Add jeffkaufman to Adsense/Doubleclick OWNERS
  extensions/amp-ad-network-adsense-impl/OWNERS
  extensions/amp-ad-network-doubleclick-impl/OWNERS
Labels: cla: yes

#28321 📖 Doc all supported analytics vendors
  extensions/amp-analytics/analytics-vendors-list.md
  extensions/amp-analytics/integrating-analytics.md
Labels: cla: yes

#28364 Launch INTERSECTION_OBSERVER_POLYFILL experiment
  build-system/global-configs/experiments-config.json
  build-system/global-configs/experiments-const.json
Labels: cla: yes

#28356 [amp-story-player] Fix import error
  build-system/compile/sources.js
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#28367 Define INTERSECTION_OBSERVER_POLYFILL_INABOX experiment
  build-system/global-configs/experiments-config.json
  build-system/global-configs/experiments-const.json
Labels: cla: yes

#28287 📖 amp-subscriptions: Updates quotation marks and formatting of a code example
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#28370 ✅ Fix failing test
  test/unit/test-runtime.js
Labels: cla: yes

#28366 Fix check for unknown deps regex
  build-system/compile/check-for-unknown-deps.js
Labels: cla: yes

#28337 Upgrade Bento component versions by full integer
  build-system/compile/bundles.config.js
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/dep-check-config.js
  examples/amp-date-display.amp.html
  examples/amp-timeago.amp.html
  extensions/amp-date-display/1.0/amp-date-display.js
  extensions/amp-date-display/1.0/async-render.js
  extensions/amp-date-display/1.0/date-display.js
  extensions/amp-date-display/1.0/render-dom-tree.js
  extensions/amp-date-display/1.0/storybook/Basic.js
  extensions/amp-date-display/1.0/test/test-amp-date-display.js
  extensions/amp-date-display/1.0/test/test-date-display.js
  extensions/amp-timeago/1.0/amp-timeago.js
  extensions/amp-timeago/1.0/storybook/Basic.js
  extensions/amp-timeago/1.0/test/test-amp-timeago.js
  extensions/amp-timeago/1.0/timeago.js
Labels: cla: yes

#28381 🏗Make Sauce Labs runs non-blocking on Travis
  .travis.yml
Labels: Related to: Flaky Tests, WG: infra, cla: yes

#28369 Add missing analytics vendors to the doc
  extensions/amp-analytics/analytics-vendors-list.md
Labels: cla: yes

#28375 Ibeat analytics payload update
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/ibeatanalytics.json
Labels: cla: yes

#28292 [amp-carousel:0.2] Do not autoplay when document is not visible
  extensions/amp-base-carousel/0.1/auto-advance.js
  extensions/amp-base-carousel/0.1/test/test-carousel.js
Labels: cla: yes

#28365 🏗 Make `AMP_CONFIG` target names easily reusable across `build-system/`
  build-system/tasks/helpers.js
Labels: WG: infra, cla: yes

#28376 🐛 Bug fix: Limit the Full-Width Responsive upgrade in Auto Ads to mobile users only.
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-auto-ads/0.1/test/test-placement.js
Labels: cla: yes

#28388 🚮 Remove unnecessary moengage analytics files
  extensions/amp-analytics/0.1/vendors/moengage.js
Labels: cla: yes

#28392 🏗 Lint globals on globalThis
  build-system/eslint-rules/window-property-name.js
Labels: cla: yes

#28362 ✨Switch config of amp-story to attributes for reaction and quiz components
  examples/amp-story/reactions.html
  examples/visual-tests/amp-story/amp-story-reaction-quiz-sizing-positioning.html
  extensions/amp-story/1.0/amp-story-reaction-quiz.css
  extensions/amp-story/1.0/amp-story-reaction-quiz.js
  extensions/amp-story/1.0/amp-story-reaction.js
  extensions/amp-story/1.0/test/test-amp-story-reaction-quiz.js
  extensions/amp-story/1.0/test/test-amp-story-reaction.js
Labels: cla: yes

#28407 🐛 Only wait for audio to build when using layout="nodisplay"
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#28393 🏗 Group minor and patch upgrades in once-a-day PRs
  .renovaterc.json
Labels: cla: yes

#28405 Prevent TalkBack from selecting hidden text.
  extensions/amp-story/1.0/amp-story-system-layer.css
Labels: cla: yes

#27725 ✨✅ Create new JW Player AMP Extension
  build-system/test-configs/dep-check-config.js
  examples/jwplayer.amp.html
  extensions/amp-jwplayer/0.1/amp-jwplayer.js
  extensions/amp-jwplayer/0.1/test/test-amp-jwplayer.js
  extensions/amp-jwplayer/amp-jwplayer.md
  extensions/amp-jwplayer/validator-amp-jwplayer.protoascii
Labels: cla: yes

#28396 Group dependency updates by category and assign working groups
  .renovaterc.json
Labels: cla: yes

#28286 🏗 Fix default extension generator test
  build-system/tasks/extension-generator/index.js
Labels: cla: yes

#28413 Add hint about amp.dev's boilerplate generator to boilerplate spec
  spec/amp-boilerplate.md
Labels: cla: yes

#28419 🏗 Improve Sauce Labs logging
  build-system/tasks/runtime-test/helpers.js
Labels: WG: infra, cla: yes

#28382 amp-story-quiz css had extra spaces on the indentation
  extensions/amp-story/1.0/amp-story-reaction-quiz.css
Labels: cla: yes

#28420 🏗 Add auto-merging group for ampproject dependencies
  .renovaterc.json
Labels: cla: yes

#28122 ✨ Add FID, LCP, CLS to amp-analytics
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-analytics/0.1/default-config.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
  extensions/amp-story/1.0/media-performance-metrics-service.js
  extensions/amp-viewer-integration/TICKEVENTS.md
  spec/amp-var-substitutions.md
  src/amp.js
  src/enums.js
  src/inabox/amp-inabox.js
  src/layout-delay-meter.js
  src/service/jank-meter.js
  src/service/performance-impl.js
  src/style-installer.js
  test/unit/test-performance.js
Labels: cla: yes

#28423 🐛 try/catch when pausing animations
  extensions/amp-story/1.0/animation.js
Labels: cla: yes

#28430 ✨ SwG Release 0.1.22.105
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#28137 ✨ New version of preact social-share component
  build-system/compile/bundles.config.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-social-share/0.2/social-share.js
  extensions/amp-social-share/1.0/amp-social-share-config.js
  extensions/amp-social-share/1.0/amp-social-share.js
  extensions/amp-social-share/1.0/social-share.css.js
  extensions/amp-social-share/1.0/social-share.js
  extensions/amp-social-share/1.0/storybook/Basic.amp.js
  extensions/amp-social-share/1.0/storybook/Basic.js
Labels: cla: yes

#28417 Added muted attribute to amp-story
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#28400 Expand consent string size limit to 1024
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/integrating-consent.md
Labels: cla: yes

#28440 Unblock Story navigation after prerendering the education screens.
  extensions/amp-story-education/0.1/amp-story-education.js
Labels: cla: yes

#28444 Add missing parenthesis crashing the production build.
  extensions/amp-story/1.0/animation.js
Labels: cla: yes

#28138 Resources: wait until amp init before sending documentHeight
  build-system/tasks/e2e/describes-e2e.js
  examples/viewer.html
  src/service/resources-impl.js
  test/e2e/test-document-height.js
  test/fixtures/e2e/amp-carousel/0.1/document-height.html
  test/unit/test-resources.js
Labels: Type: Bug, WG: runtime, cla: yes

#28434 🚀 Turn on FixedLayer experiment
  .eslintrc
  build-system/babel-config/helpers.js
  build-system/global-configs/experiments-config.json
  build-system/global-configs/experiments-const.json
Labels: WG: performance, cla: yes

#28187 amp-consent metadata values
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-info.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-info.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  src/consent.js
Labels: cla: yes

#28426 [amp-story-player] Allow top-navigation for remote attachments
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#28450 🐛 Turn off FixedLayer experiment config
  build-system/global-configs/experiments-config.json
Labels: Type: Bug, WG: performance, cla: yes

#28448 🐛 Analytics config: Do not check inline transport setting without vendor specified
  extensions/amp-analytics/0.1/config.js
  test/manual/analytics-batching.amp.html
Labels: cla: yes

#28436 Introduce 'analytics-chunks-inabox' experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/analytics-group.js
  extensions/amp-analytics/0.1/cookie-writer.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#28371 amp-animation documentation update
  extensions/amp-animation/amp-animation.md
Labels: cla: yes

#28449 🐛 Bug fix: Fix the logic for saving the enableAutoAdSize flag in local storage.
  extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
  extensions/amp-ad-network-adsense-impl/OWNERS
Labels: cla: yes

#27365 [amp-selector] Initial Bento component
  build-system/compile/bundles.config.js
  examples/selector.amp.html
  extensions/amp-selector/1.0/amp-selector.css
  extensions/amp-selector/1.0/amp-selector.js
  extensions/amp-selector/1.0/selector.css.js
  extensions/amp-selector/1.0/selector.js
  extensions/amp-selector/1.0/storybook/Basic.amp.js
  extensions/amp-selector/1.0/storybook/Basic.js
  extensions/amp-selector/1.0/test-e2e/test-amp-selector-tabs.js
  src/preact/base-element.js
  src/preact/index.js
Labels: cla: yes

#28474 🏗 Fix renovate config file
  .renovaterc.json
Labels: cla: yes

#28455 🐛♻️ Remove unused 'opt_collectVars' from expandUrlSync
  extensions/amp-ad-exit/0.1/amp-ad-exit.js
  extensions/amp-link-rewriter/0.1/link-rewriter.js
  src/service/navigation.js
  src/service/url-replacements-impl.js
  test/unit/test-url-replacements.js
Labels: cla: yes

#28481 🏗 Group patch+pin and separate patch from minor
  .renovaterc.json
Labels: cla: yes

#28484 Sync from Google
  validator/htmlparser/data/CaseFolding.txt
Labels: cla: yes

#28485 📓Document --inspect for gulp
  contributing/TESTING.md
Labels: cla: yes

#28325 🧪Add performance regression test for inabox
  build-system/server/app.js
  build-system/tasks/performance/README.md
  build-system/tasks/performance/ads-handler.js
  build-system/tasks/performance/analytics-handler.js
  build-system/tasks/performance/config.json
  build-system/tasks/performance/helpers.js
  build-system/tasks/performance/index.js
  build-system/tasks/performance/load-config.js
  build-system/tasks/performance/measure-documents.js
  build-system/tasks/performance/print-report.js
  build-system/tasks/performance/rewrite-analytics-tags.js
  build-system/tasks/performance/rewrite-script-tags.js
  test/fixtures/performance/amp-ad/amphtml-ad.html
  test/fixtures/performance/amp-ad/hostile-inabox-env.html
Labels: cla: yes

#28486 Validator rollup
  validator/engine/validator.js
  validator/testdata/feature_tests/meta_viewport.html
  validator/testdata/feature_tests/meta_viewport.out
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#28483 🏗 Fix PR titles and remove reviewer teams
  .renovaterc.json
Labels: cla: yes

#28472 🐛Change toggleAttribute to set/removeAttribute
  build-system/test-configs/conformance-config.textproto
  extensions/amp-story/1.0/amp-story-affiliate-link.js
  extensions/amp-story/1.0/amp-story.js
Labels: Type: Bug, cla: yes

#28461 Update document for responsive design
  ads/rakutenunifiedads.md
Labels: cla: yes

#28232 ✨Adhese: consent integration
  ads/adhese.js
  ads/adhese.md
Labels: cla: yes

#28498 🐛 Skip Java validator tests
  .travis.yml
  build-system/pr-check/validator-tests.js
  build-system/tasks/pr-check.js
Labels: cla: yes

#28490 Add globalThis to eslintrc
  .eslintrc
Labels: cla: yes

#28462 [amp-story-player] s/whitelist/minlist
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#28238 [amp-story-player] Use window.origin rather than url origin
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#28495 🏗 Add package file path to renovate PR table
  .renovaterc.json
Labels: cla: yes

#28512 Reference new structured data doc
  extensions/amp-story/amp-story.md
Labels: cla: yes

#28313 🐛 Catch up java validator to Doc Css logic
  validator/java/BUILD
  validator/java/WORKSPACE
  validator/java/build.sh
  validator/java/exclude-pmd.properties
  validator/java/pom.xml
  validator/java/src/main/java/dev/amp/validator/AMPHtmlHandler.java
  validator/java/src/main/java/dev/amp/validator/CdataMatcher.java
  validator/java/src/main/java/dev/amp/validator/Context.java
  validator/java/src/main/java/dev/amp/validator/ExtensionsContext.java
  validator/java/src/main/java/dev/amp/validator/ParsedValidatorRules.java
  validator/java/src/main/java/dev/amp/validator/ReferencePointMatcher.java
  validator/java/src/main/java/dev/amp/validator/TagStack.java
  validator/java/src/main/java/dev/amp/validator/ValidateTagResult.java
  validator/java/src/main/java/dev/amp/validator/css/CssParsingConfig.java
  validator/java/src/main/java/dev/amp/validator/css/Declaration.java
  validator/java/src/main/java/dev/amp/validator/css/ParsedDocCssSpec.java
  validator/java/src/main/java/dev/amp/validator/css/QualifiedRule.java
  validator/java/src/main/java/dev/amp/validator/parser/AMPHtmlParser.java
  validator/java/src/main/java/dev/amp/validator/utils/AttributeSpecUtils.java
  validator/java/src/main/java/dev/amp/validator/utils/CssSpecUtils.java
  validator/java/src/main/java/dev/amp/validator/utils/ExtensionsUtils.java
  validator/java/src/main/java/dev/amp/validator/utils/TagSpecUtils.java
  validator/java/src/main/java/dev/amp/validator/visitor/ImportantPropertyVisitor.java
  validator/java/src/main/java/dev/amp/validator/visitor/InvalidDeclVisitor.java
  validator/java/src/main/java/dev/amp/validator/visitor/UrlFunctionVisitor.java
  validator/java/src/main/proto/validator.proto
  validator/java/src/test/java/dev/amp/validator/CdataMatcherTest.java
  validator/java/src/test/java/dev/amp/validator/ContextTest.java
  validator/java/src/test/java/dev/amp/validator/CssLengthTest.java
  validator/java/src/test/java/dev/amp/validator/ParsedValidatorRulesTest.java
  validator/java/src/test/java/dev/amp/validator/TagSpecDispatchTest.java
  validator/java/src/test/java/dev/amp/validator/TagStackTest.java
  validator/java/src/test/java/dev/amp/validator/utils/AttributeSpecUtilsTest.java
Labels: WG: caching, cla: yes

#28518 🏗 Update chromedriver to v83
  build-system/tasks/e2e/package.json
  build-system/tasks/e2e/yarn.lock
Labels: cla: yes

#28513 🏗 Tweak renovate grouping and re-disable PR creation
  .renovaterc.json
Labels: cla: yes

#28245 ✅ Validation for <amp-story-animation>
  extensions/amp-story/1.0/test/validator-amp-story-amp-experiment-error.out
  extensions/amp-story/1.0/test/validator-amp-story-amp-twitter-error.out
  extensions/amp-story/1.0/test/validator-amp-story-animation.html
  extensions/amp-story/1.0/test/validator-amp-story-animation.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: WG: caching, cla: yes

#28452 [amp-story-player] Implements external load callback
  src/amp-story-player/amp-story-player-impl.js
  src/amp-story-player/amp-story-player.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#28454 ✨support for amp-embed type=yahoofedads
  3p/integration.js
  ads/_config.js
  ads/yahoofedads.js
  ads/yahoofedads.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#28451 Run FIE init chunking experiment on prod
  build-system/global-configs/prod-config.json
Labels: cla: yes

#28536 Allow empty analytics config switch from error to warning
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
Labels: cla: yes
