Repository ampproject/amphtml, pull requests merged in 2020-11, with the labels that each got.

#28496 [amp-fit-text:1.0] Use ResizeObserver for content changes
  extensions/amp-fit-text/1.0/fit-text.css.js
  extensions/amp-fit-text/1.0/fit-text.js
  extensions/amp-fit-text/1.0/storybook/Basic.js
Labels: cla: yes

#30937 resources: relayoutAll should invalidate premeasurements
  src/service/resource.js
  src/service/resources-impl.js
  test/unit/test-resources.js
Labels: P1: High Priority, WG: amp4email

#28336 Turn on esm tests
  .travis.yml
  build-system/pr-check/esm-tests.js
  build-system/pr-check/utils.js
  build-system/server/app.js
  build-system/tasks/integration.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/report-test-status.js
Labels: cla: yes

#30594 📖 Interactive docs first final version
  extensions/amp-story-interactive/README.md
  extensions/amp-story-interactive/amp-story-interactive.md
Labels: cla: yes

#28576 ✅ [amp-selector:1.0] Turn on e2e tests
  extensions/amp-selector/0.1/test-e2e/test-amp-selector-tabs.js
  extensions/amp-selector/1.0/amp-selector.js
  extensions/amp-selector/1.0/selector.js
  extensions/amp-selector/1.0/test-e2e/test-amp-selector-tabs.js
  test/fixtures/e2e/amp-selector/0.1/amp-selector-tabs.html
  test/fixtures/e2e/amp-selector/1.0/amp-selector-tabs.html
Labels: cla: yes

#31014 docs: 📖 remove amp by example, since it deprecated/dead.
  contributing/building-an-amp-extension.md
Labels: Related to: Documentation

#30359 ✨ Preact VideoIframe
  extensions/amp-video/1.0/storybook/VideoIframe.js
  extensions/amp-video/1.0/test/test-video-iframe.js
  extensions/amp-video/1.0/video-iframe.js
  extensions/amp-video/1.0/video-iframe.type.js
Labels: cla: yes

#28349 ✨ amp-video: Add intrinsic to supported_layouts
  extensions/amp-video/validator-amp-video.protoascii
Labels: WG: caching, cla: yes

#31053 🐛 [Story Interactive] Two lines on quizzes sometimes make percentages wrap
  extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.css
Labels: WG: stories

#31037 lightbox-gallery: remove viewport check
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: WG: performance

#30959 ♻️ 🚮 resources + ce + owners: fully remove viewportCallback
  ads/google/imaVideo.js
  contributing/building-an-amp-extension.md
  extensions/amp-base-carousel/0.1/child-layout-manager.js
  extensions/amp-base-carousel/0.1/test/test-child-layout-manager.js
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/0.1/test/test-scrollable-carousel.js
  extensions/amp-carousel/0.1/test/test-slidescroll.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
  extensions/amp-story/1.0/amp-story-draggable-drawer.js
  src/base-element.js
  src/custom-element.js
  src/inabox/inabox-resources.js
  src/service/owners-impl.js
  src/service/owners-interface.js
  src/service/resource.js
  src/service/resources-impl.js
  src/video-interface.js
  test/unit/inabox/test-inabox-resources.js
  test/unit/test-amp-img.js
  test/unit/test-custom-element.js
  test/unit/test-mutator.js
  test/unit/test-resource.js
Labels: Type: Refactoring, WG: performance

#31028 ✅ [amp-story-360] improve duration validation
  extensions/amp-story-360/0.1/test/validator-amp-story-360.html
  extensions/amp-story-360/0.1/test/validator-amp-story-360.out
  extensions/amp-story-360/validator-amp-story-360.protoascii
Labels: WG: stories

#31021 ✨ [amp-autocomplete] Add support for `prefetch` attribute for prefetching remote data
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
  extensions/amp-autocomplete/amp-autocomplete.md
  extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
Labels: WG: caching

#29796 ✨ Support styling of amp-lightbox-gallery caption
  examples/lightbox-gallery.amp.html
  extensions/amp-lightbox-gallery/0.1/lightbox-caption.js
  extensions/amp-lightbox-gallery/0.1/test/integration/test-amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/amp-lightbox-gallery.md
Labels: cla: yes

#30600 🚮 clean up analytics-chunks experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-analytics/0.1/analytics-group.js
  extensions/amp-analytics/0.1/test/test-amp-analytics.js
  testing/fake-dom.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#31097 🏗 Remove circular dependency between `helpers.js` and `typescript.js`
  build-system/compile/typescript.js
  build-system/tasks/helpers.js
Labels: WG: infra

#31091 🏗 Decouple `--core_runtime_only` and `--extensions*` during builds
  build-system/tasks/build.js
  build-system/tasks/dist.js
  build-system/tasks/extension-helpers.js
  contributing/TESTING.md
Labels: WG: infra

#31135 ✅ [amp-story-360] Add play/pause tests
  extensions/amp-story-360/0.1/test/test-amp-story-360.js
Labels: Type: Testing, WG: stories

#30444 Bento port of amp-youtube
  build-system/compile/bundles.config.js
  build-system/compile/sources.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-youtube/1.0/amp-youtube.js
  extensions/amp-youtube/1.0/storybook/Basic.amp.js
  extensions/amp-youtube/1.0/storybook/Basic.js
  extensions/amp-youtube/1.0/test/test-amp-youtube.js
  extensions/amp-youtube/1.0/test/test-youtube.js
  extensions/amp-youtube/1.0/youtube.js
  extensions/amp-youtube/1.0/youtube.type.js
Labels: cla: yes

#29778 🐛 [yahoofedads]Pass heigth/width into downstream js.
  ads/yahoofedads.js
Labels: cla: yes

#31112 🏗 Fix RRule usage so it works with module build
  build-system/compile/sources.js
  build-system/tasks/update-packages.js
  extensions/amp-date-picker/0.1/dates-list.js
  extensions/amp-date-picker/0.1/test/test-dates-list.js
Labels: Component: amp-date-picker, WG: infra

#31056 Update amp-jwplayer validator
  extensions/amp-jwplayer/0.1/test/validator-amp-jwplayer.html
  extensions/amp-jwplayer/0.1/test/validator-amp-jwplayer.out
  extensions/amp-jwplayer/amp-jwplayer.md
  extensions/amp-jwplayer/validator-amp-jwplayer.protoascii
Labels: WG: caching

#29973 🐛 Video percentage played, single percentage fix
  extensions/amp-analytics/0.1/events.js
  extensions/amp-video/0.1/test-e2e/test-amp-video-analytics.js
  test/fixtures/e2e/amp-video/analytics-triggers.html
Labels: cla: yes

#31194 ✨ Created amp-story-dev-tools extensions
  build-system/compile/bundles.config.js
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.css
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.js
  extensions/amp-story-dev-tools/OWNERS
  extensions/amp-story-dev-tools/amp-story-dev-tools.md
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
Labels: WG: stories

#31241 🐛 Fix value_regex for decimal option-*-results-threshold attr values
  extensions/amp-story-interactive/validator-amp-story-interactive.protoascii
Labels: WG: caching

#31243 ♻️ replaced vlyby cdn
  ads/_config.js
  ads/vlyby.js
Labels: Component: amp-ad

#31256 Update validator-amp-story-interactive.protoascii
  extensions/amp-story-interactive/validator-amp-story-interactive.protoascii
Labels: WG: caching

#31265 ✨ [Story devtools] Created header and tabs for story-dev-tools
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab.js
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.css
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.js
  extensions/amp-story-dev-tools/0.1/utils.js
  extensions/amp-story-dev-tools/amp-story-dev-tools.md
Labels: WG: stories

#31299 📖 [amp-story-360] Finalize 360 docs
  extensions/amp-story-360/0.1/amp-story-360.md
Labels: P1: High Priority, Related to: Documentation, WG: stories

#31321 Sync for validator/cpp/engine
  validator/cpp/engine/validator-internal.cc
Labels: WG: caching

#31322 Sync for validator/cpp/htmlparser
  validator/cpp/htmlparser/json/types.cc
Labels: WG: caching

#31271 ✨ [amp-accordion][amp-access] Allow access-hide attribute in accordion section
  extensions/amp-accordion/0.1/test/validator-amp-accordion.html
  extensions/amp-accordion/0.1/test/validator-amp-accordion.out
  extensions/amp-accordion/validator-amp-accordion.protoascii
Labels: WG: caching

#30687 ✨ Add Pulse widget ads extension
  3p/integration.js
  ads/_config.js
  ads/pulse.js
  ads/pulse.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#31357 viewportObserver: Fix case of quick observe and unobserve that both occur before the io callback
  src/viewport-observer.js
  test/unit/test-viewport-observer.js
Labels: Type: Bug
