Repository ampproject/amphtml, pull requests merged in 2020-06, with the labels that each got.

#28503 gulp performance: add runtime pages
  build-system/tasks/performance/config.json
  examples/runtime/README.md
  examples/runtime/animals.json
  examples/runtime/article.html
  examples/runtime/images.html
  examples/runtime/list-always.html
Labels: Related to: Performance, WG: runtime, cla: yes

#28623 🐛 Add metadata user error restriction
  extensions/amp-consent/0.1/amp-consent.js
Labels: cla: yes

#27672 📖Update `amp-access` and `amp-subscriptions` docs
  extensions/amp-subscriptions/amp-subscriptions.md
  extensions/amp-subscriptions/images/reader-id-assoociation.png
Labels: cla: yes

#28626 ♻️ Extract signing flow into own method
  extensions/amp-a4a/0.1/amp-a4a.js
Labels: cla: yes

#28644 ♻️ amp-audio: Fixes a typing TODO and refactors a bit
  extensions/amp-audio/0.1/amp-audio.js
  extensions/amp-audio/0.1/test/test-amp-audio.js
Labels: cla: yes

#28150 [amp-carousel:0.1] Hide controls in hidden controls e2e test
  test/manual/amp-carousel/0.1/hidden-controls.amp.html
Labels: cla: yes

#28655 Don't use webp as a fallback example
  builtins/amp-img.md
Labels: cla: yes

#28412 ✨Implementation of binary poll
  build-system/compile/bundles.config.js
  examples/amp-story/reactions.html
  extensions/amp-story/1.0/amp-story-reaction-poll.css
  extensions/amp-story/1.0/amp-story-reaction-poll.js
  extensions/amp-story/1.0/amp-story-reaction-quiz.css
  extensions/amp-story/1.0/amp-story-reaction-quiz.js
  extensions/amp-story/1.0/amp-story-reaction.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story-reaction-poll.js
Labels: WG: stories, cla: yes

#28654 feat: Resize ampad when SSP ad arive #SSP-2731
  ads/ssp.js
  test/unit/ads/test-ssp.js
Labels: cla: yes

#27829 🐛 Allow whitespace to precede intrinsic sizer SVG element in data: URL
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#28653 added details on email actions vs others
  spec/amp-actions-and-events.md
  spec/amp-email-actions-and-events.md
Labels: cla: yes

#28597 ✨ AMP Analytics: Added configuration and test files for RudderStack
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/rudderstack.json
  extensions/amp-analytics/analytics-vendors-list.md
Labels: cla: yes

#28566 ✨ Add data-blockid to amp-embed type="24smi"
  ads/24smi.js
  ads/24smi.md
  examples/ads.amp.html
Labels: cla: yes

#28658 🏗 Always build vendor configs when running unit tests
  build-system/tasks/unit.js
Labels: cla: yes

#28643 🖍 Changed circle color
  extensions/amp-story/1.0/amp-story-reaction-quiz.css
Labels: cla: yes

#28028 Adding consentStringType to amp-consent metadata
  examples/amp-consent/diy-consent.html
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-info.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-info.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  src/consent-state.js
Labels: cla: yes

#28666 Launch IntersectionObserverPolyfill experiments
  build-system/global-configs/experiments-config.json
  build-system/global-configs/experiments-const.json
Labels: cla: yes

#28656 🐛Fix idle render issue while getLastDequeueTime() == 0
  ads/google/a4a/utils.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  src/service/resources-impl.js
Labels: cla: yes

#28677 Validator rollup 472@1048
  validator/engine/json-testutil.js
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#28274 🔥 amp-connatix-player: Update iframe domain and path for our existing amp-connatix-player.js
  extensions/amp-connatix-player/0.1/amp-connatix-player.js
  extensions/amp-connatix-player/0.1/test/test-amp-connatix-player.js
Labels: cla: yes

#28682 🐛 Fix unmuted audio bug in FF
  extensions/amp-story/1.0/media-pool.js
Labels: cla: yes

#28687 Publish C++ CSS parser
  validator/htmlparser/WORKSPACE
  validator/htmlparser/css/BUILD
  validator/htmlparser/css/amp4ads-parse-css.cc
  validator/htmlparser/css/amp4ads-parse-css.h
  validator/htmlparser/css/amp4ads-parse-css_test.cc
  validator/htmlparser/css/parse-css-urls.cc
  validator/htmlparser/css/parse-css-urls.h
  validator/htmlparser/css/parse-css-urls.proto
  validator/htmlparser/css/parse-css-urls_test.cc
  validator/htmlparser/css/parse-css.cc
  validator/htmlparser/css/parse-css.h
  validator/htmlparser/css/parse-css.proto
  validator/htmlparser/css/parse-css_test.cc
  validator/htmlparser/fileutil.cc
  validator/htmlparser/fileutil.h
  validator/htmlparser/json/types.h
Labels: cla: yes

#28689 gulp performance: introduce --headless and --devtools
  build-system/pr-check/performance-tests.js
  build-system/tasks/performance/README.md
  build-system/tasks/performance/config.json
  build-system/tasks/performance/index.js
  build-system/tasks/performance/load-config.js
  build-system/tasks/performance/measure-documents.js
Labels: cla: yes

#28696 Create BUILD rules for validator.proto
  validator/BUILD
Labels: cla: yes

#28697 Fix compile error.
  validator/htmlparser/fileutil.cc
Labels: cla: yes

#28690 🧪Introduce a4a-no-signing experiment diversion
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#28657 ✨ Update Teads ads CDN entry point and prefetch config
  ads/_config.js
  ads/teads.js
Labels: cla: yes

#28683 ♻️ amp-subscriptions: Renames interface imports
  build-system/test-configs/dep-check-config.js
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/local-subscription-platform-renderer.js
  extensions/amp-subscriptions/0.1/local-subscription-platform.js
  extensions/amp-subscriptions/0.1/service-adapter.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
Labels: cla: yes

#28695 🚀 Removing dev().info() CallExpressions from ESM Output
  build-system/babel-config/pre-closure-config.js
  build-system/babel-plugins/babel-plugin-transform-dev-methods/index.js
  build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/imported-no-usage/input.js
  build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/imported-no-usage/options.json
  build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/imported-no-usage/output.mjs
  build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/imported-usage/input.js
  build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/imported-usage/options.json
  build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/imported-usage/output.mjs
  build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/no-import/input.js
  build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/no-import/options.json
  build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/no-import/output.js
  build-system/babel-plugins/babel-plugin-transform-dev-methods/test/index.js
  build-system/tasks/presubmit-checks.js
Labels: cla: yes

#28699 turn off function decl transformer temporarily in pre closure
  build-system/babel-config/pre-closure-config.js
Labels: cla: yes

#28427 🐛async in generated extension test
  build-system/tasks/extension-generator/index.js
Labels: cla: yes

#28583 Cleanup blurry-placeholder experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  builtins/amp-img.js
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-video/0.1/test/test-amp-video.js
  test/unit/test-amp-img.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#28701 🏗 Use allowlist instead of whitelist
  build-system/tasks/presubmit-checks.js
Labels: cla: yes

#28476 ♿ Prevent TalkBack from reading content behind education layer.
  extensions/amp-story-education/0.1/amp-story-education.js
Labels: cla: yes

#28605 opencmp
  examples/amp-consent/cmp-vendors.amp.html
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/amp-consent.md
  extensions/amp-consent/cmps/opencmp.md
Labels: cla: yes

#28702 ♻️ Use denylist
  3p/integration.js
  ads/taboola.js
  build-system/global-configs/sw-config.json
  build-system/tasks/presubmit-checks.js
  extensions/amp-auto-ads/0.1/placement.js
  extensions/amp-auto-ads/0.1/test/test-placement.js
  extensions/amp-bind/0.1/bind-validator.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/form-proxy.js
  extensions/amp-form/0.1/test/test-form-proxy.js
  extensions/amp-skimlinks/0.1/constants.js
  extensions/amp-skimlinks/0.1/skim-options.js
  extensions/amp-skimlinks/0.1/test/test-skim-options.js
  src/custom-element.js
  src/purifier/purifier.js
  src/purifier/sanitation.js
  src/sanitizer.js
  test/unit/test-custom-element.js
  test/unit/test-ini-load.js
  test/unit/test-purifier.js
  test/unit/test-resource.js
  test/unit/test-sanitizer.js
Labels: cla: yes

#28688 runtime perf pages: amp-list should use state
  examples/runtime/animals.json
  examples/runtime/list-always.html
Labels: cla: yes

#28729 🐛 Allow dl, dt and dd on amp-mustache {{{tripleBrace}}} syntax
  src/purifier/sanitation.js
Labels: cla: yes

#28553 🚀 Defer/chunk buildCallback
  src/service/resources-impl.js
Labels: cla: yes

#27518 ✨Validator: base64 encoding for SSR'd intrinsic sizer
  validator/testdata/transformed_feature_tests/server_side_rendering.html
  validator/testdata/transformed_feature_tests/server_side_rendering.out
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#28703 SwG release 0.1.22.107
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#28715 🐛 Don't attempt to unhide the body for expected errors.
  src/error.js
Labels: cla: yes

#28738 gulp performance: force headless/devtools to bool
  build-system/tasks/performance/load-config.js
Labels: cla: yes

#28749 Validator rollup
  extensions/amp-access/validator-amp-access.protoascii
  extensions/amp-ad-custom/validator-amp-ad-custom.protoascii
  extensions/amp-ad/validator-amp-ad.protoascii
  extensions/amp-analytics/validator-amp-analytics.protoascii
  extensions/amp-animation/validator-amp-animation.protoascii
  extensions/amp-audio/validator-amp-audio.protoascii
  extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
  extensions/amp-bind/validator-amp-bind.protoascii
  extensions/amp-call-tracking/validator-amp-call-tracking.protoascii
  extensions/amp-consent/validator-amp-consent.protoascii
  extensions/amp-date-picker/validator-amp-date-picker.protoascii
  extensions/amp-experiment/validator-amp-experiment.protoascii
  extensions/amp-geo/validator-amp-geo.protoascii
  extensions/amp-google-document-embed/validator-amp-google-document-embed.protoascii
  extensions/amp-iframe/validator-amp-iframe.protoascii
  extensions/amp-ima-video/validator-amp-ima-video.protoascii
  extensions/amp-inline-gallery/validator-amp-inline-gallery.protoascii
  extensions/amp-inputmask/validator-amp-inputmask.protoascii
  extensions/amp-install-serviceworker/validator-amp-install-serviceworker.protoascii
  extensions/amp-link-rewriter/validator-amp-link-rewriter.protoascii
  extensions/amp-list/validator-amp-list.protoascii
  extensions/amp-mustache/validator-amp-mustache.protoascii
  extensions/amp-next-page/validator-amp-next-page.protoascii
  extensions/amp-payment-google-button/validator-amp-payment-google-button.protoascii
  extensions/amp-payment-google-inline-async/validator-amp-payment-google-inline-async.protoascii
  extensions/amp-payment-google-inline/validator-amp-payment-google-inline.protoascii
  extensions/amp-script/validator-amp-script.protoascii
  extensions/amp-social-share/validator-amp-social-share.protoascii
  extensions/amp-story-auto-ads/validator-amp-story-auto-ads.protoascii
  extensions/amp-story/validator-amp-story.protoascii
  extensions/amp-subscriptions/validator-amp-subscriptions.protoascii
  extensions/amp-video-iframe/validator-amp-video-iframe.protoascii
  extensions/amp-video/validator-amp-video.protoascii
  extensions/amp-viewer-assistance/validator-amp-viewer-assistance.protoascii
  validator/engine/parse-css.js
  validator/engine/parse-css_test.js
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/testdata/feature_tests/link_meta_values.html
  validator/testdata/feature_tests/link_meta_values.out
  validator/testdata/feature_tests/regexps.html
  validator/testdata/feature_tests/regexps.out
  validator/validator-css.protoascii
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
  validator/validator_gen_js.py
Labels: WG: caching, cla: yes

#28725 🐛Only start the page auto advancement when assets have loaded.
  examples/amp-story/helloworld.html
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
Labels: cla: yes

#28723 ♿ Assign correct aria-role to tooltips and give them focus.
  extensions/amp-story/1.0/amp-story-embedded-component.js
Labels: cla: yes

#28759 🐛 Delay amp-next-page init until first scroll
  extensions/amp-next-page/1.0/service.js
  extensions/amp-next-page/1.0/test/test-amp-next-page.js
Labels: cla: yes

#28681 Add image cache to performance task
  build-system/tasks/performance/copy-images.js
  build-system/tasks/performance/helpers.js
  build-system/tasks/performance/index.js
  build-system/tasks/performance/measure-documents.js
Labels: cla: yes

#28750 add an mjs or js suffix to output json file
  build-system/compile/log-messages.js
Labels: cla: yes

#28740 🐛 Fix amp-fit-text with content div that is smaller than the container.
  extensions/amp-fit-text/0.1/amp-fit-text.js
Labels: cla: yes

#28755 Explain a caveat on reCaptcha sitekey registration
  extensions/amp-recaptcha-input/amp-recaptcha-input.md
Labels: cla: yes

#28710 ✨ Update Pubmine amp-ad: add siteid to the page config
  ads/pubmine.js
  test/unit/ads/test-pubmine.js
Labels: cla: yes

#28770 Validator rollup
  validator/engine/parse-css.js
  validator/engine/parse-css_test.js
  validator/engine/validator.js
  validator/engine/validator_test.js
  validator/testdata/amp4email_feature_tests/css.html
  validator/testdata/amp4email_feature_tests/css.out
  validator/testdata/amp4email_feature_tests/css_strict.html
  validator/testdata/amp4email_feature_tests/css_strict.out
  validator/validator-css.protoascii
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: WG: caching, cla: yes

#28758 🐛 Fix any issues with SSR rendered intrinsic amp-img
  builtins/amp-img.js
  test/unit/test-amp-img.js
Labels: cla: yes

#28769 🦟 Pinterest data comes HTML encoded, not URL encoded.
  examples/pinterest.amp.html
  extensions/amp-pinterest/0.1/test/test-amp-pinterest.js
  extensions/amp-pinterest/0.1/util.js
Labels: cla: yes

#28773 ✨ Add support for writing and reading textContent on amp-fit-text.
  extensions/amp-fit-text/0.1/amp-fit-text.js
  extensions/amp-fit-text/0.1/test/test-amp-fit-text.js
Labels: cla: yes

#28733 🐛 Use widest possible src from srcset for shrunk auto-lightbox images
  extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
  extensions/amp-auto-lightbox/0.1/test-e2e/test-amp-auto-lightbox.js
  test/fixtures/e2e/amp-auto-lightbox/100x100.gif
  test/fixtures/e2e/amp-auto-lightbox/240x135.gif
  test/fixtures/e2e/amp-auto-lightbox/480x270.gif
  test/fixtures/e2e/amp-auto-lightbox/960x540.gif
  test/fixtures/e2e/amp-auto-lightbox/amp-auto-lightbox.html
Labels: cla: yes

#28774 🏗 Remove branches from Travis push builds
  .travis.yml
Labels: cla: yes

#28764 Remove references to whitelist in ads
  3p/README.md
  3p/ampcontext.js
  3p/embedly.js
  3p/integration.js
  ads/_a4a-config.js
  ads/alp/handler.js
  ads/google/utils.js
  ads/inabox/inabox-messaging-host.js
  examples/ads.amp.esm.html
  examples/ads.amp.html
  extensions/amp-a4a/0.1/a4a-variable-source.js
  extensions/amp-a4a/0.1/real-time-config-manager.js
  extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
  extensions/amp-a4a/amp-a4a-format.md
  extensions/amp-a4a/rtc-documentation.md
  extensions/amp-ad-custom/amp-ad-custom.md
  extensions/amp-ad-exit/0.1/amp-ad-exit.js
  extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
  test/unit/test-3p.js
  test/unit/test-integration.js
Labels: cla: yes

#28747 🏗 Remove Single Pass Pipeline
  .eslintrc
  .travis.yml
  ads/google/a4a/traffic-experiments.js
  babel.config.js
  build-system/babel-config/single-pass-config.js
  build-system/compile/bundles.config.js
  build-system/compile/closure-compile.js
  build-system/compile/compile-wrappers.js
  build-system/compile/compile.js
  build-system/compile/single-pass.js
  build-system/eslint-rules/split-single-pass-comment.js
  build-system/pr-check/single-pass-tests.js
  build-system/tasks/dist.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
  build-system/tasks/integration.js
  build-system/tasks/report-test-status.js
  build-system/tasks/runtime-test/runtime-test-base.js
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-date-picker/0.1/test/integration/test-integration-amp-date-picker-actions.js
  extensions/amp-date-picker/0.1/test/integration/test-integration-dates-attributes.js
  extensions/amp-date-picker/0.1/test/integration/test-integration-maximum-nights.js
  extensions/amp-form/0.1/test/integration/test-integration-form-verifiers.js
  extensions/amp-script/0.1/test/integration/test-amp-script.js
  package.json
  src/error.js
  src/mode-object.js
  src/mode.js
  src/polyfills.js
  test/_init_tests.js
  test/integration/test-amp-carousel.js
  test/integration/test-amp-story-analytics.js
  test/unit/test-error.js
  test/unit/test-extension-location.js
  yarn.lock
Labels: cla: yes

#28752 ✨ Add dark theme tooltip
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-tooltip.css
Labels: cla: yes

#28788 Add wg-analytics to analytics.js owner
  src/OWNERS
Labels: cla: yes

#28787 Round SCROLL_TOP/SCROLL_LEFT to integer
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
Labels: cla: yes

#28782 Make fluid resizing robust for iframe removal race conditions.
  extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
Labels: cla: yes

#28817 Strip srcset fallback for ESM builds
  build-system/babel-config/pre-closure-config.js
Labels: cla: yes

#28801 s/RPOPS/PROPS
  extensions/amp-animation/0.1/web-animation-types.js
Labels: cla: yes

#28827 Fix yarn.lock
  yarn.lock
Labels: cla: yes

#28805 ♻️ Remove use of parseUrlDeprecated from amp-analytics
  extensions/amp-analytics/0.1/resource-timing.js
  extensions/amp-analytics/0.1/test/test-resource-timing.js
Labels: WG: performance, cla: yes

#28823 Update URL to amp.dev from ampproject.org
  extensions/amp-experiment/0.1/test/validator-amp-experiment.out
  extensions/amp-experiment/1.0/test/validator-amp-experiment.out
  extensions/amp-live-list/0.1/test/validator-amp-live-list.out
  extensions/amp-mraid/0.1/test/validator-amp-mraid.out
  extensions/amp-script/0.1/test/validator-amp-script.out
  extensions/amp-story/1.0/test/validator-amp-story-amp-experiment-error.out
  extensions/amp-viewer-gpay-button/0.1/test/validator-amp-viewer-gpay-button.out
  extensions/amp-viewer-gpay-inline/0.1/test/validator-amp-viewer-gpay-inline.out
  validator/testdata/amp4ads_feature_tests/extensions.out
  validator/testdata/amp4email_feature_tests/amp-autocomplete.out
  validator/testdata/feature_tests/comment_tags.out
  validator/testdata/feature_tests/duplicate_attribute.out
  validator/testdata/feature_tests/leaks.out
  validator/testdata/feature_tests/no_custom_js.out
  validator/testdata/feature_tests/several_errors.out
  validator/validator-main.protoascii
Labels: cla: yes

#28551 Launch no center css for ad container
  ads/google/a4a/utils.js
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#28815 🐛 Center emulated video posters.
  extensions/amp-video/0.1/amp-video.js
Labels: cla: yes

#28834 🏗 Very significantly speed up travis builds
  .travis.yml
Labels: cla: yes

#26417 📖 Update byside content md documentation
  extensions/amp-byside-content/amp-byside-content.md
Labels: cla: yes

#26989 Update amp-auto-ads.md
  extensions/amp-auto-ads/amp-auto-ads.md
Labels: cla: yes

#27175 ♿Include support for browsers that use contentDocument
  contributing/getting-started-e2e.md
  extensions/amp-a4a/0.1/template-renderer.js
Labels: cla: yes

#26018 📖Correct capitalization of JW Player in amp-video-iframe.md
  extensions/amp-video-iframe/amp-video-iframe.md
Labels: cla: yes

#28707 Add additional consent to amp-consent metadata
  examples/amp-consent/diy-consent.html
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-info.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-info.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
Labels: cla: yes

#24768 :sparkles: Add multi-site support to 'sas' type amp ads
  ads/sas.js
  ads/sas.md
  examples/ads.amp.html
Labels: cla: yes

#28832 Adds a banner for OpenJS World & Collab Summit
  README.md
Labels: cla: yes

#28716 Enable 'intersect-resources' on 10% of prod
  build-system/global-configs/prod-config.json
Labels: cla: yes

#28825 ♻️ Use IS_ESM to skip polyfills/fixes
  3p/polyfills.js
  build-system/babel-config/pre-closure-config.js
  builtins/amp-img.js
  src/css.js
  src/polyfills.js
  src/service/resources-impl.js
Labels: cla: yes

#28724 Add documentation for amp ad type Doubleclick lazy fetch
  extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
  extensions/amp-ad-network-doubleclick-impl/lazy-fetch.md
Labels: cla: yes

#28848 📖 Add referrer to doubleclick RTC macro documentation
  extensions/amp-ad-network-doubleclick-impl/doubleclick-rtc.md
Labels: cla: yes

#28853 🗑 Remove deprecated demo site
  ads/google/csa.md
Labels: cla: yes

#28831 🐛 Bug fix: Avoid aligning to the viewport if the full-width resize failed before.
  extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
Labels: cla: yes

#28850 AdSense/Doubleclick ensure ad request timing accounts for prerender
  ads/google/a4a/utils.js
Labels: cla: yes

#28847 🐛 [amp-mathml] Update config to remove math formulas from tabIndex
  3p/mathml.js
Labels: cla: yes

#28830 📖 Document nested template approach in amp-list, amp-form
  extensions/amp-form/amp-form.md
  extensions/amp-list/amp-list.md
Labels: cla: yes

#28803 catch any errors while `transform` is called
  build-system/server/new-server/router.js
Labels: cla: yes

#27043 fixed example syntax
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#28851 Unlaunch amp-ad-no-centering.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#27715 Update csa.md to include styleId
  ads/google/csa.md
Labels: cla: yes

#27039 Fix description in frontmatter
  extensions/amp-date-countdown/amp-date-countdown.md
Labels: cla: yes

#25776 📖 Update link to ImaSdkSettings
  extensions/amp-ima-video/amp-ima-video.md
Labels: cla: yes

#28446 Small nits for AMP-RDU
  extensions/amp-accordion/amp-accordion.md
Labels: WG: ui-and-a11y, cla: yes

#28860 ♿ Remove aria-live attribute on amp-story.
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#28819 📖 Document Analytics 'enabled' feature
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#28143 🐛 Fix `amp-imgur` embed format
  extensions/amp-imgur/0.1/amp-imgur.js
  extensions/amp-imgur/0.1/test/test-amp-imgur.js
Labels: cla: yes

#28863 Bandaid for SauceLabs disconnects
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test/runtime-test-base.js
  extensions/amp-story/1.0/test/integration/test-amp-story-affiliate-link.js
  src/error.js
  test/_init_tests.js
  test/integration/test-amp-analytics.js
  test/integration/test-amp-bind.js
  test/integration/test-amp-pixel.js
  test/integration/test-amp-recaptcha-input.js
  test/integration/test-amp-skimlinks.js
  test/integration/test-amp-story-analytics.js
  test/integration/test-amphtml-ads.js
  test/integration/test-user-error-reporting.js
  test/unit/test-error.js
  testing/describes.js
  testing/test-helper.js
Labels: cla: yes

#28700 Support variable expansion in amp-consent
  build-system/tasks/presubmit-checks.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/0.1/consent-config.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-config.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  src/services.js
Labels: cla: yes

#28844 Revert "Launch no center css for ad container"
  ads/google/a4a/utils.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#28743 🖍 Increase target size of swipe up
  extensions/amp-story/1.0/amp-story-page-attachment.css
Labels: cla: yes

#28104 Always prefix auto advance advancement modes with autoAdvance.
  extensions/amp-story/1.0/story-analytics.js
Labels: cla: yes

#28873 🐛 Only add additionaly sandbox flag when iframe was sandboxed previously
  src/amp-story-player/amp-story-player-impl.js
Labels: cla: yes

#28822 📖 Document all analytics advanced variable syntax
  spec/amp-var-substitutions.md
Labels: cla: yes

#28748 Include data-vars value to all analytics events by default
  extensions/amp-access/0.1/amp-access-source.js
  extensions/amp-access/0.1/amp-access.js
  extensions/amp-analytics/0.1/events.js
  extensions/amp-analytics/0.1/instrumentation.js
  extensions/amp-analytics/0.1/test/test-events.js
  extensions/amp-next-page/1.0/service.js
  extensions/amp-subscriptions/0.1/analytics.js
  src/analytics.js
  src/error.js
  src/extension-analytics.js
  test/manual/amp-analytics/default-data-vars.html
Labels: cla: yes

#28845 Add padding to amp-sticky-ad on all-screen iPhone
  ads/google/a4a/utils.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#28838 🏗 Run integration tests and only some unit tests on Sauce Labs, only during push builds
  .travis.yml
  build-system/pr-check/remote-tests.js
  build-system/pr-check/utils.js
  build-system/tasks/report-test-status.js
  build-system/test-configs/config.js
Labels: WG: infra, cla: yes

#28781 🐛 [amp-list] Call scheduleUnlayout when amp-list container is updated
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#28329 Adding docs/tests for brid-player dock
  extensions/amp-video-docking/0.1/test/validator-amp-video-docking-amp-brid-player.html
  extensions/amp-video-docking/0.1/test/validator-amp-video-docking-amp-brid-player.out
  extensions/amp-video-docking/amp-video-docking.md
Labels: cla: yes

#28868 🐛 Fix infinite loop in story ads
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
Labels: cla: yes

#28807 ✨ Add a defense-in-depth to the viewer in case communication fails
  src/service/viewer-impl.js
  test/unit/test-viewer.js
Labels: cla: yes

#28753 ♻️ Refactor AES-GCM decryption function.
  extensions/amp-subscriptions/0.1/crypto-handler.js
  third_party/subscriptions-project/aes_gcm.js
Labels: cla: yes

#28806 Fix Intrinsic layout in IE11
  build-system/tasks/presubmit-checks.js
  src/custom-element.js
  src/layout.js
  src/service/ie-intrinsic-bug.js
  src/service/ie-media-bug.js
  src/service/resources-impl.js
  src/utils/img.js
  test/fixtures/images-ie.html
  test/fixtures/script-load-extensions.html
  test/integration/test-amp-img.js
  test/unit/test-ie-media-bug.js
Labels: cla: yes

#28889 📖 Formatting for useInitialPageSize blurb
  extensions/amp-list/amp-list.md
Labels: cla: yes

#28884 Sync from Google
  validator/htmlparser/BUILD
  validator/htmlparser/css/BUILD
  validator/htmlparser/css/parse-css.cc
  validator/htmlparser/css/parse-css.h
  validator/htmlparser/css/parse-css_test.cc
  validator/htmlparser/fileutil.cc
  validator/htmlparser/renderer_test.cc
  validator/htmlparser/strings.cc
  validator/htmlparser/strings.h
  validator/htmlparser/strings_test.cc
  validator/htmlparser/testconstants.h
  validator/htmlparser/tokenizer.cc
Labels: cla: yes

#28893 Fix copyright year in intrinsic bugfix
  src/service/ie-intrinsic-bug.js
Labels: cla: yes

#28895 🐛 [amp-list] Fix incorrect usage of scheduleUnlayout from related bug fix
  extensions/amp-list/0.1/amp-list.js
Labels: cla: yes

#28898 📖 Add format filters for amp-autocomplete
  extensions/amp-autocomplete/amp-autocomplete.md
Labels: cla: yes

#28885 🚫 Hide story icons when ad is showing
  extensions/amp-story/1.0/amp-story-system-layer.css
  extensions/amp-story/1.0/amp-story-system-layer.js
Labels: cla: yes

#28560 ✨ Add GfK Sensic to AMP Analytics Vendors
  examples/analytics-vendors.amp.html
  examples/gfk-sensic-analytics.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/gfksensic.json
  extensions/amp-analytics/analytics-vendors-list.md
Labels: cla: yes

#28814 Pause other videos when a video gets played
  src/service/video-manager-impl.js
  src/video-interface.js
Labels: cla: yes

#28534 [amp-story] Complete docs regarding analytics
  extensions/amp-story/amp-story-analytics.md
Labels: cla: yes

#28736 ♿ amp-lightbox: Improve accessibility with focus
  examples/amp-lightbox.amp.html
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-lightbox/0.1/test/test-amp-lightbox.js
  extensions/amp-lightbox/amp-lightbox.md
Labels: UI: Component: amp-lightbox, WG: ui-and-a11y, cla: yes

#28879 🏗 Adding zuho library to third-party
  third_party/zuho/README.amp
  third_party/zuho/zuho.js
Labels: cla: yes

#28609 📖 springAds: update md file
  ads/springAds.md
  examples/ads.amp.html
Labels: cla: yes

#28886 Enable sticky-ad-padding-bottom on prod
  build-system/global-configs/prod-config.json
Labels: cla: yes

#28901 🐛 Fix amp-img SSR with blurry-image placeholder
  builtins/amp-img.js
  test/unit/test-amp-img.js
Labels: cla: yes

#28852 amp-consent gdprApplies move to consentMetadata
  examples/amp-consent/diy-consent.html
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/consent-info.js
  extensions/amp-consent/0.1/consent-policy-manager.js
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  extensions/amp-consent/0.1/test/test-consent-info.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  src/consent.js
Labels: cla: yes

#28872 Center multi-size creatives narrower than the ad slot.
  ads/google/a4a/utils.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#28447 updated format per amp-rdu
  extensions/amp-ad-exit/amp-ad-exit.md
Labels: WG: ads, cla: yes

#28906 Upgrade karma-sauce-launcher to 4.1.5
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test/runtime-test-base.js
  package.json
  yarn.lock
Labels: cla: yes

#28918 Fail Travis on Sauce failures again
  .travis.yml
Labels: cla: yes

#28862 🐛Correctly reload videos on refreshing of story
  examples/amp-story/videos.html
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/media-tasks.js
Labels: cla: yes

#28914 Adds a link to AMP's OpenJS Collab Summit schedule & Slack channel
  README.md
Labels: cla: yes

#28904 📖 Added missing allow-listed host for font-awesome
  spec/amp-html-format.md
Labels: cla: yes

#28923 ♻️Rename reaction components to interactive components
  build-system/compile/bundles.config.js
  build-system/tasks/presubmit-checks.js
  examples/amp-story/interactives.html
  examples/amp-story/quiz.html
  examples/visual-tests/amp-story/amp-story-interactive-quiz-sizing-positioning.html
  extensions/amp-story/1.0/amp-story-interactive-poll.css
  extensions/amp-story/1.0/amp-story-interactive-poll.js
  extensions/amp-story/1.0/amp-story-interactive-quiz.css
  extensions/amp-story/1.0/amp-story-interactive-quiz.js
  extensions/amp-story/1.0/amp-story-interactive.css
  extensions/amp-story/1.0/amp-story-interactive.js
  extensions/amp-story/1.0/amp-story-user-overridable.css
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-story/1.0/test/test-amp-story-interactive-poll.js
  extensions/amp-story/1.0/test/test-amp-story-interactive-quiz.js
  extensions/amp-story/1.0/test/test-amp-story-interactive.js
  extensions/amp-story/1.0/variable-service.js
  test/visual-diff/visual-tests
Labels: WG: stories, cla: yes

#28911 Pass `maxEntries` to SSR template
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
Labels: cla: yes

#28883 🧪 Enable json targeting CLIENT_ID expansion at 1%
  build-system/global-configs/prod-config.json
  tools/experiments/experiments-config.js
Labels: cla: yes

#28917 Further expand the consent info storage limit to 1200
  extensions/amp-consent/0.1/consent-state-manager.js
  extensions/amp-consent/0.1/test/test-consent-state-manager.js
  extensions/amp-consent/integrating-consent.md
Labels: cla: yes

#28460 add Mapp Intelligence analytics vendor
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/mapp_intelligence.json
  extensions/amp-analytics/analytics-vendors-list.md
Labels: cla: yes

#28928 ♿ amp-autocomplete: Comply with `role=combobox`
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
Labels: cla: yes

#28726 🐛 Fix story not getting touchend on swipe
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/test/test-page-advancement.js
Labels: WG: stories, cla: yes

#28912 Support expireCache in amp-consent prompt action
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-consent/0.1/test/test-amp-consent.js
  test/manual/amp-consent/amp-consent-actions.html
Labels: cla: yes

#28896 🐛Add CSS rule to hide amp-loaders from stories
  css/ampdoc.css
  extensions/amp-loader/0.1/amp-loader.css
Labels: cla: yes

#28727 ✅ Visual tests with amp-video are now working.
  examples/visual-tests/amp-story/amp-story-bot-rendering.html
Labels: cla: yes

#28705 ✨Introduce response stream writer util
  build-system/tasks/presubmit-checks.js
  extensions/amp-a4a/0.1/amp-a4a.js
  src/utils/dom-tranform-stream.js
  src/utils/stream-response.js
  test/unit/utils/test-stream-response.js
Labels: cla: yes

#26996 Add Map and Set support
  build-system/test-configs/conformance-config.textproto
  build-system/test-configs/dep-check-config.js
  src/polyfills.js
  src/polyfills/array-includes.js
  src/polyfills/map-set.js
  src/polyfills/set-add.js
Labels: cla: yes

#28941 📖 Fix syntax error in amp-subscriptions doc
  extensions/amp-subscriptions/amp-subscriptions.md
Labels: cla: yes

#28864 Copy integration files to a new test-bin directory in preparation for postHTML transformation
  .gitignore
  build-system/server/typescript-compile.js
  build-system/tasks/clean.js
  build-system/tasks/integration.js
  build-system/tasks/karma.conf.js
  build-system/tasks/serve.js
  build-system/tasks/server-tests.js
  build-system/test-configs/config.js
Labels: cla: yes
