Repository ampproject/amphtml, pull requests merged in 2020-12, with the labels that each got.

#31373 Remove the file extension for script tags in spec_names/messages
  extensions/amp-ad/validator-amp-ad.protoascii
  extensions/amp-anim/validator-amp-anim.protoascii
  extensions/amp-link-rewriter/0.1/test/validator-amp-link-rewriter-exclude.out
  extensions/amp-mraid/0.1/test/validator-amp4ads-amp-mraid-no-fallback-typo.out
  extensions/amp-mustache/0.1/test/validator-amp-mustache-version.out
  extensions/amp-mustache/0.2/test/validator-amp-mustache-version.out
  extensions/amp-sticky-ad/0.1/test/validator-amp-sticky-ad.out
  extensions/amp-sticky-ad/1.0/test/validator-amp-sticky-ad.out
  extensions/amp-story/1.0/test/validator-amp-story-deprecated.out
  extensions/amp-video/validator-amp-video.protoascii
  validator/js/engine/validator.js
  validator/js/engine/validator_test.js
  validator/testdata/amp4email_feature_tests/amp_img.out
  validator/testdata/amp4email_feature_tests/no_latest_extensions.out
  validator/testdata/amp4email_feature_tests/nonce_disallowed.out
  validator/testdata/feature_tests/article.out
  validator/testdata/feature_tests/custom_element_case.out
  validator/testdata/feature_tests/duplicate_attribute.out.cpponly
  validator/testdata/feature_tests/empty.out
  validator/testdata/feature_tests/empty.out.cpponly
  validator/testdata/feature_tests/mandatory_dimensions.out
  validator/testdata/feature_tests/manufactured_body_whitespace.out.cpponly
  validator/testdata/feature_tests/multiple_body_tags_3.out
  validator/testdata/feature_tests/multiple_body_tags_3.out.cpponly
  validator/testdata/feature_tests/not_amp.out
  validator/testdata/feature_tests/regexps.out
  validator/testdata/feature_tests/runtime_in_body.out
  validator/testdata/feature_tests/several_errors.out
  validator/testdata/feature_tests/spec_example.out
  validator/testdata/feature_tests/track_tag.out
  validator/testdata/feature_tests/unprintable_chars.out
  validator/testdata/feature_tests/unprintable_chars.out.cpponly
  validator/testdata/feature_tests/urls.out
  validator/validator-main.protoascii
Labels: WG: caching

#31376 resources-impl: fix resize event race condition.
  src/service/resources-impl.js
  test/unit/test-resources.js
Labels: Type: Bug

#31355 ✨ Scaffold amp-story-panning-media extension folder
  build-system/compile/bundles.config.js
  examples/amp-story-panning-media.amp.html
  extensions/amp-story-panning-media/0.1/amp-story-panning-media.css
  extensions/amp-story-panning-media/0.1/amp-story-panning-media.js
  extensions/amp-story-panning-media/0.1/test/test-amp-story-panning-media.js
  extensions/amp-story-panning-media/0.1/test/validator-amp-story-panning-media.html
  extensions/amp-story-panning-media/0.1/test/validator-amp-story-panning-media.out
  extensions/amp-story-panning-media/OWNERS
  extensions/amp-story-panning-media/validator-amp-story-panning-media.protoascii
  extensions/amp-story/validator-amp-story.protoascii
Labels: WG: caching

#30739 ✅ 360 component visual diff test
  build-system/tasks/visual-diff/index.js
  build-system/tasks/visual-diff/snippets/freeze-canvas-image.js
  examples/visual-tests/amp-story/amp-story-360-image.html
  examples/visual-tests/amp-story/img/SeanDoran-Quela-sol1462-edited_ver2-sm.jpg
  extensions/amp-story-360/0.1/amp-story-360.js
  test/visual-diff/visual-tests
  third_party/zuho/README.amp
  third_party/zuho/zuho.js
Labels: P2: Soon, Type: Testing, WG: stories

#31417 🏗 Remove project-level code coverage status
  .codecov.yml
Labels: WG: infra

#31303 ✨ [Story devtools] Add preview tab
  examples/amp-story/interactives.html
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.css
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.js
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.css
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.js
  extensions/amp-story-dev-tools/0.1/utils.js
Labels: WG: stories

#31433 [amp-story-player] Add intrinsic to supported layouts
  extensions/amp-story-player/validator-amp-story-player.protoascii
Labels: WG: caching

#31336 [Story devtools] Create logs tab
  examples/amp-story/interactives.html
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-logs.css
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-logs.js
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.css
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.js
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.css
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.js
Labels: WG: stories

#31397 🚮 Remove <amp-google-vrview-image>
  build-system/compile/bundles.config.js
  examples/vrview.amp.html
  extensions/amp-google-vrview-image/0.1/amp-google-vrview-image.js
  extensions/amp-google-vrview-image/0.1/test/test-amp-google-vrview-image.js
  extensions/amp-google-vrview-image/OWNERS
  extensions/amp-google-vrview-image/amp-google-vrview-image.md
  extensions/amp-story/amp-story-grid-layer.md
  extensions/amp-story/amp-story-page-attachment.md
  extensions/amp-story/validator-amp-story.protoascii
  tools/experiments/experiments-config.js
Labels: WG: caching

#31507 🏗♻️ Make all utilities in `build-system/common/git.js` CI-service-agnostic
  build-system/common/ci.js
  build-system/common/circleci.js
  build-system/common/git.js
  build-system/common/github-actions.js
  build-system/common/travis.js
  build-system/pr-check/utils.js
  build-system/tasks/bundle-size/index.js
  build-system/tasks/visual-diff/index.js
Labels: WG: infra

#31518 🏗♻️ Make visual diff code CI service agnostic
  build-system/tasks/visual-diff/index.js
  build-system/tasks/visual-diff/snippets/snapshot-error.html
Labels: WG: infra

#31520 🚮 [amp-story-360] Implicit returns on renderer setup
  extensions/amp-story-360/0.1/amp-story-360.js
Labels: Type: Refactoring, WG: stories

#31546 Validator rollup
  validator/validator-main.protoascii
Labels: WG: caching

#31527 🏗♻️ Refactor, simplify, and adopt library for CI-specific state
  build-system/common/ci.js
  build-system/common/circleci.js
  build-system/common/github-actions.js
  build-system/common/travis.js
  build-system/pr-check/dist-tests.js
  build-system/pr-check/utils.js
  build-system/tasks/bundle-size/index.js
  build-system/tasks/codecov-upload.js
  build-system/tasks/karma.conf.js
  build-system/tasks/pr-deploy-bot-utils.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/report-test-status.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/storybook/index.js
  build-system/tasks/test-report-upload.js
Labels: WG: infra

#31494 Remove polyfills from webworker for esm builds.
  src/web-worker/web-worker-polyfills.js
Labels: Related to: Performance, WG: performance

#31550 🏗 Optimize cross-browser test runs on GH actions
  .github/workflows/cross-browser-tests.yml
  build-system/common/git.js
  build-system/pr-check/cross-browser-tests.js
  build-system/tasks/karma.conf.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/runtime-test/runtime-test-base.js
Labels: WG: infra

#31526 Create e2e tests for viewers that depend on documentHeight (gmail)
  build-system/tasks/e2e/amp-driver.js
  build-system/tasks/e2e/describes-e2e.js
  test/e2e/test-amp-email.js
  test/fixtures/e2e/amp-viewer-integration/viewer.html
  test/fixtures/e2e/amp4email/element-size-race.html
  test/fixtures/e2e/amp4email/viewport-size-race.html
Labels: Related to: Performance, Type: Testing, WG: amp4email, WG: performance

#26911 📖 Visibility trigger multi-selector doc
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#31570 🏗 Clean up closure error levels, remove ineffective `jscomp_warning`
  build-system/compile/compile.js
Labels: WG: infra

#31439 intersect-resources: relaunch for amp4email
  src/service/resources-impl.js
Labels: WG: amp4email, WG: performance

#31640 Validator Roll Up
  extensions/amp-accordion/validator-amp-accordion.protoascii
  validator/testdata/amp4email_feature_tests/amp-accordion.html
  validator/testdata/amp4email_feature_tests/amp-accordion.out
  validator/validator-main.protoascii
Labels: WG: caching

#31646 🏗 Make test status reporting work across CI services
  build-system/common/ci.js
  build-system/pr-check/cross-browser-tests.js
  build-system/tasks/report-test-status.js
Labels: WG: infra

#31691 Sync for validator/cpp/engine
  validator/cpp/engine/WORKSPACE
Labels: WG: caching

#29592 ✨ Add Adtelligent network to amp-ad
  3p/integration.js
  ads/_config.js
  ads/adtelligent.js
  ads/adtelligent.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#31709 ✨[Story devtools] Added logs status icon on tab selector
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-logs.css
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-logs.js
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.css
Labels: WG: stories
