Repository ampproject/amphtml, pull requests merged in 2020-08, with the labels that each got.

#29568 amp-autocomplete: Silently disregard `suggest-first`
  extensions/amp-autocomplete/0.1/autocomplete-binding-single.js
  extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-bindings.js
Labels: cla: yes

#29541 protocol adapters: e2e test, nodom binary, and bump worker-dom.
  build-system/tasks/extension-helpers.js
  extensions/amp-list/0.1/test-e2e/test-function-src.js
  extensions/amp-script/0.1/amp-script.css
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
  package.json
  test/fixtures/e2e/amp-list/amp-list-function-src.html
  yarn.lock
Labels: Component: amp-script, UI: Component: amp-list, WG: runtime, cla: yes

#29519 🏗 Introduction of `coverage-map` task.
  build-system/tasks/coverage-map/index.js
  build-system/tasks/coverage-map/package.json
  build-system/tasks/coverage-map/yarn.lock
  build-system/tasks/presubmit-checks.js
  gulpfile.js
Labels: cla: yes

#29634 🚀 springAds: removing revised and no longer used prefetch
  ads/_config.js
Labels: cla: yes

#29631 🐛 Fix: AmpDocShadow shouldn't become visible on user interaction
  src/service/viewer-impl.js
  test/unit/test-viewer.js
Labels: cla: yes

#29552 ✨ Change requestResize interface to return promise
  3p/ampcontext.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
  test/unit/test-amp-context.js
Labels: cla: yes

#28667 ✨ Integration of iubenda in amp-consent
  examples/amp-consent/cmp-vendors.amp.html
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/amp-consent.md
  extensions/amp-consent/cmps/iubenda.md
Labels: cla: yes

#29633 ✨ [bento][amp-social-share] Do not throw error when no params are provided for email type
  extensions/amp-social-share/1.0/social-share.js
Labels: cla: yes

#29632 ✨ [bento][amp-social-share] Allow children to be rendered and colors to be customized for all types
  extensions/amp-social-share/1.0/social-share-config.js
  extensions/amp-social-share/1.0/social-share.js
Labels: cla: yes

#29616 ✅ [amp-story-player] Replace iframe checks with navigation API
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29411 ✨ [amp-story-player] Implement circular wrapping
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29652 remove unused function
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29642 Remove unnecessary requires_usage and deprecated_allow_duplicates
  extensions/amp-accordion/validator-amp-accordion.protoascii
  extensions/amp-fit-text/validator-amp-fit-text.protoascii
  extensions/amp-form/validator-amp-form.protoascii
  validator/testdata/amp4email_feature_tests/no_latest_extensions.out
Labels: Validator: Approved, WG: amp4email, WG: caching, cla: yes

#29624 🐛 amp-inputmask: query is too zealous
  extensions/amp-inputmask/0.1/amp-inputmask.js
Labels: UI: Component: amp-input-mask, cla: yes

#29418 ContextNode: components, subscribers, and hooks
  src/context/component-hooks.js
  src/context/component-install.js
  src/context/component-meta.js
  src/context/component.js
  src/context/index.js
  src/context/node.js
  src/context/scheduler.js
  test/unit/context/test-node-components.js
Labels: cla: yes

#29345 🖍 [amp-story-player] Hide exit controls during open page attachments
  css/amp-story-player-iframe.css
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29651 Remove AMP Actions from Validator WebUI
  validator/webui/@polymer/webui-mainpage/webui-mainpage.html
  validator/webui/@polymer/webui-urlform/webui-urlform.html
  validator/webui/README.md
Labels: WG: caching, cla: yes

#29378 📖 Ajust options in document of yahoofedads.
  ads/yahoofedads.md
Labels: cla: yes

#29649 🐛 [Story Interactive] Default pointer in post-select state for interactive options.
  extensions/amp-story/1.0/amp-story-interactive.css
Labels: cla: yes

#29136 removed backticks from header
  build-system/tasks/extension-generator/extension-doc.template.md
Labels: cla: yes

#29384 updated to match template
  extensions/amp-image-lightbox/amp-image-lightbox.md
  extensions/amp-image-slider/amp-image-slider.md
  extensions/amp-lightbox-gallery/amp-lightbox-gallery.md
  extensions/amp-lightbox/amp-lightbox.md
  extensions/amp-link-rewriter/amp-link-rewriter.md
Labels: WG: ui-and-a11y, cla: yes

#29068 updated structure to match template
  builtins/amp-img.md
  extensions/amp-fx-collection/amp-fx-collection.md
  extensions/amp-fx-flying-carpet/amp-fx-flying-carpet.md
  extensions/amp-geo/amp-geo.md
  extensions/amp-iframe/amp-iframe.md
Labels: WG: analytics, WG: ui-and-a11y, cla: yes

#29606 ✨ Support for icon fonts inside shadow documents
  src/multidoc-manager.js
Labels: cla: yes

#29572 ✨Introduce new macro for experiment branches.
  extensions/amp-analytics/0.1/default-config.js
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
  src/experiments.js
  test/unit/test-experiments.js
Labels: cla: yes

#29628 🐛 No Signing: add missing elements to secure frame.
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/head-validation.js
  extensions/amp-a4a/0.1/secure-frame.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/test-head-validation.js
Labels: cla: yes

#29577 Enable integration tests for no-signing (2nd try)
  extensions/amp-a4a/0.1/head-validation.js
  extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
  test/integration/test-amphtml-ads.js
Labels: cla: yes

#29672 Reduce number of AMP_TOP errors on iframe unloading
  extensions/amp-analytics/0.1/amp-analytics.js
  src/service/resource.js
Labels: cla: yes

#29646 🐛 inputmask: remove static from fn using `this`
  extensions/amp-inputmask/0.1/mask-impl.js
  extensions/amp-inputmask/0.1/test/test-mask-impl.js
Labels: UI: Component: amp-input-mask, WG: runtime, cla: yes

#29675 [amp-story] Disable local storage when provided via fragment parameter
  extensions/amp-story/1.0/history.js
Labels: cla: yes

#29654 🏗 Additional updates for gulp task `coverage-map`
  build-system/tasks/coverage-map/index.js
Labels: cla: yes

#29630 ✨ kaltura: add serviceUrl
  extensions/amp-kaltura-player/0.1/amp-kaltura-player.js
  extensions/amp-kaltura-player/0.1/test/test-amp-kaltura-player.js
  extensions/amp-kaltura-player/0.1/test/validator-amp-kaltura-player.html
  extensions/amp-kaltura-player/0.1/test/validator-amp-kaltura-player.out
  extensions/amp-kaltura-player/OWNERS
  extensions/amp-kaltura-player/amp-kaltura-player.md
Labels: cla: yes

#29653 🚀 Winner MOVE_FIXED_LAYER experiment
  build-system/global-configs/experiments-config.json
  build-system/global-configs/experiments-const.json
  extensions/amp-viewer-integration/0.1/amp-viewer-integration.js
  src/service/viewport/viewport-impl.js
Labels: WG: performance, cla: yes

#29687 🏗 Switch usage of `gulp-watch` to `gulp.watch`
  build-system/tasks/css.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
  build-system/tasks/serve.js
  build-system/tasks/vendor-configs.js
Labels: WG: infra, cla: yes

#29660 🧪 Launch render-on-idle-fix
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#29690 Fix media performance tracking on first story page.
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
Labels: cla: yes

#29694 Update validator nodejs details
  validator/nodejs/README.md
  validator/nodejs/package.json
Labels: WG: caching, cla: yes

#29503 removed extra format filter
  extensions/amp-list/amp-list.md
Labels: cla: yes

#29669 ✨ Launch sticky-ad-padding-bottom
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#29527 ♿ Focusable back button for screen readers.
  extensions/amp-story/1.0/_locales/en.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
  src/localized-strings.js
Labels: cla: yes

#29663 Ramp up ampdoc-fie experiment to 10% (5% exp, 5% control) in prod.
  build-system/global-configs/prod-config.json
Labels: cla: yes

#29665 🚮 Cleanup layoutbox-invalidate-on-scroll experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  src/service/resources-impl.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#29678 updated to match template
  extensions/amp-story/amp-story-cta-layer.md
  extensions/amp-story/amp-story-grid-layer.md
  extensions/amp-story/amp-story-page-attachment.md
  extensions/amp-story/amp-story-page.md
  extensions/amp-story/amp-story.md
Labels: cla: yes

#29702 Sync from Google
  validator/htmlparser/allocator.h
  validator/htmlparser/allocator_test.cc
Labels: WG: caching, cla: yes

#29643 Adds entity metadata support.
  extensions/amp-story/1.0/test/validator-amp-story.html
  extensions/amp-story/1.0/test/validator-amp-story.out
  extensions/amp-story/amp-story.md
  extensions/amp-story/validator-amp-story.protoascii
Labels: Validator: Approved, WG: caching, cla: yes

#29699 Reduce unloading errors for FIE
  src/friendly-iframe-embed.js
Labels: cla: yes

#29689 amp-list: launch protocol adapters in canary and prod
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: Component: amp-script, UI: Component: amp-list, WG: runtime, cla: yes

#29301 ✅ [amp story player] Visual Tests for Back and Close Button
  examples/visual-tests/amp-story-player/back-button.html
  examples/visual-tests/amp-story-player/close-button.html
  examples/visual-tests/amp-story-player/placeholder.js
  src/amp-story-player/amp-story-player-impl.js
  test/visual-diff/visual-tests
Labels: cla: yes

#29715 ✨ Add amp-ad support for glomex
  3p/integration.js
  ads/_config.js
  ads/glomex.js
  ads/glomex.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#29650 ♻️ Carousel: Use forwardRef
  build-system/compile/sources.js
  extensions/amp-base-carousel/1.0/base-carousel.js
  extensions/amp-base-carousel/1.0/scroller.js
  src/preact/compat.js
  src/preact/index.js
Labels: cla: yes

#29719 ✨ Add https to default task flags.
  build-system/tasks/default-task.js
Labels: WG: stories, cla: yes

#28929 Cleanup INTERSECTION_OBSERVER_POLYFILL experiment
  build-system/global-configs/experiments-const.json
  build-system/tasks/check-sourcemaps.js
  extensions/amp-a4a/0.1/refresh-intersection-observer-polyfill-wrapper.js
  extensions/amp-a4a/0.1/refresh-manager.js
  extensions/amp-a4a/0.1/test/test-refresh.js
  extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
  extensions/amp-analytics/0.1/test/test-visibility-manager.js
  extensions/amp-analytics/0.1/visibility-manager.js
  extensions/amp-apester-media/0.1/amp-apester-media.js
  extensions/amp-iframe/0.1/amp-iframe.js
  src/friendly-iframe-embed-legacy.js
  src/friendly-iframe-embed.js
  src/polyfills.js
  src/runtime.js
  src/utils/intersection-observer-polyfill.js
  test/unit/test-intersection-observer-polyfill.js
Labels: cla: yes

#29722 include intersection observer polyfill back into ESM
  build-system/compile/compile.js
Labels: P1: High Priority, Type: Bug, WG: performance, cla: yes

#29679 🧪Enable E2E Tests for no signing exp.
  build-system/server/routes/a4a-envelopes.js
  build-system/server/server-a4a-template.html
  build-system/tasks/e2e/amp-driver.js
  build-system/tasks/e2e/describes-e2e.js
Labels: cla: yes

#29177 ✨ Move interactive components to its own extension
  build-system/compile/bundles.config.js
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/dep-check-config.js
  examples/amp-story/interactive_results.html
  examples/amp-story/interactives.html
  examples/visual-tests/amp-story/amp-story-interactive-quiz-sizing-positioning.html
  extensions/amp-story-interactive/1.0/amp-story-interactive-abstract.js
  extensions/amp-story-interactive/1.0/amp-story-interactive-binary-poll.css
  extensions/amp-story-interactive/1.0/amp-story-interactive-binary-poll.js
  extensions/amp-story-interactive/1.0/amp-story-interactive-poll.css
  extensions/amp-story-interactive/1.0/amp-story-interactive-poll.js
  extensions/amp-story-interactive/1.0/amp-story-interactive-quiz.css
  extensions/amp-story-interactive/1.0/amp-story-interactive-quiz.js
  extensions/amp-story-interactive/1.0/amp-story-interactive-results.css
  extensions/amp-story-interactive/1.0/amp-story-interactive-results.js
  extensions/amp-story-interactive/1.0/amp-story-interactive.css
  extensions/amp-story-interactive/1.0/amp-story-interactive.js
  extensions/amp-story-interactive/1.0/interactive-confetti.js
  extensions/amp-story-interactive/1.0/test/test-amp-story-interactive-binary-poll.js
  extensions/amp-story-interactive/1.0/test/test-amp-story-interactive-quiz.js
  extensions/amp-story-interactive/1.0/test/test-amp-story-interactive-results.js
  extensions/amp-story-interactive/1.0/test/test-amp-story-interactive.js
  extensions/amp-story-interactive/1.0/utils.js
  extensions/amp-story-interactive/OWNERS
  extensions/amp-story-interactive/amp-story-interactive.md
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  src/services.js
Labels: WG: stories, cla: yes

#29720 🐛 Remove flaky no signing integration test
  test/integration/test-amphtml-ads.js
Labels: cla: yes

#29726 amp-list: Fix layoutCallback promise chain in SSR path
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#29716 ♻️ Refactoring: Separate the convertToContainerWidth flow from maybeUpgradeToResponsive method
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
Labels: cla: yes

#29705 📦 Upgrade to Terser 5
  build-system/compile/post-closure-babel.js
  package.json
  yarn.lock
Labels: cla: yes

#29709 📖 Remove pushState documentation for AMP for Email
  extensions/amp-bind/amp-bind.md
  spec/amp-email-actions-and-events.md
Labels: cla: yes

#29680 🧪Removal of `pull-to-refresh` and `viewport-binding-ios-embed` for SxG build.
  src/amp.js
  src/service/viewport/viewport-impl.js
Labels: cla: yes

#29671 updated to match template
  extensions/amp-next-page/0.1/amp-next-page.md
  extensions/amp-orientation-observer/amp-orientation-observer.md
  extensions/amp-pan-zoom/amp-pan-zoom.md
  extensions/amp-position-observer/amp-position-observer.md
Labels: cla: yes

#29668 updated to match template
  builtins/amp-pixel.md
  extensions/amp-mathml/amp-mathml.md
  extensions/amp-mega-menu/amp-mega-menu.md
  extensions/amp-nested-menu/amp-nested-menu.md
  extensions/amp-sidebar/0.1/amp-sidebar.md
Labels: cla: yes

#29737 AdSense/Doubleclick Launch Adx/Ady Rounding
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#29521 ✨Added interactive percentage results
  examples/amp-story/interactive_quizzes.html
  extensions/amp-story-interactive/1.0/amp-story-interactive-abstract.js
  extensions/amp-story-interactive/1.0/amp-story-interactive-results.css
  extensions/amp-story-interactive/1.0/amp-story-interactive-results.js
  extensions/amp-story-interactive/1.0/test/test-amp-story-interactive-results.js
Labels: WG: stories, cla: yes

#29727 amp-list: Allow layout=container and diffable together
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#29741 ♻️ Switch Lazy Loading Animation Polyfill to WeakMap
  extensions/amp-animation/0.1/install-polyfill.js
Labels: cla: yes

#29241 NWS fast fetch implementation
  ads/_a4a-config.js
  build-system/test-configs/dep-check-config.js
  examples/amphtml-ads/nws.a4a.html
  extensions/amp-ad-network-nws-impl/0.1/amp-ad-network-nws-impl.js
  extensions/amp-ad-network-nws-impl/0.1/test/test-nws-a4a-config.js
  extensions/amp-ad-network-nws-impl/amp-ad-network-nws-impl-internal.md
Labels: cla: yes

#29712 ✨ Add FirstImpression.io to amp-ad and amp-auto-ads
  3p/integration.js
  ads/_config.js
  ads/firstimpression.js
  ads/firstimpression.md
  extensions/amp-auto-ads/0.1/ad-network-config.js
  extensions/amp-auto-ads/0.1/firstimpression.io-network-config.js
  extensions/amp-auto-ads/amp-auto-ads.md
Labels: cla: yes

#29148 Remove duplicate words
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#29735 ContextNode: fix recursive computations with dependencies
  src/context/values.js
  test/unit/context/test-node-values.js
Labels: cla: yes

#29692 new lint rule: no static this
  .eslintrc.js
  build-system/eslint-rules/no-static-this.js
  testing/test-helper.js
Labels: cla: yes

#29740 🧪 Experimental code: Dial up the Adsense ad size optimization experiment to 5%.
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#29704 Rewind last story page on visibilitystate inactive.
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#29742 🏗 SwG Release 0.1.22.116, Aug 8, 2020
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#29728 Cleanup hidden-mutation-observer experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  src/service/fixed-layer.js
  test/unit/test-fixed-layer.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#29620 🐛 Use deep copy of extraUrlParams for sending requests
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/test/test-requests.js
Labels: cla: yes

#29749 ♻️ Fix todo by using a WeakMap
  extensions/amp-story/1.0/media-performance-metrics-service.js
Labels: cla: yes

#29733 Ramp "intersect-resources" to 100% (third try)
  build-system/global-configs/prod-config.json
  extensions/amp-list/0.1/test-e2e/test-function-src.js
Labels: Component: amp-script, WG: runtime, cla: yes

#29755 🧪Enable no-signing exp in experimental.
  build-system/global-configs/canary-config.json
Labels: cla: yes

#29750 ♻️ [Animation presets] Revise default curve and duration values
  examples/amp-story/animations-presets.html
  extensions/amp-story/1.0/animation-presets-utils.js
  extensions/amp-story/1.0/animation-presets.js
Labels: cla: yes

#29677 updated to match template
  extensions/amp-recaptcha-input/amp-recaptcha-input.md
  extensions/amp-selector/amp-selector.md
  extensions/amp-social-share/amp-social-share.md
  extensions/amp-sticky-ad/amp-sticky-ad.md
  extensions/amp-truncate-text/amp-truncate-text.md
Labels: cla: yes

#29739 ♻️ amp-accordion: `beforematch` modifications
  extensions/amp-accordion/0.1/amp-accordion.js
Labels: cla: yes

#29724 Use `storybook-addon-amp` inside the storybook integration
  build-system/tasks/presubmit-checks.js
  build-system/tasks/storybook/.gitignore
  build-system/tasks/storybook/amp-env/decorator.js
  build-system/tasks/storybook/amp-env/main.js
  build-system/tasks/storybook/package.json
  build-system/tasks/storybook/yarn.lock
  extensions/amp-animation/0.1/storybook/Basic.amp.js
  extensions/amp-animation/0.1/storybook/Random.amp.js
  extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
  extensions/amp-date-display/1.0/storybook/Basic.amp.js
  extensions/amp-fit-text/1.0/storybook/Basic.amp.js
  extensions/amp-image-slider/0.1/storybook/Basic.amp.js
  extensions/amp-selector/1.0/storybook/Basic.amp.js
  extensions/amp-sidebar/0.1/storybook/Basic.amp.js
  extensions/amp-social-share/0.1/storybook/Basic.amp.js
  extensions/amp-social-share/1.0/storybook/Basic.amp.js
  extensions/amp-timeago/1.0/storybook/Basic.amp.js
  extensions/amp-youtube/0.1/storybook/Basic.amp.js
Labels: cla: yes

#29707 updated to match template
  extensions/amp-user-notification/amp-user-notification.md
  extensions/amp-video-docking/amp-video-docking.md
  extensions/amp-video/amp-video.md
  extensions/amp-web-push/amp-web-push.md
  extensions/amp-youtube/amp-youtube.md
Labels: cla: yes

#29771 🐛 Clone IntersectionObserverEntry for cross-origin postMessages
  src/utils/intersection-observer-polyfill.js
Labels: cla: yes

#29772 ⏪ Temporarily revert lazy polyfill web animations
  build-system/compile/bundles.config.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-animation-polyfill/0.1/amp-animation-polyfill.js
  extensions/amp-animation-polyfill/OWNERS
  extensions/amp-animation/0.1/amp-animation.js
  extensions/amp-animation/0.1/install-polyfill.js
  extensions/amp-animation/0.1/web-animation-service.js
  extensions/amp-animation/0.1/web-animations-polyfill.js
Labels: cla: yes

#29751 🏗 Catch Minify Errors
  build-system/compile/post-closure-babel.js
Labels: cla: yes

#29766 Scale fade animation preset.
  examples/amp-story/animations-presets.html
  extensions/amp-story/1.0/animation-presets.js
  extensions/amp-story/amp-story.md
  extensions/amp-story/validator-amp-story.protoascii
Labels: WG: caching, WG: stories, cla: yes

#29780 📖 Update docs to reflect new animation preset times
  extensions/amp-story/amp-story.md
Labels: WG: stories, cla: yes

#29776 ✨ extend support for pingback on to platforms.
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
  extensions/amp-subscriptions/0.1/local-subscription-platform-base.js
  extensions/amp-subscriptions/0.1/subscription-platform.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Labels: cla: yes

#29775 Revert "⏪ Temporarily revert lazy polyfill web animations"
  build-system/compile/bundles.config.js
  build-system/tasks/presubmit-checks.js
  extensions/amp-animation-polyfill/0.1/amp-animation-polyfill.js
  extensions/amp-animation-polyfill/OWNERS
  extensions/amp-animation/0.1/amp-animation.js
  extensions/amp-animation/0.1/install-polyfill.js
  extensions/amp-animation/0.1/web-animation-service.js
  extensions/amp-animation/0.1/web-animations-polyfill.js
Labels: cla: yes

#29784 ❄️ Skip flaky amp-carousel test
  test/integration/test-amp-carousel.js
Labels: cla: yes

#29782 🏗 Always pull latest in gulp cherry-pick
  build-system/tasks/cherry-pick.js
Labels: cla: yes

#29787 Move validator/engine to validator/js/engine
  build-system/tasks/presubmit-checks.js
  extensions/amp-bind/0.1/bind-validator.js
  validator/README.md
  validator/build.py
  validator/js/engine/amp4ads-parse-css.js
  validator/js/engine/amp4ads-parse-css_test.js
  validator/js/engine/css-selectors.js
  validator/js/engine/definitions.js
  validator/js/engine/htmlparser-interface.js
  validator/js/engine/htmlparser.js
  validator/js/engine/htmlparser_test.js
  validator/js/engine/json-testutil.js
  validator/js/engine/keyframes-parse-css.js
  validator/js/engine/keyframes-parse-css_test.js
  validator/js/engine/parse-css.js
  validator/js/engine/parse-css_test.js
  validator/js/engine/parse-srcset.js
  validator/js/engine/parse-srcset_test.js
  validator/js/engine/parse-url.js
  validator/js/engine/parse-url_test.js
  validator/js/engine/tokenize-css.js
  validator/js/engine/validator-in-browser.js
  validator/js/engine/validator.js
  validator/js/engine/validator_test.js
Labels: WG: caching, cla: yes

#29752 amp-script: Move [nodom] CSS to ampdoc.css to avoid resize
  css/ampdoc.css
  extensions/amp-list/0.1/test-e2e/test-function-src.js
  extensions/amp-script/0.1/amp-script.css
Labels: cla: yes

#29748 ✨Added validation for interactives
  extensions/amp-story-interactive/1.0/test/validator-amp-story-interactive-poll.html
  extensions/amp-story-interactive/1.0/test/validator-amp-story-interactive-poll.out
  extensions/amp-story-interactive/1.0/test/validator-amp-story-interactive-quiz.html
  extensions/amp-story-interactive/1.0/test/validator-amp-story-interactive-quiz.out
  extensions/amp-story-interactive/1.0/test/validator-amp-story-interactive-results.html
  extensions/amp-story-interactive/1.0/test/validator-amp-story-interactive-results.out
  extensions/amp-story-interactive/validator-amp-story-interactive.protoascii
  extensions/amp-story/validator-amp-story.protoascii
Labels: WG: stories, cla: yes

#29801 🐛 FirstImpression.io integration: reverted to using window.location
  extensions/amp-auto-ads/0.1/firstimpression.io-network-config.js
Labels: cla: yes

#29629 Collect additional visible info for debugging
  examples/amphtml-ads/visibility-ad.a4a.html
  extensions/amp-analytics/0.1/requests.js
  extensions/amp-analytics/0.1/visibility-manager.js
  extensions/amp-analytics/0.1/visibility-model.js
Labels: cla: yes

#29803 🐛 Hide border if user is not using keyboard input.
  extensions/amp-story/1.0/amp-story.css
Labels: WG: stories, cla: yes

#29788 ✨Added interactive transparent styles
  examples/amp-story/interactives.html
  extensions/amp-story-interactive/1.0/amp-story-interactive-poll.css
  extensions/amp-story-interactive/1.0/amp-story-interactive-quiz.css
  extensions/amp-story-interactive/1.0/amp-story-interactive-results.css
  extensions/amp-story-interactive/1.0/amp-story-interactive.css
  extensions/amp-story/1.0/amp-story.css
Labels: WG: stories, cla: yes

#29204 amp-consent iframe modal UI
  examples/amp-consent/diy-consent.html
  extensions/amp-consent/0.1/amp-consent.css
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  extensions/amp-consent/integrating-consent.md
Labels: cla: yes

#29810 🐛 Talkback button, no pointer events
  extensions/amp-story/1.0/amp-story.css
Labels: WG: stories, cla: yes

#29658 ♻️ [bento][amp-social-share] Add prop types and update type definitions for Social Share and basic cleanup
  extensions/amp-social-share/1.0/social-share-config.js
  extensions/amp-social-share/1.0/social-share.js
  extensions/amp-social-share/1.0/social-share.type.js
Labels: cla: yes

#29808 🐛 Fix srcdoc in fake ad
  extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
  extensions/amp-ad-network-fake-impl/0.1/test/test-amp-ad-network-fake-impl.js
Labels: cla: yes

#29822 ✨Added pointer events caching only on selectable items
  extensions/amp-story-interactive/1.0/amp-story-interactive.css
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#29768 🏗 [test-case-reporting] Implement PoC for e2e test reporter
  build-system/tasks/e2e/index.js
  build-system/tasks/e2e/mocha-ci-reporter.js
  build-system/tasks/e2e/mocha-custom-json-reporter.js
  build-system/tasks/e2e/mocha-dots-reporter.js
Labels: cla: yes

#29659 ✨ Add sticky to allowable amp-ad attributes
  extensions/amp-ad/0.1/test/validator-amp-ad.html
  extensions/amp-ad/0.1/test/validator-amp-ad.out
  extensions/amp-ad/validator-amp-ad.protoascii
Labels: cla: yes

#29827 Fixing indents to match cl
  validator/build.py
  validator/js/nodejs/README.md
  validator/js/nodejs/index_test.js
Labels: WG: caching, cla: yes

#29830 Validator rollup
  extensions/amp-accordion/validator-amp-accordion.protoascii
  extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
  extensions/amp-fit-text/validator-amp-fit-text.protoascii
  extensions/amp-form/validator-amp-form.protoascii
  validator/js/engine/parse-css.js
  validator/js/engine/validator.js
  validator/testdata/amp4ads_feature_tests/doctype.out
  validator/testdata/amp4ads_feature_tests/doctype.out.cpponly
  validator/testdata/amp4email_feature_tests/amp-autocomplete.html
  validator/testdata/amp4email_feature_tests/amp-autocomplete.out
  validator/testdata/amp4email_feature_tests/css_declarations.html
  validator/testdata/amp4email_feature_tests/css_declarations.out
  validator/testdata/amp4email_feature_tests/css_strict.html
  validator/testdata/amp4email_feature_tests/css_strict.out
  validator/testdata/amp4email_feature_tests/no_latest_extensions.out
  validator/testdata/feature_tests/css_declarations.out
  validator/testdata/feature_tests/incorrect_custom_style.out
  validator/testdata/feature_tests/inline_style.out
  validator/testdata/feature_tests/leaks.out
  validator/testdata/feature_tests/leaks.out.cpponly
  validator/validator-css.protoascii
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
  validator/validator_gen_js.py
Labels: WG: caching, cla: yes

#29603 📖 protocol adapters: adds documentation
  extensions/amp-list/amp-list.md
  extensions/amp-script/amp-script.md
Labels: Component: amp-script, Related to: Documentation, UI: Component: amp-list, WG: runtime, cla: yes

#29832 Ramp json targeting expansion experiment to 100%
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#29828 ♻️no-signing: don't wait for fie install before writing
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/secure-frame.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  src/friendly-iframe-embed.js
Labels: cla: yes

#29845 Docs: Add caveat about AMP.navigateTo
  spec/amp-actions-and-events.md
Labels: cla: yes

#29819 📖 Added readme to interactive components
  extensions/amp-story-interactive/README.md
Labels: cla: yes

#29713 bento: add jss styling for amp-carousel.
  build-system/tasks/storybook/preact-env/webpack.config.js
  extensions/amp-base-carousel/1.0/amp-base-carousel.js
  extensions/amp-base-carousel/1.0/arrow.js
  extensions/amp-base-carousel/1.0/base-carousel.css.js
  extensions/amp-base-carousel/1.0/base-carousel.jss.js
  extensions/amp-base-carousel/1.0/scroller.js
  extensions/amp-base-carousel/1.0/storybook/Basic.js
  package.json
  yarn.lock
Labels: UI: Component: amp-base-carousel, WG: bento, cla: yes

#29853 Fix 3p ad viewportCallback
  extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
Labels: cla: yes

#29858 🐛 Fix typo
  extensions/amp-story/1.0/animation-presets.js
Labels: cla: yes

#29589 ✨ Freestar RTC Module
  examples/ads.amp.html
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-a4a/rtc-documentation.md
  extensions/amp-a4a/rtc-publisher-implementation-guide.md
Labels: cla: yes

#29861 Surround <amp-list> with backticks
  extensions/amp-script/amp-script.md
Labels: cla: yes

#29844 📖 Update comment to Resource.getLayoutBox
  src/service/resource.js
Labels: cla: yes

#29868 Sync from Google
  validator/cpp/htmlparser/.bazelrc
  validator/cpp/htmlparser/BUILD
  validator/cpp/htmlparser/README.md
  validator/cpp/htmlparser/WORKSPACE
  validator/cpp/htmlparser/allocator.h
  validator/cpp/htmlparser/allocator_test.cc
  validator/cpp/htmlparser/benchmarks/allocator_benchmarks.cc
  validator/cpp/htmlparser/benchmarks/json_validator_benchmarks.cc
  validator/cpp/htmlparser/css/BUILD
  validator/cpp/htmlparser/css/parse-css.cc
  validator/cpp/htmlparser/defer.h
  validator/cpp/htmlparser/doctype.cc
  validator/cpp/htmlparser/doctype.h
  validator/cpp/htmlparser/doctype_test.cc
  validator/cpp/htmlparser/document.cc
  validator/cpp/htmlparser/document.h
  validator/cpp/htmlparser/fileutil.cc
  validator/cpp/htmlparser/fileutil.h
  validator/cpp/htmlparser/htmldataset_test.cc
  validator/cpp/htmlparser/json/BUILD
  validator/cpp/htmlparser/json/types.h
  validator/cpp/htmlparser/minimal_recursion_test.cc
  validator/cpp/htmlparser/navigator.cc
  validator/cpp/htmlparser/navigator.h
  validator/cpp/htmlparser/navigator_test.cc
  validator/cpp/htmlparser/node.cc
  validator/cpp/htmlparser/node.h
  validator/cpp/htmlparser/node_test.cc
  validator/cpp/htmlparser/parser.cc
  validator/cpp/htmlparser/parser.h
  validator/cpp/htmlparser/parser_test.cc
  validator/cpp/htmlparser/renderer_test.cc
  validator/cpp/htmlparser/strings.cc
  validator/cpp/htmlparser/strings.h
  validator/cpp/htmlparser/testdata/largehtmldoc.html
Labels: WG: caching, cla: yes

#29870 Sync from Google
  validator/cpp/htmlparser/benchmarks/allocator_benchmarks.cc
  validator/cpp/htmlparser/benchmarks/json_validator_benchmarks.cc
  validator/cpp/htmlparser/minimal_recursion_test.cc
  validator/cpp/htmlparser/strings.cc
Labels: WG: caching, cla: yes

#29842 Fix AMP.navigateTo with relative URLs on cache
  src/service/navigation.js
  src/service/url-impl.js
  src/url.js
  test/unit/test-navigation.js
Labels: cla: yes

#29875 amp-script: dont assign onerror if failed to init
  extensions/amp-script/0.1/amp-script.js
Labels: cla: yes

#29877 Validator rollup
  extensions/amp-ad/0.1/test/validator-amp-ad.html
  extensions/amp-ad/0.1/test/validator-amp-ad.out
  extensions/amp-story/validator-amp-story.protoascii
  validator/testdata/amp4email_feature_tests/css_declarations.out
  validator/testdata/amp4email_feature_tests/css_strict.html
  validator/testdata/amp4email_feature_tests/css_strict.out
  validator/validator-css.protoascii
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: cla: yes

#29881 Sync from Google
  validator/cpp/htmlparser/BUILD
Labels: WG: caching, cla: yes

#29883 Small grammar fixes
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#29779 Add begin to render requests to a4a ad
  ads/google/a4a/test/test-utils.js
  ads/google/a4a/utils.js
Labels: cla: yes

#29880 ♻️ [bento][amp-social-share] Minor cleanup of typedefs PR
  extensions/amp-social-share/1.0/social-share-config.js
  extensions/amp-social-share/1.0/social-share.js
  extensions/amp-social-share/1.0/social-share.type.js
Labels: cla: yes

#29885 ✅♻️ [amp-story-player] Clean up tests
  test/unit/test-amp-story-player.js
Labels: cla: yes

#29745 ✨ Allow sticky ads be shown on amp-ad
  3p/ampcontext.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
  src/3p-frame-messaging.js
Labels: cla: yes

#29734 ContextNode: child props and components with auto-cleanup
  src/context/component-hooks.js
  src/context/component-install.js
  src/context/component.js
  src/context/index.js
  src/context/node.js
  src/types.js
  test/unit/context/test-node-components.js
  test/unit/test-types.js
Labels: cla: yes

#29889 Improve 3p ad IntersectionObserver API integration test
  test/fixtures/3p-ad.html
  test/integration/test-amp-ad-3p.js
Labels: cla: yes

#29903 🏗 Switch closure dependency source from `@kristoferbaxter` to `@ampproject`
  build-system/compile/closure-compile.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#29886 🏗 Consolidate GH actions workflow file and add `yarn` caching
  .github/workflows/continuous-integration-workflow.yml
Labels: WG: infra, cla: yes

#29115 🏗 Build and test AMP on Windows
  .github/workflows/continuous-integration-workflow.yml
  build-system/compile/compile.js
  build-system/compile/pre-closure-babel.js
  build-system/pr-check/cross-browser-tests.js
  build-system/tasks/integration.js
  build-system/tasks/karma.conf.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/unit.js
  package.json
  yarn.lock
Labels: WG: infra, cla: yes

#29006 AdvertServe Custom Field Support
  ads/advertserve.js
  ads/advertserve.md
Labels: cla: yes

#29901 ✨ adds LAA support to amp-subscriptions-google
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
  extensions/amp-subscriptions/0.1/entitlement.js
Labels: cla: yes

#29945 Update document for amp context requestResize API
  ads/README.md
Labels: cla: yes

#29951 🏗 Fix failing dist builds
  build-system/pr-check/dist-bundle-size.js
  build-system/test-configs/config.js
  yarn.lock
Labels: cla: yes

#29950 🐛 Fix viewer queueing for responders that don't return promises
  src/service/viewer-impl.js
Labels: cla: yes

#29947 Keep error and expectedError in ESM builds
  build-system/babel-plugins/babel-plugin-transform-dev-methods/index.js
Labels: cla: yes

#29841 amp-script: improved error messages
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
Labels: cla: yes

#29921 ✨ Intent To Implement: Macaw support for amp-ads
  3p/integration.js
  ads/_config.js
  ads/macaw.js
  ads/macaw.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#29953 🏗 Update the class names that visual-diff uses to verify loading is complete
  build-system/tasks/visual-diff/helpers.js
  build-system/tasks/visual-diff/index.js
Labels: cla: yes

#29954 Start storybooks on predefined ports by default
  build-system/tasks/storybook/index.js
Labels: cla: yes

#29944 update nodejs location
  validator/js/nodejs/README.md
  validator/js/nodejs/package.json
Labels: WG: caching, cla: yes

#29943 update gulpjs location
  validator/js/gulpjs/README.md
  validator/js/gulpjs/package.json
Labels: WG: caching, cla: yes

#29960 Validator rollup 514@1095
  extensions/amp-bodymovin-animation/validator-amp-bodymovin-animation.protoascii
  extensions/amp-experiment/1.0/test/validator-amp-experiment.out
  extensions/amp-story/validator-amp-story.protoascii
  validator/js/engine/validator.js
  validator/js/engine/validator_test.js
  validator/testdata/feature_tests/inline_script_length.html
  validator/testdata/feature_tests/inline_script_length.out
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: cla: yes

#29882 ✨ Resize image if too big to make GPU texture
  extensions/amp-story-360/0.1/amp-story-360.js
Labels: WG: stories, cla: yes
