Repository ampproject/amphtml, pull requests merged in 2020-01, with the labels that each got.

#25984 🖍Add animation to story quiz option selection
  extensions/amp-story/1.0/amp-story-quiz.css
Labels: cla: yes

#26189 Allow 2020 in copyright declaration
  build-system/tasks/presubmit-checks.js
Labels: cla: yes

#26192 📖amp-form renders response via templating provided in any descendent
  extensions/amp-form/amp-form.md
Labels: cla: yes

#26067 ♻️ Refactor bind.setState and bind.apply to take in an options bag.
  build-system/externs/amp.extern.js
  extensions/amp-bind/0.1/amp-state.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-bind/0.1/test/test-amp-state.js
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
Labels: cla: yes

#26168 Whitelist amp-list's [is-layout-container] in AMP for Email
  extensions/amp-list/validator-amp-list.protoascii
Labels: Validator: Approved, cla: yes

#26193 Add wg-analytics to cid service owners
  src/OWNERS
  src/service/OWNERS
Labels: cla: yes

#26126 Adding amp-geo url-replacement test coverage
  test/unit/test-url-replacements.js
Labels: cla: yes

#25964 🐛 Fix amp-list race condition
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: cla: yes

#26003 ✨ SwG: Propensity to Subscribe in AMP
  examples/amp-subscriptions.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/subscriptions-propensity.js
  extensions/amp-analytics/0.1/vendors/subscriptions-propensity.json
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Labels: cla: yes

#26115 ✨ Add inactive event types to amp-analytics
  extensions/amp-analytics/0.1/activity-impl.js
  test/unit/test-activity.js
Labels: cla: yes

#26102 Vdo.ai
  3p/integration.js
  ads/_config.js
  ads/vdoai.js
  ads/vdoai.md
  examples/ads.amp.html
Labels: cla: yes

#25517 Cleanup the amp-nested-menu experiment
  extensions/amp-nested-menu/0.1/amp-nested-menu.js
  extensions/amp-nested-menu/0.1/test/test-amp-nested-menu.js
  extensions/amp-sidebar/0.1/amp-sidebar.js
  test/manual/amp-nested-menu/amp-nested-menu.amp.html
  tools/experiments/experiments-config.js
Labels: cla: yes

#26218 Cta-layer typo fix
  examples/amp-story/analytics.html
Labels: cla: yes

#26222 SwG release 0.1.22.88
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#26152 Support Ctrl + Enter to submit a form within a <textarea>
  examples/forms.amp.html
  extensions/amp-form/0.1/amp-form.js
Labels: cla: yes

#26123 🏗 Make Closure import "module" field
  build-system/compile/compile.js
  build-system/compile/single-pass.js
  build-system/compile/sources.js
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  package.json
  src/polyfills/promise.js
  src/purifier.js
  yarn.lock
Labels: cla: yes

#24964 🚮 Update README.md
  README.md
Labels: cla: yes

#26045 📖 Add note in experiments page about blocking third-party cookies
  tools/experiments/experiments.html
  tools/experiments/experiments.js
Labels: cla: yes

#26129 Fix the targetId finder for position-observer in friendly iframe
  build-system/server/server-a4a-template.html
  build-system/server/server-inabox-template.html
  extensions/amp-position-observer/0.1/amp-position-observer.js
  extensions/amp-position-observer/0.1/test-e2e/test-scrollbound-animation.js
  extensions/amp-position-observer/0.1/test-e2e/test-target-id.js
  test/fixtures/e2e/amp-position-observer/target-id.html
Labels: cla: yes

#26202 ♻️ Run prettier on amp.extern.js
  build-system/externs/amp.extern.js
Labels: cla: yes

#26213 Fix analytics examples
  examples/amp-consent/amp-consent-client.html
  examples/amp-consent/amp-consent-geo.html
  examples/amp-consent/amp-consent-server.html
  examples/amp-story-auto-ads.amp.html
  test/manual/amp-analytics-cookie-writer.html
  test/manual/amp-analytics/analytics-fcp.html
  test/manual/amp-analytics/analytics-nav-timing.html
  test/manual/amp-consent/legacy_config_support/amp-consent.amp.html
  test/manual/amp-ima-video.html
  test/manual/analytics-batching.amp.html
Labels: cla: yes

#26208 🐛Fix ad request logic in stories
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
  extensions/amp-story-auto-ads/0.1/story-ad-page.js
  extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
Labels: cla: yes

#26178 📖 Document `amp-nested-menu` usage in `amp-sidebar`
  extensions/amp-nested-menu/amp-nested-menu.md
  extensions/amp-sidebar/0.1/amp-sidebar.md
Labels: cla: yes

#26130 Always return cookie from origin if exist
  src/service/cid-impl.js
Labels: cla: yes

#26227 Add issue number to amp fie experiment cleanup comment
  extensions/amp-position-observer/0.1/amp-position-observer.js
Labels: cla: yes

#25741 ✨ amp-date-picker: allow to hide keyboard shortcuts panel #25608
  examples/date-picker.amp.html
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.html
  extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out
  extensions/amp-date-picker/amp-date-picker.md
  extensions/amp-date-picker/validator-amp-date-picker.protoascii
Labels: Validator: Approved, cla: yes

#26225 ♻️ amp-script: remove support for deprecated development mode opt-in flag
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
Labels: cla: yes

#26230 Validator rollup
  validator/engine/validator_test.js
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#26188 Remove story macros from url-replacments
  src/service/url-replacements-impl.js
  test/unit/test-url-replacements.js
Labels: cla: yes

#26143 Some more comments for amp-list[diffable]
  extensions/amp-list/0.1/amp-list.js
  src/sanitation.js
Labels: cla: yes

#26173 ✨Add HOME and END key support on `amp-nested-menu`
  extensions/amp-nested-menu/0.1/amp-nested-menu.js
  extensions/amp-nested-menu/0.1/test/test-amp-nested-menu.js
  extensions/amp-nested-menu/amp-nested-menu.md
Labels: cla: yes

#26185 ✨AMP-Consent: Add Marfeel to CMPs list
  examples/amp-consent/cmp-vendors.amp.html
  extensions/amp-consent/0.1/cmps.js
  extensions/amp-consent/amp-consent.md
  extensions/amp-consent/cmps/marfeel.md
Labels: cla: yes

#26195 🐛amp-form: Listen to FORM_VALUE_CHANGE to check validity on nested input fields.
  examples/bind/forms.amp.html
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
Labels: cla: yes

#26171 🐛Remask amp-inputmask elements on amp-state change
  examples/masking.amp.html
  extensions/amp-inputmask/0.1/mask-impl.js
  extensions/amp-inputmask/0.1/test/test-mask-impl.js
Labels: cla: yes

#25886 📖 Update release tracking issue template to include LTS checkboxes
  .github/ISSUE_TEMPLATE/release-tracking-issue.md
Labels: cla: yes

#26085 📖 Rewrite Release Schedule doc with new release names/types
  README.md
  contributing/contributing-code.md
  contributing/lts-release.md
  contributing/release-schedule.md
Labels: cla: yes

#24850 ✨ Apester: Added support for ads
  extensions/amp-apester-media/0.1/amp-apester-media.css
  extensions/amp-apester-media/0.1/amp-apester-media.js
  extensions/amp-apester-media/0.1/monetization/companion/display.js
  extensions/amp-apester-media/0.1/monetization/companion/video.js
  extensions/amp-apester-media/0.1/monetization/consent-util.js
  extensions/amp-apester-media/0.1/monetization/index.js
  extensions/amp-apester-media/0.1/test/test-amp-apester-monetization.js
  extensions/amp-apester-media/OWNERS
Labels: cla: yes

#26191 🏗 Add network logging for e2e tests
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/expect.js
  build-system/tasks/e2e/network-logger.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  extensions/amp-ad-exit/0.1/test-e2e/test-amp-ad-exit.js
Labels: cla: yes

#26142 Add e2e tests for amp-fit-text
  extensions/amp-fit-text/0.1/test-e2e/test-amp-fit-text.js
  test/fixtures/e2e/amp-fit-text/amp-fit-text.html
  test/manual/amp-fit-text.amp.html
Labels: cla: yes

#25907 ✨I2I: Add captainmetrics to AMP analytics vendors
  examples/analytics-vendors.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-analytics/0.1/vendors/captainmetrics.js
  extensions/amp-analytics/0.1/vendors/captainmetrics.json
Labels: cla: yes

#26220 Callout vendor update: added consent macros to indexexchange url
  extensions/amp-a4a/0.1/callout-vendors.js
Labels: cla: yes

#26238 Add wg-analytics to url-replacement owners
  src/service/OWNERS
Labels: cla: yes

#26253 📖 Update contributing-code with copy edits
  contributing/contributing-code.md
Labels: cla: yes

#26157 Analytics array variable substitutions
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
  extensions/amp-analytics/amp-analytics.md
Labels: cla: yes

#26277 Remove z-index on flex ad slots by default.
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Labels: cla: yes

#26272 📖 Fix docs typo for amp-ad-custom
  extensions/amp-ad-custom/amp-ad-custom.md
Labels: cla: yes

#26107 filtered invalid AMP email attributes
  builtins/amp-img.md
  extensions/amp-accordion/amp-accordion.md
  extensions/amp-anim/amp-anim.md
  extensions/amp-bind/amp-bind.md
  extensions/amp-carousel/amp-carousel.md
  extensions/amp-form/amp-form.md
  extensions/amp-lightbox/amp-lightbox.md
  extensions/amp-list/amp-list.md
  extensions/amp-sidebar/0.1/amp-sidebar.md
Labels: cla: yes

#26265 🐛 Don't assume window is always available for inabox. It can be already destroyed
  ads/inabox/position-observer.js
Labels: cla: yes

#25999 Move mutator implementations out to a standalone service
  build-system/tasks/presubmit-checks.js
  extensions/amp-access-poool/0.1/poool-impl.js
  extensions/amp-story-auto-ads/0.1/story-ad-button-text-fitter.js
  src/inabox/inabox-mutator.js
  src/inabox/inabox-resources.js
  src/inabox/inabox-services.js
  src/service/core-services.js
  src/service/mutator-impl.js
  src/service/resources-impl.js
  src/service/resources-interface.js
  src/services.js
  test/unit/test-mutator.js
  test/unit/test-resources.js
Labels: cla: yes

#26244 📖 Video click analytics event
  extensions/amp-analytics/amp-video-analytics.md
Labels: cla: yes

#26128 Remove ancestor_origin macro
  build-system/compile/sources.js
  extensions/amp-analytics/0.1/vendors.js
  extensions/amp-viewer-integration/0.1/amp-viewer-integration.js
  extensions/amp-viewer-integration/0.1/test/test-variable-service.js
  extensions/amp-viewer-integration/0.1/variable-service.js
  src/service/url-expander/expander.js
  src/service/url-replacements-impl.js
  src/services.js
  test/unit/test-url-replacements.js
  test/unit/url-expander/test-expander.js
Labels: cla: yes

#26221 ♻️Refactors purifier.js into a class (and npm library)
  .eslintignore
  .gitignore
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/config.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-mustache/0.2/amp-mustache.js
  extensions/amp-mustache/0.2/test/test-amp-mustache.js
  extensions/amp-script/0.1/amp-script.js
  src/purifier.js
  src/purifier/README.md
  src/purifier/noop.js
  src/purifier/package.json
  src/purifier/purifier.js
  src/purifier/rollup.config.js
  src/purifier/sanitation.js
  src/sanitizer.js
  test/unit/test-purifier.js
Labels: cla: yes

#26286 Respects prefers-reduced-motion for content animations.
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.css
Labels: cla: yes

#26278 Replace canonicalUrl with ampdocUrl in Nielsen analytics
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/nielsen.js
  extensions/amp-analytics/0.1/vendors/nielsen.json
Labels: cla: yes

#26276 Setting up code for AmpStoryEmbed viewer
  examples/amp-story/embed.html
  src/amp-story-embed.js
Labels: cla: yes

#26298 amp-mustache-0.2: Remove extra innerHTML workaround
  extensions/amp-mustache/0.2/amp-mustache.js
  extensions/amp-mustache/0.2/test/test-amp-mustache.js
Labels: cla: yes

#26254 📖 Update docs referencing bit.ly/amp-cherry-pick
  .github/ISSUE_TEMPLATE/cherry_pick_template.md
  .github/ISSUE_TEMPLATE/release-tracking-issue.md
  .github/ISSUE_TEMPLATE/release_issue_template.md
Labels: cla: yes

#26299 Update OWNERS to make wg-stories owner of amp-story-embed
  src/OWNERS
Labels: cla: yes

#26285 Viewer get/setDocumentState messaging.
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/conformance-config.textproto
  extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story-viewer-messaging-handler.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#26280 amp-action macro layout error
  extensions/amp-action-macro/0.1/amp-action-macro.js
Labels: cla: yes

#26269 ✅ Implements unit test for `amp-next-page` v2
  extensions/amp-next-page/0.2/service.js
  extensions/amp-next-page/0.2/test/test-amp-next-page.js
  extensions/amp-next-page/0.2/test/test-config.js
  extensions/amp-next-page/0.2/utils.js
Labels: cla: yes

#26267 🏗 Properly retry e2e setup when server fails
  build-system/tasks/e2e/describes-e2e.js
Labels: cla: yes

#25811 add flux as RTC callout vendors
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-a4a/rtc-documentation.md
  extensions/amp-a4a/rtc-publisher-implementation-guide.md
Labels: cla: yes

#26106 ✨Handling sticky, fixed and hidden elements in `amp-next-page` v2
  extensions/amp-next-page/0.2/amp-next-page.css
  extensions/amp-next-page/0.2/page.js
  extensions/amp-next-page/0.2/service.js
  extensions/amp-next-page/0.2/utils.js
  test/manual/amp-next-page/0.2/amp-next-page-v1.element-visibility.html
  test/manual/amp-next-page/0.2/amp-next-page.element-visibility.html
  test/manual/amp-next-page/0.2/articles/element-visibility-1.html
  test/manual/amp-next-page/0.2/articles/element-visibility-2.html
Labels: Validator: Approved, WG: caching, cla: yes

#26099 `amp-next-page-v2`: better manual tests
  examples/visual-tests/iframe-wrapper.html
  extensions/amp-next-page/0.2/amp-next-page.js
  extensions/amp-next-page/0.2/service.js
  test/manual/amp-next-page/0.2/amp-next-page.amp.html
  test/manual/amp-next-page/0.2/articles/article-long.html
  test/manual/amp-next-page/0.2/articles/article-short.html
  test/manual/amp-next-page/0.2/articles/article-with-fixed.html
Labels: cla: yes

#26322 🔥🐛[readmo-amp] code cleanup and bug fix
  ads/readmo.js
  ads/readmo.md
  examples/ads.amp.html
Labels: cla: yes

#26281 Expected error to track AMP_STATE usage
  src/service/url-replacements-impl.js
Labels: cla: yes

#26329 SwG release 0.1.22.89
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#26234 Fix amp-consent flakey e2e
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side-expire-cache.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js
Labels: cla: yes

#26318 🏗 Remove RequestBankE2E in lieu of Selenium's network logging
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/request-bank.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-client-side.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side-expire-cache.js
  extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js
Labels: cla: yes

#26303 Propagate vertical touch events in stories.
  extensions/amp-story/1.0/amp-story-draggable-drawer.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
Labels: cla: yes

#26306 Revert amp-story-access validation.
  extensions/amp-story/0.1/test/validator-amp-story-cta-layer-error.out
  extensions/amp-story/1.0/test/validator-amp-story-access.html
  extensions/amp-story/1.0/test/validator-amp-story-access.out
  extensions/amp-story/1.0/test/validator-amp-story-amp-experiment-error.out
  extensions/amp-story/1.0/test/validator-amp-story-cta-layer-error.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: Validator: Approved, WG: caching, cla: yes

#26309 Fix edge case in isStoryDocument()
  src/utils/story.js
Labels: cla: yes

#26335 Add src/purifier/package.json to renovaterc
  .renovaterc.json
Labels: cla: yes

#26288 🐛 Change method of sending data to Propensity
  examples/amp-subscriptions.amp.html
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/subscriptions-propensity.js
  extensions/amp-analytics/0.1/vendors/subscriptions-propensity.json
  extensions/amp-subscriptions/0.1/amp-subscriptions.js
Labels: cla: yes

#26324 🐛Only expand strings in arrays
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
Labels: cla: yes

#24871 Add payjs for payment extensions to third party
  third_party/aog-payjs/LICENSE
  third_party/aog-payjs/README.amp
  third_party/aog-payjs/payjs.js
Labels: cla: yes

#26100 ♻️ Rename amp-next-page 0.2 -> 1.0
  build-system/compile/bundles.config.js
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-next-page/1.0/amp-next-page.css
  extensions/amp-next-page/1.0/amp-next-page.js
  extensions/amp-next-page/1.0/page.js
  extensions/amp-next-page/1.0/service.js
  extensions/amp-next-page/1.0/test/test-amp-next-page.js
  extensions/amp-next-page/1.0/test/test-config.js
  extensions/amp-next-page/1.0/utils.js
  extensions/amp-next-page/1.0/visibility-observer.js
  src/services.js
  test/manual/amp-next-page/1.0/amp-next-page-v1.element-visibility.html
  test/manual/amp-next-page/1.0/amp-next-page.amp.html
  test/manual/amp-next-page/1.0/amp-next-page.element-visibility.html
  test/manual/amp-next-page/1.0/articles/article-long.html
  test/manual/amp-next-page/1.0/articles/article-short.html
  test/manual/amp-next-page/1.0/articles/article-with-fixed.html
  test/manual/amp-next-page/1.0/articles/element-visibility-1.html
  test/manual/amp-next-page/1.0/articles/element-visibility-2.html
Labels: cla: yes

#26336 🏗 Create webdriver directly
  build-system/tasks/e2e/describes-e2e.js
Labels: cla: yes

#26287 Do not load amp-auto-lightbox on amp-story documents.
  extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
  src/auto-lightbox.js
Labels: cla: yes

#25880 Modify restrictions for in-viewport expansion
  src/service/resources-impl.js
  test/unit/test-mutator.js
Labels: cla: yes

#25969 ✨ Initial PreactBaseElement
  build-system/compile/bundles.config.js
  build-system/compile/check-for-unknown-deps.js
  build-system/compile/compile.js
  build-system/compile/sources.js
  build-system/eslint-rules/no-import.js
  build-system/externs/preact.extern.js
  build-system/tasks/check-types.js
  examples/amp-date-display.amp.html
  extensions/amp-date-display/0.2/amp-date-display.js
  extensions/amp-date-display/0.2/async-render.js
  extensions/amp-date-display/0.2/date-display.js
  extensions/amp-date-display/0.2/render-dom-tree.js
  extensions/amp-date-display/0.2/test/test-amp-date-display.js
  package.json
  src/preact/base-element.js
  src/preact/context.js
  src/preact/index.js
  src/preact/slot.js
  src/preact/utils.js
  src/utils/object.js
  test/_init_tests.js
  test/e2e/test-controller-promise.js
  testing/describes.js
  yarn.lock
Labels: WG: Caching: Triaged, cla: yes

#26297 ♻️ Add module / CJS and types to purifier npm package
  src/purifier/README.md
  src/purifier/package.json
  src/purifier/purifier.d.ts
  src/purifier/rollup.config.js
Labels: cla: yes

#26328 🏗 🐛 Enable `accessControls` checks for JS code (and fix errors)
  ads/google/a4a/line-delimited-response-handler.js
  build-system/compile/compile.js
  extensions/amp-analytics/0.1/instrumentation.js
  extensions/amp-autocomplete/0.1/autocomplete-binding-inline.js
  extensions/amp-autocomplete/0.1/autocomplete-binding-single.js
  extensions/amp-fx-collection/0.1/fx-type.js
  extensions/amp-lightbox-gallery/0.1/utils.js
  extensions/amp-story/0.1/amp-story-share.js
  extensions/amp-story/0.1/amp-story-store-service.js
  extensions/amp-story/0.1/embed-mode.js
  extensions/amp-story/1.0/amp-story-draggable-drawer.js
  extensions/amp-story/1.0/amp-story-embedded-component.js
  extensions/amp-story/1.0/amp-story-share.js
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/embed-mode.js
  extensions/amp-story/1.0/story-analytics.js
  extensions/amp-video-docking/0.1/events.js
  src/iframe-helper.js
  src/log.js
  src/service/origin-experiments-impl.js
  src/service/owners-interface.js
  src/service/resource.js
  src/service/variable-source.js
  src/url-rewrite.js
  src/utils/xhr-utils.js
Labels: WG: infra, cla: yes

#26113 Sync from Google
  validator/htmlparser/LICENSE
  validator/htmlparser/README.md
Labels: WG: caching, cla: yes

#26351 quick format change
  build-system/tasks/extension-generator/extension-doc.template.md
Labels: cla: yes

#26345 Allowlist <col> tag for triple mustache
  extensions/amp-mustache/0.1/test/test-amp-mustache.js
  extensions/amp-mustache/0.2/test/test-amp-mustache.js
  extensions/amp-mustache/amp-mustache.md
  src/purifier/sanitation.js
  test/unit/test-purifier.js
Labels: cla: yes

#26343 Adding attachment state and story progress to getDocumentState API.
  extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js
  extensions/amp-story/1.0/test/test-amp-story-viewer-messaging-handler.js
Labels: cla: yes

#26357 🏗️ Update transform-amp-asserts to leave devAsserts
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/index.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/no-transform-user-assert/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/no-transform-user-assert/options.json
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/no-transform-user-assert/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/no-transform-userAssert/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert/output.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-devAssert/input.js
  build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-devAssert/output.js
Labels: cla: yes

#22849 ✨Add requestCount, maxScrollDepth, and totalTime variables to Chartbeat vendor config
  extensions/amp-analytics/0.1/test/vendor-requests.json
  extensions/amp-analytics/0.1/vendors/chartbeat.js
  extensions/amp-analytics/0.1/vendors/chartbeat.json
Labels: WG: analytics, cla: yes

#26359 🐛 Proxy files from nested folder
  build-system/server/app.js
Labels: cla: yes

#25685 ✨ Add support for data-ad-host-channel to AdSense ads
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-auto-ads/0.1/adsense-network-config.js
  extensions/amp-auto-ads/0.1/test/test-adsense-network-config.js
Labels: cla: yes

#26376 clarified text node behavior
  extensions/amp-timeago/amp-timeago.md
Labels: cla: yes

#26242 ✨Add support for AMP Story Quiz Reaction API calls
  build-system/tasks/presubmit-checks.js
  examples/amp-story/quiz.html
  extensions/amp-story/1.0/amp-story-quiz.js
  extensions/amp-story/1.0/amp-story-request-service.js
  extensions/amp-story/1.0/test/test-amp-story-quiz.js
Labels: cla: yes

#26255 📖 Rename Dev Channel to Experimental Channel in docs and comments
  .github/ISSUE_TEMPLATE/release-tracking-issue.md
  .github/ISSUE_TEMPLATE/release_issue_template.md
  3p/README.md
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
  contributing/release-schedule.md
  examples/analytics-notification-with-geo.amp.html
  extensions/amp-geo/amp-geo.md
  tools/experiments/experiments.js
Labels: cla: yes

#26369 ✨ Add support for `"intrisic"` layout for `<amp-script>`
  extensions/amp-script/amp-script.md
  extensions/amp-script/validator-amp-script.protoascii
Labels: cla: yes

#25530 Update I2I & I2S to reflect new Open Source process
  .github/ISSUE_TEMPLATE/intent-to-implement--i2i-.md
  .github/ISSUE_TEMPLATE/intent-to-ship--i2s-.md
Labels: cla: yes

#26386 Skip amp story affiliate link test
  extensions/amp-story/1.0/test/integration/test-amp-story-affiliate-link.js
Labels: cla: yes

#26392 Revert "Update I2I & I2S to reflect new Open Source process (#25530)"
  .github/ISSUE_TEMPLATE/intent-to-implement--i2i-.md
  .github/ISSUE_TEMPLATE/intent-to-ship--i2s-.md
Labels: cla: yes

#26370 Render video alt and title attributes in vertical rendering mode.
  extensions/amp-story/1.0/amp-story-page.js
Labels: cla: yes

#26393 rephrased reasoning for text node
  extensions/amp-timeago/amp-timeago.md
Labels: cla: yes

#26325 🔥🐛[yahoonativeads-amp] code cleanup and bug fix
  ads/yahoonativeads.js
Labels: cla: yes

#26388 Upgrade WorkerDOM to latest version
  package.json
  yarn.lock
Labels: cla: yes

#26420 Validator rollup
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#26389 ✅Implements unit tests for `amp-next-page` v2 hidden elements
  extensions/amp-next-page/1.0/page.js
  extensions/amp-next-page/1.0/service.js
  extensions/amp-next-page/1.0/test/test-amp-next-page.js
Labels: cla: yes

#26379 🏗🚀 Add a new flag `--core_runtime_only` for `gulp {build | dist | watch}`
  build-system/tasks/build.js
  build-system/tasks/dist.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
  contributing/TESTING.md
Labels: WG: infra, cla: yes

#25830 ♻️ Replaces spinner generator with the generated svg
  extensions/amp-loader/0.1/amp-loader.js
  extensions/amp-loader/0.1/spinner.js
Labels: cla: yes

#26310 Ad wg-analytics as owner of url-expander
  src/service/url-expander/OWNERS
Labels: cla: yes

#26046 amp-script: high trust addendum
  build-system/externs/amp.extern.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
Labels: cla: yes

#26421 Validator rollup (more from last update)
  extensions/amp-mustache/0.2/test/validator-amp-mustache-json.html
  extensions/amp-mustache/0.2/test/validator-amp-mustache-json.out
  extensions/amp-mustache/0.2/test/validator-json-not-in-template.html
  extensions/amp-mustache/0.2/test/validator-json-not-in-template.out
  extensions/amp-subscriptions/validator-amp-subscriptions.protoascii
  validator/engine/validator.js
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#26355 🏗️ Use typeof type where appropriate
  extensions/amp-analytics/0.1/analytics-root.js
  extensions/amp-analytics/0.1/events.js
  extensions/amp-date-picker/0.1/amp-date-picker.js
  extensions/amp-date-picker/0.1/date-picker-common.js
  extensions/amp-date-picker/0.1/date-range-picker.js
  extensions/amp-date-picker/0.1/react-utils.js
  extensions/amp-date-picker/0.1/single-date-picker.js
  extensions/amp-date-picker/0.1/wrappers/maximum-nights.js
  extensions/amp-mustache/0.1/amp-mustache.js
  extensions/amp-mustache/0.2/amp-mustache.js
  src/custom-element.js
  src/log.js
  src/polyfills/custom-elements.js
  src/runtime.js
  src/service/custom-element-registry.js
  src/service/extensions-impl.js
  src/service/template-impl.js
  src/web-components.js
  src/window-interface.js
  testing/describes.js
Labels: cla: yes

#26427 🏗 Remove the `engines` section from all `package.json` files in `amphtml`
  package.json
  validator/gulpjs/package.json
  validator/nodejs/package.json
  validator/package.json
  validator/webui/package.json
Labels: WG: infra, cla: yes

#26431 cl/290808403 Allow span[tooShort] in validation.
  validator/validator-main.protoascii
Labels: WG: caching, cla: yes

#26436 SwG Release 0.1.22.91
  third_party/subscriptions-project/config.js
  third_party/subscriptions-project/swg.js
Labels: cla: yes

#26384 📖 Clarify process for adding dependencies
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
Labels: cla: yes

#26419 🚀 Disable FixedLayer when page is served canonically
  src/service/fixed-layer.js
  test/unit/test-fixed-layer.js
Labels: cla: yes

#26264 🐛Expander: better support of backticks
  src/service/url-expander/expander.js
  test/unit/url-expander/test-expander.js
Labels: cla: yes

#26438 🐛Fix CTA not showing in Firefox
  extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
Labels: cla: yes

#26443 🏗 Migrate deprecated VSCode setting `eslint.autoFixOnSave` to `editor.codeActionsOnSave`
  .vscode/settings.json
Labels: WG: infra, cla: yes

#26256 📖 Update docs and issue templates with 2nd-Monday LTS release schedule
  .github/ISSUE_TEMPLATE/release-tracking-issue.md
  contributing/lts-release.md
  contributing/release-schedule.md
Labels: cla: yes

#26395 Revert "Skip amp story affiliate link test (#26386)"
  extensions/amp-story/1.0/test/integration/test-amp-story-affiliate-link.js
Labels: cla: yes

#26385 add esm AMP_CONFIG field and esm performance identifier
  build-system/externs/amp.extern.js
  src/amp.js
  src/mode-object.js
  src/mode.js
Labels: cla: yes

#26445 Revert "♻️ Lint: include externs"
  .eslintignore
  .eslintrc
  ads/ads.extern.js
  build-system/externs/amp.extern.js
  build-system/externs/dompurify.extern.js
  third_party/moment/moment.extern.js
Labels: cla: yes

#26039 ✨ The Ozone Project: Add RTC endpoint to callout-vendors.js
  extensions/amp-a4a/0.1/callout-vendors.js
  extensions/amp-a4a/rtc-documentation.md
  extensions/amp-a4a/rtc-publisher-implementation-guide.md
Labels: cla: yes

#26296 ✨Implement infinite article loading on `amp-next-page` v2
  extensions/amp-next-page/1.0/amp-next-page.css
  extensions/amp-next-page/1.0/page.js
  extensions/amp-next-page/1.0/service.js
  extensions/amp-next-page/1.0/test/test-amp-next-page.js
  extensions/amp-next-page/1.0/visibility-observer.js
  test/manual/amp-next-page/1.0/amp-next-page.amp.html
Labels: cla: yes

#26455 ✅ Skip broken amp-story-affiliate link test
  extensions/amp-story/1.0/test/integration/test-amp-story-affiliate-link.js
Labels: cla: yes

#26423 ♿ Add `aria-expanded` support to `amp-nested-menu`
  extensions/amp-nested-menu/0.1/amp-nested-menu.js
  extensions/amp-nested-menu/0.1/test/test-amp-nested-menu.js
Labels: cla: yes

#26434 🏗 Add specific RTV opt-in to experiments.html
  tools/experiments/experiments.html
  tools/experiments/experiments.js
Labels: cla: yes

#25663 Add amp-ad support for ByPlay
  3p/integration.js
  ads/_config.js
  ads/byplay.js
  ads/byplay.md
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: cla: yes

#26430 ✨ Launch layoutbox-invalidate-on-scroll
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
Labels: cla: yes

#26459 Disable macro-after-long-task in inabox.
  src/chunk.js
  src/inabox/amp-inabox.js
Labels: cla: yes

#26437 amp-consent remove cmp iframe focus
  extensions/amp-consent/0.1/consent-ui.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  tools/experiments/experiments-config.js
Labels: cla: yes

#26400 amp-script: Create 'fill content' container for responsive/fluid
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test-e2e/test-amp-script.js
  test/fixtures/e2e/amp-script/basic.amp.html
  test/fixtures/e2e/amp-script/basic.js
Labels: cla: yes

#26446 ♻️ Lint: include externs (round 2)
  .eslintignore
  .eslintrc
  ads/ads.extern.js
  build-system/externs/amp.extern.js
  build-system/externs/dompurify.extern.js
  build-system/externs/preact.extern.js
  third_party/moment/moment.extern.js
Labels: cla: yes

#26360 ✨ Launch minimal-wrapper native CEv1
  build-system/global-configs/experiments-config.json
  src/friendly-iframe-embed.js
  src/polyfills.js
  src/polyfills/custom-elements.js
  testing/describes.js
  testing/iframe.js
Labels: cla: yes

#26444 ♻️ amp-script: emit warning if zero height and width.
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
Labels: Component: amp-script, cla: yes

#26026 🏗Add web performance measurement gulp task (WIP)
  .gitignore
  build-system/tasks/extension-helpers.js
  build-system/tasks/lint.js
  build-system/tasks/performance/README.md
  build-system/tasks/performance/cache-documents.js
  build-system/tasks/performance/compile-scripts.js
  build-system/tasks/performance/config.json
  build-system/tasks/performance/helpers.js
  build-system/tasks/performance/index.js
  build-system/tasks/performance/load-config.js
  build-system/tasks/performance/measure-documents.js
  build-system/tasks/performance/package.json
  build-system/tasks/performance/print-report.js
  build-system/tasks/performance/rewrite-script-tags.js
  build-system/tasks/performance/yarn.lock
  build-system/tasks/presubmit-checks.js
  gulpfile.js
Labels: cla: yes

#26333 ✨ Performance Measurement Chrome Extension
  testing/amp-performance-extension/128x128.png
  testing/amp-performance-extension/16x16.png
  testing/amp-performance-extension/48x48.png
  testing/amp-performance-extension/OWNERS
  testing/amp-performance-extension/README.md
  testing/amp-performance-extension/background.js
  testing/amp-performance-extension/manifest.json
  testing/amp-performance-extension/measure.js
Labels: cla: yes

#26464 Fix Story tests.
  extensions/amp-story/1.0/test/test-full-bleed-animations.js
  extensions/amp-story/1.0/test/test-live-story-manager.js
Labels: cla: yes

#26449 Fix border around desktop amp-story-pages.
  extensions/amp-story/1.0/amp-story-desktop-panels.css
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
Labels: cla: yes

#26480 ✨ Start logging AMP URL on SwG Pages
  extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
  extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Labels: cla: yes

#26448 More user friendly errors in layout.js
  src/layout.js
  test/unit/test-layout.js
Labels: cla: yes

#26486 Add perspective(1px) back to desktop amp-story-pages.
  extensions/amp-story/1.0/amp-story-desktop-panels.css
Labels: cla: yes

#26481 Fix syntax error
  extensions/amp-bind/amp-bind.md
Labels: cla: yes

#26479 Revert 'Move mutator implementations out to a standalone service'
  build-system/tasks/presubmit-checks.js
  extensions/amp-access-poool/0.1/poool-impl.js
  extensions/amp-story-auto-ads/0.1/story-ad-button-text-fitter.js
  src/inabox/inabox-mutator.js
  src/inabox/inabox-resources.js
  src/inabox/inabox-services.js
  src/service/core-services.js
  src/service/mutator-impl.js
  src/service/resources-impl.js
  src/service/resources-interface.js
  src/services.js
  test/unit/test-mutator.js
  test/unit/test-resources.js
Labels: cla: yes

#26352 Ensure that fluid slots hidden by media queries do not issue ad requests.
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
Labels: cla: yes

#26290 🐛Log warning when missing URL while attaching shadow doc
  src/multidoc-manager.js
Labels: cla: yes

#26502 ✨amp-nested-menu: allow svg into
  extensions/amp-nested-menu/validator-amp-nested-menu.protoascii
Labels: cla: yes

#26488 Position n+1 story desktop page before positioning attributes are set.
  extensions/amp-story/1.0/amp-story-desktop-panels.css
Labels: cla: yes

#26485 performance: emit timeOrigin w/ polyfill
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: cla: yes
