Repository ampproject/amphtml, pull requests merged in 2021-06, with the labels that each got.

#34628 🏗 Don't duplicate copyright comments in ESM output
  build-system/babel-config/post-closure-config.js
Labels: WG: infra

#34605 🏗 Fix several suppressed type-check errors in `build-system`
  build-system/babel-config/eslint-config.js
  build-system/common/check-package-manager.js
  build-system/common/exec.js
  build-system/global.d.ts
  build-system/task-runner/amp-cli-runner.js
  build-system/task-runner/amp-task-runner.js
  build-system/tasks/dep-check.js
  build-system/tasks/e2e/driver/query-xpath.js
  build-system/tasks/make-extension/index.js
  build-system/tasks/storybook/amp-env/register.js
  build-system/tsconfig.json
Labels: WG: infra

#34553 🖍 Add `min--moz-device-pixel-ratio` and `max--moz-device-pixel-ratio` media features to CSS validator spec
  validator/validator-css.protoascii
Labels: WG: caching

#34640 ⏪ Revert "✨[amp-form] allow `form` attributes for form elements outside…
  build-system/test-configs/forbidden-terms.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/form-dirtiness.js
  extensions/amp-form/0.1/form-validators.js
  extensions/amp-form/0.1/form-verifiers.js
  extensions/amp-form/0.1/test/integration/test-integration-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-form/0.1/test/test-form-dirtiness.js
  extensions/amp-form/amp-form.md
  validator/testdata/feature_tests/forms.html
  validator/testdata/feature_tests/forms.out
  validator/validator-main.protoascii
Labels: WG: caching

#34638 🏗 Shorten copyright comments in esm and non-esm minified output
  build-system/babel-config/post-closure-config.js
  build-system/babel-plugins/babel-plugin-transform-minified-comments/index.js
  build-system/babel-plugins/babel-plugin-transform-minified-comments/test/fixtures/transform/licenses-tabs/input.js
  build-system/babel-plugins/babel-plugin-transform-minified-comments/test/fixtures/transform/licenses-tabs/output.js
  build-system/babel-plugins/babel-plugin-transform-minified-comments/test/fixtures/transform/licenses/input.js
  build-system/babel-plugins/babel-plugin-transform-minified-comments/test/fixtures/transform/licenses/output.js
  build-system/compile/post-closure-babel.js
  third_party/webcomponentsjs/ShadowCSS.js
Labels: WG: infra

#34532 ✨ [amp-story] [amp-story-page-outlink] Element child
  examples/amp-story/attachment.html
  examples/visual-tests/amp-story/amp-story-page-attachment-v2.html
  examples/visual-tests/amp-story/amp-story-page-attachment-v2.js
  extensions/amp-story/1.0/amp-story-open-page-attachment.js
  extensions/amp-story/1.0/amp-story-page-attachment.css
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
  extensions/amp-story/1.0/test/validator-amp-story-amp-experiment-error.out
  extensions/amp-story/1.0/test/validator-amp-story-amp-twitter-error.out
  extensions/amp-story/1.0/test/validator-amp-story-page-attachment.html
  extensions/amp-story/1.0/test/validator-amp-story-page-attachment.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: WG: caching

#34652 Validator Rollup: cl/376942095 Update spec_file_revision comment.
  validator/validator-main.protoascii
Labels: WG: caching

#34655 🏗 Update task-level subpackages before task code can be loaded
  build-system/common/update-packages.js
  build-system/task-runner/amp-task-runner.js
  build-system/tasks/check-build-system.js
Labels: WG: infra

#34653 🏗 Enable type-checking for `build-system/tasks/visual-diff`
  .eslintignore
  build-system/tasks/visual-diff/helpers.js
  build-system/tasks/visual-diff/index.js
  build-system/tasks/visual-diff/package-lock.json
  build-system/tasks/visual-diff/package.json
  build-system/tasks/visual-diff/snippets/freeze-canvas-image.js
  build-system/tasks/visual-diff/snippets/freeze-form-values.js
  build-system/tasks/visual-diff/snippets/iframe-wrapper.js
  build-system/tasks/visual-diff/snippets/remove-amp-scripts.js
  build-system/tsconfig.json
Labels: WG: infra

#34661 🏗 Enable type-checking for `performance` and `get-zindex`
  build-system/global.d.ts
  build-system/tasks/get-zindex/index.js
  build-system/tasks/get-zindex/jscodeshift/collect-zindex.js
  build-system/tasks/performance/ads-handler.js
  build-system/tasks/performance/analytics-handler.js
  build-system/tasks/performance/copy-images.js
  build-system/tasks/performance/helpers.js
  build-system/tasks/performance/index.js
  build-system/tasks/performance/load-config.js
  build-system/tasks/performance/measure-documents.js
  build-system/tasks/performance/rewrite-analytics-tags.js
  build-system/tasks/performance/rewrite-script-tags.js
  build-system/tasks/performance/test-suite.js
  build-system/test-configs/jscodeshift/index.js
  build-system/tsconfig.json
Labels: WG: infra, WG: performance

#34676 🏗 Switch name of renovate bot for owners check
  OWNERS
Labels: WG: infra

#34692 🏗 Fix bot account name for owners check
  OWNERS
Labels: WG: infra

#34695 ❄️ Skip a few flaky tests
  extensions/amp-access/0.1/test/test-amp-access-server-jwt.js
  extensions/amp-story/1.0/test/test-animation.js
Labels: Related to: Flaky Tests

#33753 Adding support for Tail ad service
  3p/integration.js
  3p/vendors/tail.js
  ads/_config.js
  ads/vendors/tail.js
  ads/vendors/tail.md
  examples/amp-ad/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: WG: monetization

#34698 🏗 Use AMP's closure compiler while running validator checks
  validator/build.py
  validator/package-lock.json
  validator/package.json
Labels: WG: caching, WG: infra

#34718 🏗 Enable auto-merge for all devDependency upgrades that pass CI
  .renovaterc.json
Labels: WG: infra

#34721 🏗 Speculative fix for puppeteer disconnections
  build-system/tasks/visual-diff/index.js
Labels: Related to: Flaky Tests, WG: infra

#34723 🏗 Do not import task modules during `amp --help`
  build-system/task-runner/amp-task-runner.js
  build-system/tasks/analytics-vendor-configs.js
  build-system/tasks/ava.js
  build-system/tasks/babel-plugin-tests.js
  build-system/tasks/build.js
  build-system/tasks/bundle-size/index.js
  build-system/tasks/caches-json.js
  build-system/tasks/check-analytics-vendors-list.js
  build-system/tasks/check-asserts.js
  build-system/tasks/check-build-system.js
  build-system/tasks/check-exact-versions.js
  build-system/tasks/check-invalid-whitespaces.js
  build-system/tasks/check-links.js
  build-system/tasks/check-owners.js
  build-system/tasks/check-renovate-config.js
  build-system/tasks/check-sourcemaps.js
  build-system/tasks/check-types.js
  build-system/tasks/check-video-interface-list.js
  build-system/tasks/cherry-pick.js
  build-system/tasks/clean.js
  build-system/tasks/codecov-upload.js
  build-system/tasks/compile-jison.js
  build-system/tasks/coverage-map/index.js
  build-system/tasks/css/index.js
  build-system/tasks/default-task.js
  build-system/tasks/dep-check.js
  build-system/tasks/dev-dashboard-tests.js
  build-system/tasks/dist.js
  build-system/tasks/e2e/index.js
  build-system/tasks/firebase.js
  build-system/tasks/get-zindex/index.js
  build-system/tasks/integration.js
  build-system/tasks/lint.js
  build-system/tasks/make-extension/index.js
  build-system/tasks/markdown-toc/index.js
  build-system/tasks/performance-urls.js
  build-system/tasks/performance/index.js
  build-system/tasks/pr-check.js
  build-system/tasks/prepend-global/index.js
  build-system/tasks/prettify.js
  build-system/tasks/release/index.js
  build-system/tasks/serve.js
  build-system/tasks/server-tests.js
  build-system/tasks/storybook/index.js
  build-system/tasks/sweep-experiments/index.js
  build-system/tasks/test-report-upload.js
  build-system/tasks/unit.js
  build-system/tasks/validate-html-fixtures.js
  build-system/tasks/validator.js
  build-system/tasks/visual-diff/index.js
  package.json
Labels: WG: infra

#34745 📖 Create a yaml issue template for a Bento component tracker
  .github/ISSUE_TEMPLATE/bento-component-tracker.yml
Labels: Related to: Documentation, WG: bento

#34751 amp-lightbox-gallery: fix incorrect unlayout
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Labels: Component: amp-lightbox-gallery, Type: Bug, WG: performance

#34787 typechecking: remove pride as not compatible with rest of strategy
  build-system/tasks/check-types.js
Labels: WG: performance

#34755 ✨ [Amp story] Scaffold desktop one panel experiment
  build-system/test-configs/config.js
  examples/amp-story/amp-story-desktop-one-panel.html
  examples/visual-tests/amp-story/amp-story-desktop-one-panel.html
  extensions/amp-story/1.0/amp-story-desktop-one-panel.css
  extensions/amp-story/1.0/amp-story-store-service.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/test/test-amp-story.js
  test/visual-diff/visual-tests
Labels: WG: stories

#34862 🏗 Refinements to renovate config
  .renovaterc.json
Labels: WG: infra

#34813 Refactor: move getRealChildNodes and getRealChildren to core
  builtins/amp-layout/amp-layout.js
  docs/building-an-amp-extension.md
  extensions/amp-accordion/0.1/amp-accordion.js
  extensions/amp-audio/0.1/amp-audio.js
  extensions/amp-call-tracking/0.1/test/test-amp-call-tracking.js
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-consent/0.1/amp-consent.js
  extensions/amp-fit-text/0.1/amp-fit-text.js
  extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
  extensions/amp-image-slider/0.1/amp-image-slider.js
  extensions/amp-image-viewer/0.1/amp-image-viewer.js
  extensions/amp-lightbox/0.1/amp-lightbox.js
  extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-sidebar/0.1/amp-sidebar.js
  extensions/amp-sidebar/0.2/amp-sidebar.js
  extensions/amp-sidebar/1.0/base-element.js
  extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
  extensions/amp-truncate-text/0.1/amp-truncate-text.js
  src/base-element.js
  src/core/dom/layout.js
  src/core/dom/query.js
  src/custom-element.js
  src/preact/base-element.js
  test/unit/core/dom/test-query.js
  test/unit/test-custom-element.js
Labels: Type: Refactoring, WG: performance

#34769 Validator Rollup
  extensions/amp-cache-url/0.1/test/validator-amp-cache-url.html
  extensions/amp-cache-url/0.1/test/validator-amp-cache-url.out
  extensions/amp-cache-url/validator-amp-cache-url.protoascii
  validator/build.py
  validator/js/engine/htmlparser-interface.js
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: WG: caching

#34798 ✨ Add Bento versions (1.0) to validator specs for `amp-twitter` and `amp-facebook-like`
  extensions/amp-facebook-like/1.0/test/validator-amp-facebook-like.html
  extensions/amp-facebook-like/1.0/test/validator-amp-facebook-like.out
  extensions/amp-facebook-like/validator-amp-facebook-like.protoascii
  extensions/amp-twitter/1.0/test/validator-amp-twitter.html
  extensions/amp-twitter/1.0/test/validator-amp-twitter.out
  extensions/amp-twitter/validator-amp-twitter.protoascii
Labels: WG: bento, WG: caching

#34906 ✅ `amp-story-desktop-one-panel` Rename visual test and new test for small square screen
  test/visual-diff/visual-tests
Labels: P1: High Priority, WG: stories

#34913 validator test, update comments
  validator/testdata/feature_tests/lts_extension_without_lts_runtime.html
  validator/testdata/feature_tests/lts_extension_without_lts_runtime.out
  validator/testdata/feature_tests/lts_runtime_and_extensions.html
  validator/testdata/feature_tests/lts_runtime_and_extensions.out
Labels: WG: caching

#34869 Enable amp-ad sticky type top/bottom
  extensions/amp-ad/0.1/test/validator-amp-ad.html
  extensions/amp-ad/0.1/test/validator-amp-ad.out
  extensions/amp-ad/validator-amp-ad.protoascii
Labels: WG: caching

#34970 🏗 Move `exclude` out of `compilerOptions` in `tsconfig.json`
  tsconfig.json
Labels: WG: infra

#34964 ✨ [amp-render] validation changes for layout="container"
  extensions/amp-render/1.0/test/validator-amp-render.html
  extensions/amp-render/1.0/test/validator-amp-render.out
  extensions/amp-render/validator-amp-render.protoascii
  validator/js/nodejs/package-lock.json
Labels: WG: caching

#34941 🚮 Remove examiner.js binary
  build-system/compile/bundles.config.js
  build-system/tasks/check-types.js
  build-system/tasks/helpers.js
  src/examiner/examiner.js
  src/mode.js
  src/validator-integration.js
Labels: Type: Refactoring, WG: performance

#34828 ✨Bento `amp-soundcloud`
  build-system/compile/bundles.config.extensions.json
  extensions/amp-soundcloud/1.0/amp-soundcloud.js
  extensions/amp-soundcloud/1.0/base-element.js
  extensions/amp-soundcloud/1.0/component.js
  extensions/amp-soundcloud/1.0/component.type.js
  extensions/amp-soundcloud/1.0/storybook/Basic.amp.js
  extensions/amp-soundcloud/1.0/storybook/Basic.js
  extensions/amp-soundcloud/1.0/storybook/converter.js
  extensions/amp-soundcloud/1.0/test/test-amp-soundcloud.js
  extensions/amp-soundcloud/1.0/test/validator-amp-soundcloud.html
  extensions/amp-soundcloud/1.0/test/validator-amp-soundcloud.out
  extensions/amp-soundcloud/validator-amp-soundcloud.protoascii
Labels: WG: caching

#33999 ✨ [`amp-tiktok`] Add validation rules for the amp-tiktok component.
  examples/amp-tiktok.amp.html
  extensions/amp-tiktok/0.1/test/validator-amp-tiktok.html
  extensions/amp-tiktok/0.1/test/validator-amp-tiktok.out
  extensions/amp-tiktok/validator-amp-tiktok.protoascii
Labels: WG: caching

#34924 Move building outlink attachment to layoutcallback.
  extensions/amp-story/1.0/amp-story-page-attachment.js
Labels: P1: High Priority, WG: stories

#35045 🏗 Fix errors emitted by the VSCode typescript plugin
  tsconfig.json
Labels: WG: infra

#34770 amp-layout: extract buildDOM #compiler
  builtins/amp-layout/amp-layout.js
Labels: WG: performance

#35070 performance-impls: LCP should use startTime
  extensions/amp-viewer-integration/TICKEVENTS.md
  src/core/constants/enums.js
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: Related to: Performance, WG: performance

#35023 🚮 Assist.js: Remove assistjs extension and all relevant libraries.
  build-system/compile/bundles.config.extensions.json
  build-system/compile/compile.js
  build-system/compile/sources.js
  build-system/test-configs/config.js
  build-system/test-configs/dep-check-config.js
  examples/amp-google-assistant-assistjs.amp.html
  extensions/amp-google-assistant-assistjs/0.1/amp-google-assistant-assistjs.css
  extensions/amp-google-assistant-assistjs/0.1/amp-google-assistant-assistjs.js
  extensions/amp-google-assistant-assistjs/0.1/amp-google-assistant-inline-suggestion-bar.js
  extensions/amp-google-assistant-assistjs/0.1/amp-google-assistant-voice-bar.js
  extensions/amp-google-assistant-assistjs/0.1/amp-google-assistant-voice-button.js
  extensions/amp-google-assistant-assistjs/0.1/assistjs-config-service.js
  extensions/amp-google-assistant-assistjs/0.1/assistjs-frame-service.js
  extensions/amp-google-assistant-assistjs/0.1/test/test-amp-google-assistant-assistjs.js
  extensions/amp-google-assistant-assistjs/0.1/test/validator-amp-google-assistant-assistjs.html
  extensions/amp-google-assistant-assistjs/0.1/test/validator-amp-google-assistant-assistjs.out
  extensions/amp-google-assistant-assistjs/OWNERS
  extensions/amp-google-assistant-assistjs/amp-google-assistant-assistjs.md
  extensions/amp-google-assistant-assistjs/validator-amp-google-assistant-assistjs.protoascii
  src/service/index.js
  third_party/closure-responding-channel/LICENSE
  third_party/closure-responding-channel/README.amp
  third_party/closure-responding-channel/calcdeps.sh
  third_party/closure-responding-channel/closure-bundle.js
  third_party/closure-responding-channel/closure-wrapper.js
  third_party/closure-responding-channel/compile.sh
  third_party/closure-responding-channel/manifest.MF
Labels: WG: caching
