Repository ampproject/amphtml, pull requests merged in 2021-03, with the labels that each got.

#32879 use esbuild native watch mode for unminified builds
  build-system/tasks/helpers.js
Labels: WG: infra, WG: performance

#32891 🏗 Replace `browserify` in tests with `esbuild`
  .circleci/config.yml
  .gitignore
  build-system/babel-config/helpers.js
  build-system/babel-config/test-config.js
  build-system/common/browserify-cache.js
  build-system/common/compute-karma-cache-hash.js
  build-system/externs/amp.extern.js
  build-system/server/app.js
  build-system/server/new-server/transforms/transform.ts
  build-system/server/typescript-compile.js
  build-system/tasks/clean.js
  build-system/tasks/dep-check.js
  build-system/tasks/helpers.js
  build-system/tasks/integration.js
  build-system/tasks/report-test-status.js
  build-system/tasks/runtime-test/helpers-unit.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/serve.js
  build-system/tasks/unit.js
  build-system/test-configs/config.js
  build-system/test-configs/karma.conf.js
  contributing/TESTING.md
  extensions/amp-analytics/0.1/test/test-vendors.js
  extensions/amp-date-picker/0.1/dates-list.js
  extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
  package-lock.json
  package.json
  test/_init_tests.js
  test/unit/test-3p.js
  test/unit/test-shadow-embed.js
  third_party/inputmask/build.sh
  third_party/react-dates/build.sh
  third_party/react-dates/debug.sh
Labels: WG: infra

#33021 🏗 Fix Karma's watch mode for `esbuild` transforms
  build-system/server/app.js
  build-system/tasks/helpers.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/test-configs/karma.conf.js
Labels: WG: infra

#32969 ♿ [Story a11y] Improve screen reader output for interactive components
  extensions/amp-story-interactive/0.1/amp-story-interactive-abstract.js
  extensions/amp-story-interactive/0.1/amp-story-interactive-binary-poll.js
  extensions/amp-story-interactive/0.1/amp-story-interactive-poll.js
  extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.js
  extensions/amp-story-interactive/0.1/amp-story-interactive-results.js
Labels: Related to: Accessibility, WG: stories

#33072 🏗 Lazy-require babel configs
  babel.config.js
  build-system/babel-config/empty-config.js
  build-system/tasks/presubmit-checks.js
Labels: WG: infra

#33075 🐛 Check validator initialization in nodejs tool
  validator/js/nodejs/index.js
Labels: WG: caching

#33078 🐛 Check validator initialization in webui tool
  validator/js/webui/@polymer/webui-mainpage/webui-mainpage.html
Labels: WG: caching

#33108 🏗 Expand instructions for dealing with stale PR branches
  .circleci/check_config.sh
Labels: WG: infra

#32779 ♿ TetraLogical: AMP Stories accessibility review / documentation
  extensions/amp-story-360/0.1/amp-story-360.md
  extensions/amp-story-interactive/amp-story-interactive.md
  extensions/amp-story/amp-story-grid-layer.md
  extensions/amp-story/amp-story.md
  extensions/amp-video/0.1/amp-video.md
  extensions/amp-video/amp-video.md
Labels: Related to: Accessibility, Related to: Documentation

#33115 🏗🚮 Clean up `amphtml` root-level dependencies
  .renovaterc.json
  build-system/tasks/check-renovate-config.js
  build-system/tasks/compile-jison.js
  build-system/tasks/serve.js
  build-system/tasks/sweep-experiments/index.js
  package-lock.json
  package.json
  third_party/react-dates/build.sh
  third_party/react-dates/debug.sh
Labels: WG: infra

#33088 ✅ amp-video-iframe: Remove poster requirement
  extensions/amp-video-iframe/0.1/amp-video-iframe.js
  extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
  extensions/amp-video-iframe/0.1/test/validator-amp-video-iframe.html
  extensions/amp-video-iframe/0.1/test/validator-amp-video-iframe.out
  extensions/amp-video-iframe/amp-video-iframe.md
  extensions/amp-video-iframe/validator-amp-video-iframe.protoascii
  validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.out
Labels: WG: caching

#33222 🏗 Restore `package-lock.json` to `lockfileVersion = 1`
  package-lock.json
Labels: WG: infra

#33223 🏗 Ensure up-to-date and clean `package-lock.json` before running any CI job
  build-system/pr-check/checks.js
  build-system/pr-check/ci-job.js
  build-system/pr-check/cross-browser-tests.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/experiment-build.js
  build-system/pr-check/module-build.js
  build-system/pr-check/module-tests.js
  build-system/pr-check/nomodule-build.js
  build-system/pr-check/nomodule-tests.js
  build-system/pr-check/npm-checks.js
  build-system/pr-check/performance-tests.js
  build-system/pr-check/unit-tests.js
  build-system/pr-check/unminified-build.js
  build-system/pr-check/unminified-tests.js
  build-system/pr-check/visual-diff-tests.js
Labels: WG: infra

#33216 🐛 Sync amp-autocomplete test output file
  extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out.cpponly
Labels: Component: amp-autocomplete

#33232 Revert "amp-list: Fix Bind.rescan vs. diffing race condition"
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
Labels: Component: amp-list

#33264 🏗 Read merge commit only if file was created
  .circleci/fetch_merge_commit.sh
Labels: WG: infra

#33275 🐛Unlaunch no signing
  build-system/global-configs/experiments-const.json
Labels: P1: High Priority, WG: monetization

#33027 🏗 Rewrite closure compiler code without file streaming
  build-system/babel-config/pre-closure-config.js
  build-system/compile/check-for-unknown-deps.js
  build-system/compile/closure-compile.js
  build-system/compile/compile.js
  build-system/compile/debug-compilation-lifecycle.js
  build-system/compile/helpers.js
  build-system/compile/post-closure-babel.js
  build-system/compile/pre-closure-babel.js
  build-system/compile/sanitize.js
  build-system/compile/sources.js
  build-system/tasks/check-types.js
  build-system/tasks/dist.js
  build-system/tasks/extension-helpers.js
  package-lock.json
  package.json
Labels: WG: infra

#33077 ✨ [Story bookend] Created amp-story-social-share
  examples/amp-story/share.html
  extensions/amp-story/1.0/amp-story-request-service.js
  extensions/amp-story/1.0/amp-story-share.js
  extensions/amp-story/1.0/test/test-amp-story-request-service.js
  extensions/amp-story/1.0/test/validator-amp-story-amp-experiment-error.out
  extensions/amp-story/1.0/test/validator-amp-story-cta-layer-error.out
  extensions/amp-story/1.0/test/validator-amp-story-social-share.html
  extensions/amp-story/1.0/test/validator-amp-story-social-share.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: WG: caching

#33236 build-system: lazily build jison parsers + ww.js
  build-system/server/app.js
  build-system/server/lazy-build.js
  build-system/tasks/build.js
  build-system/tasks/compile-jison.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
  build-system/test-configs/config.js
Labels: WG: infra, WG: performance

#30190 Add accidentally removed comment back in to ampshared.css
  css/ampshared.css
Labels: cla: yes

#33298 🏗 Add support for minified lazy build + watch
  build-system/compile/compile.js
  build-system/compile/pre-closure-babel.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
Labels: WG: infra

#33306 🏗 Remove root `package.json` dependency on `0x`
  package-lock.json
  package.json
Labels: WG: infra

#33295 performance-impl: use fcp and ofv entryTime when summing for cls-fcp and cls-ofv
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: WG: performance

#33314 🚀 🚀 🚀 build-system: use fs for babel-cache 🚀 🚀 🚀
  build-system/common/esbuild-babel.js
  build-system/tasks/clean.js
Labels: WG: infra, WG: performance

#33334 build-system: fix unminified watch mode.
  build-system/compile/pre-closure-babel.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
Labels: Type: Bug, WG: infra

#29846 🖍 Fix rendering of noscript fallbacks in optimized AMP pages
  css/Z_INDEX.md
  css/ampshared.css
Labels: cla: yes

#33366 esbuild cache invalidation: add argv to optionsHash
  build-system/common/esbuild-babel.js
Labels: Type: Bug

#33375 🏗 Automatically update `npm` packages if needed before any task is run
  amp.js
  build-system/tasks/amp-task-runner.js
  build-system/tasks/build.js
  build-system/tasks/check-links.js
  build-system/tasks/check-types.js
  build-system/tasks/css/index.js
  build-system/tasks/default-task.js
  build-system/tasks/dist.js
  build-system/tasks/lint.js
  build-system/tasks/prettify.js
  build-system/tasks/update-packages.js
Labels: WG: infra

#33372 Validator rollup
  validator/testdata/transformed_feature_tests/module_nomodule.html
  validator/testdata/transformed_feature_tests/module_nomodule.out
  validator/validator-main.protoascii
Labels: WG: caching

#33376 🏗🚀 Speed up `amp` task loading by lazy-requiring large dependencies
  build-system/compile/closure-compile.js
  build-system/compile/typescript.js
  build-system/tasks/bundle-size/index.js
  build-system/tasks/css/jsify-css.js
  build-system/tasks/performance/copy-images.js
  build-system/tasks/performance/rewrite-analytics-tags.js
  build-system/tasks/performance/rewrite-script-tags.js
Labels: WG: infra

#33389 🏗 Report results for experiment tests
  build-system/common/ci.js
  build-system/pr-check/experiment-tests.js
Labels: WG: infra

#33385 🏗 Clean up / replace lazy `require` statements in `build-system/`
  build-system/compile/typescript.js
  build-system/tasks/amp-task-runner.js
  build-system/tasks/bundle-size/index.js
  build-system/tasks/css/jsify-css.js
  build-system/tasks/helpers.js
  build-system/tasks/performance/copy-images.js
  build-system/tasks/performance/index.js
  build-system/tasks/performance/rewrite-analytics-tags.js
  build-system/tasks/performance/rewrite-script-tags.js
  package-lock.json
  package.json
Labels: WG: infra

#33380 📖🐛 [amp-story] [amp-story-360] Fix typo in 360 docs
  extensions/amp-story-360/0.1/amp-story-360.md
Labels: WG: stories

#33383 ✨[amp-analytics] New macro $CALC to perform basic arithmetic on analytics variables and macros.
  extensions/amp-analytics/0.1/test/test-variables.js
  extensions/amp-analytics/0.1/variables.js
  spec/amp-var-substitutions.md
Labels: WG: components

#33419 🏗 Fix folder creation for test reports
  build-system/tasks/e2e/mocha-custom-json-reporter.js
Labels: WG: infra

#33262 resources: remove intersect-resources experiment
  build-system/global-configs/canary-config.json
  build-system/global-configs/prod-config.json
  src/inabox/inabox-resources.js
  src/service/mutator-impl.js
  src/service/resource.js
  src/service/resources-impl.js
  src/service/resources-interface.js
  src/service/viewport/viewport-binding-def.js
  src/service/viewport/viewport-binding-ios-embed-wrapper.js
  src/service/viewport/viewport-binding-natural.js
  src/service/viewport/viewport-impl.js
  src/service/viewport/viewport-interface.js
  test/integration/test-visibility-states.js
  test/unit/test-resource.js
  test/unit/test-resources.js
  tools/experiments/experiments-config.js
Labels: WG: performance

#33441 🖍 Fix visible UI that mentions "Accelerated Mobile Pages"
  ads/google/a4a/docs/RTBExchangeGuide.md
  extensions/amp-access/0.1/amp-login-done.html
  tools/experiments/experiments.html
  validator/js/webui/index.html
Labels: WG: infra

#33371 ✨ Add cpp test of validator into pr checks
  .circleci/config.yml
  .circleci/install_validator_dependencies.sh
  amp.js
  build-system/pr-check/build-targets.js
  build-system/pr-check/validator-tests.js
  build-system/tasks/validator.js
  validator/.gitignore
Labels: WG: caching

#33447 🏗 Clean up all `gulp` style error throwing in build-system
  build-system/global.d.ts
  build-system/server/app-utils.js
  build-system/tasks/check-exact-versions.js
  build-system/tasks/check-sourcemaps.js
  build-system/tasks/cherry-pick.js
  build-system/tasks/helpers.js
  build-system/tasks/pr-check.js
  build-system/tasks/server-tests.js
  build-system/tasks/storybook/index.js
Labels: WG: infra

#33452 🏗 Optimize root-level and task-level package installation while running `amp` tasks
  amp.js
  build-system/common/update-packages.js
  build-system/common/utils.js
  build-system/pr-check/ci-job.js
  build-system/tasks/amp-task-runner.js
  build-system/tasks/coverage-map/index.js
  build-system/tasks/e2e/index.js
  build-system/tasks/performance/index.js
  build-system/tasks/release/index.js
  build-system/tasks/storybook/index.js
  build-system/tasks/visual-diff/index.js
Labels: WG: infra

#33465 🏗 Replace all mentions of `build cop` with `build on-duty`
  contributing/DEVELOPING.md
  contributing/build-on-duty.md
Labels: Related to: Documentation, WG: infra

#33469 🏗 Make warning levels for `check-types` more granular
  build-system/compile/closure-compile.js
  build-system/compile/compile.js
  build-system/tasks/check-types.js
Labels: WG: infra

#33505 🏗 Consolidate arg processing and file globbing / ignoring across `amp` tasks
  build-system/common/utils.js
  build-system/tasks/lint.js
  build-system/tasks/prettify.js
Labels: WG: infra

#33531 🏗 Clean up visual-diff install code
  build-system/tasks/visual-diff/index.js
Labels: WG: infra

#33533 🏗 Replace `fancy-log` with a native nodejs implementation
  babel.config.js
  build-system/common/logging.js
  build-system/tasks/visual-diff/helpers.js
  build-system/test-configs/forbidden-terms.js
  package-lock.json
  package.json
  validator/js/gulpjs/index.js
Labels: WG: caching, WG: infra

#33328 🚮 [Story sidebar] Added warning to deprecate amp-sidebar in stories
  extensions/amp-sidebar/validator-amp-sidebar.protoascii
  extensions/amp-story/1.0/test/validator-amp-story-sidebar.out
Labels: WG: caching

#33475 Brid player support for carousel
  examples/brid-player.amp.html
  extensions/amp-brid-player/0.1/amp-brid-player.js
  extensions/amp-brid-player/0.1/test/test-amp-brid-player.js
  extensions/amp-brid-player/0.1/test/validator-amp-brid-player.html
  extensions/amp-brid-player/0.1/test/validator-amp-brid-player.out
  extensions/amp-brid-player/amp-brid-player.md
  extensions/amp-brid-player/validator-amp-brid-player.protoascii
Labels: WG: caching

#33535 Make `build-system` code main-branch-agnostic
  build-system/common/ci.js
  build-system/common/git.js
  build-system/common/main-branch.js
  build-system/common/utils.js
  build-system/compile/internal-version.js
  build-system/pr-check/build-targets.js
  build-system/pr-check/npm-checks.js
  build-system/pr-check/utils.js
  build-system/pr-check/visual-diff-tests.js
  build-system/tasks/bundle-size/index.js
  build-system/tasks/check-exact-versions.js
  build-system/tasks/check-links.js
  build-system/tasks/cherry-pick.js
  build-system/tasks/prepend-global/index.js
  build-system/tasks/runtime-test/helpers-unit.js
  build-system/tasks/visual-diff/index.js
Labels: WG: infra

#30589 ⏪ Revert "Fix `amp-imgur` embed format (#28143)"
  examples/amp-imgur.amp.html
  extensions/amp-imgur/0.1/amp-imgur.js
  extensions/amp-imgur/0.1/test/test-amp-imgur.js
  extensions/amp-imgur/amp-imgur.md
Labels: cla: yes
