Repository ampproject/amphtml, pull requests merged in 2021-12, with the labels that each got.

#36980 update validator to allow script[amp-story-dvh-polyfill] for transformed documents
  validator/js/engine/validator_test.js
  validator/testdata/transformed_feature_tests/amp-story-css-link.html
  validator/testdata/transformed_feature_tests/amp-story-css-link.out
  validator/validator-main.protoascii
Labels: WG: caching

#37094 fix comment for dvh polyfill spec
  validator/validator-main.protoascii
Labels: WG: caching

#37070 🐛 Add `hidden` attribute to `bento-lightbox` and `bento-sidebar` to prevent FOUC
  extensions/amp-lightbox/1.0/README.md
  extensions/amp-lightbox/1.0/example/index.html
  extensions/amp-sidebar/1.0/README.md
  extensions/amp-sidebar/1.0/example/index.html
  test/fixtures/e2e/bento/lightbox.html
Labels: WG: bento

#36889 build-system: freeze all latestVersions.
  build-system/compile/bundles.config.extensions.json
  build-system/compile/bundles.config.js
  build-system/compile/bundles.legacy-latest-versions.js
  build-system/compile/compile-wrappers.js
  build-system/server/lazy-build.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/make-extension/index.js
  build-system/tasks/make-extension/test/test.js
  docs/building-a-bento-amp-extension.md
  docs/building-an-amp-extension.md
Labels: WG: infra

#37119 Update nonce propagation to retrieve value via property
  src/core/dom/element.nonce.extern.js
  src/core/dom/index.js
  src/service/extension-script.js
  src/validator-integration.js
  test/unit/test-validator-integration.js
Labels: Type: Bug, WG: performance

#37147 Validator rollup
  extensions/amp-carousel/validator-amp-carousel.protoascii
  extensions/amp-live-list/0.1/test/validator-amp-live-list.html
  extensions/amp-live-list/0.1/test/validator-amp-live-list.out
  extensions/amp-story-player/0.1/test/validator-amp-story-player-error.out
  extensions/amp-story-player/0.1/test/validator-amp-story-player-img-error.out
  extensions/amp-story/1.0/test/validator-amp-story-reference-point.html
  extensions/amp-story/1.0/test/validator-amp-story-reference-point.out
  validator/js/engine/validator_test.js
  validator/testdata/feature_tests/img.html
  validator/testdata/feature_tests/img.out
  validator/testdata/feature_tests/leaks.html
  validator/testdata/feature_tests/leaks.out
  validator/testdata/feature_tests/leaks.out.cpponly
  validator/testdata/feature_tests/noscript.html
  validator/testdata/feature_tests/noscript.out
  validator/validator-main.protoascii
Labels: WG: caching

#37120 ✨ [amp-story-captions] Support container layout in amp-story-captions component
  examples/amp-story/amp-story-captions.html
  examples/amp-story/captions-for-container-layout.vtt
  extensions/amp-story-captions/0.1/amp-story-captions.js
  extensions/amp-story-captions/0.1/amp-story-captions.md
  extensions/amp-story-captions/0.1/track-renderer.js
  extensions/amp-story-captions/validator-amp-story-captions.protoascii
Labels: WG: caching

#37183 Remove 'version: "latest"'.
  docs/component-validator-rules.md
Labels: WG: caching

#37178 amp-carousel-0.2: fix keyboard navigation.
  extensions/amp-carousel/0.1/carousel-controls.js
  extensions/amp-carousel/0.2/amp-carousel.js
  extensions/amp-carousel/0.2/test/test-type-slides.js
Labels: Component: amp-carousel

#37207 core/window/interface: small ie support removal
  src/core/window/interface.js
Labels: WG: performance

#37216 core tsconfig: update target
  src/core/tsconfig.json
Labels: Type: Bug, WG: infra

#37228 root tsconfig: disable typecheck to save VS Code
  tsconfig.json
Labels: Type: Bug

#37237 ✨ Remove Bento experiments from `amp-wordpress-embed`
  extensions/amp-wordpress-embed/1.0/amp-wordpress-embed.js
Labels: WG: components, WG: bento

#37149 🖍 [amp story shopping] Prevent shopping tag dot and image from shrinking
  examples/visual-tests/amp-story/amp-story-shopping.html
  extensions/amp-story-shopping/0.1/amp-story-shopping-tag.css
Labels: P1: High Priority, Type: Feature Request, WG: stories

#37002 ✨ Add missing `aria-modal` to global attributes in validator spec
  validator/validator-main.protoascii
Labels: WG: caching

#36898 ⏪ Remove `bento_supported_version` from `amp-render` validator spec
  extensions/amp-render/validator-amp-render.protoascii
Labels: WG: caching
