Repository ampproject/amphtml, pull requests merged in 2021-01, with the labels that each got.

#30429 ✨ Pass consent to amp-brightcove iframe src
  extensions/amp-brightcove/0.1/amp-brightcove.js
  extensions/amp-brightcove/0.1/test/test-amp-brightcove.js
  extensions/amp-brightcove/amp-brightcove.md
Labels: cla: yes

#31800 amp-video: Add intrinsic to supported_layouts
  extensions/amp-video/validator-amp-video.protoascii
Labels: WG: caching

#31655 ♻️ Move amp-story example files under amp-story/
  examples/amp-story.0.1.amp.html
  examples/amp-story/amp-story-360.html
  examples/amp-story/amp-story-auto-ads-payload.json
  examples/amp-story/amp-story-auto-ads.html
  examples/amp-story/amp-story-panning-media.html
  examples/amp-story/img/Equirectangular_projection_SW.jpg
  examples/amp-story/img/NASA_VR_360_Astronaut_Training_Space_Walk_Clip.mp4
  examples/amp-story/img/SeanDoran-Quela-sol1462-edited_ver2-sm.jpg
  examples/amp-story/img/conservatory-coords.jpg
  examples/amp-story/img/nasa_training_poster.jpg
  extensions/amp-story-360/0.1/test/test-amp-story-360.js
  extensions/amp-story-panning-media/0.1/test/test-amp-story-panning-media.js
Labels: P3: When Possible, WG: stories

#31656 📦 Upgrade colors dependency in NodeJS validator
  validator/js/nodejs/package-lock.json
  validator/js/nodejs/package.json
Labels: WG: caching

#31842 Skip flaky carousel test
  extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
Labels: Related to: Flaky Tests

#31829 update amphtml-validator to v.1.0.34
  validator/js/nodejs/README.md
  validator/js/nodejs/package.json
Labels: WG: caching

#31839 🖍 Remove underline from story swipe up
  examples/visual-tests/amp-story/amp-story-page-attachment.html
  examples/visual-tests/amp-story/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story-page-attachment.css
Labels: WG: stories

#31825 activation-tracker: keydown as activation event
  extensions/amp-script/0.1/user-activation-tracker.js
Labels: Component: amp-script, WG: performance

#31868 Update building-an-amp-extension.md
  contributing/building-an-amp-extension.md
Labels: Related to: Documentation, WG: caching

#31867 Update to Validator Chrome Extension
  validator/js/chromeextension/content_script.js
  validator/js/chromeextension/manifest.json
Labels: WG: caching

#31723 ✨ Adds Adnuntius support to amp-ad.
  3p/integration.js
  ads/_config.js
  ads/adnuntius.js
  ads/adnuntius.md
  examples/ads.amp.esm.html
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
  validator/testdata/feature_tests/ads.html
  validator/testdata/feature_tests/ads.out
Labels: WG: caching

#31726 🚮 Removes Cxense Display/EAS support, which no longer exists
  3p/integration.js
  ads/_config.js
  ads/eas.js
  ads/eas.md
  examples/ads.amp.esm.html
  examples/ads.amp.html
  extensions/amp-ad/amp-ad.md
  validator/testdata/feature_tests/ads.html
  validator/testdata/feature_tests/ads.out
Labels: WG: caching

#31922 Validator rollup
  extensions/amp-video/validator-amp-video.protoascii
  validator/validator-main.protoascii
Labels: WG: caching

#31940 🏗 Standardize names of CI jobs and build artifact files
  .travis.yml
  build-system/pr-check/bundle-size.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/local-tests.js
  build-system/pr-check/module-build.js
  build-system/pr-check/module-tests.js
  build-system/pr-check/nomodule-tests.js
  build-system/pr-check/performance-tests.js
  build-system/pr-check/unminified-build.js
  build-system/pr-check/unminified-tests.js
  build-system/pr-check/utils.js
  build-system/pr-check/visual-diff-tests.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/report-test-status.js
Labels: WG: infra

#31939 🏗 Modernize / fix test logging during CI builds
  build-system/tasks/e2e/index.js
  build-system/tasks/e2e/mocha-dots-reporter.js
  build-system/tasks/karma.conf.js
  build-system/tasks/presubmit-checks.js
Labels: WG: infra

#31946 🏗 Assorted Validator fixes
  build-system/tasks/clean.js
  build-system/tasks/validator.js
  validator/build.py
  validator/package-lock.json
  validator/package.json
Labels: WG: caching, WG: infra

#31731 📖 Document how to build a Bento AMP extension
  contributing/building-a-bento-amp-extension.md
Labels: WG: caching

#31947 🏗 Create `gulp init-bento-component` task to generate new Bento component boilerplate
  .eslintignore
  .prettierrc
  build-system/tasks/extension-generator/bento/OWNERS
  build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/OWNERS
  build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/__component_name_hyphenated__.js
  build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/__component_name_hyphenated__.jss.js
  build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/__component_name_hyphenated__.type.js
  build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/amp-__component_name_hyphenated__.css
  build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/amp-__component_name_hyphenated__.js
  build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.amp.js
  build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.js
  build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/test/test-amp-__component_name_hyphenated__.js
  build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/amp-__component_name_hyphenated__.md
  build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/validator-amp-__component_name_hyphenated__.protoascii
  build-system/tasks/extension-generator/bento/index.js
  build-system/tasks/extension-generator/index.js
  build-system/tasks/presubmit-checks.js
Labels: WG: bento

#31753 Convert ad iframes to get initialIntersection async
  3p/3d-gltf/viewer.js
  build-system/global-configs/canary-config.json
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/name-frame-renderer.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/test-name-frame-renderer.js
  extensions/amp-ad-custom/0.1/test/test-amp-ad-custom.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-ad/0.1/legacy-ad-intersection-observer-host.js
  extensions/amp-ad/0.1/test/test-legacy-ad-intersection-observer-host.js
  src/3p-frame.js
  src/iframe-attributes.js
  test/integration/test-amp-ad-3p.js
  test/unit/3p/test-3p-frame.js
Labels: WG: performance

#31975 🏗 Updates to VM setup during CI
  .travis.yml
  build-system/pr-check/utils.js
Labels: WG: infra

#31927 ✨[Story layouts] Responsiveness presets for grid-layers
  extensions/amp-story/1.0/amp-story-grid-layer.js
  extensions/amp-story/1.0/test/test-amp-story-grid-layer.js
Labels: WG: stories

#31961 🏗 Use ci-agnostic helper in test reporting and display error message on failure
  build-system/tasks/test-report-upload.js
Labels: cla: yes

#31982 🏗 Update CI build / job identifiers
  build-system/common/ci.js
  build-system/pr-check/utils.js
  build-system/tasks/pr-deploy-bot-utils.js
  build-system/tasks/test-report-upload.js
Labels: WG: infra

#31981 🏗 Propagate errors while building / launching storybook
  build-system/tasks/storybook/index.js
Labels: WG: infra

#27430 ✨Update to amp-3q-player
  examples/3q-player.amp.html
  extensions/amp-3q-player/0.1/amp-3q-player.js
  extensions/amp-3q-player/0.1/test/test-amp-3q-player.js
Labels: cla: yes

#32021 🏗 Expose and fix silent failure in ava tests
  build-system/tasks/ava.js
  build-system/tasks/get-zindex/test-2.css
Labels: WG: infra

#32009 Increase inline style to 1500 bytes for Transformed AMP
  validator/validator-css.protoascii
Labels: WG: caching

#32044 🏗 PR-check logging cleanup
  build-system/pr-check/build-targets.js
  build-system/pr-check/bundle-size.js
  build-system/pr-check/checks.js
  build-system/pr-check/cross-browser-tests.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/experiment-tests.js
  build-system/pr-check/module-build.js
  build-system/pr-check/module-tests.js
  build-system/pr-check/nomodule-build.js
  build-system/pr-check/nomodule-tests.js
  build-system/pr-check/npm-checks.js
  build-system/pr-check/performance-tests.js
  build-system/pr-check/unminified-build.js
  build-system/pr-check/unminified-tests.js
  build-system/pr-check/utils.js
  build-system/pr-check/validator-tests.js
  build-system/pr-check/visual-diff-tests.js
  build-system/tasks/pr-check.js
  build-system/tasks/pr-deploy-bot-utils.js
  build-system/tasks/presubmit-checks.js
Labels: WG: infra

#32059 🏗 Fixes to PR-check logic
  build-system/pr-check/bundle-size.js
  build-system/pr-check/checks.js
  build-system/pr-check/cross-browser-tests.js
  build-system/pr-check/module-build.js
  build-system/pr-check/nomodule-build.js
  build-system/pr-check/nomodule-tests.js
  build-system/pr-check/unminified-build.js
  build-system/pr-check/unminified-tests.js
  build-system/pr-check/utils.js
  build-system/pr-check/validator-tests.js
  build-system/tasks/pr-deploy-bot-utils.js
Labels: WG: infra

#32051 🏗 Configure CircleCI
  .circleci/config.yml
  build-system/common/check-package-manager.js
  build-system/common/ci.js
  build-system/compile/compile.js
  build-system/pr-check/bundle-size.js
  build-system/tasks/report-test-status.js
  build-system/test-configs/config.js
Labels: WG: infra

#32071 Validator rollup
  validator/validator-main.protoascii
Labels: WG: caching

#32018 🏗 Update PR deploy URLs
  build-system/tasks/pr-deploy-bot-utils.js
Labels: WG: infra

#32073 🏗 Fix bundle-size check for Travis builds
  build-system/pr-check/bundle-size.js
Labels: WG: infra

#32086 ❄️ Skip flaky carousel E2E test
  extensions/amp-base-carousel/0.1/test-e2e/test-advance.js
  extensions/amp-base-carousel/1.0/test-e2e/test-advance.js
Labels: Related to: Flaky Tests

#32093 🏗 Minor bugfixes for `gulp prettify`
  .prettierignore
  build-system/tasks/prettify.js
  build-system/test-configs/config.js
Labels: WG: infra

#32095 🏗 Test the merge commit with `master` during CircleCI builds
  .circleci/config.yml
  .circleci/fetch_merge_commit.sh
Labels: WG: infra

#32102 🏗 Stop running performance tests until they are optimized / fixed
  .circleci/config.yml
Labels: WG: infra, WG: performance

#32088 🏗 Add an owners file for `.circleci/`
  .circleci/OWNERS
Labels: WG: infra

#32089 🏗 Add branch filtering for CircleCI builds
  .circleci/config.yml
Labels: WG: infra

#32105 ❄️ Skip flaky iframe test
  test/unit/test-iframe-helper.js
Labels: WG: components

#32090 🏗 Upgrade to `dompurify` 2.2.6
  package-lock.json
  package.json
  src/purifier/package-lock.json
  src/purifier/package.json
Labels: WG: infra

#32108 ❄️ Mark visual test `amphtml-ads: friendly iframe static` as flaky
  test/visual-diff/visual-tests
Labels: Related to: Flaky Tests, WG: monetization

#32083 🏗 Switch build artifact unique identifier from build ID to commit SHA
  build-system/pr-check/utils.js
  build-system/tasks/pr-deploy-bot-utils.js
Labels: WG: infra

#32116 🏗 Fix commit SHA retrieval for push and PR builds on all CI services
  build-system/common/ci.js
  build-system/pr-check/utils.js
  build-system/tasks/codecov-upload.js
  build-system/tasks/pr-deploy-bot-utils.js
Labels: WG: infra

#32058 🏗 Replace `lolex` v5 with `@sinonjs/fake-timers` v7
  extensions/amp-access/0.1/test/test-amp-access-client.js
  extensions/amp-access/0.1/test/test-amp-access-iframe.js
  extensions/amp-access/0.1/test/test-amp-access-server-jwt.js
  extensions/amp-access/0.1/test/test-amp-access-server.js
  extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
  extensions/amp-ad/0.1/test/test-concurrent-load.js
  extensions/amp-analytics/0.1/test/test-cookie-writer.js
  extensions/amp-analytics/0.1/test/test-events.js
  extensions/amp-analytics/0.1/test/test-requests.js
  extensions/amp-analytics/0.1/test/test-transport.js
  extensions/amp-bind/0.1/test/integration/test-bind-impl.js
  extensions/amp-consent/0.1/test/test-consent-policy-manager.js
  extensions/amp-consent/0.1/test/test-consent-ui.js
  extensions/amp-date-display/0.1/test/test-amp-date-display.js
  extensions/amp-date-picker/0.1/test/integration/test-integration-amp-date-picker-actions.js
  extensions/amp-date-picker/0.1/test/integration/test-integration-dates-attributes.js
  extensions/amp-date-picker/0.1/test/integration/test-integration-maximum-nights.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker-bind.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker-state.js
  extensions/amp-date-picker/0.1/test/test-amp-date-picker.js
  extensions/amp-date-picker/0.1/test/test-wrapper-maximum-nights.js
  extensions/amp-image-lightbox/0.1/test/test-amp-image-lightbox.js
  extensions/amp-nested-menu/0.1/test/test-amp-nested-menu.js
  extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
  extensions/amp-sidebar/0.2/test/test-amp-sidebar.js
  extensions/amp-story/1.0/test/test-media-performance-metrics-service.js
  package-lock.json
  package.json
  test/unit/test-3p-environment.js
  test/unit/test-ad-cid.js
  test/unit/test-cache-cid-api.js
  test/unit/test-cid.js
  test/unit/test-cookies.js
  test/unit/test-custom-element.js
  test/unit/test-impression.js
  test/unit/test-jank-meter.js
  test/unit/test-loader.js
  test/unit/test-mutator.js
  test/unit/test-performance.js
  test/unit/test-position-observer.js
  test/unit/test-preconnect.js
  test/unit/test-render-delaying-services.js
  test/unit/test-resources.js
  test/unit/test-yield.js
Labels: WG: infra

#32118 🏗 Print closure concurrency during `gulp dist`
  build-system/compile/compile.js
  build-system/tasks/dist.js
Labels: WG: infra

#32125 🏗 Remove npm publishing boilerplate from `src/purifier`
  .renovaterc.json
  src/purifier/OWNERS
  src/purifier/README.md
  src/purifier/package-lock.json
  src/purifier/package.json
Labels: WG: infra

#32130 🏗 Replace org-level context with project-level env vars on CircleCI
  .circleci/config.yml
Labels: WG: infra

#32140 🏗♻️ Refactor and simplify all CI job executor scripts
  build-system/pr-check/bundle-size.js
  build-system/pr-check/checks.js
  build-system/pr-check/ci-job.js
  build-system/pr-check/cross-browser-tests.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/experiment-tests.js
  build-system/pr-check/module-build.js
  build-system/pr-check/module-tests.js
  build-system/pr-check/nomodule-build.js
  build-system/pr-check/nomodule-tests.js
  build-system/pr-check/performance-tests.js
  build-system/pr-check/unit-tests.js
  build-system/pr-check/unminified-build.js
  build-system/pr-check/unminified-tests.js
  build-system/pr-check/validator-tests.js
  build-system/pr-check/visual-diff-tests.js
Labels: WG: infra

#32151 🏗 Prepare to move AMP's CI off Travis
  .codecov.yml
  .prettierrc
  .vscode/settings.json
  METRICS.md
  README.md
  build-system/server/app-index/header-links.js
  build-system/tasks/pr-deploy-bot-utils.js
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/config.js
  contributing/DEVELOPING.md
  contributing/TESTING.md
  contributing/buildcop.md
  contributing/getting-started-e2e.md
  contributing/release-schedule.md
  extensions/amp-3d-gltf/0.1/test/test-amp-3d-gltf.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
  extensions/amp-iframe/0.1/amp-iframe.js
  test/integration/test-amphtml-ads.js
  test/unit/test-mutator.js
Labels: WG: infra

#32146 🏗 Refactor and simplify build target logic during CI builds
  build-system/pr-check/build-targets.js
  build-system/pr-check/bundle-size.js
  build-system/pr-check/checks.js
  build-system/pr-check/ci-job.js
  build-system/pr-check/cross-browser-tests.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/module-build.js
  build-system/pr-check/module-tests.js
  build-system/pr-check/nomodule-build.js
  build-system/pr-check/nomodule-tests.js
  build-system/pr-check/unit-tests.js
  build-system/pr-check/unminified-build.js
  build-system/pr-check/unminified-tests.js
  build-system/pr-check/validator-tests.js
  build-system/pr-check/visual-diff-tests.js
  build-system/tasks/pr-check.js
  build-system/tasks/report-test-status.js
Labels: WG: infra

#32162 🏗 Clean up CircleCI config, move some setup steps into separate files
  .circleci/config.yml
  .circleci/fetch_merge_commit.sh
  .circleci/setup-storage.sh
  build-system/test-configs/hosts
Labels: WG: infra

#32156 🏗 Enable `gulp` log coloring during CI
  build-system/pr-check/utils.js
  gulpfile.js
Labels: WG: infra

#32179 🏗 Report bundle-size / PR-deploy from Travis until the switch to CircleCI actually happens
  build-system/pr-check/bundle-size.js
  build-system/tasks/pr-deploy-bot-utils.js
Labels: WG: infra

#32174 Optimize CircleCI builds with a mix of `xlarge` and `large` VMs
  .circleci/config.yml
Labels: WG: infra

#32193 🏗 Report test statuses from Travis until it is turned off
  build-system/tasks/report-test-status.js
Labels: WG: infra

#31873 🐛Update validator-amp-base-carousel.protoascii with 'controls' attribute. Resolves 31872
  extensions/amp-base-carousel/validator-amp-base-carousel.protoascii
Labels: WG: caching, WG: components

#32227 🏗 Add the missing `DOCS` build target to the `Targets` enum in `build-targets.js`
  build-system/pr-check/build-targets.js
Labels: WG: infra

#32182 InOb: Force polyfill for WebKit document=root
  src/polyfillstub/intersection-observer-stub.js
  src/service.js
  test/unit/polyfills/test-intersection-observer.js
Labels: WG: performance

#32253 🏗 Run the exact version check on all `package.json` files in the repo
  build-system/pr-check/build-targets.js
  build-system/tasks/check-exact-versions.js
  third_party/amp-toolbox-cache-url/package.json
  validator/js/webui/package-lock.json
  validator/js/webui/package.json
Labels: WG: infra

#32257 🏗 Optimize the running of various checks during local dev and CI builds
  build-system/pr-check/build-targets.js
  build-system/pr-check/bundle-size.js
  build-system/pr-check/checks.js
  build-system/pr-check/cross-browser-tests.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/module-build.js
  build-system/pr-check/module-tests.js
  build-system/pr-check/nomodule-build.js
  build-system/pr-check/nomodule-tests.js
  build-system/pr-check/unminified-build.js
  build-system/pr-check/unminified-tests.js
  build-system/pr-check/visual-diff-tests.js
  build-system/tasks/pr-check.js
  build-system/tasks/report-test-status.js
Labels: WG: infra

#32276 🏗 CircleCI config fixes
  .circleci/config.yml
  .circleci/fetch_merge_commit.sh
Labels: WG: infra

#32262 Add validation rules for aspect-ratio support via SSR
  css/ampshared.css
  test/unit/test-layout.js
  validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.html
  validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.out
  validator/testdata/transformed_feature_tests/server_side_rendering.html
  validator/testdata/transformed_feature_tests/server_side_rendering.out
  validator/validator-css.protoascii
  validator/validator-main.protoascii
Labels: WG: caching

#32295 🏗 Cache Karma's babel transforms during CircleCI builds
  .circleci/config.yml
Labels: WG: infra

#32290 🏗 Consolidate CircleCI VM setup steps into separate scripts
  .circleci/config.yml
  .circleci/fetch_merge_commit.sh
  .circleci/install_dependencies.sh
  .circleci/setup_storage.sh
Labels: WG: infra

#32297 🏗 Reorganize browserify caching code
  build-system/common/browserify-cache.js
  build-system/common/logging.js
  build-system/tasks/e2e/mocha-dots-reporter.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/test-configs/karma.conf.js
Labels: WG: infra

#32307 🏗 Fix bug in build target discovery logic
  build-system/pr-check/build-targets.js
Labels: WG: infra

#32312 🏗 Update CircleCI hash for `.karma-cache`
  .circleci/config.yml
  .gitignore
  build-system/common/browserify-cache.js
  build-system/common/compute-karma-cache-hash.js
  build-system/tasks/clean.js
Labels: WG: infra
