Repository ampproject/amphtml, pull requests merged in 2021-08, with the labels that each got.

#35466 build-system: improve terser/esbuild integration
  build-system/tasks/helpers.js
Labels: Type: Refactoring, WG: infra

#29290 AMP.goBack: update documentation
  docs/spec/amp-actions-and-events.md
Labels: cla: yes

#35494 ✅ buildDom: add tests for amp-fit-text and amp-layout
  extensions/amp-fit-text/0.1/amp-fit-text.js
  extensions/amp-fit-text/0.1/test/test-amp-fit-text.js
  src/builtins/amp-layout/amp-layout.js
  test/unit/builtins/test-amp-layout.js
Labels: Type: Testing, WG: performance

#35477 babel: teach amp mode transformer about #core/mode
  build-system/babel-plugins/babel-plugin-amp-mode-transformer/index.js
  build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/no-transform/input.js
  build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/no-transform/output.js
  build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/transform/input.js
  build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/transform/output.mjs
Labels: WG: performance

#35329 🐛 Fix `value_regex` for `amp-tiktok@data-src` to allow repeating digits and a TikTok URL
  extensions/amp-tiktok/0.1/test/validator-amp-tiktok.out
  extensions/amp-tiktok/validator-amp-tiktok.protoascii
Labels: WG: caching, WG: components

#35518 Validator rollup
  validator/js/engine/validator_test.js
  validator/validator-main.protoascii
Labels: WG: caching

#35298 core mode: add version()
  3p/integration-lib.js
  ads/google/a4a/utils.js
  build-system/test-configs/dep-check-config.js
  build-system/test-configs/forbidden-terms.js
  extensions/amp-ad-network-valueimpression-impl/0.1/amp-ad-network-valueimpression-impl.js
  extensions/amp-addthis/0.1/amp-addthis.js
  extensions/amp-analytics/0.1/iframe-transport.js
  extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
  src/3p-frame.js
  src/amp-shadow.js
  src/amp.js
  src/core/mode/index.js
  src/core/mode/version.js
  src/iframe-attributes.js
  src/inabox/amp-inabox.js
  src/log.js
  src/mode.js
  src/runtime.js
  src/service/url-replacements-impl.js
Labels: Type: Refactoring, WG: performance

#35500 amp-carousel: Remove BaseSlides
  extensions/amp-carousel/0.1/base-slides.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/0.1/test/test-slidescroll-slides.js
Labels: Type: Refactoring, WG: components

#35448 ✨ 🍱 Bento `amp-brightcove`
  build-system/compile/bundles.config.extensions.json
  build-system/compile/sources.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-brightcove/0.1/amp-brightcove.js
  extensions/amp-brightcove/1.0/amp-brightcove.css
  extensions/amp-brightcove/1.0/amp-brightcove.js
  extensions/amp-brightcove/1.0/base-element.js
  extensions/amp-brightcove/1.0/component.js
  extensions/amp-brightcove/1.0/component.type.js
  extensions/amp-brightcove/1.0/storybook/Basic.amp.js
  extensions/amp-brightcove/1.0/storybook/Basic.js
  extensions/amp-brightcove/1.0/test/test-amp-brightcove.js
  extensions/amp-brightcove/1.0/test/test-component.js
  extensions/amp-brightcove/1.0/test/validator-amp-brightcove.html
  extensions/amp-brightcove/1.0/test/validator-amp-brightcove.out
  extensions/amp-brightcove/brightcove-api.js
  extensions/amp-brightcove/validator-amp-brightcove.protoascii
  extensions/amp-video/1.0/video-iframe.js
Labels: WG: caching

#35533 🐛 performance-impl: origin should use value directly from PO
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: WG: performance

#34848 Allow `amp-autocomplete` in email format by default
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-autocomplete/amp-autocomplete.md
  validator/testdata/amp4email_feature_tests/amp-autocomplete.html
  validator/testdata/amp4email_feature_tests/amp-autocomplete.out
  validator/validator-main.protoascii
Labels: WG: caching

#35455 🏗 Move macOS testing from GH Actions to CircleCI
  .circleci/config.yml
  .github/workflows/cross-browser-tests.yml
  build-system/pr-check/safari-tests.js
Labels: WG: infra

#35497 ✨ Allow <amp-render> within story pages and story page attachments
  extensions/amp-story/1.0/test/validator-amp-story-amp-render.html
  extensions/amp-story/1.0/test/validator-amp-story-amp-render.out
  extensions/amp-story/validator-amp-story.protoascii
Labels: WG: caching

#35592 delete babel plugin `prune-namespace`
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/index.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/errors/computed-identifier-property/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/errors/computed-identifier-property/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/errors/computed-number-property/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/errors/computed-number-property/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/errors/computed-string-property/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/errors/computed-string-property/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/errors/deep-computed-identifier/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/errors/deep-computed-identifier/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/double-assignment/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/double-assignment/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/double-assignment/output.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/other-namespace/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/other-namespace/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/other-namespace/output.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/underscore-namespace/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/underscore-namespace/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/underscore-namespace/output.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/using-other-namespace/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/using-other-namespace/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/unused-properties/using-other-namespace/output.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/deep-access/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/deep-access/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/deep-access/output.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/prototypes/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/prototypes/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/prototypes/output.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/simple/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/simple/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/simple/output.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/update-expression/input.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/update-expression/options.json
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/fixtures/used-properties/update-expression/output.js
  build-system/babel-plugins/babel-plugin-transform-prune-namespace/test/index.js
Labels: WG: performance

#35594 🏗 Move Firefox testing from GH Actions to CircleCI
  .circleci/config.yml
  .github/workflows/cross-browser-tests.yml
  build-system/pr-check/firefox-tests.js
Labels: WG: infra

#35639 🐛 [Amp story] Null check on screen.orientation
  extensions/amp-story/1.0/amp-story.js
Labels: P0: Drop Everything, WG: stories

#35646 🏗 Fix CircleCI config check so it works with `.git` caching
  .circleci/config.yml
  .circleci/initialize_repo.sh
Labels: WG: infra

#35671 ✅ Remove a couple unnecessary `async`s from `amp-bind` e2e test
  test/e2e/test-amp-bind-brightcove.js
Labels: Related to: Flaky Tests

#35419 🚀 ♻️ build-system: merge unminified and vendor codepath
  build-system/tasks/3p-vendor-helpers.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
Labels: Type: Refactoring

#35679 Allow `i-amphtml-sizer[slot="i-amphtml-svc"]` on transformed documents.
  validator/testdata/transformed_feature_tests/amp-img.html
  validator/testdata/transformed_feature_tests/amp-img.out
  validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.html
  validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.out
  validator/validator-main.protoascii
Labels: WG: caching

#35698 eslint rule: no-deep-destructuring should handle ArrayPattern
  build-system/babel-config/import-resolver.js
  build-system/eslint-rules/no-deep-destructuring.js
  build-system/release-tagger/create-release.js
  build-system/tasks/release/index.js
  src/preact/component/3p-frame.js
Labels: WG: performance

#35703 🏗 Use a different process to pre-build AMP while running tests
  build-system/common/utils.js
  build-system/tasks/build.js
  build-system/tasks/dist.js
  build-system/tasks/firebase.js
  build-system/tasks/performance/compile-scripts.js
Labels: WG: infra

#35690 🐛 amp-mode-transformer: Only resolve development mode for esm builds
  build-system/babel-plugins/babel-plugin-amp-mode-transformer/index.js
  build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/nomodule/output.mjs
Labels: WG: performance

#35706 🏗 Rename `--compiled` to `--minified` in AMP testing tasks
  build-system/common/utils.js
  build-system/compile/build-constants.js
  build-system/pr-check/browser-tests.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/experiment-e2e-tests.js
  build-system/pr-check/experiment-integration-tests.js
  build-system/pr-check/ie-tests.js
  build-system/pr-check/module-tests.js
  build-system/pr-check/nomodule-tests.js
  build-system/server/amp4test.js
  build-system/server/app-index/settings.js
  build-system/server/app-utils.js
  build-system/server/app.js
  build-system/server/lazy-build.js
  build-system/server/new-server/transforms/sxg/sxg-transform.ts
  build-system/server/new-server/transforms/sxg/test/sxg-env-compiled/options.json
  build-system/server/new-server/transforms/sxg/test/sxg-env/options.json
  build-system/server/new-server/transforms/sxg/test/sxg-query-param/options.json
  build-system/server/new-server/transforms/transform.ts
  build-system/server/new-server/transforms/utilities/option-set.ts
  build-system/server/test/app-utils.test.js
  build-system/tasks/default-task.js
  build-system/tasks/dist.js
  build-system/tasks/e2e/index.js
  build-system/tasks/firebase.js
  build-system/tasks/helpers.js
  build-system/tasks/integration.js
  build-system/tasks/performance/cache-documents.js
  build-system/tasks/pr-check.js
  build-system/tasks/pr-deploy-bot-utils.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/serve.js
  build-system/tasks/visual-diff/index.js
  docs/testing.md
  test/integration/test-amphtml-ads.js
  testing/iframe.js
Labels: WG: infra

#35713 🏗 Fix unminified build on Windows
  build-system/tasks/compile-jison.js
  build-system/tasks/extension-helpers.js
Labels: WG: infra

#35723 🏗 Use asynchronous `globby` API wherever possible
  build-system/server/typescript-compile.js
  build-system/tasks/analytics-vendor-configs.js
  build-system/tasks/bundle-size/index.js
  build-system/tasks/check-exact-versions.js
  build-system/tasks/compile-jison.js
  build-system/tasks/css/index.js
  build-system/tasks/dist.js
  build-system/tasks/get-zindex/index.js
  build-system/tasks/markdown-toc/index.js
  build-system/tasks/markdown-toc/test/test.js
  build-system/tasks/presubmit.js
  build-system/tasks/server-tests.js
Labels: WG: infra

#35714 Allow private click measurement attributes
  validator/js/engine/validator_test.js
  validator/testdata/feature_tests/a_private_click_measurement.html
  validator/testdata/feature_tests/a_private_click_measurement.out
  validator/validator-main.protoascii
Labels: WG: caching

#35724 🏗 Remove lint and presubmit checks for AMP copyright notice
  .eslintrc.js
  build-system/common/LICENSE-TEMPLATE.txt
  build-system/tasks/presubmit.js
  build-system/test-configs/config.js
  package-lock.json
  package.json
Labels: WG: infra

#35731 🏗 Matrixify `amp build | dist` checks on GH actions
  .github/workflows/cross-platform-builds.yml
  build-system/pr-check/cross-platform-builds.js
Labels: WG: infra

#35734 remove notice from validator/js/... files
  validator/js/chromeextension/README.md
  validator/js/chromeextension/background.html
  validator/js/chromeextension/background.js
  validator/js/chromeextension/build_extension.sh
  validator/js/chromeextension/content_script.js
  validator/js/chromeextension/package_extension.sh
  validator/js/chromeextension/polymer-extension-toolbar.html
  validator/js/chromeextension/polymer.html
  validator/js/chromeextension/popup-validator-not-present.html
  validator/js/chromeextension/popup-validator.html
  validator/js/engine/amp4ads-parse-css.js
  validator/js/engine/amp4ads-parse-css_test.js
  validator/js/engine/definitions.js
  validator/js/engine/htmlparser-interface.js
  validator/js/engine/htmlparser.js
  validator/js/engine/htmlparser_test.js
  validator/js/engine/json-testutil.js
  validator/js/engine/keyframes-parse-css.js
  validator/js/engine/keyframes-parse-css_test.js
  validator/js/engine/parse-css.js
  validator/js/engine/parse-css_test.js
  validator/js/engine/parse-srcset.js
  validator/js/engine/parse-srcset_test.js
  validator/js/engine/parse-url.js
  validator/js/engine/parse-url_test.js
  validator/js/engine/tokenize-css.js
  validator/js/engine/validator-in-browser.js
  validator/js/engine/validator.js
  validator/js/engine/validator_test.js
  validator/js/gulpjs/index.js
  validator/js/gulpjs/sample/gulpfile.js
  validator/js/gulpjs/test/validate.js
  validator/js/nodejs/cli.js
  validator/js/nodejs/index.js
  validator/js/nodejs/index_test.js
  validator/js/webui/@polymer/amphtml-editor/amphtml-editor.html
  validator/js/webui/@polymer/ampproject-toolbar/ampproject-toolbar.html
  validator/js/webui/@polymer/webui-errorlist/webui-errorlist.html
  validator/js/webui/@polymer/webui-mainpage/webui-mainpage.html
  validator/js/webui/@polymer/webui-statusbar/webui-statusbar.html
  validator/js/webui/@polymer/webui-urlform/webui-urlform.html
  validator/js/webui/README.md
  validator/js/webui/build.py
  validator/js/webui/index.html
  validator/js/webui/main/serve.go
  validator/js/webui/serve-standalone.go
  validator/js/webui/webui.js
Labels: WG: caching

#35735 Remove notice requirement from new component validator doc
  docs/component-validator-rules.md
Labels: WG: caching

#35742 🏗 Refresh git branches before potentially early-exiting during repo setup
  .circleci/fetch_merge_commit.sh
  .circleci/initialize_repo.sh
Labels: WG: infra

#35745 🏗 Refresh git cache only for non-main branches
  .circleci/fetch_merge_commit.sh
  .circleci/initialize_repo.sh
Labels: WG: infra

#35744 🏗📖 Remove AMP copyright from infrastructure source files
  .circleci/check_config.sh
  .circleci/fetch_merge_commit.sh
  .circleci/get_pr_number.sh
  .circleci/initialize_repo.sh
  .circleci/install_microsoft_edge.sh
  .circleci/install_validator_dependencies.sh
  .circleci/maybe_gracefully_halt.sh
  .circleci/restore_build_output.sh
  .github/workflows/install_dependencies.sh
  babel.config.js
  build-system/babel-config/minified-config.js
  build-system/babel-config/pre-closure-config.js
  build-system/common/default-pre-push
  build-system/common/enable-git-pre-push.sh
  build-system/release-tagger/index.js
  build-system/tasks/e2e/index.js
  build-system/tasks/make-extension/index.js
  build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/amp-__component_name_hyphenated__.js
  build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/base-element.js
  build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/component.js
  build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/component.type.js
  build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.js
  build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/test/test-amp-__component_name_hyphenated__.js
  build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/test/test-component.js
  build-system/tasks/make-extension/template/classic/examples/amp-__component_name_hyphenated__.html
  build-system/tasks/make-extension/template/classic/extensions/amp-__component_name_hyphenated__/__component_version__/amp-__component_name_hyphenated__.js
  build-system/tasks/make-extension/template/classic/extensions/amp-__component_name_hyphenated__/__component_version__/test/test-amp-__component_name_hyphenated__.js
  build-system/tasks/make-extension/template/css/extensions/amp-__component_name_hyphenated__/__component_version__/amp-__component_name_hyphenated__.css
  build-system/tasks/make-extension/template/jss/extensions/amp-__component_name_hyphenated__/__component_version__/component.jss.js
  build-system/tasks/make-extension/template/shared/extensions/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.amp.js
  build-system/tasks/make-extension/template/shared/extensions/amp-__component_name_hyphenated__/__component_version__/test/__validator__-amp-__component_name_hyphenated__.html
  build-system/tasks/make-extension/template/shared/extensions/amp-__component_name_hyphenated__/__validator__-amp-__component_name_hyphenated__.protoascii
  build-system/tasks/make-extension/template/shared/extensions/amp-__component_name_hyphenated__/amp-__component_name_hyphenated__.md
  build-system/tasks/sweep-experiments/jscodeshift/remove-experiment-config.js
  build-system/tasks/sweep-experiments/jscodeshift/remove-experiment-runtime.js
  testing/helpers/index.js
  testing/helpers/types.js
Labels: WG: infra

#35747 📖 Remove AMP Copyright notice from non-validator HTML files
  examples/ad-lightbox.amp.html
  examples/amp-date-countdown.amp.html
  examples/amp-next-page.amp.html
  examples/amp-smartlinks.html
  examples/amp-story/interactive_quizzes.html
  examples/amp-story/interactive_size.html
  examples/viqeo.amp.html
  test/fixtures/e2e/amp-base-carousel/captions.amp.html
  test/fixtures/served/ampdoc-with-messaging.html
  test/manual/amp-analytics/analytics-shadow.html
  test/manual/amp-flying-carpet-media.amp.html
  test/manual/amp-lightbox-gallery.amp.html
  test/manual/amp-list/infinite-scroll-2.amp.html
  test/manual/amp-sidebar-focus.amp.html
  test/manual/autofocus-on-show.html
  test/manual/video-caching.amp.html
Labels: WG: infra

#35740 ♻️ ads-initialIntersection: clean up failed experiment
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/name-frame-renderer.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  src/experiments/ads-initial-intersection-exp.js
  test/integration/test-amp-ad-3p.js
Labels: Cleanup AMP Experiments, Type: Refactoring

#35749 Add wg-caching as owners of validator-*.out.cpponly
  OWNERS
Labels: WG: caching

#35757 ExtensionSpec with bento_supported_version
  extensions/amp-accordion/validator-amp-accordion.protoascii
  extensions/amp-base-carousel/validator-amp-base-carousel.protoascii
  extensions/amp-brightcove/validator-amp-brightcove.protoascii
  extensions/amp-date-countdown/validator-amp-date-countdown.protoascii
  extensions/amp-date-display/validator-amp-date-display.protoascii
  extensions/amp-embedly-card/validator-amp-embedly-card.protoascii
  extensions/amp-facebook/validator-amp-facebook.protoascii
  extensions/amp-fit-text/validator-amp-fit-text.protoascii
  extensions/amp-inline-gallery/validator-amp-inline-gallery.protoascii
  extensions/amp-instagram/validator-amp-instagram.protoascii
  extensions/amp-lightbox-gallery/validator-amp-lightbox-gallery.protoascii
  extensions/amp-lightbox/validator-amp-lightbox.protoascii
  extensions/amp-render/validator-amp-render.protoascii
  extensions/amp-selector/validator-amp-selector.protoascii
  extensions/amp-social-share/validator-amp-social-share.protoascii
  extensions/amp-soundcloud/validator-amp-soundcloud.protoascii
  extensions/amp-stream-gallery/validator-amp-stream-gallery.protoascii
  extensions/amp-timeago/validator-amp-timeago.protoascii
  extensions/amp-twitter/validator-amp-twitter.protoascii
  extensions/amp-video-iframe/validator-amp-video-iframe.protoascii
  extensions/amp-video/validator-amp-video.protoascii
  extensions/amp-vimeo/validator-amp-vimeo.protoascii
  extensions/amp-wordpress-embed/validator-amp-wordpress-embed.protoascii
  extensions/amp-youtube/validator-amp-youtube.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: WG: caching, WG: bento

#35762 Add latest to bento_supported_version
  extensions/amp-stream-gallery/validator-amp-stream-gallery.protoascii
  extensions/amp-wordpress-embed/validator-amp-wordpress-embed.protoascii
Labels: WG: caching

#35772 🐛 [Amp story] Toggle desktop attribute on tooltip overlay
  extensions/amp-story/1.0/amp-story-embedded-component.js
Labels: Type: Bug, P1: High Priority, WG: stories

#35675 build-system: esbuild for production via EXP_C
  build-system/babel-config/minified-config.js
  build-system/babel-config/unminified-config.js
  build-system/compile/helpers.js
  build-system/global-configs/experiments-config.json
  build-system/global-configs/experiments-const.json
  build-system/tasks/check-sourcemaps.js
  build-system/tasks/helpers.js
Labels: WG: infra, WG: performance

#35791 Validator roll-up
  validator/js/engine/validator_test.js
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: WG: caching

#35792 Sync for validator cpp engine and cpp htmlparser
  validator/cpp/engine/validator-internal.cc
Labels: WG: caching

#35846 🏗 Replace `globby` with `fast-glob`
  .eslintignore
  build-system/common/utils.js
  build-system/compile/compile.js
  build-system/compile/pre-closure-babel.js
  build-system/pr-check/build-targets.js
  build-system/pr-check/utils.js
  build-system/server/typescript-compile.js
  build-system/tasks/3p-vendor-helpers.js
  build-system/tasks/analytics-vendor-configs.js
  build-system/tasks/bundle-size/index.js
  build-system/tasks/check-analytics-vendors-list.js
  build-system/tasks/check-build-system.js
  build-system/tasks/check-exact-versions.js
  build-system/tasks/check-types.js
  build-system/tasks/check-video-interface-list.js
  build-system/tasks/compile-jison.js
  build-system/tasks/css/index.js
  build-system/tasks/dist.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/get-zindex/index.js
  build-system/tasks/lint.js
  build-system/tasks/markdown-toc/index.js
  build-system/tasks/markdown-toc/test/test.js
  build-system/tasks/presubmit.js
  build-system/tasks/runtime-test/helpers-unit.js
  build-system/tasks/serve.js
  build-system/tasks/server-tests.js
  build-system/tasks/sweep-experiments/index.js
  build-system/test-configs/config.js
  package.json
Labels: WG: infra

#35823 mode: collapse definitions of localDev and test
  build-system/test-configs/forbidden-terms.js
  src/core/context/node.js
  src/core/dom/layout/viewport-observer.js
  src/core/mode/index.js
  src/core/mode/local-dev.js
  src/core/mode/test.js
  src/mode.js
  src/preact/base-element.js
  src/service/extension-script.js
  src/video-iframe-integration.js
  test/unit/core/window/test-history.js
  test/unit/test-runtime.js
  test/unit/test-viewport.js
Labels: WG: performance, Type: Refactoring

#35860 🚮 Remove getIntersectionElementLayoutBox from amp-iframe
  build-system/test-configs/forbidden-terms.js
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-iframe/0.1/test/test-amp-iframe.js
Labels: WG: performance, Type: Refactoring

#35863 🐛 [Amp story page attachment] Propagate title attribute to draggable drawer header
  examples/amp-story/attachment.html
  extensions/amp-story/1.0/amp-story-page-attachment.js
Labels: Type: Bug, P1: High Priority, WG: stories

#35849 Make `compiler.js` runnable within a node.js environment
  extensions/amp-fit-text/0.1/amp-fit-text.js
  extensions/amp-fit-text/0.1/build-dom.js
  extensions/amp-fit-text/0.1/test/test-amp-fit-text.js
  src/builtins/amp-layout/amp-layout.js
  src/builtins/amp-layout/build-dom.js
  src/compiler/builders.js
  src/compiler/index.js
  src/compiler/polyfills.js
  src/compiler/shame.extern.js
  test/unit/builtins/test-amp-layout.js
Labels: WG: performance
