Repository ampproject/amphtml, pull requests merged in 2021-07, with the labels that each got.

#35107 update re2 master to main
  validator/cpp/engine/WORKSPACE
  validator/cpp/htmlparser/WORKSPACE
Labels: WG: caching

#35105 amp-fit-text: fix cls by hiding until font size calculation
  extensions/amp-fit-text/0.1/amp-fit-text.js
Labels: Component: amp-fit-text, Related to: Performance, Type: Bug, WG: components, WG: performance

#34939 ✨ `amp-story-desktop-one-panel` Background color
  extensions/amp-story/1.0/amp-story-desktop-one-panel.css
Labels: P1: High Priority, WG: stories

#35108 bump worker-dom to 0.30.1
  package-lock.json
  package.json
Labels: WG: performance

#35101 amp-fit-text: extract buildDOM #compiler
  builtins/amp-layout/amp-layout.js
  css/Z_INDEX.md
  extensions/amp-fit-text/0.1/amp-fit-text.css
  extensions/amp-fit-text/0.1/amp-fit-text.js
Labels: WG: components, WG: performance

#34948 ✨Bento `amp-wordpress-embed`
  build-system/compile/bundles.config.extensions.json
  extensions/amp-wordpress-embed/1.0/amp-wordpress-embed.js
  extensions/amp-wordpress-embed/1.0/base-element.js
  extensions/amp-wordpress-embed/1.0/component.js
  extensions/amp-wordpress-embed/1.0/component.type.js
  extensions/amp-wordpress-embed/1.0/storybook/Basic.amp.js
  extensions/amp-wordpress-embed/1.0/storybook/Basic.js
  extensions/amp-wordpress-embed/1.0/test/test-amp-wordpress-embed.js
  extensions/amp-wordpress-embed/OWNERS
  extensions/amp-wordpress-embed/amp-wordpress-embed.md
  extensions/amp-wordpress-embed/validator-amp-wordpress-embed.protoascii
Labels: WG: caching

#35150 🏗 Update release (freeze) documentation
  docs/release-schedule.md
Labels: Related to: Documentation, WG: infra

#35160 builtins: restructure unit tests to mirror new folder structure
  test/integration/builtins/test-amp-img.js
  test/integration/builtins/test-amp-pixel.js
  test/unit/builtins/test-amp-img-v1.js
  test/unit/builtins/test-amp-img.js
  test/unit/builtins/test-amp-layout.js
  test/unit/builtins/test-amp-pixel.js
Labels: Type: Refactoring, WG: performance

#35036 🐛 `amp-story-page-attachment` Move overlay logic from story to page.
  css/Z_INDEX.md
  extensions/amp-story/1.0/amp-story-page-attachment.js
  extensions/amp-story/1.0/amp-story.css
  extensions/amp-story/1.0/amp-story.js
Labels: P1: High Priority, WG: stories

#35132 ✨ `amp-story-desktop-one-panel` `background-blur` Ensure img is loaded, no animation on landing
  extensions/amp-story/1.0/background-blur.js
Labels: P1: High Priority, WG: stories

#35175 ✨ `amp-story-desktop-one-panel` `background-blur` Pre draw image to fade in
  extensions/amp-story/1.0/background-blur.js
Labels: P1: High Priority, WG: stories

#35215 add capture for inpute[type=file] on AMP format only
  validator/testdata/feature_tests/forms.html
  validator/testdata/feature_tests/forms.out
  validator/validator-main.protoascii
Labels: WG: caching

#35271 🏗 Fix bug in instantiation of babel cache
  build-system/common/esbuild-babel.js
  build-system/tasks/runtime-test/helpers.js
Labels: WG: infra

#35327 Sync for validator cpp engine and cpp htmlparser
  validator/cpp/engine/validator-internal.cc
Labels: WG: caching

#35326 Validator Rollup.
  extensions/amp-lightbox/1.0/test/validator-amp4ads-lightbox.out
  extensions/amp-story/1.0/test/validator-amp-story-deprecated.out
  validator/js/engine/htmlparser-interface.js
  validator/js/engine/validator.js
  validator/testdata/amp4email_feature_tests/no_latest_extensions.out
  validator/testdata/feature_tests/forms.out
  validator/testdata/feature_tests/regexps.out
  validator/testdata/feature_tests/script_invalid_path.html
  validator/testdata/feature_tests/script_invalid_path.out
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
  validator/validator_gen_js.py
Labels: WG: caching

#35119 🐛 [Amp story] [Draggable drawer] Null check on headerEl.
  extensions/amp-story/1.0/amp-story-draggable-drawer.js
  extensions/amp-story/1.0/amp-story-page-attachment.js
Labels: P1: High Priority, WG: stories

#35064 Support `amp-facebook-comments`, `-like`, and `-page` with one extension binary (`1.0` only)
  build-system/compile/bundles.config.extensions.json
  build-system/test-configs/dep-check-config.js
  extensions/amp-facebook-comments/1.0/amp-facebook-comments.css
  extensions/amp-facebook-comments/1.0/amp-facebook-comments.js
  extensions/amp-facebook-comments/1.0/base-element.js
  extensions/amp-facebook-comments/1.0/storybook/Basic.amp.js
  extensions/amp-facebook-like/1.0/amp-facebook-like.css
  extensions/amp-facebook-like/1.0/amp-facebook-like.js
  extensions/amp-facebook-like/1.0/base-element.js
  extensions/amp-facebook-like/1.0/storybook/Basic.amp.js
  extensions/amp-facebook-page/1.0/amp-facebook-page.css
  extensions/amp-facebook-page/1.0/amp-facebook-page.js
  extensions/amp-facebook-page/1.0/base-element.js
  extensions/amp-facebook-page/1.0/storybook/Basic.amp.js
  extensions/amp-facebook/1.0/amp-facebook.css
  extensions/amp-facebook/1.0/amp-facebook.js
  extensions/amp-facebook/1.0/base-element.js
  extensions/amp-facebook/1.0/facebook-base-element.js
  extensions/amp-facebook/1.0/storybook/Basic.amp.js
  extensions/amp-facebook/1.0/test/test-amp-facebook-comments.js
  extensions/amp-facebook/1.0/test/test-amp-facebook-like.js
  extensions/amp-facebook/1.0/test/test-amp-facebook-page.js
Labels: WG: caching

#35397 ✨ [Amp story player] [Desktop panels player] Hide buttons if full-bleed story.
  css/amp-story-player-shadow.css
  extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js
  src/amp-story-player/amp-story-player-impl.js
  test/unit/test-amp-story-player.js
Labels: P1: High Priority, Type: Feature Request, WG: stories
