Repository ampproject/amphtml, pull requests merged in 2021-02, with the labels that each got.

#32335 🏗 Optimize GitHub Actions jobs
  .github/workflows/cross-browser-tests.yml
  build-system/pr-check/cross-browser-tests.js
  build-system/tasks/report-test-status.js
Labels: WG: infra

#32340 Update node.js readme with htmlFormat parameter
  validator/js/nodejs/README.md
Labels: WG: caching

#32346 🏗 Trigger CircleCI builds only for `ampproject/amphtml`
  .circleci/config.yml
Labels: WG: infra

#32351 🏗 Log commit info during bundle-size checks
  build-system/tasks/bundle-size/index.js
Labels: WG: infra

#32357 Validator rollup 20210202
  validator/testdata/feature_tests/doctype_lang.html
  validator/testdata/feature_tests/doctype_lang.out
  validator/testdata/feature_tests/doctype_lang.out.cpponly
  validator/testdata/feature_tests/newline_attributes.html
  validator/testdata/feature_tests/newline_attributes.out
  validator/validator-main.protoascii
Labels: WG: caching

#32362 🏗 Run GH actions workflow only for `ampproject/amphtml` PRs and pushes
  .github/workflows/cross-browser-tests.yml
Labels: WG: infra

#32363 Fork SVG validator rules into their own file
  validator/build.py
  validator/js/engine/validator_test.js
  validator/validator-main.protoascii
  validator/validator-svg.protoascii
Labels: WG: caching

#32359 🏗 Clean up a few things in `gulpfile.js`
  build-system/tasks/build.js
  build-system/tasks/default-task.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/sweep-experiments/index.js
  contributing/TESTING.md
  gulpfile.js
  package-lock.json
  package.json
Labels: WG: infra

#32370 🏗 Replace `karma-simple-reporter` with `karma-spec-reporter`
  build-system/test-configs/karma.conf.js
  package-lock.json
  package.json
Labels: WG: infra

#32376 Allow more SVG filter primitive elements
  validator/testdata/feature_tests/svg-filter-primitive-elements.html
  validator/testdata/feature_tests/svg-filter-primitive-elements.out
  validator/validator-main.protoascii
  validator/validator-svg.protoascii
Labels: WG: caching

#32372 Sync for validator/cpp/engine
  validator/cpp/engine/validator-internal.cc
Labels: WG: caching

#32374 Sync for validator/cpp/htmlparser
  validator/cpp/htmlparser/allocator_test.cc
  validator/cpp/htmlparser/bin/casetablegen.cc
  validator/cpp/htmlparser/css/parse-css.cc
  validator/cpp/htmlparser/css/parse-css_test.cc
  validator/cpp/htmlparser/elements.h
  validator/cpp/htmlparser/fileutil.h
  validator/cpp/htmlparser/grammar/tablebuilder.cc
  validator/cpp/htmlparser/json/types.h
  validator/cpp/htmlparser/node.h
  validator/cpp/htmlparser/parser.cc
  validator/cpp/htmlparser/parser.h
  validator/cpp/htmlparser/tokenizer.h
  validator/cpp/htmlparser/url.cc
  validator/cpp/htmlparser/url_test.cc
Labels: WG: caching

#32315 ✨ Add support for Canvas renderer in the amp-bodymovin-animation component
  3p/bodymovinanimation.js
  examples/bodymovin-animation.amp.html
  extensions/amp-bodymovin-animation/0.1/amp-bodymovin-animation.js
  extensions/amp-bodymovin-animation/0.1/test/validator-amp-bodymovin-animation.html
  extensions/amp-bodymovin-animation/0.1/test/validator-amp-bodymovin-animation.out
  extensions/amp-bodymovin-animation/amp-bodymovin-animation.md
  extensions/amp-bodymovin-animation/validator-amp-bodymovin-animation.protoascii
Labels: WG: caching

#32388 🏗 Check if PR branches contain the latest CircleCI config file
  .circleci/check_config.sh
  .circleci/config.yml
Labels: WG: infra

#32417 🏗 Refine PR / push build detection logic for upstream branches
  .circleci/check_config.sh
  .circleci/fetch_merge_commit.sh
  build-system/common/ci.js
Labels: WG: infra

#32423 🏗 Use correct env var to check for PR / push
  build-system/common/ci.js
Labels: WG: infra

#32424 🏗 Switch signaling for bundle-size, test-status, and pr-deploy to CircleCI
  build-system/pr-check/bundle-size.js
  build-system/tasks/pr-deploy-bot-utils.js
  build-system/tasks/report-test-status.js
Labels: WG: infra

#32373 🐛🏗 Update build-system/tasks/server-tests to use import rather than require.
  build-system/tasks/server-tests.js
Labels: WG: infra

#32444 🏗 Remove `node_modules` caching on GH Actions
  .github/workflows/cross-browser-tests.yml
Labels: WG: infra

#32443 🏗 Run E2E tests on Safari and Firefox
  build-system/pr-check/cross-browser-tests.js
  build-system/tasks/report-test-status.js
Labels: WG: infra

#32440 ♻️ [timeago/date-countdown/date-display] Split component files for packaging
  build-system/tasks/presubmit-checks.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-date-countdown/1.0/amp-date-countdown.js
  extensions/amp-date-countdown/1.0/base-element.js
  extensions/amp-date-countdown/1.0/component.js
  extensions/amp-date-countdown/1.0/component.type.js
  extensions/amp-date-countdown/1.0/storybook/Basic.js
  extensions/amp-date-countdown/1.0/test/test-date-countdown.js
  extensions/amp-date-display/1.0/amp-date-display.js
  extensions/amp-date-display/1.0/base-element.js
  extensions/amp-date-display/1.0/component.js
  extensions/amp-date-display/1.0/component.type.js
  extensions/amp-date-display/1.0/storybook/Basic.js
  extensions/amp-date-display/1.0/test/test-date-display.js
  extensions/amp-timeago/1.0/amp-timeago.js
  extensions/amp-timeago/1.0/base-element.js
  extensions/amp-timeago/1.0/component.js
  extensions/amp-timeago/1.0/component.type.js
  extensions/amp-timeago/1.0/storybook/Basic.js
  extensions/amp-timeago/1.0/test/test-timeago.js
Labels: WG: bento

#32472 🏗🚀 Substantially speed up `gulp` task loading
  build-system/compile/post-closure-babel.js
  build-system/compile/pre-closure-babel.js
  build-system/pr-check/build-targets.js
  build-system/tasks/a4a.js
  build-system/tasks/ava.js
  build-system/tasks/create-golden-css/index.js
  build-system/tasks/csvify-size/index.js
  build-system/tasks/csvify-size/test.js
  build-system/tasks/jsify-css.js
  build-system/tasks/process-3p-github-pr.js
  build-system/tasks/runtime-test/runtime-test-base.js
  build-system/tasks/size.js
  build-system/tasks/todos.js
  build-system/test-configs/config.js
  build-system/test-configs/karma.conf.js
  gulpfile.js
  package-lock.json
  package.json
  test/SIZE.md
  test/golden-files/main.css
  test/size.csv
  test/size.txt
Labels: WG: infra, WG: performance

#32481 🏗 Add a way to run NPM scripts that live outside `package.json` (via `nps`)
  .eslintrc.js
  OWNERS
  package-scripts.js
Labels: WG: infra

#32465 🏗 Fix message in `cross-browser-tests.js`
  build-system/pr-check/cross-browser-tests.js
Labels: WG: infra

#32525 🏗 Update closure compiler to February's version
  extensions/amp-playbuzz/0.1/utils.js
  extensions/amp-user-notification/0.1/amp-user-notification.js
  package-lock.json
  package.json
  src/impression.js
  src/polyfills/fetch.js
  src/polyfillstub/intersection-observer-stub.js
  src/polyfillstub/resize-observer-stub.js
  src/runtime.js
  src/service/resource.js
  src/service/resources-interface.js
  src/service/viewer-interface.js
  src/style.js
  third_party/subscriptions-project/swg.js
Labels: WG: infra

#32479 🏗 Replace logging in `gulp bundle-size` with output from `filesize`
  build-system/tasks/bundle-size/index.js
  package-lock.json
  package.json
Labels: WG: infra

#32529 🏗 Fix skip logic for E2E tests on FF / Safari
  build-system/pr-check/cross-browser-tests.js
Labels: WG: infra

#32527 🏗 E2E test improvements
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/index.js
Labels: WG: infra

#32538 🏗 Remove and prevent unused eslint directives
  build-system/tasks/lint.js
  src/ini-load.js
Labels: WG: infra

#32546 🏗 Stop running visual diff tests on Travis
  build-system/pr-check/visual-diff-tests.js
Labels: WG: infra

#32556 ❄️ Skip flaky ads tests
  test/integration/test-amphtml-ads.js
Labels: Related to: Flaky Tests, WG: monetization

#32557 ❄️ Skip flaky carousel test
  extensions/amp-base-carousel/1.0/test-e2e/test-carousel.js
Labels: Related to: Flaky Tests, WG: components

#32561 Sync for validator/cpp/engine
  validator/cpp/engine/validator-internal.cc
Labels: WG: caching

#32575 🏗 Add fail-fast behavior to CircleCI builds
  .circleci/check_config.sh
  .circleci/config.yml
  .circleci/fail_fast.sh
  .circleci/fetch_merge_commit.sh
  .circleci/install_dependencies.sh
  .circleci/setup_storage.sh
  .github/workflows/install_dependencies.sh
  build-system/common/enable-git-pre-push.sh
Labels: WG: infra

#32595 🏗 Add fail-fast behavior to CircleCI PR builds
  .circleci/check_config.sh
  .circleci/config.yml
  .circleci/fail_fast.sh
  .circleci/fetch_merge_commit.sh
  .circleci/install_dependencies.sh
  .circleci/setup_storage.sh
  .github/workflows/install_dependencies.sh
  build-system/common/enable-git-pre-push.sh
Labels: WG: infra

#32599 ❄️ Skip flaky ads test
  test/integration/test-amphtml-ads.js
Labels: Related to: Flaky Tests, WG: monetization

#32437 Remove sync measurement from ad iframes: experiment
  build-system/global-configs/canary-config.json
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/name-frame-renderer.js
  extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
  extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  src/experiments/ads-initial-intersection-exp.js
  test/integration/test-amp-ad-3p.js
Labels: Related to: Performance, WG: performance

#32574 🏗 Run experiment tests during PR builds
  .circleci/config.yml
  build-system/pr-check/experiment-tests.js
  build-system/tasks/e2e/index.js
  build-system/tasks/integration.js
  build-system/tasks/report-test-status.js
  extensions/amp-fit-text/0.1/test-e2e/test-amp-fit-text.js
Labels: WG: infra

#32604 🏗 Clean up log coloring, enable on GH Actions
  .github/workflows/install_dependencies.sh
  build-system/compile/log-messages.js
Labels: WG: infra

#32602 🏗 Rewrite `gulp ava` using the `ava` CLI
  build-system/tasks/ava.js
  build-system/tasks/get-zindex/get-zindex.test.js
  build-system/tasks/prepend-global/prepend-global.test.js
  build-system/tasks/presubmit-checks.js
  package-lock.json
  package.json
Labels: WG: infra

#32578 amp-form: enable detached analytics & fix error flow
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
Labels: Component: amp-form

#32626 🏗 Rewrite `gulp prettify` using the `nodejs` API of `prettier`
  build-system/pr-check/build-targets.js
  build-system/tasks/prettify.js
  package-lock.json
  package.json
Labels: WG: infra

#32576 🏗 Rewrite `gulp lint` using the `nodejs` API of `eslint`
  build-system/tasks/lint.js
  package-lock.json
  package.json
  test/unit/test-vsync.js
  testing/amp-performance-extension/measure.js
Labels: WG: infra

#32117 🏗 Fully migrate AMP's CI from Travis to CircleCI
  .prettierrc
  .travis.yml
  .vscode/settings.json
  build-system/common/ci.js
  build-system/pr-check/bundle-size.js
  build-system/pr-check/visual-diff-tests.js
  build-system/tasks/pr-deploy-bot-utils.js
  build-system/tasks/report-test-status.js
  build-system/test-configs/config.js
Labels: WG: infra

#32623 🏗 Remove `gulp` streaming from a few developer tasks
  build-system/tasks/caches-json.js
  build-system/tasks/get-zindex/get-zindex.test.js
  build-system/tasks/get-zindex/index.js
  build-system/tasks/performance-urls.js
  build-system/tasks/presubmit-checks.js
  build-system/tasks/server-tests.js
Labels: WG: infra

#32660 Sync for validator/cpp/htmlparser
  validator/cpp/htmlparser/css/amp4ads-parse-css_test.cc
  validator/cpp/htmlparser/css/parse-css_test.cc
  validator/cpp/htmlparser/json/types.cc
  validator/cpp/htmlparser/json/types_test.cc
Labels: WG: caching

#32661 Sync for validator/cpp/engine
  validator/cpp/engine/keyframes-parse-css_test.cc
  validator/cpp/engine/parse-layout.cc
  validator/cpp/engine/validator-internal.cc
  validator/cpp/engine/validator_test.cc
Labels: WG: caching

#32662 Validator rollup
  validator/js/engine/validator.js
  validator/js/engine/validator_test.js
  validator/testdata/amp4email_feature_tests/amp-accordion.html
  validator/testdata/amp4email_feature_tests/amp-accordion.out
  validator/testdata/amp4email_feature_tests/amp-autocomplete.html
  validator/testdata/amp4email_feature_tests/amp-autocomplete.out
  validator/testdata/amp4email_feature_tests/amp_carousel.html
  validator/testdata/amp4email_feature_tests/amp_carousel.out
  validator/testdata/amp4email_feature_tests/amp_form.html
  validator/testdata/amp4email_feature_tests/amp_form.out
  validator/testdata/amp4email_feature_tests/amp_img.html
  validator/testdata/amp4email_feature_tests/amp_img.out
  validator/testdata/amp4email_feature_tests/amp_list.html
  validator/testdata/amp4email_feature_tests/amp_list.out
  validator/testdata/amp4email_feature_tests/anchor.html
  validator/testdata/amp4email_feature_tests/anchor.out
  validator/testdata/amp4email_feature_tests/css.out
  validator/testdata/amp4email_feature_tests/css_declarations.out
  validator/testdata/amp4email_feature_tests/css_i_amphtml.html
  validator/testdata/amp4email_feature_tests/css_i_amphtml.out
  validator/testdata/amp4email_feature_tests/css_length.out
  validator/testdata/amp4email_feature_tests/doc_size.html
  validator/testdata/amp4email_feature_tests/doc_size.out
  validator/testdata/amp4email_feature_tests/min_valid_amp4email.html
  validator/testdata/amp4email_feature_tests/min_valid_amp4email.out
  validator/testdata/amp4email_feature_tests/min_valid_multiline_amp4email.html
  validator/testdata/amp4email_feature_tests/min_valid_multiline_amp4email.out
  validator/testdata/amp4email_feature_tests/no_latest_extensions.html
  validator/testdata/amp4email_feature_tests/no_latest_extensions.out
  validator/testdata/amp4email_feature_tests/nonce_disallowed.html
  validator/testdata/amp4email_feature_tests/nonce_disallowed.out
  validator/validator-main.protoascii
  validator/validator.pb.go
  validator/validator.proto
Labels: WG: caching

#32652 🏗 Remove `gulp.watch` and modernize `analytics-vendor-configs`
  build-system/tasks/3p-vendor-helpers.js
  build-system/tasks/analytics-vendor-configs.js
  build-system/tasks/e2e/index.js
  build-system/tasks/serve.js
  package-lock.json
  package.json
Labels: WG: infra

#32663 🏗🚀 Rewrite and speed up `gulp build` using `esbuild` and `@babel/core`
  build-system/babel-config/unminified-config.js
  build-system/tasks/helpers.js
  extensions/amp-bind/0.1/bind-expression.js
  package-lock.json
  package.json
Labels: WG: infra

#32696 🏗 Follow up changes to `gulp build` rewrite
  build-system/babel-config/unminified-config.js
  build-system/tasks/helpers.js
Labels: WG: infra

#32208 ✨Assist.js: Create the skeleton of the new extension for assist.js: amp-google-assistant-assistjs.
  build-system/compile/bundles.config.extensions.json
  examples/amp-google-assistant-assistjs.amp.html
  extensions/amp-google-assistant-assistjs/0.1/amp-google-assistant-assistjs.css
  extensions/amp-google-assistant-assistjs/0.1/amp-google-assistant-assistjs.js
  extensions/amp-google-assistant-assistjs/0.1/amp-google-assistant-inline-suggestion-bar.js
  extensions/amp-google-assistant-assistjs/0.1/amp-google-assistant-voice-bar.js
  extensions/amp-google-assistant-assistjs/0.1/amp-google-assistant-voice-button.js
  extensions/amp-google-assistant-assistjs/0.1/assistjs-config-service.js
  extensions/amp-google-assistant-assistjs/0.1/test/test-amp-google-assistant-assistjs.js
  extensions/amp-google-assistant-assistjs/0.1/test/validator-amp-google-assistant-assistjs.html
  extensions/amp-google-assistant-assistjs/0.1/test/validator-amp-google-assistant-assistjs.out
  extensions/amp-google-assistant-assistjs/OWNERS
  extensions/amp-google-assistant-assistjs/amp-google-assistant-assistjs.md
  extensions/amp-google-assistant-assistjs/validator-amp-google-assistant-assistjs.protoascii
  src/services.js
Labels: Component: amp-google-assistant-assistjs, WG: caching

#32774 🏗 Sync Chrome version used by Visual tests with Percy backend
  build-system/tasks/visual-diff/index.js
Labels: WG: infra

#32845 🏗 Rewrite `dep-check` with `esbuild` and `babel`
  .gitignore
  build-system/babel-config/dep-check-config.js
  build-system/tasks/clean.js
  build-system/tasks/dep-check.js
  package-lock.json
  package.json
Labels: WG: infra

#32864 🏗 Make bundle-size reporting failures non-blocking
  build-system/tasks/bundle-size/index.js
Labels: WG: infra

#32835 watch src dir for v0.js
  build-system/server/lazy-build.js
  build-system/tasks/helpers.js
Labels: WG: infra, WG: performance

#32878 validator release schedule
  contributing/release-schedule.md
  contributing/validator-release-schedule.md
Labels: WG: caching

#32890 🐛Fix the bug that parseLayout ignores case and underscore
  validator/js/engine/validator.js
  validator/testdata/feature_tests/amp_layouts.html
  validator/testdata/feature_tests/amp_layouts.out
Labels: WG: caching

#32926 gulp build: support esm
  build-system/babel-config/unminified-config.js
  build-system/tasks/build.js
Labels: WG: infra

#32903 🏗 Remove almost all `gulp` streaming from the compilation pipeline
  build-system/tasks/css/index.js
  build-system/tasks/dist.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
  extensions/amp-web-push/0.1/amp-web-push-helper-frame.html
  extensions/amp-web-push/0.1/amp-web-push-permission-dialog.html
  package-lock.json
  package.json
Labels: WG: infra
