Repository ampproject/amphtml, pull requests merged in 2021-05, with the labels that each got.

#34176 🏗 Switch top-level reviewer list from `reviewerTeam` to `reviewerPool`
  OWNERS
Labels: WG: infra

#34182 🏗 Use bot name of `renovate-approve` for owner approval of upgrade PRs
  OWNERS
Labels: WG: infra

#34183 Revert "🏗 Use bot name of `renovate-approve` for owner approval of upgrade PRs"
  OWNERS
Labels: WG: infra

#34202 🏗 Disable updates for validator webui
  .renovaterc.json
Labels: WG: caching

#34196 Sync for validator/cpp/engine
  validator/cpp/engine/validator-internal.cc
Labels: WG: caching

#34187 amp-iframely validation update
  extensions/amp-iframely/0.1/test/validator-amp-iframely.html
  extensions/amp-iframely/0.1/test/validator-amp-iframely.out
  extensions/amp-iframely/validator-amp-iframely.protoascii
Labels: WG: caching

#34211 🏗 Use correct suffix for `renovate-approve` bot
  OWNERS
Labels: WG: infra

#34214 🏗 Allow auto-merge for low-risk validator upgrades
  validator/OWNERS
Labels: WG: caching

#34105 Types: fix all type parse errors and ensure no new ones crop up
  ads/vendors/feedad.js
  build-system/compile/closure-compile.js
  build-system/tasks/check-types.js
  extensions/amp-a4a/0.1/amp-ad-utils.js
  extensions/amp-accordion/1.0/component.type.js
  extensions/amp-addthis/0.1/amp-addthis.js
  extensions/amp-addthis/0.1/config-manager.js
  extensions/amp-bind/0.1/bind-impl.js
  extensions/amp-brightcove/0.1/amp-brightcove.js
  extensions/amp-lightbox-gallery/1.0/component.type.js
  extensions/amp-lightbox/1.0/component.type.js
  extensions/amp-render/1.0/component.type.js
  extensions/amp-selector/1.0/component.type.js
  extensions/amp-sidebar/1.0/component.type.js
  extensions/amp-sidebar/1.0/sidebar-animations-hook.js
  extensions/amp-story-auto-ads/0.1/story-ad-page-manager.js
  extensions/amp-story-auto-ads/0.1/story-ad-ui.js
  extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.js
  extensions/amp-subscriptions/0.1/entitlement.js
  extensions/amp-video/1.0/video-iframe.js
  src/amp-story-player/amp-story-player-viewport-observer.js
  src/context/node.js
  src/custom-element.js
  src/preact/component/3p-frame.js
  src/preact/component/component.type.js
  src/preact/slot.js
Labels: Type: Performance, Type: Refactoring

#34236 📖 🐛 Update amp-story-panning-media docs image link and size
  extensions/amp-story-panning-media/amp-story-panning-media.md
Labels: WG: stories

#34227 resources: rename V1 to R1, to clear up ambiguity
  build-system/externs/amp.extern.js
  build-system/global-configs/experiments-config.json
  build-system/global-configs/experiments-const.json
  builtins/amp-img.js
  src/base-element.js
  src/custom-element.js
  src/inabox/inabox-resources.js
  src/preact/base-element.js
  src/service/resource.js
  src/service/resources-impl.js
  test/integration/test-visibility-states.js
  test/unit/inabox/test-inabox-resources.js
  test/unit/preact/test-base-element-mapping.js
  test/unit/test-amp-img-v1.js
  test/unit/test-custom-element-v1.js
  test/unit/test-resources.js
  testing/element-v1.js
Labels: Related to: Performance, WG: performance

#34234 allow http and relative for amp-story-page-attachment
  extensions/amp-story/validator-amp-story.protoascii
Labels: WG: caching, WG: stories

#34249 🏗 runtime: allow for iterator polyfill
  .eslintrc.js
  build-system/.eslintrc.js
  build-system/eslint-rules/no-for-of-statement.js
  examples/.eslintrc.js
  src/service/owners-impl.js
Labels: WG: performance

#34171 ✨ [Amp story] Add `amp-story-page-outlink` component
  examples/amp-story/attachment.html
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/amp-story.js
  extensions/amp-story/1.0/page-advancement.js
  extensions/amp-story/1.0/test/test-amp-story-page.js
  extensions/amp-story/validator-amp-story.protoascii
Labels: WG: caching

#34275 🖍 [Amp story] [Page attachments] Style adjustments
  extensions/amp-story/1.0/amp-story-open-page-attachment.css
  extensions/amp-story/1.0/amp-story-open-page-attachment.js
Labels: P1: High Priority, WG: stories

#34303 ❄️ Skip flaky stories tests
  extensions/amp-story/1.0/test/test-page-advancement.js
Labels: Related to: Flaky Tests, WG: stories

#34200 ✅ Validator rules for amp-video-iframe 1.0
  extensions/amp-video-iframe/1.0/test/validator-amp-video-iframe.html
  extensions/amp-video-iframe/1.0/test/validator-amp-video-iframe.out
  extensions/amp-video-iframe/validator-amp-video-iframe.protoascii
Labels: WG: caching

#34339 validator update
  extensions/amp-vimeo/validator-amp-vimeo.protoascii
Labels: WG: caching

#30043 Upgrade Preact to 10.5.13
  extensions/amp-accordion/1.0/test/test-component.js
  extensions/amp-base-carousel/1.0/test-e2e/test-grouping.js
  extensions/amp-selector/1.0/test/test-component.js
  package-lock.json
  package.json
  src/preact/index.js
Labels: cla: yes

#34346 🏗♻️ Refactor and simplify initialization / clean up of unit and integration tests
  build-system/test-configs/config.js
  build-system/test-configs/forbidden-terms.js
  test/unit/test-iframe-helper.js
  testing/_init_tests.js
  testing/async-errors.js
  testing/console-logging-setup.js
  testing/init-tests.js
Labels: Related to: Flaky Tests, WG: infra

#34393 🏗 Switch AMP's main bug template to a yaml-based form
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: WG: infra

#34397 📖 Expand AMP issue template intro text
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Related to: Documentation

#34398 📖 Convert feature request issue template to a form
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Related to: Documentation

#34428 Validator rollup
  validator/validator.pb.go
  validator/validator.proto
Labels: WG: caching

#34431 📖 Migrate `Intent-to-*` issue templates to yaml forms
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/intent-to-deprecate--i2d-.md
  .github/ISSUE_TEMPLATE/intent-to-deprecate.yml
  .github/ISSUE_TEMPLATE/intent-to-implement--i2i-.md
  .github/ISSUE_TEMPLATE/intent-to-implement.yml
  .github/ISSUE_TEMPLATE/intent-to-remove--i2r-.md
  .github/ISSUE_TEMPLATE/intent-to-remove.yml
  .github/ISSUE_TEMPLATE/intent-to-ship--i2s-.md
  .github/ISSUE_TEMPLATE/intent-to-ship.yml
Labels: Related to: Documentation

#34213 ✨ Change default validator to WebAssembly in Node.js Package
  validator/js/nodejs/index.js
  validator/js/nodejs/index_test.js
Labels: WG: caching

#34440 📖 Migrate the release tracker template to a yaml form
  .github/ISSUE_TEMPLATE/release-tracker.yml
  .github/ISSUE_TEMPLATE/release-tracking-issue.md
Labels: Related to: Documentation

#33095 ✨[amp-form] allow `form` attributes for form elements outside of `amp-form`
  build-system/test-configs/forbidden-terms.js
  extensions/amp-form/0.1/amp-form.js
  extensions/amp-form/0.1/form-dirtiness.js
  extensions/amp-form/0.1/form-validators.js
  extensions/amp-form/0.1/form-verifiers.js
  extensions/amp-form/0.1/test/integration/test-integration-form.js
  extensions/amp-form/0.1/test/test-amp-form.js
  extensions/amp-form/0.1/test/test-form-dirtiness.js
  extensions/amp-form/amp-form.md
  validator/testdata/feature_tests/forms.html
  validator/testdata/feature_tests/forms.out
  validator/validator-main.protoascii
Labels: WG: caching

#34463 📖 Migrate the cherry-pick request template to a yaml form
  .github/ISSUE_TEMPLATE/cherry-pick-request.yml
  .github/ISSUE_TEMPLATE/cherry_pick_template.md
Labels: Related to: Documentation

#34473 📖 Assorted issue and PR template fixes
  .github/ISSUE_TEMPLATE/release-tracker.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  build-system/pr-check/build-targets.js
  build-system/test-configs/config.js
  docs/amp-module-build.md
  docs/contributing-code.md
  docs/contributing.md
  docs/developing.md
  docs/spec/amp-3p-video.md
  docs/spec/amp-html-format.md
  docs/spec/amp-localstorage.md
  extensions/amp-analytics/amp-components-analytics.md
  extensions/amp-analytics/integrating-analytics.md
  extensions/amp-bind/amp-bind.md
  extensions/amp-geo/amp-geo.md
  extensions/amp-iframe/0.1/amp-iframe.js
  extensions/amp-script/amp-script.md
Labels: Related to: Documentation

#34478 🏗 Enable VSCode auto-formatting and prettier checks for `.yml` files
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/cherry-pick-request.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/intent-to-deprecate.yml
  .github/ISSUE_TEMPLATE/intent-to-implement.yml
  .github/ISSUE_TEMPLATE/intent-to-remove.yml
  .github/ISSUE_TEMPLATE/intent-to-ship.yml
  .github/ISSUE_TEMPLATE/release-tracker.yml
  .prettierignore
  .prettierrc
  .vscode/settings.json
  build-system/test-configs/config.js
Labels: WG: infra

#34506 🏗 Move default PR template to `.github` directory
  .github/pull_request_template.md
Labels: WG: infra

#34509 🏗 Consolidate glob expansion while determining build targets
  build-system/pr-check/build-targets.js
Labels: WG: infra

#34503 Use isModeDevelopment for validator integration
  src/validator-integration.js
  test/unit/test-validator-integration.js
Labels: WG: caching

#34522 📖 Add bug report fields for OSs and Devices
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Related to: Documentation

#34524 📖 Use `n/a` instead of `/all` in the OS and device fields
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Related to: Documentation

#34525 🏗 Update build-system subpackages before checking types
  build-system/tasks/check-build-system.js
Labels: WG: infra

#34510 🏗 Include dotfiles while expanding globs during the CI check for valid URLs
  build-system/tasks/check-links.js
Labels: WG: infra

#34531 add amp-onerror validation for v0.js or v0.mjs
  validator/testdata/feature_tests/script_amp_onerror_js.html
  validator/testdata/feature_tests/script_amp_onerror_js.out
  validator/testdata/feature_tests/script_amp_onerror_js_fail.html
  validator/testdata/feature_tests/script_amp_onerror_js_fail.out
  validator/testdata/transformed_feature_tests/script_amp_onerror_js_mjs.html
  validator/testdata/transformed_feature_tests/script_amp_onerror_js_mjs.out
  validator/testdata/transformed_feature_tests/script_amp_onerror_js_mjs_fail.html
  validator/testdata/transformed_feature_tests/script_amp_onerror_js_mjs_fail.out
  validator/validator-main.protoascii
Labels: WG: caching

#34535 🐛 [Amp story] [Page attachments] [Outlink] Open remote from light dom
  extensions/amp-story/1.0/amp-story-page-attachment.js
Labels: P1: High Priority

#34537 🏗 Don't type-check server transform output
  build-system/server/typescript-compile.js
  build-system/tasks/coverage-map/index.js
Labels: WG: infra

#34366 ✨ [amp-render] validator changes
  extensions/amp-render/1.0/test/validator-amp-render.html
  extensions/amp-render/1.0/test/validator-amp-render.out
  extensions/amp-render/validator-amp-render.protoascii
Labels: WG: caching

#34546 🏗 Auto-format dev dashboard tests
  .eslintignore
  build-system/server/app-index/test/helpers.js
  build-system/server/app-index/test/test-amphtml-helpers.js
  build-system/server/app-index/test/test-file-list.js
  build-system/server/app-index/test/test-html.js
  build-system/server/app-index/test/test-self.js
  build-system/server/app-index/test/test-template.js
  build-system/server/app-index/test/test.js
Labels: WG: infra

#34557 🏗 Skip NPM checks while type-checking build-system
  build-system/common/update-packages.js
  build-system/tasks/check-build-system.js
Labels: WG: infra

#34567 🏗 Optimize linting during PR builds
  .eslintignore
  build-system/pr-check/build-targets.js
  build-system/pr-check/checks.js
  build-system/tasks/lint.js
  build-system/tasks/pr-check.js
Labels: WG: infra

#34359 ✨ Supports locale options for localeString in amp-date-display.
  examples/amp-date-display.amp.html
  extensions/amp-date-display/0.1/amp-date-display.js
  extensions/amp-date-display/0.1/amp-date-display.md
  extensions/amp-date-display/0.1/test/test-amp-date-display.js
  extensions/amp-date-display/0.1/test/validator-amp-date-display.html
  extensions/amp-date-display/0.1/test/validator-amp-date-display.out
  extensions/amp-date-display/1.0/base-element.js
  extensions/amp-date-display/1.0/component.js
  extensions/amp-date-display/1.0/component.type.js
  extensions/amp-date-display/1.0/test/test-amp-date-display.js
  extensions/amp-date-display/1.0/test/test-component.js
  extensions/amp-date-display/1.0/test/validator-amp-date-display.html
  extensions/amp-date-display/1.0/test/validator-amp-date-display.out
  extensions/amp-date-display/amp-date-display.md
Labels: WG: caching

#34575 📖 Add explanatory text to the LTS and cherry-pick sections of the release tracker
  .github/ISSUE_TEMPLATE/release-tracker.yml
Labels: Related to: Documentation

#34569 Run through all actions for each distFlavor in `amp release` before the next
  .eslintignore
  .gitignore
  .prettierignore
  build-system/tasks/clean.js
  build-system/tasks/release/index.js
Labels: WG: infra

#34591 🏗 Enforce JSDoc across `build-system/` for complete type-checking
  .eslintrc.js
  build-system/.eslintrc.js
  build-system/OWNERS
  build-system/babel-plugins/babel-plugin-transform-jss/index.js
  build-system/common/esbuild-babel.js
  build-system/common/update-packages.js
  build-system/compile/compile.js
  build-system/compile/helpers.js
  build-system/compile/sanitize.js
  build-system/eslint-rules/forbidden-terms-config.js
  build-system/pr-check/bundle-size.js
  build-system/pr-check/checks.js
  build-system/pr-check/cross-browser-tests.js
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/experiment-build.js
  build-system/pr-check/experiment-tests.js
  build-system/pr-check/module-build.js
  build-system/pr-check/module-tests.js
  build-system/pr-check/nomodule-build.js
  build-system/pr-check/nomodule-tests.js
  build-system/pr-check/performance-tests.js
  build-system/pr-check/unit-tests.js
  build-system/pr-check/unminified-build.js
  build-system/pr-check/unminified-tests.js
  build-system/pr-check/validator-tests.js
  build-system/pr-check/visual-diff-tests.js
  build-system/server/app-index/test/test-amphtml-helpers.js
  build-system/server/app-index/test/test-self.js
  build-system/server/typescript-compile.js
  build-system/tasks/e2e/describes-e2e.js
  build-system/tasks/e2e/expect.js
  build-system/tasks/e2e/repl.js
  build-system/tasks/e2e/selenium-webdriver-controller.js
  build-system/tasks/extension-helpers.js
  build-system/tasks/get-zindex/jscodeshift/collect-zindex.js
  build-system/tasks/helpers.js
  build-system/tasks/integration.js
  build-system/tasks/markdown-toc/index.js
  build-system/tasks/performance/measure-documents.js
  build-system/tasks/release/index.js
  build-system/tsconfig.json
Labels: WG: infra
