Repository ampproject/amphtml, pull requests merged in 2021-11, with the labels that each got.

#36663 test-amp-script: fix stubbing of WorkerDOM
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
Labels: WG: performance, Type: Testing

#36715 ♻️[amp story page advancement] handle clicks on drawer
  extensions/amp-story/1.0/page-advancement.js
Labels: WG: stories

#36746 🏗 Explicitly use node LTS for GH actions workflows
  .github/workflows/cross-platform-builds.yml
  .github/workflows/cut-nightly.yml
  .github/workflows/publish-npm-packages.yml
  .github/workflows/release-tagger.yml
  .github/workflows/status-page.yml
  .github/workflows/sweep-experiments.yml
Labels: WG: infra

#36742 🏗✨ Add lazy-build support for nested CSS imports
  build-system/tasks/css/jsify-css.js
  package-lock.json
  package.json
Labels: WG: infra

#36743 terser: enable toplevel, less hacky fix for nameCache local vars
  build-system/tasks/helpers.js
Labels: WG: performance, WG: bento

#36769 🏗 Restore hard-coded node version in GH actions setup
  .github/workflows/cross-platform-builds.yml
  .github/workflows/cut-nightly.yml
  .github/workflows/publish-npm-packages.yml
  .github/workflows/release-tagger.yml
  .github/workflows/status-page.yml
  .github/workflows/sweep-experiments.yml
Labels: WG: infra

#36801 ✅[bento-facebook] add e2e test
  extensions/amp-facebook/1.0/test-e2e/test-bento-facebook.js
  test/fixtures/e2e/bento/facebook.html
Labels: WG: bento

#36862 amp-story: remove reference to 0.1
  extensions/amp-story/amp-story.md
Labels: WG: stories, WG: performance

#36764 [amp story page advancement] Add comment on drawer click exception
  extensions/amp-story/1.0/page-advancement.js
Labels: WG: stories

#36859 compiler.js: s/versions/component_versions
  src/compiler/compile.js
  src/compiler/types.d.ts
  test/unit/compiler/test-compile.js
Labels: WG: performance

#36864 Validator rollup
  extensions/amp-video/validator-amp-video.protoascii
Labels: WG: caching

#36869 gallery/carousel fix: restore public function
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
Labels: Type: Bug, Component: amp-carousel, Component: amp-lightbox-gallery

#36872 adds basic tests to amp-gallery-lightbox, reintroduce goCallback to amp-carousel 0.1
  extensions/amp-base-carousel/0.1/amp-base-carousel.js
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-lightbox-gallery/0.1/test/test-amp-lightbox-gallery.js
Labels: Type: Bug, WG: performance, WG: components, Component: amp-carousel, Component: amp-lightbox-gallery

#36844 ✨Allow link[rel=stylesheet] which points to the amp-story-1.0.css in a transformed amp document
  validator/testdata/transformed_feature_tests/amp-story-css-link.html
  validator/testdata/transformed_feature_tests/amp-story-css-link.out
  validator/validator-main.protoascii
Labels: WG: caching

#36884 amp-form: allow xssi-prefix for amphtml and amp4ads
  validator/validator-main.protoascii
Labels: WG: components, WG: caching

#36930 🚮 ♻️ [amp story panning media] implicit returns
  extensions/amp-story-panning-media/0.1/amp-story-panning-media.js
Labels: WG: stories

#36942 ♻️[amp story 360] Use JSX
  extensions/amp-story-360/0.1/amp-story-360.js
Labels: WG: stories

#36602 compiler: create buildDom for amp-carousel 0.1
  extensions/amp-carousel/0.1/amp-carousel.js
  extensions/amp-carousel/0.1/build-dom.js
  extensions/amp-carousel/0.1/carousel-controls.js
  extensions/amp-carousel/0.1/scrollable-carousel.js
  extensions/amp-carousel/0.1/shame.d.ts
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-carousel/0.1/test/test-scrollable-carousel.js
  extensions/amp-carousel/0.1/test/test-slidescroll-slides.js
  extensions/amp-carousel/0.1/test/test-slidescroll.js
  test/integration/test-amp-carousel.js
Labels: WG: performance, WG: components

#36974 ✅ [bento-sidebar] refactor e2e test to hopefully be less flaky
  extensions/amp-sidebar/1.0/test-e2e/test-bento-sidebar.js
Labels: Related to: Flaky Tests, Type: Testing, WG: bento

#37001 renovate: immediately bump deps from @amppproject
  .renovaterc.json
Labels: WG: infra, WG: performance

#37005 bind-expression: bump max expression size.
  extensions/amp-bind/0.1/bind-expression.js
  extensions/amp-bind/amp-bind.md
Labels: WG: performance

#36989 ♻️ [Amp story shopping] Attachment as element child
  build-system/test-configs/dep-check-config.js
  examples/amp-story/amp-story-shopping.html
  examples/visual-tests/amp-story/amp-story-shopping.html
  extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.css
  extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js
  extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-attachment.js
  extensions/amp-story/1.0/amp-story-draggable-drawer.js
Labels: P1: High Priority, WG: stories

#37049 🚀 [Story performance] Only change dvh if the transformer doesn't do that already.
  extensions/amp-story/1.0/amp-story.js
Labels: WG: stories

#37079 Sync for validator cpp engine and cpp htmlparser
  validator/cpp/htmlparser/strings_test.cc
Labels: WG: caching
