Repository ampproject/amphtml, pull requests merged in 2021-10, with the labels that each got.

#36241 bento amp-iframe: guard effect from running without a win
  extensions/amp-iframe/1.0/component.js
Labels: Related to: Flaky Tests, WG: performance, Type: Testing, WG: bento

#36143 🚀 babel/terser: rename all amp privates with sentinel suffix
  build-system/babel-config/minified-config.js
  build-system/babel-plugins/babel-plugin-transform-rename-privates/index.js
  build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/rename-amp-privates/input.js
  build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/rename-amp-privates/options.json
  build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/rename-amp-privates/output.mjs
  build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/skip-nonamp-privates/input.js
  build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/skip-nonamp-privates/options.json
  build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/skip-nonamp-privates/output.mjs
  build-system/babel-plugins/babel-plugin-transform-rename-privates/test/index.js
  build-system/common/esbuild-babel.js
  build-system/tasks/helpers.js
Labels: WG: performance

#36302 🏗 Persist test sharding filelist as an artifact on CircleCI
  .circleci/config.yml
  build-system/pr-check/e2e-tests.js
  build-system/pr-check/experiment-e2e-tests.js
  build-system/pr-check/unit-tests.js
  build-system/pr-check/utils.js
Labels: WG: infra

#36295 ♻️ core: add getWin to core/window
  extensions/amp-a4a/0.1/within-viewport.js
  extensions/amp-accordion/1.0/amp-accordion.js
  extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
  extensions/amp-analytics/0.1/analytics-group.js
  extensions/amp-analytics/0.1/transport.js
  extensions/amp-animation/0.1/parsers/keyframes-extractor.js
  extensions/amp-auto-ads/0.1/adsense-network-config.js
  extensions/amp-auto-ads/0.1/measure-page-layout-box.js
  extensions/amp-base-carousel/1.0/amp-base-carousel.js
  extensions/amp-base-carousel/1.0/component.js
  extensions/amp-base-carousel/1.0/scroller.js
  extensions/amp-fit-text/1.0/component.js
  extensions/amp-form/0.1/form-proxy.js
  extensions/amp-form/0.1/form-validators.js
  extensions/amp-iframe/1.0/component.js
  extensions/amp-lightbox/1.0/amp-lightbox.js
  extensions/amp-pinterest/0.1/pin-widget.js
  extensions/amp-pinterest/0.1/save-button.js
  extensions/amp-selector/1.0/amp-selector.js
  extensions/amp-social-share/1.0/amp-social-share.js
  extensions/amp-story/1.0/amp-story-open-page-attachment.js
  extensions/amp-story/1.0/media-pool.js
  extensions/amp-story/1.0/prerender-active-page.js
  extensions/amp-story/1.0/toast.js
  extensions/amp-stream-gallery/1.0/amp-stream-gallery.js
  extensions/amp-stream-gallery/1.0/component.js
  extensions/amp-timeago/1.0/component.js
  src/base-element.js
  src/core/dom/index.js
  src/core/dom/layout/intersection-no-root.js
  src/core/dom/layout/intersection.js
  src/core/dom/layout/size-observer.js
  src/core/dom/layout/viewport-observer.js
  src/core/window/index.js
  src/custom-element.js
  src/extension-analytics.js
  src/friendly-iframe-embed.js
  src/gesture.js
  src/preact/bento-ce.js
  src/service-helpers.js
  src/service/action-impl.js
  src/service/navigation.js
  src/service/standard-actions-impl.js
  src/shadow-embed.js
  src/static-layout.js
Labels: Type: Refactoring

#36348 🏗 Pin Chrome version used during CI
  .circleci/config.yml
  .circleci/get_pinned_chrome_version.sh
  .renovaterc.json
Labels: WG: infra

#35437 ✨ Preact implementation for bento-dailymotion
  build-system/compile/sources.js
  build-system/test-configs/dep-check-config.js
  extensions/amp-dailymotion/0.1/amp-dailymotion.js
  extensions/amp-dailymotion/0.1/test/test-amp-dailymotion.js
  extensions/amp-dailymotion/1.0/component.js
  extensions/amp-dailymotion/1.0/component.type.js
  extensions/amp-dailymotion/1.0/storybook/Basic.js
  extensions/amp-dailymotion/1.0/test/test-component.js
  extensions/amp-dailymotion/dailymotion-api.js
Labels: WG: Caching: Triaged

#36300 core: add static layout
  extensions/amp-audio/0.1/test/test-amp-audio.js
  src/builtins/amp-layout/build-dom.js
  src/core/dom/amp-element.extern.js
  src/core/dom/layout/index.js
  src/core/static-layout.js
  src/custom-element.js
  test/unit/core/dom/layout/test-layout.js
  test/unit/test-amp-img-intrinsic.js
Labels: WG: performance, Type: Refactoring

#36418 compiler: accept partials
  package-lock.json
  package.json
  src/compiler/compile.js
  src/compiler/index.js
  src/compiler/types.d.ts
  test/unit/compiler/test-compile.js
Labels: WG: performance
