Repository ampproject/amphtml, pull requests merged in 2021-04, with the labels that each got.

#33386 📖[amp-story][amp-story-panning-media] Draft docs for developer preview
  extensions/amp-story-panning-media/amp-story-panning-media.md
  extensions/amp-story-panning-media/img/amp-story-panning-media.gif
  extensions/amp-story-panning-media/img/constellations-screenshot.jpg
  extensions/amp-story-panning-media/img/controls.jpg
Labels: WG: stories

#33640 📖 Use `default-jdk` for `amp validator --update_tests` instead of `openjdk-7-jre`
  validator/README.md
Labels: WG: caching

#33629 ads experiment: move initialIntersection to buildCallback
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-ad/0.1/amp-ad-3p-impl.js
Labels: WG: monetization, WG: performance, WG: runtime

#33659 🏗 Run the `bundle-size` check on pure production code
  .circleci/config.yml
  build-system/pr-check/bundle-size.js
Labels: WG: infra

#33616 Add validation rules for amp-timeago:1.0
  extensions/amp-timeago/1.0/test/validator-amp-timeago-mutation-error.html
  extensions/amp-timeago/1.0/test/validator-amp-timeago-mutation-error.out
  extensions/amp-timeago/1.0/test/validator-amp-timeago-mutation.html
  extensions/amp-timeago/1.0/test/validator-amp-timeago-mutation.out
  extensions/amp-timeago/1.0/test/validator-amp-timeago.html
  extensions/amp-timeago/1.0/test/validator-amp-timeago.out
  extensions/amp-timeago/validator-amp-timeago.protoascii
Labels: WG: caching

#33615 Add validation rules for amp-date-display:1.0 on websites
  extensions/amp-date-display/1.0/test/validator-amp-date-display.html
  extensions/amp-date-display/1.0/test/validator-amp-date-display.out
  extensions/amp-date-display/validator-amp-date-display.protoascii
Labels: WG: caching

#33652 amp-script: fix long task start/end order for within the same macrotask
  extensions/amp-script/0.1/user-activation-tracker.js
Labels: Component: amp-script, Type: Bug

#33683 🏗 Extract `PERCY_TOKEN` before skipping the check
  build-system/pr-check/nomodule-build.js
Labels: WG: infra

#33686 🏗 Use unique filenames to signal graceful halt of CircleCI Jobs
  .circleci/config.yml
  build-system/common/ci.js
  build-system/pr-check/utils.js
Labels: WG: infra

#33687 ✨ Set Validator WebUI to use WebAssembly by default
  validator/js/webui/app.yaml
Labels: WG: caching

#33691 🏗 Another fix for the graceful halt optimization during CI
  .circleci/config.yml
  build-system/pr-check/utils.js
Labels: WG: infra

#33632 Teach amp-analytics how to forward events to amp-script
  extensions/amp-analytics/0.1/amp-analytics.js
  extensions/amp-analytics/0.1/test/test-transport.js
  extensions/amp-analytics/0.1/transport.js
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
  test/manual/analytics-script-target.html
Labels: Component: amp-analytics, Component: amp-script, WG: analytics, WG: performance

#33696 🏗 Make `check-types` more granular by splitting `src/` and `extensions/`
  build-system/compile/compile.js
  build-system/tasks/check-types.js
Labels: WG: infra

#33695 dependencies: bump worker dom
  package-lock.json
  package.json
Labels: Component: amp-script

#33698 🏗 Update AMP's CI config to work on the `main` branch
  .circleci/check_config.sh
  .circleci/compute_merge_commit.sh
  .circleci/config.yml
  .circleci/fail_fast.sh
  .circleci/fetch_merge_commit.sh
  .circleci/get_pr_number.sh
  .github/workflows/create-design-review-issue.yml
  .github/workflows/cross-browser-tests.yml
  .renovaterc.json
  build-system/common/main-branch.js
  build-system/server/app-index/header-links.js
Labels: WG: infra

#33692 🚮 Remove Jank Meter
  build-system/tasks/create-golden-css/css/main.css
  build-system/test-configs/dep-check-config.js
  css/Z_INDEX.md
  css/ampdoc.css
  extensions/amp-analytics/0.1/iframe-transport.js
  src/service/jank-meter.js
  src/service/vsync-impl.js
  test/unit/test-jank-meter.js
  tools/experiments/experiments-config.js
Labels: Cleanup AMP Experiments, Type: Refactoring, WG: performance

#33711 🏗 Update AMP's CI config to work on the `main` branch (#33698)
  .circleci/check_config.sh
  .circleci/compute_merge_commit.sh
  .circleci/config.yml
  .circleci/fail_fast.sh
  .circleci/fetch_merge_commit.sh
  .circleci/get_pr_number.sh
  .github/workflows/create-design-review-issue.yml
  .github/workflows/cross-browser-tests.yml
  .renovaterc.json
  build-system/common/main-branch.js
  build-system/server/app-index/header-links.js
Labels: WG: infra

#33714 🏗 Run `lint` and `presubmit` when the checks' implementation or rules are changed
  build-system/pr-check/build-targets.js
Labels: WG: infra

#33718 🐛Rename JS version Validator WebUI as `legacy.html`
  validator/js/webui/app.yaml
  validator/js/webui/build.py
  validator/js/webui/index.html
Labels: WG: caching

#33723 🏗 Use the `allowlist` option in the closure conformance config
  build-system/test-configs/conformance-config.textproto
Labels: WG: infra

#33726 🏗 Print relative path of task file while running `amp` tasks
  build-system/tasks/amp-task-runner.js
Labels: WG: infra

#33729 🏗 Make `amp` and `gulp` execute the correct repo-local task runner
  amp.js
  build-system/task-runner/amp-task-runner.js
  build-system/task-runner/cli-runner.js
  build-system/task-runner/install-task-runner.js
  build-system/test-configs/forbidden-terms.js
  gulp-deprecated.js
  package.json
Labels: WG: infra

#33768 🏗 Optimize `dist` when only a subset of binaries need to be built
  build-system/tasks/dist.js
Labels: WG: infra

#33612 Add validations for Bento carousels on websites
  build-system/compile/bundles.config.extensions.json
  extensions/amp-base-carousel/1.0/test/validator-amp-base-carousel.html
  extensions/amp-base-carousel/1.0/test/validator-amp-base-carousel.out
  extensions/amp-base-carousel/validator-amp-base-carousel.protoascii
  extensions/amp-inline-gallery/1.0/test/validator-amp-inline-gallery-pagination.html
  extensions/amp-inline-gallery/1.0/test/validator-amp-inline-gallery-pagination.out
  extensions/amp-inline-gallery/1.0/test/validator-amp-inline-gallery-thumbnails.html
  extensions/amp-inline-gallery/1.0/test/validator-amp-inline-gallery-thumbnails.out
  extensions/amp-inline-gallery/validator-amp-inline-gallery.protoascii
  extensions/amp-stream-gallery/1.0/test/validator-amp-stream-gallery.html
  extensions/amp-stream-gallery/1.0/test/validator-amp-stream-gallery.out
  extensions/amp-stream-gallery/validator-amp-stream-gallery.protoascii
Labels: WG: Caching: Triaged, WG: caching

#33800 🏗 Reduce repetition in `amp.js` with the introduction of defaults
  .eslintignore
  .prettierrc
  amp.js
  build-system/task-runner/amp-task-runner.js
  build-system/tasks/make-extension/OWNERS
  build-system/tasks/make-extension/bento/OWNERS
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/OWNERS
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/__component_version__/amp-__component_name_hyphenated__.css
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/__component_version__/amp-__component_name_hyphenated__.js
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/__component_version__/base-element.js
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/__component_version__/component.js
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/__component_version__/component.jss.js
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/__component_version__/component.type.js
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.amp.js
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.js
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/__component_version__/test/test-amp-__component_name_hyphenated__.js
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/amp-__component_name_hyphenated__.md
  build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/validator-amp-__component_name_hyphenated__.protoascii
  build-system/tasks/make-extension/bento/index.js
  build-system/tasks/make-extension/index.js
  build-system/tasks/make-extension/insert-extension-bundles-config.js
  build-system/tasks/presubmit.js
  build-system/test-configs/forbidden-terms.js
  build-system/tsconfig.json
Labels: WG: infra

#33787 🏗 Clean up deprecated `gulp` task runner
  .eslintrc.js
  OWNERS
  build-system/task-runner/OWNERS
  build-system/task-runner/amp-cli-runner.js
  build-system/task-runner/amp-task-runner.js
  build-system/task-runner/install-amp-task-runner.js
  build-system/task-runner/install-task-runner.js
  build-system/test-configs/forbidden-terms.js
  gulp-deprecated.js
  package.json
Labels: WG: infra

#33480 ✨ [bento][amp-date-countdown] Extend validator to 1.0 for amp-date-countdown
  extensions/amp-date-countdown/1.0/test/validator-amp-date-countdown.html
  extensions/amp-date-countdown/1.0/test/validator-amp-date-countdown.out
  extensions/amp-date-countdown/validator-amp-date-countdown.protoascii
Labels: WG: Caching: Triaged, WG: caching

#33478 ✨ [bento][amp-social-share] Extend validator to 1.0 for social-share for websites
  extensions/amp-social-share/1.0/test/validator-amp-social-share.html
  extensions/amp-social-share/1.0/test/validator-amp-social-share.out
  extensions/amp-social-share/validator-amp-social-share.protoascii
Labels: WG: Caching: Triaged, WG: caching

#33641 ✨ Allow amp-date-display in stories
  extensions/amp-story/validator-amp-story.protoascii
Labels: WG: caching

#33808 📖 Add sign-in instructions for PR check services to dev docs and PR template
  .github/PULL_REQUEST_TEMPLATE.md
  contributing/getting-started-e2e.md
  contributing/getting-started-quick.md
Labels: Related to: Documentation, WG: infra

#33829 🏗 Remove duplicate local var in task runner installer
  build-system/task-runner/install-amp-task-runner.js
Labels: WG: infra

#33834 🏗 Move directory management into `TransformCache`
  build-system/common/esbuild-babel.js
  build-system/common/transform-cache.js
  build-system/tasks/css/jsify-css.js
Labels: WG: infra

#33836 🏗 Ignore `build-system/dist`
  .gitignore
  build-system/tsconfig.json
Labels: WG: infra

#33838 🏗 Reorganize `.gitignore` and keep it in sync with `amp clean`, `.eslintignore`, and `.prettierignore`
  .eslintignore
  .gitignore
  .prettierignore
  build-system/tasks/clean.js
Labels: WG: infra

#33840 build-system: use metafile for smarter watching
  build-system/tasks/extension-helpers.js
  build-system/tasks/helpers.js
Labels: WG: infra

#33310 performance-impl: exclusively use ampdoc visibility state
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: WG: performance

#33858 🏗 Drop support for python 3.5 now that it has reached EOL
  build-system/common/check-package-manager.js
Labels: WG: infra

#33864 🚀🏗 Speed up minified compilation by caching pre-closure transforms
  .eslintignore
  .gitignore
  .prettierignore
  build-system/common/esbuild-babel.js
  build-system/common/transform-cache.js
  build-system/compile/closure-compile.js
  build-system/compile/helpers.js
  build-system/compile/pre-closure-babel.js
  build-system/tasks/clean.js
  build-system/tasks/helpers.js
Labels: WG: infra

#33875 🏗 Fix dependency extraction while watching JS entry points
  build-system/tasks/helpers.js
Labels: WG: infra

#33856 🏗 Update CircleCI base docker image from 12/2020 to 4/2021
  .circleci/config.yml
Labels: WG: infra

#33880 🏗 Automatically verify root-level / task-level package files during PR checks
  build-system/common/npm-checks.js
  build-system/common/update-packages.js
  build-system/pr-check/ci-job.js
  build-system/pr-check/npm-checks.js
  build-system/task-runner/amp-task-runner.js
  build-system/tasks/pr-check.js
  build-system/tasks/storybook/package-lock.json
Labels: WG: infra

#33805 Add validation rules for amp-instagram:1.0
  extensions/amp-instagram/1.0/test/validator-amp-instagram.html
  extensions/amp-instagram/1.0/test/validator-amp-instagram.out
  extensions/amp-instagram/validator-amp-instagram.protoascii
Labels: WG: caching

#33811 Add validation rules for amp-lightbox:1.0
  extensions/amp-lightbox/1.0/test/validator-amp-lightbox.html
  extensions/amp-lightbox/1.0/test/validator-amp-lightbox.out
  extensions/amp-lightbox/1.0/test/validator-amp4ads-lightbox.html
  extensions/amp-lightbox/1.0/test/validator-amp4ads-lightbox.out
  extensions/amp-lightbox/validator-amp-lightbox.protoascii
Labels: WG: caching

#33903 cl/369259725 Revision bump for #33702
  validator/validator-main.protoascii
Labels: WG: caching

#33900 ♻️ Extract AmpScriptService.fetch into its own fn.
  extensions/amp-analytics/0.1/test/test-transport.js
  extensions/amp-analytics/0.1/transport.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/0.1/test/test-amp-list.js
  extensions/amp-render/1.0/amp-render.js
  extensions/amp-script/0.1/amp-script.js
  src/url.js
Labels: Component: amp-analytics, Component: amp-list, Component: amp-script, Type: Refactoring, WG: performance

#33905 Validator Roll Up
  validator/validator-main.protoascii
Labels: WG: caching

#33848 Add validation rules for amp-youtube 1.0
  extensions/amp-youtube/1.0/test/validator-amp-youtube.html
  extensions/amp-youtube/1.0/test/validator-amp-youtube.out
  extensions/amp-youtube/validator-amp-youtube.protoascii
  validator/testdata/feature_tests/duplicate_attribute.out.cpponly
Labels: WG: caching

#33910 🏗 Clean up validator C++ logs and surface errors
  build-system/tasks/validator.js
Labels: WG: caching, WG: infra

#33916 🏗 Clean up exports from `exec.js` and `process.js`
  build-system/common/exec.js
  build-system/common/git.js
  build-system/tasks/check-renovate-config.js
  build-system/tasks/cherry-pick.js
  build-system/tasks/codecov-upload.js
  build-system/tasks/markdown-toc/index.js
  build-system/test-configs/jscodeshift/index.js
Labels: WG: infra

#33918 Bump worker-dom, update iframe-worker-proxy
  3p/amp-script-proxy-iframe.js
  examples/amp-list-protocol-adapters.html
  package-lock.json
  package.json
Labels: Component: amp-script, Type: Bug, WG: performance

#33902 📖 Support newlines for amp-script meta hashes
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/amp-script.md
  test/fixtures/e2e/amp-script/basic.amp.html
Labels: Component: amp-script

#33927 🏗 Check dot files and directories for invalid whitespaces
  .circleci/maybe_gracefully_halt.sh
  build-system/tasks/check-invalid-whitespaces.js
Labels: WG: infra

#32617 amp-nexxtv-player updates
  examples/nexxtv-player.amp.html
  extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js
  extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js
  extensions/amp-nexxtv-player/0.1/test/validator-amp-nexxtv-player.html
  extensions/amp-nexxtv-player/0.1/test/validator-amp-nexxtv-player.out
  extensions/amp-nexxtv-player/amp-nexxtv-player.md
  extensions/amp-nexxtv-player/validator-amp-nexxtv-player.protoascii
Labels: WG: Caching: Triaged, WG: caching

#33934 🏗 Omit files / dirs in `.gitignore` during invalid whitespace checks
  build-system/tasks/check-invalid-whitespaces.js
Labels: WG: infra

#33872 ✨ Ads RTC: support amp-script fetching
  examples/amp-ad/doubleclick-rtc.amp.html
  src/service/real-time-config/real-time-config-impl.js
  test/unit/test-real-time-config.js
Labels: WG: monetization

#33962 🏗 Refine and update a few infrastructure related `OWNERS` files
  build-system/common/OWNERS
  build-system/tasks/check-owners.js
  examples/visual-tests/OWNERS
  test/visual-diff/OWNERS
Labels: WG: infra

#33963 Externs: remove two outdated files
  build-system/externs/amp.multipass.extern.js
  build-system/externs/weakref.extern.js
Labels: Type: Refactoring, WG: performance

#33967 🏗 Prevent Karma from hanging when a transformation error is encountered
  build-system/tasks/report-test-status.js
  build-system/tasks/runtime-test/helpers.js
  build-system/tasks/runtime-test/runtime-test-base.js
Labels: WG: infra

#33997 🏗 Add `amp validate-html-fixtures` to AMP's PR check workflow
  amp.js
  build-system/common/utils.js
  build-system/pr-check/build-targets.js
  build-system/pr-check/checks.js
  build-system/tasks/check-invalid-whitespaces.js
  build-system/tasks/pr-check.js
  build-system/tasks/validate-html-fixtures.js
  build-system/test-configs/config.js
  examples/3q-player.amp.html
  examples/amphtml-ads/adchoices-1.a4a.html
  examples/timeago.amp.html
  examples/visual-tests/article.amp/article.amp.html
  test/fixtures/e2e/amp4email/viewport-size-race.html
Labels: WG: infra

#34000 🏗 Add a way to validate all HTML test fixtures, even skipped ones
  build-system/tasks/validate-html-fixtures.js
Labels: WG: infra

#34018 🏗 Enable `automerge` for renovate updates to `devDependencies`
  .renovaterc.json
Labels: WG: infra

#33847 Add validation rules for amp-video 1.0
  extensions/amp-video/1.0/test/validator-amp-video.html
  extensions/amp-video/1.0/test/validator-amp-video.out
  extensions/amp-video/validator-amp-video.protoascii
Labels: WG: caching

#33518 ✨ Ads: Resolves support for Opinary Embed integration
  ads/vendors/opinary.js
  ads/vendors/opinary.md
Labels: WG: Caching: Triaged

#34031 🏗 Perform `esbuild` package upgrades via a separate PR
  .renovaterc.json
Labels: WG: infra

#34034 ❄️ Mark `amp-story-dev-tools` visual tests as flaky
  test/visual-diff/visual-tests
Labels: WG: stories

#34040 🏗 Flag an error and exit when Karma runs zero tests
  build-system/tasks/runtime-test/helpers.js
  build-system/test-configs/config.js
Labels: WG: infra

#34045 🏗 Log extension name while building npm binaries
  build-system/tasks/helpers.js
Labels: WG: infra

#34060 🏗 Flag an error if `--files` matches zero test files
  build-system/common/utils.js
Labels: WG: infra

#34063 🏗 Clean up extension generator tests
  build-system/tasks/make-extension/index.js
Labels: WG: infra

#34064 🏗 Refine renovate configuration
  .renovaterc.json
Labels: WG: infra

#34082 🏗 Further refine renovate configuration
  .renovaterc.json
  build-system/tasks/coverage-map/package-lock.json
  build-system/tasks/coverage-map/package.json
Labels: WG: infra

#34079 ✨ Add wg-stories to OWNERS of localized-strings
  src/OWNERS
Labels: WG: stories

#34095 ✨ Add raxsha to amp-story owners.
  extensions/amp-story/OWNERS
Labels: WG: stories

#26151 ✨ AMP - Iframely.com component
  extensions/amp-iframely/0.1/amp-iframely.js
  extensions/amp-iframely/0.1/test/test-amp-iframely.js
  extensions/amp-iframely/0.1/test/validator-amp-iframely.html
  extensions/amp-iframely/0.1/test/validator-amp-iframely.out
  extensions/amp-iframely/OWNERS.yaml
  extensions/amp-iframely/amp-iframely.md
  extensions/amp-iframely/validator-amp-iframely.protoascii
Labels: WG: Caching: Triaged, WG: caching, cla: yes

#34100 🏗 Use terminal width for test log wrapping if possible
  build-system/common/logging.js
Labels: WG: infra

#34107 🏗 Restrict all root-level upgrade groups to the root `package.json`
  .renovaterc.json
Labels: WG: infra

#34119 🏗 Further group package updates to reduce noise
  .renovaterc.json
Labels: WG: infra

#34118 🏗 Make package update review requests less noisy
  OWNERS
  extensions/amp-access/0.1/iframe-api/OWNERS
  third_party/amp-toolbox-cache-url/OWNERS
  validator/OWNERS
Labels: WG: infra

#34145 🏗 Add `renovate-bot` as an owner of package upgrade PRs
  OWNERS
  build-system/OWNERS
Labels: WG: infra

#34041 [bento] Disable 1.0 only attributes for amp4email
  extensions/amp-accordion/validator-amp-accordion.protoascii
  extensions/amp-lightbox/validator-amp-lightbox.protoascii
Labels: WG: caching
