Repository ampproject/amphtml, pull requests merged in 2021-09, with the labels that each got.

#35937 cl/394490119 Fix a bug where the CSS parser was not correctly accounting for the possibility of calc() in the media expression.
  validator/js/engine/parse-css.js
  validator/js/engine/parse-css_test.js
  validator/testdata/feature_tests/media_expression_calc.html
  validator/testdata/feature_tests/media_expression_calc.out
Labels: WG: caching

#35879 ♻️ docs/bento-stream-gallery
  extensions/amp-stream-gallery/1.0/base-element.js
  extensions/amp-stream-gallery/1.0/component.js
  extensions/amp-stream-gallery/1.0/component.type.js
  extensions/amp-stream-gallery/1.0/storybook/Basic.js
  extensions/amp-stream-gallery/1.0/test/test-component.js
Labels: cla: yes

#35982 Clean up some small linter issues with validator files.
  validator/build.py
  validator/js/nodejs/index_test.js
Labels: WG: caching

#35980 📖 Add instructions to reproduce validator tests
  validator/README.md
Labels: WG: caching

#35682 amp-story-captions
  build-system/compile/bundles.config.extensions.json
  examples/amp-story/amp-story-captions.html
  examples/amp-story/captions.vtt
  extensions/amp-story-captions/0.1/amp-story-captions.css
  extensions/amp-story-captions/0.1/amp-story-captions.js
  extensions/amp-story-captions/0.1/test/test-amp-story-captions.js
  extensions/amp-story-captions/0.1/test/validator-amp-story-captions.html
  extensions/amp-story-captions/0.1/test/validator-amp-story-captions.out
  extensions/amp-story-captions/0.1/track-renderer.js
  extensions/amp-story-captions/validator-amp-story-captions.protoascii
  extensions/amp-story/validator-amp-story.protoascii
  extensions/amp-video/0.1/amp-video.js
  extensions/amp-video/validator-amp-video.protoascii
Labels: WG: caching

#35815 esbuild for dist: fix 3 discovered issues
  build-system/tasks/helpers.js
Labels: WG: infra, WG: performance

#35835 Custom hook using IntersectionObserver
  examples/amp-timeago.amp.html
  extensions/amp-iframe/1.0/component.js
  extensions/amp-iframe/1.0/storybook/Basic.js
  extensions/amp-timeago/1.0/component.js
  extensions/amp-timeago/1.0/storybook/Basic.js
  src/core/dom/layout/viewport-observer.js
  src/preact/component/index.js
  src/preact/component/intersection-observer-resize.js
  src/preact/storybook/Hooks.js
  src/preact/utils.js
  test/unit/core/dom/layout/test-viewport-observer.js
Labels: WG: bento

#35981 ✨ compiler.js: myriad fixes
  build-system/compile/build-compiler.js
  build-system/compile/bundles.config.js
  build-system/tasks/dist.js
  build-system/tasks/helpers.js
  build-system/test-configs/forbidden-terms.js
  package-lock.json
  package.json
  src/compiler/index.js
  src/compiler/polyfills.js
  src/compiler/types.js
Labels: WG: performance

#36054 Update text to minimum valid JavaScript AMP
  validator/js/webui/@polymer/webui-mainpage/webui-mainpage.html
  validator/testdata/amp4ads_feature_tests/min_valid_amp4ads.html
  validator/testdata/amp4ads_feature_tests/min_valid_amp4ads.out
  validator/testdata/amp4ads_feature_tests/min_valid_multiline_amp4ads.html
  validator/testdata/amp4ads_feature_tests/min_valid_multiline_amp4ads.out
  validator/testdata/amp4email_feature_tests/min_valid_amp4email.html
  validator/testdata/amp4email_feature_tests/min_valid_amp4email.out
  validator/testdata/feature_tests/minimum_valid_amp.html
  validator/testdata/feature_tests/minimum_valid_amp.out
  validator/testdata/transformed_feature_tests/minimum_valid_amp.html
  validator/testdata/transformed_feature_tests/minimum_valid_amp.out
Labels: WG: caching

#36031 🐛 Bump worker dom, fixes storage access in sandbox
  examples/amp-script/export-functions.js
  package-lock.json
  package.json
Labels: WG: performance, Component: amp-script

#36010 Broadbandy AMP Integration
  3p/vendors/broadbandy.js
  ads/_config.js
  ads/vendors/broadbandy.js
  ads/vendors/broadbandy.md
  examples/amp-ad/ads.amp.html
  extensions/amp-ad/amp-ad.md
Labels: WG: Caching: Triaged

#36008 Revert "Revert "Improve AMP_CONFIG handling during build (#35773)" (#35819)"
  build-system/compile/compile.js
  build-system/compile/post-closure-babel.js
  build-system/pr-check/module-tests.js
  build-system/pr-check/nomodule-tests.js
  build-system/server/lazy-build.js
  build-system/tasks/build.js
  build-system/tasks/helpers.js
  build-system/tasks/prepend-global/index.js
  build-system/tasks/prepend-global/prepend-global.test.js
  build-system/tasks/release/index.js
  build-system/test-configs/forbidden-terms.js
Labels: WG: infra, WG: performance

#36034 Compiler: create documentation
  src/compiler/README.md
Labels: WG: performance

#34149 Integrate Bandsintown Amplified ad network
  3p/vendors/amplified.js
  ads/_config.js
  ads/ads.extern.js
  ads/vendors/amplified.js
  ads/vendors/amplified.md
  examples/amp-ad/ads.amp.html
Labels: WG: monetization

#35123 performance-impl: start tracking lcp element
  extensions/amp-viewer-integration/TICKEVENTS.md
  src/core/constants/enums.js
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: WG: performance

#36100 ♿ Add Accessibility attributes to iframes
  extensions/amp-a4a/0.1/amp-a4a.js
  extensions/amp-a4a/0.1/friendly-frame-util.js
  extensions/amp-a4a/0.1/secure-frame.js
  extensions/amp-a4a/0.1/test/test-amp-a4a.js
  extensions/amp-a4a/0.1/test/test-friendly-frame-util.js
Labels: Type: Accessibility

#36075 Validator Rollup
  validator/js/engine/validator-deprecated.js
  validator/js/engine/validator-in-browser-deprecated.js
Labels: WG: caching

#36122 Sync for validator cpp engine and cpp htmlparser
  validator/cpp/htmlparser/strings.cc
Labels: WG: caching

#36085 ✨ [Amp story panning media] Validation
  examples/amp-story/amp-story-desktop-one-panel.html
  examples/amp-story/amp-story-panning-media.html
  extensions/amp-story-panning-media/0.1/amp-story-panning-media.js
  extensions/amp-story-panning-media/0.1/test/test-amp-story-panning-media.js
  extensions/amp-story-panning-media/0.1/test/validator-amp-story-panning-media.html
  extensions/amp-story-panning-media/0.1/test/validator-amp-story-panning-media.out
  extensions/amp-story-panning-media/amp-story-panning-media.md
  extensions/amp-story-panning-media/validator-amp-story-panning-media.protoascii
Labels: WG: caching

#36149 Add validator rules for 1.0 amp-sidebar
  extensions/amp-sidebar/1.0/test/validator-amp-sidebar.html
  extensions/amp-sidebar/1.0/test/validator-amp-sidebar.out
  extensions/amp-sidebar/validator-amp-sidebar.protoascii
Labels: WG: caching

#36105 Reenable EsbuildCompilation on EXP_C
  build-system/global-configs/experiments-config.json
  build-system/tasks/check-sourcemaps.js
  build-system/tasks/helpers.js
  build-system/tasks/visual-diff/index.js
Labels: WG: infra, WG: performance

#35423 ✨ [Amp story player] [panel player] Launch panel player
  css/Z_INDEX.md
  css/amp-story-player-shadow.css
  extensions/amp-story-player/0.1/test/test-e2e/test-amp-story-player-prerender.js
  src/amp-story-player/amp-story-player-impl.js
  test/e2e/test-amp-story-player-prerender.js
  test/unit/test-amp-story-player.js
Labels: P1: High Priority, Type: Feature Request, WG: stories

#36155 🚮 performance-impl: cleanup outdated metrics 🧹
  extensions/amp-viewer-integration/TICKEVENTS.md
  src/core/constants/enums.js
  src/service/performance-impl.js
  test/unit/test-performance.js
Labels: Related to: Performance, WG: performance, Type: Refactoring, Type: Performance

#36103 🐛(amp-lightbox-gallery): opens to selected image, resolve #35920
  extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
  extensions/amp-lightbox-gallery/0.1/test-e2e/test-open-close.js
  test/fixtures/e2e/amp-lightbox/amp-lightbox-gallery-launch.amp.html
Labels: WG: Caching: Triaged

#36113 🐛 bind-impl: missing <amp-state> specified as an amp-list data source is a user error
  extensions/amp-bind/0.1/bind-impl.js
Labels: WG: performance, Component: amp-list, Component: amp-bind, Type: Error Report

#36217 🐛 [amp-story-panning-media] Set width on amp-img el
  extensions/amp-story-panning-media/0.1/amp-story-panning-media.css
Labels: Type: Bug, P1: High Priority
