Repository ampproject/amphtml, pull requests merged in 2022-01, with the labels that each got.

#37173 🏗🚮 Clean up closure compiler code paths no longer used by `amp dist`
  build-system/compile/compile.js
  build-system/tasks/check-sourcemaps.js
  build-system/tasks/dist.js
  build-system/tasks/helpers.js
  package-lock.json
  package.json
Labels: WG: infra

#37096 ✨ New component: [amp-access-fewcents] paywall support by Fewcents
  build-system/compile/bundles.config.extensions.json
  examples/amp-access-fewcents.html
  extensions/amp-access-fewcents/0.1/amp-access-fewcents.css
  extensions/amp-access-fewcents/0.1/amp-access-fewcents.js
  extensions/amp-access-fewcents/0.1/fewcents-constants.js
  extensions/amp-access-fewcents/0.1/fewcents-impl.js
  extensions/amp-access-fewcents/0.1/test/test-amp-access-fewcents.js
  extensions/amp-access-fewcents/0.1/test/validator-amp-access-fewcents.html
  extensions/amp-access-fewcents/0.1/test/validator-amp-access-fewcents.out
  extensions/amp-access-fewcents/OWNERS
  extensions/amp-access-fewcents/amp-access-fewcents.md
Labels: WG: caching

#34168 🐛 Adds microsoft-edge protocol
  extensions/amp-bind/0.1/bind-validator.js
  validator/validator-main.protoascii
Labels: WG: caching

#37316 🐛 [amp story] Replay/next page button bug fix
  extensions/amp-story/1.0/pagination-buttons.js
Labels: Type: Bug, WG: stories

#37340 preact-base-element: modernize statics
  build-system/babel-config/minified-config.js
  build-system/babel-config/test-config.js
  build-system/babel-config/unminified-config.js
  package-lock.json
  package.json
  src/preact/base-element.js
Labels: WG: performance

#35751 ✨ `bento-dailymotion` AMP and Bento mode implementations
  build-system/compile/bundles.config.extensions.json
  extensions/amp-dailymotion/1.0/amp-dailymotion.css
  extensions/amp-dailymotion/1.0/amp-dailymotion.js
  extensions/amp-dailymotion/1.0/base-element.js
  extensions/amp-dailymotion/1.0/storybook/Basic.amp.js
  extensions/amp-dailymotion/1.0/test/test-amp-dailymotion.js
  extensions/amp-dailymotion/1.0/test/validator-amp-dailymotion.html
  extensions/amp-dailymotion/1.0/test/validator-amp-dailymotion.out
  extensions/amp-dailymotion/validator-amp-dailymotion.protoascii
Labels: WG: caching

#37355 🐛 extension bundles json: revert latestVersions change
  build-system/compile/bundles.config.extensions.json
Labels: Type: Bug

#37307 ✨ Second cut for new component: [amp-access-fewcents] paywall support by Fewcents
  examples/amp-access-fewcents.html
  extensions/amp-access-fewcents/0.1/amp-access-fewcents.css
  extensions/amp-access-fewcents/0.1/amp-access-fewcents.js
  extensions/amp-access-fewcents/0.1/fewcents-constants.js
  extensions/amp-access-fewcents/0.1/fewcents-impl.js
  extensions/amp-access-fewcents/0.1/test/test-amp-access-fewcents.js
  extensions/amp-access-fewcents/0.1/test/validator-amp-access-fewcents.html
  extensions/amp-access-fewcents/0.1/test/validator-amp-access-fewcents.out
  extensions/amp-access-fewcents/amp-access-fewcents.md
Labels: WG: caching

#37341 small build cleanup: move closure devDep to validator folder
  package-lock.json
  package.json
  validator/build.py
  validator/package-lock.json
  validator/package.json
Labels: WG: infra, WG: performance

#37453 Add descriptive names to all validator reference points.
  extensions/amp-base-carousel/validator-amp-base-carousel.protoascii
  extensions/amp-carousel/validator-amp-carousel.protoascii
  extensions/amp-live-list/0.1/test/validator-amp-live-list.out
  extensions/amp-live-list/validator-amp-live-list.protoascii
  extensions/amp-next-page/validator-amp-next-page.protoascii
  extensions/amp-selector/validator-amp-selector.protoascii
  extensions/amp-story/validator-amp-story.protoascii
Labels: WG: caching

#36234 ✨ Allow `importance` attribute on `amp-img` and SSR'ed `amp-img > img`
  validator/validator-main.protoascii
Labels: WG: caching

#37442 ✨ [AMP Story Paywall] Create the paywall extension with boilerplate code
  build-system/compile/bundles.config.extensions.json
  build-system/test-configs/config.js
  examples/amp-story-subscriptions/amp-story-subscriptions.html
  extensions/amp-story-subscriptions/0.1/amp-story-subscriptions.css
  extensions/amp-story-subscriptions/0.1/amp-story-subscriptions.js
  extensions/amp-story-subscriptions/0.1/test/test-amp-story-subscriptions.js
  extensions/amp-story-subscriptions/0.1/test/validator-amp-story-subscriptions.html
  extensions/amp-story-subscriptions/0.1/test/validator-amp-story-subscriptions.out
  extensions/amp-story-subscriptions/OWNERS
  extensions/amp-story-subscriptions/validator-amp-story-subscriptions.protoascii
Labels: WG: caching

#37502 🐛 [amp story shopping] shopping CTA label fix
  extensions/amp-story-page-attachment/0.1/amp-story-open-page-attachment.js
Labels: P1: High Priority, WG: stories

#37515 ♻️ ✅ [amp story shopping] Move i18n CTA label logic into shopping-attachment component
  extensions/amp-story-page-attachment/0.1/amp-story-open-page-attachment.js
  extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js
  extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-attachment.js
Labels: P1: High Priority, WG: stories

#37527 ♻️ [amp story shopping] Rename tag-id to product-id
  examples/amp-story/amp-story-shopping.html
  examples/amp-story/shopping/remote.json
  examples/visual-tests/amp-story/amp-story-shopping-lang-de.html
  examples/visual-tests/amp-story/amp-story-shopping.html
  extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js
  extensions/amp-story-shopping/0.1/amp-story-shopping-config.js
  extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js
  extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-attachment.js
  extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-config.js
  extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-tag.js
  extensions/amp-story/1.0/amp-story-store-service.js
Labels: P1: High Priority, WG: stories, Type: Refactoring
