Repository ampproject/amphtml, pull requests merged in 2022-02, with the labels that each got.

#37387 tslint: ban non-standard ecmascript features
  .eslintrc.js
  build-system/server/new-server/transforms/utilities/lazy.ts
  build-system/tasks/performance/print-report.js
Labels: WG: performance, WG: bento

#37561 src/preact: use URL instead of parseUrlDeprecated
  src/preact/component/3p-frame.js
Labels: WG: bento

#37579 🖍️ [amp story page attachment] Box shadow on header
  extensions/amp-story-page-attachment/0.1/amp-story-draggable-drawer-header.css
Labels: WG: stories

#37463 ♻️ typecheck: src/preact/components
  src/3p-frame.d.ts
  src/core/amp-globals.d.ts
  src/core/constants/loading-instructions.js
  src/core/types/index.js
  src/preact/compat.js
  src/preact/component/3p-frame.js
  src/preact/component/component.type.js
  src/preact/component/contain.jsx
  src/preact/component/iframe.js
  src/preact/component/intersection-observer.js
  src/preact/component/renderer.js
  src/preact/component/types.d.ts
  src/preact/component/wrapper.js
  src/preact/context.tsx
  src/preact/contextprops.js
  src/preact/hooks/useLocalStorage.js
  src/preact/storybook/Context.js
  src/preact/storybook/Hooks.js
  src/preact/storybook/Wrappers.js
  src/preact/tsconfig.json
  src/preact/utils.js
  src/preact/utils/docInfo.js
  src/preact/utils/platform.js
  src/preact/utils/url.js
  src/url.d.ts
Labels: WG: bento

#37569 🏗 Use locally built validator during `amp validate-html-fixtures`
  build-system/pr-check/checks.js
  build-system/pr-check/validator-tests.js
  build-system/tasks/validate-html-fixtures.js
  build-system/test-configs/config.js
Labels: WG: infra, WG: caching

#37619 R1: schedule amp-bind targets
  src/custom-element.js
  test/unit/test-custom-element-v1.js
Labels: WG: runtime, WG: performance

#37673 🏗 Make visual tests depend on module build
  build-system/pr-check/module-build.js
Labels: WG: infra

#37676 🐛added optional extention matching for dependency remap when bundling
  build-system/tasks/helpers.js
Labels: WG: infra

#37671 🐛 compiler.js buildDoms: ensure behavior matches browser
  examples/compiler-hydration.html
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-carousel/0.1/test/test-scrollable-carousel.js
  extensions/amp-carousel/0.1/test/test-slidescroll.js
  extensions/amp-fit-text/0.1/test/test-amp-fit-text.js
  src/core/dom/style.js
  test/integration/test-video-manager.js
  test/unit/builtins/test-amp-layout.js
  test/unit/compiler/test-builders.js
  test/unit/test-fixed-layer.js
  testing/helpers/index.js
Labels: Type: Bug, WG: performance, Type: Performance

#37646 🚀 🚀 🚀 amp-carousel ssr: allow render without JS 🚀 🚀 🚀
  examples/compiler-hydration.html
  extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
  extensions/amp-carousel/0.1/build-dom.js
  extensions/amp-carousel/0.1/slidescroll.js
  extensions/amp-fit-text/0.1/test/test-amp-fit-text.js
  src/compiler/builders.ts
  src/core/dom/style.js
  test/unit/core/dom/test-style.js
  test/unit/test-fixed-layer.js
  test/unit/test-friendly-iframe-embed.js
  testing/helpers/index.js
Labels: WG: performance, Component: amp-carousel

#37719 Validator rollup
  extensions/amp-mustache/validator-amp-mustache.protoascii
Labels: WG: caching

#37723 🏗 Fix local change detection in unit tests
  build-system/tasks/runtime-test/helpers-unit.js
Labels: WG: infra

#37666 ✅ [amp-google-read-aloud-player] Adds validator and examples for `amp-google-read-aloud-player` extension
  examples/amp-google-read-aloud-player/amp-google-read-aloud-player.amp.html
  extensions/amp-google-read-aloud-player/0.1/test/validator-amp-google-read-aloud-player.html
  extensions/amp-google-read-aloud-player/0.1/test/validator-amp-google-read-aloud-player.out
  extensions/amp-google-read-aloud-player/amp-google-read-aloud-player.md
  extensions/amp-google-read-aloud-player/validator-amp-google-read-aloud-player.protoascii
Labels: WG: caching

#37736 [amp story shopping] bring back images to example
  examples/amp-story/amp-story-shopping.html
Labels: P1: High Priority, WG: stories

#37718 Sync for validator cpp engine and cpp htmlparser
  validator/cpp/engine/validator-internal.cc
Labels: WG: caching

#37744 🐛 [amp story shopping tag] Call To Initialize listeners
  extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js
Labels: Type: Bug, P1: High Priority, WG: stories

#37747 amp-script: warn with zero width or height
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
Labels: Type: Bug, WG: performance, Component: amp-script

#37748 ✨[amp story shopping] Update values in examples to be numbers instead of strings
  examples/amp-story/amp-story-shopping.html
  examples/amp-story/shopping/remote.json
  examples/visual-tests/amp-story/amp-story-shopping-lang-de.html
  examples/visual-tests/amp-story/amp-story-shopping-rtl.html
  examples/visual-tests/amp-story/amp-story-shopping.html
  extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-config.js
Labels: P1: High Priority, Type: Feature Request, WG: stories

#37360 ✨ [bento-list] Implemented bento-list component
  build-system/compile/bundles.config.extensions.json
  build-system/test-configs/dep-check-config.js
  build-system/test-configs/forbidden-terms.js
  extensions/amp-autocomplete/0.1/amp-autocomplete.js
  extensions/amp-list/0.1/amp-list.js
  extensions/amp-list/1.0/amp-list.css
  extensions/amp-list/1.0/amp-list.js
  extensions/amp-list/1.0/base-element.js
  extensions/amp-list/1.0/component.js
  extensions/amp-list/1.0/component.jss.js
  extensions/amp-list/1.0/component.type.js
  extensions/amp-list/1.0/storybook/Basic.amp.js
  extensions/amp-list/1.0/storybook/Basic.js
  extensions/amp-list/1.0/test/test-amp-list.js
  extensions/amp-list/1.0/test/test-component.js
  extensions/amp-list/1.0/test/utils.js
  extensions/amp-render/1.0/amp-render.js
  extensions/amp-render/1.0/shared/amp-fetch-utils.js
  src/batched-json.js
  src/core/dom/layout/types.d.ts
  src/core/dom/layout/viewport-observer.js
  src/preact/component/intersection-observer.js
  src/preact/component/value-ref.ts
  src/preact/hooks/useInfiniteQuery.ts
  src/preact/hooks/useLocalStorage.ts
  src/preact/hooks/useStateSafe.ts
  src/preact/index.js
  src/preact/logger.js
  src/service/template-impl.js
  test/unit/core/dom/layout/test-viewport-observer.js
Labels: Component: amp-list, WG: bento

#37712 ✨ [amp-story] Enables volume=0 and sets noaudio to be an alias for volume=0
  extensions/amp-story/1.0/amp-story-page.js
  extensions/amp-story/1.0/media-pool.js
  extensions/amp-story/1.0/test/validator-amp-story-video-error.html
  extensions/amp-story/1.0/test/validator-amp-story-video-error.out
  extensions/amp-video/0.1/amp-video.md
  extensions/amp-video/validator-amp-video.protoascii
Labels: WG: caching

#37752 ✨ 🖍 [amp story shopping] Display in desktop supports-landscape
  examples/visual-tests/amp-story/amp-story-shopping-landscape.html
  extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.css
  test/visual-diff/visual-tests.jsonc
Labels: P1: High Priority, Type: Feature Request, WG: stories
