Repository ampproject/amphtml, pull requests merged in 2022-04, with the labels that each got.

#37977 🐛 [amp story captions] Close voice tags in example html .vtt files
  examples/amp-story/video/ecommerce.vtt
  examples/amp-story/video/gmail.vtt
  examples/amp-story/video/p1.vtt
  examples/amp-story/video/stamp.vtt
Labels: Type: Bug, P1: High Priority, WG: stories

#37993 [amp-story-shopping] Add `productDescription` to all templates and max length
  examples/amp-story/amp-story-shopping.html
  examples/amp-story/shopping/remote.json
  examples/visual-tests/amp-story/amp-story-shopping-landscape.html
  examples/visual-tests/amp-story/amp-story-shopping-lang-de.html
  examples/visual-tests/amp-story/amp-story-shopping-rtl.html
  examples/visual-tests/amp-story/amp-story-shopping.html
  extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js
  extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-config.js
Labels: P1: High Priority, WG: stories

#38063 amp-script: callFunction should handle when workerDom failed to init
  extensions/amp-script/0.1/amp-script.js
  extensions/amp-script/0.1/test/unit/test-amp-script.js
Labels: Type: Bug, Component: amp-list, Component: amp-script

#35342 ✨ Bento `amp-audio`
  build-system/compile/bundles.config.extensions.json
  extensions/amp-audio/1.0/amp-audio.css
  extensions/amp-audio/1.0/amp-audio.js
  extensions/amp-audio/1.0/base-element.js
  extensions/amp-audio/1.0/component.js
  extensions/amp-audio/1.0/component.type.js
  extensions/amp-audio/1.0/storybook/Basic.amp.js
  extensions/amp-audio/1.0/storybook/Basic.js
  extensions/amp-audio/1.0/test/test-amp-audio.js
  extensions/amp-audio/1.0/test/test-component.js
  extensions/amp-audio/1.0/test/validator-amp-audio.html
  extensions/amp-audio/1.0/test/validator-amp-audio.out
  extensions/amp-audio/amp-audio.md
  extensions/amp-audio/validator-amp-audio.protoascii
  src/preact/amp-base-element.js
  validator/testdata/amp4ads_feature_tests/script_release_versions.out
Labels: WG: caching, WG: bento

#37982 Enable server-side rendering for amp-audio
  extensions/amp-audio/0.1/amp-audio.js
  extensions/amp-audio/0.1/test/test-amp-audio.js
  extensions/amp-audio/0.1/test/validator-amp-audio.html
  extensions/amp-audio/0.1/test/validator-amp-audio.out
  extensions/amp-audio/validator-amp-audio.protoascii
  src/core/static-layout.js
  validator/validator-main.protoascii
Labels: WG: caching

#37967 ✨ [amp story captions] `style-preset` attribute with styles
  build-system/test-configs/dep-check-config.js
  examples/amp-story/amp-story-captions.html
  extensions/amp-story-captions/0.1/amp-story-captions-presets.css
  extensions/amp-story-captions/0.1/amp-story-captions.css
  extensions/amp-story-captions/0.1/amp-story-captions.js
  extensions/amp-story-captions/0.1/test/test-amp-story-captions.js
  extensions/amp-story-captions/0.1/test/validator-amp-story-captions.html
  extensions/amp-story-captions/0.1/test/validator-amp-story-captions.out
  extensions/amp-story-captions/0.1/track-renderer.js
  extensions/amp-story-captions/validator-amp-story-captions.protoascii
Labels: WG: caching

#37863 ✨ [Bento] Implemented bento-pan-zoom component
  build-system/compile/bundles.config.extensions.json
  extensions/amp-list/1.0/test/test-amp-list.js
  extensions/amp-list/1.0/test/test-component.js
  extensions/amp-list/1.0/test/utils.js
  extensions/amp-pan-zoom/1.0/amp-pan-zoom.css
  extensions/amp-pan-zoom/1.0/amp-pan-zoom.js
  extensions/amp-pan-zoom/1.0/base-element.js
  extensions/amp-pan-zoom/1.0/component-ts.tsx
  extensions/amp-pan-zoom/1.0/component.js
  extensions/amp-pan-zoom/1.0/component.jss.js
  extensions/amp-pan-zoom/1.0/component.type.js
  extensions/amp-pan-zoom/1.0/hooks/usePanZoomState.ts
  extensions/amp-pan-zoom/1.0/storybook/Basic.amp.js
  extensions/amp-pan-zoom/1.0/storybook/Basic.js
  extensions/amp-pan-zoom/1.0/test/test-amp-pan-zoom.js
  extensions/amp-pan-zoom/1.0/test/test-component.js
  package-lock.json
  package.json
  src/gesture-recognizers.d.ts
  src/gesture-recognizers.js
  src/gesture.js
  src/preact/component/value-ref.ts
  src/preact/hooks/useResizeObserver.ts
  src/preact/index.js
  test/unit/test-gesture.js
  testing/helpers/cleanHtml.ts
Labels: WG: components, WG: caching, WG: bento

#38119 📖 [amp story shopping] CTA casing in docs. Remove "draft" from doc metadata.
  extensions/amp-story-shopping/amp-story-shopping.md
Labels: Related to: Documentation, P1: High Priority, WG: stories
