Repository ampproject/amphtml, pull requests merged in 2023-07, with the labels that each got.

#38723 ✨ [RTC-Config]: add source_url and title to real-time-config global macros allowlist
  src/service/real-time-config/real-time-config-impl.js
  test/unit/test-real-time-config.js
Labels: WG: monetization, P1: High Priority, Type: Feature Request, WG: components

#39211 ♻️🐛 [Trusted Types] Make AmpWorker Trusted Types compatible
  src/web-worker/amp-worker.js
Labels: P1: High Priority, Type: Feature Request, WG: runtime

#39273 ♻️🐛 [Trusted Types] Make createExtensionScript's policy regex less permissive
  src/service/extension-script.js
Labels: Type: Feature Request, WG: runtime, P2: Soon
